[build]
  # Dossier contenant le code source Next.js
  base = "frontend"
  
  # Commande de build Next.js
  command = "npm run build"
  
  # Dossier de sortie après build
  publish = "out"
  
  # Dossier des fonctions serverless
  functions = "netlify/functions"

[build.environment]
  # Version Node.js compatible avec Next.js 13
  NODE_VERSION = "18"
  
  # Variables d'environnement pour les fonctions
  # SUPABASE_URL = "your-supabase-url"
  # SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"

# Redirections pour SPA Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache des assets statiques
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
