# Désactiver la détection automatique des variables d'environnement
[variables]
# Ne pas inclure les variables vides dans le Dockerfile

[phases.setup]
nixPkgs = ["nodejs_22"]
# Pas de variables ENV dans le setup

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"
