-- Batch 5 - Section 2/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '1c87087f-5aab-4e32-9733-1ff5f9529c8a',
        'B Cash : Une banque 100 % mobile pour les exclus du système bancaire au Gabon',
        'La BCEG lance une néo-banque totalement mobile, B Cash, pour permettre aux personnes exclues du système bancaire, notamment dans l’économie informelle, d’accéder plus facilement aux services financiers.',
        'https://directinfosgabon.com/b-cash-une-banque-100-mobile-pour-les-exclus-du-systeme-bancaire-au-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '60093d4c-d1f6-47bf-994a-b51f09153a85',
        'Digitalisation et souveraineté alimentaire : Le Gabon explore de nouveaux partenariats stratégiques',
        'Le Gabon cherche à renforcer sa souveraineté alimentaire et sa digitalisation en nouant de nouveaux partenariats stratégiques avec des entreprises internationales, sous la direction de son président.',
        'https://gabonactu.com/blog/2025/06/24/digitalisation-et-souverainete-alimentaire-le-gabon-explore-de-nouveaux-partenariats-strategiques/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f021a85-a951-4ee3-8c80-462d652c1056',
        'RdB : Quand les tambours traditionnels étouffent la voix politique',
        'Un rassemblement politique a été reporté à cause de rituels traditionnels, illustrant comment des pratiques culturelles peuvent influencer et même limiter la liberté d’expression politique.',
        'https://www.gabonreview.com/rdb-quand-les-tambours-traditionnels-etouffent-la-voix-politique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5fb70139-d694-417e-8104-a3d4fa64a3ec',
        'Gabon : l’Assemblée générale constitutive des Bâtisseurs reportée au 5 juillet 2025',
        'La réunion constitutive des Bâtisseurs a été reportée au 5 juillet 2025, repoussant ainsi la création officielle de cette nouvelle organisation.',
        'https://gabonmediatime.com/gabon-lassemblee-generale-constitutive-des-batisseurs-reportee-au-5-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c813b398-3ae1-473a-b002-5fee060a7007',
        'Déguerpissement sans relogement : du « Sadisme d’État » selon Bilie-By-Nze !',
        'Le délogement sans relogement de la population à Libreville est dénoncé comme une forme de violence d’État, révélant un mépris envers les droits des citoyens.',
        'https://gabonmediatime.com/deguerpissement-sans-relogement-du-sadisme-detat-selon-bilie-by-nze/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01f31cab-140b-4d56-bd94-0ed9856406a8',
        'Note souveraine de Fitch : le Gabon prend acte et reste mobilisé pour renforcer sa crédibilité financière',
        'Fitch a maintenu la note souveraine du Gabon, soulignant la nécessité pour le pays de rester mobilisé afin de renforcer sa crédibilité financière.',
        'https://gabonmediatime.com/note-souveraine-de-fitch-le-gabon-prend-acte-et-reste-mobilise-pour-renforcer-sa-credibilite-financiere/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8cad0490-fe33-4673-bded-32a4f1e5bbd2',
        'Distinction: un Gabonais sacré meilleure moyenne de la Francophonie en expertise comptable',
        'Un étudiant gabonais, Evrard Moumbeki, a obtenu la meilleure moyenne en expertise comptable parmi les candidats de la Francophonie lors d''une cérémonie à Paris en juin 2025, distinction saluée pour sa rigueur et sa persévérance.',
        'https://agpgabon.ga/distinction-un-gabonais-sacre-meilleure-moyenne-de-la-francophonie-en-expertise-comptable/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0a900c6-077d-48c4-83f5-2b7e68ce9e39',
        'Lutte contre la pêche illicite : le Gabon active l’AMREP',
        'Le Gabon a lancé un atelier pour mettre en œuvre l’AMREP, un accord visant à lutter contre la pêche illicite, en impliquant plusieurs ministères et partenaires ONG.',
        'https://agpgabon.ga/lutte-contre-la-peche-illicite-le-gabon-active-lamrep/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48523440-4094-475a-bd63-e5fbe4fe3c90',
        'Formation ferroviaire : 15 jeunes Gabonais diplômés du programme « Tremplin » porté par Setrag et Eramet',
        '15 jeunes Gabonais ont obtenu leur diplôme à la fin du programme de formation « Tremplin » lancé par la société Setrag, marquant une première réussite dans cette initiative visant à renforcer les compétences dans le secteur ferroviaire.',
        'https://www.gabonews.com/fr/actus/societe/article/formation-ferroviaire-15-jeunes-gabonais-diplomes',
        'Gabonews',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1977ca2c-1875-48d9-b302-1baf8a4ee1ae',
        'Gabon : l’Assemblée générale constitutive des Bâtisseurs reportée au 5 juillet 2025',
        'La réunion de l''Assemblée générale constitutive des Bâtisseurs, initialement prévue, a été reportée au 5 juillet 2025.',
        'https://gabonmediatime.com/gabon-lassemblee-generale-constitutive-des-batisseurs-reportee-au-5-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '501b1cba-c6f7-47a4-8d5a-210b4ce948e7',
        'Déguerpissement sans relogement : du « Sadisme d’État » selon Bilie-By-Nze !',
        'Le gouvernement gabonais aurait expulsé des squatters sans leur fournir de solutions de relogement, ce qui suscite des critiques sur la gestion des relogements et la manière dont l’État traite ces populations vulnérables.',
        'https://gabonmediatime.com/deguerpissement-sans-relogement-du-sadisme-detat-selon-bilie-by-nze/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8447929d-6bd4-44b5-b994-e89888ad196d',
        'Note souveraine de Fitch : le Gabon prend acte et reste mobilisé pour renforcer sa crédibilité financière',
        'Fitch confirme la stabilité de la note souveraine du Gabon, soulignant sa volonté de renforcer sa crédibilité financière malgré les défis économiques.',
        'https://gabonmediatime.com/note-souveraine-de-fitch-le-gabon-prend-acte-et-reste-mobilise-pour-renforcer-sa-credibilite-financiere/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9863f59-58c1-42a0-8ce8-410205f96b03',
        'Chine/Chongqing : un exemple à suivre pour les villes africaines',
        'L''article montre que la ville chinoise de Chongqing, même construite en terrain montagneux, a su se développer grâce à une urbanisation innovante, et peut servir d''exemple pour le développement durable des villes en Afrique.',
        'https://agpgabon.ga/chine-chongqing-un-exemple-a-suivre-pour-les-villes-africaines/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f9702bc-013d-4f5e-8c37-c2b307073288',
        'Emballages plastiques : le Gabon accorde 3 mois aux grandes surfaces pour les bannir',
        'Le gouvernement gabonais donne trois mois aux grandes surfaces pour arrêter d’utiliser les sacs plastiques à usage unique, face à une collecte quotidienne de 36 tonnes de ces sacs dans la région de Libreville.',
        'https://agpgabon.ga/emballages-plastiques-le-gabon-accorde-3-mois-aux-grandes-surfaces-pour-les-bannir/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4f450d9-a966-417b-8f5a-762f3ab7666f',
        'Formation ferroviaire: 15 jeunes Gabonais diplômés du programme « Tremplin » porté par Setrag et Eramet',
        'Quinze jeunes Gabonais ont obtenu leur diplôme dans le cadre du programme de formation ferroviaire « Tremplin », une initiative menée par Setrag et Eramet pour développer les compétences locales dans le secteur ferroviaire.',
        'https://vxp241.com/2025/06/24/formation-ferroviaire-15-jeunes-gabonais-diplomes-du-programme-tremplin-porte-par-setrag-et-eramet/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd14e64da-2e4d-4f54-8423-d7bb0c2f9877',
        'Coupe Baby Champion : Club Suprême Taekwondo a survolé la compétition',
        'Lors de la 28ᵉ édition du « Baby Champion » de taekwondo à Libreville, le club Suprême Taekwondo a dominé la compétition en remportant plusieurs victoires lors de cet événement sportif majeur.',
        'https://gabonactu.com/blog/2025/06/24/coupe-baby-champion-club-supreme-taekwondo-a-survole-la-competition/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fcf9a8e4-07c0-4925-a0e8-ea23f4193cc2',
        '« 5ème République » : Entre pouvoir et opposition, Nicole Assélé joue à l’équilibriste',
        'Nicole Assélé affirme sa neutralité politique dans le contexte actuel de la transition au Gabon, cherchant à équilibrer entre le pouvoir en place et l''opposition.',
        'https://gabonactu.com/blog/2025/06/24/5eme-republique-entre-pouvoir-et-opposition-nicole-assele-joue-a-lequilibriste/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14acd205-3129-4e59-a4ae-66a84fdeb346',
        'Haut-Ogooué : la plateforme Horizon resserre les liens autour de sa Coordinatrice provinciale',
        'Les membres de la plateforme Horizon du Haut-Ogooué ont célébré leur culture et leur unité lors d''une rencontre conviviale, en partageant des danses, des chants et des mets traditionnels sous la direction de leur coordinatrice.',
        'https://www.gabonews.com/fr/actus/politique/article/haut-ogooue-la-plateforme-horizon-resserre-les',
        'Gabonews',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'da4c168d-5733-497b-9bbb-a7710cd7da4c',
        'Gabon : l''Assemblée générale du Rassemblement des Bâtisseurs reportée au 5 juillet',
        'L’Assemblée générale du Rassemblement des Bâtisseurs, prévue initialement le 28 juin 2025, a été reportée au 5 juillet afin d’éviter la coïncidence avec des cérémonies traditionnelles dans la province de l’Estuaire.',
        'https://www.gabonews.com/fr/actus/politique/article/gabon-l-assemblee-generale-du-rassemblement-des',
        'Gabonews',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb689721-5731-473f-835e-68990b6c21cb',
        'Axel Joël Iba-Ba : Un génie aux mille talents s''est éteint',
        'Axel Joël Iba-Ba, un styliste et artiste gabonais reconnu dans le monde de la mode, de la musique et de la culture africaine, est décédé à l’âge de 49 ans.',
        'https://www.gabonews.com/fr/actus/necrologie/article/axel-joel-iba-ba-un-genie-aux-mille-talents-s-est',
        'Gabonews',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ebb61b4-ce0d-4fa2-9a4c-425d2d232364',
        'Gabon : la ministre Armande Longo-Moulengui prend langue avec les entités sous tutelle',
        'La ministre de la Jeunesse, des Sports et du Rayonnement culturel a commencé à rencontrer les responsables des différentes entités sous sa tutelle pour mieux connaître leurs réalités et améliorer leur fonctionnement.',
        'https://agpgabon.ga/gabon-la-ministre-armande-longo-moulengui-prend-langue-avec-les-entites-sous-tutelle/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0352b25e-8558-42ce-9aff-196834e2648b',
        'Petite enfance : vers une réorganisation structurée entre Affaires Sociales et Éducation Nationale',
        'L''article explique qu''une réforme est en cours pour mieux coordonner les efforts entre les secteurs des affaires sociales et de l''éducation nationale afin d''améliorer la prise en charge de la petite enfance.',
        'https://kongossanews.info/petite-enfance-vers-une-reorganisation-structuree-entre-affaires-sociales-et-education-nationale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5c348f0-9239-42fc-81ce-393a865dd457',
        'Guy Nzouba Ndama et l’audio menaçant envers les membres de sa famille biologique',
        'Une polémique sur les réseaux sociaux oppose Guy Nzouba Ndama à la Fondation anglaise Fatima, soulevant des questions sur la liberté d’expression et la gestion des critiques en ligne.',
        'https://kongossanews.info/guy-nzouba-ndama-laudio-polemique-qui-secoue-les-reseaux-sociaux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '556dba73-67e8-4b96-9667-e95c281d871c',
        'Report de l’Assemblée Générale du Parti des Bâtisseurs : une décision pour honorer les traditions culturelles',
        'Le Parti des bâtisseurs a tenu une assemblée générale pour discuter de l''importance de préserver et honorer les traditions culturelles locales à travers ses actions et décisions.',
        'https://kongossanews.info/report-de-lassemblee-generale-du-parti-des-batisseurs-une-decision-pour-honorer-les-traditions-culturelles/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4228d1db-3ea5-42c9-98a7-57968e6a07f7',
        'Publié le 24 / 06 / 2025',
        'Le comité d’organisation a justifié le report de la création du parti politique, expliquant des raisons internes et stratégiques qui nécessitent encore du temps pour finaliser les préparatifs.',
        'https://union.sonapresse.com/fr/les-batisseurs-le-comite-dorganisation-justifie-le-report-de-la-creation-du-parti-politique',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6cad2ba-81d0-40f4-b4f1-3312d242df4b',
        'Publié le 24 / 06 / 2025',
        'Oci Onanga Ndiaye souhaite encourager une collaboration renforcée entre les États membres pour favoriser le développement et la synergie régionale.',
        'https://union.sonapresse.com/fr/oci-onanga-ndiaye-favorable-une-synergie-des-etats-membres',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d143ed4-8cc5-426e-bbb3-693a7fa5be2e',
        'Publié le 24 / 06 / 2025',
        'Les députés sénégalais ont accepté de transférer davantage de compétences de l’État aux collectivités locales afin de renforcer leur autonomie et leur capacité de gestion.',
        'https://union.sonapresse.com/fr/transfert-des-competences-de-letat-aux-collectivites-locales-les-deputes-emboitent-le-pas-aux',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f02f449-72e4-4fec-900c-3a39161766cb',
        'Gabon : l’Arcep lance ses activités dans la ville d’Oyem',
        'L''Arcep a lancé ses activités à Oyem, en rencontrant les opérateurs économiques locaux pour leur présenter ses services et leur indiquer qu''il est désormais présent dans la région.',
        'https://agpgabon.ga/gabon-larcep-lance-ses-activites-dans-la-ville-doyem/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb18bb31-a58b-4454-8bc8-5dcc691422e4',
        'Gabon/ Mouila : 23 impétrants du BEPTM valident leurs acquis professionnels',
        'Vingt-trois élèves en formation professionnelle ont validé leurs compétences dans les filières de comptabilité-gestion et secrétariat-bureautique après avoir soutenu leurs rapports de stage, marquant la fin de leur cycle de quatre années d''études.',
        'https://agpgabon.ga/gabon-mouila-23-impetrants-du-beptm-valident-leurs-acquis-professionnels/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb249060-c44f-4896-8a36-96b56c59a1fa',
        'Petite enfance : vers une réorganisation structurée entre Affaires Sociales et Éducation Nationale',
        'L''article explique la volonté de réorganiser de manière structurée la coordination entre les affaires sociales et l''éducation nationale dans la petite enfance pour mieux répondre aux besoins des jeunes enfants.',
        'https://kongossanews.info/petite-enfance-vers-une-reorganisation-structuree-entre-affaires-sociales-et-education-nationale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '259d8357-8085-4faa-85ee-9c9157df71dc',
        'Guy Nzouba Ndama et l’audio menaçant envers les membres de sa famille biologique',
        'Une polémique a éclaté sur les réseaux sociaux autour de Guy Nzouba Ndama, suscitant des débats sur ses propos et leur impact dans le contexte ivoirien.',
        'https://kongossanews.info/guy-nzouba-ndama-laudio-polemique-qui-secoue-les-reseaux-sociaux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '038fc4fc-9427-438b-abc1-0aca8f06b1b1',
        'Report de l’Assemblée Générale du Parti des Bâtisseurs : une décision pour honorer les traditions culturelles',
        'L''assemblée générale du Parti des Bâtisseurs a décidé de mettre en avant les traditions culturelles pour renforcer l''unité et le développement de la communauté.',
        'https://kongossanews.info/report-de-lassemblee-generale-du-parti-des-batisseurs-une-decision-pour-honorer-les-traditions-culturelles/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ee96159-0c50-4da5-be23-4dcf1b24306f',
        'Publié le 24 / 06 / 2025',
        'Le comité d’organisation a justifié le report de la création du parti politique en expliquant qu''il est nécessaire de mieux préparer la structuration et la concertation avant de lancer officiellement le parti.',
        'https://union.sonapresse.com/fr/les-batisseurs-le-comite-dorganisation-justifie-le-report-de-la-creation-du-parti-politique',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f4ed044-fcf7-4155-8876-c1adf535e7f1',
        'Publié le 24 / 06 / 2025',
        'On a souligné l''importance d''une meilleure coopération entre les États membres pour renforcer l''intégration régionale et promouvoir le développement économique en Afrique.',
        'https://union.sonapresse.com/fr/oci-onanga-ndiaye-favorable-une-synergie-des-etats-membres',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e14edbe9-a581-4c22-b069-784a466d5a52',
        'Publié le 24 / 06 / 2025',
        'Les députés sénégalais soutiennent le transfert des compétences de l’État aux collectivités locales pour renforcer leur autonomie dans la gestion des services publics.',
        'https://union.sonapresse.com/fr/transfert-des-competences-de-letat-aux-collectivites-locales-les-deputes-emboitent-le-pas-aux',
        'L''union',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ed047f5-2456-4796-83e2-42c2be556ebb',
        'Informelle : B-Cash, l’offre solidaire de BCEG',
        'La BCEG propose une offre solidaire de cash informel pour aider les personnes en difficulté financière.',
        'https://mediapostegabon.com/informelle-b-cash-loffre-solidaire-de-bceg/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bae86574-3244-4e9c-8f95-b19434df49c4',
        'Justice : I.N. à la barre pour trafic d’ivoire le 27 juin 2025 Logement au Gabon : la SNI aligne sa stratégie sur la vision du P...',
        'Une personne accusée de trafic de drogue doit comparaître devant la justice en Côte d''Ivoire le 27 juin 2025.',
        'https://mediapostegabon.com/justice-i-n-a-la-barre-pour-trafic-divoire-le-27-juin-2025/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '542642d0-b03b-4049-a779-8e64bfb6dea2',
        'Au Gabon, comment Oligui Nguema bouleverse le jeu politique avant les législatives',
        'Le président gabonais prépare la création de sa propre formation politique dans un contexte de recomposition du paysage partisan, suite à une nouvelle loi sur les partis.',
        'https://www.jeuneafrique.com/1700302/politique/au-gabon-comment-oligui-nguema-bouleverse-le-jeu-politique-avant-les-legislatives/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '061f6ccb-602c-435d-b39d-e85d8c117404',
        'BGFIBANK ébranlé par une décision de justice le condamnant à verser 900 millions de FCFA à un ex cadre pour licenciement abusif',
        'Une décision de justice oblige BGFIBANK à verser 900 millions de FCFA à un ancien cadre, après un licenciement jugé abusif.',
        'https://gabonactu.com/blog/2025/06/25/bgfibank-ebranle-par-une-decision-de-justice-le-condamnant-a-verser-900-millions-de-fcfa-a-un-ex-cadre-pour-licenciement-abusif/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92b9c9e5-7e3a-4879-9373-08388acc1ed8',
        '"Le 30 mai 2025 restera une date charnière pour l''économie gabonaise"Thibaut C. Mambenda Yamba',
        'Le gouvernement gabonais a décidé d’interdire l’exportation du manganèse brut à partir de 2029, afin de renforcer sa souveraineté industrielle en tant que deuxième producteur mondial de ce minerai stratégique.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/le-30-mai-2025-restera-une-date-charniere-pour-l',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25ce9b48-b2ea-484b-8eb7-99e19cf90b7a',
        'Gabon: en lançant son parti, Brice Clothaire Oligui Nguema peut-il perdre son mandat ?',
        'Le lancement du nouveau parti du président Brice Clotaire Oligui Nguema, initialement prévu ce samedi à Libreville, a été reporté au 5 juillet.',
        'https://www.rfi.fr/fr/afrique/20250625-gabon-en-lan%C3%A7ant-son-parti-brice-clothaire-oligui-nguema-peut-il-perdre-son-mandat',
        'RFI',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '778cff63-358a-44e7-a480-72c1780cc8e3',
        'Gabon: en lançant son parti, Brice Clothaire Oligui Nguema peut-il perdre son mandat ?',
        'Le lancement du nouveau parti du président gabonais Brice Clotaire Oligui Nguema, initialement prévu pour ce samedi, a été reporté au 5 juillet.',
        'https://www.rfi.fr/fr/afrique/20250625-gabon-en-lan%C3%A7ant-son-parti-brice-clothaire-oligui-nguema-peut-il-perdre-son-mandat?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f651c289-3f2d-402a-b5b0-f4817b3843e8',
        'Gabon–Medef : une feuille de route sur deux ans pour accélérer l’industrialisation',
        'Un partenariat stratégique de deux ans entre le Gabon et MEDEF International vise à élaborer et mettre en œuvre une feuille de route pour accélérer le développement industriel durable dans le pays.',
        'https://directinfosgabon.com/gabon-medef-une-feuille-de-route-sur-deux-ans-pour-accelerer-lindustrialisation/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6980e499-bc9a-415c-ade3-48129dc3a91b',
        'Gabon : Le gouvernement relativise la confirmation de la note « CCC » par Fitch Ratings',
        'Malgré le maintien de la note « CCC » par Fitch Ratings, les autorités gabonaises estiment que les progrès politiques et économiques du pays peuvent permettre d''améliorer sa Situation financière à l''avenir.',
        'https://www.gabonreview.com/gabon-le-gouvernement-relativise-la-confirmation-de-la-note-ccc-par-fitch-ratings/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6bba3ad4-e6aa-41fb-a7fc-e64772ed60e7',
        'Ouverture du sommet d''Affaires États-Unis-Afrique : le Chef de l''État participe au dialogue de haut niveau',
        'Lors du 17e Sommet d''Affaires États-Unis-Afrique à Luanda, le président angolais a participé à la cérémonie d''ouverture, échangeant notamment avec la présidente du Corporate Council on Africa.',
        'https://www.gabonews.com/fr/actus/politique/article/ouverture-du-sommet-d-affaires-etats-unis-afrique',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5073a9c5-928f-4599-96ef-ebf1e694836b',
        'La Police touristique gabonaise en préparation !',
        'Le gouvernement gabonais met en place une Police Touristique, après une mission de benchmarking menée au Sénégal et au Maroc par des responsables ministériels et militaires pour s''inspirer des meilleures pratiques en sécurité touristique.',
        'https://www.gabonews.com/fr/actus/securite-207/article/la-police-touristique-gabonaise-en-preparation',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7232a770-ca74-45d4-9159-70a47ffc5512',
        'Gabon : les Awards de la Presse Gabonaise reportés au 4 juillet 2025',
        'La cérémonie des Awards de la Presse Gabonaise 2025, initialement prévue le 28 juin, est reportée au 4 juillet 2025 en raison d’un changement de date, avec des excuses du comité d’organisation pour ce délai.',
        'https://agpgabon.ga/gabon-les-awards-de-la-presse-gabonaise-reportes-au-4-juillet-2025/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd21b47bb-7a2a-4818-ae82-b0c05e09a1c5',
        'Nigéria/Afreximbank 2025 : lancement de la 32ᵉ Assemblée annuelle à Abuja',
        'Plus de 6 000 participants se réunissent à Abuja du 25 au 27 juin pour la 32e Assemblée annuelle d’Afreximbank, axée sur l’innovation, le commerce africain et la coopération régionale.',
        'https://agpgabon.ga/nigeria-afreximbank-2025-lancement-de-la-32%e1%b5%89-assemblee-annuelle-a-abuja/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74e32304-3748-4968-9675-c53298ffdd16',
        'Gabon/Route Bikélé-Bambouchine : les populations impactées invitées à une consultation publique ce jeudi',
        'Des représentants locaux ont organisé deux réunions pour informer et consulter les populations concernées par le projet de construction d’un contournement routier entre Bikélé et Bambouchine, dans le cadre du Plan national de développement.',
        'https://agpgabon.ga/gabon-route-bikele-bambouchine-les-populations-impactees-invitees-a-une-consultation-publique-ce-jeudi/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb1cb920-8299-4f19-857e-5c385de4e9a6',
        'De l''industrie pétrolière aux petits pots de confiture : le parcours atypique d''une entrepreneure Gabonaise',
        'Jessica Medza Allogo, ancienne ingénieure pétrolière gabonaise, a décidé en 2016 de se lancer dans la production artisanale de confitures à partir de produits locaux, valorisant ainsi le terroir et créant sa propre entreprise.',
        'https://www.bbc.com/afrique/articles/cg4r5q56qyko?xtor=AL-73-%5Bpartner%5D-%5Bflipboard%5D-%5Bheadline%5D-%5Bafrique%5D-%5Bbizdev%5D-%5Bisapi%5D',
        'Flipboard',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

