-- Batch 6 - Section 16/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '5929cdc0-f3fd-4d16-8abb-ca72d326b5a6',
        'Championnats du monde de natation : Noëlie Lacour termine 3e de sa série',
        'Noélie Lacour, nageuse gabonaise de 19 ans, a terminé 3e de sa série du 50 mètres nage libre aux championnats du monde à Singapour, ce qui lui a permis de se classer 57e sur 105 nageuses, mais elle n''a pas accédé à la suite de la compétition.',
        'https://agpgabon.ga/championnats-du-monde-de-natation-noelie-lacour-termine-3e-de-sa-serie/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41d8de3a-c1be-4b3c-a03d-7cfb6ca328da',
        'Woleu-Ntem : organisation d’un atelier d’appropriation du Régime social unique',
        'Un atelier s’est tenu à Oyem pour former les participants à la mise en œuvre et à la digitalisation du Régime social unique (RSU) afin de renforcer leurs capacités dans la gestion de la protection sociale non contributive.',
        'https://agpgabon.ga/woleu-ntem-organisation-dun-atelier-dappropriation-du-regime-social-unique/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9e61c15-18b8-42d2-8f62-32e49bfea8ac',
        'Turquie/Gabon : un accord signé pour une centrale thermique à gaz de 1 GW',
        'Un accord a été signé entre la Turquie et le Gabon pour construire et exploiter une centrale thermique à gaz de 1 gigawatt afin de renforcer la production d''électricité dans le pays.',
        'https://agpgabon.ga/turquie-gabon-un-accord-signe-pour-une-centrale-thermique-a-gaz-de-1-gw/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eb3abe91-d419-4653-931d-02b5507d2633',
        'Football : Shavy Babicka rejoint l’Etoile Rouge de Belgrade',
        'Le footballeur gabonais Shavy Babicka a signé un contrat de 4 ans avec l''Etoile Rouge de Belgrade, après avoir joué en France à Toulouse.',
        'https://agpgabon.ga/football-shavy-babicka-rejoint-letoile-rouge-de-belgrade/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e15d3c73-540f-46a3-b2b4-257f1c4379fd',
        'Ogooué-Ivindo/Législatives et Locales : peu d’engouement pour le dépôt des candidatures',
        'Le dépôt des candidatures pour les élections législatives et locales dans la région de l''Ogooué-Ivindo connaît une faible participation, quelques jours avant la date limite, avec peu de candidats qui se manifestent.',
        'https://agpgabon.ga/ogooue-ivindo-legislatives-et-locales-peu-dengouement-pour-le-depot-des-candidatures/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a3292551-4e07-417f-9dee-71672dbefdcc',
        'Passeport : le Gabon, champion de la CEMAC avec 58 destinations sans visa en 2025',
        'Le passeport gabonais devrait permettre d’accéder à 58 destinations sans visa d’ici 2025, consolidant ainsi la position du pays en tant que leader en Espace CEMAC.',
        'https://gabonmediatime.com/passeport-le-gabon-champion-de-la-cemac-avec-58-destinations-sans-visa-en-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeee669e-2cd9-4dbf-b600-b4a31402a673',
        'Cemac : le Gabon sollicite un report du Sommet de Libreville',
        'Le Gabon demande un rapport lors du sommet de la Communauté économique des États de l’Afrique centrale (CEEAC) pour faire le point sur ses engagements et ses avancées dans la mise en œuvre des décisions régionales.',
        'https://gabonmediatime.com/cemac-le-gabon-sollicite-un-report-du-sommet-de-libreville/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92f1d1ce-157c-47cb-b7db-4c4d6a042d16',
        'Fegahand : invalidation de la candidature de Nicole Asselé, le sport victime des amalgames politiques ?',
        'La candidature de Nicole Assélé a été invalidée, illustrant comment le sport devient souvent victime d''amalgames et de stratégies politiques dans le contexte gabonais.',
        'https://gabonmediatime.com/fegahand-invalidation-de-la-candidature-de-nicole-assele-le-sport-victime-des-amalgames-politiques/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a90b68ff-d519-4f22-a6c3-08203d074a68',
        'Élections législatives et locales 2025 / L’UDB de l’Estuaire mobilisée pour ratisser large',
        'L''UDHB de l''Estuaire se mobilise pour sensibiliser et mobiliser les électeurs en vue des élections législatives et locales de 2025, afin de maximiser la participation.',
        'https://kongossanews.info/elections-legislatives-et-locales-2025-ludb-de-lestuaire-mobilisee-pour-ratisser-large/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c590cf6-89f9-4039-857a-3bacae8a7475',
        'Accords Gabon-Turquie: Ce qu’il faut (absolument) retenir',
        'La signature de l''accord entre le Gabon et la Turquie vise à renforcer la coopération économique, commerciale et éducative entre les deux pays, avec des engagements concrets pour développer leurs relations bilatérales.',
        'https://kongossanews.info/accords-gabon-turquie-ce-quil-faut-absolument-retenir/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c2da97c3-c0de-457a-a0b6-31f0a546c4e6',
        'Brice Clotaire Oligui Nguema : Le bâtisseur obstiné du Gabon nouveau',
        'Brice Clotaire Oligui Nguema est présenté comme un bâtisseur obstiné et déterminé, jouant un rôle clé dans la reconstruction et le développement du Gabon.',
        'https://kongossanews.info/brice-clotaire-oligui-nguema-le-batisseur-obstine-du-gabon-nouveau/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab3ba642-6713-4c0b-9f0c-df99856d81cf',
        'Moyen-Ogooué/Mines : 24 expatriés récidivistes arrêtés pour trafic d’or à Ndjolé',
        'Vingt-quatre expatriés, dont plusieurs récidivistes, ont été arrêtés à Ndjolé pour exploitation illégale de mines d’or et séjour irrégulier, principalement des ressortissants tchadiens, burkinabés et camerounais.',
        'https://agpgabon.ga/moyen-ogooue-mines-24-expatries-recidivistes-arretes-pour-trafic-dor-a-ndjole/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b42d781-8142-461c-a581-678b0bdcf0e9',
        'Aval pétrolier : mobilisation technique pour sécuriser l’approvisionnement national',
        'Les autorités gabonaises ont mis en place une mobilisation technique pour assurer la disponibilité des produits pétroliers sur l’ensemble du territoire, notamment en réactivant les mécanismes déployés lors de la récente période de forte demande.',
        'https://agpgabon.ga/aval-petrolier-mobilisation-technique-pour-securiser-lapprovisionnement-national/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e824340f-c507-4fe8-9b76-bccb7499b1af',
        'Passeport : le Gabon, champion de la CEMAC avec 58 destinations sans visa en 2025',
        'Le passeport gabonais devrait permettre d’accéder sans visa à 58 destinations en 2025, faisant du Gabon le leader de la CEMAC en termes de liberté de mouvement pour ses citoyens.',
        'https://gabonmediatime.com/passeport-le-gabon-champion-de-la-cemac-avec-58-destinations-sans-visa-en-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '734be620-48e7-4adb-878f-d369c99d76e9',
        'Cemac : le Gabon sollicite un report du Sommet de Libreville',
        'Le Gabon demande un rapport lors du sommet de la Communauté économique de l’Afrique centrale (CEEAC) pour résoudre les problèmes économiques et sécuritaires de la région.',
        'https://gabonmediatime.com/cemac-le-gabon-sollicite-un-report-du-sommet-de-libreville/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'adf79c66-c860-4c44-97c2-33bdfc7ab1c6',
        'Fegahand : invalidation de la candidature de Nicole Asselé, le sport victime des amalgames politiques ?',
        'La candidature de Nicole Asselé a été invalidée pour des raisons politiques, le sport étant utilisé comme un outil de manipulation et d''instrumentalisation par certains acteurs politiques.',
        'https://gabonmediatime.com/fegahand-invalidation-de-la-candidature-de-nicole-assele-le-sport-victime-des-amalgames-politiques/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '629d851b-c525-4d3d-8d92-40144470edf3',
        'Élections législatives et locales 2025 / L’UDB de l’Estuaire mobilisée pour ratisser large',
        'L’UDβL de l’Estuaire organise des activités pour mobiliser et ratisser large en vue des élections législatives et locales de 2025 dans la région.',
        'https://kongossanews.info/elections-legislatives-et-locales-2025-ludb-de-lestuaire-mobilisee-pour-ratisser-large/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b68eb245-ddea-4cd6-8a9f-8d878d8da82a',
        'Accords Gabon-Turquie: Ce qu’il faut (absolument) retenir',
        'Gabon et la Turquie ont signé de nombreux accords visant à renforcer leur coopération dans les domaines économique, éducatif, et culturel, avec pour objectif de développer leurs relations bilatérales.',
        'https://kongossanews.info/accords-gabon-turquie-ce-quil-faut-absolument-retenir/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f933914-5100-4dcc-a1df-621af471aa81',
        'Brice Clotaire Oligui Nguema : Le bâtisseur obstiné du Gabon nouveau',
        'Brice Clotaire Oligui Nguema est présenté comme un bâtisseur déterminé, jouant un rôle clé dans la stabilisation et le développement du Gabon.',
        'https://kongossanews.info/brice-clotaire-oligui-nguema-le-batisseur-obstine-du-gabon-nouveau/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '798c5fee-533d-486f-92e2-12cf7f5c288d',
        'Gabon : Sylvain Florient Pangou réelu à la tête de la Fegahand',
        'Sylvain Florient Pangou a été réélu président de la Fédération gabonaise de handball avec 60,37 % des voix, confirmant la légitimité de son mandat et son engagement à réaliser les projets de la fédération.',
        'https://agpgabon.ga/gabon-sylvain-florient-pangou-reelu-a-la-tete-de-la-fegahand/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86644029-2754-4e43-b7c0-1792fb5f731e',
        'Akournam 2 vibre au son de l''espoir : ouverture du studio "Gloss Company", un rêve devenu réalité',
        'Une nouvelle studio d''enregistrement nommé "Gloss Company" a été créé dans le quartier d''Akournam 2 à Owendo, par Ndzengone Akoma Chancelle, mettant en valeur la passion et la créativité de la scène musicale gabonaise.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/akournam-2-vibre-au-son-de-l-espoir-ouverture-du',
        'Gabonews',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '11949b27-e693-488f-888a-3be3c381b7e5',
        'Structuration de la Banque de Données de Projets de Développement (BDPD) : le ministère de l''Éducation nationale pleinement engagé aux côtés du ministère de la Planification',
        'Une réunion entre plusieurs institutions gabonaises a permis de commencer à organiser une base de données pour mieux gérer et suivre les projets de développement dans le pays.',
        'https://www.gabonews.com/fr/actus/cooperation/article/structuration-de-la-banque-de-donnees-de-projets',
        'Gabonews',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b05972bf-845c-4335-baf2-b5ee81b1ac4d',
        'Bassin du Congo : les États s’accordent sur les priorités pour la reconnaissance des APAC',
        'Les pays du Bassin du Congo ont convenu de prioriser la reconnaissance légale et l’harmonisation des données sur les Aires et Territoires du Patrimoine Autochtone et Communautaire lors d’un atelier organisé à Libreville, afin de mieux protéger ces zones.',
        'https://agpgabon.ga/bassin-du-congo-les-etats-saccordent-sur-les-priorites-pour-la-reconnaissance-des-apac/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78bcd96e-86b0-4f7e-8889-9eb1101409e3',
        'Gabon/Culture : clôture de la Semaine du cinéma à Libreville',
        'La Semaine du cinéma à Libreville s''est terminée par des masterclasses, des panels et des projections qui ont permis aux participants d''apprendre et de créer leurs propres scènes avec l''encadrement de professionnels.',
        'https://agpgabon.ga/gabon-culture-cloture-de-la-semaine-du-cinema-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f47cdf61-679f-48b7-b051-671bb930587f',
        'Élections 2025 : l’UDB convoque une réunion du Commissariat Politique ce 3 août',
        'Le parti UDB organise une réunion importante du Commissariat Politique le 3 août à Libreville, afin de préparer les élections législatives et locales prévues en septembre et octobre 2025.',
        'https://agpgabon.ga/elections-2025-ludb-convoque-une-reunion-du-commissariat-politique-ce-3-aout/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5cd955c5-9524-4bb1-8586-5b1af1724408',
        'Football/Tournois de l’unité Lubin Martial Ntoutoume Obame : Dzobere débute bien face à l’OM (1-0)',
        'L''équipe Dzobere a remporté un match d''ouverture du tournoi de l''Unité Lubin Martial Ntoutoume Obame en battant Okolassi-Mekonanam 1-0, lors d''une cérémonie qui a mis en valeur l''importance du sport pour l''unité et la paix dans la région.',
        'https://agpgabon.ga/football-tournois-de-lunite-lubin-martial-ntoutoume-obame-dzobere-debute-bien-face-a-lom-1-0/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '73c5c49f-3f78-435d-bfe6-24c9b9d4d47b',
        'Jeux Africains Scolaires d’Alger/Judo : encore deux médailles de bronze pour le Gabon',
        'Le Gabon a gagné quatre médailles de bronze dans le judo lors des Jeux Africains Scolaires d’Alger, grâce aux performances de plusieurs jeunes athlètes.',
        'https://agpgabon.ga/jeux-africains-scolaires-dalger-judo-encore-deux-medailles-de-bronze-pour-le-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c832dd08-9a9d-47a9-9d4f-6e6e69963ce9',
        'Football/33 Export Corporate Championship : début de la 4e édition',
        'La 4e édition du championnat d''entreprise 33 Export a débuté samedi au stade Augustin Monedan avec un match entre Comilog et la Grande pharmacie des Forestiers, remporté par Comilog (3-1).',
        'https://agpgabon.ga/football-33-export-corporate-championship-debut-de-la-4e-edition/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce3da434-93d1-42b0-a8bf-49d246459a79',
        'Gabon-Turquie: Une coopération médicale axée sur la formation du personnel médical gabonais',
        'Après sa visite en Turquie, le président gabonais a signé un accord de coopération visant à renforcer la formation du personnel médical gabonais par le biais d’un programme de formation dédié.',
        'https://vxp241.com/2025/08/03/gabon-turquie-une-cooperation-medicale-axee-sur-la-formation-du-personnel-medical-gabonais/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b985ce5-df58-4cbb-92c6-da5c7bf59031',
        'Ces 3 accords stratégiques signés au cours du Forum d’affaire et d’investissement Turquie-Gabon',
        'Lors d''une visite d''État à Istanbul, le président gabonais Brice Clotaire OLIGUI NGUEMA a participé à un forum d''affaires bilatéral, où trois accords stratégiques ont été signés pour renforcer la coopération économique entre le Gabon et la Turquie.',
        'https://vxp241.com/2025/08/03/ces-3-accords-strategiques-signes-au-cours-du-forum-daffaire-et-dinvestissement-turquie-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52f0e77d-aaa3-4080-9997-a4a2eb139b4a',
        'Le Président de la République visite le chantier naval de Gölcük, Karpowership et Baykar',
        'Le président Brice Clotaire OLIGUI NGUEMA a visité un important complexe naval turc à Gölcük, où il a pu observer la qualité et l’innovation des équipes turques dans la construction et la modernisation de navires militaires.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-president-de-la-republique-visite-le-chantier',
        'Gabonews',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd33a7355-ab4c-456c-bf62-f9a59c020296',
        '« L''Iboga, c''est plus qu''une plante : c''est un patrimoine immatériel, un savoir sacré, une force gabonaise. » Zita Oligui Nguema',
        'L''iboga est une plante dont les usages dépassent la simple consommation, ayant des enjeux culturels, médicaux et économiques importants dans certains pays africains.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/l-iboga-c-est-plus-qu-une-plante-c-est-un',
        'Gabonews',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '294cef39-c156-4cc4-99a6-0120d73a3da4',
        'Le Président Brice Clotaire Oligui Nguema se recueille au Mausolée d''Atatürk',
        'Le président gabonais Brice Clotaire Oligui Nguema a rendu hommage à Atatürk au mausolée d’Anıtkabir à Ankara lors de sa première visite officielle en Turquie.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-president-brice-clotaire-oligui-nguema-se',
        'Gabonews',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd0bc964-ce0b-410d-abb0-0d70f7238ce5',
        'Publié le 03 / 08 / 2025',
        'Seraphin Moundounga transmet un message du président Oligui Nguema à ses pairs de la sous-région, appelant à l’unité et à la coopération pour le développement de la communauté.',
        'https://union.sonapresse.com/fr/cemac-seraphin-moundounga-porteur-dun-message-du-president-oligui-nguema-ses-pairs-de-la-sous',
        'L''union',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '669e5140-359c-4f6e-8d68-3b286abd6bd1',
        'Publié le 02 / 08 / 2025',
        'Le Gabon et la Turquie renforcent leur coopération bilatérale en signant de nouveaux accords pour développer la coopération économique, éducative et culturelle entre les deux pays.',
        'https://union.sonapresse.com/fr/gabon-turquie-une-cooperation-bilaterale-renforcee',
        'L''union',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb211dff-127f-4b13-9cfd-716ec2dca5cd',
        'Basket-ball/Coupe du Gabon 2025 : Gladiators et Relais ouvrent les hostilités',
        'La Coupe du Gabon de basketball 2025 a été lancée avec des matchs où l''équipe Gladiators a gagné contre Relais, et Moanda BB a largement battu Tandem.',
        'https://agpgabon.ga/94990-2/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2bc6a743-911d-42bd-95c9-7e83aa31a055',
        'Satellites : un bouclier high-tech pour protéger l’or bleu du Gabon',
        'Le Gabon utilise des satellites en partenariat avec des organisations internationales pour surveiller ses eaux et lutter contre la pêche illicite, protégeant ainsi ses ressources halieutiques précieuses.',
        'https://www.gabonreview.com/satellites-un-bouclier-high-tech-pour-proteger-lor-bleu-du-gabon/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '29cb84c6-d7e0-4a32-b73a-7f9332ad97c5',
        'Exhumation délicate de 30 tombes pour la future Cité Émeraude',
        'Une opération délicate d’exhumation de 30 tombes est prévue les 5 et 6 août 2025 pour permettre la construction de la future Cité Émeraude sur l’ancien site du cimetière catholique de Libreville.',
        'https://www.gabonreview.com/exhumation-delicate-de-30-tombes-pour-la-future-cite-emeraude/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bdf5632-075a-4062-bc72-47cebabc7321',
        'Trafic illégal d’or : Vingt-quatre expatriés arrêtés à Ndjolé',
        'Vingt-quatre expatriés originaires du Tchad, du Burkina Faso et du Cameroun ont été arrêtés à Ndjolé pour trafic illégal d’or et séjour irrégulier, certains étant récidivistes âgés de 25 à 40 ans.',
        'https://www.gabonreview.com/trafic-illegal-dor-vingt-quatre-expatries-arretes-a-ndjole/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c2840849-78c0-46a0-9eae-f5df9dcc73b1',
        'Publié le 03 / 08 / 2025',
        'Seraphin Moundounga a transmis un message du président Oligui Nguema à ses pairs de la CEMAC, soulignant l''importance de l''unité et de la coopération régionale pour le développement économique et la stabilité des pays membres.',
        'https://union.sonapresse.com/fr/cemac-seraphin-moundounga-porteur-dun-message-du-president-oligui-nguema-ses-pairs-de-la-sous',
        'L''union',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'be0d9eb1-ffaa-450c-ac2e-19ac88fac6a1',
        'Publié le 02 / 08 / 2025',
        'Le Gabon et la Turquie renforcent leur coopération bilatérale en signant de nouveaux accords pour développer leurs relations économiques, éducatives et culturelles.',
        'https://union.sonapresse.com/fr/gabon-turquie-une-cooperation-bilaterale-renforcee',
        'L''union',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0811544b-76b9-4b54-a61b-7f704052edd7',
        'Amélioration du système de traitement des pensions : dialogue fructueux entre la CNSS et  l’association des retraités',
        'Une rencontre a permis à la CNSS et à l’association des retraités d’échanger sur des améliorations pour rendre le traitement des pensions plus efficace.',
        'https://gabonactu.com/blog/2025/08/03/amelioration-du-systeme-de-traitement-des-pensions-dialogue-fructueux-entre-la-cnss-lassociation-des-retraites/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65cff072-035a-4b47-96eb-9a7a716f8435',
        '16 ans de prison infligés à Clément Nkonombouet pour avoir violé sa petite sœur',
        'Clément Nkonombouet a été condamné à 16 ans de prison pour avoir violé sa petite sœur mineure.',
        'https://gabonactu.com/blog/2025/08/03/16-ans-de-prison-infliges-a-clement-nkonombouet-pour-avoir-viole-sa-petite-soeur-2/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '39a67555-d5aa-43c2-b732-18dff311ff3f',
        'Woleu-Ntem/Nécrologie : le journaliste Bernardin Ngui- Ngui Obiang conduit à sa dernière demeure',
        'Un journaliste gabonais, Bernardin Ngui-Ngui, est décédé en juillet à Libreville et a été inhumé dans son village natal d''Oyem lors d''une cérémonie familiale à laquelle ont assisté ses collègues et proches.',
        'https://agpgabon.ga/woleu-ntem-necrologie-le-journaliste-bernardin-ngui-ngui-obiang-conduit-a-sa-derniere-demeure/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db41803b-ff17-4248-bcb8-02442fd4b63f',
        'FEGAHAND : réélection sous haute tension de Pangou Mbembo',
        'Le général Florian Pangou Mbembo a été réélu à la tête de la FEGHAND dans un contexte marqué par des tensions et des controverses.',
        'https://gabonactu.com/blog/2025/08/03/fegahand-reelection-sous-haute-tension-de-pangou-mbembo/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3999c1f3-1941-4447-b7cc-3efebfbc5464',
        'Gabon/Prévoyance sociale : un atelier de renforcement de capacités pour les agents des Affaires sociales de l’Ogooué-Lolo',
        'Un atelier de renforcement des capacités a été organisé pour les agents des Affaires sociales de l’Ogooué-Lolo afin d''améliorer la digitalisation des services de protection sociale non contributives dans la région.',
        'https://agpgabon.ga/gabon-prevoyance-sociale-un-atelier-de-renforcement-de-capacites-pour-les-agents-des-affaires-sociales-de-logooue-lolo/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33b3974e-d0e2-4d08-9fae-02b1a5745841',
        'Woleu-Ntem/Administration déconcentrée : la nouvelle cheffe de village d’Angouma installée dans ses fonctions',
        'Un nouveau chef de village, Angélique Bendome Ella, a été installé à Angouma dans la province du Woleu-Ntem, en remplacement de la défunte Adèle Abang, lors d''une cérémonie officielle.',
        'https://agpgabon.ga/woleu-ntem-administration-deconcentree-la-nouvelle-cheffe-de-village-dangouma-installee-dans-ses-fonctions/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '32dc5a02-7c86-46ae-abbb-c3f5bfacb388',
        'Nigeria : Dangote déploie 4000 camions pour révolutionner les distributions de carburant',
        'Dangote déploie 4000 camions alimentés au gaz naturel pour améliorer la distribution de ses carburants au Nigeria, ce qui représente une évolution majeure dans la logistique pétrolière du pays.',
        'https://agpgabon.ga/nigeria-dangote-deploie-4000-camions-pour-revolutionner-les-distributions-de-carburant/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f9decd0-ff8c-4fbd-b9d1-89b3dc2cb374',
        'Gabon/Vie des partis politiques : UNI officialise sa fusion-absorption par UDB',
        'L''Union Démocratique des Bâtisseurs (UDB) a officiellement absorbé l''Union Nationale Initiale (UNI) pour renforcer le front républicain et promouvoir la démocratie ainsi que le développement du Gabon.',
        'https://agpgabon.ga/gabon-vie-des-partis-politiques-uni-officialise-sa-fusion-absorption-par-udb/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e64a9ebf-59a6-4d38-af6d-e7524b080df4',
        'Judo : clôture du Camp de vacances du club Manga judo DFIPB',
        'Le club Manga Judo DFIP a organisé avec succès un camp de vacances pourinitier 40 enfants âgés de 6 à 14 ans aux bases du judo, en suscitant également un intérêt inattendu chez d’autres groupes d''âge.',
        'https://agpgabon.ga/judo-cloture-du-camp-de-vacances-du-club-manga-judo-dfipb/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

