-- Batch 1 - Section 15/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '95c87921-6c72-4a2e-a9b1-92708d5ce930',
        'Ngounié : les enfants de la province en rang serré pour le président de la Transition à Mouila',
        'Le président de la transition, Brice Clotaire Oligui Nguema, a visité la province de la Ngounié à Mouila pour inaugurer un centre hospitalier et lancer plusieurs projets d''infrastructures visant à accélérer la transformation du Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/ngounie-les-enfants-de-la-province-en-rang-serre',
        'Gabonews',
        'Numérique / Digital, Services, Éducation, Tourisme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5e4a7fc-9a1b-41f9-9c2f-904027daee14',
        'Gabon : suspension de la grève des magistrats !',
        'Les magistrats gabonais ont suspendu leur grève pour alléger la population tout en continuant de réclamer des réformes structurelles dans le système judiciaire.',
        'https://gabonmediatime.com/gabon-suspension-de-la-greve-des-magistrats/',
        'Gabon Media Time',
        'Services, Finances, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '515c2d9d-cbc5-4bf6-97fd-5646a92f6d95',
        'Présidentielle au Gabon : les journalistes s’engagent pour une couverture médiatique responsable',
        'Les journalistes gabonais ont adopté une charte éthique et une déclaration pour assurer une couverture médiatique responsable et fiable lors de l’élection présidentielle de 2025.',
        'https://www.gabonreview.com/presidentielle-au-gabon-les-journalistes-sengagent-pour-une-couverture-mediatique-responsable/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f753bcf0-8afd-4086-89f3-5557124a4280',
        'Publié le 26 / 03 / 2025',
        'Brice Clotaire Oligui Nguema se présente à la présidentielle du 12 avril 2025 avec une grande confiance, mettant en avant les réalisations de la Transition et s''engageant à résoudre le chômage des jeunes et les problèmes d''infrastructures.',
        'https://union.sonapresse.com/fr/presidentielle-oligui-nguema-plus-que-jamais-confiant',
        'L''Union',
        'Numérique / Digital, Services, Commerce, Éducation, Agriculture',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3103a64-2290-4e08-b041-03cbefcc1382',
        'Gabon : le Comité santé et sécurité au Travail de l’OCT désormais installé !',
        'Le 25 mars 2025, Owendo Container Terminal (OCT) a inauguré son Comité Santé et Sécurité au Travail (CSST), renforçant ainsi son engagement en faveur de la prévention des risques professionnels et du bien-être de ses employés.',
        'https://gabonmediatime.com/gabon-le-comite-sante-et-securite-au-travail-de-loct-desormais-installe/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24f07970-30be-4198-b850-a2bbb9cdfde2',
        'Gabon : lancement d’un projet pour une coexistence pacifique entre l’homme et l’éléphant',
        'Le gouvernement gabonais lance un projet soutenu par la CAFI et la WCS visant à installer 1 800 clôtures électriques à travers le pays pour réduire les conflits entre les populations rurales et les éléphants, protéger les cultures et améliorer les conditions de vie des communautés locales.',
        'https://www.gabonreview.com/gabon-lancement-dun-projet-pour-une-coexistence-pacifique-entre-lhomme-et-lelephant/',
        'Gabon Review',
        'Numérique / Digital, Services, Agriculture',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e21189b-edd9-455e-91dc-19c9f3f28591',
        'Publié le 26 / 03 / 2025',
        'Les bailleurs de fonds internationaux ont réaffirmé leur soutien au Gabon lors d''une réunion dirigée par le président de la Transition, reconnaissant les efforts du pays pour renforcer la transparence et stimuler le développement économique.',
        'https://union.sonapresse.com/fr/les-bailleurs-de-fonds-reaffirment-leur-soutien-au-gabon',
        'L''Union',
        'Numérique / Digital, Finances, Éducation, Agriculture, Services',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9436b9a4-12af-4713-8e26-d838243979b5',
        'Les doléances de Mimongo et d’Etéké soumises au Conseiller Spécial de Brice Clotaire Oligui Nguema',
        'Le conseiller spécial de Brice Clotaire Oligui Nguema a recueilli les doléances des habitants de Mimongo et d’Etéké, soulignant les besoins urgents en infrastructures sanitaires et développement local dans la province de la Ngounié sud.',
        'https://www.gabonews.com/fr/actus/societe/article/les-doleances-de-mimongo-et-d-eteke-soumises-au',
        'Gabonews',
        'Services, Éducation, Santé',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05a26c02-c1c4-4078-ab02-b41a45de3cdc',
        'Gabon : le Gén. Ntossui lance le projet de coexistence pacifique entre l’homme et l’éléphant',
        'Le Général Maurice Ntossui Allogo a lancé un projet financé par l''Initiative pour la forêt d’Afrique centrale (CAFI) visant à promouvoir une coexistence pacifique entre les humains et les éléphants au Gabon en installant plus de 1 800 clôtures électriques à travers le pays.',
        'https://gabonmediatime.com/gabon-le-gen-ntossui-lance-le-projet-de-coexistence-pacifique-entre-lhomme-et-lelephant/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Agriculture, Tourisme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fecabef0-ee42-4144-adcd-7755a2431fdf',
        'Développement rural : Assiami et Bayi misent sur Oligui Nguema pour un avenir prometteur',
        'Les habitants des villages d’Assiami et Bayi ont décidé de soutenir Brice Clotaire Oligui Nguema lors d’une réunion à Libreville pour promouvoir le développement local à travers des initiatives collaboratives et le renforcement des coopératives.',
        'https://www.gabonreview.com/developpement-rural-assiami-et-bayi-misent-sur-oligui-nguema-pour-un-avenir-prometteur/',
        'Gabon Review',
        'Numérique / Digital, Services, Agriculture, Business Femme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '99b54aa4-a0f8-4ff8-8535-2c99d7678c11',
        'Publié le 25 / 03 / 2025',
        'Le Bloc démocratique chrétien (BDC) et le Parti du réveil citoyen (PRC) ont officiellement soutenu Brice Clotaire Oligui Nguema comme leader pour l’avenir du Gabon post-transition.',
        'https://union.sonapresse.com/fr/le-bdc-et-le-prc-egalement-derriere-oligui-nguema',
        'L''Union',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '508467cd-25dc-463b-b1aa-ec8124b26f4d',
        'Publié le 25 / 03 / 2025',
        'Le bilan de Jude Ibrahim Rapontchombo à la mairie de Libreville est entaché par un manque de transparence financière et une gestion budgétaire déséquilibrée, suscitant des doutes quant à sa capacité à mettre en œuvre les réformes nécessaires.',
        'https://union.sonapresse.com/fr/mairie-de-libreville-les-doutes-subsistent',
        'L''Union',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '747c33ca-b03c-4756-9b98-adbc8d92fab8',
        'Présidentielle 2025 : Une vaste campagne pour l’adhésion à Ensemble pour le Gabon',
        'La plateforme Ensemble pour le Gabon, dirigée par Alain-Claude Bilie-By-Nze, a lancé une vaste campagne d’adhésion du 26 mars au 2 avril 2025 afin de rassembler associations et personnalités en vue des élections présidentielles du 12 avril 2025.',
        'https://www.gabonreview.com/presidentielle-2025-une-vaste-campagne-pour-ladhesion-a-ensemble-pour-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.360Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cca0f179-3e11-4fd0-bbef-c6f62eedeefe',
        'Aymard Mbioko défend le statut de l’entreprenant sur Gabon 24',
        'Aymard Mbioko défend lors d’un débat l’instauration d’un statut juridique clair et favorable pour les entrepreneurs au Gabon afin de renforcer l’écosystème entrepreneurial national.',
        'https://kongossanews.info/aymard-mbioko-defend-le-statut-de-lentreprenant-sur-gabon-24/',
        'Kongossa News',
        'Numérique / Digital, Services, Finances',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.361Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f5e6382-f861-4426-99d1-9d0112dda6d0',
        'Gabon : Face aux patrons, Oligui Nguema annonce un nouveau plan d’action pour booster l’économie',
        'Le président de la transition gabonaise, Brice Clotaire Oligui Nguema, a dévoilé un nouveau plan d’action visant à dynamiser l’économie nationale en renforçant le partenariat avec la Fédération des entreprises du Gabon (FEG) à travers des mesures telles que la gestion optimisée de la dette publique, la simplification administrative et une fiscalité attractive.',
        'https://www.gabonreview.com/gabon-face-aux-patrons-oligui-nguema-annonce-un-nouveau-plan-daction-pour-booster-leconomie/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.361Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14708249-52d5-4eb6-a502-ad474e5e42a3',
        'Présidentielle au Gabon : plus de 100 observateurs en quête d’accréditation',
        'Plus de 100 observateurs ont soumis des demandes d’accréditation pour surveiller la présidentielle de 2025 au Gabon, qui sont actuellement en cours d’examen par la Commission spéciale.',
        'https://www.gabonreview.com/presidentielle-au-gabon-plus-de-100-observateurs-en-quete-daccreditation/',
        'Gabon Review',
        'Services, Tourisme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.361Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e00aa901-6147-44a0-a66b-a7d7f4e4bdf2',
        'Investissements stratégiques : UBA et le Gabon unissent leurs forces',
        'L''article décrit la collaboration stratégique entre le Groupe UBA et le Gabon visant à renforcer les partenariats économiques et promouvoir des investissements durables dans le pays.',
        'https://kongossanews.info/investissements-strategiques-uba-et-le-gabon-unissent-leurs-forces/',
        'Kongossa News',
        'Services, Finances, Tourisme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.361Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f69b38c9-ccf6-479f-9ec5-c854d58d58cb',
        'Grève suspendue, colère maintenue : les magistrats « plient sans rompre »',
        'Les magistrats gabonais suspendent leur grève pour alléger les souffrances de la population tout en restant déterminés à obtenir des réformes judiciaires profondes.',
        'https://www.gabonreview.com/greve-suspendue-colere-maintenue-les-magistrats-plient-sans-rompre/',
        'Gabon Review',
        'Éducation, Services, Finances, Numérique / Digital',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.361Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '02970e88-8b02-4c1b-bb18-df57dd2ab646',
        '[Tribune] Diplomatie Économique et Intermédiation d’Affaires : un appel à l’action pour le Gabon',
        'À l''approche des élections présidentielles de 2025, Yohann Emeryc Moussadji Nzamba appelle à renforcer la diplomatie économique du Gabon en accordant des passeports diplomatiques aux intermédiaires d’affaires afin d’attirer des investissements étrangers et d''améliorer l''image du pays sur la scène mondiale.',
        'https://www.gabonreview.com/diplomatie-economique-et-intermediation-daffaires-un-appel-a-laction-pour-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.362Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8eb7de8b-82cd-4388-ab1f-568226d8614b',
        'Feuilleton Politico-judiciaire HPO: la communauté internationale s’ouvre au sujet',
        'Une délégation de l''UDIS a rencontré l''ambassade de France au Gabon pour dénoncer la situation politico-judiciaire de son président Hervé Patrick Opiangah et les répercussions sur les employés de ses entreprises.',
        'https://kongossanews.info/feuilleton-politico-judiciaire-hpo-la-communaute-internationale-souvre-au-sujet/',
        'Kongossa News',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.362Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2eabe14d-bc18-4c08-924e-f8fa65ff9649',
        'BEAC/CPM : Ajustement des taux directeurs et repli de l’inflation à 2,9%, sous la norme communautaire',
        'Lors de sa réunion du 24 mars 2025, le Comité de politique monétaire de la BEAC a ajusté les taux directeurs afin de réduire l’inflation à 2,9 % conformément à la norme communautaire.',
        'https://www.gabonreview.com/beac-cpm-ajustement-des-taux-directeurs-et-repli-de-linflation-a-29-sous-la-norme-communautaire/',
        'Gabon Review',
        'Numérique / Digital, Finances, Commerce, Agriculture',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.362Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0b2a1fc-3431-4290-84bc-b8333e3d237d',
        'Gestion plus rigoureuse de la dette : Création de la Caisse autonome d’amortissement',
        'Le président de la Transition, Brice Clotaire Oligui Nguema, a annoncé la création de la Caisse autonome d’amortissement (CAA) afin d''assurer une gestion rigoureuse de l''endettement du Gabon et de renforcer la confiance des partenaires financiers.',
        'https://directinfosgabon.com/gestion-plus-rigoureuse-de-la-dette-creation-de-la-caisse-autonome-damortissement/',
        'Direct infos Gabon',
        'Finances, Numérique / Digital',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.362Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2f395ab-908e-4391-abf6-a16d02dafd51',
        'Présidentielle 2025 : Les résultats en moins de 48 heures ?',
        'Le ministère de l’Intérieur et la CNOCER visent à publier les résultats de la présidentielle 2025 en moins de 48 heures afin d''assurer une proclamation rapide du vainqueur par la Cour constitutionnelle et éviter tout désordre.',
        'https://www.gabonreview.com/presidentielle-2025-les-resultats-en-moins-de-48-heures/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.362Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca3d78a7-f72b-4695-a0fa-bd6f4df8b8fa',
        'Présidentielle 2025 : La coalition pour la rupture avec la Françafrique appelle au boycott',
        'La Coalition pour la rupture avec la Françafrique appelle au boycott de l''élection présidentielle de 2025, estimant que les candidats ne reflètent pas leurs valeurs de fin des relations avec la Françafrique et du système PDG-Bongo-CTRI.',
        'https://gabonactu.com/blog/2025/03/26/presidentielle-2025-la-coalition-pour-la-rupture-avec-la-francafrique-appelle-au-boycott/',
        'Gabon Actu',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.363Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aaa8b122-f5c1-4321-a907-cb3a1e1d4ea4',
        'Prêts bancaires : Oligui Nguéma rassure les bailleurs de fonds',
        'Le président de la Transition, Brice Clotaire Oligui Nguema, a rassuré les principaux bailleurs de fonds lors d''une réunion à Libreville en présentant un bilan détaillé de l''utilisation des fonds, renforçant ainsi le soutien financier au Gabon pour assurer sa stabilité et son développement.',
        'https://directinfosgabon.com/prets-bancaires-oligui-nguema-rassure-les-bailleurs-de-fonds/',
        'Direct infos Gabon',
        'Finances, Services',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.363Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7716335a-3b07-4f83-ac14-ae7bb1285f2b',
        'Campagne d’Oligui Nguema : Controverse autour des anciens du PDG',
        'La campagne présidentielle de Brice Clotaire Oligui Nguema est controversée en raison de l''inclusion de nombreux anciens membres du Parti démocratique gabonais dans son équipe, suscitant des inquiétudes parmi les jeunes partisans quant à la répétition des anciennes pratiques politiques.',
        'https://www.gabonreview.com/campagne-doligui-nguema-la-controverse-autour-des-anciens-du-pdg/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.363Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95672cdc-b2e0-4723-a43a-45eb443c0ba0',
        'Pêche : 500 nouveaux emplois annoncés pour dynamiser le secteur',
        'Le ministère de la Pêche du Gabon a annoncé la création de 500 nouveaux emplois dans le secteur halieutique pour dynamiser la filière et favoriser l''emploi des jeunes.',
        'https://gabonactu.com/blog/2025/03/26/peche-500-nouveaux-emplois-annonces-pour-dynamiser-le-secteur/',
        'Gabon Actu',
        'Agriculture, Éducation, Services',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.363Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cbc840a6-3f94-4c04-bf80-24c8eba57710',
        'Publi-rédactionnel / Oligui Nguéma, de la transition à la quête de légitimité démocratique',
        'L''article présente Oligui Nguéma, chef de la transition au Gabon, ses réformes majeures et sa candidature à l''élection présidentielle de 2025 visant à légitimer démocratiquement son pouvoir et à poursuivre les améliorations socio-économiques du pays.',
        'https://directinfosgabon.com/publi-redactionnel-oligui-nguema-de-la-transition-a-la-quete-de-legitimite-democratique/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.363Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe3e7686-b4e4-4cfc-bf2c-cc454b947d8d',
        'Pêche et Mer : un séminaire dévoile des opportunités d’emplois dans le secteur',
        'Un séminaire organisé par le ministère de la Pêche et de la Mer sous le patronage du président de la Transition a identifié près de 500 opportunités d’emploi dans le secteur de la pêche et de la mer, positionnant ce domaine comme un levier stratégique pour l’employabilité et le développement économique du Gabon.',
        'https://mediapostegabon.com/peche-et-mer-un-seminaire-devoile-des-opportunites-demplois-dans-le-secteur/',
        'Media Poste Gabon',
        'Services, Business Femme, Agriculture',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.364Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db942f23-c2fb-4fa9-963e-1af2c51729d0',
        'Présidentielle du 12 avril : Barro Chambrier et le RPM rejoignent le RdB',
        'Dans le cadre de la campagne présidentielle de 2025 au Gabon, le Rassemblement pour la patrie et la modernité (RPM) d’Alexandre Barro Chambrier a adhéré au Rassemblement des Bâtisseurs (RdB) de Brice Clotaire Oligui Nguema afin de renforcer la cohésion et l’unité autour de sa candidature.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-barro-chambrier-et-le-rpm-rejoignent-le-rdb/',
        'Gabon Review',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.364Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d8718d1-fb44-490e-9237-72915073183d',
        'CIMAF injecte 25 milliards de FCFA pour soutenir la production de ciment au Gabon',
        'Le groupe marocain CIMAF investit 25 milliards de FCFA pour augmenter la production de ciment au Gabon en ajoutant une nouvelle ligne de production et en construisant une unité à Ntoum, favorisant ainsi le développement économique et la création d''emplois locaux.',
        'https://gabonactu.com/blog/2025/03/26/cimaf-injecte-25-milliards-de-fcfa-pour-soutenir-la-production-de-ciment-au-gabon/',
        'Gabon Actu',
        'Industrie, Services, Emploi',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.364Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1d014af-3347-4be4-b1b2-2136f65608cd',
        'Caravane médicale Mayani d’Abord : l’onction sanitaire de Christian Boundzanga pour les populations du canton Wano-Ivindzi Prési...',
        'Christian Boundzanga a lancé la caravane médicale « Mayani d’abord » pour fournir des soins de santé à cinq villages reculés du canton Wano-Ivindzi, bénéficiant ainsi à 700 habitants.',
        'https://mediapostegabon.com/caravane-medicale-mayani-dabord-lonction-sanitaire-de-christian-boundzanga-pour-les-populations-du-canton-wano-ivindzi/',
        'Media Poste Gabon',
        'Services, Agriculture, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.365Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68d179fd-efe5-4595-bc4a-d758a912b85a',
        'Freddy Koula à la tête de Moabi-Aigles Lunga : une mission de cœur et d’ambition',
        'Freddy Koula Moussavou a été élu président de Moabi-Aigles Lunga et ambitionne de transformer le club en un symbole de fierté locale et de l’élever jusqu’à l’élite nationale dans les prochaines années.',
        'https://www.gabonreview.com/freddy-koula-a-la-tete-de-moabi-aigles-lunga-une-mission-de-coeur-et-dambition/',
        'Gabon Review',
        'Services, Tourisme, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.365Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f5e9b849-4097-4986-afbb-2ae86ac14474',
        'Lettre ouverte aux coordinateurs de campagne : Le canton Nyé exige sa juste place dans l’équipe électorale d’Oligui Nguema',
        'Les cadres du canton Nyé ont lancé une lettre ouverte au campaing d’Oligui Nguema, dénonçant l’exclusion des personnalités locales des équipes de campagne et exigeant une représentation équitable pour garantir l’inclusivité et la légitimité de sa candidature.',
        'https://kongossanews.info/lettre-ouverte-aux-coordinateurs-de-campagne-le-canton-nye-exige-sa-juste-place-dans-lequipe-electorale-doligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.365Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e33b132-b2e1-4654-8624-4d4d5d383e95',
        'Au service du développement durable, Jess&Action s’implante au Gabon et s’engage aux côtés Oligui Nguema',
        'Jess&Action s''implante au Gabon pour promouvoir l''agriculture durable et soutenir le développement des jeunes aux côtés d''Oligui Nguema.',
        'https://www.gabonreview.com/au-service-du-developpement-durable-jessaction-simplante-au-gabon-et-sengage-aux-cotes-oligui-nguema/',
        'Gabon Review',
        'Agriculture, Éducation, Services, Business Femme',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.365Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '081ddf12-c433-4b08-8d7d-fdcf61f9687e',
        '[Tribune] Congrès d’investiture de l’UPR : la confirmation de la fidélité de Gervais Oniane',
        'Le congrès de l’Union Pour la République (UPR) dirigé par Gervais Oniane confirme sa fidélité et son soutien à Oligui Nguema pour l’élection présidentielle de 2025, soulignant leur vision commune pour un nouveau Gabon.',
        'https://www.gabonreview.com/tribune-congres-dinvestiture-de-lupr-la-confirmation-de-la-fidelite-de-gervais-oniane/',
        'Gabon Review',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.365Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ded8615e-a5e7-411e-a369-c6bb749805da',
        'Présidentielle 2025/Abstention : « Le changement commence par toi et moi. Faisons entendre nos voix en votant »  dixit Éric Gaël...',
        'Éric Gaël Myboto appelle les Gabonais à participer aux élections présidentielles de 2025 pour lutter contre l''abstention et soutenir le retour à la stabilité constitutionnelle du pays.',
        'https://kongossanews.info/presidentielle-2025-abstention-le-changement-commence-par-toi-et-moi-faisons-entendre-nos-voix-en-votant-dixit-eric-gael-myboto/',
        'Kongossa News',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46f97972-87fc-4ddf-b105-99a0648c71ae',
        'Gabon : 6539 cas de tuberculose sensible enregistrés en 2024',
        'En 2024, le Gabon a enregistré 6 539 cas de tuberculose sensible, mettant en lumière la persistance de la maladie et les défis persistants pour le système de santé publique du pays.',
        'https://gabonmediatime.com/gabon-6539-cas-de-tuberculose-sensible-enregistres-en-2024/',
        'Gabon Media Time',
        'Santé, Services, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e71d2b73-a1ec-4edb-85d4-b7697b00071c',
        'Owendo Container Terminal installe son Comité santé et sécurité au travail',
        'Owendo Container Terminal (OCT) a officiellement mis en place son Comité santé et sécurité au travail (CSST) le 25 mars 2025 afin de renforcer la sécurité et améliorer les conditions de travail de ses employés.',
        'https://www.gabonreview.com/owendo-container-terminal-installe-son-comite-sante-et-securite-au-travail/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4147844-2d7c-423d-9662-609b4a37defe',
        'Présidentielle 2025 : Oyiba en maître d’orchestre de la campagne d’Oligui Nguema',
        'Jean Pierre Oyiba, ancien ministre d’État et conseiller spécial, dirigera la coordination générale de la campagne présidentielle d’Oligui Nguema pour l’élection de 2025 au Gabon.',
        'https://gabonmediatime.com/presidentielle-2025-oyiba-en-maitre-dorchestre-de-la-campagne-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a48b6a53-fe2e-4f5c-9bf4-40a5f05b2728',
        'Présidentielle 2025 : Les candidats repêchés signent leur conformité sur la protection des données',
        'Les candidats rééligibles à la présidentielle gabonaise de 2025 ont signé leur conformité aux réglementations sur la protection des données, garantissant ainsi une campagne respectueuse des droits fondamentaux et de la vie privée.',
        'https://www.gabonreview.com/presidentielle-2025-les-candidats-repeches-signent-leur-conformite-sur-la-protection-des-donnees/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '802f63e3-5143-42d3-a586-a7c0dc967b6a',
        'Dette publique : Oligui Nguema annonce la mise en place d’une Caisse autonome d’amortissements',
        'Le Président de la Transition gabonaise Brice Clotaire Oligui Nguema annonce la création d’une Caisse autonome d’amortissements pour garantir une gestion transparente de la dette publique.',
        'https://gabonmediatime.com/dette-publique-oligui-nguema-annonce-la-mise-en-place-dune-caisse-autonome-damortissements/',
        'Gabon Media Time',
        'Finances, Numérique / Digital',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '42d7fd2b-7a4b-45f9-8fd4-5e89b9fa7438',
        'Affaire Sylvia et Noureddin Bongo Valentin : La procédure touche à sa fin',
        'L''enquête judiciaire contre Sylvia et Noureddin Bongo Valentin, épouse et fils aîné de l''ancien président gabonais, est presque achevée et pourrait se conclure par un procès en raison de graves accusations de détournement de fonds publics, de corruption et de blanchiment d''argent.',
        'https://www.gabonreview.com/affaire-sylvia-et-noureddin-bongo-valentin-la-procedure-touche-a-sa-fin/',
        'Gabon Review',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '855f8b5b-fada-49e3-b514-eeaa103b85ad',
        'Publié le 27 / 03 / 2025',
        'Le candidat à la présidentielle gabonaise Alain-Claude Bilie-By-Nze présente douze mesures clés de son projet de société visant à réformer les finances, renforcer la justice et la réconciliation nationale, combattre la corruption et le grand banditisme, ainsi qu’à améliorer le cadre social et urbain du pays.',
        'https://union.sonapresse.com/fr/presidentielle-bilie-nze-devoile-son-projet-de-societe',
        'L''Union',
        'Numérique / Digital, Services, Finances, Éducation, Business Femme',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.366Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d61f8d2-86bd-4173-98e0-fa31312b4c80',
        'La Dola/Le PDG se réjouit pour ses 57 ans',
        'Le Parti démocratique gabonais (PDG) célèbre son 57ᵉ anniversaire dans la Dola en nommant un nouveau secrétaire départemental, symbolisant le renouvellement du parti en vue des prochaines élections présidentielles et législatives au Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/la-dola-le-pdg-se-rejouit-pour-ses-57-ans',
        'Gabonews',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bb5eee0-1ab4-46f8-8d7e-a7d1e38185e4',
        'Bilie-By-Nze : « Je m’engage à opérer une rupture totale avec l’ancien régime »',
        'Le candidat à la présidentielle gabonaise Alain-Claude Bilie-By-Nze a présenté son « Contrat national de rupture », s’engageant à rompre totalement avec l’ancien régime en mettant en œuvre des réformes axées sur la transparence, la justice et la refondation de l’État.',
        'https://gabonmediatime.com/bilie-by-nze-je-mengage-a-operer-une-rupture-totale-avec-lancien-regime/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Éducation, Business Femme',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ecdcd829-fd9c-4644-ad16-061e242a0b95',
        'Présidentielle du 12 avril : Mike Jocktane soutient Oligui Nguema, un choix de responsabilité pour l’avenir du Gabon',
        'Mike Jocktane, leader du mouvement Gabon Nouveau, a exprimé son soutien à Brice Clotaire Oligui Nguema pour les élections présidentielles du 12 avril 2025, estimant que ce choix garantit la stabilité politique et la continuité des réformes au Gabon.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-mike-jocktane-soutient-oligui-nguema-un-choix-de-responsabilite-pour-lavenir-du-gabon/',
        'Gabon Review',
        'Autres',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '07847ee7-ddd0-4f56-88cb-68b8eb0e92b9',
        'Publié le 27 / 03 / 2025',
        'À l’approche de l’élection présidentielle gabonaise, la diaspora joue un rôle essentiel dans le renouveau démocratique et économique du pays en s’engageant activement dans l’entrepreneuriat, l’investissement local et les réformes soutenues par le président de la transition.',
        'https://union.sonapresse.com/fr/presidentielle-la-diaspora-gabonaise-en-moteur-du-renouveau-democratique',
        'L''Union',
        'Numérique / Digital, Services, Finances, Business Femme',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e958c61b-02d2-49dc-adda-a9742771d926',
        'Gabon : Oligui Nguema annonce 10 mesures clés pour améliorer le climat des affaires',
        'Le président Brice Clotaire Oligui Nguema a annoncé dix mesures clés visant à améliorer le climat des affaires au Gabon, incluant la réduction des barrières commerciales, la simplification administrative, une fiscalité attractive et la digitalisation de l’administration.',
        'https://gabonmediatime.com/gabon-oligui-nguema-annonce-10-mesures-cles-pour-ameliorer-le-climat-des-affaires/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '30476105-8ec4-4b30-a8e2-d30a6c1e89c0',
        'Publié le 27 / 03 / 2025',
        'Le gouvernement gabonais instaure de nouveaux manuels de procédures et un système d’évaluation des agents publics pour standardiser les pratiques administratives, améliorer la performance et lutter contre la corruption.',
        'https://union.sonapresse.com/fr/administration-des-outils-pour-de-nouvelles-regles-du-jeu',
        'L''Union',
        'Numérique / Digital, Services, Éducation',
        '2025-03-27T00:00:00.000Z',
        '2025-09-15T23:06:12.367Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

