-- Batch 7 - Section 6/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '1d793e7a-21d3-4c7c-8acd-ceb78488a445',
        'Gabon: le gouvernement amnistie les putschistes de 2023 et de la tentative de 2019',
        'Le gouvernement gabonais a adopté une ordonnance d''amnistie couvrant à la fois le coup d''État de 2023 et la tentative de putsch de 2019, afin de favoriser la réconciliation et la stabilité politique.',
        'https://www.rfi.fr/fr/afrique/20250813-gabon-amnistie-les-putschistes-de-2023-et-de-la-tentative-de-2019-%C3%A9conomie-lutte-deficit-croissante-metiers',
        'RFI',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3544a480-3380-472a-8370-8d1f361b329b',
        'Gabon: le gouvernement amnistie les putschistes de 2023 et de la tentative de 2019',
        'Le gouvernement gabonais a décidé d’accorder une amnistie couvrant à la fois le coup d’État du 30 août 2023 et la tentative de putsch manquée du 7 janvier 2019, dans le but de favoriser la réconciliation nationale.',
        'https://www.rfi.fr/fr/afrique/20250813-gabon-amnistie-les-putschistes-de-2023-et-de-la-tentative-de-2019-%C3%A9conomie-lutte-deficit-croissante-metiers?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2bb6f82-0a99-4224-99e3-ef8148c63b78',
        'Hôpital interdépartemental à 3 milliards de Moanda : un nouvel horizon pour la santé dans la localité',
        'Un nouvel hôpital interdépartemental, construit à Moanda pour 3 milliards de francs CFA, a été inauguré, offrant un meilleur accès aux soins dans la région du Haut-Ogooué.',
        'https://www.gabonreview.com/hopital-interdepartemental-a-3-milliards-de-moanda-un-nouvel-horizon-pour-la-sante-dans-la-localite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c709229d-08a5-40d3-b96c-24b481ae846f',
        'Franceville : saisie importante de cannabis par les agents de l’Oclad',
        'Une opération policière à Franceville a permis d’arrêter un homme en possession d’une grande quantité de cannabis.',
        'https://agpgabon.ga/franceville-saisie-importante-de-cannabis-par-les-agents-de-loclad/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd096e98d-bc0f-4e74-8531-ce664813d6e3',
        'Gabon : quatre dignitaires honorifiés par le Président de la République',
        'Quatre personnalités gabonaises ont reçu des distinctions honorifiques de la part du président Brice Clotaire Oligui Nguema lors d''une cérémonie à la présidence pour récompenser leur engagement et leur contribution à la République.',
        'https://agpgabon.ga/gabon-quatre-dignitaires-honorifies-par-le-president-de-la-republique/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1371b8ec-ea54-4669-a557-af124b2f7968',
        'Gabon/Industrie : le Conseil des ministres valide la mise en œuvre du CATI',
        'Le gouvernement gabonais a validé la mise en œuvre du Centre d’appui à la technologie et à l’innovation (CATI), un projet conjoint avec l’OMPI visant à fournir aux innovateurs locaux des services pour renforcer leurs capacités technologiques et leur développement.',
        'https://agpgabon.ga/gabon-industrie-le-conseil-des-ministres-valide-la-mise-en-oeuvre-du-cati/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88d20c0b-f642-467c-b631-af2184acf300',
        'Gabon/Numérique : vers une réglementation de la digitalisation',
        'Le gouvernement gabonais prévoit de mettre en place un cadre réglementaire pour encadrer la digitalisation dans tous les secteurs, afin de simplifier les démarches administratives et de favoriser le développement économique et social.',
        'https://agpgabon.ga/gabon-numerique-vers-une-reglementation-de-la-digitalisation/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b733ab0-1e1f-4cde-82d5-66cdd58485a1',
        'Gabon : 300 recrues engagées pour la protection des forêts',
        '300 nouveaux recrues issues des écoles forestières du Gabon ont commencé une formation de 45 jours pour renforcer la protection des forêts, dans le cadre d’un projet national visant à constituer une force de 900 agents disciplinés et patriotiques.',
        'https://agpgabon.ga/gabon-300-recrues-engagees-pour-la-protection-des-forets/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd4a37e8d-bad3-4cd0-a3c4-76fdc54e0de7',
        'Citoyenneté : le Gabon renforce ses procédures d’acquisition de la nationalitél',
        'Le Gabon a adopté un nouveau Code de nationalité pour moderniser et harmoniser ses règles d''acquisition, de perte et de déchéance de la citoyenneté, remplaçant la loi de 1999.',
        'https://agpgabon.ga/citoyennete-le-gabon-renforce-ses-procedures-dacquisition-de-la-nationalitel/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0968a990-a706-42a6-b641-e7b386b02df6',
        'Arrestation du Roi Béni : 10000 ans de protection dans les geôles de la Police',
        'La police gabonaise a arrêté un criminel très violent, connu sous le nom de « Le Roi Béni », mettant fin à un réseau criminel dangereux.',
        'https://gabonactu.com/blog/2025/08/13/arrestation-du-roi-beni-10000-ans-de-protection-dans-les-geoles-de-la-police/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96ba21fa-978b-4214-a88f-82362d04cb43',
        'Faits-divers : découverte d’un corps en décomposition avancée à Ndjolé',
        'Un corps en état de décomposition a été retrouvé près du fleuve Ogooué à Ndjolé, alors que la ville recherche un enseignant disparu depuis trois semaines.',
        'https://agpgabon.ga/faits-divers-decouverte-dun-corps-en-decomposition-avancee-a-ndjole/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe2d84ac-fbb8-4e69-b91a-2f6ef0b325ff',
        'Publié le 13 / 08 / 2025',
        'La mairie de Libreville, le FDS et l''EPG appellent à un changement pour améliorer la gestion urbaine et les services publics dans la ville.',
        'https://union.sonapresse.com/fr/mairie-de-libreville-fds-et-epg-pronent-le-changement',
        'L''union',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f6e487b-c35a-432b-a7a5-da0315a0b9c1',
        'Publié le 13 / 08 / 2025',
        'La révision de la liste électorale a provoqué une hausse massive de la fréquentation des bureaux de vote, notamment dans les zones urbaines, à la dernière minute avant la clôture des inscriptions.',
        'https://union.sonapresse.com/fr/revision-de-la-liste-electorale-le-grand-rush-au-dernier-jour',
        'L''union',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80981a4f-eb0f-4b7b-aef2-59d4ee4b0146',
        '« Fête de la Libération » : la Nyanga hôte de l’édition 2025 Année scolaire 2025-2026 : la rentrée des classes fixée au 1er sept...',
        'La fête de la Libération à Nyanga, prévue pour 2025, se veut un évènement majeur de célébration et de commémoration dans la région.',
        'https://mediapostegabon.com/fete-de-la-liberation-la-nyanga-hote-de-ledition-2025/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3ac4aa8f-cc8e-4369-8eb9-07c0a1b44bf8',
        'Ntoum-2e arrondissement : lancement de la 2e édition du tournoi de football « Ensemble, bâtissons le 2e arrondissement de Ntoum',
        'Une initiative locale a lancé la deuxième édition d’un tournoi de football pour rassembler la communauté et encourager la cohésion dans le 2e arrondissement de Ntoum.',
        'https://mediapostegabon.com/ntoum-2e-arrondissement-lancement-de-la-2e-edition-du-tournoi-de-football-ensemble-batissons-le-2e-arrondissement-de-ntoum/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bec2da44-0d5f-4c55-8795-2297feffed35',
        'Gabon/Braquages : le Roi Béni et ses complices aux arrêts',
        'La police de Libreville a arrêté un réseau de criminels dirigé par Ted Willy Alimbi Ognalagha, alias « le Roi Bénie », responsable de plusieurs braquages violents visant des résidences de personnalités, avec l’implication de personnes venues des pays voisins.',
        'https://agpgabon.ga/gabon-braquages-le-roi-beni-et-ses-complices-aux-arrets/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c3888b5-8732-482d-8d5f-d1f5ec7ec4dc',
        'Gabon : le Président Brice Clotaire Oligui Nguema inaugure des  d’infrastructures à Kango',
        'Le président gabonais a inauguré à Kango plusieurs infrastructures, dont un complexe évangélique, une perception de trésorerie équipée et la remise des clés d’un logement réhabilité, pour améliorer la vie des habitants et soutenir l’économie locale.',
        'https://agpgabon.ga/gabon-le-president-brice-clotaire-oligui-nguema-inaugure-des-dinfrastructures-a-kango/',
        'AGP',
        'Business Intelligence',
        '2025-08-13T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9cb0240-6f47-4080-9270-cfa11394db1a',
        'Gabon : le « Roi Béni » impliqué dans le vol chez Ali Bongo Ondimba !',
        'L''article affirme que le roi béni serait impliqué dans un vol chez Ali Bongo Ondimba, suscitant des interrogations sur ses véritables intentions.',
        'https://gabonmediatime.com/gabon-le-roi-beni-implique-dans-le-vol-chez-ali-bongo-ondimba/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49fb8a53-d6cc-45e2-8a3e-b619aa83bc5f',
        'Libreville : Bilie-By-Nze plaide pour l’élection du maire au suffrage universel direct',
        'Nze Plaide a appelé à l''organisation d''une élection municipale à Libreville au suffrage universel direct pour renforcer la démocratie locale et mieux représenter les citoyens.',
        'https://gabonmediatime.com/libreville-bilie-by-nze-plaide-pour-lelection-du-maire-au-suffrage-universel-direct/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dab01c9f-6576-44fb-8460-1cbe4620ad86',
        'Législatives et locales 2025 : le gouvernement fixe les modalités des bulletins de vote',
        'Le gouvernement gabonais a fixé les modalités d''impression et de présentation des bulletins de vote pour les élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-le-gouvernement-fixe-les-modalites-des-bulletins-de-vote/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1cddc17e-aa8e-404c-8ba3-31d428023ddd',
        'Gabon/Inauguration de l’hôpital de Moanda : un pas de plus vers l’égalité d’accès aux soins',
        'L''inauguration de l''hôpital de Moanda au Gabon marque une avancée vers un accès plus égalitaire aux soins de santé dans la région.',
        'https://kongossanews.info/gabon-inauguration-de-lhopital-de-moanda-un-pas-de-plus-vers-legalite-dacces-aux-soins/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'acdfd9a8-39e1-4234-9bc3-bd9e9f6cd6ea',
        'Publié le 13 / 08 / 2025',
        'La mairie de Libreville, le Fonds départemental de solidarité (FDS) et l’École privée de gestion (EPG) appellent à un changement dans la gestion et l’organisation pour améliorer le service public et l’éducation.',
        'https://union.sonapresse.com/fr/mairie-de-libreville-fds-et-epg-pronent-le-changement',
        'L''union',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58bd877a-6dc3-43c0-bfb4-4bfd42033e55',
        'Publié le 13 / 08 / 2025',
        'La dernière journée de révision de la liste électorale a été marquée par une forte affluence avec de nombreux citoyens cherchant à s’inscrire ou à mettre à jour leurs informations, ce qui a créé une grande agitation.',
        'https://union.sonapresse.com/fr/revision-de-la-liste-electorale-le-grand-rush-au-dernier-jour',
        'L''union',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7afe7816-61a6-4aae-90cb-b46ae66e7e65',
        'Estuaire/Inauguration du bâtiment de perception de Kango : un nouvel élan pour la comptabilité publique, selon le DG de cette entité',
        'Un nouveau bâtiment de perception a été inauguré à Kango pour moderniser la gestion comptable et rapprocher l''administration des usagers, facilitant ainsi le traitement des opérations.',
        'https://agpgabon.ga/estuaire-inauguration-du-batiment-de-perception-de-kango-un-nouvel-elan-pour-la-comptabilite-publique-selon-le-dg-de-cette-entite/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '497ae440-ce6e-4cdf-b14f-c72e4d88ed07',
        'RDC : 10 ans de travaux forcés requis contre un ancien minisre de la justice',
        'Un ancien ministre de la Justice congolais, Constant Mutamba, a été condamné à 10 ans de travaux forcés pour le détournement de 19 millions de dollars destinés à la construction d’une prison à Kisangani.',
        'https://agpgabon.ga/rdc-10-ans-de-travaux-forces-requis-contre-un-ancien-minisre-de-la-justice/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74519c01-e0b4-4346-9b2c-331be2b83b38',
        'Football/UEFA : le PSG s’offre la Supercoupe',
        'Le Paris Saint-Germain a remporté sa première Super Coupe d’Europe en battant Tottenham aux tirs au but après un match où ils ont été menés 2-0 à la mi-temps.',
        'https://agpgabon.ga/football-uefa-le-psg-soffre-la-supercoupe/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0009f90d-cec9-4bb1-9991-ff6b5a916633',
        'Trésor Public : 𝗶𝗻𝗮𝘂𝗴𝘂𝗿ation d𝗲 𝗹𝗮 p𝗲𝗿𝗰𝗲𝗽𝘁𝗶𝗼𝗻 𝗱𝗲 𝗞𝗮𝗻𝗴𝗼',
        'La cérémonie d''inauguration du dispositif Kango, visant à améliorer la perception et la gestion des finances publiques, a été récemment organisée par le Trésor public au Gabon.',
        'https://gabonactu.com/blog/2025/08/14/tresor-public-%f0%9d%97%b6%f0%9d%97%bb%f0%9d%97%ae%f0%9d%98%82%f0%9d%97%b4%f0%9d%98%82%f0%9d%97%bfation-d%f0%9d%97%b2-%f0%9d%97%b9%f0%9d%97%ae-p%f0%9d%97%b2%f0%9d%97%bf%f0%9d%97%b0%f0%9d%97%b2/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '212689af-758f-4957-85bf-1e7d5dbd2efc',
        'Gabon : le « Roi Béni » impliqué dans le vol chez Ali Bongo Ondimba !',
        'L''article affirme que le roi Beni serait impliqué dans le vol ayant ciblé la résidence de l''ancien président Ali Bongo Ondimba.',
        'https://gabonmediatime.com/gabon-le-roi-beni-implique-dans-le-vol-chez-ali-bongo-ondimba/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeb4b415-b844-495a-9212-45e8dc7bfa9f',
        'Libreville : Bilie-By-Nze plaide pour l’élection du maire au suffrage universel direct',
        'Nze Plaide a plaidé pour que l’élection du maire de Libreville se fasse par suffrage universel direct, afin d’accroître la légitimité et la démocratie dans la ville.',
        'https://gabonmediatime.com/libreville-bilie-by-nze-plaide-pour-lelection-du-maire-au-suffrage-universel-direct/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '231e52a4-ea0d-4da2-b4f9-3ab036e059d1',
        'Législatives et locales 2025 : le gouvernement fixe les modalités des bulletins de vote',
        'Le gouvernement gabonais a fixé les modalités concernant la conception et la distribution des bulletins de vote pour les élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-le-gouvernement-fixe-les-modalites-des-bulletins-de-vote/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38acdb54-1f02-447a-b22b-853c34e63257',
        'Gabon/Inauguration de l’hôpital de Moanda : un pas de plus vers l’égalité d’accès aux soins',
        'L''inauguration de l''hôpital de Moanda au Gabon marque une avancée vers un accès plus égalitaire aux soins de santé pour la population locale.',
        'https://kongossanews.info/gabon-inauguration-de-lhopital-de-moanda-un-pas-de-plus-vers-legalite-dacces-aux-soins/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c532f217-6486-42d4-8b5c-22cca070f349',
        'Gabon/Gestion de la faune : reformes statutaires des agents et renforcement logistique au ministère des Eaux et Forêts',
        'Le ministère des Eaux et Forêts a présenté les actions des 100 premiers jours, incluant la gestion de la faune, la réforme des agents et le renforcement logistique, notamment par l’abattage administratif des éléphants et l’installation de clôtures électriques pour limiter les conflits homme-faune.',
        'https://agpgabon.ga/gabon-gestion-de-la-faune-reforme-statutaire-des-agents-et-renforcement-logistique-au-ministere-des-eaux-et-forets/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '257ede94-c49a-4376-a81f-cef2777406fe',
        'Gabon/Logement : le Conseil des ministres annonce des réformes structurelles',
        'Le gouvernement gabonais prévoit de réformes structurelles pour le secteur du logement, en combinant budget national, partenariats et régulations pour garantir son développement durable.',
        'https://agpgabon.ga/gabon-logement-le-conseil-des-ministres-annonce-des-reformes-structurelles/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef9870cd-d461-4ec5-88b3-a33a1da15fc7',
        'Gabon/Bilan des 100 jours du Gouvernement : 23 chantiers réalisés et 12 à venir au ministère des Transports et de la Marine Marchande',
        'En 100 jours, le ministère des Transports, de la Marine marchande et de la Logistique a réalisé 23 chantiers sur 50 objectifs fixés, avec notamment la création d’un bureau local pour l’immatriculation des navires sous pavillon gabonais.',
        'https://agpgabon.ga/gabon-bilan-des-100-jours-du-gouvernement-23-chantiers-realises-et-12-a-venir-au-ministere-des-transports-et-de-la-marine-marchande/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ce75895-d5e3-45fa-9c3e-b40abed89266',
        'Gabon : Le gouvernement veut régulariser 50 000 titres de propriété',
        'Le gouvernement gabonais prévoit de régulariser 50 000 titres de propriété foncière pour sécuriser les droits des citoyens et encourager l’investissement immobilier.',
        'https://directinfosgabon.com/gabon-le-gouvernement-veut-regulariser-50-000-titres-de-propriete/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a95f16b2-7ec1-4547-8aad-4d66e813d188',
        'Fougamou et Lambaréné se parent de nouvelles infrastructures',
        'La visite du président dans les villes de Fougamou et Lambaréné a permis de constater l’avancement des nouveaux projets d''infrastructures, notamment l’inauguration de la Maison de la Culture à Fougamou.',
        'https://vxp241.com/2025/08/14/fougamou-et-lambarene-se-parent-de-nouvelles-infrastructures/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd97b8a67-83d4-421c-83c6-7c9c18ee103b',
        'Les Gabonais partagés après l’interdiction de certains métiers aux étrangers',
        'Le gouvernement gabonais interdit aux étrangers d''exercer certains petits métiers pour lutter contre le chômage et mieux contrôler l''économie locale, ce qui divise l''opinion des citoyens.',
        'https://www.rfi.fr/fr/afrique/20250814-les-gabonais-partag%C3%A9s-apr%C3%A8s-l-interdiction-de-certains-m%C3%A9tiers-aux-%C3%A9trangers-%C3%A9conomie-gouvernement-restriction-nguema',
        'RFI',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28387046-d82b-454c-9741-1bfe2da81203',
        'Les Gabonais partagés après l’interdiction de certains métiers aux étrangers',
        'Le gouvernement gabonais a décidé d''interdire aux expatriés d''exercer certains petits métiers afin de lutter contre le chômage et de mieux contrôler l''économie locale.',
        'https://www.rfi.fr/fr/afrique/20250814-les-gabonais-partag%C3%A9s-apr%C3%A8s-l-interdiction-de-certains-m%C3%A9tiers-aux-%C3%A9trangers-%C3%A9conomie-gouvernement-restriction-nguema?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f041c620-ce3f-431c-8927-9b6ce389905d',
        'Programme GAB PÊCHE : 18 mois pour rembourser le crédit d’acquisition de la pirogue…',
        'Le programme GAB Pêche permet aux pêcheurs d’emprunter de l’argent pour acheter des équipements modernes, avec un remboursement prévu en 18 mois.',
        'https://directinfosgabon.com/programme-gab-peche-18-mois-pour-rembourser-le-credit-dacquisition-de-la-pirogue/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e9ea594-5aa2-4376-a9a9-44c039826325',
        'Transformation du manganèse : Après le Japon, l’Inde aussi veut sa part…',
        'Plusieurs pays, notamment le Japon et l’Inde, souhaitent investir dans la transformation du manganèse au Gabon, afin de profiter du potentiel minier du pays.',
        'https://directinfosgabon.com/transformation-du-manganese-apres-le-japon-linde-aussi-veut-sa-part/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aa942543-c770-4004-a01e-1bcc56792d7a',
        'Fonctionnaire : Fini les cumuls abusifs entre logement de fonction et indemnité',
        'Le gouvernement gabonais a adopté des mesures pour empêcher les fonctionnaires de cumuler indûment des logements de fonction et des indemnisations, afin de lutter contre les abus et améliorer la gestion des ressources publiques.',
        'https://directinfosgabon.com/fonctionnaire-fini-les-cumuls-abusifs-entre-logement-de-fonction-et-indemnite/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3855827-c9c6-4086-8e52-e5e13b0bee6e',
        '‎Gabon : Lutte contre la traite des êtres humains, le ministère de la Justice et l’OIM s’allient',
        'Une rencontre stratégique s’est tenue au Gabon pour renforcer la lutte contre la traite des êtres humains, en partenariat avec le ministère de la Justice et l’Organisation internationale pour les migrations (OIM).',
        'https://www.gabonreview.com/%e2%80%8egabon-lutte-contre-la-traite-des-etres-humains-le-ministere-de-la-justice-et-loim-sallient/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52513097-5b1a-49d9-9b21-669f918018be',
        'Le gouvernement engage une réforme profonde des comptes publics',
        'Le gouvernement prévoit une réforme profonde des comptes publics afin de soutenir une croissance économique d’au moins 10 % à moyen terme, en favorisant un secteur non pétrolier dynamique.',
        'https://vxp241.com/2025/08/14/le-gouvernement-engage-une-reforme-profonde-des-comptes-publics/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57aeeef1-b557-456b-9525-e883b3d0ece6',
        'Fly Gabon obtient le feu vert pour des vols réguliers vers Johannesburg',
        'Fly Gabon a obtenu en août 2025 un permis sud-africain pour effectuer des vols réguliers entre Libreville et Johannesburg, marquant une étape importante dans son développement régional.',
        'https://vxp241.com/2025/08/14/fly-gabon-obtient-le-feu-vert-pour-des-vols-reguliers-vers-johannesburg/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f2f31bf-9c05-4ff6-ba52-36750efc5278',
        'Charente-Maritime : la chaufferie biomasse à 10 millions d’euros bientôt en service chez Joubert-Plywood',
        'L''entreprise de Saint-Jean-d’Angély, spécialisée dans la fabrication de contreplaqués, va bientôt mettre en service une chaudière biomasse innovante de 10 millions d''euros, visant à réduire son impact environnemental.',
        'https://www.sudouest.fr/charente-maritime/saint-jean-d-angely/charente-maritime-la-chaufferie-biomasse-a-10-millions-d-euros-bientot-en-service-chez-joubert-plywood-25530916.php?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47ea153e-e40e-44d2-a100-753725a1023e',
        'Métiers du numérique : Plus de 800 personnes en formation à Port-Gentil',
        'Plus de 800 jeunes à Port-Gentil suivent une formation intensive dans les métiers du numérique, notamment grâce au programme GT Lab lancé en août 2025, qui vise à préparer la jeunesse gabonaise aux emplois liés aux nouvelles technologies.',
        'https://directinfosgabon.com/metiers-du-numerique-plus-de-800-personnes-en-formation-a-port-gentil/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad34df15-1235-40e5-b80a-46ca46da23b0',
        '"Les populations de Sindara, Dibwa et Oumba ont besoin d''eau et de l''électricité "',
        'Trois ans après l''achèvement des travaux financés par la Banque mondiale, les populations des cantons Sindara, Dibwa et Oumba restent sans accès à l''eau et à l''électricité, soulevant des interrogations sur la mise en service du projet.',
        'https://www.gabonews.com/fr/actus/politique/article/les-populations-de-sindara-dibwa-et-oumba-ont',
        'Gabonews',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9fef932-04ca-47ef-a084-8c48e4d0eac0',
        'Le Président Brice Clotaire Oligui Nguema inaugure plusieurs infrastructures majeures',
        'Le président Brice Clotaire Oligui Nguema continue ses visites dans le pays en inaugurant plusieurs infrastructures à Franceville, dans le but de renforcer les équipements publics au Gabon.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-president-brice-clotaire-oligui-nguema',
        'Gabonews',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e76f796-12de-410c-84ba-7c017d5e5e52',
        'Crise alimentaire en RDC, la flambée des prix menace des millions de vies',
        'La République démocratique du Congo fait face à une crise humanitaire aggravée par la forte augmentation des prix des aliments essentiels, rendant l’accès à la nourriture difficile pour de nombreux Congolais.',
        'https://www.gabonews.com/fr/actus/international/article/crise-alimentaire-en-rdc-la-flambee-des-prix',
        'Gabonews',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a10463e4-2e18-433f-843a-93116820b7a2',
        'Football : Nze Samake rejoint le Stade d’Abidjan',
        'Nze Samake, jeune footballeur gabonais de 23 ans, a signé pour deux saisons avec le club ivoirien Stade d’Abidjan, marquant sa première expérience à l’étranger.',
        'https://agpgabon.ga/football-nze-samake-rejoint-le-stade-dabidjan/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

