-- Batch 6 - Section 3/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'c288ef31-dedf-4351-bd85-771d17dbe477',
        'RDB – UDB : Mbatchi Pambou et ses compagnons attendent ‘’le retour de l’ascenseur’’',
        'Des représentants politiques affiliés au Rassemblement des bâtisseurs (RDB) attendent le retour d’opportunités politiques pour progresser, dans un contexte de tensions et d’attente d’un changement de situation.',
        'https://gabonactu.com/blog/2025/07/18/rdb-udb-mbatchi-pambou-et-ses-compagnons-de-lappel-dangondje-attendent-le-retour-de-lascenseur/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3ad69ea9-ca88-481f-ab42-37f7d99bc8fd',
        'Gabon : la SFI réaffirme son appui au développement des secteurs des infrastructures, de l’agro-industrie…',
        'La SFI réaffirme son soutien au développement des infrastructures et de l’agro-industrie au Gabon lors d’une rencontre avec le gouvernement gabonais.',
        'https://www.gabonreview.com/gabon-la-sfi-reaffirme-son-appui-au-developpement-des-secteurs-des-infrastructures-de-lagro-industrie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1843919-407b-473a-ac16-acce21e5f673',
        'Gouvernement : Barro Chambrier met la pression pour concrétiser la vision présidentielle',
        'Lors d’un Conseil interministériel, le vice-président du gouvernement a exhorté les ministres à faire preuve de plus d’implication et de rigueur pour concrétiser les promesses du président.',
        'https://www.gabonreview.com/gouvernement-barro-chambrier-met-la-pression-pour-concretiser-la-vision-presidentielle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '902731e1-2e23-4bb9-8cf1-79c164545a31',
        'Publié le 18 / 07 / 2025',
        'La Commission nationale des revenues (CNR) critique la gouvernance actuelle pour ses dérives et ses abus de pouvoir, appelant à des réformes pour renforcer la transparence et la démocratie.',
        'https://union.sonapresse.com/fr/gouvernance-la-cnr-fustige-les-derives-du-pouvoir-actuel',
        'L''union',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e553b87d-01e5-4cc7-84c2-63f2f403d3fc',
        'Publié le 18 / 07 / 2025',
        'L''entreprise minière Sonamès a réussi à transformer localement la gestion du manganèse, menant à une meilleure efficacité et à la réussite de ses projets.',
        'https://union.sonapresse.com/fr/transformation-locale-du-manganese-management-et-succes-acquis',
        'L''union',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1b92de5-ecc3-47d0-a906-3a5d9de8d1c4',
        'Publié le 18 / 07 / 2025',
        'Alice Lamou consacre sa vie à aider son prochain en menant des actions solidaires dans sa communauté, notamment à travers des initiatives éducatives et sociales.',
        'https://union.sonapresse.com/fr/alice-lamou-une-vie-au-service-de-son-prochain',
        'L''union',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6b96f245-4f30-49b0-a324-3a14a76627c5',
        'Gabon/Appui financier : Barro Chambrier échange avec la responsable Afrique centrale de la SFI',
        'La SFI a réaffirmé son engagement à soutenir le développement économique du Gabon en finançant des projets dans les secteurs des infrastructures, de l’agro-industrie et du tourisme, lors d’une rencontre avec le Vice-Président du gouvernement.',
        'https://agpgabon.ga/gabon-appui-financier-barro-chambrier-echange-avec-la-responsable-afrique-centrale-de-la-sfi/',
        'AGP',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17ca62cd-03e3-4b30-86f5-212d1528d309',
        'Université. Le Gabon supprime les bourses pour les étudiants aux États-Unis, au motif “qu’ils ne reviennent jamais”',
        'Le gouvernement gabonais a décidé de supprimer les bourses offertes aux étudiants partis étudier aux États-Unis, invoquant principalement le coût élevé de ces programmes et la difficulté pour certains étudiants de revenir dans le pays après leurs études.',
        'https://www.courrierinternational.com/article/universite-le-gabon-supprime-les-bourses-pour-les-etudiants-aux-etats-unis-au-motif-qu-ils-ne-reviennent-jamais_233288?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af820277-a343-490f-8d73-5fdbbcbdbf61',
        'Pétrole : Des soubresauts géopolitiques qui imposent au Gabon un choix stratégique',
        'La hausse des prix du pétrole liée aux tensions géopolitiques incite le Gabon à choisir entre profiter de cette opportunité pour relancer son économie ou risquer de s’enliser dans une dépendance accrue.',
        'https://directinfosgabon.com/petrole-des-soubresauts-geopolitiques-qui-imposent-au-gabon-un-choix-strategique/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '905d2ba7-b0da-48d7-bb71-3dd1762dcc24',
        'Port-Gentil :  formation sur le traitement non-opératoire des fractures des membres',
        'Un séminaire éducatif se tient du 17 au 19 juillet 2025 à l’Hôpital régional de N’tchengué de Port-Gentil, visant à renforcer les compétences du personnel médical sur les principes du traitement non opératoire des fractures des membres.',
        'https://gabonactu.com/blog/2025/07/18/port-gentil-les-personnels-medicaux-au-centre-dune-formation-sur-le-traitement-non-operatoire-des-fractures-des-membres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f94ed50-8ac3-4b5f-b19e-78eba6f2d7da',
        'Diabète de type 2 : le protocole thérapeutique expliqué au CHR de N’tchengué',
        'Un atelier organisé par le Centre hospitalier régional de N’tchengué a permis d''expliquer comment prendre en charge le diabète de type 2 en présentant le protocole thérapeutique adapté.',
        'https://gabonactu.com/blog/2025/07/18/diabete-de-type-2-le-protocole-therapeutique-explique-au-chr-de-ntchengue/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f0ce589-81d1-490b-8b5c-1fcadc84cfbe',
        'Vidéos secrètes de Nourredin Bongo : Le soutien du Barreau de Paris à Maître Eyué Békalé',
        'Le barreau de Paris exprime son soutien à l''avocate Gisèle Eyué Békalé face à une situation critique liée à des vidéos impliquant Nourredin Bongo.',
        'https://gabonactu.com/blog/2025/07/18/videos-secretes-de-nourredin-bongo-le-barreau-de-paris-soutien-a-maitre-eyue-bekale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e892acc6-4774-4527-bc6d-8bf4ae3f47ed',
        'Entrepreneuriat : le plaidoyer de Gaston Midoungani pour accélérer la croissance de la micro entreprise au Gabon',
        'L''article souligne l''importance de renforcer le soutien et les politiques publiques pour accélérer la croissance des micro-entreprises au Gabon, afin de stimuler l''économie locale et créer davantage d''emplois.',
        'https://mediapostegabon.com/entrepreneuriat-le-plaidoyer-de-gaston-midoungani-pour-accelerer-la-croissance-de-la-micro-entreprise-au-gabon/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd03d755a-2ecc-40f8-a07b-957fcfa6e341',
        'Mairie de Libreville : Adrien Nguema Mba pour un Libreville propre Mairie de Libreville : Séminaire de renforcement des capacité...',
        'Le maire d''Abi de Libreville a lancé un programme de nettoyage pour rendre la ville plus propre en impliquant la communauté et en sensibilisant les habitants à l''importance de l''hygiène urbaine.',
        'https://mediapostegabon.com/mairie-de-libreville-adrien-nguema-mba-pour-un-libreville-propre/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4d487677-822f-4e62-86eb-34e2d5f81a90',
        'Gabon : Ali Bongo Ondimba affirme reprendre « fermement » en main son parti politique',
        'L''ancien président gabonais Ali Bongo Ondimba, qui revendique la direction de l''ancien parti au pouvoir, a dénoncé une « ingérence inadmissible » en parlant depuis Londres.',
        'https://www.jeuneafrique.com/1707686/politique/gabon-ali-bongo-ondimba-affirme-reprendre-fermement-en-main-son-parti-politique/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e6c32bf0-dbe0-4e52-9605-1c2fe58baba0',
        'Entrepreneuriat : le plaidoyer de Gaston Midoungani pour accélérer la croissance de la micro entreprise au Gabon',
        'L''article souligne l''importance de soutenir et de simplifier les démarches pour développer la micro-entreprise au Gabon afin d’accélérer la croissance économique du pays.',
        'https://mediapostegabon.com/entrepreneuriat-le-plaidoyer-de-gaston-midoungani-pour-accelerer-la-croissance-de-la-micro-entreprise-au-gabon/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4b5c0a8-25ce-451e-baf6-f470ae123847',
        'Mairie de Libreville : Adrien Nguema Mba pour un Libreville propre Mairie de Libreville : Séminaire de renforcement des capacité...',
        'Le maire d''Okala Bedé, Adrien Nguema, a lancé une campagne de nettoyage à Libreville pour sensibiliser la population à maintenir la ville propre et à préserver l’environnement.',
        'https://mediapostegabon.com/mairie-de-libreville-adrien-nguema-mba-pour-un-libreville-propre/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-18T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6dcf2da3-0819-4477-9e5e-46845d94c5bd',
        'Hugues Otha clochardisé pour des raisons inavouées',
        'Un ancien adjudant-chef révèle avoir été abandonné dans la précarité et l’humiliation en raison d’injustices liées à son arrestation ou à des décisions politiques sous le régime d’Ali Bongo.',
        'https://gabonactu.com/blog/2025/07/18/hugues-otha-clochardise-pour-des-raisons-inavouees/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81db0257-1221-4544-82e1-b9d06d8ec5a1',
        'Gabon : Ali Bongo reprend la main sur le PDG et dénonce un «coup de force interne»',
        'Ali Bongo reprend le contrôle du Parti démocratique gabonais (PDG) en dénonçant un coup de force interne visant à le déstabiliser.',
        'https://gabonmediatime.com/gabon-ali-bongo-reprend-la-main-sur-le-pdg-et-denonce-un-coup-de-force-interne/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '421d6030-fb39-4e88-84b6-01e3d03a024b',
        'Loi de finances 2025 : coupe drastique de 5 milliards de Fcfa dans le budget des bourses du secondaire',
        'Le budget national prévoit une réduction de 5 milliards de FCFA dans le financement des bourses du secondaire pour l’année 2025.',
        'https://gabonmediatime.com/loi-de-finances-2025-coupe-drastique-de-5-milliards-de-fcfa-dans-le-budget-des-bourses-du-secondaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a384565b-1e2a-4bb6-9baa-a234020e849c',
        'Gabon : le congrès du FDS fixé au 27 juillet 2025 !',
        'Le congrès du FDS en Guinée-Bissau est prévu pour le 27 juillet 2025, afin de choisir de nouveaux dirigeants et de définir la future orientation du parti.',
        'https://gabonmediatime.com/gabon-le-congres-du-fds-fixe-au-27-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bbc2ca9d-e9a7-4081-8905-b7e932d4d4b9',
        'Ogooué-Maritime/Session criminelle : condamnée à 4 ans de prison pour  homicide involontaire sur une nonagénaire',
        'Une femme de 28 ans a été condamnée à 4 ans de prison pour avoir involontairement causé la mort d''une nonagénaire en l''étouffant avec une taie d''oreiller dans sa maison à Port-Gentil.',
        'https://agpgabon.ga/ogooue-maritime-session-criminelle-condamnee-a-4-ans-de-prison-pour-homicide-involontaire-sur-une-nonagenaire/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7796cdcd-ea51-4cf4-84c2-2703449266d2',
        'Gabon : Ali Bongo reprend la main sur le PDG et dénonce un «coup de force interne»',
        'Gabon : Ali Bongo reprend le contrôle du PDG après une tentative de coup de force interne, consolidant ainsi son pouvoir au sein de la direction.',
        'https://gabonmediatime.com/gabon-ali-bongo-reprend-la-main-sur-le-pdg-et-denonce-un-coup-de-force-interne/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0397280b-d2d7-4434-bee7-dd14f1406b07',
        'Loi de finances 2025 : coupe drastique de 5 milliards de Fcfa dans le budget des bourses du secondaire',
        'Le projet de loi de finances 2025 prévoit une réduction de 5 milliards de FCFA du budget consacré aux bourses d’études secondaires, impactant le financement de l’éducation dans ce secteur.',
        'https://gabonmediatime.com/loi-de-finances-2025-coupe-drastique-de-5-milliards-de-fcfa-dans-le-budget-des-bourses-du-secondaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf9e362c-4db0-4e5e-a22a-eef49546f00c',
        'Gabon : le congrès du FDS fixé au 27 juillet 2025 !',
        'Le congrès du FDS est fixé au 27 juillet 2025 afin de discuter des enjeux politiques et de renforcer l''unité du parti au Gabon.',
        'https://gabonmediatime.com/gabon-le-congres-du-fds-fixe-au-27-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40034bbb-1eb8-4bef-91cf-3271f2caf4d8',
        'Gabon/ projet Movingui Okolassi: cap vers une ville moderne, durable & inclusive',
        'Le projet Movingui-Okolassi, soutenu par la Caisse des Dépôts et Consignations du Gabon, vise à aménager un quartier innovant, durable, et inclusif dans la commune de Ntoum, en ligne avec la vision du président pour transformer la ville de Libreville en une métropole moderne.',
        'https://vxp241.com/2025/07/19/gabon-projet-movingui-okolassi-cap-vers-une-ville-moderne-durable-inclusive/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2c729c6-f01b-40d3-ae4f-6dfa0c4f45db',
        'Gabon: Fake news sur déportation des migrants en provenance des USA',
        'Une rumeur indique qu''après sa visite diplomatique et le mini sommet USA-Afrique, il existerait un accord secret entre l''administration Trump et le Gabon, suscitant des préoccupations dans l''opinion publique.',
        'https://vxp241.com/2025/07/19/gabon-fake-news-sur-deportation-des-migrants-en-provenance-des-usa/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6567184-8960-48ec-bfbb-bf6919026e52',
        'Les responsables du CCPE-ZON reçus par la Directrice générale de la Chambre de commerce',
        'Les responsables du centre CCPE-ZON ont rencontré la Direction de la Chambre de Commerce du Gabon pour envisager des partenariats visant à soutenir et formaliser les activités entrepreneuriales dans le pays.',
        'https://www.gabonews.com/fr/actus/societe/article/les-responsables-du-ccpe-zon-recus-par-la',
        'Gabonews',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7bc1842-292e-4045-8baa-f81c0ef912df',
        'Football : Aubameyang va faire son retour à l’OM',
        'Pierre-Emerick Aubameyang va signer un contrat de deux ans avec l’Olympique de Marseille, après avoir été libre de tout engagement et obtenu un bon retour lors de sa précédente saison avec le club.',
        'https://agpgabon.ga/football-aubameyang-va-faire-son-retour-a-lom/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63aeee13-19b8-4af5-938e-6dc01403371d',
        'Gabon/Baccalauréat 2025 : Camélia Ntoutoume Leclercq en mission de délibération à Koulamoutou et Franceville',
        'La ministre de l’Éducation s’est rendue à Koulamoutou et Franceville pour suivre et présider la délibération des résultats du baccalauréat 2025 dans ces centres.',
        'https://agpgabon.ga/gabon-baccalaureat-2025-camelia-ntoutoume-leclercq-en-mission-de-deliberation-a-koulamoutou-et-franceville/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fbb23a8-f106-494e-8373-ee6b0071855c',
        'Énergie : Le méga projet CAPS va entrer en phase opérationnelle en 2027',
        'Le projet de pipeline énergétique central, lancé en 2021, vise à améliorer l’accès à l’énergie en Afrique centrale et devrait devenir opérationnel d’ici 2027, après finalisation des études et du financement.',
        'https://directinfosgabon.com/energie-le-mega-projet-caps-va-entrer-en-phase-operationnelle-en-2027/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b3bc8e4-7592-435c-977b-e7a323d3ab54',
        'CEMAC : Les banques réclament 639 milliards de FCFA',
        'Les banques de la zone CEMAC ont besoin de 639 milliards de FCFA en liquidités en juillet 2025, ce qui montre des difficultés persistantes de trésorerie malgré l''assouplissement monétaire mis en place en 2023.',
        'https://directinfosgabon.com/cemac-les-banques-reclament-639-milliards-de-fcfa/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dc15f9a-8d4a-4238-a21b-10e5ef168abe',
        'Publié le 19 / 07 / 2025',
        'Il faut parfois se taire et écouter ceux qui savent plutôt que parler sans connaître, pour mieux comprendre et agir efficacement.',
        'https://union.sonapresse.com/fr/francois-ndong-obiang-reagir-ceux-qui-savent-ne-parlent-pas',
        'L''union',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '411188c2-6330-4fa5-a843-7ab0e9e2c6bf',
        'Publié le 19 / 07 / 2025',
        'Le président équatoguinéen Oligui Nguema a effectué une visite officielle en Turquie pour renforcer la coopération entre les deux pays.',
        'https://union.sonapresse.com/fr/diplomatie-oligui-nguema-invite-en-visite-officielle-en-turquie',
        'L''union',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5dd91caa-2d86-4aca-bc6f-c921d925ceda',
        'Taekwondo/Coupe Inter ligues : place aux combats',
        'Une compétition de taekwondo rassemblant 63 athlètes de 7 ligues provinciales a été lancée à Libreville, visant à promouvoir la discipline et à préparer la sélection pour les Mondiaux 2025 en Chine.',
        'https://agpgabon.ga/taekwondo-coupe-inter-ligues-place-aux-combats/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '34060d54-2dc3-4c76-9afa-b01d1e429c94',
        'Sénégal : les présidents Bissirou Diomaye Faye et Patrice Talon veulent insuffler un nouveau souffle à l’UEMOA',
        'Les présidents sénégalais Bissirou Diomaye Faye et béninois Patrice Talon souhaitent réformer et renforcer l’intégration économique de l’UEMOA pour favoriser une croissance plus équitable et une souveraineté monétaire accrue dans la région.',
        'https://agpgabon.ga/senegal-les-presidents-bissirou-diomaye-faye-et-patrice-talon-veulent-insuffler-un-nouveau-souffle-a-luemoa/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f72bb1a0-291c-4d7b-873c-0748d2bd64c6',
        'Burkina Faso : Le pouvoir s’apprête à dissoudre la commission électoral',
        'Le gouvernement burkinabè prévoit de dissoudre la Commission électorale nationale pour la réformer, dans un contexte de transition sous régime militaire depuis 2022, afin de renforcer la transparence des élections.',
        'https://agpgabon.ga/burkina-faso-le-pouvoir-sapprete-a-dissoudre-la-commission-electoral/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f972f094-3587-4a9b-a3a1-9004b9815e48',
        '»Le Code du travail gabonais commenté », recueil d’Augustin Émane présenté aux Port-Gentillais',
        'Un expert en droit du travail au Gabon, Augustin Emane, a présenté un recueil commenté sur le Code du travail gabonais lors d''une visite aux Port-Gentillais.',
        'https://gabonactu.com/blog/2025/07/19/le-code-du-travail-gabonais-commente-recueil-daugustin-emane-presente-aux-port-gentillais/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0ebb2c0-447d-45a9-8f82-cea5f3839509',
        'PDG : Ali Bongo Ondimba désavoue formellement Blaise Louémbé',
        'Ali Bongo Ondimba a publié une vidéo dans laquelle il désavoue officiellement Blaise Louémbé, ce qui a suscité des réactions sur les réseaux sociaux.',
        'https://gabonactu.com/blog/2025/07/19/pdg-ali-bongo-desavoue-formellement-blaise-louembe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b51a82b9-d406-4022-b267-a744e0228f23',
        'Publié le 19 / 07 / 2025',
        'Il est préférable de s’exprimer uniquement lorsque l’on possède des connaissances solides, car parler sans savoir peut causer des malentendus ou des erreurs.',
        'https://union.sonapresse.com/fr/francois-ndong-obiang-reagir-ceux-qui-savent-ne-parlent-pas',
        'L''union',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41e332e8-d916-443d-bc89-81d1cbe1fda9',
        'Publié le 19 / 07 / 2025',
        'Le président de la République gabonaise, Oligui Nguema, a été reçu en visite officielle en Turquie, renforçant ainsi les liens diplomatiques et économiques entre les deux pays.',
        'https://union.sonapresse.com/fr/diplomatie-oligui-nguema-invite-en-visite-officielle-en-turquie',
        'L''union',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e65fd895-0f49-4bab-98a0-0eb5be506c6c',
        'Gabon/Baccalauréat général 2025 : 100 % de réussite au second tour',
        'Tous les candidats admissibles au premier tour du baccalauréat général 2025 ont été officiellement déclarés admis après le second tour, témoignant d’un taux de réussite exceptionnel grâce aux efforts éducatifs.',
        'https://agpgabon.ga/gabon-baccalaureat-general-2025-100-de-reussite-au-second-tour/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e74187d7-1f61-457d-a986-707eb8e5fb74',
        'Gabon/Justice : 300 postes à pourvoir pour renforcer l’appareil judiciaire',
        'Le gouvernement gabonais lance quatre concours pour recruter 300 agents judiciaires, dont des magistrats et greffiers, afin de moderniser le système judiciaire et améliorer la gestion des dossiers.',
        'https://agpgabon.ga/gabon-justice-300-postes-a-pourvoir-pour-renforcer-lappareil-judiciaire/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.475Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b30b548e-5d86-4ab1-9dd2-4b4f8f512b61',
        'Gabon/Handball : Melkiade Meye, nouveau président de la Ligue provinciale de l’Estuaire',
        'Melkiade Meye a été élu seul candidat à la tête de la Ligue provinciale de handball de l’Estuaire, avec 100 % des voix, et prévoit d''organiser un tournoi amical inter-ligues pour débuter son mandat.',
        'https://agpgabon.ga/gabon-handball-melkiade-meye-nouveau-president-de-la-la-ligue-provinciale-de-lestuaire/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b1d4c62-cb23-45de-a164-85fd29fba1f0',
        'Les sapeurs-pompiers dans une cité totalement rénovée',
        'Les casernes des sapeurs-pompiers, notamment celle de Nomba à Owendo, ont été entièrement rénovées par le président Brice Clotaire Oligui Nguema, dans plusieurs provinces du pays.',
        'https://gabonactu.com/blog/2025/07/19/les-sapeurs-pompiers-dans-une-cite-totalement-renovee/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cebed7b5-8ac3-44d5-9ba0-95368151e4b3',
        'Cadre de vie : la Cité des Sapeurs-Pompiers du Centre de Secours de Nomba fait peau neuve À Tchibanga, l’Association Bane Ba Nda...',
        'Le centre de secours de Nomba a été rénové pour améliorer la qualité de vie de ses sapeurs-pompiers et renforcer leur efficacité lors des interventions.',
        'https://mediapostegabon.com/cadre-de-vie-la-cite-des-sapeurs-pompiers-du-centre-de-secours-de-nomba-fait-peau-neuve/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a7c4e62f-083a-4b4b-953c-17f67ab15099',
        'Gabon : L’humoriste digital Roméo MD nominé aux Digima Movie Awards 2025',
        'Roméo MD, humoriste digital gabonais, est nommé dans trois catégories aux Digima Movie Awards 2025 pour sa production «L’Électricien», soulignant sa montée en popularité en Afrique.',
        'https://agpgabon.ga/gabon-lhumoriste-digital-romeo-md-nomine-aux-digima-movie-awards-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6ce9325-3748-4c52-ad59-fc401b84e25a',
        'Gabon : Des bourses pour de jeunes femmes leaders africaines',
        'Le gouvernement gabonais, en partenariat avec la Commission de l’Union africaine, a lancé un appel à candidatures pour la quatrième promotion de bourses destinées à de jeunes femmes leaders africaines, afin de promouvoir leur engagement et leur influence dans leurs communautés.',
        'https://agpgabon.ga/gabon-des-bourses-pour-de-jeunes-femmes-leaders-africaines/',
        'AGP',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a608d6db-38f8-4db6-ba48-206d8cf5e8dc',
        'Général Pascal Ianni : "Nous sommes engagés dans une guerre informationnelle contre la Russie"',
        'Le général Pascal Ianni explique que la France mène une guerre de l''information contre la Russie pour défendre ses intérêts et contrer la désinformation.',
        'https://www.france24.com/fr/%C3%A9missions/au-c%C5%93ur-de-l-info-l-invit%C3%A9/20250719-g%C3%A9n%C3%A9ral-pascal-ianni-nous-sommes-engag%C3%A9s-dans-une-guerre-informationnelle-contre-la-russie?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '163b0c72-131b-4f42-b8bd-5e9f4d08a665',
        'Cadre de vie : la Cité des Sapeurs-Pompiers du Centre de Secours de Nomba fait peau neuve À Tchibanga, l’Association Bane Ba Nda...',
        'Le centre de secours de Nomba a été rénové pour offrir un meilleur cadre de vie aux sapeurs-pompiers, améliorant ainsi leur efficacité et leur environnement de travail.',
        'https://mediapostegabon.com/cadre-de-vie-la-cite-des-sapeurs-pompiers-du-centre-de-secours-de-nomba-fait-peau-neuve/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-19T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

