-- Batch 1 - Section 7/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '5661c42a-399f-489a-a708-a7b604fe1a29',
        'Liberté économique : un pas en arrière, un saut dans l’incertitude pour le Gabon',
        'L''indice de liberté économique 2025 situe le Gabon au 110ᵉ rang mondial avec une baisse de score, révélant des obstacles persistants à l''initiative privée et une gouvernance économique inefficace.',
        'https://www.gabonreview.com/liberte-economique-un-pas-en-arriere-un-saut-dans-lincertitude-pour-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services, Éducation',
        '2025-03-10T00:00:00.000Z',
        '2025-09-15T23:06:12.277Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ac8249bd-1774-4c83-9a43-045215d99fa5',
        'Présidentielle 2025 / Publication de la liste des candidats : la CNOCER a-t-elle violé la loi ?',
        'La publication des candidats pour la présidentielle de 2025 soulève des questions sur la légalité de la candidature de Stéphane Germain Iloko Boussengui, en raison de sa démission récente du Parti démocratique gabonais.',
        'https://www.gabonreview.com/presidentielle-2025-publication-de-la-liste-des-candidats-la-cnocer-a-t-elle-viole-la-loi/',
        'Gabon Review',
        'Autres',
        '2025-03-10T00:00:00.000Z',
        '2025-09-15T23:06:12.277Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2abc5e8-f5a6-4946-b2a9-e46c0f8a0fe0',
        'Liberté économique : un pas en arrière, un saut dans l’incertitude pour le Gabon',
        'Selon l''Indice de liberté économique 2025, le Gabon se classe 110e au niveau mondial avec un score de 56,3, reflétant un recul économique et suscitant des inquiétudes quant à l''efficacité des réformes entreprises.',
        'https://www.gabonreview.com/liberte-economique-un-pas-en-arriere-un-saut-dans-lincertitude-pour-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.277Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8144b472-c353-4dc8-a211-a7208a07c5cd',
        'Candidatures en vue de la présidentielle : Une ombre sur la Transition',
        'Le processus de sélection des candidats à la présidentielle au Gabon est critiqué pour ses critères d’éligibilité restrictifs et son manque de transparence, remettant en question la crédibilité et la compétitivité de l’élection à venir.',
        'https://www.gabonreview.com/candidatures-en-vue-de-la-presidentielle-une-ombre-sur-la-transition/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.277Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35979113-55b2-4774-9210-07d99054428e',
        'Soutien à l’entrepreneuriat : Le geste de cœur du MORAL',
        'Le Mouvement Rationnel pour la Libération (MORAL) a soutenu les jeunes entrepreneurs gabonais en leur fournissant gratuitement des étals, parasols et autres accessoires de vente.',
        'https://directinfosgabon.com/soutien-a-lentrepreneuriat-le-geste-de-coeur-du-moral/',
        'Direct infos Gabon',
        'Services, Business Femme',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.277Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e0b6b772-f405-46d1-b87e-fd268d156fed',
        'Gabon : Alain-Claude Bilie-By-Nze dévoile son projet de société pour la présidentielle d’avril 2025',
        'Alain-Claude Bilie-By-Nze a dévoilé son projet de société pour l''élection présidentielle gabonaise d’avril 2025, axé sur la réduction du chômage des jeunes, le renforcement de la protection sociale et la réforme des institutions.',
        'https://www.gabonews.com/fr/actus/politique/article/gabon-alain-claude-bilie-by-nze-devoile-son',
        'Gabonews',
        'Numérique / Digital, Services, Éducation, Finances, Business Femme',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.278Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd99f358-1014-4a86-8bdf-7fef9d50fca1',
        'Comilog : Reprise du travail le 11 mars',
        'Après trois jours de grève, les travailleurs de la Compagnie Minière de l’Ogooué (Comilog) reprennent le travail le 11 mars suite à des discussions prometteuses avec le Président de la Transition.',
        'https://directinfosgabon.com/comilog-reprise-du-travail-le-11-mars/',
        'Direct infos Gabon',
        'Services, Finances, Numérique / Digital',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.278Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57ac120f-1794-4653-8d37-afc4cfebc922',
        'Qui est Alain-Claude Bilie By Nze le probable président du Gabon ?',
        'Alain-Claude Bilie-By-Nze, homme politique gabonais ayant occupé de nombreux postes ministériels de haut niveau, est présenté comme le probable candidat à la présidence du Gabon grâce à son parcours riche et influent.',
        'https://gabonactu.com/blog/2025/03/11/qui-est-alain-claude-bilie-by-nze-le-probable-president-du-gabon/',
        'Gabon Actu',
        'Autres',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.278Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1be13b64-d200-4a12-92af-adc3af2bd166',
        'PID/PIH : Les projets ambitieux d’Assala Energy pour 2025',
        'En 2025, Assala Energy prévoit de réaliser plusieurs projets majeurs, incluant la construction d''écoles, la modernisation de centres médicaux et l’expansion de son engagement sur l’ensemble du territoire national pour répondre aux attentes stratégiques de l’État gabonais.',
        'https://directinfosgabon.com/pid-pih-les-projets-ambitieux-dassala-energy-pour-2025/',
        'Direct infos Gabon',
        'Éducation, Services',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.278Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eeac2929-076f-4168-95bb-238161dd2524',
        'Présidentielle 2025 : Bilie-By-Nze entre rupture, nouvelle espérance et relève des défis socio-économiques et institutionnels',
        'Alain-Claude Bilie-By-Nze annonce sa candidature à la présidentielle gabonaise de 2025 en proposant des réformes socio-économiques et institutionnelles majeures pour lutter contre le chômage et renforcer l’indépendance nationale.',
        'https://www.gabonreview.com/presidentielle-2025-bilie-by-nze-entre-rupture-nouvelle-esperance-et-releve-des-defis-socio-economiques-et-institutionnels/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Finances, Business Femme',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.278Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d3591c4-cd5a-4b01-a61b-8d164bdd1bae',
        '« Les Flux financiers illicites vont en l’encontre de la morale mais aussi de l’efficacité économique » (Nestor Mbou, président ...',
        'Le président de la Commission nationale de lutte contre la corruption et l’enrichissement (CNLCEI), Nestor Mbou, a souligné que les flux financiers illicites nuisent à la morale et à l’efficacité économique du Gabon, rendant impérative la lutte contre ce phénomène pour le développement du pays.',
        'https://gabonactu.com/blog/2025/03/10/les-flux-financiers-illicites-vont-en-lencontre-de-la-morale-mais-aussi-de-lefficacite-economique-nestor-mbou-president-de-la-cnlcei/',
        'Gabon Actu',
        'Numérique / Digital, Finances, Services',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.279Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b880cdf-0945-4480-b056-118e2becfbc8',
        'Suivi des forêts : l’Afrique centrale renforce ses capacités grâce à la télédétection',
        'L''Afrique centrale renforce ses capacités de suivi forestier grâce à un atelier organisé par la FAO à Libreville, destiné à former des experts à l''utilisation de la télédétection pour surveiller les forêts et combattre la déforestation.',
        'https://www.gabonreview.com/suivi-des-forets-lafrique-centrale-renforce-ses-capacites-grace-a-la-teledetection/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Agriculture',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.279Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93a9010a-da75-44be-bc20-0dbcd242cb95',
        'Un câble souterrain défectueux à l’origine des perturbations sur une partie du réseau électrique de Libreville',
        'Un câble électrique souterrain défectueux dans la zone des Trois Quartiers de Libreville a causé des pannes d’électricité dans plusieurs quartiers le 10 mars 2025, et les équipes de la SEEG travaillent à rétablir l’alimentation.',
        'https://gabonactu.com/blog/2025/03/10/un-cable-souterrain-defectueux-a-lorigine-des-perturbations-sur-une-partie-du-reseau-electrique-de-libreville/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.279Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '32c56533-124a-4943-99d2-64aab71469fb',
        'Affaire Opiangah : «Il doit rentrer chez lui !» (Bilie-By-Nze)',
        'Alain-Claude Bilie-By-Nze, candidat à la présidentielle 2025, demande la libération d’Hervé Patrick Opiangah et l’organisation d’un procès équitable pour Sylvia et Noureddin Bongo, dénonçant les charges contre eux comme sans fondement.',
        'https://www.gabonreview.com/affaire-opiangah-il-doit-rentrer-chez-lui-bilie-by-nze/',
        'Gabon Review',
        'Autres',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.279Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bae3342a-25ab-4d7b-88d4-9b06527721c8',
        'Éducation et emploi au Gabon : le dilemme d’une jeunesse en quête d’avenir',
        'Le Premier ministre gabonais appelle à réformer le système éducatif pour mieux aligner la formation des jeunes avec les besoins du marché du travail, face au chômage élevé des diplômés.',
        'https://www.gabonreview.com/education-et-emploi-au-gabon-le-dilemme-dune-jeunesse-en-quete-davenir/',
        'Gabon Review',
        'Éducation, Numérique / Digital, Services',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.280Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14b5fcab-bea8-475d-923b-fa90186d2660',
        'Le Groupe Sogafric soutient l’ITO avec un don d’équipements informatiques',
        'Le Groupe Sogafric a fait don d’équipements informatiques à l’Institut de technologies d’Owendo (ITO) pour améliorer la formation des étudiants et renforcer les capacités techniques de l’établissement.',
        'https://www.gabonreview.com/le-groupe-sogafric-soutient-lito-avec-un-don-dequipements-informatiques/',
        'Gabon Review',
        'Numérique / Digital, Éducation',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.280Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7fe664a-398d-4a2a-a390-f996cf8ab72a',
        'Emploi au Gabon : repenser la formation pour une insertion professionnelle réussie',
        'Le Premier ministre gabonais Raymond Ndong Sima a lancé les Assises nationales de l’emploi pour réformer la formation professionnelle et améliorer l’insertion des jeunes sur le marché du travail.',
        'https://www.gabonreview.com/emploi-au-gabon-repenser-la-formation-pour-une-insertion-professionnelle-reussie/',
        'Gabon Review',
        'Éducation, Numérique / Digital, Services, Finances, Agriculture, Tourisme, Business Femme',
        '2025-03-11T00:00:00.000Z',
        '2025-09-15T23:06:12.280Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2bb45e32-1404-4cb1-a253-cc27bf732f00',
        'Gabon : Oligui Nguema sur le chantier de la Baie des Rois devant générer 15 à 20 000 emplois',
        'Le président Brice Clotaire Oligui Nguema a visité le chantier de la Baie des Rois à Libreville, un projet ambitieux visant à créer un pôle d’affaires moderne générant entre 15 000 et 20 000 emplois.',
        'https://www.gabonreview.com/gabon-oligui-nguema-sur-le-chantier-de-la-baie-des-rois-devant-generer-15-a-20-000-emplois/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce, Éducation, Agriculture, Business Femme, Tourisme',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.280Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb410206-61c6-466e-a18f-b5097723078f',
        'Présidentielle 2025 : Mise en place de la Commission spéciale chargée de l’accueil et de l’encadrement des observateurs',
        'À l''approche des élections présidentielles du 12 avril 2025, le Ministre de l’Intérieur et de la Sécurité a annoncé la création d''une Commission spéciale chargée d’accueillir et d''encadrer les observateurs, invitant les missions nationales et internationales à soumettre leurs demandes d’accréditation avant le 31 mars 2025.',
        'https://directinfosgabon.com/presidentielle-2025-mise-en-place-de-la-commission-speciale-chargee-de-laccueil-et-de-lencadrement-des-observateurs/',
        'Direct infos Gabon',
        'Autres',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.281Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b421c5be-311b-4b80-b5a1-c3bb0c63a915',
        'Mumbande : Une association pour l’unité des enfants de Ndendé autour de la politique du Président Oligui Nguema',
        'L''Association Mumbande a été lancée à Ndendé pour unir les jeunes autour des politiques du Président de la Transition, Brice Clotaire Oligui Nguema, et promouvoir le développement communautaire dans le Département de la Dola.',
        'https://www.gabonews.com/fr/actus/politique/article/mumbande-une-association-pour-l-unite-des-enfants',
        'Gabonews',
        'Numérique / Digital, Éducation, Services, Business Femme',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.281Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b387c92-b744-4513-9441-814fe9c3c19b',
        'Oligui Nguema serait l’otage du PDG qu’il faut délivrer, selon Me Anges Kevin Nzigou',
        'Me Anges Kevin Nzigou, Secrétaire Exécutif du PLC, affirme lors d’une tournée politique à Marseille que le Président de la Transition Brice Clotaire Oligui Nguema est un otage du Parti démocratique gabonais qu’il faut délivrer pour assurer un renouveau politique au Gabon.',
        'https://gabonactu.com/blog/2025/03/11/oligui-nguema-serait-lotage-du-pdg-quil-faut-delivrer-selon-me-anges-kevin-nzigou/',
        'Gabon Actu',
        'Autres',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.281Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '275ee7b5-04bb-4bc9-bf2e-679e06a7598d',
        'Setrag : AGL assure avec succès le déchargement de 3242 rails au port d’Owendo',
        'AGL Gabon a réussi le déchargement de 3 242 rails au port d’Owendo pour SETRAG, démontrant leur expertise en logistique et contribuant au développement des infrastructures ferroviaires gabonaises.',
        'https://directinfosgabon.com/setrag-agl-assure-avec-succes-le-dechargement-de-3242-rails-au-port-dowendo/',
        'Direct infos Gabon',
        'Logistique, Services, Commerce',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.282Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc810c50-01f2-4c9a-8b41-5c28bdd12664',
        'Sobraga, un acteur clé de la formation et de l’emploi au Gabon',
        'Sobraga, premier employeur privé au Gabon, joue un rôle essentiel dans la formation et l’emploi des jeunes en collaborant avec le ministère du Travail et en développant des programmes de formation interne pour combler le déficit de compétences dans l’industrie agroalimentaire.',
        'https://www.gabonreview.com/sobraga-un-acteur-cle-de-la-formation-et-de-lemploi-au-gabon/',
        'Gabon Review',
        'Éducation, Services, Numérique / Digital',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.282Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c622dd71-924a-4e12-be28-113fd8f2d452',
        'AGL Gabon : débarquement à Owendo de 3 242 rails pour le chemin de fer gabonais',
        'AGL Gabon a déchargé avec succès 3 242 rails au port d’Owendo pour soutenir le développement du chemin de fer gabonais en partenariat avec la SETRAG.',
        'https://gabonactu.com/blog/2025/03/11/agl-gabon-debarquement-a-owendo-de-3-242-rails-pour-le-chemin-de-fer-gabonais/',
        'Gabon Actu',
        'Numérique / Digital, Services, Commerce, Agriculture',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.282Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ea2aeef0-e49d-4271-a023-37f84f721579',
        'CNSS : Une journée de réflexion pour réformer les pensions vieillesses',
        'La CNSS a organisé une journée de réflexion le 11 mars 2025 à Libreville pour engager des réformes visant à assurer la viabilité financière et l’efficacité des pensions vieillesses au Gabon.',
        'https://directinfosgabon.com/cnss-une-journee-de-reflexion-pour-reformer-les-pensions-vieillesses/',
        'Direct infos Gabon',
        'Finances, Éducation, Numérique / Digital',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.282Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '29c07ca7-ee05-469e-8edf-43322a701d5c',
        'Eau potable et assainissement : vers l’achèvement du projet PIEPAL au Gabon',
        'Le projet PIEPAL, soutenu par la Banque Africaine de Développement, atteint 95 % d’achèvement technique au Gabon et est en phase finale, promettant un accès amélioré à l’eau potable pour Libreville et ses environs.',
        'https://www.gabonreview.com/eau-potable-et-assainissement-vers-lachevement-du-projet-piepal-au-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.283Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c38be726-cd3f-47c5-b8b3-bc581c4e26a2',
        'Pétrole : l’ONEP fait planer un nuage sombre sur le secteur pétrolier gabonais',
        'L’Organisation nationale des employés du pétrole (ONEP) menace de paralyser le secteur pétrolier gabonais en raison du non-respect par les sociétés pétrolières de ses préavis concernant l''emploi et les paiements des salaires des employés.',
        'https://gabonactu.com/blog/2025/03/11/petrole-lonep-fait-planer-un-nuage-sombre-sur-le-secteur-petrolier-gabonais/',
        'Gabon Actu',
        'Services, Finances',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.283Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3346bad-7d9f-4476-bd03-29ce6b8ff6e7',
        'La CNNII relance officiellement ses activités avec une nouvelle flotte',
        'La Compagnie de Navigation Intérieure Internationale (CNNII) relance officiellement ses activités avec une nouvelle flotte navale, renforçant ainsi le transport maritime national et optimisant les échanges commerciaux entre Libreville, Port-Gentil et Lambaréné.',
        'https://directinfosgabon.com/la-cnnii-relance-officiellement-ses-activites-avec-une-nouvelle-flotte/',
        'Direct infos Gabon',
        'Transport, Services, Commerce, Numérique / Digital',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.283Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5520dd8-c9c6-4503-a9e9-6c0a99604f7f',
        'Présidentielle 2025 : Le processus d’accréditation des observateurs officiellement lancé',
        'Le gouvernement gabonais a officiellement lancé le processus d''accréditation des observateurs électoraux pour l''élection présidentielle de 2025 afin d''assurer une observation impartiale et de renforcer la transparence du scrutin.',
        'https://www.gabonreview.com/presidentielle-2025-le-processus-daccreditation-des-observateurs-officiellement-lance/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.283Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f808b4de-3d2c-4fb7-ab33-b3969d9e33f6',
        'Relance de l’Economie : Mark Alexandre Doumba prend conseil chez Oyima',
        'Le Ministre de l’Économie gabonaise, Mark Alexandre Doumba, a rencontré le Président de la Fédération des Entreprises du Gabon, Henri-Claude Oyima, pour discuter des initiatives visant à relancer l’économie nationale en renforçant l’investissement, le climat des affaires et l’emploi.',
        'https://directinfosgabon.com/relance-de-leconomie-mark-alexandre-doumba-prend-conseil-chez-oyima/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f79ee60e-eeee-42de-843c-527987022bd9',
        'Formation minière : 50 jeunes Gabonais en route pour l’Australie',
        'Le programme « We Train For Gabon–Destination Australie » lancé par Ivindo Iron et l’État gabonais envoie 50 jeunes Gabonais en Australie pour une formation avancée dans le secteur minier afin de développer les compétences locales et soutenir le développement économique du pays.',
        'https://www.gabonreview.com/formation-miniere-50-jeunes-gabonais-en-route-pour-laustralie/',
        'Gabon Review',
        'Éducation, Services',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d281235-c811-4385-9d6a-0f90abebe38f',
        'Réforme des retraites : la CNSS en quête d’un équilibre financier',
        'La Caisse nationale de sécurité sociale du Gabon envisage une réforme urgente du système de retraite afin de rétablir son équilibre financier face à un déficit structurel croissant.',
        'https://www.gabonreview.com/reforme-des-retraites-la-cnss-en-quete-dun-equilibre-financier/',
        'Gabon Review',
        'Finances, Numérique / Digital, Éducation',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c27d77c-fcbc-4199-86b3-56b88b959afc',
        'Présidentielle 2025 : Jean Remy Yama, un candidat entravé mais déterminé',
        'Jean Remy Yama, candidat à la présidentielle de 2025, conteste le rejet de sa candidature par la CNOCER pour insuffisance de preuves de sa nationalité gabonaise et reste déterminé à poursuivre son ambition présidentielle.',
        'https://www.gabonreview.com/presidentielle-2025-jean-remy-yama-un-candidat-entrave-mais-determine/',
        'Gabon Review',
        'Autres',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1501cd89-5c3a-487e-b9be-6090cad5a332',
        'Affaire Sylvia et Noureddin Bongo : l’ex-ambassadeur de France au Gabon visé par une plainte',
        'Les diplomates français au Gabon, dont l’ex-ambassadeur Alexis Lamek, sont poursuivis en France pour avoir omis de dénoncer les conditions de détention de Sylvia et Noureddin Bongo.',
        'https://www.gabonreview.com/affaire-sylvia-et-noureddin-bongo-lambassadeur-de-france-au-gabon-vise-par-une-plainte/',
        'Gabon Review',
        'Autres',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3883b391-9944-4637-9648-49256f089192',
        'Présidentielle 2025 : le PDG annoncera son soutien à un candidat le 19 mars',
        'À un mois des élections présidentielles de 2025, le Parti démocratique gabonais (PDG) annoncera le 19 mars le candidat qu’il soutiendra, en mettant l’accent sur l’unité et le développement du Gabon.',
        'https://www.gabonreview.com/presidentielle-2025-le-pdg-annoncera-son-soutien-a-un-candidat-le-19-mars/',
        'Gabon Review',
        'Autres',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.284Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '19ee3a22-41b0-43be-8ad2-34a271b5f2cf',
        'Présidentielle 2025 : Oligui Nguema veut «Un nouveau chapitre pour le Gabon»',
        'Lors de la présidentielle de 2025 au Gabon, Brice Clotaire Oligui Nguema, président de la Transition, propose un programme axé sur des réformes profondes, le développement durable et l’unité nationale pour inaugurer un « nouveau chapitre » pour le pays.',
        'https://www.gabonreview.com/presidentielle-2025-oligui-nguema-veut-un-nouveau-chapitre-pour-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture, Business Femme, Tourisme',
        '2025-03-12T00:00:00.000Z',
        '2025-09-15T23:06:12.285Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3cb4de75-91eb-415b-ac2d-c263c79c5fac',
        'PIEPAL : La livraison des travaux repoussée (encore) de…6 mois !',
        'Le programme PIEPAL visant à améliorer l''accès à l''eau potable et à l''assainissement à Libreville voit sa livraison repoussée de six mois, avec une nouvelle échéance fixée à décembre 2025.',
        'https://directinfosgabon.com/piepal-la-livraison-des-travaux-repoussee-encore-de-6-mois/',
        'Direct infos Gabon',
        'Services, Agriculture',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.285Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ff6ef1d-2109-44c0-8217-0854390c8206',
        'Présidentielle 2025 : Michel Ongoundou Loundah fait-Il peur au système ?',
        'Michel Ongoundou Loundah, candidat du Parti REAGIR à la présidentielle 2025, accuse la Commission Nationale d’Organisation et de Coordination des Elections de manifester une connivence pour empêcher sa participation à l’élection.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-michel-ongoundou-loundah-fait',
        'Gabonews',
        'Autres',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.285Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e895b5d-c2e3-4170-9f39-70e64d752994',
        'Gabon : Nouvelle menace des employés du pétrole',
        'Les employés du pétrole au Gabon, représentés par l''ONEP, menacent de lancer une grève le 22 mars 2025 si un accord satisfaisant n''est pas trouvé d''ici le 21 mars.',
        'https://www.gabonreview.com/gabon-nouvelle-menace-des-employes-du-petrole/',
        'Gabon Review',
        'Autres',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.285Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97b9efb6-cf31-4e95-913c-6a958a11fed3',
        'L’Alliance pour l’Avenir engagée autour de la candidature d’Oligui Nguema',
        'L’Alliance pour l’Avenir réaffirme son soutien total à la candidature de Brice Clotaire Oligui Nguema pour l’élection présidentielle de mars 2025 au Gabon.',
        'https://gabonactu.com/blog/2025/03/13/lalliance-pour-lavenir-engagee-autour-de-la-candidature-doligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.286Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f3113d9-24b4-426c-9578-9c323d08548d',
        'Fer de Bélinga : 50 jeunes Gabonais en formation en Australie',
        'Ivindo Iron, en partenariat avec le gouvernement gabonais, a lancé le programme "We Train For Gabon – Destination Australie" visant à former 50 jeunes Gabonais dans le secteur minier en Australie afin de renforcer leurs compétences et soutenir le développement économique du pays.',
        'https://directinfosgabon.com/fer-de-belinga-50-jeunes-gabonais-en-formation-en-australie/',
        'Direct infos Gabon',
        'Éducation, Services, Numérique / Digital',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.286Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3fc9f22a-061f-43d6-9568-d56258d31f34',
        'Séance de travail avec l’Institut National de la Jeunesse et des Sports',
        'Le Ministre de la Jeunesse et des Sports a organisé une séance de travail avec l’Institut National de la Jeunesse et des Sports pour répondre aux revendications des étudiants et assurer le paiement imminent des bourses du premier trimestre.',
        'https://www.gabonews.com/fr/actus/societe/article/seance-de-travail-avec-l-institut-national-de-la',
        'Gabonews',
        'Commerce, Éducation, Santé, Services',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.286Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '300cef0e-4e34-4f98-92a9-08e6edbce1da',
        'Afrijet / FlyGabon : le vol inaugural vers Bangui a eu lieu le 12 mars 2025',
        'La compagnie gabonaise Afrijet/FlyGabon a inauguré avec succès son premier vol vers Bangui le 12 mars 2025, lançant ainsi une expansion de ses services aériens régionaux.',
        'https://gabonactu.com/blog/2025/03/13/afrijet-flygabon-le-vol-inaugural-vers-bangui-a-eu-lieu-le-12-mars-2025/',
        'Gabon Actu',
        'Tourisme, Services, Numérique / Digital',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.287Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74f428df-1209-4258-a082-b12675d8a825',
        'Opérateurs pétroliers : Le rappel à l’ordre du gouvernement',
        'Le gouvernement gabonais a organisé une réunion avec les opérateurs pétroliers pour imposer l’application des réglementations sur les fonds de remise en état, établir un cadre de crédit TVA visant à stimuler l’investissement, et renforcer le dialogue sur la responsabilité sociétale des entreprises dans les secteurs de la santé et de l’éducation.',
        'https://directinfosgabon.com/operateurs-petroliers-le-rappel-a-lordre-du-gouvernement/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.287Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6cade711-a647-431a-b07c-5bad7dabc313',
        'Le Gabon dans le top 3 des pays africains les moins stressés en 2025',
        'En 2025, le Gabon se classe comme le troisième pays africain et le premier de la CEMAC parmi les nations les moins stressées, grâce à sa qualité de vie élevée, son environnement naturel riche et sa stabilité politique.',
        'https://gabonactu.com/blog/2025/03/13/le-gabon-dans-le-top-3-des-pays-africains-les-moins-stresses-en-2025/',
        'Gabon Actu',
        'Numérique / Digital, Tourisme, Services',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.287Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'abd289fc-38ff-479d-831b-1612f16fd31a',
        'NSIA Assurances ouvre une nouvelle agence à Louis',
        'NSIA Assurances étend son réseau au Gabon en inaugurant une nouvelle agence dans le quartier Louis à Libreville, renforçant ainsi sa présence pour offrir un meilleur accès à ses services d''assurance.',
        'https://directinfosgabon.com/nsia-assurances-ouvre-une-nouvelle-agence-a-louis/',
        'Direct infos Gabon',
        'Finances, Services',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.287Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b2a3680-072c-422b-96e8-2e2b293f3b7d',
        'Transport aérien : Afrijet/FlyGabon inaugure la desserte Bangui en RCA',
        'FlyGabon a inauguré une nouvelle desserte aérienne vers Bangui en République centrafricaine le 12 mars 2025, marquant le début de son expansion régionale en Afrique centrale.',
        'https://www.gabonreview.com/transport-aerien-afrijet-flygabon-inaugure-la-desserte-bangui-en-rca/',
        'Gabon Review',
        'Transport aérien, Tourisme',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '515f4315-7df9-46ca-833c-85a0d4e2f599',
        'CEMAC : Les nouvelles pièces de monnaie en circulation à partir de juillet  2025',
        'À partir de juillet 2025, la Banque des États de l’Afrique centrale (BEAC) introduira de nouvelles pièces de monnaie dans l’espace CEMAC afin de moderniser le système monétaire en améliorant la qualité, la sécurité et la durabilité des pièces actuellement en circulation.',
        'https://directinfosgabon.com/cemac-les-nouvelles-pieces-de-monnaie-en-circulation-a-partir-de-juillet-2025/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5bdb87e-f349-484c-9551-52f1f52a6fcd',
        'Des embauches assurées aux Assises sur l’emploi ? Les autorités démentent et expliquent',
        'Les autorités gabonaises réfutent les affirmations selon lesquelles les Assises nationales sur l’emploi garantissent des embauches automatiques, précisant que les recrutements répondent à des critères spécifiques et offrent des formations gratuites aux demandeurs d’emploi.',
        'https://www.gabonreview.com/des-embauches-assurees-aux-assises-sur-lemploi-les-autorites-dementent-et-expliquent/',
        'Gabon Review',
        'Services, Éducation, Numérique / Digital',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5d55b53-1689-452a-afe6-7f16e0aa9270',
        'eGabon-SIS et Gabon Digital : Opérationnalisation des solutions et défis de financement',
        'Le 3e Comité de pilotage du projet eGabon-SIS et du programme Gabon Digital a annoncé des progrès notables dans l''intégration des solutions technologiques dans les établissements sanitaires et prévoit le lancement prochain de services gouvernementaux numériques, de paiements digitaux et d''une identité numérique en collaboration avec la Banque mondiale.',
        'https://www.gabonreview.com/egabon-sis-et-gabon-digital-operationnalisation-des-solutions-et-defis-de-financement/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-03-13T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

