-- Batch 1 - Section 5/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '3e647771-4935-491e-8f18-4e5d38900056',
        'Cemac : Classement des 20 premières entreprises de la sous-région (2023-2024)',
        'L''article présente le classement des 20 premières entreprises de la sous-région CEMAC pour 2023-2024, élaboré par Jeune Afrique en se basant sur les chiffres d''affaires de plus de 1 300 entreprises africaines, en excluant les secteurs de la finance et des assurances.',
        'https://directinfosgabon.com/cemac-classement-des-20-premieres-entreprises-de-la-sous-region-2023-2024/',
        'Direct infos Gabon',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.255Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97edd962-ef12-4780-a4ed-87ed132d3008',
        'PUDC : Fred Ntoutoume Ndong Obiang officiellement installé comme Coordonnateur national',
        'Fred Ntoutoume Ndong Obiang a été officiellement nommé coordonnateur national du Programme d’urgence de développement communautaire (PUDC) au Gabon, prenant ses fonctions le 3 mars 2025 pour coordonner et suivre le programme dans les neuf provinces du pays.',
        'https://www.gabonreview.com/pudc-fred-ntoutoume-ndong-obiang-officiellement-installe-comme-coordonnateur-national/',
        'Gabon Review',
        'Services, Éducation, Agriculture',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.255Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4be07d0-2a23-4b67-89e1-02aaa4ccc590',
        'Santé : SETRAG invite ses employés à se soumettre au dépistage du cancer de  la prostate',
        'En novembre 2024, la SETRAG a lancé une campagne de sensibilisation invitant ses employés à se soumettre gratuitement au dépistage du cancer de la prostate afin de promouvoir la santé et la détection précoce de la maladie.',
        'https://kongossanews.info/sante-setrag-invite-ses-employes-a-se-soumettre-au-depistage-du-cancer-de-la-prostate/',
        'Kongossa News',
        'Santé, Éducation, Services',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.256Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5cf1988f-b97b-468a-9953-e92f41c9acc9',
        'Présidentielle 2025: Jean Rémy Yama se lance dans la course Transition: la dangereuse ingérence du Président Obiang Nguema dans ...',
        'Jean Rémy Yama, syndicaliste et ancien sénateur de la Transition, a officiellement annoncé sa candidature à l’élection présidentielle de 2025 au Gabon, affirmant sa volonté de provoquer un changement profond dans le pays.',
        'https://depeches241.com/?p=22768',
        'Dépêche 241',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.256Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28356ed1-734a-4138-ad5f-1be0c56a6d6c',
        'IPP Owendo : les principaux acteurs fixent le cap',
        'Le projet IPP Owendo, une centrale thermique à gaz de 125 MW, avance grâce à la coordination des principaux acteurs de l’énergie gabonaise, avec le lancement des travaux en juin 2025 et une mise en service prévue en 2027 pour renforcer l’approvisionnement électrique du pays.',
        'https://www.gabonreview.com/ipp-owendo-les-principaux-acteurs-fixent-le-cap/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.256Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'faff9863-d660-48bf-b70f-46a62ed9e12a',
        'Entreprise : La Setrag ouvre ses portes aux élèves de l’école St Joseph de Calasanz pour une immersion pédagogique',
        'La Setrag a accueilli des élèves de l’école St Joseph de Calasanz à la gare d’Owendo pour une immersion pédagogique visant à les sensibiliser aux métiers ferroviaires.',
        'https://kongossanews.info/entreprise-la-setrag-ouvre-ses-portes-aux-eleves-de-lecole-st-joseph-de-calasanz-pour-une-immersion-pedagogique/',
        'Kongossa News',
        'Éducation, Services',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.256Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '03cca395-7ab4-4926-87a0-7d83a8f6deee',
        'Initiative Jeunesse Altogovéenne Debout : Une mobilisation en soutien à la candidature d’Oligui Nguema',
        'La jeunesse du Haut-Ogooué se mobilise de plus en plus à travers l''Initiative DEBOUT pour soutenir la candidature du Général Brice Clotaire Oligui Nguema en vue de renforcer le développement et la cohésion sociale dans la région.',
        'https://www.gabonews.com/fr/actus/politique/article/initiative-jeunesse-altogoveenne-debout-une',
        'Gabonews',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.256Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e25cb62-1c59-419f-bc9c-87606ecb37e2',
        'Gabon : Un atelier scientifique pour allier conservation de la biodiversité et développement durable',
        'Le Gabon organise à Libreville un atelier scientifique du 3 au 5 mars 2025 réunissant des experts gabonais et français pour discuter de la conservation de la biodiversité et du développement durable dans les forêts du bassin du Congo.',
        'https://www.gabonreview.com/gabon-un-atelier-scientifique-pour-allier-conservation-de-la-biodiversite-et-developpement-durable/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Agriculture',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1b3ff65-5997-481f-9135-510823f5caa4',
        'Gabon: Oligui Nguema inaugure l’interconnexion électrique entre le Gabon et la Guinée-Équatoriale Enseignement Supérieur: Projet...',
        'Le président de la Transition gabonaise, Brice Clotaire Oligui Nguema, a inauguré avec le président de la Guinée équatoriale, Teodoro Obiang Nguema, une interconnexion électrique destinée à renforcer l’intégration énergétique entre les deux pays.',
        'https://depeches241.com/?p=22730',
        'Dépêche 241',
        'Numérique / Digital, Éducation, Services',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f017456b-4e61-4659-867e-90c9a8bfcc68',
        '[Tribune] À mes frères Gabonais',
        'Léon Paul Ngoulakia appelle les Gabonais à préserver la cohésion nationale et la stabilité du pays en cultivant la paix et l’unité lors des prochaines élections présidentielles.',
        'https://www.gabonreview.com/tribune-a-mes-freres-gabonais/',
        'Gabon Review',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ccea89e-825a-4b44-8de1-9d505def5363',
        'Affaire Opiangah: faire son devoir ou obéir à ses intérêts, le choix cornélien du Procureur Eddy Minang  Transfert du dossier HP...',
        'L''article décrit le dilemme moral du Procureur général Eddy Minang face à l’affaire Opiangah, devant choisir entre respecter son devoir judiciaire malgré un dossier entaché de mensonges ou céder à des pressions d’intérêts obscurs.',
        'https://depeches241.com/?p=22779',
        'Dépêche 241',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a433c212-9133-41ef-843b-2b51ac1c6da2',
        'Gabon : La session des lois s’ouvre au Sénat',
        'La première session des lois 2025 du Sénat gabonais s''est ouverte en même temps que la déclaration de candidature du président de la transition, avec des attentes adressées au gouvernement concernant les contraintes budgétaires de l''institution et les difficultés d''approvisionnement en eau et électricité pour la population.',
        'https://www.gabonreview.com/gabon-la-session-des-lois-souvre-au-senat/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '34983b0f-a357-4921-812d-693b48df8b4b',
        'Gabon : Jean-François Ndongou invite à «cultiver l’esprit de responsabilité, de sagesse et de tolérance»',
        'Le président de l’Assemblée nationale de la Transition, Jean-François Ndongou, a appelé lors de l’ouverture de la première session ordinaire de 2025 les députés à cultiver l’esprit de responsabilité, de sagesse et de tolérance tout en soulignant l’importance de la loi foncière et de l’unité nationale en vue des prochaines élections présidentielles.',
        'https://www.gabonreview.com/gabon-jean-francois-ndongou-invite-a-cultiver-lesprit-de-responsabilite-de-sagesse-et-de-tolerance/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Agriculture, Services',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.257Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '668d0fe9-74c5-4323-8abb-038220bfc15a',
        '«Organiser l’élection présidentielle plus tôt est une bonne chose», selon Paulette Missambo',
        'Selon Paulette Missambo, organiser plus tôt les élections présidentielles est essentiel pour rétablir l’ordre constitutionnel et normaliser les relations internationales du Gabon.',
        'https://www.gabonreview.com/organiser-lelection-presidentielle-plus-tot-est-une-bonne-chose-selon-paulette-missambo/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.258Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e1b96673-198d-495d-8c76-b4bd3206c8c9',
        'Présidentielle 2025 : Noël Bertrand Boundzanga renonce à sa candidature et dénonce une élection biaisée',
        'Noël Bertrand Boundzanga se retire de la course présidentielle de 2025 au Gabon, dénonçant un processus électoral biaisé et remettant en cause la crédibilité de la transition démocratique en cours.',
        'https://www.gabonreview.com/presidentielle-2025-noel-bertrand-boundzanga-renonce-a-sa-candidature-et-denonce-une-election-biaisee/',
        'Gabon Review',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.258Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '533a204c-f883-4ab8-9e7b-d98e7b2c1d8a',
        'Forbes Afrique célèbre Camélia Ntoutoume Leclercq, figure de proue de l’éducation gabonaise',
        'Camélia Ntoutoume Leclercq, ministre de l''Éducation nationale du Gabon, a été honorée par Forbes Afrique en tant que l''une des 50 femmes africaines les plus inspirantes pour son engagement exceptionnel dans le domaine de l''éducation.',
        'https://kongossanews.info/forbes-afrique-celebre-camelia-ntoutoume-leclercq-figure-de-proue-de-leducation-gabonaise/',
        'Kongossa News',
        'Éducation, Business Femme',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.258Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a22b47a-5d55-4a0d-8c53-ae17ef28f901',
        'Jean Rémy Yama : « Oligui Nguéma n’a pas écouté la voix de la sagesse »',
        'Jean Rémy Yama, candidat à la présidence gabonaise, accuse le président de la transition Brice Clotaire Oligui Nguéma de ne pas avoir respecté ses engagements et d''ignorer les conseils de sagesse dans la gestion du pays.',
        'https://gabonactu.com/blog/2025/03/04/jean-remy-yama-oligui-nguema-na-pas-ecoute-les-voix-de-la-sagesse/',
        'Gabon Actu',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.259Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '771b22b1-1633-41ef-abde-4ce722706315',
        'Présidentielle 2025: Oligui Nguema qui a entendu l’appel des « Kounabelistes » devrait y répondre ce jour  Présidentielle 2025: ...',
        'Le Président de la Transition gabonaise, le Général Brice Clotaire Oligui Nguema, prévoit de répondre prochainement aux sollicitations des "Kounabelistes" concernant sa candidature à la présidentielle de 2025.',
        'https://depeches241.com/?p=22783',
        'Dépêche 241',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.259Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4342e41c-837a-49cd-8fa8-c162a3bbe2a2',
        'Face aux tensions politiques, les ressortissants de Ndoubi s’opposent aux manœuvres de manipulation',
        'Les ressortissants de Ndoubi résistent activement aux tentatives de manipulation politique exacerbées par les tensions entre Brice Clotaire Oligui Nguema et Hervé Patrick Opiangah.',
        'https://kongossanews.info/face-aux-tensions-politiques-les-ressortissants-de-ndoubi-sopposent-aux-manoeuvres-de-manipulation/',
        'Kongossa News',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.259Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b543865-0de4-4e3a-a3e2-64f24f372973',
        'Agé de 72 ans Pierre Claver Maganga Moussavou a retiré le dossier de candidature',
        'Pierre Claver Maganga Moussavou, âgé de 72 ans et ancien vice-président, a retiré sa candidature à l’élection présidentielle du Gabon en raison de la limite d’âge de 70 ans prévue par la constitution.',
        'https://gabonactu.com/blog/2025/03/04/age-de-72-ans-pierre-claver-maganga-moussavou-a-retire-le-dossier-de-candidature/',
        'Gabon Actu',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.259Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5682199e-5867-40ed-9a77-0902b7d74a30',
        'Gabon : Vers la création d’un laboratoire d’analyse des minerais avec Hope Global Investments',
        'Le Gabon prévoit de créer un laboratoire d’analyse des minerais en partenariat avec Hope Global Investments afin d''améliorer l’analyse des ressources minières et de former les jeunes Gabonais aux métiers de l’analyse chimique et minière.',
        'https://www.gabonreview.com/gabon-vers-la-creation-dun-laboratoire-danalyse-des-minerais-avec-hope-global-investments/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services, Agriculture',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.259Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '042e5eaf-bc63-4caf-8c05-eabcad284a5a',
        'Crise au sein de la Chambre des Huissiers de Justice : un collectif dénonce un coup de force',
        'Un collectif de huissiers et de clercs dénonce une prise de pouvoir illégale et des irrégularités dans la gestion de la Chambre nationale des huissiers de justice du Gabon, réclamant un retour à la légalité et l’organisation d’élections transparentes.',
        'https://www.gabonreview.com/crise-au-sein-de-la-chambre-des-huissiers-de-justice-un-collectif-denonce-un-coup-de-force/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0da9915-2621-4e3f-b6ed-fcfd75564ea4',
        'Électricité : Un accident sur la Nationale 1 à l’origine des perturbations sur l’axe Oyane 1 – Lambaréné',
        'Un accident sur la Route Nationale 1 le 3 mars 2025 a endommagé des infrastructures électriques, provoquant une coupure de courant entre Oyane 1 et Bifoun, dont le rétablissement est prévu d''ici la fin de l''après-midi.',
        'https://www.gabonreview.com/electricite-un-accident-sur-la-nationale-1-a-lorigine-des-perturbations-sur-laxe-oyane-1-lambarene/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4b8c4ab-7bc9-4df6-a66c-12c8a3dbb633',
        'Présidentielle 2025 : L’IDEA International propose un Code de bonne conduite électorale',
        'L''Institut international pour la démocratie et l’assistance électorale (IDEA International) a proposé un Code de bonne conduite électorale afin de soutenir et sécuriser le processus de l''élection présidentielle prévue au Gabon le 12 avril 2025.',
        'https://www.gabonreview.com/presidentielle-2025-lidea-international-propose-un-code-de-bonne-conduite-electorale/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bbbb0016-4e43-4426-b23a-6206d300d618',
        'Présidentielle 2025 : Michel Ongoundou Loundah se lance',
        'Michel Ongoundou Loundah, président intérimaire du parti Réagir, annonce sa candidature à l’élection présidentielle gabonaise de 2025 avec un programme axé sur des institutions fortes, la justice sociale et le développement économique.',
        'https://www.gabonreview.com/presidentielle-2025-michel-ongoundou-loundah-se-lance/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation, Business Femme',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab559ba0-33aa-4db7-8824-eaec227e2489',
        'Port-Gentil : Patrick Barbera Isaac en mission pour la cohésion sociale',
        'Le ministre de la Jeunesse et des Sports, Patrick Barbera Isaac, mène une mission à Port-Gentil pour promouvoir l''unité, la paix et la fraternité au sein des communautés dans le cadre de la politique d’apaisement du président de la transition.',
        'https://www.gabonreview.com/port-gentil-patrick-barbera-isaac-en-mission-pour-la-cohesion-sociale/',
        'Gabon Review',
        'Autres',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05581cb0-eb04-4485-9ae3-d9bf8b695d0b',
        'Gabon : le député Lionel Ella Engonga plaide pour une amnistie en faveur de Kelly Ondo Obiang et ses compagnons',
        'Le député Lionel Ella Engonga propose une loi d’amnistie pour trois militaires condamnés pour une tentative de changement de régime en 2019, dans le but de favoriser la réconciliation nationale au Gabon.',
        'https://www.gabonreview.com/gabon-le-depute-lionel-ella-engonga-reclame-une-amnistie-pour-kelly-ondo-obiang-et-ses-compagnons/',
        'Gabon Review',
        'Autres',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fcec478f-e499-4574-8ae2-6c6cab3f893d',
        'ANBG : Les délégués provinciaux et extérieurs à la diète depuis un an',
        'Depuis leur nomination en mars 2024, les délégués provinciaux et extérieurs de l’Agence nationale des bourses du Gabon (ANBG) n''ont pas perçu leurs salaires pendant près d’un an, entraînant des difficultés financières et le départ de certains d''entre eux.',
        'https://www.gabonreview.com/anbg-les-delegues-provinciaux-et-exterieurs-a-la-diete-depuis-un-an/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.260Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b2053e2-d98a-4c34-a1c0-7d895bcdb44c',
        'À l’orée de la campagne présidentielle : Faire échec au kounabélisme',
        'L''article critique la montée du "kounabélisme" durant la campagne présidentielle gabonaise, soulignant la nécessité de préserver les valeurs républicaines et la bonne gouvernance en évitant le culte de la personnalité autour du président de la Transition.',
        'https://www.gabonreview.com/a-loree-de-la-campagne-presidentielle-faire-echec-au-kounabelisme/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-05T00:00:00.000Z',
        '2025-09-15T23:06:12.261Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3790b6a1-8ba3-49d1-b5de-99c46b87adda',
        'Présidentielle 2025 : déjà 30 potentiels candidats !',
        'Pour l’élection présidentielle du 12 avril 2025 au Gabon, 30 candidats, dont seulement trois femmes, ont retiré les dossiers de candidature au ministère de l’Intérieur avec une échéance imminente de trois jours et une caution de 30 millions de FCFA.',
        'https://gabonactu.com/blog/2025/03/05/presidentielle-2025-deja-30-potentiels-candidats/',
        'Gabon Actu',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.261Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eecfc558-ca1f-4c00-ba60-17ac0b65a9f4',
        'Malversations financières du groupe EBOMAF : Quels impacts pour le Gabon ?',
        'Les malversations financières du groupe EBOMAF menacent les projets d''infrastructure au Gabon et incitent le gouvernement à réévaluer ses partenariats avec l''entreprise.',
        'https://directinfosgabon.com/malversations-financieres-du-groupe-ebomaf-quels-impacts-pour-le-gabon/',
        'Direct infos Gabon',
        'Finances, Services, Numérique / Digital',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.261Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '869c6fb5-01c8-44d9-9959-c6a1887d1eaf',
        'Airtel Africa et Mastercard lancent une nouvelle solution de paiement numérique pour les clients d’Airtel Money',
        'Airtel Africa et Mastercard ont lancé la carte virtuelle Airtel Money GlobalPay, permettant à 150 millions de clients dans 14 pays africains d''effectuer des paiements numériques internationaux sécurisés directement depuis leur portefeuille Airtel Money.',
        'https://gabonactu.com/blog/2025/03/05/airtel-africa-et-mastercard-lancent-une-nouvelle-solution-de-paiement-numerique-pour-les-clients-dairtel-money/',
        'Gabon Actu',
        'Numérique / Digital, Finances, Commerce',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.262Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '876b96c6-4417-47a4-a6e6-e35e1011a61d',
        'CEMAC : Des sociétés de bourse prêtes à accompagner la restructuration des dettes souveraines',
        'Des sociétés de bourse de la CEMAC proposent d’accompagner la restructuration des dettes souveraines des États membres lors d’un colloque international à Yaoundé, visant à optimiser les stratégies d’endettement et renforcer la stabilité économique régionale.',
        'https://directinfosgabon.com/cemac-des-societes-de-bourse-pretes-a-accompagner-la-restructuration-des-dettes-souveraines/',
        'Direct infos Gabon',
        'Finances, Numérique / Digital',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.262Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1fd2c052-ba91-4f90-a8d7-e46dc2db4e11',
        'Sécurisation des aéroportuaires : Le Britannique Westminster décroche un juteux contrat au Gabon',
        'Le groupe britannique Westminster Group PLC a signé un contrat de plus de 15 ans pour assurer la sécurité de quatre aéroports internationaux au Gabon, contribuant ainsi à la modernisation des infrastructures et au développement du trafic aérien et du tourisme dans le pays.',
        'https://directinfosgabon.com/securisation-des-aeroportuaires-le-britannique-westminster-decroche-un-juteux-contrat-au-gabon/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Tourisme',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.262Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36c01a57-86ec-4ba5-9e20-f8c49833364e',
        'Crise énergétique : Un agenda caché derrière la sortie de la tourmente ?',
        'La mise en service des centrales électriques flottantes à Owendo par le Général Oligui Nguema met fin à une grave crise énergétique au Gabon, mais son calendrier proche de l’annonce de candidature présidentielle suscite des interrogations sur ses motivations politiques.',
        'https://directinfosgabon.com/crise-energetique-un-agenda-cache-derriere-la-sortie-de-la-tourmente-2/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.262Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65f34109-c79b-4ffd-8695-3e5be15d5640',
        'Crise énergétique : Un agenda caché derrière la sortie de la tourmente ?',
        'L''article analyse l''inauguration des centrales électriques flottantes par le Général Oligui Nguema pour résoudre la crise énergétique au Gabon, tout en questionnant un éventuel agenda politique lié à sa prochaine candidature présidentielle.',
        'https://directinfosgabon.com/crise-energetique-un-agenda-cache-derriere-la-sortie-de-la-tourmente/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.262Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2403723d-1ade-41e6-94ad-99a41a404c37',
        'Gabon : vers la construction d’une ville futuriste et durable',
        'Le ministre des Affaires étrangères gabonais a présenté un projet ambitieux de construction d''une ville intelligente et écologique à Libreville, incluant 400 logements sociaux équipés de technologies durables et d''énergie solaire.',
        'https://www.gabonreview.com/gabon-vers-la-construction-dune-ville-futuriste-et-durable/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6c941ca-403d-42dd-bc76-f380d488ea2c',
        'Moanda/Relogement forcé à Leyima : les populations interpellent Oligui Nguema',
        'Les habitants de Leyima et Lekolo dénoncent une expropriation injuste par la Compagnie minière de l’Ogooué (Comilog) et réclament un relogement conforme aux engagements pris, sollicitant l’intervention des autorités pour faire respecter leurs droits.',
        'https://www.gabonreview.com/moanda-relogement-force-a-leyima-les-populations-interpellent-oligui-nguema/',
        'Gabon Review',
        'Services, Éducation, Business Femme',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88a0df88-cc92-4c3d-875c-e8b52090c908',
        'Conflit social à la Comilog : En contradiction avec le Code du travail, des salaires réels à plus 102,1 % de la moyenne nationale',
        'Les syndicats de Comilog ont repris leur grève malgré des salaires déjà supérieurs à 102,1 % de la moyenne nationale, ce qui, selon l''entreprise, contrevient au Code du travail et menace l''économie gabonaise.',
        'https://www.gabonreview.com/conflit-social-a-la-comilog-en-contradiction-avec-le-code-du-travail-des-salaires-reels-a-plus-1021-de-la-moyenne-nationale/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3883395-c1ad-41e1-9f60-eea2d621c612',
        'Développement sanitaire : le Gabon bénéficie d’un don de 300 millions de la BAD',
        'La Banque africaine de développement a accordé au Gabon un don de 300 millions de FCFA pour financer l’élaboration de sa carte sanitaire et pharmaceutique dans le cadre du Plan national de développement sanitaire.',
        'https://www.gabonreview.com/developpement-sanitaire-le-gabon-beneficie-dun-don-de-300-millions-de-la-bad/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Santé',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'acff7881-0339-464d-89c6-524b87a09116',
        'Gabon : une nouvelle dotation en matériel agricole pour accélérer l’autosuffisance alimentaire',
        'Le 6 mars 2025, le président de la Transition gabonaise, Brice Clotaire Oligui Nguema, a remis une deuxième vague de matériel agricole visant à moderniser le secteur et à réduire la dépendance alimentaire du Gabon aux importations.',
        'https://www.gabonreview.com/gabon-une-nouvelle-dotation-en-materiel-agricole-pour-accelerer-lautosuffisance-alimentaire/',
        'Gabon Review',
        'Agriculture, Éducation, Services',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c52a9503-d666-4b5f-9d46-0cb38cb7a937',
        'Trésors publics de la Cemac : des mesures concrètes pour une gestion plus efficace des finances publiques',
        'Lors de la 13ᵉ session du Cadre permanent de concertation de la CEMAC, les responsables des Trésors publics ont adopté des mesures concrètes pour optimiser la gestion des finances publiques, renforcer la résilience économique et développer les marchés financiers de la sous-région.',
        'https://www.gabonreview.com/tresors-publics-de-la-cemac-des-mesures-concretes-pour-une-gestion-plus-efficace-des-finances-publiques/',
        'Gabon Review',
        'Finances, Services',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.263Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28cbb64f-518e-42a0-b649-4b22ed78ecf9',
        'Sécurité aéroportuaire : un contrat de plus de 15 ans et plusieurs millions de dollars pour Westminster Group au Gabon',
        'The Westminster Group Plc a signé un contrat de plus de 15 ans et de plusieurs millions de dollars avec l’État gabonais pour sécuriser les aéroports de Libreville, Port-Gentil, Franceville et Oyem.',
        'https://www.gabonreview.com/securite-aeroportuaire-un-contrat-de-plus-de-15-ans-et-plusieurs-millions-de-dollars-pour-westminster-group-au-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Tourisme',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.264Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '703c7e4e-0af3-49b5-b23a-57c5303378c4',
        'Présidentielle au Gabon : Sous quelle bannière Oligui Nguema conduira-t-il sa campagne ?',
        'Brice Clotaire Oligui Nguema prépare sa campagne présidentielle au Gabon soit en se présentant comme candidat indépendant, soit en créant ou en s''associant à un nouveau parti politique afin de dépasser les clivages partisans traditionnels.',
        'https://www.gabonreview.com/presidentielle-au-gabon-sous-quelle-banniere-oligui-nguema-conduira-t-il-sa-campagne/',
        'Gabon Review',
        'Autres',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.264Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55d20216-1b3c-41d0-bc21-d0f9d9824242',
        'Ossimane change de peau : un véhicule politique pour Oligui, un revers pour le PDG',
        'À un mois des élections présidentielles au Gabon, l''association Ossimane se transforme en parti politique pour servir de véhicule électoral à Brice Clotaire Oligui Nguema, affaiblissant ainsi le Parti démocratique gabonais (PDG).',
        'https://www.gabonreview.com/ossimane-change-de-peau-un-vehicule-politique-pour-oligui-un-revers-pour-le-pdg/',
        'Gabon Review',
        'Autres',
        '2025-03-06T00:00:00.000Z',
        '2025-09-15T23:06:12.264Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53e12e1b-2ba3-41c9-b170-71b01bd2db71',
        'Frédéric Massavala rebondit au conseil gabonais des chargeurs',
        'L’ancien ministre et porte-parole du Parti démocratique gabonais, Frédéric Massavala Maboumba, a été nommé président du conseil d’administration du Conseil gabonais des chargeurs par le président de la Transition, Brice Clotaire Oligui Nguema, en vue des élections présidentielles de 2025.',
        'https://gabonactu.com/blog/2025/03/07/frederic-massavala-rebondit-au-conseil-gabonais-des-chargeurs/',
        'Gabon Actu',
        'Autres',
        '2025-03-07T00:00:00.000Z',
        '2025-09-15T23:06:12.264Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ad148aa-6765-40cd-a05b-6b67d867700e',
        'Le groupe Maurel & Prom réalise un bénéfice net de 149 milliards FCFA en 2024',
        'En 2024, le groupe pétrolier Maurel & Prom a enregistré un bénéfice net de 149,2 milliards FCFA, soit une hausse de 2 % par rapport à 2023.',
        'https://directinfosgabon.com/le-groupe-maurel-prom-realise-un-benefice-net-de-149-milliards-fcfa-en-2024/',
        'Direct infos Gabon',
        'Finances, Commerce',
        '2025-03-07T00:00:00.000Z',
        '2025-09-15T23:06:12.265Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dff3fa73-7990-4383-9ad8-fd4eab383c4a',
        'PROMETAL S’ENGAGE A INJECTER 30 MILLIARDS DE F CFA POUR RENFORCER LE…			 
			DGI : DES RECETTES FISCALES RECORD DE PLUS DE 1 000...',
        'Le groupe camerounais Prometal investit 30 milliards de FCFA au Gabon pour établir une unité sidérurgique dans la zone industrielle de Nkok, créant ainsi 1 000 emplois et renforçant le secteur de la métallurgie locale.',
        'https://echosdeleco.com/prometal-sengage-a-injecter-30-milliards-de-f-cfa-pour-renforcer-le-secteur-de-la-siderurgie/',
        'Les Echos de l''Eco',
        'Services, Agriculture, Numérique / Digital',
        '2025-03-07T00:00:00.000Z',
        '2025-09-15T23:06:12.265Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '747915e2-ccfd-4364-950b-741efedc0b91',
        'COMILOG : nouvelle grève pour des augmentations chiffrées à 12 milliards de FCFA par l’administration',
        'Le collectif des syndicats de COMILOG a déclenché une grève générale illimitée le 6 mars 2025 pour réclamer une augmentation salariale totale de 12 milliards de FCFA par an, que l’administration juge insoutenable.',
        'https://gabonactu.com/blog/2025/03/06/comilog-nouvelle-greve-pour-des-augmentations-chiffrees-a-12-milliards-de-fcfa-par-ladministration/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-07T00:00:00.000Z',
        '2025-09-15T23:06:12.265Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08376beb-c134-4070-8aed-bf59d095c5fa',
        'Gabon | Entre Transition et élection',
        'L’élection présidentielle gabonaise de 2025, prévue pour le 12 avril, constitue une étape cruciale après le coup d’État militaire de 2023, avec le général Brice Clotaire Oligui Nguema annonçant sa candidature et suscitant des débats sur la transition démocratique et l’avenir politique du Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/gabon-entre-transition-et-election',
        'Gabonews',
        'Politique, Éducation, Numérique / Digital',
        '2025-03-07T00:00:00.000Z',
        '2025-09-15T23:06:12.265Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

