-- Batch 5 - Section 6/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'ca85066a-3fe3-454c-94a1-6a3e2a7d38e3',
        'Le Gabon décroche plus de 1600 milliards FCFA auprès d’Afreximbank pour soutenir la transformation minière et énergétique',
        'Le Gabon a signé deux accords de financement avec la Banque africaine d’Import-Export (Afreximbank) pour plus de 1 600 milliards FCFA, afin de soutenir ses projets de transformation dans les secteurs minier et énergétique.',
        'https://vxp241.com/2025/06/28/le-gabon-decroche-plus-de-1600-milliards-fcfa-aupres-dafreximbank-pour-soutenir-la-transformation-miniere-et-energetique/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46518006-b507-470d-aead-cab38eb47555',
        'En kiosque : ‘’Princesse Kûmba, la belle âme’’, le premier jet de Warren Nkili Akieme',
        'Un jeune auteur de 25 ans, Warren Nkili Akieme, publie son premier roman intitulé « Princesse Kumba, la belle âme », une œuvre à la fois émouvante et réfléchie qui invite à se poser des questions essentielles.',
        'https://gabonactu.com/blog/2025/06/28/en-kiosque-princesse-kumba-la-belle-ame-le-premier-jet-de-warren-nkili-akieme/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7653641a-56bd-431f-8f3e-9899ab08f683',
        'Nigéria/AAM2025 : George Elombi, nouveau visage d’Afreximbank',
        'Lors de l''assemblée annuelle de 2025, M. George Elombi a été élu président du Conseil d''administration d''Afreximbank, après une longue carrière au sein de la banque, où il a occupé plusieurs postes clés.',
        'https://agpgabon.ga/nigeria-aam2025-george-elombi-nouveau-visage-dafreximbank/',
        'AGP',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b62258a-870c-43e3-825a-f7c22d3b1ef4',
        'Gabon : la CNAMGS dévoile la nouvelle liste 2025 des médicaments et produits de santé remboursables',
        'La CNAMGS a publié la liste 2025 des médicaments et produits de santé remboursables, avec des améliorations pour garantir un accès plus large, durable et équitable aux soins médicaux au Gabon.',
        'https://agpgabon.ga/gabon-la-cnamgs-devoile-la-nouvelle-liste-2025-des-medicaments-et-produits-de-sante-remboursables/',
        'AGP',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1000f414-0a78-46ad-97bd-367875a21b02',
        'Karaté : Pamphil Youmou Andimi élu président de la Fegakama',
        'Pamphil Youmou Andimi a été élu président de la Fédération gabonaise de karaté pour un mandat de quatre ans, recueillant la majorité des voix lors du vote.',
        'https://agpgabon.ga/karate-pamphil-youmou-andimi-elu-president-de-la-fegakama/',
        'AGP',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7012511f-60da-41a8-b3c6-cf6d65c48637',
        'Football/Ndambo d’Or : Derrick Assoumou Obame fêté par les siens à Oyem',
        'Un jeune footballeur de 19 ans, Derrick Assoumou Obame, a fêté sa récompense du Ndambo d’Or 2024-2025 à Oyem, sa ville natale, où il a été chaleureusement accueilli par ses proches et la communauté.',
        'https://agpgabon.ga/football-ndambo-dor-derrick-assoumou-obame-fete-par-les-siens-a-oyem/',
        'AGP',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a80afc8-c26a-46f7-af60-71dbb7743649',
        'Gabon : Charles Mondjo veut façonner des malafoutiers éco-responsables',
        'Charles Mondjo souhaite former des entrepreneurs écoresponsables afin de promouvoir un développement durable et une gestion responsable des ressources naturelles au Gabon.',
        'https://gabonmediatime.com/gabon-charles-mondjo-veut-faconner-des-malafoutiers-eco-responsables/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e7432af-8b03-4dd8-9c4d-1db87f10198d',
        'Gabon : Oligui Nguema obtient un financement de 140 milliards Fcfa pour le bitumage de l’axe Alembe – Mikouyi',
        'Gabon a obtenu un financement de 140 milliards de FCFA pour asphaltier la route entre Libreville et Alembe-Mikouyi, dans le but d''améliorer les infrastructures et la mobilité dans la région.',
        'https://gabonmediatime.com/gabon-oligui-nguema-obtient-un-financement-de-140-milliards-fcfa-pour-le-bitumage-de-laxe-alembe-mikouyi/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76769b40-0ec0-4fe9-89e4-53dba5bf53b8',
        'Gabon : entrée en vigueur de la loi sur les partis',
        'Une nouvelle loi sur les partis politiques est entrée en vigueur au Gabon, visant à renforcer le cadre juridique et réglementaire de la vie politique dans le pays.',
        'https://gabonmediatime.com/gabon-entree-en-vigueur-de-la-loi-sur-les-partis/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6378bfa-d943-48ce-bf7d-be620d14d58a',
        'ÉVANDAGANYÈ : Le Président Oligui Nguema célèbre les valeurs culturelles et spirituelles gabonaises',
        'Le président Oulgui Nguema a mis en avant l''importance de préserver et de valoriser les traditions culturelles et spirituelles du Gabon comme un élément essentiel de l''identité nationale.',
        'https://kongossanews.info/evandaganye-le-president-oligui-nguema-celebre-les-valeurs-culturelles-et-spirituelles-gabonaises/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bacb39be-0dee-4636-a60c-f6cca848f4f3',
        'Législatives 2025: candidat, Nicaise Etakobezaka réunit les ressortissants de Massaha (Ogooué-Ivindo) residant à Libreville',
        'Nicaise Etakobezaka s’engage à soutenir le développement des régions de Massaha et de Logooue Ivindo en menant des actions pour améliorer les conditions de vie des populations et promouvoir l’émergence locale.',
        'https://kongossanews.info/nicaise-etakobezaka-un-engagement-pour-le-developpement-de-massaha-et-de-logooue-ivindo/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2dc993b4-139f-4082-a75d-9a7cbddabcce',
        'Gabon/ Travaux d’aménagement et bitumage: : 140 milliards FCFA engagés pour la route Alembe–Mikouyi',
        'Le gouvernement gabonais a signé un contrat de 140 milliards FCFA pour aménager et goudronner une route de 300 km entre Alembe et Mikouyi, afin de mieux relier plusieurs régions et améliorer les connections entre les différents modes de transport.',
        'https://agpgabon.ga/gabon-travaux-damenagement-et-bitumage-140-milliards-fcfa-engages-pour-la-route-alembe-mikouyi/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e88403a-e583-4f9f-954d-e8664da83f79',
        'Caravane Touristique du Gabon 2025 : lancement officiel de la plateforme e-Visa touristique',
        'Le Gabon lance une plateforme en ligne permettant aux touristes étrangers d’obtenir gratuitement leur visa électronique en moins de 48 heures, dans le cadre de la deuxième édition de la Caravane Touristique 2025.',
        'https://agpgabon.ga/caravane-touristique-du-gabon-2025-lancement-officiel-de-la-plateforme-e-visa-touristique/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae154a6f-9bd6-49c5-8469-5a038623c099',
        'Gabon : Ecobank et le gouvernement unissent leurs forces pour l’entrepreneuriat féminin avec ELLEVER 2.0',
        'Le gouvernement gabonais et Ecobank lancent le programme ELLEVER 2.0, qui vise à soutenir les femmes entrepreneures en leur offrant des financements, des formations et des opportunités de réseautage pour favoriser leur autonomie économique.',
        'https://agpgabon.ga/gabon-ecobank-et-le-gouvernement-unissent-leurs-forces-pour-lentrepreneuriat-feminin-avec-ellever-2-0/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '799fb798-6a69-443b-8002-b7c3d90ea98d',
        'Gabon : Charles Mondjo veut façonner des malafoutiers éco-responsables',
        'Charles Mondjo souhaite former des jeunes gabonais aux techniques de fabrication de malafoutiers respectueux de l’environnement, afin de développer une filière locale durable et responsable.',
        'https://gabonmediatime.com/gabon-charles-mondjo-veut-faconner-des-malafoutiers-eco-responsables/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c2351ea-4a30-42c7-b6f7-cffed4b64b4f',
        'Gabon : Oligui Nguema obtient un financement de 140 milliards Fcfa pour le bitumage de l’axe Alembe – Mikouyi',
        'Gabon a obtenu un financement de 140 milliards de FCFA pour réaliser la route bitumée entre Laxe et Alembe Mikouyi, améliorant ainsi les infrastructures de transport dans la région.',
        'https://gabonmediatime.com/gabon-oligui-nguema-obtient-un-financement-de-140-milliards-fcfa-pour-le-bitumage-de-laxe-alembe-mikouyi/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba263882-fa92-4fb2-a6f8-1f7d0cdb2f03',
        'Gabon : entrée en vigueur de la loi sur les partis',
        'La nouvelle loi sur les partis politiques en vigueur au Gabon établit un cadre réglementaire pour leur création, leur fonctionnement et leur financement, visant à renforcer la démocratie et la stabilité politique dans le pays.',
        'https://gabonmediatime.com/gabon-entree-en-vigueur-de-la-loi-sur-les-partis/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6391a3a6-0c17-4ec4-bd22-0aafc5ab5675',
        'ÉVANDAGANYÈ : Le Président Oligui Nguema célèbre les valeurs culturelles et spirituelles gabonaises',
        'Le président Oguéli Nguema a célébré l''importance des valeurs culturelles et spirituelles gabonaises, soulignant leur rôle dans l''identité et le développement du pays.',
        'https://kongossanews.info/evandaganye-le-president-oligui-nguema-celebre-les-valeurs-culturelles-et-spirituelles-gabonaises/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad341701-c8e3-42d9-8485-bcb709757747',
        'Législatives 2025: candidat, Nicaise Etakobezaka réunit les ressortissants de Massaha (Ogooué-Ivindo) residant à Libreville',
        'Nicaise Etakobezaka s''engage pour le développement des communes de Massaha et Logooué IVindo en menant des projets axés sur l''éducation, l''agriculture et l''amélioration des conditions de vie locales.',
        'https://kongossanews.info/nicaise-etakobezaka-un-engagement-pour-le-developpement-de-massaha-et-de-logooue-ivindo/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d7c81c4-70ac-4b8d-8c75-765e47d0816a',
        'Joseph Théodore Sandwidi & William Palé pour «Sanbbiz» et Prisca Bivigou Gangou pour «Yoma»',
        'Deux entrepreneurs du Burkina Faso ont lancé en 2024 une application pour organiser des sorties culturelles, tandis qu''une créatrice gabonaise a lancé une marque de parfums basée sur des essences locales.',
        'https://www.rfi.fr/fr/podcasts/les-t%C3%AAtes-d-affiches-de-denise-epot%C3%A9/20250629-joseph-th%C3%A9odore-sandwidi-william-pal%C3%A9-pour-sanbbiz-et-prisca-bivigou-gangou-pour-yoma',
        'RFI',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a49538b-fa6f-428c-8152-3ec318087805',
        'Franzy Kouya Ndjandja : le leadership de la jeunesse mis en lumière',
        'Le président gabonais favorise l''inclusion et la confiance envers la jeunesse en leur confiant des postes stratégiques dans le gouvernement, comme c''est le cas de Franzy Kouya Ndjandja.',
        'https://www.gabonews.com/fr/actus/politique/article/franzy-kouya-ndjandja-le-leadership-de-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'def2d0a4-3724-48fc-afe9-7e5c0eaf3c41',
        'Ngounié : Une baignade mortelle à la rivière Biroundou',
        'Une jeune femme d''une trentaine d''années, connue sous le nom de "maman béné", a tragiquement perdu la vie en se noyant dans la rivière Biroundou à Lébamba, suscitant une grande émotion parmi les habitants.',
        'https://vxp241.com/2025/06/29/ngounie-une-baignade-mortelle-a-la-riviere-biroundou/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6bb5374d-b494-47ca-990b-c1b3fac27c29',
        'OLIGUI NGUEMA participe à la cérémonie sacrée ÉVANDAGANYÈ de la communauté Mpongwè',
        'Le président Brice Clotaire Oligui Nguema a assisté à la cérémonie sacrée Évandaganyè organisée par la communauté Mpongwè, un événement culturel et spirituel important qui rassemble plusieurs communautés traditionnelles dans la province de l’Estuaire.',
        'https://vxp241.com/2025/06/29/oligui-nguema-participe-a-la-ceremonie-sacree-evandaganye-de-la-communaute-mpongwe/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d9fe78a-6eaf-49e9-a12b-e780ef73de5f',
        'BTP : 140 milliards de FCFA pour bitumer la route Alembe–Mikouyi (300 km)',
        'Un projet de bitumage de 300 km de route entre Alembe et Mikouyi, d''une valeur de 140 milliards de FCFA, sera réalisé au Gabon grâce à la collaboration entre PORTEO BTP, BGFI Bank et d''autres partenaires, pour améliorer la connection entre Libreville et Franceville.',
        'https://gabonactu.com/blog/2025/06/29/btp-140-milliards-de-fcfa-pour-bitumer-la-route-alembe-mikouyi-300-km/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2913a8c-dec8-4b35-8d67-b0f293a247ba',
        'Cérémonie de purification, de pardon et de réconciliation',
        'Le président Brice Clotaire Oligui Nguema a participé à une cérémonie spirituelle de purification, de pardon et de réconciliation organisée par la communauté Mpongwè, en présence de plusieurs autres communautés au sein de la Chefferie traditionnelle Eka.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/ceremonie-de-purification-de-pardon-et-de',
        'Gabonews',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d02cfb0-ad06-4a44-b255-c0d7ffde56ed',
        'Signature d''une convention historique entre l''État gabonais et l''ANINF',
        'Un accord historique a été signé pour créer un Data Center national au Gabon, visant à renforcer la souveraineté numérique du pays avec le soutien de partenaires internationaux tels que Cisco, Citibank, EximBank et le gouvernement américain.',
        'https://www.gabonews.com/fr/actus/economie-numerique/article/signature-d-une-convention-historique-entre-l',
        'Gabonews',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a45398f-28e0-468c-a58d-974ccbd6e99d',
        'Publié le 29 / 06 / 2025',
        'Le Gabon s''équipe d’un centre de données national pour renforcer sa souveraineté numérique et sécuriser ses infrastructures technologiques.',
        'https://union.sonapresse.com/fr/souverainete-numerique-le-gabon-se-dote-dun-data-center-national',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '052a1148-cc3c-4598-8e9b-c701e0098db7',
        'Publié le 29 / 06 / 2025',
        'Une banque gabonaise a reçu 140 milliards de francs CFA pour financer des projets qui amélioreront la vie dans la capitale et favoriseront le développement économique du pays.',
        'https://union.sonapresse.com/fr/route-alembe-mikouyi-bgfibank-injecte-140-milliards-pour-desenclaver-le-coeur-du-gabon',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41931141-08be-45b8-ac4d-dfd6cb936c5f',
        'Publié le 29 / 06 / 2025',
        'Afreximbank renforce la diplomatie économique africaine en facilitant le financement et la promotion des échanges commerciaux intra-africains, contribuant ainsi au développement économique du continent.',
        'https://union.sonapresse.com/fr/afreximbank-un-coup-de-maitre-pour-la-diplomatie-economique',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6398c267-bd04-40bb-9ef4-343f9617a5fa',
        'Tourisme : visa gratuit au Gabon de juillet à septembre 2025',
        'Le gouvernement gabonais offrira un visa touristique gratuit aux visiteurs étrangers de juillet à septembre 2025, dans le cadre de la deuxième édition de la caravane touristique pour promouvoir le tourisme en Afrique centrale.',
        'https://gabonactu.com/blog/2025/06/29/tourisme-visa-gratuit-au-gabon-de-juillet-a-septembre-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'efe6be2b-d904-4cbc-8db2-d4e80c7d4cad',
        'Evandaganye : un lent pèlerinage de la chefferie Mpongwé dans les rues de Libreville 25 ans après',
        'Vingt-cinq ans après, la chefferie Mpongwé d’Acaé et d’Ozoungué participe à une procession dans les rues de Libreville pour célébrer et maintenir vivantes leurs traditions et leur identité culturelle.',
        'https://gabonactu.com/blog/2025/06/29/evandaganye-un-lent-pelerinage-de-la-chefferie-mpongwe-dans-les-rues-de-libreville-25-ans-apres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62f4513c-21ed-42a6-84ac-6e636bce75c0',
        'Patriotisme économique : 200 000 FCFA par citoyen pour financer le développement',
        'L’article propose la création d’un fonds citoyen au Gabon, invitant chaque citoyen à contribuer avec 200 000 FCFA pour financer des projets de développement et réduire la dépendance aux financements étrangers.',
        'https://www.gabonreview.com/patriotisme-economique-200-000-fcfa-par-citoyen-pour-financer-le-developpement/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2dde4bbf-bc78-4675-a774-db48043ea452',
        'Quand le Gabon devient le premier fournisseur du Cameroun : le renversement silencieux',
        'Le Gabon est devenu le principal fournisseur du Cameroun au sein de la communauté économique de la CEMAC, ce qui représente un changement discret mais important dans leurs échanges commerciaux.',
        'https://www.gabonreview.com/quand-le-gabon-devient-le-premier-fournisseur-du-cameroun-le-renversement-silencieux/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '811dd6f9-ceff-40b0-9a30-75145560bf73',
        'Rolling Stone : une superstar américaine, trois artistes gabonais, une couverture historique',
        'Pour la première fois, un magazine célèbre comme Rolling Stone met en valeur des artistes et talents gabonais en réalisant une couverture historique avec la star américaine Ciara, réalisée par trois artistes gabonais.',
        'https://www.gabonreview.com/rolling-stone-une-superstar-americaine-trois-artistes-gabonais-une-couverture-historique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47e63be9-71a0-44f6-a69e-d6fdeaa86c70',
        '"Les vrais leaders sont ceux qui savent se faire petits pour entendre les murmures du peuple, pour comprendre ses aspirations et porter ses espoirs"',
        'Le véritable leadership repose sur l''humilité, la simplicité et la sincérité, comme en témoigne l''image du président vêtu de blanc et pieds nus, symbole de pureté et de grandeur intérieure.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/les-vrais-leaders-sont-ceux-qui-savent-se-faire',
        'Gabonews',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0239c478-5598-477c-b51a-7463deb743a6',
        'Publié le 29 / 06 / 2025',
        'Le Gabon s’engage à renforcer sa souveraineté numérique en construisant un centre de données national pour mieux gérer ses informations et assurer la sécurité de ses infrastructures digitals.',
        'https://union.sonapresse.com/fr/souverainete-numerique-le-gabon-se-dote-dun-data-center-national',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '130fc7f7-f789-4e8e-9c34-8b6883e8f695',
        'Publié le 29 / 06 / 2025',
        'Une banque gabonaise a reçu 140 milliards de francs CFA pour financer des projets qui permettront de mieux connecter le centre-ville du pays et de favoriser le développement économique local.',
        'https://union.sonapresse.com/fr/route-alembe-mikouyi-bgfibank-injecte-140-milliards-pour-desenclaver-le-coeur-du-gabon',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8b29e41b-f31c-430f-a50d-02d61d8108d7',
        'Publié le 29 / 06 / 2025',
        'L’Afreximbank a lancé une initiative pour renforcer la diplomatie économique africaine en facilitant les investissements et les échanges commerciaux entre les pays du continent.',
        'https://union.sonapresse.com/fr/afreximbank-un-coup-de-maitre-pour-la-diplomatie-economique',
        'L''union',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5857798c-e828-49a1-8b15-24bdb12bcf08',
        'Football: la Fegafoot tient son 63e Congrès ordinaire ce dimanche',
        'La Fédération gabonaise de football (Fegafoot) a tenu son 63e Congrès ordinaire pour évaluer ses actions passées et planifier la saison à venir, dans un contexte particulier lié à la récente nomination de son président à un poste important en Afrique.',
        'https://agpgabon.ga/football-la-fegafoot-tient-son-63e-congres-ordinaire-ce-dimanche/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '84a46b5c-84f1-4b9f-9eb6-9f13f29ddd9c',
        'Gabon/Littérature : Hasse Nziengui présente trois ouvrages aux accents prémonitoires des événements du 30 août 2023',
        'L’écrivain Hasse Nziengui a présenté à Libreville trois de ses ouvrages, publiés entre 2010 et 2012, qui abordent les changements politiques en Afrique, notamment au Gabon, et sont considérés comme ayant des accents prémonitoires des événements du 30 août 2023.',
        'https://agpgabon.ga/gabon-litterature-hasse-nziengui-presente-trois-ouvrages-aux-accents-premonitoires-des-evenements-du-30-aout-2023/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b2c67e0-6160-45c8-b2e2-8c828acecc1f',
        'Prix import: Ntoum s’apprête à accueillir une nouvelle ère commerciale avec l’inauguration d’un supermarché',
        'L’ouverture prochaine d’une succursale Carrefour-Prix Import à Ntoum marque une étape importante dans le développement commercial de la région, suite à des échanges entre le groupe et le Ministre du Commerce en amont de cet événement.',
        'https://vxp241.com/2025/06/29/prix-import-ntoum-sapprete-a-accueillir-une-nouvelle-ere-commerciale-avec-linauguration-dun-supermarche/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f7fb01f-7a15-4af2-b0b4-de8515560706',
        'CRRM – CRG : Regards croisés sur le bien-être des communautés villageoises',
        'Une collaboration entre le Cercle de Réflexion des Ressortissants de Malundu et la Croix-Rouge gabonaise a permis d’organiser une conférence pour discuter des actions visant à améliorer le bien-être des communautés villageoises.',
        'https://gabonactu.com/blog/2025/06/29/crrm-crg-regards-croises-sur-le-bien-etre-des-communautes-villageoises/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86aaee94-9cd8-420e-b623-6d6ac5b4f010',
        'SATRAM – EGCA : Faillite constatée, liquidation judiciaire prononcée',
        'La Cour commune de justice et d’arbitrage de l’OHADA a officiellement déclaré la faillite et ordonné la liquidation judiciaire de la société SATRAM – EGCA.',
        'https://gabonactu.com/blog/2025/06/29/satram-egca-faillite-et-liquidation-judiciaire-prononcees/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce6c1584-afeb-4a84-a115-0d06f9aa337e',
        'Gabon : le préfet Ulrich Sylvère Mavioga offre un tricycle à un jeune en situation de handicap à Bateva',
        'Un jeune homme à mobilité réduite a reçu un tricycle offert par le préfet de la région pour améliorer ses déplacements, geste salué par le bénéficiaire et en hommage à l’engagement social de l’autorité locale.',
        'https://agpgabon.ga/gabon-le-prefet-ulrich-sylvere-mavioga-offre-un-tricycle-a-un-jeune-en-situation-de-handicap-a-bateva/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '145374da-1d2e-40f9-af3d-98b13a3f9ae8',
        'Football : Pierre-Alain Mounguengui confirme la participation du FC 105 à la Coupe de la CAF',
        'Le président de la Fédération gabonaise de football a confirmé que le club FC 105 participera à la prochaine Coupe de la CAF, conformément à la tradition d’inscrire les deux meilleurs clubs du championnat gabonais dans les compétitions africaines.',
        'https://agpgabon.ga/football-pierre-alain-mounguengui-confirme-la-presidence-du-fc-105-a-la-coupe-de-la-caf/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6af9e135-c258-44c7-b7bc-01bf201e8868',
        'Gabon : le Chef de l’État officialise la convention de création du Data Center national avec le groupe Cybastion',
        'Le gouvernement gabonais a signé un accord avec la société américaine Cybastion pour créer un centre de données national, afin d''assurer une infrastructure numérique indépendante, sécurisée et performante.',
        'https://agpgabon.ga/gabon-le-chef-de-letat-officialise-la-convention-de-creation-du-data-center-national-avec-le-groupe-cybastion/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f59bfefb-a36e-4715-a205-066b67f70e30',
        'Football / Nécrologie : décès de Kevine Klaïne Mbakogo',
        'Un jeune footballeur gabonais, Kevine Klaïne Mbakogo, est décédé subitement après s''être effondré lors d’un match amical, alors qu''il avait marqué 11 buts cette saison avec son club, le Vautour FC.',
        'https://agpgabon.ga/football-necrologie-deces-de-kevine-klaine-mbakogo/',
        'AGP',
        'Business Intelligence',
        '2025-06-29T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7719454-3975-4c57-b349-58814ae860d4',
        'Lutte contre la pêche illégale : 2 semaines de formation à Port-Gentil pour surveiller et utiliser durablement les ressources marines du Gabon',
        'Une formation de deux semaines à Port-Gentil vise à renforcer la surveillance et la gestion durable des ressources marines du Gabon, en collaboration avec le gouvernement, la DGPA, l''ONG WildAid et l''ANPN, pour lutter contre la pêche illégale.',
        'https://gabonactu.com/blog/2025/06/29/lutte-contre-la-peche-illegale-2-semaines-de-formation-a-port-gentil-pour-surveiller-et-utiliser-durablement-les-ressources-marines-du-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-30T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9254e435-f4c0-46a0-8345-b012430f3c38',
        'Gabon Digital : adoption d’une feuille de route à exécuter progressivement en 2026',
        'Un plan de transformation numérique pour le Gabon a été présenté, avec une feuille de route à mettre en œuvre progressivement en 2026 pour renforcer les systèmes d’information et le projet IBOGA.',
        'https://gabonactu.com/blog/2025/06/29/gabon-digital-adoption-dune-feuille-de-route-a-executer-progressivement-en-2026/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-30T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e369d80-b846-4aa4-98cb-8e6a067f0cba',
        'Mention ‘’très honorable’’ pour le tout premier Docteur d’EM Gabon-Université',
        'Après quinze ans d''existence, le groupe EM Gabon-Université a couronné son premier docteur, Louis Bertrand Ogoula Ikinda, avec la mention « très honorable ».',
        'https://gabonactu.com/blog/2025/06/29/mention-tres-honorable-pour-le-tout-premier-docteur-dem-gabon-universite/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-30T00:00:00.000Z',
        '2025-09-15T23:06:12.464Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

