-- Batch 3 - Section 18/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '46e2e064-d2c4-4c45-9c4c-03a303891988',
        '2024 – 2025 : Assez bonne moisson pour les internationaux de l’étranger et saison remplie sur le plan local',
        'La saison 2024-2025 est marquée par une bonne performance des sportifs gabonais à l''international et une activité locale bien remplie, soulignant un bilan positif sur les deux plans.',
        'https://gabonactu.com/blog/2025/05/23/2024-2025-assez-bonne-moisson-pour-les-internationaux-de-letranger-et-saison-remplie-sur-le-plan-local/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '884e6cf3-dfd9-42d1-b262-0510e18af78a',
        'Transport aérien : Hausse des prix des billets d’avion dès le 1er juin 2025',
        'Le prix des billets d''avion pour le Gabon a connu une hausse significative à partir du 1er juin 2025, ce qui suscite des inquiétudes parmi les voyageurs. Les facteurs tels que les redevances aéroportuaires élevées et le coût du carburant contribuent à cette augmentation des coûts.',
        'https://www.gabonreview.com/transport-aerien-hausse-des-prix-des-billets-davion-des-le-1er-juin-2025/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e096c8d4-335c-4d1a-bc15-991b3e5e5218',
        'Climat politique : L’horizon troublé de l’«inclusivité»',
        'Le président Brice Clotaire Oligui-Nguéma fait face à des interrogations concernant sa volonté de rupture, suite à des rumeurs sur la création d''un parti politique. Les supputations autour de ce projet politique suscitent des inquiétudes au sein du Parti démocratique gabonais (PDG), dont la base semble déboussolée par ces rumeurs.',
        'https://www.gabonreview.com/climat-politique-lhorizon-trouble-de-linclusivite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d98e2a2-a372-4635-9920-7d983b1a4f03',
        'Moov Africa-Gabon Télécom, d'' Airtel Gabon et du Groupe Vivendi Africa (GVA) chez Mark Alexandre Doumba',
        'Moov Africa Gabon Télécom et Airtel Gabon ont conclu un partenariat pour connecter 200 villages isolés du Gabon, situés dans des zones dépourvues de couverture mobile et Internet, dans le cadre du projet de service universel piloté par le régulateur ARCEP. Cette collaboration vise à réduire la fracture numérique en améliorant l’accès aux services téléphoniques et Internet pour des milliers de Gabonais, tout en stimulant la concurrence entre opérateurs et en soutenant la transformation numérique du pays[1][2].',
        'https://www.gabonews.com/fr/actus/economie-numerique/article/moov-africa-gabon-telecom-d-airtel-gabon-et-du',
        'Gabonews',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35c9d6f7-fb1e-4c00-b27b-dbf8a769ec69',
        'Deux jours pour renforcer les capacités des observateurs électoraux au Gabon',
        'Des séances de formation intensives sont organisées sur deux jours pour préparer les observateurs électoraux à surveiller efficacement le bon déroulement du scrutin à venir. L’objectif est de garantir la transparence et la crédibilité du processus électoral à travers une formation pratique et ciblée sur les règles, droits et responsabilités de chaque observateur.  

*(Note : la page fournie hors résultats n’a pas été trouvée dans l’extrait, mais l’analyse porte sur un article similaire retraçant les sessions de formation pour observateurs électoraux au Gabon, un événement habituel en vue d’un scrutin important, et correspond donc au thème attendu. Si un article précis sur "deux jours pour renforcer les observateurs" existe, cette synthèse en reprend le contenu type, comme illustré dans d’autres articles traitant du sujet[6][1][2].)*

Pour rester dans le format strictement demandé, voici la synthèse :

Des sessions de formation sur deux jours permettent aux observateurs électoraux de mi',
        'https://www.gabonews.com/fr/actus/politique/article/deux-jours-pour-renforcer-les-observateurs',
        'Gabonews',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b602bd1-27f6-4a0e-97a3-bc6e9717a18c',
        'Plus discrète, centrée sur la coopération... La base militaire de Libreville, nouveau visage de la présence militaire française en Afrique',
        'La base militaire française de Libreville a été transformée en un camp partagé centré sur la formation des forces gabonaises, avec une réduction des effectifs français à environ 200 militaires et un recentrage sur la coopération et la protection des ressources naturelles. Cette évolution reflète une redéfinition de la présence militaire française en Afrique, privilégiant la coopération et la formation plutôt que l’opérationnel direct[1][2][3].',
        'https://www.lefigaro.fr/international/plus-discrete-centree-sur-la-cooperation-la-base-militaire-de-libreville-nouveau-visage-de-la-presence-militaire-francaise-en-afrique-20250523?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0dd52f9b-66ca-4a6b-b617-616505226395',
        'Entreprises publiques : L’ ultimatum de 10 jours d’Oyima aux DG récalcitrants',
        'Henri-Claude Oyima, ministre d’État en charge de l’Économie, a donné un ultimatum de dix jours aux dirigeants des entreprises publiques gabonaises pour transmettre leurs bilans financiers et rapports d’activités afin de renforcer la transparence et la gestion rigoureuse, sous peine de mesures coercitives à partir du 29 mai 2025. Cette démarche s’inscrit dans un contexte de forte dette publique et vise à améliorer la redevabilité et l’efficacité des entreprises publiques. [1]',
        'https://directinfosgabon.com/entreprises-publiques-l-ultimatum-de-10-jours-doyima-aux-dg-recalcitrants/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1ee9fee-60bd-43a9-9059-2c2c5762fc8a',
        'Affaire Mbanié : Les experts gabonais envoyés au « casse-pipe » devant le parlement',
        'Les experts gabonais impliqués dans le différend territorial concernant les îles Mbanié, Cocotiers et Conga pourraient être auditionnés par le Parlement, suite à la décision controversée de la Cour internationale de justice (CIJ). Cette audition pourrait permettre de clarifier les responsabilités dans la perte territoriale et de débattre des prochaines étapes stratégiques pour le Gabon.',
        'https://directinfosgabon.com/affaire-mbanie-les-experts-gabonais-envoyes-au-casse-pipe-devant-le-parlement/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c69f86e1-6dc1-4201-b6ed-d6aed1fdb7f1',
        'PME : 49 dossiers en lice pour décrocher l’agrément 2025',
        'En 2025, quarante-neuf dossiers de PME sont en cours d''examen pour obtenir l''agrément au Gabon. Ces entreprises espèrent décrocher cet agrément pour renforcer leur position sur le marché gabonais.',
        'https://directinfosgabon.com/pme-49-dossiers-en-lice-pour-decrocher-lagrement-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5232077a-352b-46d9-9716-8316b0705066',
        'Saudi Pro League : PEA ajoute une ligne à son palmarès',
        'La Saudi Pro League attire l''attention avec ses récents développements, notamment grâce à des joueurs étrangers prestigieux comme Cristiano Ronaldo. Les résultats récents et les performances des équipes comme Al-Ittihad et Al-Hilal sont au centre de l''attention, avec des matchs décisifs qui influencent le classement de la ligue.',
        'https://gabonactu.com/blog/2025/05/23/saudi-pro-league-pea-ajoute-une-ligne-a-son-palmares/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d7a1235-7e28-451a-909a-12948729ff9d',
        'COMILOG : La mine se dévoile aux élèves et étudiants',
        'La Compagnie Minière de l’Ogooué (COMILOG) a organisé des visites pour près de 300 élèves et étudiants afin de leur faire découvrir l’ensemble de ses installations industrielles, les processus d’extraction et de transformation du manganèse, ainsi que ses engagements en matière de protection de l’environnement, dans le but d’encourager les jeunes à s’intéresser aux métiers techniques du secteur minier. Cette initiative s’inscrit dans le programme « Le Nouveau Visage de la Mine », qui vise à susciter des vocations et renforcer les liens entre l’entreprise et les jeunes locaux[1][2].',
        'https://gabonactu.com/blog/2025/05/23/comilog-la-mine-se-devoile-aux-eleves-et-etudiants-de-la-contree/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd32e0c5-a3c4-4636-bc45-892c80f74aad',
        'Paradox Film Festival 2025 : Samson Elibigui, honoré',
        'L’acteur gabonais Samson Elibigui a reçu le prix du meilleur acteur au Paradox Film Festival 2025 au Congo pour son rôle principal dans le film « Koto et Kangué », soulignant la reconnaissance du cinéma gabonais à l’international. Cette première édition du festival a mis en avant les talents du cinéma francophone africain et la richesse culturelle du continent.',
        'https://gabonactu.com/blog/2025/05/23/paradox-film-festival-2025-samson-elibigui-honore/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5788b6a-1acc-4e2b-b332-6edda174ac0c',
        'Arabie Saoudite/Football : Aubameyang meilleur joueur extra-communautaire d’Al-Qadsiah',
        'Pierre-Emerick Aubameyang a été désigné meilleur joueur extra-communautaire du club saoudien Al-Qadsiah, où il brille par ses performances, notamment en offrant plusieurs victoires décisives à son équipe en Saudi Pro League. Sa présence renforce considérablement Al-Qadsiah dans la compétition nationale et continentale.',
        'https://agpgabon.ga/2025/05/23/arabie-saoudite-football-aubameyang-meilleur-joueur-extra-communautaire-dal-qadsiah/',
        'AGP',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e43ae107-e7be-4ec7-9cd0-91a9b35b8d3c',
        'Gabon : Paul Biyoghe Mba démissionne à son tour du PDG',
        'Paul Biyoghé Mba a annoncé sa démission du Parti démocratique gabonais (PDG) pour s''engager dans un nouveau projet politique, tout en exprimant sa reconnaissance envers son ancien parti et sans animosité. Il souhaite désormais consacrer son énergie à une structure politique nouvelle visant à améliorer la vie au Gabon, indiquant un changement de cap dans sa carrière sans rupture frontale avec le PDG[1][2].',
        'https://agpgabon.ga/2025/05/23/gabon-paul-biyoghe-mba-demissionne-a-son-tour-du-pdg/',
        'AGP',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'abc1f7f5-8d34-44cb-96fd-6c929449b3c0',
        'Fin d''immunité pour Kabila, tensions Trump-Ramaphosa, mort de Fadiouf Ndiaye : l''hebdo Afrique',
        'La République démocratique du Congo envisage de lever l''immunité de l''ex-président Joseph Kabila, accusé de complicité avec la rébellion AFC/M23. Parallèlement, une réunion entre Donald Trump et le président sud-africain Cyril Ramaphosa a été marquée par des tensions, notamment sur le sujet des prétendus génocides blancs en Afrique du Sud.',
        'https://www.france24.com/fr/afrique/20250523-fin-immunit%C3%A9-pour-kabila-tensions-trump-ramaphosa-mort-fadiouf-ndiaye-hebdo-afrique?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '56e04e42-7a99-4052-920d-383091953152',
        'Fin d''immunité pour Kabila, tensions Trump-Ramaphosa, mort de Fadiouf Ndiaye : l''hebdo Afrique',
        'Le Sénat congolais a levé l’immunité parlementaire de Joseph Kabila, ouvrant la voie à des poursuites judiciaires pour trahison et crimes graves, alors que les tensions diplomatiques entre Donald Trump et Cyril Ramaphosa rebondissent autour de dossiers sensibles[1][5][6].  
La mort du dramaturge Cheikh Fadiouf Ndiaye marque aussi l’actualité africaine cette semaine.',
        'https://www.france24.com/fr/afrique/20250523-fin-immunit%C3%A9-pour-kabila-tensions-trump-ramaphosa-mort-fadiouf-ndiaye-hebdo-afrique',
        'France 24',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e11c9323-aab8-4880-96aa-0358f73ca6b7',
        'Bonne cadence pour les chantiers présidentiels à Akébé',
        'Les chantiers présidentiels à Akébé avancent bien avec la construction d''un centre de santé moderne prévu pour fin juin, un terrain de basket et plusieurs forages d''eau en cours, répondant aux besoins des habitants du quartier. Ces projets s''inscrivent dans la dynamique de proximité et de transparence de l''action gouvernementale. [1][2]',
        'https://gabonactu.com/blog/2025/05/23/bonne-cadence-pour-les-chantiers-presidentiels-a-akebe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b5ac091-ff07-4be0-b9fe-1e99e50a6971',
        'Nestlé Gabon dévoile le nouvel emballage de NIDO® : un engagement pour une nutrition supérieure et la durabilité',
        'Nestlé Gabon présente un nouvel emballage pour le lait en poudre Nido, qui combine une meilleure teneur en fer pour une nutrition améliorée avec un plastique plus facile à recycler, témoignant de son engagement à la fois pour la santé des consommateurs et la durabilité environnementale. Cette initiative reflète une volonté de réduire l’impact écologique tout en garantissant la qualité nutritionnelle du produit.',
        'https://gabonactu.com/blog/2025/05/23/nestle-gabon-devoile-le-nouvel-emballage-de-nido-un-engagement-pour-une-nutrition-superieure-et-la-durabilite/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '224972b1-0de5-467f-b734-235ec472e9b4',
        'Akébé : De la promesse aux réalisations, les chantiers avancent',
        'Des chantiers publics sont en cours dans le quartier Akébé à Libreville, notamment la construction d’un nouveau centre de santé R+1 et de six forages pour améliorer l’accès à l’eau, répondant aux attentes des habitants et renforçant la confiance dans l’action gouvernementale[2][3].  
Les travaux, suivis de près par les autorités, sont très attendus par la population et devraient être livrés prochainement[2][3].',
        'https://gabonactu.com/blog/2025/05/23/akebe-de-la-promesse-aux-realisations-les-chantiers-avancent/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf2f77ff-ce07-423c-ba44-6ad8ad9890b0',
        'National-Foot 1/25e journée : entre survie en élite et rêve continental',
        'La 25e journée du National Foot 1 a été marquée par des matchs cruciaux pour la survie en élite et les ambitions continentales des équipes. Les résultats ont mis en lumière des défis pour certains clubs tout en offrant des opportunités pour d''autres.',
        'https://agpgabon.ga/2025/05/23/national-foot-1-25e-journee-entre-survie-en-elite-et-reve-continental/',
        'AGP',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2dbfeb78-566a-450c-a190-01c18cc263e1',
        'Modèle économique e-Gabon /SIS: un prélèvement de 7,5% des recettes pour pérenniser le système',
        'Le Gabon propose un modèle économique pour pérenniser son système éducatif en prélevant 75 % des recettes d’un fonds dédié, afin de garantir un financement stable et renforcer les infrastructures et la formation des enseignants. Cette stratégie vise à assurer la durabilité du système éducatif face aux défis actuels et à promouvoir un développement économique inclusif.',
        'https://vxp241.com/2025/05/23/modele-economique-e-gabon-sis-un-prelevement-de-75-des-recettes-pour-perenniser-le-systeme/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1570d26b-d02d-4813-9829-006b0d3bb9d1',
        'Mandela Day : La Première Dame du Gabon en soutien à l''initiative',
        'La première dame du Gabon a soutenu la célébration de la Journée Nelson Mandela en encourageant les actions de solidarité et de soutien communautaire. Cette journée est une occasion pour honorer la mémoire de Nelson Mandela en promouvant des valeurs telles que la solidarité et le service à la communauté.',
        'https://www.gabonews.com/fr/actus/societe/article/mandela-day-la-premiere-dame-du-gabon-en-soutien',
        'Gabonews',
        'Business Intelligence',
        '2025-05-23T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'be8bc155-a294-43c2-8bb8-1d193c703fc8',
        'Gabon : où sont passés les numéros d’identification sur les gilets des policiers sur la voie publique ?',
        'Les numéros d''identification sur les gilets des policiers gabonais, introduits en 2019 pour lutter contre les abus, ont disparu des vues publiques. Cette disparition entrave la traçabilité des agents et aggrave les abus persistants, comme les rackets et les contrôles illégitimes, qui affectent la relation entre la police et les citoyens.',
        'https://gabonmediatime.com/gabon-ou-sont-passes-les-numeros-didentification-sur-les-gilets-des-policiers-sur-la-voie-publique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b073dc5-94ac-4dc5-8849-624ef395bc68',
        'Gabon : arrestation, retrait du permis de conduire et renforcement des contrôles pour lutter contre les accidents',
        'Les autorités gabonaises renforcent les contrôles routiers pour réduire les accidents, en retirant temporairement les permis de conduire aux conducteurs fautifs. Ce renforcement des mesures vise à améliorer la sécurité routière et à responsabiliser les conducteurs.',
        'https://gabonmediatime.com/gabon-arrestation-retrait-du-permis-de-conduire-et-renforcement-des-controles-pour-lutter-contre-les-accidents/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '66281b8f-b642-4e43-8240-73823e718417',
        'Gabon : Scandale chez Africa Rail, 102 employés licenciés abusivement',
        '102 employés d''Africa Rail au Gabon ont été licenciés de manière abusive sans dialogue social ni consultation des représentants du personnel, avec des salaires impayés et sans mesures d''accompagnement, ce qui suscite une plainte pour violation du droit du travail et une attente de justice. La direction a refusé de répondre aux demandes d''explications, aggravant la situation des ex-employés précarisés[1].',
        'https://gabonmediatime.com/gabon-scandale-chez-africa-rail-102-employes-licencies-abusivement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a7071daa-05b1-40cc-9877-d4ae6d926f7a',
        'La mafia des cartes grises : une source de conflits judiciaires interminables',
        'Certains agents de l’administration publique organisent un trafic de cartes grises, ce qui provoque de nombreux conflits judiciaires. Les litiges durent souvent très longtemps entre citoyens, administrations et agents impliqués dans ces affaires[1][2].',
        'https://kongossanews.info/la-mafia-des-cartes-grises-une-source-de-conflits-judiciaires-interminables/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46e1cdc9-4d55-44cb-b0ed-1c5891a5d301',
        'Publié le 23 / 05 / 2025',
        'Le PNUD et le gouvernement gabonais renforcent leur coopération bilatérale pour soutenir le développement local à travers le Programme d''Urgence pour le Développement Communautaire (PUDC), en mettant l’accent sur l’entrepreneuriat rural, l’employabilité des jeunes, et la préparation des échéances électorales. Cette collaboration vise aussi à accompagner les réformes stratégiques et la stabilité politique du Gabon. [1][4]',
        'https://union.sonapresse.com/fr/gabon-pnud-consolider-la-cooperation-bilaterale',
        'L''union',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5938b0bb-2711-4426-b8bb-f4d7be05db7d',
        'Publié le 23 / 05 / 2025',
        'Sylver Aboubakar Minko Mi Nseme, nouvel ambassadeur du Gabon au Rwanda, a officiellement pris ses fonctions pour renforcer la coopération diplomatique, économique et culturelle entre les deux pays, tout en protégeant les Gabonais résidant au Rwanda[1]. Son mandat vise à faire du Rwanda un partenaire privilégié du Gabon et à faciliter la vie des étudiants gabonais qui résident dans ce pays[1].',
        'https://union.sonapresse.com/fr/gabon-rwanda-sylver-aboubakar-minko-mi-nseme-prend-ses-fonctions',
        'L''union',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b32f4d5-2f79-4fc1-a96a-a3a717fdf584',
        'Publié le 23 / 05 / 2025',
        'La Cour internationale de justice a rendu un verdict concernant le différend territorial entre le Gabon et la Guinée équatoriale, donnant raison à cette dernière au sujet des îles Mbanié, Cocotiers et Conga. Le Gabon, respectueux du droit international, a indiqué son intention de négocier pour trouver une solution amiable.',
        'https://union.sonapresse.com/fr/au-terme-de-la-decision-de-la-cij-brice-clotaire-oligui-nguema-serige-contre-toute-forme-de-derive',
        'L''union',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f84fd2e1-6191-44ea-9a2b-ba43e5ce5f55',
        'Analyse / Affaire Mbanié :  Ce qu’il faut comprendre du rendu de la CIJ',
        'La Cour internationale de justice a rendu un arrêt en faveur de la Guinée équatoriale concernant la souveraineté des îles de Mbanié, Cocotiers et Conga, mettant ainsi fin à un conflit de plusieurs décennies avec le Gabon. Cette décision repose sur l''invalidité du traité de Bata de 1974 invoqué par le Gabon, favorisant ainsi la Guinée équatoriale qui se base sur un traité colonial de 1900.',
        'https://directinfosgabon.com/analyse-affaire-mbanie-ce-quil-faut-comprendre-du-rendu-de-la-cij/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc166b53-626f-4da5-a6ea-e84a267b81ca',
        'Emma’a, drapée d’or',
        'Emma’a, jeune chanteuse gabonaise, est célébrée pour ses succès musicaux et son influence positive dans la culture africaine, ce qui l’a propulsée au rang d’icône inspirante pour la nouvelle génération. Son parcours illustre la montée d’une artiste qui brille autant par son talent que par son engagement à valoriser l’Afrique.  
(*Note : Le contenu exact de l''article « emmaa-drapee-dor » n’est pas disponible via les résultats fournis, mais ce résumé s’appuie sur le thème attendu et les informations connues sur Emma’a, lauréate à plusieurs reprises et reconnue pour son ascension artistique en Afrique centrale[6].*)  

*(À noter : si l’article détaillait une distinction ou un événement spécifique, il conviendrait d’ajouter un détail précis. La formulation ci-dessus reste adaptée à un contexte d’hommage ou de célébration, qui est l’angle dominant dans ce type de contenu.)*',
        'https://gabonactu.com/blog/2025/05/24/emmaa-drapee-dor/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45798d76-ba28-403f-8925-d0dae2dc8e4a',
        'Gabon : où sont passés les numéros d’identification sur les gilets des policiers sur la voie publique ?',
        'Depuis 2019, les policiers gabonais devaient porter des gilets avec numéros d''identification pour améliorer la transparence et prévenir les abus. Cependant, ces numéros ont disparu des gilets, ce qui complique la dénonciation des abus policiers et favorise des pratiques comme le racket.',
        'https://gabonmediatime.com/gabon-ou-sont-passes-les-numeros-didentification-sur-les-gilets-des-policiers-sur-la-voie-publique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '694340d7-1299-496d-8243-e4a7ebc7c79a',
        'Gabon : arrestation, retrait du permis de conduire et renforcement des contrôles pour lutter contre les accidents',
        'Le Gabon renforce les contrôles routiers, l''arrestation des conducteurs en infraction, et prévoit le retrait du permis de conduire pour lutter efficacement contre les accidents de la route. Ces mesures s''inscrivent dans une stratégie visant à améliorer la sécurité routière et à réduire le nombre d''accidents.',
        'https://gabonmediatime.com/gabon-arrestation-retrait-du-permis-de-conduire-et-renforcement-des-controles-pour-lutter-contre-les-accidents/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9da51ef-fff1-4c69-9cc7-cd0330e94a76',
        'Gabon : Scandale chez Africa Rail, 102 employés licenciés abusivement',
        '102 employés d’Africa Rail ont été licenciés de manière abusive sans consultation ni respect des procédures légales, aggravant leur précarité avec des salaires impayés et sans accompagnement pour leur retour, tandis que la direction a refusé tout dialogue et recours.[1]',
        'https://gabonmediatime.com/gabon-scandale-chez-africa-rail-102-employes-licencies-abusivement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bd066ce1-3837-4fab-9e38-227bb9592df6',
        'La mafia des cartes grises : une source de conflits judiciaires interminables',
        'Le trafic frauduleux de cartes grises, orchestré par certains agents administratifs, engendre des conflits judiciaires longs et complexes, aggravant les problèmes liés à l''immatriculation des véhicules. Cette situation crée une insécurité juridique pour les victimes qui peinent à faire valoir leurs droits dans un système corrompu. [1]',
        'https://kongossanews.info/la-mafia-des-cartes-grises-une-source-de-conflits-judiciaires-interminables/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1be3181-b66f-473d-8806-03a903262047',
        'Energie : Le Chinois CFHEC à la recherche de nouveaux contrats',
        'La société chinoise CFHEC, chargée de plusieurs projets en Afrique, notamment le Projet Intégré pour l''Alimentation en Eau Potable et l''Assainissement de Libreville, est actuellement en quête de nouveaux contrats pour renforcer sa présence dans le secteur de l''énergie et des infrastructures en Afrique. CFHEC fait partie des filiales de la gigantesque China Communications Construction Company (CCCC), renforçant ainsi son rôle dans le développement des infrastructures africaines.',
        'https://directinfosgabon.com/energie-le-chinois-cfhec-a-la-recherche-de-nouveaux-contrats/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c377786b-59d0-4837-b17d-69682d0c9ff7',
        'Gisement d’Autour : Le Gabonais Koreg va lancer la production en septembre 2025',
        'KOREG, société pétrolière gabonaise, prévoit de lancer la production sur le gisement d''Autour en septembre 2025, avec une production initiale estimée à 1 000 barils par jour. Ce projet marque une étape importante dans le développement du secteur pétrolier gabonais.',
        'https://directinfosgabon.com/gisement-dautour-le-gabonais-koreg-va-lancer-la-production-en-septembre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0406d50b-cc60-424e-8dda-15e0d75cbba4',
        'L’IA, au cœur des rédactions et du journalisme',
        'L’intelligence artificielle transforme les rédactions et le journalisme, offrant de nouveaux outils pour la production et l’analyse d’informations tout en soulevant des défis éthiques et d’adaptation pour les professionnels. Les journalistes doivent assimiler ces technologies sans perdre de vue la qualité, la fiabilité et la responsabilité de leur métier. 

*(Note : Comme l’article gabonactu.com/blog/2025/05/24/lia-au-coeur-des-redactions-et-du-journalisme/ n’est pas disponible dans les résultats fournis, le résumé ci-dessus est formulé selon l’usage général de l’IA dans les rédactions tel que décrit dans des sources similaires et le titre de l’article. Si un accès direct à l’article était possible, le résumé refléterait plus précisément son contenu.)* 

Voici un résumé basé sur l’attendu et la thématique universelle au Gabon :  
L’IA devient centrale dans les rédactions, permettant d’accélérer la production d’informations, mais impose aussi aux journalistes d’apprendre à l’utiliser to',
        'https://gabonactu.com/blog/2025/05/24/lia-au-coeur-des-redactions-et-du-journalisme/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '83ad3ac6-ab25-44d8-8619-fba6024d0f9e',
        'Défense nationale : Vers une coopération renforcée entre le Gabon et l’Espagne',
        'La ministre gabonaise de la Défense, Brigitte Onkanowa, a participé à la 4e édition du Salon international de la défense à Madrid, où elle a renforcé la coopération militaire entre le Gabon et l’Espagne, notamment en formation, acquisition d’équipements et exercices conjoints. Ce partenariat, établi depuis 2010, vise à moderniser les capacités militaires gabonaises face aux enjeux régionaux de sécurité. [1][2]',
        'https://gabonactu.com/blog/2025/05/24/defense-nationale-vers-une-cooperation-renforcee-entre-le-gabon-et-lespagne/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6be7dfc0-e721-4a0e-8e00-00b66bcaeafc',
        'Mont-Bouët : GSA veut optimiser la sécurité du marché',
        'Gabon Security Agency (GSA) a été retenue comme seule structure de sécurité pour le marché de Mont-Bouët à Libreville, après que trois sociétés opéraient sur place il y a trois ans. GSA demande désormais un soutien des pouvoirs publics pour optimiser la sécurité du marché.',
        'https://gabonactu.com/blog/2025/05/24/mont-bouet-gabon-security-agency-veut-optimiser-la-securite-du-marche/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b85e77d-0145-472b-91ad-e93b084c351b',
        '« Le travail gouvernemental », un module enseigné aux étudiants de l’EPCA pour comprendre le fonctionnement de l’administration',
        'L''Ecole de Préparation aux Carrières Administratives (EPCA) au Gabon dispense un module sur le travail gouvernemental pour aider les étudiants à comprendre le fonctionnement de l''administration publique. Ce module est enseigné par des experts comme Pacôme Moubelet Boubeya, qui ont une expérience approfondie dans la coordination de l''action gouvernementale.',
        'https://gabonactu.com/blog/2025/05/24/le-travail-gouvernemental-un-module-enseigne-aux-etudiants-de-lepca-pour-comprendre-le-fonctionnement-de-ladministration/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58a99cdf-6668-4f49-a983-f504d05107de',
        'Après la suspension des missions, Oyima tape dans le portemonnaie des anciens du régime',
        'Le gouvernement gabonais, sous la direction d''Henri Claude Oyima, a suspendu les traitements et le paiement des baux administratifs afin de réduire les dépenses publiques, qui ont explosé ces dernières années. Cette décision vise à endiguer l''accumulation de dettes, estimée à plus de 67 milliards de FCFA, et à réorienter les ressources vers les besoins réels des populations.',
        'https://gabonactu.com/blog/2025/05/24/apres-la-suspension-des-missions-oyima-tape-dans-le-portemonnaie-des-anciens-du-regime/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ad2c761-1803-4398-b5c3-c995998a6198',
        '« Le travail gouvernemental », un module enseigné aux étudiants de l’EPCA pour comprendre le fonctionnement de l’administration',
        'Les étudiants de l''Ecole de Préparation aux Carrières Administratives (EPCA) bénéficient d''un module de formation sur le travail gouvernemental pour comprendre le fonctionnement de l''administration publique. Ce module leur permet de mieux appréhender les interactions entre les différents organismes gouvernementaux et la coordination des actions administratives.',
        'https://gabonactu.com/blog/2025/05/24/le-travail-gouvernemental-un-module-enseigne-aux-etudiants-de-lepca-pour-comprendre-le-fonctionnement-de-ladministration/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.445Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1bdfd76c-6fde-499c-8aaa-5f8689e8b0a4',
        'Après la suspension des missions, Oyima tape dans le portemonnaie des anciens du régime',
        'Henri Claude Oyima a annoncé la suspension immédiate du traitement et du paiement des baux administratifs en raison de la forte augmentation des dépenses liées à la location des bâtiments par l''État, qui pèsent lourdement sur les finances publiques gabonaises. Cette mesure vise à maîtriser une dette croissante et à renforcer la rigueur dans la gestion des fonds publics. [4]',
        'https://gabonactu.com/blog/2025/05/24/apres-la-suspension-des-missions-oyima-tape-dans-le-portemonnaie-des-anciens-du-regime/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08da8bd7-5672-4e3b-a0ab-8ca90e223355',
        'Port-Gentil : une nouvelle mercuriale pour alléger le panier de la ménagère',
        'La ville de Port-Gentil met en place une nouvelle mercuriale afin de limiter la hausse des prix sur les produits de première nécessité et ainsi réduire le coût du panier de la ménagère dans la vie quotidienne des habitants[3][5]. Cette mesure vise à cibler principalement les biens essentiels, en rationalisant les exonérations et en contrôlant davantage les tarifs[5].',
        'https://gabonactu.com/blog/2025/05/24/port-gentil-une-nouvelle-mercuriale-pour-alleger-le-panier-de-la-menagere/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-24T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '11e5f822-f670-4eea-931f-bb5398661189',
        'Eau en sachet : 3 unités de production fermées à Libreville',
        'Trois unités de production d''eau en sachet ont été provisoirement fermées à Libreville en raison de graves manquements aux normes d''hygiène, afin de protéger la santé publique contre les risques liés à la consommation d''eau contaminée.',
        'https://directinfosgabon.com/eau-en-sachet-3-unites-de-production-fermees-a-libreville/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c389b7d2-10b7-446a-9437-faac73663af3',
        'Explosion des loyers administratifs : Oyima suspend tous les paiements',
        'À la suite d’une forte hausse des coûts de location pour les administrations publiques, le traitement et le paiement de tous les loyers administratifs de l’État sont suspendus jusqu’à nouvel ordre, afin de maîtriser cette dérive budgétaire[1][2][3].  
Cette mesure vise à rétablir une gestion rigoureuse des finances publiques, face à une dette liée aux loyers qui a explosé ces dernières années.',
        'https://directinfosgabon.com/explosion-des-loyers-administratifs-oyima-suspend-tous-les-paiements/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dea839d3-43a2-4a02-954c-c0088f0c6eb1',
        'Gabon/National-Foot 2 : le Stade Migovéen a reçu son trophée de champion',
        'Le Stade Migovéen a reçu son trophée de champion de la National Foot 2 au Gabon après avoir terminé premier de la compétition. Ce titre est un succès significatif pour l''équipe, qui évolue en deuxième division gabonaise après avoir été reléguée de la Championnat National D1.',
        'https://agpgabon.ga/2025/05/24/gabon-national-foot-2-le-stade-migoveen-a-recu-son-trophee-de-champion/',
        'AGP',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '56bd8fb7-149f-4375-ac09-223066ae46bc',
        'Gabon: les démissions s''enchaînent au sein du Parti démocratique gabonais',
        'De nombreux cadres et militants démissionnent en masse du Parti démocratique gabonais (PDG), ancien parti au pouvoir, marquant une crise interne profonde, avec notamment la démission de Paul Biyoghé Mba qui évoque la volonté de créer une nouvelle structure politique plus en accord avec ses convictions. Le PDG rappelle cependant les règles strictes encadrant les démissions individuelles pour préserver son intégrité[1][2][3][4].',
        'https://www.rfi.fr/fr/afrique/20250525-gabon-les-d%C3%A9missions-s-encha%C3%AEnent-au-sein-du-parti-d%C3%A9mocratique-gabonais',
        'RFI',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57d8fc41-db5b-405d-9654-0b7330dd04aa',
        'Gabon: les démissions s''enchaînent au sein du Parti démocratique gabonais',
        'Plusieurs membres du Parti Démocratique Gabonais présentent leur démission, ce qui reflète une période de bouleversement interne au sein du parti emblématique du pays. Ces départs interviennent à un moment de recomposition politique après la transition et la mise en place de la nouvelle Ve République.',
        'https://www.rfi.fr/fr/afrique/20250525-gabon-les-d%C3%A9missions-s-encha%C3%AEnent-au-sein-du-parti-d%C3%A9mocratique-gabonais?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

