-- Batch 4 - Section 1/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES (
        'ed0154d8-b048-4ef2-a1d4-72ee3edda212',
        'Face au différend frontalier, Brice Clotaire Oligui Nguema consulte les sages et notables au Palais Rénovation',
        'Face à un conflit frontalier, Brice Clotaire Oligui Nguema consulte les sages et notables pour trouver une solution pacifique et rassurer la population.',
        'https://kongossanews.info/face-au-differend-frontalier-brice-clotaire-oligui-nguema-consulte-les-sages-et-notables-au-palais-renovation/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7fa5b08-ac2a-4064-abaf-73482ac038b5',
        'Publié le 29 / 05 / 2025',
        'Le Rapid et le PPU ont fusionné pour créer une nouvelle entité visant à renforcer leur contribution au développement du Gabon.',
        'https://union.sonapresse.com/fr/le-rapid-et-le-ppu-fusionnent-pour-creer-ensemble-pour-le-gabon',
        'L''union',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d7acc68-d89e-4f70-b685-10aa8b5eb675',
        'Publié le 29 / 05 / 2025',
        'Guy Rossatanga Rignault affirme que les autorités sont conscientes de la situation concernant Mbanie et que tout le monde est au courant.',
        'https://union.sonapresse.com/fr/pr-guy-rossatanga-rignault-sur-laffaire-mbanie-nous-savons-quils-savent-que-nous-savons',
        'L''union',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40879b27-a675-4b89-8435-c0a0495bd43e',
        'Publié le 29 / 05 / 2025',
        'Un nettoyage complet du fichier des GEF est prévu pour améliorer la gestion et la fiabilité des données, en vue d''une meilleure organisation et utilisation.',
        'https://union.sonapresse.com/fr/cnamgs-vers-un-toilettage-complet-du-fichier-des-gef',
        'L''union',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8abd9481-53b1-4af6-a156-49e9f581e4d5',
        'CNAMGS : Oligui Nguema pour une résorption des dysfonctionnements de la structure Sécurité alimentaire : le faux pas du Dr. Jean...',
        'Le président de la Cnamgs, Oligui Nguema, s''est engagé à résoudre les dysfonctionnements de la structure pour garantir une meilleure gestion et satisfaction des usagers.',
        'https://mediapostegabon.com/cnamgs-oligui-nguema-pour-une-resorption-des-dysfonctionnements-de-la-structure/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce8da40b-a4ab-40fb-b147-7517b43fb228',
        'Football / Obsèques : Aaron Boupenza fait Officier dans l’ordre national du mérite gabonais à titre posthume',
        'Le Gabon a honoré posthumément l''ancien footballeur Aaron Boupendza en le nommant Officier dans l’ordre national du mérite gabonais pour ses réalisations dans sa carrière sportive.',
        'https://agpgabon.ga/2025/05/29/football-obseques-aaron-boupenza-fait-officier-dans-lordre-national-du-merite-gabonais-a-titre-posthume/',
        'AGP',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '99017478-8488-43e0-a5de-bc65cafc6666',
        'Football/Obsèques : « Aaron Boupendza restera à jamais dans mon cœur », dixit André Poko',
        'André Poko exprime sa douleur après le décès de son ami et "petit frère" Aaron Boupendza, en disant qu''il gardera à jamais ces moments précieux en lui.',
        'https://agpgabon.ga/2025/05/29/football-obseques-aaron-boupendza-restera-a-jamais-dans-mon-coeur-dixit-andre-poko/',
        'AGP',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7afe2682-3246-43fc-9be0-e1fe4545e076',
        'Football/Obsèques : début de l’hommage national à Aaron Boupendza',
        'Le corps d’Aaron Boupendza a été amené au Palais des Sports de Libreville pour un dernier hommage, en présence de sa famille, d’anciens coéquipiers et de nombreux fans, marquant le début des funérailles nationales.',
        'https://agpgabon.ga/2025/05/29/football-necrologie-debut-de-lhommage-national-a-aaron-boupendza/',
        'AGP',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9024c481-f11e-4e17-b8c1-8a558c824df9',
        'Nouvelle coupure générale d’électricité dans le Grand Libreville : la SEEG explique ce qui s’est passé',
        'Une panne importante d''électricité a récemment eu lieu dans le Grand Libreville, et la SEEG a expliqué les causes de cette coupure.',
        'https://gabonactu.com/blog/2025/05/29/nouvelle-coupure-generale-delectricite-dans-le-grand-libreville-la-seeg-explique-ce-qui-sest-passe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97bce82f-fd56-4c74-aa7e-084be139d4d3',
        'Sidy Ould Tah, nouveau président de la BAD',
        'Sidou Ould Tah, de la Mauritanie, a été élu président de la Banque africaine de développement (BAD) lors d''une élection en Abidjan, après plusieurs tours de scrutin.',
        'https://gabonactu.com/blog/2025/05/29/sidy-ould-tah-nouveau-president-de-la-bad/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '791f657e-135c-4ef8-ab1c-cf1e9d92ce11',
        'Sidi Ould Tah nouveau président de la Banque Africaine de Développement',
        'Sidi Ould Tah, ancien ministre mauritanien de l’Économie, a été élu président de la Banque africaine de développement pour un mandat, confronté à des enjeux liés au climat, aux tensions commerciales et à d’autres défis économiques en Afrique.',
        'https://www.gabonews.com/fr/actus/economie/article/sidi-ould-tah-nouveau-president-de-la-banque',
        'Gabonews',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4450a7f4-d018-4881-a6b4-29dbe096971a',
        'Football/Obsèques : la République a rendu un dernier hommage à Aaron Boupendza',
        'La nation gabonaise a rendu un dernier hommage à Aaron Boupendza lors d''une cérémonie de plusieurs heures au Palais des sports de Libreville, en présence de hauts responsables et de la population.',
        'https://agpgabon.ga/2025/05/29/football-obseques-la-republique-a-rendu-un-dernier-hommage-a-aaron-boupendza/',
        'AGP',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f056be11-7a78-4e89-bdfb-aa664ca6b7da',
        'Le mauritanien Sidi Ould Tah élu 9ème président de la BAD créée en 1964',
        'Sidi Ould Tah, originaire de Mauritanie, a été élu président de la Banque africaine de développement en succédant à un autre leader, avec le soutien de plusieurs personnalités et institutions financières africaines.',
        'https://gabonactu.com/blog/2025/05/29/le-mauritanien-sidi-ould-tah-elu-9eme-president-de-la-bad-creee-en-1964/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5449c48f-7fee-4d6f-80d6-896e0bc12d96',
        'L''Amicale des Anciens du Lycée d''État de Port-Gentil – Génération 80 officiellement lancée',
        'Une trentaine d’anciens élèves des années 1980 du Lycée d''État de Port-Gentil ont créé une association pour préserver la mémoire de leur école et renforcer les liens entre les générations lors d’une assemblée à Libreville.',
        'https://www.gabonews.com/fr/actus/societe/article/l-amicale-des-anciens-du-lycee-d-etat-de-port',
        'Gabonews',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2f672f1-0819-451e-832f-be278ece52b3',
        'Gabon – Guinée équatoriale : le Président de la République reçoit officiellement l’arrêt de la Cour internationale de Justice',
        'Le président gabonais a reçu l''arrêt de la Cour internationale de Justice concernant le différend territorial avec la Guinée équatoriale, marquant une étape importante dans la résolution du conflit.',
        'https://vxp241.com/2025/05/29/gabon-guinee-equatoriale-le-president-de-la-republique-recoit-officiellement-larret-de-la-cour-internationale-de-justice/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-29T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44446840-421a-4352-9371-3b2064f4a579',
        'Gabon: hommage national pour le footballeur Aaron Boupendza décédé en avril en Chine',
        'Le Gabon a rendu hommage à Aaron Boupendza, joueur de football gabonais décédé à 28 ans après une chute en Chine, en réunissant des officiels, des sportifs et des proches lors d’une cérémonie à Libreville.',
        'https://www.rfi.fr/fr/afrique/20250529-gabon-hommage-national-pour-le-footballeur-aaron-boupendza-d%C3%A9c%C3%A9d%C3%A9-en-avril-en-chine',
        'RFI',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98d356ff-202e-4818-9f48-a5c64fb77e4a',
        'Gabon: hommage national pour le footballeur Aaron Boupendza décédé en avril en Chine',
        'Le 29 mai, le Gabon a rendu un hommage national à Aaron Boupendza, attaquant de football décédé en avril en Chine suite à une chute depuis le 11ème étage de son immeuble.',
        'https://www.rfi.fr/fr/afrique/20250529-gabon-hommage-national-pour-le-footballeur-aaron-boupendza-d%C3%A9c%C3%A9d%C3%A9-en-avril-en-chine?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fe25def-d91c-45d8-9b07-ed4e077b2794',
        'Projet de loi sur les partis politiques au Gabon : réduction drastique  du nombre des formations politiques en vue',
        'Le gouvernement gabonais prévoit de réduire fortement le nombre de partis politiques en mettant en place une nouvelle loi pour limiter leur multiplication.',
        'https://gabonactu.com/blog/2025/05/30/projet-de-loi-sur-les-partis-politiques-au-gabon-reduction-drastique-du-nombre-des-formations-politiques-en-vue/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '02ae0509-33c2-4ed0-9d6a-1ab159fc265a',
        'Remise officielle de la décision de la Cour internationale de justice sur le différend frontalier entre le Gabon et la Guinée équatoriale',
        'Le verdict de la Cour internationale de justice concernant la délimitation des frontières entre le Gabon et la Guinée équatoriale a été officiellement annoncé lors d''une cérémonie au Palais du Bord de Mer en présence du président gabonais.',
        'https://www.gabonews.com/fr/actus/politique/article/remise-officielle-de-la-decision-de-la-cour',
        'Gabonews',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cdcf1127-f2df-445c-a593-ede2ab63e13f',
        'Afrique Centrale : situation « assez stable, bien que préoccupante », selon la CEEAC',
        'Des experts ont discuté à N’Djamena des transitions politiques, des tensions sécuritaires et des enjeux humanitaires en Afrique centrale lors de la 59e session du Comité UNSAC.',
        'https://www.gabonews.com/fr/actus/politique/article/afrique-centrale-situation-assez-stable-bien-que',
        'Gabonews',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c6537ee0-116b-4499-b85e-54b005c75340',
        'UE/GABON : Une coopération renforcée pour l''hydroélectricité',
        'Le Gabon et l’Union européenne renforcent leur coopération en matière d’énergie durable, notamment à travers des projets hydroélectriques stratégiques pour l’indépendance énergétique du pays.',
        'https://www.gabonews.com/fr/actus/cooperation/article/ue-gabon-une-cooperation-renforcee-pour-l',
        'Gabonews',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98b207c2-82d7-4eae-b275-43f1c4458b8a',
        'Washington a levé toutes ses sanctions contre le Gabon',
        'Les États-Unis ont levé toutes leurs sanctions contre le Gabon, permettant ainsi de renforcer les relations bilatérales et de favoriser le développement économique du pays.',
        'https://gabonactu.com/blog/2025/05/30/washington-a-leve-toutes-ses-sanctions-contre-le-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24914254-dc2e-403e-8a45-82ad8e798c1f',
        'Bourses d’études « Concorde » : Postulez jusqu’au 27 juin',
        'Les étudiants gabonais en fin de cycle (Licence et Master) diplômés depuis moins de deux ans peuvent postuler aux bourses d’études « Concorde» jusqu’au 27 juin.',
        'https://gabonactu.com/blog/2025/05/30/bourses-detudes-concorde-postulez-jusquau-27-juin/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '920a26fc-5f1d-4747-9ae0-8a25fa7ce8bd',
        'Conseil des ministres ce vendredi',
        'Un conseil des ministres s’est tenu ce vendredi pour discuter de l’administration du pays après la transition, sous la présidence de Brice Clotaire Oligui Nguema.',
        'https://gabonactu.com/blog/2025/05/30/conseil-des-ministres-ce-vendredi-2/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca9df664-97b0-4ee3-b3ba-b056879ab8c0',
        'Justice pour les parlementaires dont le mandat a été écourté après le coup d’Etat du 30 août 2023 (Tribune libre par Pierre Moussounda)',
        'L''article dénonce la justice inéquitable envers les parlementaires dont les mandats ont été interrompus suite au coup d''État du 30 août 2023, en appelant à une réparation de leurs droits.',
        'https://gabonactu.com/blog/2025/05/30/justice-pour-les-parlementaires-dont-le-mandat-a-ete-ecourte-apres-le-coup-detat-du-30-aout-2023-tribune-libre-par-pierre-moussounda/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad98d871-8eaa-49bc-9b4f-277beee1b8e7',
        'Port-Gentil : mort atroce d’un élève du lycée technique',
        'Un élève du lycée technique de Port-Gentil a trouvé une fin tragique dans des circonstances atroces, provoquant une grande émotion dans la communauté locale.',
        'https://gabonactu.com/blog/2025/05/30/port-gentil-mort-atroce-dun-eleve-du-lycee-technique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4035cb1-a93c-4b6a-a8ed-d9215fc35403',
        'Couvre-feu : L’oublié de la « 5ème République »',
        'Depuis l’instauration du couvre-feu en avril 2023 après un coup d’Etat, cette mesure semble avoir été oubliée ou négligée dans le cadre de la « 5ème République » en cours.',
        'https://gabonactu.com/blog/2025/05/30/couvre-feu-loublie-de-la-5eme-republique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '32955dbc-ced4-4351-9871-366967f4fbf2',
        '[Tribune] Lettre ouverte à Madame Zita Oligui Nguema, Première Dame de la République gabonaise',
        'Une lettre ouverte dénonce la violence et la mortalité évitable des femmes au Gabon, appelant la Première Dame à agir pour améliorer leur condition et garantir leur sécurité.',
        'https://www.gabonreview.com/tribune-lettre-ouverte-a-madame-zita-oligui-nguema-premiere-dame-de-la-republique-gabonaise/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8c2f7e5a-5a1a-4a35-b4c5-17fb312600e9',
        'Transport aérien : Afrijet/FLYGABON appelle à l’ouverture en urgence d’une concertation sur le financement du secteur',
        'Afrijet appelle à une concertation urgente pour déterminer comment financer durablement le secteur aérien au Gabon.',
        'https://gabonmediatime.com/transport-aerien-afrijet-flygabon-appelle-a-louverture-en-urgence-dune-concertation-sur-le-financement-du-secteur/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8461d3a6-8ca4-4d83-a331-e9141dd8663c',
        'Gabon : traité de «feuilles mortes», Paul Biyoghe Mba riposte et retourne la métaphore contre le Blaise Louembe',
        'Paul Biyoghé Mba réagit vivement à la métaphore de Blaise Louembe, qualifiée de "feuilles mortes", en lui retournant la polémique et en défendant son positionnement politique.',
        'https://gabonmediatime.com/gabon-traite-de-feuilles-mortes-paul-biyoghe-mba-riposte-et-retourne-la-metaphore-contre-le-blaise-louembe/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'abeb75bf-1082-4445-80b1-ba09212a8419',
        'Journées Pétrole 2025 : Gaëtan Mboza dévoile ses clés pour sécuriser les contrats de partage',
        'Géatan Mboza explique comment sécuriser les contrats de partage dans le secteur pétrolier afin d''attirer davantage d''investissements et de garantir la transparence.',
        'https://gabonmediatime.com/journees-petrole-2025-gaetan-mboza-devoile-ses-cles-pour-securiser-les-contrats-de-partage/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9524501f-b3ec-4c18-bc3d-237ace3b0dbb',
        'Zita Oligui Nguema marraine des premières Olympiades de l’Éducation nationale',
        'Zita Oligui Nguema a été nommée marraine des premières Olympiades de l’éducation nationale, visant à encourager l''excellence scolaire et la valorisation des jeunes talents.',
        'https://kongossanews.info/zita-oligui-nguema-marraine-des-premieres-olympiades-de-leducation-nationale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45ef106d-7196-4183-8aec-0926490c5f40',
        'Zita Oligui Nguema marraine des premières Olympiades de l’Éducation national',
        'Une compétition nationale éducative, les premières Olympiades, ont été lancées sous le haut patronage de Zita Oligui Nguema, pour encourager l''excellence scolaire.',
        'https://kongossanews.info/education-nationale-les-premieres-olympiades-sous-le-haut-patronage-de-zita-oligui-nguema/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ed65f5a-dab4-4f70-9ee4-900bc3b5717c',
        'Publié le 30 / 05 / 2025',
        'Le Gabon et la Grande-Bretagne ont discuté de la coopération bilatérale, notamment dans les domaines économique, éducatif et sécuritaire, afin de renforcer leur partenariat.',
        'https://union.sonapresse.com/fr/gabon-grande-bretagne-la-cooperation-bilaterale-evoquee-avec-le-vpg',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2d23ba9-4b35-4288-9b68-a65d1ddfac03',
        'Publié le 30 / 05 / 2025',
        'La Cour de justice de la Cei a prononcé la dissolution de certains partis politiques en Côte d''Ivoire en raison de leur non-respect de l''obligation patriotique, ce qui soulève des enjeux sur la stabilité démocratique et la loyauté politique.',
        'https://union.sonapresse.com/fr/apres-larret-de-la-cij-obligation-patriotique',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f430ce5-b04b-4592-8424-87a8c75d514a',
        'Publié le 30 / 05 / 2025',
        'Le comité de rédaction a examiné le projet de loi sur les partis politiques, soulignant ses implications et demandant des ajustements pour renforcer le cadre démocratique.',
        'https://union.sonapresse.com/fr/avant-projet-de-loi-sur-les-partis-politiques-le-comite-de-redaction-livre-sa-copie',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c70fda1b-d088-45a3-b45b-075d9dc90f2a',
        'Paysage politique : Recomposition à marche forcée ?',
        'Plusieurs démissions dans le Parti démocratique gabonais (PDG) semblent être une stratégie de repositionnement politique, traduisant une recomposition forcée du paysage politique au Gabon.',
        'https://www.gabonreview.com/paysage-politique-recomposition-a-marche-forcee/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f665139e-81ec-4054-9588-0ce951a62165',
        'Transport aérien : Afrijet/FLYGABON appelle à l’ouverture en urgence d’une concertation sur le financement du secteur',
        'AfriJet et FlyGabon appellent à une concertation urgente pour trouver des solutions durables au financement du secteur aérien afin de garantir sa stabilité et son développement.',
        'https://gabonmediatime.com/transport-aerien-afrijet-flygabon-appelle-a-louverture-en-urgence-dune-concertation-sur-le-financement-du-secteur/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7393a9d5-c178-4434-b9fb-b487201e6b1c',
        'Gabon : traité de «feuilles mortes», Paul Biyoghe Mba riposte et retourne la métaphore contre le Blaise Louembe',
        'L''article présente une réponse virulente à une métaphore critique employée par Blaise Louembe, où Paul Biyoghé-Mba la renverse en confrontant ses propos de manière directe et polémique.',
        'https://gabonmediatime.com/gabon-traite-de-feuilles-mortes-paul-biyoghe-mba-riposte-et-retourne-la-metaphore-contre-le-blaise-louembe/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c714ef4-6375-401a-88e4-16ae0a3fdd5a',
        'Journées Pétrole 2025 : Gaëtan Mboza dévoile ses clés pour sécuriser les contrats de partage',
        'Géatan Mboza partage des stratégies pour sécuriser les contrats de partage dans le secteur pétrolier afin d’assurer une meilleure gestion et valorisation des ressources.',
        'https://gabonmediatime.com/journees-petrole-2025-gaetan-mboza-devoile-ses-cles-pour-securiser-les-contrats-de-partage/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '377a5414-0bc1-479d-8c3c-2ec13c587f8a',
        'Zita Oligui Nguema marraine des premières Olympiades de l’Éducation nationale',
        'Zita Oligui Nguema a été nommée marraine des premières Olympiades de l''Éducation nationale, visant à encourager l''excellence scolaire en Guinée équatoriale.',
        'https://kongossanews.info/zita-oligui-nguema-marraine-des-premieres-olympiades-de-leducation-nationale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10aa8c36-b75e-4051-986e-6a464585dd1d',
        'Zita Oligui Nguema marraine des premières Olympiades de l’Éducation national',
        'La première édition des Olympiades de l''éducation nationale, sous le haut patronage de Zita Oligui Nguema, vise à encourager l''excellence académique et à valoriser les talents des élèves dans divers domaines scolaires.',
        'https://kongossanews.info/education-nationale-les-premieres-olympiades-sous-le-haut-patronage-de-zita-oligui-nguema/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b04eb649-38fb-430b-bc57-7d1187cb6664',
        'Publié le 30 / 05 / 2025',
        'Une réunion a permis d’échanger sur la coopération bilatérale entre le Gabon et la Grande-Bretagne, notamment dans les domaines du développement et de la sécurité.',
        'https://union.sonapresse.com/fr/gabon-grande-bretagne-la-cooperation-bilaterale-evoquee-avec-le-vpg',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6c0bc49-1902-4989-bb18-f5f8ecc98179',
        'Publié le 30 / 05 / 2025',
        'La Cour de justice de la CEDEAO a annulé la décision sénégalaise imposant une obligation patriotique aux citoyens, soulignant l''importance du respect des droits fondamentaux.',
        'https://union.sonapresse.com/fr/apres-larret-de-la-cij-obligation-patriotique',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.447Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78a3d576-6de5-4c27-8c72-cf347b9f6379',
        'Publié le 30 / 05 / 2025',
        'Le comité de rédaction a publié un avis critique sur le projet de loi relatif aux partis politiques, soulignant ses implications et questionnant certains aspects de sa mise en œuvre.',
        'https://union.sonapresse.com/fr/avant-projet-de-loi-sur-les-partis-politiques-le-comite-de-redaction-livre-sa-copie',
        'L''union',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9de5dae-3a89-455c-85e4-c139b70ef560',
        'Football/Panthères du Gabon : la liste dévoilée le samedi 31 mai prochain',
        'La liste des joueurs gabonais sélectionnés pour les matchs amicaux contre le Niger et la Guinée-Bissau en juin sera annoncée le 31 mai, avec notamment huit joueurs issus du championnat national, dont cinq nouveaux.',
        'https://agpgabon.ga/2025/05/30/football-pantheres-du-gabon-la-liste-devoilee-le-samedi-31-mai-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b60d1f1-564c-4e5b-a786-f9352649dcda',
        'Manganèse : La nomination du nouveau DG d’Eramet, une opportunité à saisir pour le Gabon',
        'La nomination du nouveau directeur général d’Eramet représente une opportunité pour le Gabon de renforcer son secteur du manganèse et d’attirer davantage d’investissements dans ce domaine.',
        'https://directinfosgabon.com/manganese-la-nomination-du-nouveau-dg-deramet-une-opportunite-a-saisir-pour-le-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65f10d4a-2970-4038-88d5-612c67bb2299',
        'Perenco mise sur le Gabon pour accélérer sa transition énergétique',
        'Perenco prévoit d''investir au Gabon pour accélérer sa transition vers des énergies plus propres et renforcer ses projets stratégiques dans la région africain.',
        'https://directinfosgabon.com/perenco-mise-sur-le-gabon-pour-accelerer-sa-transition-energetique/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'be0d2618-5622-4cb0-b9b7-3c44a0fc1acb',
        'Le Gabon salué par l’UE pour sa lutte contre la déforestation',
        'La Commission européenne a reconnu les efforts du Gabon dans la lutte contre la déforestation, en le plaçant parmi les pays les moins risqués selon le règlement européen sur la déforestation.',
        'https://directinfosgabon.com/le-gabon-salue-par-lue-pour-sa-lutte-contre-la-deforestation/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9025584-d2c7-4233-b5fb-edde16d34b16',
        'Rencontre entre la Première Dame du Gabon et l''Ambassadeur d''Afrique du Sud : vers un partenariat au service des femmes, des jeunes et des enfants',
        'La Première Dame du Gabon a rencontré l''ambassadrice d''Afrique du Sud pour discuter de projets communs en faveur des enfants et des jeunes.',
        'https://www.gabonews.com/fr/actus/cooperation/article/rencontre-entre-la-premiere-dame-du-gabon-et-l',
        'Gabonews',
        'Business Intelligence',
        '2025-05-30T00:00:00.000Z',
        '2025-09-15T23:06:12.448Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

