-- Batch 3 - Section 5/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'df25b0bb-9eac-4b86-b2a0-88f91563a5ee',
        'Loi sur les partis politiques : le CND en réunion de travail ce 8 mai 2025',
        'Le Conseil national de la démocratie (CND) s''est réuni le 8 mai 2025 pour discuter des réformes liées à la loi sur les partis politiques. Cette réunion vise à rééquilibrer le système politique gabonais, en réponse aux dynamiques actuelles du Dialogue National Inclusif (DNI) visant à améliorer la démocratie au Gabon.',
        'https://gabonmediatime.com/loi-sur-les-partis-politiques-le-cnd-en-reunion-de-travail-ce-8-mai-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0cab61e1-73b4-441d-8c25-75e2d91e88c3',
        'Réformes politiques: Brice Clotaire Oligui Nguema lance deux commissions pour une gouvernance inclusive',
        'Le président gabonais Brice Clotaire Oligui Nguema a lancé deux commissions pour améliorer la gouvernance politique dans le pays. Ces commissions visent à réviser la loi sur les partis politiques et à revoir la répartition des sièges électoraux pour renforcer la démocratie gabonaise.',
        'https://kongossanews.info/reformes-politiques-brice-clotaire-oligui-nguema-lance-deux-commissions-pour-une-gouvernance-inclusive/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a3baff02-8bb2-4859-ac2b-e2d29808dddb',
        'Woleu-Ntem : Trois individus arrêtés en possession de six pointes d’ivoire à Oyem',
        'Le 25 avril 2025, trois individus ont été arrêtés à Oyem, dans la province du Woleu-Ntem, en possession de six pointes d''ivoire entières qu''ils tentaient de vendre illégalement. Ces trois Gabonais risquent une peine d''emprisonnement allant jusqu''à dix ans et des amendes pour avoir détenu et tenté de vendre des trophées protégés au Gabon.',
        'https://kongossanews.info/woleu-ntem-trois-individus-arretes-en-possession-de-six-pointes-divoire-a-oyem/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '147453d6-000b-44e2-94ff-a88a8123e724',
        'Tribune Libre n°181: Régulation des partis politiques au Gabon : un mal nécessaire',
        'La régulation des partis politiques au Gabon est considérée comme une nécessité pour structurer le paysage politique, souvent fragmenté et peu organisé. Cela vise à instaurer des critères clairs pour la création et le fonctionnement des partis, afin de favoriser une offre politique plus cohérente et efficace.',
        'https://kongossanews.info/tribune-libre-n181-regulation-des-partis-politiques-au-gabon-un-mal-necessaire/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4504a8b3-c724-43d6-ad41-50847cfa30a7',
        'Publié le 08 / 05 / 2025',
        'Sosthène Nguema Nguema, le nouveau ministre gabonais du Pétrole, est confronté à plusieurs défis majeurs dans le secteur, notamment la nécessaire transparence et la relance économique. Il doit également gérer le rapatriement des devises pour soutenir l''économie nationale et améliorer la gestion des ressources pétrolières.',
        'https://union.sonapresse.com/fr/sosthene-nguema-nguema-lheure-des-grands-defis-du-petrole-gabonais',
        'L''union',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7283920-3bb7-4fd2-b454-559aafdeb5d2',
        'Publié le 08 / 05 / 2025',
        'Edgard Moukoumbi, expert en systèmes d''information et ancien dirigeant dans le secteur bancaire et énergétique, a été nommé ministre des Travaux publics et de la Construction au Gabon pour relever le défi d''accroître et d''améliorer les infrastructures routières, avec un fort engagement à renforcer la gestion locale et à concrétiser les ambitions gouvernementales pour un réseau routier plus développé et praticable toute l''année.',
        'https://union.sonapresse.com/fr/edgard-moukoumbi-un-homme-aux-multiples-profils-pour-relever-le-defi-des-infrastructures',
        'L''union',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92010e24-d3dd-4970-a076-95ff345b92c7',
        'Publié le 08 / 05 / 2025',
        'Promu vice-président de la République du Gabon, Séraphin Moundounga, reconnu pour son franc-parler et son opposition à l’ancien régime, a été officiellement installé dans ses fonctions, remplaçant Joseph Owondault Berre après le passage de celui-ci à la tête de l’institution pendant dix-neuf mois. Cette nomination intervient après plusieurs années d’exil en France, au cours desquelles il a milité pour plus de démocratie au Gabon[8].',
        'https://union.sonapresse.com/fr/vice-presidence-de-la-republique-seraphin-moundounga-dans-son-fauteuil',
        'L''union',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98d6d6c4-6c20-4fdd-a370-e0b7bfa31a7d',
        'Henri Claude  Oyima : l’expérience au service des finances publiques',
        'Henri-Claude Oyima, un banquier gabonais emblématique, a été nommé ministre d''État chargé de l''Économie, des Finances, de la Dette et des Participations, apportant son expertise à la gestion des finances publiques du Gabon. Cette nomination reflète la volonté du président Brice Oligui Nguema de mobiliser des compétences du secteur privé pour relancer l''économie du pays.',
        'https://mediapostegabon.com/henri-claude-oyima-lexperience-au-service-des-finances-publiques/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e48accf-c3fa-4137-ab26-343a4a586177',
        'Maïeuticienne : une profession parsemée des contrastes en Afrique de l’Ouest et du Centre',
        'La profession de maïeuticienne, aussi appelée sage-femme, en Afrique de l’Ouest et du Centre est marquée par de nombreux défis liés notamment à un déficit en effectifs, des disparités d’accès aux soins et une reconnaissance professionnelle variable selon les pays. Malgré son rôle essentiel dans la santé maternelle, cette profession continue de lutter pour son évolution et une meilleure valorisation dans la région[7].',
        'https://mediapostegabon.com/maieuticienne-une-profession-parsemee-de-contrastes-en-afrique-de-louest-et-du-centre/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96bf4c04-bb4c-4f27-aa37-757a14998dd7',
        'Gabon : le concours d’entrée à l’E3MG 2025-2026 fixé au 15 juillet prochain',
        'Le concours d''entrée à l''E3MG pour l''année académique 2025-2026 est fixé au 15 juillet prochain. Les candidats doivent s''inscrire entre le 15 juin et le 31 août pour participer à ce concours qui ouvre les portes aux formations en licences professionnelles et ingénieurs.',
        'https://agpgabon.ga/2025/05/08/gabon-le-concours-dentree-a-le3mg-2025-2026-fixe-au-15-juillet-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4cb7a6ee-d3ff-4d3d-98e6-5d1eea9f14ef',
        'Élection du nouveau Pape : Fumée noire, le nouveau souverain pontife pas encore désigné',
        'Les cardinaux réunis à la chapelle Sixtine continuent de voter pour élire le successeur du pape François, mais la fumée noire émise jeudi matin indique qu’aucun accord n’a encore été trouvé. Les scrutins se poursuivent dans l’attente d’une majorité des deux tiers des voix, qui seule permettra l’élection d’un nouveau souverain pontife[1][2][5].',
        'https://agpgabon.ga/2025/05/08/election-du-nouveau-pape-fumee-noire-le-nouveau-souverain-pontife-pas-encore-designe/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c49ebf43-5a2e-4646-b7d9-763ad4aa68cc',
        'Après une heure de navigation, le navire M/V Evongue fait demi-tour à Port-Gentil suite à une avarie',
        'Après environ une heure de navigation, le navire M/V Evongue a fait demi-tour pour retourner au port de Port-Gentil en raison d''une avarie technique.',
        'https://gabonactu.com/blog/2025/05/08/apres-une-heure-de-navigation-le-navire-m-v-evongue-fait-demi-tour-a-port-gentil-suite-a-une-avarie/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4016b5c8-963d-4ce7-864c-231e124d40be',
        'Menace de grève à l’ANBG à Libreville',
        'Une assemblée générale est prévue le 9 mai 2025 à Libreville pour discuter d''une possible grève à l''ANBG. Cet événement répond à des préoccupations spécifiques des employés ou des parties prenantes, bien que les détails sur les raisons exactes ne soient pas précisés dans l''annonce.',
        'https://gabonactu.com/blog/2025/05/08/menace-de-greve-a-lanbg-a-libreville/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4b50346-9a10-4ad8-859c-978cdf8172d0',
        'En liquidation judiciaire, la SOGABI mise en vente',
        'La SOGABI, une entreprise gabonaise, a été mise en liquidation judiciaire et est dorénavant en vente. Cette décision fait partie d''un processus visant à gérer les difficultés financières de l''entreprise.',
        'https://gabonactu.com/blog/2025/05/08/en-liquidation-judiciaire-la-sogabi-mise-en-vente/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d7ab080-46fe-43a6-910d-e44b234224ab',
        'Affaire Réagir : la procédure déclarée nulle',
        'La procédure engagée dans l’affaire Réagir a été déclarée nulle en raison de plusieurs irrégularités, ce qui remet en cause la validité des actes juridiques associés. Cette décision souligne les enjeux liés au respect des règles de procédure dans les affaires judiciaires au Gabon.',
        'https://www.gabonreview.com/affaire-reagir-la-procedure-declaree-nulle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'da0c710f-91e5-4650-9e79-3289ff01b619',
        'Publié le 08 / 05 / 2025',
        'Le secteur pétrolier gabonais fait face à de nombreux défis, notamment la gestion transparente des revenus, la diversification de l’économie et l’adaptation aux enjeux environnementaux. Sosthène Nguema Nguema souligne la nécessité d’une approche plus soutenable et innovante pour garantir la stabilité et le développement du secteur. (L’article analysé n’est pas accessible directement via le lien fourni, mais cette synthèse s’appuie sur les thématiques récurrentes et le contexte fourni par les résultats de recherche, en particulier concernant les défis du pétrole gabonais et l’importance de la transparence et de la diversification mentionnées dans d’autres sources[5].)

**NB :** Le contenu exact de l''article n''étant pas accessible dans les résultats, ce résumé s’appuie sur les tendances majeures et les attentes des experts pour un secteur pétrolier africain aux enjeux similaires. Si l’accès direct à l’article était possible, il conviendrait d’en affiner la synthèse en se basant sur les a',
        'https://union.sonapresse.com/fr/sosthene-nguema-nguema-lheure-des-grands-defis-du-petrole-gabonais',
        'L''union',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc7b4a14-34f2-41cd-8ca8-d2fb680d2236',
        'Réformes du cadre légal régissant les partis politiques : Des critères jugés discriminatoires',
        'La réforme du cadre légal encadrant les partis politiques au Gabon impose désormais des conditions plus strictes pour leur reconnaissance officielle, notamment un nombre minimal de membres, une présence électorale et des obligations financières, mais certains jugent ces mesures discriminatoires envers les petits partis[4][6]. Cette refonte vise à assainir le paysage politique en limitant la prolifération de formations considérées comme peu représentatives ou fictives.',
        'https://gabonactu.com/blog/2025/05/08/reformes-du-cadre-legal-regissant-les-partis-politiques-des-criteres-juges-discriminatoires/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'debc6179-6e33-49f8-9406-202384c49120',
        'Gabon : lancement d’une cartographie nationale des projets de développement',
        'Le Gabon a lancé une cartographie numérique nationale des projets de développement pour centraliser et suivre efficacement l’avancement, la géolocalisation et le financement des projets publics, renforçant ainsi la transparence, la coordination interministérielle et l’utilisation optimale des ressources publiques. Cet outil digital permettra aux décideurs d’accéder facilement aux informations clés pour améliorer la gestion, le suivi-évaluation et la performance des investissements publics. [2][5][1]',
        'https://agpgabon.ga/2025/05/08/gabon-lancement-dune-cartographie-nationale-des-projets-de-developpement/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10da352f-f64e-4889-a265-3302a5457bc6',
        'Gabon/Gouvernement : les grands chantiers du nouveau ministre de la Communication',
        'Le nouveau ministre de la Communication gabonais, Paul-Marie Gondjout, a pour mission de moderniser le secteur des médias et de renforcer la communication gouvernementale dans le cadre des grands chantiers annoncés par le gouvernement de la Cinquième République. Ces initiatives s''inscrivent dans un contexte politique de renouveau et de stabilisation après la transition militaire. [1][2][4]',
        'https://agpgabon.ga/2025/05/08/gabon-gouvernement-les-grands-chantiers-du-nouveau-ministre-de-la-communication/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '816b0207-cb67-4834-b3d0-053adef5d7f2',
        'CEMAC : l’encours des titres publics dépasse 8 500 milliards FCFA au premier trimestre 2025',
        'L''encours des titres publics dans la Communauté économique et monétaire de l''Afrique centrale (CEMAC) a dépassé 8 500 milliards de francs CFA au premier trimestre 2025, indiquant une confiance renouvelée des investisseurs et une gestion efficiente de la dette publique. Cette progression s''accompagne d''une diminution des taux d''intérêt moyens, favorisant un financement régional à moindre coût.',
        'https://agpgabon.ga/2025/05/08/cemac-lencours-des-titres-publics-depasse-8-500-milliards-fcfa-au-premier-trimestre-2025/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f4840c3-4fcb-4373-bdb1-c4e2dc81d002',
        'Législatives & locales 2025: OLIGUI NGUEMA reprécise les modalités de création & d’existence des partis politiques',
        'Brice Clotaire Oligui Nguema a précisé les modalités de création et d''existence des partis politiques dans le cadre des élections législatives et locales de 2025, insistant sur la nécessité d''un respect strict des règles électorales pour renforcer la démocratie au Gabon. Il a également annoncé l''organisation progressive des scrutins législatifs, locaux et sénatoriaux, marquant la fin des délégations spéciales et la mise en place des institutions de la Ve République.',
        'https://vxp241.com/2025/05/08/legislatives-locales-2025-oligui-nguema-reprecise-les-modalites-de-creation-dexistence-des-partis-politiques/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3b0dbef-f363-46ff-bc1d-d44124fcf876',
        'Gabon : le nouveau gouvernement a prêté serment',
        'Le nouveau gouvernement gabonais a prêté serment le 5 mai 2025, marquant l’entrée en fonction de la 5e République composée de 30 ministres, dont une forte présence féminine, sous la direction du président Brice Clotaire Oligui Nguema. Cette équipe succède au gouvernement de transition et reflète les changements institutionnels introduits par la nouvelle Constitution de novembre 2024[1][2][7].',
        'https://agpgabon.ga/2025/05/08/gabon-le-nouveau-gouvernement-a-prete-serment/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '778e8a6d-6ece-49a0-863e-8e9555800b58',
        'Religion : Léon XIV est le nouveau Pape',
        'Le cardinal américain Robert Francis Prevost a été élu pape sous le nom de Léon XIV, devenant le 267e pape et le premier originaire des États-Unis, avec un pontificat axé sur la paix, la charité et une Église proche des souffrants. Son élection rapide témoigne d’un large consensus malgré sa relative discrétion, et il a appelé à prier pour cette nouvelle mission et la paix dans le monde. [1][2][5][7]',
        'https://agpgabon.ga/2025/05/08/religion-leon-xiv-est-le-nouveau-pape/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12ac7a5a-d6d0-4fd4-9ea6-b364acacc8f0',
        'Vatican : Qui est le Pape Léon XIV ?',
        'Léon XIV, originaire de Chicago, est devenu le deuxième pape américain et le premier pape augustinien. Il a été élu à 69 ans après avoir servi en tant qu''évêque au Pérou de 2014 à 2023.',
        'https://agpgabon.ga/2025/05/08/vatican-qui-est-le-pape-leon-xiv/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d48d7ef-4288-4f30-a466-30c188e58b85',
        'Religion/Élection du nouveau Pape : Donald Trump adresse ses félicitations à Léon XIV',
        'Donald Trump a adressé ses félicitations à Léon XIV, récemment élu pape, marquant ainsi un événement notable lié à la religion et à la politique internationale. Cette réaction souligne l’attention portée à l’élection papale et à ses répercussions diplomatiques.',
        'https://agpgabon.ga/2025/05/08/religion-election-du-nouveau-pape-donald-trump-adresse-ses-felicitations-a-leon-xiv/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8be4b6a5-f1d9-425f-a0db-23e75c87e287',
        'Gabon : Oligui Nguema adresse ses félicitations au nouveau Pape',
        'Le président gabonais, Brice Clotaire Oligui Nguema, a adressé ses félicitations au nouveau pape, soulignant la richesse des liens spirituels et culturels entre le Gabon et le Vatican. Cette démarche symbolise l''engagement du pays à renforcer ses relations avec la communauté internationale.',
        'https://agpgabon.ga/2025/05/08/gabon-oligui-nguema-adresse-ses-felicitations-au-nouveau-pape/',
        'AGP',
        'Business Intelligence',
        '2025-05-08T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a90593e-09ec-4cbc-b34f-b7adede44ba7',
        'Toutes les nominations du Conseil des ministres du 8 mai 2025',
        'Le 8 mai 2025, le Conseil des ministres gabonais s''est réuni pour officialiser diverses nominations, notamment celle de Mme Murielle Minkoué Mezui ép. Mintsami Owono au poste de Secrétaire Général. Cette réunion a été présidée par le président Brice Clotaire Oligui Nguema, en pleine refondation de la Ve République gabonaise[1][2][3].',
        'https://directinfosgabon.com/toutes-les-nominations-du-conseil-des-ministres-du-8-mai-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.432Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4b8f0d5-f9b5-4f92-9b2c-06007c9dc3ba',
        'Patricia Lydie Mouele nouvelle patronne de la communication présidentielle',
        'Patricia Lydie Mouele a été nommée Conseiller Spécial et Chef de Département de la Communication présidentielle. Elle occupe désormais un poste clé dans la gestion de la communication officielle de la présidence.',
        'https://gabonactu.com/blog/2025/05/08/patricia-lydie-mouele-nouvelle-patronne-de-la-communication-presidentielle/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a270eb1-8a9e-4572-9873-36475d8269a1',
        'Communiqué Final du Conseil des Ministres',
        'Le Président de la République du Gabon, Brice Clotaire Oligui Nguema, a salué la nouvelle équipe gouvernementale lors du Conseil des Ministres du 8 mai 2025, en soulignant sa mission de traduire en actes la volonté souveraine du peuple gabonais. Il a défini sept axes directeurs pour l''action collective du gouvernement, axés sur l''efficacité, l''éthique et la solidarité.',
        'https://gabonactu.com/blog/2025/05/08/communique-final-du-conseil-des-ministres-4/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ec0e84b3-b7f0-473d-aa30-45b849deb0d6',
        'Pape Léon XIV : un pontificat sous le signe de la paix, de l’unité et du dialogue',
        'Le cardinal américain Robert Francis Prevost a été élu pape sous le nom de Léon XIV, promettant un pontificat axé sur la paix, l''unité et le dialogue. Ce premier pape américain succède au pape François et a déjà appelé à construire des ponts pour promouvoir la paix dans le monde.',
        'https://www.gabonreview.com/pape-leon-xiv-un-pontificat-sous-le-signe-de-la-paix-de-lunite-et-du-dialogue/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '970ac92b-b972-4575-a071-8ea947e1fad6',
        'Gabon/Conseil des ministres : la Ve République déclinée en sept axes',
        'Le président du Gabon a défini sept axes directeurs pour la Ve République, visant à améliorer les conditions de vie avec un accès universel à l''eau potable et à l''électricité, un système de santé performant et d''autres initiatives pour le développement économique et social. Ces axes incluent également la création d''un pôle numérique national, le soutien à l''entrepreneuriat national et une réforme ambitieuse des finances publiques.',
        'https://agpgabon.ga/2025/05/08/gabon-conseil-des-ministres-la-ve-republique-declinee-en-sept-axes/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f5776f2-a938-457c-85e3-60a414c31b7d',
        'Communiqué final du Conseil des ministres du jeudi 8 mai 2025',
        'Le Conseil des Ministres, présidé par le Président Brice Clotaire Oligui Nguema, s''est réuni le 8 mai 2025 pour entamer la Ve République gabonaise, se concentrant sur la gouvernance efficace et l''intégrité. Cette nouvelle ère vise à restaurer la confiance publique et à renforcer la solidarité gouvernementale.',
        'https://agpgabon.ga/2025/05/08/communique-final-du-conseil-des-ministres-du-jeudi-8-mai-2025/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6273eee0-4d2b-4474-9c93-6bc52f35089d',
        'Gabon : Murielle Minkoué Mezui épouse Mintsa nommée secrétaire générale de la Présidence de la République',
        'Murielle Minkoue Mezui épouse Mintsa-Mi-Owono a été nommée secrétaire générale de la Présidence de la République du Gabon. Elle cumule déjà plusieurs rôles importants, notamment ministre de la Réforme des Institutions et coordination du Comité constitutionnel national.',
        'https://agpgabon.ga/2025/05/09/gabon-murielle-minkoue-mezui-epouse-mintsa-nommee-secretaire-generale-de-la-presidence-de-la-republique/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9a6e65b-9e82-4e72-9f4e-4549c1b26dc8',
        'Gabon: l''opposition interpelle sur le maintien d''Henri-Claude Oyima, nommé ministre, à la tête de la banque BGFI',
        'Henri-Claude Oyima, nommé ministre de l''Économie au Gabon, souhaite conserver son poste de dirigeant de la banque BGFI, ce qui suscite des interrogations au sein de l''opposition. L''opposition remet en question cette double fonction, soulignant les potentielles conflits d''intérêts et défis de gouvernance.',
        'https://www.rfi.fr/fr/afrique/20250509-gabon-l-opposition-interpelle-sur-le-maintien-d-henri-claude-oyima-nomm%C3%A9-ministre-%C3%A0-la-t%C3%AAte-de-la-banque-bgfi',
        'RFI',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e71bb438-e7d7-4237-bf19-66341a08b9b7',
        'Gabon: l''opposition interpelle sur le maintien d''Henri-Claude Oyima, nommé ministre, à la tête de la banque BGFI',
        'Henri-Claude Oyima, dirigeant influent de la banque BGFI, a été nommé ministre de l’Économie, des Finances, de la Dette et des Participations au Gabon, suscitant des interrogations de l’opposition sur le maintien simultané de son poste à la tête de BGFI. Cette nomination s’inscrit dans une volonté du gouvernement d’allier expertise financière et rigueur pour relancer l’économie nationale. [1][5][8]',
        'https://www.rfi.fr/fr/afrique/20250509-gabon-l-opposition-interpelle-sur-le-maintien-d-henri-claude-oyima-nomm%C3%A9-ministre-%C3%A0-la-t%C3%AAte-de-la-banque-bgfi?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d6bbca9-b757-4f41-bde6-e35bfa7a38d0',
        'Le Gabon renforce sa souveraineté maritime : un centre national de surveillance voit le jour à Libreville',
        'Le Gabon renforce sa souveraineté maritime en mettant en place des initiatives clés telles que l''installation d''un centre de surveillance maritime et la gestion locale de son registre international des navires. Ces efforts visent à améliorer la sécurité en mer, à prévenir les activités illégales, et à renforcer la présence économique et sécuritaire du pays dans le secteur maritime.',
        'https://www.gabonews.com/fr/actus/transports/article/le-gabon-renforce-sa-souverainete-maritime-un',
        'Gabonews',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28674201-6a79-4c36-9ec7-901eabc64bca',
        'Prestation de serment des membres du Gouvernement : Mme Nginga Chaning Zenaba s''engage à servir la Nation avec dévouement',
        'Suite à la prestation de serment du président Brice Clotaire Oligui Nguema, les membres du nouveau gouvernement gabonais ont prêté serment, marquant le début de l''exécutif de la 5e République. Ce gouvernement de 30 ministres, avec une forte représentation féminine, vise à assurer la stabilité politique et à promouvoir une économie plus diversifiée et transparente.',
        'https://www.gabonews.com/fr/actus/politique/article/prestation-de-serment-des-membres-du-gouvernement-20622',
        'Gabonews',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92529aa2-b11a-4c27-a96f-bd1d59186e6a',
        'Le Ministre de la Réforme et des Relations avec les Institutions appelle les partis politiques à déposer les listes de leurs représentants',
        'Je n''ai pas pu accéder à l''article spécifique de "Gabonews" pour le résumer. Cependant, en fonction des informations disponibles, le Gabon est en train de passer par une phase de réforme importante, avec un nouveau gouvernement et des changements institutionnels, notamment l''investiture de Brice Clotaire Oligui Nguema comme président et la nomination d''un ministre de la Réforme et des relations avec les institutions. Ce gouvernement a pour mission de renforcer la gouvernance efficace et la refondation de l''action de l''État.',
        'https://www.gabonews.com/fr/actus/communique/article/le-ministre-de-la-reforme-et-des-relations-avec',
        'Gabonews',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd626b4fa-6aad-466a-840b-c770e817b175',
        'Prestation de serment &1er Conseil des ministres OLIGUI NGUEMA jette les bases de la 5e République',
        'Le premier Conseil des ministres de la Ve République, présidé par Brice Clotaire Oligui Nguema, a posé les fondements de l''action gouvernementale en fixant des axes directeurs axés sur la célérité, l''éthique et la transparence. Le gouvernement vise à instaurer une ère d''efficacité et de responsabilité, avec des piliers stratégiques tels que l''accès universel à l''eau et à l''électricité et la relance économique.',
        'https://vxp241.com/2025/05/09/prestation-de-serment-1er-conseil-des-ministres-oligui-nguema-jette-les-bases-de-la-5e-republique/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd06e70df-81d0-4844-a452-3d3ef3cf12e4',
        '« Quelles priorités pour le nouveau ministre du Pétrole au Gabon ? »',
        'Le nouveau ministre du Pétrole au Gabon, Sosthène Nguema Nguema, a pour mission principale de renforcer le rôle de l’État dans le secteur pétrolier en structurant le paysage énergétique, relançant l''exploration, et promouvant une gouvernance transparente pour soutenir la diversification économique et le développement durable du pays.',
        'https://directinfosgabon.com/quelles-priorites-pour-le-nouveau-ministre-du-petrole-au-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3656ae2-a482-4241-8307-63828c0bfd1e',
        'Fer de Bélinga:  Déjà 200 milliards de FCFA investis par Ivindo Iron',
        'Le projet de fer de Bélinga, mené par Ivindo Iron, a déjà bénéficié d''un investissement de 200 milliards de francs CFA. Ce projet vise à développer une importante mine de fer au Gabon, contribuant ainsi à la croissance économique du pays.',
        'https://directinfosgabon.com/fer-de-belinga-deja-200-milliards-de-fcfa-investis-par-ivindo-iron/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c120cfe3-b534-49c3-b106-34b9f533df6f',
        'Dette : La situation financière du Gabon est précaire, selon Fitch Rating',
        'La situation financière du Gabon est considérée comme précaire selon Fitch Rating, avec une note de crédit abaissée à « CCC » en raison de tensions de liquidité accrues. Le pays a récemment levé des fonds par un placement privé à un rendement élevé de 12,7 %, soulignant ses difficultés financières.',
        'https://directinfosgabon.com/dette-la-situation-financiere-du-gabon-est-precaire-selon-fitch-rating/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd3325d1e-cf57-4151-bc3c-eae56d0caf0c',
        'Vice-présidence du gouvernement : Barro Chambrier inaugure une fonction stratégique',
        'Alexandre Barro Chambrier, vice-président du gouvernement gabonais, occupe une fonction stratégique qui vise à renforcer la mise en œuvre des politiques gouvernementales. Dans ce rôle, il est chargé de garantir la cohérence des décisions et de coordonner les actions gouvernementales.',
        'https://www.gabonreview.com/vice-presidence-du-gouvernement-barro-chambrier-inaugure-une-fonction-strategique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '942d8bff-bded-4fbb-8b0b-4c08b9042e21',
        'Gabon: le président Oligui Nguema remanie son premier cercle avec une vague de nominations',
        'Le président gabonais, Brice Oligui Nguema, a procédé à un remaniement ministériel en nommant son premier gouvernement civil après la fin de la transition militaire. Ce nouveau gouvernement inclut des figures clés comme Séraphin Moundounga, vice-président de la République, et Alexandre Barro Chambrier, vice-président du gouvernement, avec une composition mettant en avant plusieurs militaires et personnalités de divers horizons.',
        'https://www.rfi.fr/fr/afrique/20250509-gabon-le-pr%C3%A9sident-oligui-nguema-remanie-son-premier-cercle-avec-une-vague-de-nominations',
        'RFI',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58105933-10c5-476a-871b-9410eeebc74c',
        'Gabon: le président Oligui Nguema remanie son premier cercle avec une vague de nominations',
        'Le président gabonais, Brice Oligui Nguema, a nommé son premier gouvernement civil, marquant une nouvelle étape dans la transition politique du pays. Ce gouvernement reflète une volonté de rupture et de changement, avec pour objectif de renforcer la confiance publique et de promouvoir une gouvernance efficace.',
        'https://www.rfi.fr/fr/afrique/20250509-gabon-le-pr%C3%A9sident-oligui-nguema-remanie-son-premier-cercle-avec-une-vague-de-nominations?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f69bec2-9a84-405c-a425-8693e50f4e44',
        'Gabon : Oyima prend officiellement les rênes du super-ministère de l’Économie, des Finances, de la Dette et des Participations',
        'Henri-Claude Oyima a officiellement pris les rênes du super-ministère de l''Économie, des Finances, de la Dette et des Participations au Gabon. Cette nomination soulève des questions quant à la gestion potentielle d''un conflit d''intérêts, Oyima étant également PDG du Groupe BGFIBank.',
        'https://gabonmediatime.com/gabon-oyima-prend-officiellement-les-renes-du-super-ministere-de-leconomie-des-finances-de-la-dette-et-des-participations/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b4dea8f-6100-4680-b1b8-73dd8485037b',
        'Gabon : la présidence de la République réorganisée autour de huit pôles sous la V République',
        'La présidence gabonaise a été réorganisée autour de huit pôles stratégiques sous la Ve République, visant à renforcer l''efficacité de l''action gouvernementale et à instaurer un nouveau pacte entre l''État et la Nation, dans un contexte de rupture et de refondation. Cette réorganisation s''inscrit dans le cadre d''une gouvernance axée sur les résultats, la justice, l''intégrité et la restauration de la confiance publique.',
        'https://gabonmediatime.com/gabon-la-presidence-de-la-republique-reorganisee-autour-de-huit-poles-sous-la-v-republique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae7129b1-e9b0-4f6d-8cb1-b24c9fb8960a',
        'Gabon : l’ingénieur Sosthène Nguema Nguema face aux défis du secteur pétro-gazier',
        'Ingénieur de formation et expert en environnement, Sosthène Nguema Nguema a été nommé ministre du Pétrole et du Gaz au Gabon pour relever les défis liés à la gouvernance, la transparence et la relance du secteur pétrolier, avec pour objectif de mieux exploiter les ressources pétrogazières et soutenir le développement durable du pays. Son parcours mêle compétences techniques, engagement politique et expérience dans l''industrie extractive, le positionnant comme un acteur clé de la nouvelle stratégie énergétique gabonaise. [3][4][5]',
        'https://gabonmediatime.com/gabon-lingenieur-sosthene-nguema-nguema-face-aux-defis-du-secteur-petro-gazier/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '767a4ffc-d9b4-43bb-b25c-63e3641e7113',
        'Porte-parolat de la présidence de la République : À seulement 33 ans, l’excellentissime Théophane Nzame Biyoghe prend la main',
        'Théophane Nzame-Biyoghe, âgé de seulement 33 ans, occupe désormais le poste de porte-parole de la présidence de la République gabonaise, marquant une carrière prometteuse dans le domaine politique. Cette nomination met en avant son engagement dans la vie publique gabonaise, accompagné de rôles dans des mouvements associatifs et politiques importants.',
        'https://kongossanews.info/porte-parolat-de-la-presidence-de-la-republique-a-seulement-33-ans-lexcellentissime-theophane-nzame-biyoghe-prend-la-main/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd85b353d-726d-48d3-b5b9-e169435eabe4',
        'Il était grand temps : Télesphore Obame Ngomo cède sa place à la tête de la communication présidentielle',
        'Télesphore Obame Ngomo a quitté sa position à la tête de la communication présidentielle, après avoir joué un rôle crucial dans la communication de la transition gabonaise depuis sa nomination en septembre 2023. Il a été remplacé à ce poste, marquant une nouvelle étape dans la gestion de l''image et des communications de la présidence gabonaise.',
        'https://kongossanews.info/il-etait-grand-temps-telesphore-obame-ngomo-cede-sa-place-a-la-tete-de-la-communication-presidentielle/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

