-- Batch 6 - Section 17/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'e75c9cde-a4b6-4970-a609-1a461e92d01f',
        'Gabon–Banque mondiale : la SFI veut accompagner la transformation minière et logistique',
        'La SFI, branche de la Banque mondiale, prévoit de soutenir la transformation des secteurs minier et logistique au Gabon pour renforcer le développement économique du pays.',
        'https://gabonmediatime.com/gabon-banque-mondiale-la-sfi-veut-accompagner-la-transformation-miniere-et-logistique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c1fc536-ab96-484d-b8fc-0d8a860dcb50',
        'Potasse : Millennial Potash lève 4,1 milliards de FCFA pour accélérer son projet à Banio',
        'Potasse Millennial Potash a levé 41 milliards de FCFA pour accélérer le développement de son projet minier à Banio, en vue de produire de la potasse destinée à l’exportation.',
        'https://gabonmediatime.com/potasse-millennial-potash-leve-41-milliards-de-fcfa-pour-accelerer-son-projet-a-banio/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ff234f9-b1a0-462a-ada0-dcc642a070ce',
        'Forum Maggi 2025 : 400 femmes à l’école d’une vie épanouie',
        'Une initiative vise à encourager 400 femmes à suivre une formation pour améliorer leur vie et leur autonomie d’ici 2025.',
        'https://gabonmediatime.com/forum-maggi-2025-400-femmes-a-lecole-dune-vie-epanouie/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeab632b-0213-44d2-a6ef-890f94f8ce87',
        'Tournoi de l’Unité 2025 : Sous l’égide de Camélia Ntoutoum Leclercq, Ntoum célèbre le sport, la cohésion et la mémoire de Lubin ...',
        'Un tournoi sportif organisé pour promouvoir l’unité, la cohésion et la mémoire de figures importantes du football, en mettant en avant des valeurs comme le sport et la solidarité.',
        'https://kongossanews.info/tournoi-de-lunite-2025-sous-legide-de-camelia-ntoutoum-leclercq-ntoum-celebre-le-sport-la-cohesion-et-la-memoire-de-lubin-martial-ntoutoume-obame/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3152e51f-3459-45ac-9e52-a0f40dc13285',
        'Partenariat Gabon-Turquie : Brice Clotaire Oligui Nguema visite le chantier naval de GÖLCÜK, KARPOWERSHIP et BAYKAR',
        'Le ministre gabonais Brice Clotaire Oligui Nguema a visité des sites industriels turcs, notamment un chantier naval, un terminal électrique et une entreprise aéronautique, dans le cadre du partenariat entre le Gabon et la Turquie.',
        'https://kongossanews.info/partenariat-gabon-turquie-brice-clotaire-oligui-nguema-visite-le-chantier-naval-de-golcuk-karpowership-et-baykar/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98682429-c19c-4860-8ef2-7fd7e116fae0',
        'Les géants du manganèse au Gabon : CICMHZ et NGM à la pointe de la transformation locale',
        'Plusieurs entreprises gazières et minières de premier plan contribuent à la transformation économique locale au Gabon, notamment avec des projets dans le secteur du manganèse qui renforcent le développement industriel et l''autonomisation de la région.',
        'https://kongossanews.info/les-geants-du-manganese-au-gabon-cicmhz-et-ngm-a-la-pointe-de-la-transformation-locale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ac2c799-15d7-4d45-9856-20f8bb776a96',
        'Gabon : la passerelle de Bizango PK13 désormais posée',
        'La nouvelle passerelle piétonne de Bizango-PK13 a été installée, permettant aux habitants de traverser en toute sécurité au-dessus de la route fréquentée de Ntoum.',
        'https://agpgabon.ga/gabon-la-passerelle-de-bizango-pk13-desormais-posee/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '289d9590-e2cc-4419-9b79-79834151f35b',
        'Gastronomie : le Gabon célèbre sa cuisine du terroir du 5 au 11 août',
        'Une semaine dédiée à la valorisation de la cuisine gabonaise se déroulera du 5 au 11 août à Libreville, avec diverses activités pour promouvoir les produits locaux et l''alimentation durable.',
        'https://agpgabon.ga/gastronomie-le-gabon-celebre-sa-cuisine-du-terroir-du-5-au-11-aout/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33d9e30f-892e-4e75-a711-371736930c03',
        'Gabon/Foire itinérante : le poisson frais à 1000 FCFA du 5 au 11 août',
        'Une foire itinérante organisée du 5 au 11 août 2025 dans plusieurs villes du Gabon propose du poisson frais à 1000 FCFA le kilogramme, pour permettre aux familles d’accéder facilement aux produits de la pêche locale.',
        'https://agpgabon.ga/gabon-foire-itinerante-le-poisson-frais-a-1000-fcfa-du-5-au-11-aout/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '82c0814b-740e-4758-8f08-a59d6eaf2320',
        'Gabon–Banque mondiale : la SFI veut accompagner la transformation minière et logistique',
        'La SFI, filiale de la Banque mondiale, souhaite soutenir la transformation des secteurs minier et logistique au Gabon en finançant des projets visant à améliorer leur développement économique.',
        'https://gabonmediatime.com/gabon-banque-mondiale-la-sfi-veut-accompagner-la-transformation-miniere-et-logistique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5516e382-ae74-4792-a2e4-01fbd835ec98',
        'Potasse : Millennial Potash lève 4,1 milliards de FCFA pour accélérer son projet à Banio',
        'Potasse Millennial Potash a levé 41 milliards de FCFA pour financer l’accélération de son projet minier à Banio, visant à exploiter des ressources en potasse en Guinée équatoriale.',
        'https://gabonmediatime.com/potasse-millennial-potash-leve-41-milliards-de-fcfa-pour-accelerer-son-projet-a-banio/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a35fcb4-8eb9-4a8c-854d-b86641f53d3b',
        'Forum Maggi 2025 : 400 femmes à l’école d’une vie épanouie',
        'Uneinitiative vise à promouvoir l''éducation et l''autonomisation des femmes en Gabon, en formant 400 d''entre elles à des compétences pour une vie épanouie d''ici 2025.',
        'https://gabonmediatime.com/forum-maggi-2025-400-femmes-a-lecole-dune-vie-epanouie/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9296c1f2-8887-48be-a12a-9ff36257b80c',
        'Tournoi de l’Unité 2025 : Sous l’égide de Camélia Ntoutoum Leclercq, Ntoum célèbre le sport, la cohésion et la mémoire de Lubin ...',
        'Un tournoi de l’unité prévu pour 2025 célèbre le sport, la cohésion et la mémoire de figures importantes comme Lubin Martial Ntoutoume Obame, sous la direction de Camélia Ntoutoum Leclercq Ntoum.',
        'https://kongossanews.info/tournoi-de-lunite-2025-sous-legide-de-camelia-ntoutoum-leclercq-ntoum-celebre-le-sport-la-cohesion-et-la-memoire-de-lubin-martial-ntoutoume-obame/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9765f611-7c53-46de-8aad-d9bd10445465',
        'Partenariat Gabon-Turquie : Brice Clotaire Oligui Nguema visite le chantier naval de GÖLCÜK, KARPOWERSHIP et BAYKAR',
        'Le gouvernement gabonais explore des partenariats avec la Turquie pour développer ses infrastructures navales, notamment en visitant des sites industriels comme le chantier naval de Gölcük, la société Karpowership et le constructeur aéronautique Baykar.',
        'https://kongossanews.info/partenariat-gabon-turquie-brice-clotaire-oligui-nguema-visite-le-chantier-naval-de-golcuk-karpowership-et-baykar/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05800dad-2589-4f77-9771-c3699d91c287',
        'Les géants du manganèse au Gabon : CICMHZ et NGM à la pointe de la transformation locale',
        'Les géants du manganèse au Gabon, CICMHZ et NGM, contribuent activement à la transformation locale de l’économie en investissant dans des projets d’exploitation minière et de développement durable.',
        'https://kongossanews.info/les-geants-du-manganese-au-gabon-cicmhz-et-ngm-a-la-pointe-de-la-transformation-locale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '30a020a1-9ef0-4d19-99ad-ade4606960d1',
        'Omnisports/Jeux Africains Scolaires d’Alger : encore du bronze pour le Gabon en taekwondo et en judo',
        'Le Gabon a remporté deux médailles de bronze en taekwondo et en judo lors des Jeux Africains Scolaires à Alger, continuant ainsi ses performances dans ces sports.',
        'https://agpgabon.ga/omnisports-jeux-africains-scolaires-dalger-encore-du-bronze-pour-le-gabon-en-taekwondo-et-en-judo/',
        'AGP',
        'Business Intelligence',
        '2025-08-03T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cd12d4a8-d5a9-4adf-8604-3caae52d8196',
        'Gabon: un activiste exige des millions pour ne pas diffuser des vidéos compromettantes du président',
        'Un jeune Gabonais d''origine libanaise, connu sous le nom de Nazih, a été arrêté au Liban après avoir affirmé posséder des vidéos et audios compromettants sur le président gabonais Brice Clotaire Oligui Nguema, qu''il réclame 6 millions de CFA pour ne pas diffuser.',
        'https://www.rfi.fr/fr/afrique/20250804-gabon-un-activiste-liban-millions-diffusion-vid%C3%A9os-compromettantes-du-pr%C3%A9sident-brice-clotaire-oligui-nguema',
        'RFI',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2dbeef7c-9c63-4788-b715-6c81202715d1',
        'La CNSS met en place un site web pour vérifier le versement des cotisations sociales par les employeurs',
        'La CNSS a annoncé la création d’un site internet permettant aux employeurs de vérifier en ligne le versement des cotisations sociales, facilitant ainsi la transparence et le contrôle pour les employés.',
        'https://directinfosgabon.com/la-cnss-met-en-place-un-site-web-pour-verifier-le-versement-des-cotisations-sociales-par-les-employeurs/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6182351d-8b49-4c1b-8589-feb2e68c18de',
        'Mouila : Réouverture officielle de l’usine de la Sobraga',
        'L’usine de la Société des Boissons Rafraîchissantes du Gabon (Sobraga) à Mouila a été officiellement réouverte en présence de responsables locaux et nationaux, marquant le redémarrage de la production dans la région.',
        'https://directinfosgabon.com/mouila-reouverture-officielle-de-lusine-de-la-sobraga/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2420e174-9641-4a21-8283-45f9428e09bd',
        'Ngounié : La société turque Aksa Energy va construire une centrale électrique à gaz de 1000 MW',
        'Une société turque, Aksa Energy, va construire une centrale électrique à gaz d''une capacité de 1000 MW dans la région de Ngounié.',
        'https://directinfosgabon.com/ngounie-la-societe-turque-aksa-energy-va-construire-une-centrale-electrique-a-gaz-de-1000-mw/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '20bc6b31-0335-4abf-a4b7-20152cf40334',
        'Publié le 04 / 08 / 2025',
        'Les configurations prévues en septembre et octobre pour le CODIV-19 impliquent des changements dans la gestion des écoles et des mesures sanitaires pour limiter la propagation du virus.',
        'https://union.sonapresse.com/fr/pdg-quelle-configuration-en-septembre-et-octobre-prochains',
        'L''union',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '99af789f-9830-4f62-b71a-724b4c0f065d',
        'Investissement : Le patronat gabonais (FEG) et turc (DIEK) créent un Conseil d’affaires bilatéral',
        'Le Gabon et la Turquie ont créé un Conseil d’affaires bilatéral pour renforcer leurs échanges économiques et encourager les investissements entre les deux pays.',
        'https://directinfosgabon.com/investissement-le-patronat-gabonais-feg-et-turc-diek-creent-un-conseil-daffaires-bilateral/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '773bd9b3-6922-4143-bd48-ed0bbefbfd58',
        'La CNSS dresse son bilan 2024 et annonce de grandes innovations pour 2025',
        'La CNSS a présenté un bilan positif pour 2024, en évoquant l''amélioration de la qualité du service aux retraités, la digitalisation, et a annoncé de importantes innovations prévues pour 2025.',
        'https://directinfosgabon.com/la-cnss-dresse-son-bilan-2024-et-annonce-de-grandes-innovations-pour-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd91779e8-7cf7-450f-8d34-c05a66f7a7ad',
        'Santé au travail : briser le tabou de la douleur féminine',
        'L''article souligne que les douleurs féminines liées à l’endométriose et aux troubles hormonaux sont encore peu reconnues dans le monde du travail au Gabon, malgré leur impact sur la vie quotidienne des femmes.',
        'https://www.gabonreview.com/sante-au-travail-briser-le-tabou-de-la-douleur-feminine/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae426ebc-62d4-41cc-a8e9-19d84af9efc3',
        'Publié le 04 / 08 / 2025',
        'Les configurations de gouvernance pour le président-directeur général (PDG) en septembre et octobre montrent une évolution vers plus de clarté et d’efficacité dans la gestion des entreprises.',
        'https://union.sonapresse.com/fr/pdg-quelle-configuration-en-septembre-et-octobre-prochains',
        'L''union',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6c16cf5-60b1-4a3c-8fb2-5649eac030e5',
        'Babicka s’envole pour Belgrade : sur les traces de Kanga Guelord !',
        'Un ancien joueur de Toulouse, Shavy Warren Babicka, rejoint l’Étoile Rouge de Belgrade pour quatre ans, dans le cadre d’un transfert de 4 millions d’euros.',
        'https://gabonactu.com/blog/2025/08/04/babicka-senvole-pour-belgrade-sur-les-traces-de-kanga-guelord/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4733be9-7de5-4042-b71d-e6ad1b7fb6fa',
        'David Mbourou condamné à 30 ans de prison pour inceste aggravé et viol sur ses petites-filles',
        'David Mbourou a été condamné à 30 ans de prison pour avoir commis des actes d’inceste aggravé et viol sur ses petites filles.',
        'https://gabonactu.com/blog/2025/08/04/david-mbourou-condamne-a-30-ans-de-prison-pour-inceste-aggrave-et-viol-sur-ses-petites-filles/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46aa99cf-6a20-40e8-8790-7e120a2c4504',
        'Législatives et locales 2025 : des rudiments pour les observateurs de l’OCP et l’ONELT',
        'Une formation a été organisée pour préparer les observateurs électoraux aux élections législatives et locales de 2025, afin d''assurer la transparence et la crédibilité du scrutin.',
        'https://gabonactu.com/blog/2025/08/04/legislatives-et-locales-2025-des-rudiments-pour-les-observateurs-de-locp-et-lonelt/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd750bf31-3e90-47ab-a89a-4894a0b53352',
        'Ech Gang, triomphe librevillois au Mandji Battle Dance',
        'Ech Gang de Libreville a remporté la 4ᵉ édition du Mandji Battle Dance à Port-Gentil, en battant l''équipe invincible Power Dream lors d''une finale intense.',
        'https://www.gabonreview.com/ech-gang-le-triomphe-librevillois-au-mandji-battle-dance/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9a121d1-5bfd-41c8-ba79-9651eb9000a2',
        'Énergie : le Gabon s’allie à Aksa Energy pour une centrale de 1000 MW dans la Ngounié',
        'Le Gabon a signé un accord avec la société turque Aksa Energy pour construire une centrale à gaz de 1000 MW dans la région de la Ngounié, afin d’améliorer l’approvisionnement en électricité du pays.',
        'https://www.gabonreview.com/energie-le-gabon-sallie-a-aksa-energy-pour-une-centrale-de-1000-mw-dans-la-ngounie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '628f7c42-6381-410d-8d06-951bd90d58f3',
        'Élections jumelées 2025 : Hermann Immongault va-t-il écarter le PDG ?',
        'À deux jours de la fin du dépôt des candidatures pour les élections législatives et locales, la division au sein du Parti démocratique gabonais (PDG) pourrait conduire le ministre de l’Intérieur à utiliser la loi sur les partis politiques pour exclure l’ancien parti au pouvoir.',
        'https://www.gabonreview.com/elections-jumelees-2025-hermann-immongault-va-t-il-ecarter-le-pdg/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55ff24db-c228-42cb-b6fd-a37d28281f3e',
        'Airtel Africa signe un partenariat stratégique pluriannuel avec Xtelify, la branche digitale d’Airtel India',
        'Xtelify, filiale entièrement détenue par Airtel, a lancé une plateforme logicielle innovante alimentée par l’intelligence artificielle pour accélérer la transformation numérique d’Airtel Africa.',
        'https://vxp241.com/2025/08/04/airtel-africa-signe-un-partenariat-strategique-pluriannuel-avec-xtelify-la-branche-digitale-dairtel-india/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86a598d2-bd4c-45e1-92c7-649b233e2168',
        'Législatives 2025 à Mimongo :  le journaliste Pacôme Idyatha investi candidat de l’UDB',
        'Un journaliste et militant de l’Union démocratique des bâtisseurs (UDB), Pacôme Idyatha Nguimbi, a été choisi comme candidat du parti pour les élections législatives de 2025 dans la circonscription de Mimongo.',
        'https://gabonactu.com/blog/2025/08/04/legislatives-2025-a-mimongo-le-journaliste-pacome-idyatha-investi-candidat-de-ludb/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '757c0f4c-0968-4098-8d73-2d8254cfa7b9',
        'JET Football 2025 : des recruteurs européens à Libreville pour dénicher les pépites gabonaises',
        'Neuf recruteurs de clubs européens prestigieux sont venus à Libreville pour découvrir de jeunes talents gabonais lors d''une grande session de détection organisée dans le cadre du programme JET Football 2025.',
        'https://gabonactu.com/blog/2025/08/04/jet-football-2025-des-recruteurs-europeens-a-libreville-pour-denicher-les-pepites-gabonaises/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0529352e-f1c2-4f50-8472-10928c8811d7',
        'Gabon/Littérature : Sharon Onkoni lance son premier café littéraire',
        'Sharon Onkoni a ouvert un café littéraire appelé « Philomène Onkoni » à Libreville en hommage à sa mère décédée, marquant son retour après une pause sur les réseaux sociaux.',
        'https://agpgabon.ga/gabon-litterature-sharon-onkoni-lance-son-premier-cafe-litteraire/',
        'AGP',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8779dfd4-217a-4f01-9d21-67b85e04696d',
        'Football/Tournoi Jet : la sélection communale d’Akanda et Atletico Akanda vainqueurs',
        'Les équipes d''Akanda, côté masculin et féminin, ont remporté la première édition du tournoi Jet de football, la victoire féminine étant largement acquise face à AFCO d’Owendo.',
        'https://agpgabon.ga/football-tournoi-jet-la-selection-communale-dakanda-et-atletico-akanda-vainqueurs/',
        'AGP',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d23b382-59d6-49cb-8a02-1cf18d5ad9e6',
        'Henri Paul Nanh Bioghe invite les populations du 1ᵉʳ siège du 2ᵉ arrondissement à se faire enrôler',
        'Henri Paul Nanh a encouragé les habitants du quartier Atong-Abe à s’inscrire sur les listes électorales et à se rendre dans les bureaux de vote les plus proches, afin de mieux préparer les prochaines élections législatives et locales du 27 septembre.',
        'https://www.gabonews.com/fr/actus/politique/article/henri-paul-nanh-bioghe-invite-les-populations-du',
        'Gabonews',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a99abd30-6a0d-4321-8827-c524de2c2af5',
        'Santé communautaire au Gabon : un partenariat novateur se met en place',
        'Le Gabon a lancé une formation pour environ 100 personnes afin qu’elles puissent donner les premiers secours, avec l’aide d’une ONG belge, pour mieux préparer les communautés face aux urgences de santé.',
        'https://www.gabonews.com/fr/actus/cooperation/article/sante-communautaire-au-gabon-un-partenariat',
        'Gabonews',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1d3c558-1f2e-451c-8a46-2626ccb4eba2',
        'Edgard Moukoumbi et Gilles Nembe en visite de terrain à Bakoumba',
        'Le Ministre des Travaux Publics et de la Construction, Edgard Moukoumbi, et le Ministre des Mines, Gilles Nembe, ont visité les travaux routiers reliant Moanda à Bakoumba et Bakoumba à Lékoko, deux axes stratégiques de près de 95 km entre le Gabon et le Congo, afin d’évaluer l’avancement des projets.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/edgard-moukoumbi-et-gilles-nembe-en-visite-de',
        'Gabonews',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a879aea8-291a-4254-93ff-bd1342b2532f',
        'Gabon/Mines : le Gabon et AML Holdings envisagent une usine de transformation de manganèse',
        'Le Gabon et la société japonaise AML Holdings envisagent de construire une usine de transformation de manganèse afin de valoriser localement cette ressource, conformément à la stratégie nationale qui interdit l''exportation de manganèse brut d''ici 2029.',
        'https://agpgabon.ga/gabon-mines-le-gabon-et-aml-holdings-envisagent-une-usine-de-transformation-de-manganese/',
        'AGP',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '968374fb-8cbc-49e1-9803-16fb4a29398b',
        'Moyen-Ogooué/Faits divers : un jeune cycliste fauché mortellement par un taxi à Lambaréné',
        'Un jeune homme qui faisait du vélo a été renversé mortellement par un taxi sur la route à Lambaréné, dans la soirée de dimanche à lundi.',
        'https://agpgabon.ga/moyen-ogooue-faits-divers-un-jeune-cycliste-fauche-mortellement-par-un-taxi-a-lambarene/',
        'AGP',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12141932-91e4-46c2-bff6-77dd98447a4b',
        'Gabon/Numérique : Un data center 100 % africain bientôt opérationnel à Nkok',
        'Un nouveau centre de données écologique, 100 % africain, sera bientôt opérationnel à Nkok, offrant des services cloud locaux pour renforcer la souveraineté numérique du Gabon.',
        'https://agpgabon.ga/gabon-numerique-un-data-center-100-africain-bientot-operationnel-a-nkok/',
        'AGP',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '00a84fbf-0b61-42c8-b272-0810f0db6061',
        'Mathieu Mboumba Nziengui n’est plus',
        'Mathieu Mboumba Nziengui, président de l’Union du peuple gabonais (UPG), est décédé le 4 août 2025.',
        'https://gabonactu.com/blog/2025/08/04/mathieu-mboumba-nziengui-nest-plus/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '172859c8-8802-4cf1-af03-e78aee328571',
        'Démantèlement d’un réseau de faux papiers : Droit de réponse de la DGDI',
        'La DGD (Direction Générale de la Documentation) a démantelé un réseau de faussaires impliqué dans la falsification de documents administratifs.',
        'https://gabonmediatime.com/demantelement-dun-reseau-de-faux-papiers-droit-de-reponse-de-la-dgdi/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '19c33dc4-b411-420a-9d3a-71991c8d7bdb',
        'Législatives et locales 2025 : le PDG, guerre des égaux et risque de disqualification',
        'Les enjeux des élections législatives et locales de 2025 au Gabon risquent d''être compliqués en raison de tensions internes dans le Parti démocratique gabonais (PDG) et de risques de disqualification de certains candidats.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-le-pdg-guerre-des-egaux-et-risque-de-disqualification/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff3ad6f7-a788-44b0-9ba7-7340bb7fe2bc',
        'Gabon : le gouvernement et AML Holdings unis pour la transformation locale du manganèse',
        'Le gouvernement gabonais et AML Holdings collaborent pour transformer localement le manganèse, afin de développer l’industrie minière et créer des opportunités économiques dans le pays.',
        'https://gabonmediatime.com/gabon-le-gouvernement-et-aml-holdings-unis-pour-la-transformation-locale-du-manganese/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a197c70-dcbb-4b34-bd7a-4492d4b37d8b',
        'Akanda : Dépossédée de sa parcelle, l’Église La Chapelle des Vainqueurs en appelle à l’arbitrage du Président de la République',
        'Une église située à la Chapelle des Vainqueurs a été dépossédée de sa parcelle, et l’église demande l’arbitrage du président de la République pour régler le litige.',
        'https://kongossanews.info/akanda-depossedee-de-sa-parcelle-leglise-la-chapelle-des-vainqueurs-en-appelle-a-larbitrage-du-president-de-la-republique/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e1659b2-db55-49fe-bd2b-ad2ff21e02b8',
        'Le Gabon mise sur un partenariat innovant pour renforcer la santé communautaire',
        'Le Gabon mise sur un partenariat innovant pour renforcer les services de santé communautaire et améliorer l''accès aux soins pour tous.',
        'https://kongossanews.info/le-gabon-mise-sur-un-partenariat-innovant-pour-renforcer-la-sante-communautaire/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51a961fe-1b49-4bc1-8223-d6dc433d8eba',
        'Démantèlement d’un réseau de faux papiers : Droit de réponse de la DGDI',
        'Une opération policière a permis de démanteler un réseau de fabrication et de vente de faux papiers en République gabonaise.',
        'https://gabonmediatime.com/demantelement-dun-reseau-de-faux-papiers-droit-de-reponse-de-la-dgdi/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9862928c-2cbd-44b8-bd46-ed17517f975e',
        'Législatives et locales 2025 : le PDG, guerre des égaux et risque de disqualification',
        'Le parti au pouvoir au Gabon, le PDG, se livre à une course pour préparer les élections législatives et locales de 2025, tout en étant confronté à des risques de disqualification et à des tensions internes.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-le-pdg-guerre-des-egaux-et-risque-de-disqualification/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

