-- Batch 6 - Section 18/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '6a203d4e-f883-4825-8d9e-014498780ac9',
        'Gabon : le gouvernement et AML Holdings unis pour la transformation locale du manganèse',
        'Le gouvernement gabonais et la société AML Holdings collaborent pour développer localement la transformation du manganèse afin de valoriser cette ressource minérale dans le pays.',
        'https://gabonmediatime.com/gabon-le-gouvernement-et-aml-holdings-unis-pour-la-transformation-locale-du-manganese/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88e0a63c-bade-4178-a80f-bf92779af7a6',
        'Akanda : Dépossédée de sa parcelle, l’Église La Chapelle des Vainqueurs en appelle à l’arbitrage du Président de la République',
        'Une église protestante, la Chapelle des Vainqueurs, a été dépossédée de sa parcelle par la justice, mais elle demande l’arbitrage du président de la République pour résoudre le différend.',
        'https://kongossanews.info/akanda-depossedee-de-sa-parcelle-leglise-la-chapelle-des-vainqueurs-en-appelle-a-larbitrage-du-president-de-la-republique/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9c7c638-6056-4873-b850-2a36f47dfdbe',
        'Le Gabon mise sur un partenariat innovant pour renforcer la santé communautaire',
        'Le Gabon mise sur un partenariat innovant pour renforcer la santé communautaire en utilisant des technologies et des stratégies nouvelles afin d''améliorer l''accès aux soins et la prévention.',
        'https://kongossanews.info/le-gabon-mise-sur-un-partenariat-innovant-pour-renforcer-la-sante-communautaire/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd30e9ccc-11ac-497e-b5f1-95ab856ec4e1',
        'Déficit énergétique: le Gabon s’offre 31 groupes électrogènes supplémentaires',
        'Le gouvernement gabonais a récemment acquis 31 groupes électrogènes neufs pour renforcer la production d''énergie, qui seront déployés dans 18 localités afin de pallier le déficit énergétique dans le pays.',
        'https://vxp241.com/2025/08/04/deficit-energetique-le-gabon-soffre-31-groupes-electrogenes-supplementaires/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-04T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '20449982-e7e3-4614-bf5a-e2d0f6cfce68',
        'Brice Laccruche Alihanga donne la raison de sa descente aux enfers orchestrée par Noureddin Bongo',
        'Brice Laccruche Alihanga affirme que sa chute et son emprisonnement de plus de quatre ans ont été orchestrés par Noureddin Bongo pour des raisons politiques.',
        'https://gabonactu.com/blog/2025/08/04/brice-laccruche-alihanga-donne-la-raison-de-sa-descente-aux-enfers-orchestree-par-noureddin-bongo/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '321fbfda-0ba7-4408-94d1-aa9fc443cad7',
        'Gabon : les objectifs de Brice Laccruche Alihanga',
        'Brice Laccruche Alihanga, ancien proche du président gabonais Ali Bongo, a connu la prison et des problèmes de santé avant de revenir en soutien au président.',
        'https://information.tv5monde.com/afrique/video/gabon-les-objectifs-de-brice-laccruche-alihanga-2787695?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89d4698b-ab70-42c8-ad8f-603941f28dd1',
        'Transfomartion du manganèse : Le Japon passe à l’offensive !',
        'Le Japon prévoit d''ouvrir une usine de transformation de manganèse en partenariat avec une entreprise gabonaise, renforçant ainsi sa présence dans le secteur minier africain.',
        'https://directinfosgabon.com/transfomartion-du-manganese-le-japon-passe-a-loffensive/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7d4e0ab-a7fe-4de5-a4ad-a17f7672973b',
        'CNSS : Les pensions du 3ᵉ trimestre 2025 versées dès ce 5 août 2025',
        'La CNSS du Gabon commence à verser les pensions du troisième trimestre 2025 à partir du 5 août sur tout le territoire, en insistant notamment sur la perception obligatoire pour celles supérieures ou égales à 100 000 FCFA.',
        'https://directinfosgabon.com/cnss-les-pensions-du-3%e1%b5%89-trimestre-2025-versees-des-ce-5-aout-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b25b7a06-50f1-4599-aedd-d9a830f27486',
        'Orabank Gabon : Un bénéfice net de 3 milliards de FCFA au 1er semestre 2025',
        'Orabank Gabon a réalisé un bénéfice net de 3 milliards de FCFA au premier semestre 2025, avec une croissance notable de ses actifs financiers.',
        'https://directinfosgabon.com/orabank-gabon-un-benefice-net-de-3-milliards-de-fcfa-au-1er-semestre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c75bbfc7-0d3a-4122-b627-397d86d9abd6',
        'PFP : vers un partenariat renforcé entre le Gabon, The Nature Conservancy et la Rezos Earth Fund',
        'Le Gabon a renforcé sa coopération avec la Bezos Earth Fund et The Nature Conservancy pour financer des projets environnementaux dans le cadre du Programme de Financement pour la Permanence (PFP).',
        'https://www.gabonews.com/fr/actus/environnement/article/pfp-vers-un-partenariat-renforce-entre-le-gabon',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '579821bc-4eb9-4bb8-9ca7-bcfad8f224bd',
        'Célébration de la Journée Panafricaine des Droits de la Femme : Une mobilisation gouvernementale exemplaire au Gabon',
        'Le Gabon a célébré la Journée Panafricaine des Droits de la Femme, en mettant en avant les progrès pour les droits des femmes et en renforçant les actions en faveur de l’égalité, de l’inclusion et de la justice sociale.',
        'https://www.gabonews.com/fr/actus/societe/article/celebration-de-la-journee-panafricaine-des-droits',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b9b5716-c141-4bc7-aaac-c21336c9b97a',
        'Publié le 05 / 08 / 2025',
        'Plusieurs membres du gouvernement ivoirien ont été élus dans différentes arènes, ce qui pourrait renforcer leur légitimité et leur influence dans le pays.',
        'https://union.sonapresse.com/fr/elections-couplees-udb-des-membres-du-gouvernement-dans-larene',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a5c3af3-552a-4685-a5f5-c27ebff092cb',
        'Publié le 05 / 08 / 2025',
        'L’article explique que la combinaison de la volonté citoyenne et des outils numériques facilite la participation aux élections, tout en soulignant les enjeux liés à leur utilisation en Afrique.',
        'https://union.sonapresse.com/fr/elections-couplees-le-mix-de-ludb',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffe2be79-46e3-4605-9d84-9330a3af2a95',
        'Publié le 04 / 08 / 2025',
        'Les candidats ont jusqu’au 28 septembre pour déposer leurs dossiers de candidature aux élections législatives et locales, dernière étape pour participer à ces scrutins au Sénégal.',
        'https://union.sonapresse.com/fr/legislatives-et-locales-derniere-ligne-droite-pour-le-depot-des-candidatures',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ada16a1-cb7a-4b40-a3be-3d61df11dea2',
        'UDB : La liste complète des investitures pour les législatives et les locales 2025',
        'L''article présente la liste complète des candidats et des investitures pour les élections législatives et locales de 2025 au Gabon, notamment ceux du parti UDB.',
        'https://directinfosgabon.com/udb-la-liste-complete-des-investitures-pour-les-legislatives-et-les-locales-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0444612-07b3-4aee-a78a-26a8b5d29742',
        '« BEAC NG2020 » : L’application mobile pour détecter les faux billets de CFA',
        'La BEAC a lancé une application mobile appelée « BEAC NG2020 » pour aider à identifier les faux billets de banque en circulation dans la zone CFA.',
        'https://gabonactu.com/blog/2025/08/05/franc-cfa-lapplication-mobile-de-la-beac-pour-detecter-les-faux-billets/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2167b3a7-8ff5-4e3d-90f3-6a6e19b9a62a',
        'Interpellation de trois individus avec quatre pointes d''ivoires et deux armes de chasse à Kango',
        'Trois personnes ont été arrêtées à Kango avec des ivoirs, des armes et des munitions, lors d''une opération conjointe entre les forces de l’ordre et une ONG contre le braconnage.',
        'https://www.gabonews.com/fr/actus/societe/article/interpellation-de-trois-individus-avec-quatre',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd2fdd4b-1815-4cbe-9261-11696a8db3a9',
        'Publié le 05 / 08 / 2025',
        'Plusieurs membres du gouvernement ont été élus dans la même circonscription lors des dernières élections, ce qui soulève des questions sur la composition du gouvernement et la représentation politique.',
        'https://union.sonapresse.com/fr/elections-couplees-udb-des-membres-du-gouvernement-dans-larene',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76a5907f-3ef9-483f-ab6d-d4c85e6cc74b',
        'Publié le 05 / 08 / 2025',
        'L''article explique le compromis entre l''utilisation des technologies numériques pour améliorer la participation électorale et les risques liés à leur vulnérabilité face aux attaques et à la manipulation.',
        'https://union.sonapresse.com/fr/elections-couplees-le-mix-de-ludb',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b349fac8-a954-4803-b5e8-be028e99408a',
        'Publié le 04 / 08 / 2025',
        'La date limite de dépôt des candidatures pour les élections législatives et locales approche, obligeant les candidats à finaliser leurs dossiers avant la fin du délai fixé.',
        'https://union.sonapresse.com/fr/legislatives-et-locales-derniere-ligne-droite-pour-le-depot-des-candidatures',
        'L''union',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.487Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd86f487-56a3-4f3a-bab7-eefefdacd944',
        'Transformation locale du manganèse: la société japonaise AML Holdings planifit la construction d’une usine de transformation au Gabon',
        'Le gouvernement gabonais, sous la direction du président Brice Clotaire OLIGUI NGUEMA, a lancé un projet de transformation locale du manganèse, notamment à travers l''ouverture d''une usine au Gabon en partenariat avec la société japonaise AML.',
        'https://vxp241.com/2025/08/05/transformation-locale-du-manganese-la-societe-japonaise-aml-holdings-planifit-la-construction-dune-usine-de-transformation-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b75170dd-a1c1-447a-ab01-a54ff045e656',
        'Transformation locale du manganèse : Le Japon précise son offre',
        'Le Japon a précisé son offre pour transformer localement le manganèse au Gabon, lors d’un échange entre le vice-président gabonais et l’ambassadeur japonais, visant à renforcer la coopération dans ce secteur.',
        'https://gabonactu.com/blog/2025/08/05/transformation-locale-du-manganese-le-japon-precise-son-offre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ac78f305-3a49-4885-ac0f-c3b968b1c1ff',
        'Rouverture de l''usine Sobraga Mouila',
        'L''usine Sobraga de Mouila a rouvert ses portes en août 2025 après avoir été fermée en novembre 2023 suite à un sinistre, ce qui contribue à relancer l''emploi dans la région.',
        'https://www.gabonews.com/fr/actus/economie/article/rouverture-de-l-usine-sobraga-mouila',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fbd741b-0df2-491b-afb1-ba177829b4cc',
        'Denise Époté au cabinet de la Première Dame Zita Oligui Nguema',
        'Madame Denise Époté, journaliste et directrice de TV5MONDE, a échangé avec la Première Dame Zita Oligui Nguema sur l''importance des médias pour valoriser les initiatives sociales, promouvoir le leadership féminin et partager les récits africains pour favoriser le changement.',
        'https://www.gabonews.com/fr/actus/societe/article/denise-epote-au-cabinet-de-la-premiere-dame-zita',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d99f6d3-49d8-409f-98c0-92ef6dcf69bd',
        'Interpellation de trois individus avec quatre pointes d''ivoires et deux armes de chasse à Kango',
        'Trois personnes ont été arrêtées à Kango avec des ivoires et des armes lors d''une opération conjointe entre la Direction de la Lutte Contre le Braconnage, la Police judiciaire et une ONG.',
        'https://www.gabonews.com/fr/actus/societe/article/interpellation-de-trois-individus-avec-quatre',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dfb47f24-ace4-4ef9-9a88-c8e56b195591',
        'Gabon/Faune : trois individus interpellés pour trafic d’ivoire à Kango',
        'Trois personnes ont été arrêtées à Kango, Oyane et Siat Gabon pour leur implication supposée dans un réseau de trafic d''ivoire, lors d''une opération conjointe qui a permis de saisir des pièces d''ivoire, des armes et des munitions.',
        'https://agpgabon.ga/gabon-faune-trois-individus-interpelles-pour-trafic-divoire-a-kango/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7800efa-de8d-44cb-b7cb-35c1a59a94e2',
        'Fonds Bezos pour la Terre : Le Gabon réclame plus de financements à la hauteur de ses résultats',
        'Le Gabon demande plus de financements pour mieux valoriser et protéger ses résultats en matière de conservation grâce au Fonds Bezos pour la Terre, qui soutient des initiatives environnementales dans la région du Bassin du Congo.',
        'https://directinfosgabon.com/fonds-bezos-pour-la-terre-le-gabon-reclame-plus-de-financements-a-la-hauteur-de-ses-resultats/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1d84880-4502-45de-8b31-84bfcf315e01',
        'Coupures et délestages : 18 localités de l’hinterland bientôt équipées de groupes électrogènes',
        '18 localités de l’intérieur du pays recevront bientôt des groupes électrogènes pour améliorer leur fourniture d’électricité.',
        'https://gabonactu.com/blog/2025/08/05/coupures-et-delestages-18-localites-de-lhinterland-bientot-equipees-de-groupes-electrogenes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c799773-314d-4d86-9738-cf395de47584',
        'La Turquie va doper les secteurs de l’énergie et des affaires au Gabon',
        'Lors de sa visite en Turquie, le président gabonais a participé à un forum pour renforcer la coopération dans les secteurs de l’énergie et des affaires entre les deux pays.',
        'https://gabonactu.com/blog/2025/08/05/la-turquie-va-doper-les-secteurs-de-lenergie-et-des-affaires-au-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ada8bb42-03a3-4b78-9326-d1cb9b8b9f86',
        'Football : décès de Jorge Costa, ancien sélectionneur du Gabon',
        'Jorge Costa, ancien défenseur et entraîneur du Gabon, est décédé à l''âge de 53 ans à la suite d''un arrêt cardiaque à l''entraînement du FC Porto, où il occupait un poste de dirigeant.',
        'https://agpgabon.ga/football-deces-de-jorge-costa-ancien-selectionneur-du-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a84e9665-25c7-49fe-933d-9ba978670309',
        'Gabon : « Ce n’était pas une arrestation judiciaire », dixit Brice Laccruche Alihanga',
        'Brice Laccruche Alihanga affirme que son incarcération en 2019 n’était pas une arrestation judiciaire, mais liée à son refus de soutenir la candidature de Noureddin Bongo comme successeur de son père, le président déchu.',
        'https://agpgabon.ga/gabon-ce-netait-pas-une-arrestation-judiciaire-dixit-brice-laccruche-alihanga/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf18f21c-d079-4413-a70e-7db8c48da577',
        'Gabon/Cameroun : signature d’un accord de coordination des fréquences aux frontières',
        'Le Gabon et le Cameroun ont signé un accord pour coordonner l’utilisation des fréquences radio près de leurs frontières, afin de réduire les interférences et renforcer leur coopération technique.',
        'https://agpgabon.ga/gabon-cameroun-signature-dun-accord-de-coordination-des-frequences-aux-frontieres/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '59ed1abc-9195-42ca-b73c-f580a1deb2df',
        'Foot: Jorge Costa, légende du FC Porto est décédé',
        'Jorge Costa, ancien footballeur et légende du FC Porto, est décédé à 53 ans d''une crise cardiaque dans le centre d''entraînement où il travaillait comme dirigeant depuis 2024.',
        'https://www.rfi.fr/fr/sports/20250805-foot-jorge-costa-l%C3%A9gende-du-fc-porto-est-d%C3%A9c%C3%A9d%C3%A9',
        'RFI',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '60458666-9aee-4a5c-8146-ad227a84ecc2',
        'CPPF : Orthodoxie et autonomie financière',
        'Le Conseil d’administration de la CPPF a tenu sa première réunion de l’année, soulignant la nécessité de maintenir une gestion financière rigoureuse, orthodoxe et autonome pour assurer la stabilité du régime de pensions et prestations familiales des agents publics.',
        'https://gabonactu.com/blog/2025/08/05/cppf-orthodoxie-et-autonomie-financiere/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fd195cc-cad2-4e99-94b0-c017b2d5ee67',
        'Cour criminelle de Port-Gentil : Boris Gastien Koumba condamné à 18 ans de prison pour viol',
        'Boris Gastien Koumba a été condamné à 18 ans de prison par la cour criminelle de Port-Gentil pour un crime de viol, après avoir été placé en détention provisoire depuis février 2022.',
        'https://gabonactu.com/blog/2025/08/05/cour-criminelle-de-port-gentil-boris-gastien-koumba-condamne-a-18-ans-de-prison-pour-viol/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2e13dee-b43c-45a5-9f41-6ef684b30789',
        'Gabon : réflexion sur la réforme institutionnelle pour implémenter la Ve République',
        'Le gouvernement gabonais a lancé une réflexion sur la réforme institutionnelle nécessaire pour mettre en œuvre la Ve République, afin d’adapter le fonctionnement des institutions aux enjeux du pays.',
        'https://gabonactu.com/blog/2025/08/05/gabon-reflexion-sur-la-reforme-institutionnelle-pour-implementer-la-ve-republique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eff545d6-b4ea-4149-8f10-3513d395d545',
        'Gabon/Menace de choléra  dans la sous région : le ministre de la Santé tire la sonnette d’alarme',
        'Le ministre de la Santé du Gabon a annoncé des mesures pour renforcer la surveillance et la prévention contre une éventuelle invasion de choléra, face à la recrudescence de cas dans les pays voisins.',
        'https://agpgabon.ga/gabon-menace-de-cholera-dans-la-sous-region-le-ministre-de-la-sante-tire-la-sonnette-dalarme/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb7c95b8-8379-4f5c-b047-724bb4ffb1e0',
        'Gabon : le Gouvernement renforce son partenariat environnemental avec le Fonds Bezos pour la Terre et The Nature Conservancy',
        'Le gouvernement gabonais renforce sa collaboration avec le Fonds Bezos pour la Terre et The Nature Conservancy afin de soutenir la conservation de la biodiversité dans la région du Bassin du Congo, notamment dans le cadre de l’initiative mondiale « 30×30 ».',
        'https://agpgabon.ga/gabon-le-gouvernement-renforce-son-partenariat-environnemental-avec-le-fonds-bezos-pour-la-terre-et-the-nature-conservancy/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aa5b5d46-52a7-4a74-b4a1-429c1d41d9fd',
        'Gabon : deux jours pour débattre sur la réforme de la construction de la V ème République',
        'Un séminaire national de deux jours à Libreville réunit des acteurs pour discuter des réformes structurelles, du fonctionnement de l’État et du renouveau institutionnel de la Ve République au Gabon.',
        'https://agpgabon.ga/gabon-deux-jours-pour-debattre-sur-la-reforme-de-la-construction-de-la-v-eme-republique/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7e73f2f3-b180-49d8-b31a-3c050eb2cd23',
        'Ngounie/Foire aux poissons : 15 tonnes mises à disposition pour les populations de Mouila',
        'Le ministère de la Mer, de la Pêche et de l’Économie Bleue a organisé une foire itinérante à Mouila pour rendre 15 tonnes de poissons accessibles aux habitants à des prix abordables.',
        'https://agpgabon.ga/ngounie-mise-a-disposition-de-15-tonnes-de-poissons-pour-la-foire-itinerante-de-mouila/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cadf6c59-435b-4f4c-b14e-fd4ca0f79934',
        'Le Vice-Président, le Ministre du Tourisme et la Ministre de l''Entrepreneuriat, du Commerce, PME/PMI en visite à Mayumba pour un projet de lodge',
        'Une délégation officielle, menée par le Vice-Président, a visité Mayumba pour suivre l’avancement de la construction d’un lodge touristique dans le cadre des projets engagés par le gouvernement.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-vice-president-le-ministre-du-tourisme-et-la',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44705271-69ac-4c99-bd25-cc9679fced79',
        'Mayumba : Nginga Chaning Zénaba investie candidate de l''UDB aux élections législatives',
        'Nginga Chaning Zénaba, ancienne candidate à la présidentielle, a été désignée comme candidate de l''Union pour la Démocratie et le Bien-être (UDB) pour les élections législatives dans la commune de Mayumba.',
        'https://www.gabonews.com/fr/actus/politique/article/mayumba-nginga-chaning-zenaba-investie-candidate',
        'Gabonews',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75c9de4c-c849-4b55-b508-845bd029e4ae',
        'Nécrologie : décès de Jorge Costa, ancien sélectionneur du Gabon !',
        'Jorge Costa, ancien sélectionneur de l''équipe nationale de football du Gabon, est décédé, suscitant une vague de tristesse dans le monde sportif gabonais.',
        'https://gabonmediatime.com/necrologie-deces-de-jorge-costa-ancien-selectionneur-du-gabon/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47e15165-733e-4c52-8464-e159c2d983eb',
        'Législatives 2025 : les candidats de la Nyanga reçoivent leurs récépissés de déclaration de biens',
        'Les candidats de la circonscription de la Nyanga ont reçu leurs reçus de déclaration de biens en prévision des élections législatives de 2025.',
        'https://gabonmediatime.com/legislatives-2025-les-candidats-de-la-nyanga-recoivent-leurs-recepisses-de-declaration-de-biens/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46c4cfb7-7ccf-4e9e-974f-9f0567af8a76',
        'Nécrologie : Décès de Mathieu Mboumba Nziengui, disparition d’un pilier de l’UPG',
        'Mathieu Mboumba Nziengui, un pilier de l’UPG, est décédé, laissant derrière lui un grand vide dans le domaine de l’éducation au Gabon.',
        'https://gabonmediatime.com/necrologie-deces-de-mathieu-mboumba-nziengui-disparition-dun-pilier-de-lupg/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e30f66bf-965d-41a2-8211-2cab4b9af6dd',
        'Élections législatives 2025 : Les candidats de la Nyanga reçoivent leurs récépissés de déclaration de biens à Tchibanga',
        'Les candidats à la législative de la Nyanga ont reçu leurs reçus de déclaration de biens lors d''une cérémonie à Tchibanga, marquant une étape importante dans leur processus d''élection.',
        'https://kongossanews.info/elections-legislatives-2025-les-candidats-de-la-nyanga-recoivent-leurs-recepisses-de-declaration-de-biens-a-tchibanga-2/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28ee7012-ae61-4545-880f-17c381c1e65d',
        'Élections législatives 2025 : Les candidats de la Nyanga reçoivent leurs récépissés de déclaration de biens à Tchibanga',
        'Les candidats aux prochaines législatives de la Nyanga ont reçu leurs reçisses de déclaration de biens à Tchibanga, marquant une étape dans le processus de transparence électorale.',
        'https://kongossanews.info/elections-legislatives-2025-les-candidats-de-la-nyanga-recoivent-leurs-recepisses-de-declaration-de-biens-a-tchibanga/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'daff97dd-8824-40fd-bea5-1d20786bd768',
        'Coupe Jean François Lingoumbi : Lastoursville vibre au rythme du football communautaire',
        'Une compétition de football communautaire s''est déroulée à Lastoursville, rythmée par l''enthousiasme des participants et des supporters locaux.',
        'https://kongossanews.info/coupe-jean-francois-lingoumbi-lastoursville-vibre-au-rythme-du-football-communautaire/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48536965-ab9d-4ab1-a7e6-7010ab602025',
        'Football/CHAN : le Sénégal bat le Nigeria (1-0)',
        'Le Sénégal a battu le Nigeria 1-0 lors d’un match de la phase de groupes, grâce à un but de Christian Gomis à la 75e minute.',
        'https://agpgabon.ga/football-chan-le-senegal-bat-le-nigeria-1-0/',
        'AGP',
        'Business Intelligence',
        '2025-08-05T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '60d96a87-6eb3-4bfe-982c-486c0ac0055f',
        'Nécrologie : décès de Jorge Costa, ancien sélectionneur du Gabon !',
        'Jorge Costa, ancien sélectionneur de l''équipe nationale du Gabon, est décédé, laissant derrière lui un héritage dans le football gabonais.',
        'https://gabonmediatime.com/necrologie-deces-de-jorge-costa-ancien-selectionneur-du-gabon/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-06T00:00:00.000Z',
        '2025-09-15T23:06:12.488Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

