-- Batch 5 - Section 17/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'f4d816e7-87da-4377-b467-dbc3de30a5cd',
        'Publié le 10 / 07 / 2025',
        'Des investisseurs américains sont attirés par le Gabon, qui mise sur ses ressources naturelles et un environnement favorable pour attirer davantage de capitaux étrangers dans ses projets économiques.',
        'https://union.sonapresse.com/fr/des-investisseurs-americains-seduits-par-le-gabon',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2082da5a-0373-4d1a-b1e7-ea231ed891cf',
        'Publié le 10 / 07 / 2025',
        'Un accord de 300 milliards de FCFA a été signé pour exploiter la potasse de Mayumba, une ressource stratégique pour le développement économique.',
        'https://union.sonapresse.com/fr/exploitation-de-la-potasse-de-mayumba-signature-dun-accord-de-300-milliards-de-fcfa',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04a19f02-6646-4de9-8840-e7339ca61755',
        'Potasse de Mayumba : la société américaine Millennial Potash met sur la table 500 millions de dollars',
        'Une société américaine, Millennial Potash, a proposé une importante somme de 500 millions de dollars pour développer la potasse à Mayumba, au Gabon, dans le but d''exploiter cette ressource et de favoriser l''économie locale.',
        'https://mediapostegabon.com/potasse-de-mayumba-la-societe-americaine-millennial-potash-met-sur-la-table-500-millions-de-dollars/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae31174e-1bf3-42fd-b1c5-abd765582783',
        'SEEG : 8500 compteurs électriques en stock à Jeta Engineering',
        'Une entreprise gabonaise, Jeta Engineering, dispose actuellement de 8 500 compteurs électriques en stock, ce qui permet de préparer leur déploiement pour améliorer l’accès à l’électricité dans le pays.',
        'https://directinfosgabon.com/seeg-8500-compteurs-electriques-en-stock-a-jeta-engineering/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06a05dd3-865a-48f1-a781-80710184fd36',
        'Satisfaction client : Quelle est la meilleure banque du Gabon ? (Classement 2025)',
        'Selon une enquête menée en 2025, Ecobank est la banque ayant obtenu la meilleure satisfaction des clients au Gabon.',
        'https://directinfosgabon.com/satisfaction-client-quelle-est-la-meilleure-banque-du-gabon-classement-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '15bd2ee7-1e36-482e-a24a-ba44240925e2',
        'Le Président de la République s''entretient avec les représentants de la société BW Energy',
        'Lors d''une visite officielle aux États-Unis, le président gabonais a échangé avec le directeur général de BW Energy sur l''exploitation du nouveau champ pétrolier « Bourdon » au large de Mayumba.',
        'https://www.gabonews.com/fr/actus/energie/article/le-president-de-la-republique-s-entretient-avec',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef5cea6d-e404-492a-861c-ca23622a1c7c',
        'Un fauteuil roulant offert à une maman en détresse par Zita Oligui Nguema',
        'Une mère en difficulté, victime d''une entorse, a reçu un fauteuil roulant offert par la Première Dame, Zita Oligui Nguema, ce qui lui permet de se déplacer seule et de retrouver de la joie.',
        'https://www.gabonews.com/fr/actus/social/article/un-fauteuil-roulant-offert-a-une-maman-en',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5f62f51-5fbe-4dee-ae23-226dfaa26512',
        'Potasse de Mayumba : la société américaine Millennial Potash met sur la table 500 millions de dollars',
        'Une société américaine spécialisée dans l''exploitation de potasse, Millennial Potash, serait sur le point de recevoir un financement de 500 millions de dollars pour développer ses projets en Afrique.',
        'https://mediapostegabon.com/potasse-de-mayumba-la-societe-americaine-millennial-potash-met-sur-la-table-500-millions-de-dollars/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f2850ca-0e6d-4ded-bca6-6b0f5b68f3b6',
        'e-Tax : le Gabon passe au paiement mobile des impôts',
        'Le Gabon facilite le paiement des impôts pour les petits contribuables en leur permettant désormais d''utiliser Moov Money via un nouveau service numérique, e-Tax, visant à simplifier et digitaliser l''administration fiscale.',
        'https://www.gabonreview.com/e-tax-le-gabon-passe-au-paiement-mobile-des-impots/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '61101b31-51ef-42ac-987f-b840a471fbae',
        'BDEAC–Gabon : 60 milliards pour les logements sociaux et de nouveaux axes routiers en ligne de mire',
        'La BDEAC prévoit de financer 60 milliards de francs CFA pour soutenir la construction de logements sociaux et le développement de nouvelles routes au Gabon, afin de renforcer les infrastructures du pays.',
        'https://www.gabonreview.com/bdeac-gabon-60-milliards-pour-les-logements-sociaux-et-de-nouveaux-axes-routiers-en-ligne-de-mire/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '54b56362-362d-4a01-acfc-1e5702f52de6',
        'La Ligue des Jeunes Bâtisseurs en marche',
        'Le président de la Ligue des Jeunes Bâtisseurs a organisé une réunion stratégique avec ses membres pour renforcer la collaboration et définir les orientations du mouvement.',
        'https://www.gabonews.com/fr/actus/politique/article/la-ligue-des-jeunes-batisseurs-en-ordre-de-marche',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41350758-d0c4-4557-84a5-f8541b831b47',
        '"Félicitations à Son Excellence Monsieur le Président de la République, Brice Clotaire Oligui Nguema"',
        'Le président gabonais, Brice Clotaire Oligui Nguema, a salué lors d''une rencontre à Washington la déclaration engageante qu''il a prononcée, défendant fermement les intérêts de son pays.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/felicitations-a-son-excellence-monsieur-le',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57e99f6f-3af5-4255-a588-10737a8c9304',
        'Éliezer Moukouboungou Gomat officialise sa candidature aux législatives pour représenter la diaspora gabonaise zone Afrique',
        'Éliezer Moukouboungou Gomat officialise sa candidature aux législatives pour représenter la diaspora gabonaise en zone Afrique, dans le contexte des prochaines élections législatives et locales au Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/eliezer-moukouboungou-gomat-officialise-sa',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0f4abe2-d82b-4334-9a23-52f95ca030c5',
        'Pétrole : Quelle stratégie pour le Gabon et pour l’OPEP ?',
        'Le marché pétrolier mondial est actuellement incertain, et le Gabon doit élaborer une stratégie adaptée pour faire face aux fluctuations des prix et aux enjeux de l’OPEP afin de renforcer son secteur pétrolier.',
        'https://directinfosgabon.com/petrole-quelle-strategie-pour-le-gabon-et-pour-lopep/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '966f4d3f-3053-4380-b717-16ea812125cd',
        'Pindi et la Chorale Nelson Mandela : Sur scène ce samedi soir',
        'Le groupe Pindi et la Chorale Nelson Mandela se produiront ce samedi soir au Musée national lors d’un spectacle.',
        'https://gabonactu.com/blog/2025/07/11/pindi-et-la-chorale-nelson-mandela-sur-scene-ce-samedi-soir/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bac4c4b8-ddfa-4eff-8644-4ef8c0091d13',
        'Janvier Nguema Mboumba dément les rumeurs de son décès',
        'Janvier Nguema Mboumba a démenti les rumeurs qui disaient qu’il était mort depuis plus de 24 heures, expliquant qu’il s’agit d’une mauvaise interprétation d’un post.',
        'https://www.gabonews.com/fr/actus/societe/article/janvier-nguema-mboumba-dement-les-rumeurs-de-son',
        'Gabonews',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1230b06b-35ff-46a2-afa0-e420218d9b88',
        'Gabon/Réhabilitation des pavillons universitaires : le ministre fait le point avec les opérateurs',
        'Le ministre de l’Enseignement supérieur a rencontré les opérateurs pour faire le point sur l’avancement des travaux de réhabilitation des universités, notamment la rénovation des logements étudiants et la construction de nouvelles infrastructures.',
        'https://agpgabon.ga/gabon-rehabilitation-des-pavillons-universitaires-le-ministre-fait-le-point-avec-les-operateurs/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '82d9d321-e0cf-4efb-88d7-7b003720f333',
        'Gabon/Politique : le mouvement « La Majorité Bloquante » tient une conférence de presse ce vendredi',
        'Le mouvement politique “La Majorité Bloquante” organise une conférence de presse pour présenter ses objectifs, sa vision pour le Gabon, et renforcer son soutien en vue des prochaines élections législatives et locales.',
        'https://agpgabon.ga/gabon-politique-le-mouvement-la-majorite-bloquante-tient-une-conference-de-presse-ce-vendredi/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a20bbe7c-fdf0-4905-ad85-295a2bb17e00',
        'Gabon – Coopération : l’Ambassade de Chine fait don de matériel informatique à l’AGP',
        'L’ambassade de Chine au Gabon a offert à l’Agence gabonaise de presse du matériel informatique, comme des ordinateurs et des imprimantes, pour aider à renforcer ses capacités techniques.',
        'https://agpgabon.ga/gabon-cooperation-lambassade-de-chine-fait-don-de-materiel-informatique-a-lagp/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e1a1d60c-964b-46cd-88e6-e1dc5553f8a1',
        'Gabon : L’UDB a déposé son dossier de légalisation ce vendredi',
        'Le parti politique UDB a déposé officiellement son dossier de reconnaissance auprès du ministère de l’Intérieur en vue de sa légalisation en respectant la législation en vigueur.',
        'https://agpgabon.ga/gabon-ludb-depose-son-dossier-de-legalisation-ce-11-juillet-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72f676da-2f54-4b37-b937-dc70874692f7',
        'Gabon-PDG/Nomination des membres du Bureau Politique',
        'Le Parti Démocratique Gabonais renforce ses structures en renouvelant la composition de son Bureau Politique à travers de nouvelles nominations dans différentes régions.',
        'https://agpgabon.ga/gabon-pdg-nomination-des-membres-du-bureau-politique/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22b3be9b-f15b-4703-837d-38d9a9dcc7c7',
        'Lutte contre la corruption au Gabon : la CNLCEI appelle tous les acteurs à cesser la politique de l’Autriche',
        'La CNLCEI du Gabon appelle tous les acteurs à cesser la politique de l’austérité afin de renforcer la lutte contre la corruption et favoriser le développement du pays.',
        'https://gabonactu.com/blog/2025/07/11/lutte-contre-la-corruption-au-gabon-la-cnlcei-appelle-tous-les-acteurs-a-cesser-la-politique-de-lautriche/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '511b13bc-6295-4e0b-9d32-7be7109d92f0',
        'Législatives et Locales 2025 : les dépôts de candidatures reportés et fixés du 27 juillet au 7 août 2025',
        'Les dépôts de candidatures pour les élections législatives et locales au Gabon, initialement prévus du 17 au 23 juillet 2025, ont été reportés et fixés du 27 juillet au 7 août 2025 par le ministère de l’Intérieur.',
        'https://www.gabonreview.com/legislatives-et-locales-2025-les-depots-de-candidatures-reportes-et-fixes-du-27-juillet-au-7-aout-2025/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '54dc6e5f-79ac-43a7-a32d-878d9de2bdda',
        'Législatives et Locales 2025 : révision de la liste électorale dès le 14 juillet',
        'La liste électorale gabonaise sera révisée à partir du 14 juillet 2024 en vue des élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-revision-de-la-liste-electorale-des-le-14-juillet/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2310f619-7e87-41fc-a9e8-e86e1b4c017d',
        'Gabon-USA : Lancement à Libreville de l’American Business Council !',
        'Un nouveau Conseil des affaires américain a été lancé à Libreville pour renforcer la coopération économique entre le Gabon et les États-Unis.',
        'https://gabonmediatime.com/gabon-usa-lancement-a-libreville-de-lamerican-business-council/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b5309d28-fd53-40f4-ac7b-c2755494ed8a',
        'IMI-PDG : un gendarme décède après un saut du 5e étage !',
        'Un gendarme en mission en Guinée équatoriale est décédé après avoir sauté du 5e étage d’un bâtiment.',
        'https://gabonmediatime.com/imi-pdg-un-gendarme-decede-apres-un-saut-du-5e-etage/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a1e70a5-d457-49e3-8b98-76cbac19aad2',
        'Retour triomphal à Libreville : Oligui Nguema accueilli en héros par la population',
        'Oligui Nguema a été accueilli en héros par la population de Libreville lors de son retour triomphal, marquant son importance pour le pays.',
        'https://kongossanews.info/retour-triomphal-a-libreville-oligui-nguema-accueilli-en-heros-par-la-population/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '64d10bd1-aa28-4e93-82e6-bf011d3fd1c7',
        'Makongonio-Affaire de détournement de fonds : Jean Aimé Foula totalement blanchi',
        'Jean Aime Foula a été totalement innocenté dans l''affaire de détournement de fonds liée à Makongoni, après une enquête approfondie.',
        'https://kongossanews.info/makongonio-affaire-de-detournement-de-fonds-jean-aime-foula-totalement-blanchi/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62c7fc25-0f3b-429c-bc4f-0a7eef9935be',
        'Libertés bafouées ? L’Ordre des avocats alerte sur les violations des règles déontologiques',
        'Les violations des règles déontologiques et les atteintes aux libertés sont dénoncées par l’Ordre des avocats, qui alerte sur des pratiques qui mettent en danger la justice.',
        'https://kongossanews.info/libertes-bafouees-lordre-des-avocats-alerte-sur-les-violations-des-regles-deontologiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '71193128-70a4-4766-9a61-d285171dc4ae',
        'Gabon : retour triomphal du président Oligui Nguema des Etats-Unis',
        'Le président Brice Clotaire Oligui Nguema est accueilli avec enthousiasme à son retour d’une visite officielle aux États-Unis, provoquant une grande mobilisation populaire et des perturbations dans la circulation à Libreville.',
        'https://agpgabon.ga/gabon-retour-triomphal-du-president-oligui-nguema-des-etats-unis/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd7206ba-88c9-4b36-bab7-7c1fb9781878',
        'Législatives et Locales 2025 : révision de la liste électorale dès le 14 juillet',
        'La liste électorale gabonaise sera révisée à partir du 14 juillet 2023 en vue des élections législatives et locales de 2025, permettant d''assurer une meilleure fiabilité du registre électoral.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-revision-de-la-liste-electorale-des-le-14-juillet/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf98b07f-c1f4-4127-a093-3b358eeced9c',
        'Gabon-USA : Lancement à Libreville de l’American Business Council !',
        'Le lancement de l''American Business Council à Libreville vise à renforcer les échanges économiques et commerciaux entre le Gabon et les États-Unis, en facilitant les investissements et la collaboration entre les entreprises des deux pays.',
        'https://gabonmediatime.com/gabon-usa-lancement-a-libreville-de-lamerican-business-council/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b31171ba-35c2-41cb-a9c2-3e818cd6b89d',
        'IMI-PDG : un gendarme décède après un saut du 5e étage !',
        'Un gendarme est décédé après avoir sauté du cinquième étage d’un bâtiment, suscitant une enquête pour déterminer les circonstances de cette chute.',
        'https://gabonmediatime.com/imi-pdg-un-gendarme-decede-apres-un-saut-du-5e-etage/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa8edfb3-3842-485c-8e32-6dba4202c283',
        'Retour triomphal à Libreville : Oligui Nguema accueilli en héros par la population',
        'Le président Oligui Nguema a été chaleureusement accueilli par la population de Libreville lors de son retour, symbole d’un soutien populaire à son leadership en Guinée équatoriale.',
        'https://kongossanews.info/retour-triomphal-a-libreville-oligui-nguema-accueilli-en-heros-par-la-population/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba4fe813-d9b8-4374-9526-4abfc0767d75',
        'Makongonio-Affaire de détournement de fonds : Jean Aimé Foula totalement blanchi',
        'Jean Aimé Foula a été complètement innocenté dans l''affaire de détournement de fonds de Makongoniо, ce qui met fin à l''accusation à son encontre.',
        'https://kongossanews.info/makongonio-affaire-de-detournement-de-fonds-jean-aime-foula-totalement-blanchi/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4bd83af7-c930-475c-b149-fb1faf204d8c',
        'Libertés bafouées ? L’Ordre des avocats alerte sur les violations des règles déontologiques',
        'L''article dénonce des violations des règles déontologiques par certains avocats, remettant en question leur liberté et leur professionnalisme au sein du barreau.',
        'https://kongossanews.info/libertes-bafouees-lordre-des-avocats-alerte-sur-les-violations-des-regles-deontologiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c67c59cf-3a40-498b-a0c7-7c8011320fca',
        'Gabon-EPFASS: quatre étudiants suspendus pour tricherie à l’examen à Makokou',
        'Quatre étudiants de l''EPFASS à Makokou ont été suspendus pour avoir été en possession de corrigés-types et de pompes lors de leur examen du deuxième trimestre.',
        'https://agpgabon.ga/gabon-epfass-quatre-etudiants-suspendus-pour-tricherie-a-lexamen-a-makokou/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '323def6c-abc9-45fe-9f3a-1348c02768b1',
        'Commerce, accueil de criminels: ce qu''il faut retenir du sommet des présidents africains à Washington',
        'Le sommet entre cinq chefs d’États africains et le gouvernement américain a permis d’établir de nouveaux partenariats économiques, même si aucun accord majeur n’a été conclu, avec une demande particulière des États-Unis.',
        'https://www.rfi.fr/fr/afrique/20250711-commerce-accueil-de-criminels-ce-qu-il-faut-retenir-du-sommet-des-pr%C3%A9sidents-africains-%C3%A0-washington',
        'RFI',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c78ba462-7806-4192-82d1-d89ceaa18f8e',
        'E-Tax: la révolution du paiement des impôts via Moov Money au Gabon',
        'Le service e-Tax permet aux contribuables gabonais de payer leurs impôts facilement via Moov Money, favorisant ainsi la digitalisation et la simplification des démarches fiscales.',
        'https://vxp241.com/2025/07/11/e-tax-la-revolution-du-paiement-des-impots-via-moov-money-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6573350e-34bb-488b-9400-fc3032d80ff6',
        'Gabon : retour triomphal d’Oligui Nguema après son séjour jugé fructueux aux Etats Unis',
        'Le président gabonais Brice Clotaire Oligui Nguema est rentré triomphalement de son voyage aux États-Unis, considéré comme une visite fructueuse lors du sommet restreint Afrique-États-Unis à Washington.',
        'https://gabonactu.com/blog/2025/07/11/gabon-retour-triomphal-doligui-nguema-apres-son-sejour-juge-fructueux-etats-unis/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9efb4be5-8813-4960-a3af-7c7510c26feb',
        'Gabon/Formation : une masterclass portée par “La Passion des Autres” pour stimuler les vocations entrepreneuriales',
        'Une initiative visant à encourager l’esprit entrepreneurial chez les jeunes gabonais en valorisant les produits du terroir à travers une masterclass.',
        'https://agpgabon.ga/gabon-formation-une-masterclass-portee-par-la-passion-des-autres-pour-stimuler-les-vocations-entrepreneuriales/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '414d848f-0d40-4aaa-82b5-76d4ef0a1d05',
        'Gabon/Culture : la 4ᵉ édition du FEMOGA reportée à 2026',
        'La quatrième édition du Festival de la mode du Gabon (FEMOGA) est reportée à 2026 en raison de difficultés financières et de problèmes organisationnels liés à l’année électorale.',
        'https://agpgabon.ga/gabon-culture-la-4%e1%b5%89-edition-du-femoga-reportee-a-2026/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf0a0122-6536-4961-981b-f19165baeeaf',
        'Le RPM se fond dans la mouvance présidentielle sous condition',
        'Le président du RPM a annoncé son intention de rejoindre la majorité présidentielle, mais à condition que certaines garanties soient respectées.',
        'https://gabonactu.com/blog/2025/07/12/le-rpm-se-fond-dans-la-mouvance-presidentielle-avec-condition/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '105212d6-03cf-463f-ba73-734ac0e0d9fe',
        'Massaha, un exemple de forêt communautaire au Gabon',
        'Dans la forêt communautaire de Massaha au Gabon, cinq villages exploitent collectivement les ressources naturelles pour vivre, favorisant ainsi la gestion transparente et le vivre-ensemble.',
        'https://www.rfi.fr/fr/podcasts/un-jour-au-village/20250712-massaha-un-exemple-de-for%C3%AAt-communautaire-au-gabon',
        'RFI',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80153814-2782-465f-8bf2-9255aa65d897',
        'Publié le 12 / 07 / 2025',
        'Barro Chambrier appelle à l''unité et à la mobilisation pour soutenir la majorité présidentielle dans ses projets de développement.',
        'https://union.sonapresse.com/fr/formation-de-la-majorite-presidentielle-lappel-de-barro-chambrier',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b5d73555-83a1-4763-a213-3a1514ef5b09',
        'Publié le 12 / 07 / 2025',
        'Sejour d''Oligui Nguema aux États-Unis a été perçu comme un succès diplomatique, apprécié par la population locale.',
        'https://union.sonapresse.com/fr/sejour-doligui-nguema-aux-usa-un-succes-diplomatique-salue-par-les-populations',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72c7958e-6564-4256-b7b6-80740506f6cc',
        'Publié le 12 / 07 / 2025',
        'Les candidatures pour les élections couplées en Côte d''Ivoire doivent être déposées entre le 27 juillet et le 7 août 2023.',
        'https://union.sonapresse.com/fr/elections-couplees-depot-de-candidatures-du-27-juillet-au-07-aout-prochain',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a9ae6fd-b0ff-45e5-9de6-83844dddfde0',
        'Dialogue social :  Louise Pierrette Mvono échange  avec les syndicats du  Ministère de la Planification',
        'Le ministre de la Planification a échangé avec les syndicats de son département pour discuter de la mise en place de projets et de réformes dans le cadre de la politique de développement du pays.',
        'https://gabonactu.com/blog/2025/07/12/dialogue-social-louise-pierrette-mvono-echange-avec-les-syndicats-du-ministere-de-la-planification/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d2504f6-1075-412b-ad84-338e0008c507',
        'Législatives 2025 dans la Mvoung (2e siège) :   Claude François Nkoulaveng candidat',
        'Claude François Nkoulaveng a annoncé sa candidature pour les élections législatives de 2025 dans le département de la Mvoung (canton Dzoué) au sein de la province de l’Ogooué.',
        'https://gabonactu.com/blog/2025/07/12/legislatives-2025-dans-la-mvoung-2e-siege-claude-francois-nkoulaveng-candidat/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d098d3b-66db-4426-82a1-800d7ad0bf7b',
        'Le Chef de l''État de retour de Washington',
        'À son retour d''une visite officielle aux États-Unis, le président gabonais a été accueilli chaleureusement à son arrivée à Libreville, soulignant le renforcement des relations bilatérales entre le Gabon et les États-Unis.',
        'https://www.gabonews.com/fr/actus/politique/article/le-chef-de-l-etat-de-retour-de-washington',
        'Gabonews',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

