-- Batch 2 - Section 3/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'db722f1d-1781-4559-95f4-a0504ea13e6a',
        'Campagne de Proximité de la coordinatrice provinciale adjointe de  C’BON au 2e arrondissement de Libreville pour Oligui Nguema',
        'La coordinatrice provinciale adjointe de CBON a mené une campagne de proximité dans le 2e arrondissement de Libreville pour sensibiliser et mobiliser les citoyens en faveur du président Oligui Nguéma. Elle a échangé avec les habitants sur les enjeux locaux et les actions gouvernementales.',
        'https://kongossanews.info/campagne-de-proximite-de-la-coordinatrice-provinciale-adjointe-de-cbon-au-2e-arrondissement-de-libreville-pour-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '54291cb9-9dee-4147-8968-086580569dcc',
        'Perenco Gabon face à des accusations de manquements éthiques et d’entraves à la liberté syndicale',
        'L''entreprise pétrolière Perenco Gabon est accusée de violations éthiques et d''entraves à la liberté syndicale, notamment par des licenciements abusifs et des pressions sur les travailleurs souhaitant se syndiquer. Ces allégations soulèvent des inquiétudes quant aux droits des employés et aux pratiques de l''entreprise dans le pays.',
        'https://kongossanews.info/perenco-gabon-face-a-des-accusations-de-manquements-ethiques-et-dentraves-a-la-liberte-syndicale/',
        'Kongossa News',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a101a78-f7b2-4d2d-9fd5-da540da82034',
        'Pierre Akendengue en concert pour la première fois en Côte-d''Ivoire le 25 février',
        'Le musicien gabonais Pierre Akendengué a donné son premier concert en Côte d’Ivoire le 25 février, marquant un événement culturel important pour ses fans et la scène musicale africaine.',
        'https://www.rfi.fr/fr/podcasts/couleurs-tropicales/20250408-pierre-akendengue-en-concert-pour-la-premi%C3%A8re-fois-en-c%C3%B4te-d-ivoire-le-25-f%C3%A9vrier',
        'RFI',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '021bb8a7-4fc0-4a19-9924-a2e0237f6d1a',
        'Gabon : la lutte contre la vie chère',
        'Au Gabon, des mesures sont prises pour lutter contre la vie chère, notamment des subventions sur les produits de première nécessité et des contrôles de prix, afin de soulager les populations face à l''inflation. Ces initiatives visent à réduire les tensions sociales liées au coût élevé de la vie.',
        'https://information.tv5monde.com/international/video/gabon-la-lutte-contre-la-vie-chere-2769335?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Services, Commerce, Finances',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fcf346a-46ac-4fc3-b0e3-b59124507403',
        'Gros Bouquet : plus d’une centaine de détenus libérés après une descente du procureur général',
        'Plus d''une centaine de détenus ont été libérés après une descente du procureur général dans une prison, mettant en lumière des conditions de détention préoccupantes. Cette action vise à alléger la surpopulation carcérale et à examiner les dossiers judiciaires en suspens.',
        'https://gabonmediatime.com/gros-bouquet-plus-dune-centaine-de-detenus-liberes-apres-une-descente-du-procureur-general/',
        'Gabon Media Time',
        'Services, Éducation, Finances',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7ebb2389-e911-450b-911f-fec894c6514a',
        'Cemac : le Gabon principal contributeur en devises de la zone en 2024',
        'Le Gabon est le principal contributeur en devises de la CEMAC en 2024, apportant une part significative des recettes de la zone grâce à ses exportations de pétrole et de manganèse. Cette performance renforce sa position économique centrale dans la région.',
        'https://gabonmediatime.com/cemac-le-gabon-principal-contributeur-en-devises-de-la-zone-en-2024/',
        'Gabon Media Time',
        'Numérique / Digital, Finances, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21e606d8-e4ef-4416-8e7a-36add014e3dd',
        'Gabon : 500 millions de budget additionnel pour la mairie de Libreville',
        'La mairie de Libreville bénéficie d''un budget supplémentaire de 500 millions de FCFA pour renforcer ses projets de développement urbain et améliorer les services publics. Cette enveloppe vise à soutenir les infrastructures locales et les initiatives sociales dans la capitale gabonaise.',
        'https://gabonmediatime.com/gabon-500-millions-de-budget-additionnel-pour-la-mairie-de-libreville/',
        'Gabon Media Time',
        'Commerce, Services, Tourisme',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f33e4491-6bc7-4981-8d59-21e4123d6e05',
        'La mobilisation exceptionnelle des populations du département du Komo Océan des coordinations de campagne de la commune et du dé...',
        'Les populations du département du Komo-Océan se sont massivement mobilisées pour voter lors d''une campagne électorale marquée par un fort soutien à Oligui Nguema, avec une participation active des coordinations locales et communales. Cet engagement citoyen a témoigné d''une dynamique collective en faveur du processus démocratique.',
        'https://kongossanews.info/la-mobilisation-exceptionnelle-des-populations-du-departement-du-komo-ocean-des-coordinations-de-campagne-de-la-commune-et-du-departement-pour-voter-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae06670d-206b-4f97-b057-4fcc6484b5c4',
        'Campagne de Proximité de la coordinatrice provinciale adjointe de  C’BON au 2e arrondissement de Libreville pour Oligui Nguema',
        'La coordinatrice provinciale adjointe de CBON au 2e arrondissement de Libreville a mené une campagne de proximité pour soutenir la candidature d''Oligui Nguema, en échangeant avec les habitants sur les enjeux locaux. Cette initiative visait à renforcer les liens entre la population et les représentants politiques avant les élections.',
        'https://kongossanews.info/campagne-de-proximite-de-la-coordinatrice-provinciale-adjointe-de-cbon-au-2e-arrondissement-de-libreville-pour-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21563812-dcfc-48a9-b37a-a6adc797c35b',
        'Perenco Gabon face à des accusations de manquements éthiques et d’entraves à la liberté syndicale',
        'L’entreprise pétrolière Perenco Gabon est accusée de violations éthiques et d’entraves à la liberté syndicale, notamment pour avoir licencié des employés engagés dans des activités syndicales. Ces allégations soulèvent des inquiétudes quant au respect des droits des travailleurs dans le secteur énergétique gabonais.',
        'https://kongossanews.info/perenco-gabon-face-a-des-accusations-de-manquements-ethiques-et-dentraves-a-la-liberte-syndicale/',
        'Kongossa News',
        'Services, Finances, Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '136b1a3b-91ce-415a-b00c-af493eb74c36',
        'Pétrole : SMP Afrique et Tullow Oil sous actionnariat de Gabon Oil Company',
        'SMP Africa et Tullow Oil, partenaires sous l’actionnariat de Gabon Oil Company, collaborent dans le secteur pétrolier au Gabon. Cette alliance vise à renforcer les activités d’exploration et de production d’hydrocarbures dans le pays.',
        'https://mediapostegabon.com/petrole-smp-afrique-et-tullow-oil-sous-actionnariat-de-gabon-oil-company/',
        'Media Poste Gabon',
        'Énergie, Finances',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f56324bd-a135-4427-9074-d0c490ab275f',
        'Ogooué-Lolo : les membres Rassemblement des Bâtisseurs en mode séduction à Koulamoutou pour Oligui Nguema',
        'Les membres du Rassemblement des Républicains dans l’Ogooué-Lolo se sont réunis pour discuter des stratégies politiques locales et renforcer leur unité en vue des prochaines échéances électorales.',
        'https://www.gabonews.com/fr/actus/politique/article/ogooue-lolo-les-membres-rassemblement-des',
        'Gabonews',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f865f25-d892-4f81-b260-9c696d307e2d',
        'Gros Bouquet : plus d’une centaine de détenus libérés après une descente du procureur général',
        'Plus d''une centaine de détenus ont été libérés après une descente du procureur général dans une prison, mettant en lumière des problèmes liés aux conditions de détention. Cette action vise à alléger la surpopulation carcérale et à améliorer le respect des droits des prisonniers.',
        'https://gabonmediatime.com/gros-bouquet-plus-dune-centaine-de-detenus-liberes-apres-une-descente-du-procureur-general/',
        'Gabon Media Time',
        'Services, Éducation, Finances',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6bd6c7e4-020f-420e-8d6c-0a42cd4bea2a',
        'Cemac : le Gabon principal contributeur en devises de la zone en 2024',
        'Le Gabon est le principal contributeur en devises de la zone CEMAC en 2024, renforçant ainsi son rôle économique central dans la région. Cette performance s’explique notamment par ses exportations de pétrole et sa stabilité financière.',
        'https://gabonmediatime.com/cemac-le-gabon-principal-contributeur-en-devises-de-la-zone-en-2024/',
        'Gabon Media Time',
        'Numérique / Digital, Finances, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '351fcfc9-48ce-491a-9d6c-53d5eee29793',
        'Gabon : 500 millions de budget additionnel pour la mairie de Libreville',
        'La mairie de Libreville reçoit un budget additionnel de 500 millions de FCFA pour améliorer les services publics et les infrastructures urbaines. Ces fonds visent à renforcer les actions municipales en faveur des citoyens.',
        'https://gabonmediatime.com/gabon-500-millions-de-budget-additionnel-pour-la-mairie-de-libreville/',
        'Gabon Media Time',
        'Services, Numérique / Digital, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d709070-53b4-42a6-8653-937d0b99ab5d',
        'Pétrole : SMP Afrique et Tullow Oil sous actionnariat de Gabon Oil Company',
        'SMP Africa et Tullow Oil, partenaires sous l’actionnariat de Gabon Oil Company, collaborent dans le secteur pétrolier au Gabon. Cette alliance vise à renforcer les activités d’exploration et de production d’hydrocarbures dans le pays.',
        'https://mediapostegabon.com/petrole-smp-afrique-et-tullow-oil-sous-actionnariat-de-gabon-oil-company/',
        'Media Poste Gabon',
        'Services, Finances, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3f251cc-ff20-47ff-98f6-d217d3b95356',
        'Guélor Kanga champion de Serbie pour la 6e fois',
        'Guelor Kanga a remporté pour la sixième fois consécutive le championnat de Serbie, confirmant sa domination dans le football local. Ce joueur gabonais continue d''impressionner par ses performances et sa constance au plus haut niveau.',
        'https://gabonactu.com/blog/2025/04/08/guelor-kanga-champion-de-serbie-pour-la-6e-fois/',
        'Gabon Actu',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4a30bf4c-6944-40ed-9b13-c7590ed43573',
        '"Les élections en Afrique ne doivent plus être source de craintes et de tensions" dixit Abdou Abarry',
        'Les élections en Afrique doivent évoluer vers plus de transparence et d''inclusion pour éviter les conflits et garantir la légitimité des dirigeants, en s''inspirant des meilleures pratiques démocratiques.',
        'https://www.gabonews.com/fr/actus/politique/article/les-elections-en-afrique-ne-doivent-plus-etre',
        'Gabonews',
        'Numérique / Digital, Services, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74d05de3-2626-418e-ae7b-33eceb4462c8',
        'Publié le 08 / 04 / 2025',
        'L''article aborde les préoccupations des habitants du Moyen-Ogooué et de Makouké face aux promesses non tenues des gouvernements précédents, tout en exprimant leurs attentes pour les prochaines élections présidentielles. Les citoyens espèrent des actions concrètes pour améliorer leurs conditions de vie et le développement local.',
        'https://union.sonapresse.com/fr/presidentielle-moyen-ogooue-makouke-entre-rappel-des-promesses-non-tenues-et-attentes',
        'L''union',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e227c6d4-cc21-4c61-aa17-6ece2a86afa2',
        'Publié le 08 / 04 / 2025',
        'Le Woleu-Ntem, fief du président sortant, vise un score de 100 % pour Ali Bongo Ondimba lors de la présidentielle, selon les partisans locaux qui appellent à une mobilisation massive.',
        'https://union.sonapresse.com/fr/presidentielle-woleu-ntem-nous-devons-atteindre-un-score-de-100-pour-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7711abdf-f0c4-4117-9c63-e43ca543afe4',
        'Publié le 08 / 04 / 2025',
        'Les cartes d''électeurs pour la présidentielle dans l''Ogooué-Maritime sont désormais disponibles, permettant aux citoyens de participer au scrutin. Cette distribution était attendue après des retards antérieurs.',
        'https://union.sonapresse.com/fr/presidentielle-ogooue-maritime-les-cartes-delecteurs-enfin-disponibles',
        'L''union',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1080907e-9075-43cf-bfb6-961eb4c99164',
        'Gabon-Présidentielle 2025 : l’association DiDOMI nettoie le centre de vote d’Ambowè',
        'L’association Didomi a organisé une opération de nettoyage du centre de vote d’Ambowe en prévision de l’élection présidentielle gabonaise de 2025, mobilisant des bénévoles pour assurer un environnement propre et accueillant. Cette initiative citoyenne vise à promouvoir la participation électorale et le civisme.',
        'https://agpgabon.ga/2025/04/08/gabon-presidentielle-2025-lassociation-didomi-nettoie-le-centre-de-vote-dambowe/',
        'AGP',
        'Services, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c35d244-896c-406a-80a1-81864b2646ae',
        'Publié le 08 / 04 / 2025',
        'L''article évoque les attentes des habitants du Moyen-Ogooué envers le gouvernement, soulignant les promesses non tenues lors des précédentes élections et leurs espoirs pour des améliorations futures. Les préoccupations locales concernent notamment les infrastructures et le développement socio-économique.',
        'https://union.sonapresse.com/fr/presidentielle-moyen-ogooue-makouke-entre-rappel-des-promesses-non-tenues-et-attentes',
        'L''union',
        'Services, Commerce, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '702eb9e8-a6da-47c2-b5de-821e1129eeab',
        'Publié le 08 / 04 / 2025',
        'Le Woleu-Ntem, région natale du président gabonais Oligui Nguéma, vise un score électoral de 100 % pour lui lors de la prochaine présidentielle, selon des partisans locaux qui affirment leur soutien total.',
        'https://union.sonapresse.com/fr/presidentielle-woleu-ntem-nous-devons-atteindre-un-score-de-100-pour-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '209fd8a0-543e-418f-8849-1aba32074544',
        'Publié le 08 / 04 / 2025',
        'Les cartes d''électeurs pour la présidentielle dans l''Ogooué-Maritime au Gabon sont désormais disponibles, permettant aux citoyens de participer au scrutin. Cette distribution était attendue après des retards antérieurs.',
        'https://union.sonapresse.com/fr/presidentielle-ogooue-maritime-les-cartes-delecteurs-enfin-disponibles',
        'L''union',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a324c14-4bcb-406f-a185-ca35ee17f8c4',
        'Gabon/Rappels soldes : 70 milliards FCFA déjà réglés sur les 105 prévus',
        'Le Gabon a déjà remboursé 70 milliards de FCFA sur les 105 milliards prévus pour le règlement des rappels de soldes, démontrant une avancée significative dans ses engagements financiers.',
        'https://agpgabon.ga/2025/04/09/gabon-rappels-soldes-70-milliards-fcfa-deja-regles-sur-les-105-prevus/',
        'AGP',
        'Finances, Services',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9c2451f4-8e62-47f1-9205-23e33932ce91',
        'Gabon/Régularisation des pensions : 57,4 milliards de FCFA versés à 52 129 retraités',
        'Le Gabon a versé 574 milliards de FCFA pour régulariser les pensions de 52 129 retraités, dans le cadre d’une opération visant à améliorer leur situation financière. Cette mesure s’inscrit dans les efforts du gouvernement pour garantir les droits sociaux des anciens travailleurs.',
        'https://agpgabon.ga/2025/04/09/gabon-regularisation-des-pensions-574-milliards-de-fcfa-verses-a-52-129-retraites/',
        'AGP',
        'Services, Finances, Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf294f75-ce82-4675-aae6-59805d9f9fc6',
        'Gabon : le difficile accès à l''eau et à l''électricité',
        'Au Gabon, de nombreux habitants rencontrent des difficultés pour accéder à l''eau potable et à l''électricité, malgré les ressources naturelles du pays, ce qui impacte leur quotidien et le développement local.',
        'https://information.tv5monde.com/afrique/video/gabon-le-difficile-acces-leau-et-lelectricite-2769384?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Services, Numérique / Digital, Agriculture',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36f08099-37e8-4da3-bd3b-f19de97b4824',
        'Présidentielle 2025: L’Ogooué-Ivindo réaffirme son soutien OLIGUI NGUEMA',
        'Le député Logo Ivindo réaffirme son soutien au président Oligui Nguéma pour l’élection présidentielle de 2025, soulignant son engagement envers le développement du Gabon.',
        'https://vxp241.com/2025/04/09/presidentielle-2025-logooue-ivindo-reaffirme-son-soutien-oligui-nguema/',
        'Vox Populi',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc8c4ed7-a1d3-4012-80ae-cd589cc86637',
        'Election présidentielle au Gabon : qui sont les huit candidats ?',
        'Huit candidats se présentent à l''élection présidentielle au Gabon, chacun proposant des programmes différents pour répondre aux défis économiques et sociaux du pays.',
        'https://www.lemonde.fr/afrique/article/2025/04/09/election-presidentielle-au-gabon-qui-sont-les-huit-candidats_6593124_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08925f0c-0219-4b6a-a75d-7d16b0f837cc',
        'Arnauld Clobert Lebomo au cœur de la mobilisation et de la ferveur populaire autour de l''arrivée d''Oligui Nguema à Moanda',
        'Arnold Clobert Lebomo, une figure politique gabonaise, est au centre d''une actualité impliquant des enjeux locaux, bien que les détails spécifiques ne soient pas précisés dans l''article.',
        'https://www.gabonews.com/fr/actus/politique/article/arnauld-clobert-lebomo-au-coeur-de-la',
        'Gabonews',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b6c9ac9-9c52-4631-8452-2c140c9f7aad',
        'Présidentielle au Gabon : la diaspora de France en campagne pour tourner la page Bongo',
        'Des membres de la diaspora gabonaise en France s''engagent dans la campagne électorale pour promouvoir un changement politique après des décennies de pouvoir des Bongo, tout en critiquant les inégalités et la corruption dans leur pays.',
        'https://www.france24.com/fr/afrique/20250409-pr%C3%A9sidentielle-gabon-diaspora-france-campagne-pour-tourner-la-page-bongo?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d4139ae-2d0b-4f70-91c5-45199a9a3cd8',
        'Présidentielle au Gabon : la diaspora de France en campagne pour tourner la page Bongo',
        'La diaspora gabonaise en France s''engage activement dans la campagne électorale pour soutenir un changement politique après des décennies de pouvoir des Bongo, en mobilisant les jeunes et en promouvant la transparence.',
        'https://www.france24.com/fr/afrique/20250409-pr%C3%A9sidentielle-gabon-diaspora-france-campagne-pour-tourner-la-page-bongo',
        'France 24',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d279e7f-6bf9-4840-8e86-1f13d54f4501',
        'Des observateurs de plus en plus formés pour garantir une élection équitable et transparente',
        'Des observateurs électoraux mieux formés et équipés sont déployés pour assurer le bon déroulement des élections au Gabon, renforçant ainsi la transparence et la crédibilité du processus démocratique.',
        'https://gabonactu.com/blog/2025/04/09/des-observateurs-de-plus-en-plus-formes-pour-garantir-une-election-equitable-et-transparente/',
        'Gabon Actu',
        'Éducation, Services',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c82de959-6ad0-4981-95a9-64f92b5899b8',
        'Gabon : Oligui Nguema promet des centrales à gaz pour mettre définitivement fin aux délestages',
        'Le président gabonais Oligui Nguema annonce la construction de centrales à gaz pour résoudre durablement les problèmes de délestage et assurer un approvisionnement stable en électricité. Cette initiative vise à moderniser le réseau énergétique du pays et à améliorer les conditions de vie des populations.',
        'https://gabonactu.com/blog/2025/04/09/gabon-oligui-nguema-promet-des-centrales-a-gaz-pour-mettre-definitivement-fin-aux-delestages/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1103486e-2672-47c7-b144-e7e7169c8dfd',
        'Présidentielle 2025 : Zénaba Chaning Gninga va rompre avec les anciennes pratiques',
        'Zenaba Chaning Gninga, candidate à la présidentielle 2025 au Gabon, promet de rompre avec les anciennes pratiques politiques en proposant une nouvelle approche plus transparente et inclusive. Elle souhaite moderniser la gouvernance et répondre aux attentes des jeunes et des citoyens.',
        'https://gabonactu.com/blog/2025/04/09/presidentielle-2025-zenaba-chaning-gninga-va-rompre-avec-les-anciennes-pratiques/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '624e4b77-7dc9-4476-b06f-323ea88ccc94',
        'Komo-Océan : L’appel clair du vote en faveur d’Oligui Nguéma à la Pointe-Denis',
        'Les habitants de Komo-Océan ont massivement voté en faveur d''Oligui Nguema lors d''une consultation à Pointe-Denis, exprimant ainsi un soutien marqué à sa leadership. Cette mobilisation reflète une adhésion populaire aux projets politiques et sociaux qu''il porte.',
        'https://gabonactu.com/blog/2025/04/09/komo-ocean-lappel-clair-du-vote-en-faveur-doligui-nguema-a-la-pointe-denis/',
        'Gabon Actu',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '442c5f26-d28a-479b-a225-3008ee779769',
        'Présidentielle 2025 : «On ne bâtit pas dans la guerre», l’appel vibrant d’Honorine Ngou à une présidentielle apaisée au Gabon',
        'Honorine Ngou appelle à une présidentielle apaisée au Gabon en 2025, soulignant que la paix est essentielle pour construire l’avenir du pays. Elle insiste sur le dialogue et l’unité pour éviter les tensions politiques.',
        'https://www.gabonreview.com/presidentielle-2025-on-ne-batit-pas-dans-la-guerre-lappel-vibrant-dhonorine-ngou-a-une-presidentielle-apaisee-au-gabon/',
        'Gabon Review',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8aed1a8-fc85-4f31-9fc9-88d32a5e07d8',
        'Présidentielle du 12 avril : la mission d’observation du Commonwealth reçue par Paul-Marie Gondjout',
        'Le Commonwealth a envoyé une mission d’observation pour les élections présidentielles du 12 avril au Gabon, rencontrée par Paul Marie Gondjout pour discuter du processus électoral. Cette initiative vise à assurer la transparence et la crédibilité du scrutin.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-la-mission-dobservation-du-commonwealth-recue-par-paul-marie-gondjout/',
        'Gabon Review',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd83d294c-8632-420e-9485-f26014683983',
        'ARTF : entre réforme ambitieuse et tensions internes',
        'L’ARTF au Gabon traverse une période de réforme ambitieuse visant à moderniser le secteur des télécommunications, mais elle est marquée par des tensions internes liées à des désaccords sur sa gouvernance et ses orientations stratégiques.',
        'https://www.gabonreview.com/artf-entre-reforme-ambitieuse-et-tensions-internes/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6104e78c-361c-4c50-af67-b450c61ed18a',
        'Gabon : l''unique train du pays entame sa modernisation',
        'Le seul train du Gabon, reliant Libreville à Franceville, commence sa modernisation avec de nouveaux wagons et locomotives pour améliorer le transport des marchandises et des passagers. Ce projet vise à renforcer l''économie locale et désenclaver les régions intérieures.',
        'https://www.france24.com/fr/vid%C3%A9o/20250409-gabon-l-unique-train-du-gabon-entame-sa-modernisation',
        'France 24',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c5f10a5-0b6c-4893-8a6b-66682f4ae2f7',
        '1 Candidat – 1 Projet / Corruption : Les ‘’voyous en col blanc’’ dans le collimateur d’Oligui Nguéma',
        'Le président gabonais Oligui Nguema s’attaque à la corruption en ciblant les « voyous en col blanc » impliqués dans des détournements de fonds publics, notamment via des projets fictifs liés à des candidats. Cette initiative vise à assainir la gestion des ressources de l’État.',
        'https://gabonactu.com/blog/2025/04/09/1-candidat-1-projet-corruption-les-voyous-en-col-blanc-dans-le-collimateur-doligui-nguema/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8b412d0b-25c4-463d-8ab3-3f1e54859cab',
        '« Lambaréné c’est le meilleur exemple du Gabon » (Dr Iloko Boussengui)',
        'Lambaréne est présentée comme un modèle de développement au Gabon, mettant en avant ses initiatives locales en matière d''éducation, de santé et d''innovation, selon les propos du Dr Iloko Boussengui. La ville illustre comment les solutions communautaires peuvent inspirer le reste du pays.',
        'https://gabonactu.com/blog/2025/04/09/lambarene-cest-le-meilleur-exemple-du-gabon-dr-iloko-boussengui/',
        'Gabon Actu',
        'Numérique / Digital, Éducation, Services, Santé',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75676eaf-d2ba-4ccc-ba16-08798defe403',
        'Gabon : Thierry Yvon Michel N’Goma veut rompre définitivement avec la Françafrique',
        'Thierry Yvon Michel Ngoma, président du parti politique ADERE, propose une nouvelle vision pour le Gabon visant à rompre avec l’influence traditionnelle de la France (Françafrique) et à promouvoir une souveraineté nationale renforcée. Il défend une approche panafricaine et une coopération équilibrée avec les partenaires internationaux pour un développement autonome.',
        'https://www.gabonreview.com/gabon-thierry-yvon-michel-ngoma-veut-rompre-definitivement-avec-la-francafrique/',
        'Gabon Review',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dbed712e-cc4f-4c85-ab3d-08a58686ec10',
        'Entre le Gabon et les Bongo, les « BMA » pourraient ouvrir un nouveau front judiciaire',
        'Les BMA, une société britannique, pourraient engager des poursuites judiciaires contre le Gabon pour rupture de contrat après le coup d''État de 2023, ce qui pourrait compliquer la transition politique et économique du pays.',
        'https://www.jeuneafrique.com/1677080/politique/entre-le-gabon-et-les-bongo-les-bma-pourraient-ouvrir-un-nouveau-front-judiciaire/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa5448fb-e739-4c49-bdba-8ca616fd4e80',
        'Campagne présidentielle : Rendez-vous manqué',
        'La campagne présidentielle au Gabon a été marquée par des rendez-vous manqués entre candidats et électeurs, avec des meetings peu fréquentés et un manque d''engagement visible de la part de la population.',
        'https://www.gabonreview.com/campagne-presidentielle-rendez-vous-manque/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1cf57d2e-ba93-44f3-8353-ef9c6df52a23',
        'Pour que le Gabon pèse, il doit compter ses impacts… pour financer son avenir',
        'Le Gabon doit mieux évaluer et valoriser ses impacts environnementaux et socio-économiques pour attirer des financements internationaux et financer son développement durable. Une stratégie de mesure précise permettrait de convertir ses atouts naturels en ressources financières pour l''avenir.',
        'https://www.gabonreview.com/pour-que-le-gabon-pese-il-doit-compter-ses-impacts-pour-financer-son-avenir/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b74faddd-6445-44f4-9dcb-bcd83f146571',
        '"Oligui Nguema est l''homme de la situation" dixit Armand Dagraça',
        'L''article présente le général Oligui Nguéma comme la personne adaptée pour résoudre les défis actuels du Gabon, selon des opinions exprimées dans le contexte politique du pays. Il souligne son rôle perçu comme stabilisateur et rassembleur dans une période de transition.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/oligui-nguema-est-l-homme-de-la-situation-dixit',
        'Gabonews',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65ce6c7c-d4c3-4bc0-9114-e548494d656b',
        '«Lobby», le nouveau projet de Vicky qui marque un tournant dans sa carrière',
        'Vicky, ancienne journaliste, lance un projet de lobby pour promouvoir les talents africains dans les secteurs de la tech et de l''éducation, marquant ainsi un nouveau cap dans son parcours professionnel. Son initiative vise à influencer les politiques et à créer des opportunités pour les jeunes du continent.',
        'https://www.rfi.fr/fr/podcasts/couleurs-tropicales/20250409-lobby-le-nouveau-projet-de-vicky-qui-marque-un-tournant-dans-sa-carri%C3%A8re',
        'RFI',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '484cda0c-7751-45eb-8fe7-6df733192363',
        'Présidentielle 2025 : La campagne pour Brice Clotaire Oligui Nguema s’intensifie dans l’Ogooué-Lolo',
        'La campagne électorale pour Brice Clotaire Oligui Nguema, candidat à la présidentielle de 2025, prend de l''ampleur dans la province de l''Ogooué-Lolo, avec des soutiens locaux qui multiplient les mobilisations. Les partisans organisent des rencontres et des actions pour renforcer sa visibilité avant les élections.',
        'https://kongossanews.info/presidentielle-2025-la-campagne-pour-brice-clotaire-oligui-nguema-sintensifie-dans-logooue-lolo/',
        'Kongossa News',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

