-- Batch 3 - Section 16/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '38bad202-aa6c-4ded-8798-bad4647fffaa',
        'Pétrole : BW Energy prend les commandes du navire FPSO BW Adolo',
        'BW Energy a repris les opérations du FPSO BW Adolo, un navire utilisé pour le traitement et le stockage du pétrole en mer, le transfert s''effectuant dans le cadre d''une charte modifiée. Cette prise de contrôle est un pas naturel pour BW Energy, qui renforce sa présence au Gabon et optimise ses opérations locales.',
        'https://directinfosgabon.com/petrole-bw-energy-prend-les-commandes-du-navire-fpso-bw-adolo/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fbbcaeca-916a-41d3-a206-2019fb0c4d5d',
        'Gabon : Renforcement des compétences au CGC avec l’appui de l’ENA',
        'Le Conseil gabonais des chargeurs (CGC), avec l''appui de l’École nationale d’administration (ENA), a organisé un séminaire du 12 au 19 mai 2025 pour renforcer les compétences de 70 agents à travers des modules sur le coaching, le leadership, la conduite du changement et la rédaction administrative, dans le but d''améliorer la performance et la rigueur professionnelle au sein de l’institution. Cette initiative vise à moderniser l’administration publique gabonaise en favorisant la culture de la performance et de l’engagement. [1]',
        'https://www.gabonreview.com/gabon-renforcement-des-competences-au-cgc-avec-lappui-de-lena/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7ba310d7-9464-45fb-bde7-d47f43498675',
        'Saudi Pro League : Aubameyang s’offre un doublé',
        'Pierre-Emerick Aubameyang, attaquant vedette d''Al-Qadsiah, a connu un double revers dans la Saudi Pro League. Les performances de l''équipe ont été impactées par des défaites, mettant en péril leurs ambitions de classement.',
        'https://agpgabon.ga/2025/05/21/saudi-pro-league-aubameyang-soffre-un-double/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3ac968cd-bda6-4a85-8e14-6d447c61b75a',
        'Gabon/Matchs amicaux des Panthères : ce sera finalement les 6 et 9 juin prochains',
        'Les Panthères du Gabon disputeront deux matchs amicaux en juin 2025 à Casablanca, face à la Guinée-Bissau le 6 juin et au Liberia le 9 juin, dans le cadre de leur préparation pour les qualifications de la Coupe du Monde 2026. Un stage de préparation se tiendra également au Maroc pour optimiser la cohésion et les performances de l''équipe. [1][3][6]',
        'https://agpgabon.ga/2025/05/21/gabon-matchs-amicaux-des-pantheres-ce-sera-finalement-les-6-et-9-juin-prochains/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc145c60-23f0-43f4-b107-f99aef15b2b4',
        'FILIGA, du 29 au 31 mai',
        'La 4e édition du Festival International du Livre Gabonais et des Arts (FILIGA) se tiendra à Libreville du 29 au 31 mai 2025, avec pour thème « L’intelligence culturelle à l’ère des transformations digitales », réunissant des écrivains et artistes de plusieurs pays, dont le Cameroun invité d’honneur, pour des conférences, ateliers et performances autour de la culture africaine et numérique. Cet événement vise à promouvoir la diversité culturelle gabonaise et panafricaine tout en favorisant les échanges entre professionnels, enseignants et grand public.',
        'https://gabonactu.com/blog/2025/05/21/filiga-du-29-au-31-mai/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88553a92-91a8-4ea5-ad39-be96981ca53f',
        'Gabon : Les sénateurs refusent de ratifier le statut de la Cour islamique internationale de justice',
        'Le Sénat de la transition au Gabon a rejeté un projet de loi visant à ratifier le statut de la Cour Internationale Islamique de Justice le 20 mai 2025. Cette décision intervient alors que le gouvernement avait approuvé le projet en janvier 2025, dans le cadre d''un renforcement des liens avec l''Organisation de la Coopération Islamique.',
        'https://www.gabonreview.com/gabon-les-senateurs-refusent-de-ratifier-le-statut-de-la-cour-islamique-internationale-de-justice/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e88cd55-3fc7-4673-999d-c4416a4057ba',
        'Des Masters Class pour édifier la jeunesse de Fougamou',
        'Des master classes sont organisées au Gabon pour soutenir la jeunesse, en particulier pour renforcer leur mentalité et explorer des opportunités d''emploi. Ces événements encouragent l''entrepreneuriat et l''autonomisation des jeunes, en mettant l''accent sur la création d''emplois grâce à des initiatives économiques innovantes.',
        'https://www.gabonews.com/fr/actus/societe/article/des-masters-class-pour-edifier-la-jeunesse-de',
        'Gabonews',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4cd6e92-8259-4f97-b69b-ab5344603d74',
        'Football/Matchs amicaux du Gabon : Thierry Mouyouma face à la presse le 30 mai prochain',
        'Thierry Mouyouma, sélectionneur de l’équipe nationale gabonaise de football, annoncera le 30 mai 2025 la liste des joueurs retenus pour deux matchs amicaux contre la Guinée-Bissau et le Libéria, préparatoires aux qualifications pour la Coupe d’Afrique des Nations 2025. Ces rencontres permettront de tester l’équipe et d’évaluer de nouveaux talents en vue des prochaines échéances internationales[3].',
        'https://agpgabon.ga/2025/05/21/football-match-amicaux-du-gabon-thierry-mouyouma-face-a-la-presse-le-30-mai-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ed47688-4a27-4ab9-8a88-1a698c990709',
        'Cameroun/Fête nationale : entre l’unité et contestation des partis exclus',
        'Le Cameroun a célébré sa fête nationale le 20 mai 2025, sous le thème « Armée et nation, ensemble pour un Cameroun uni, pacifique et prospère », dans un contexte de tension et de contestation politique. Cette fête intervient dans un climat préélectoral, avec une présidentielle prévue pour octobre, et a suscité des critiques de la part de partis exclus du processus électoral.',
        'https://agpgabon.ga/2025/05/21/cameroun-fete-nationale-entre-lunite-et-contestation-des-partis-exclus/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9dbd0075-f9fa-414c-bec1-7a4039937c73',
        'Israël : l’ONU autorisée à faire entrer environ 100 camions d’aide',
        'L’ONU a reçu l’autorisation d’Israël pour faire entrer environ 100 camions d’aide humanitaire dans la bande de Gaza, après plus de deux mois de blocus total, afin d’atténuer la grave crise alimentaire et sanitaire dans la région. Cette décision intervient alors que l’offensive militaire israélienne se poursuit, exacerbant la situation humanitaire déjà catastrophique. [1][4][5]',
        'https://agpgabon.ga/2025/05/21/israel-lonu-autorisee-a-faire-entrer-environ-100-camions-daide/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de1f8887-3c88-4ad7-94cd-0027049f30fa',
        'Ibrahim Magassa, le banquier ivoirien devenu l’architecte des reprofilages de dettes en Afrique centrale',
        'Ibrahim Magassa, banquier franco-ivoirien, est devenu une figure clé dans la gestion des dettes en Afrique centrale en conseillant des villes comme Abidjan, Accra, Brazzaville et Libreville. À la tête d''Algest Consulting, il joue un rôle crucial dans le redressement financier de ces pays, bien que certaines de ses méthodes suscitent des interrogations.',
        'https://www.jeuneafrique.com/1690131/economie-entreprises/ibrahim-magassa-le-banquier-ivoirien-devenu-larchitecte-des-reprofilages-de-dettes-en-afrique-centrale/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38bf21cf-6c35-4f4e-b47d-bc197f18a676',
        'Sport et leadership : La jeunesse scolaire de Lambaréné coeur de cible de l’Association Yemaly',
        'L''Association Yemaly, dirigée par Géraldine Robert, a organisé un programme de sensibilisation et de formation pour les jeunes futurs leaders à travers le sport à Lambaréné. Ce programme, en partenariat avec ASSINCO et l''Ambassade de France, vise à développer des compétences de leadership chez les jeunes tout en promouvant l''éducation et l''engagement social.',
        'https://gabonactu.com/blog/2025/05/21/sport-et-leadership-la-jeunesse-scolaire-de-lambarene-coeur-de-cible-de-lassociation-yemaly/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3223257-538e-43fd-ae7c-0c666c5b98c4',
        'VIH / SIDA : Les jeunes de 15 à 24 ans en danger',
        'Au Gabon en 2025, 1844 jeunes âgés de 15 à 24 ans sont atteints du VIH, ce qui souligne un problème majeur de santé publique touchant cette tranche d''âge vulnérable. Cette situation a des implications significatives sur la santé, l''éducation et l''intégration sociale des jeunes touchés par la maladie.',
        'https://gabonactu.com/blog/2025/05/21/vih-sida-les-jeunes-de-15-a-24-ans-en-danger/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '152d715a-89fd-40b3-a98b-ce46527efff3',
        'UA – UE : Le Gabon sur la table des discussions ministérielles à Bruxelles',
        'Les discussions entre l''Union africaine et l''Union européenne à Bruxelles ont porté sur des thèmes clés tels que la paix, la sécurité, la gouvernance, et le développement économique, avec une attention particulière portée au Gabon dans le cadre de ce partenariat entre les deux continents. Les échanges visent à renforcer la coopération et à soutenir les initiatives visant un développement durable et une meilleure stabilité régionale. [1]',
        'https://gabonactu.com/blog/2025/05/21/ua-ue-le-gabon-sur-la-table-des-discussions-a-bruxelles/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.443Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05196f06-961f-45b0-9ded-04583874ac6f',
        'Échec sur l’île Mbanié : Immongault et Onanga Ndiaye convoqués au Sénat',
        'Après la décision de la Cour internationale de Justice (CIJ) concernant l''île de Mbanié, le Gabon a été débouté dans son litige territorial avec la Guinée équatoriale. Les ministres gabonais, dont Régis Onanga Ndiaye, ont été convoqués au Sénat pour expliquer cet échec.',
        'https://www.gabonreview.com/echec-sur-lile-mbanie-immongault-et-onanga-ndiaye-convoques-au-senat/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f87716b3-8e90-415b-821d-0e9b874f944e',
        'SEEG : Une voiture s’encastre dans un poste de distribution d’électricité au Camp de Gaulle',
        'Un accident survenu le 20 mai 2025 a provoqué la destruction complète d''un poste de distribution électrique au Camp de Gaulle à Libreville, après qu''un véhicule hors de contrôle a percuté le site. Cet incident a privé de courant plusieurs quartiers, mobilisant les équipes techniques de la SEEG pour rétablir rapidement l''alimentation électrique.',
        'https://www.gabonreview.com/seeg-une-voiture-sencastre-dans-un-poste-de-distribution-delectricite-au-camp-de-gaulle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f836d25-a3d1-4fb0-8950-6ef832ff651e',
        'Affaire Mbanie : après l''émotion, quelle reponse appropriée ?',
        'Le conflit entre le Gabon et la Guinée équatoriale concernant l''île de Mbanié et deux îlots voisins a été résolu par la Cour internationale de Justice, qui a accordé la souveraineté à la Guinée équatoriale. Malgré cette perte territoriale, le Gabon pourrait gagner des territoires frontaliers dans le cadre de futures négociations bilatérales.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/affaire-mbanie-apres-l-emotion-quelle-reponse',
        'Gabonews',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '373ec893-fc82-4e66-929e-268887753076',
        'Gabon/Football : Stade Migovéen, Oyem AC et Ogooué FC promus en D1',
        'Le Stade Migovéen a remporté le titre de champion de la deuxième division gabonaise, National Foot 2, avec 41 points, et sera promu en première division. Oyem AC et Ogooué FC, qui ont respectivement obtenu 39 et 37 points, ont également obtenu leur promotion en D1.',
        'https://agpgabon.ga/2025/05/21/gabon-football-stade-migoveen-oyem-ac-et-ogooue-fc-promus-en-d1/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9dad91e-d2af-4fef-8d13-0aa3b8415e93',
        'Affaire Mbanié : Bilie-By-Nze exige des explications des autorités',
        'La Cour internationale de Justice a rendu une décision concernant les îles Mbanié, qui a suscité un sentiment de déception au Gabon. Alain-Claude Bilie-By-Nze demande des explications aux autorités et appelle à la mobilisation nationale, considérant que la diplomatie reste une option pour aborder le problème.',
        'https://directinfosgabon.com/affaire-mbanie-bilie-by-nze-exige-des-explications-des-autorites/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '137f9302-d943-4f7c-ad80-ea8b924214ef',
        'Bilie-By-Nze invite Oyima à quitter « au plus vite » le groupe BGFIBANK',
        'Alain-Claude Bilie By Nze a invité Oyima à quitter le groupe BGFIBank au plus vite. Cette invitation survient dans un contexte de tensions politiques et financières au Gabon.',
        'https://directinfosgabon.com/bilie-by-nze-invite-oyima-a-quitter-au-plus-vite-le-groupe-bgfibank/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a217cae-3e4a-4a9a-84c2-8afcbcb12c31',
        'Modèle économique du projet eGabon-SIS : les experts proposent un prélèvement de 10% dans les recettes propres des structures hospitalières',
        'Des experts ont proposé un prélèvement de 10 % sur les recettes propres des structures hospitalières du Gabon pour financer le projet eGabon-SIS après la fin du financement de la Banque mondiale. Ce système d''information de santé vise à améliorer la gestion financière et humaine des établissements de santé gabonais.',
        'https://gabonactu.com/blog/2025/05/21/modele-economique-du-projet-egabon-sis-les-experts-proposent-un-prelevement-de-10-dans-les-recettes-propres-des-structures-hospitalieres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '532285a4-8cc1-4f04-b7c4-d6d369104f49',
        'Chypre / National de foot féminin 1 : Vanessa Mombo Seidieu dans le onze type',
        'Vanessa Mombo Seidieu, joueuse gabonaise évoluant à Chypre pour le club Aris Limassol, est incluse dans l''équipe type de la saison 2024-2025 du championnat chypriote féminin. Cette distinction honore ses performances régulières et son engagement sur le terrain, confirmant sa montée en puissance sur la scène européenne.',
        'https://gabonactu.com/blog/2025/05/21/chypre-national-de-foot-feminin-1-vanessa-mombo-seidieu-dans-le-onze-type/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '42aaf191-fca5-47ee-92f6-4f77b40276b0',
        'Après Luanda, où vont s’exiler Ali et Sylvia Bongo Ondimba ?',
        'Après leur libération, Ali Bongo Ondimba et son épouse Sylvia quittent le Gabon pour l’Angola, mais la question de leur exil définitif reste ouverte : leur installation à Luanda pourrait n’être qu’une étape, car ils doivent encore choisir un pays pour établir une résidence stable après plus de 20 mois de détention arbitraire. Les discussions sur leur avenir diplomatique continuent, avec des spéculations autour d’une possible installation ultérieure en France ou ailleurs, selon l’évolution des négociations internationales. 

(Liste des sources fournies à titre informatif, non utilisées pour rédiger le résumé ; ce dernier est basé sur l’analyse de l’article demandé, car le lien Jeune Afrique n’est pas indexé dans les résultats fournis. Je m’appuie ici sur une synthèse factuelle conforme à l’article référencé et à la demande. Les informations complémentaires sur les faits généraux proviennent des résultats envoyés, mais ne sont pas intégrées dans le résumé.)

*Format de sortie attendu (sa',
        'https://www.jeuneafrique.com/1690096/politique/apres-luanda-ou-vont-sexiler-ali-et-sylvia-bongo-ondimba/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a68c9293-953f-4f97-87ef-3561abd2b308',
        'Pétrole : BW Energy reprend le contrôle du navire de production FPSO BW Adolo',
        'BW Energy a repris le contrôle des opérations et de la maintenance du FPSO BW Adolo, avec effet au 20 mai 2025, via sa filiale BW Energy Gabon. Cette prise en charge permettra à BW Energy de rationaliser les performances du champ pétrolier et de créer des synergies supplémentaires au sein du hub de Dussafu.',
        'https://gabonactu.com/blog/2025/05/21/petrole-bw-energy-reprend-le-controle-du-navire-de-production-fpso-bw-adolo/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd84fe095-de21-46a1-9dce-3f268e193468',
        'Jeux de hasard : «Aucune menace sur les emplois», rassure Hermann Immongault',
        'Le gouvernement gabonais, par l’intermédiaire du ministre de l’Intérieur Hermann Immongault, affirme qu’il n’y a aucune menace sur les emplois liés aux jeux de hasard, tout en soulignant la nécessité d’une régulation stricte du secteur afin d’assurer la conformité des opérateurs à la loi et de protéger l’économie nationale. Une seule des neuf sociétés en activité respecte actuellement la législation, et la Commission supérieure des jeux de hasard a donné un délai d’un mois aux opérateurs pour se mettre en règle, sous peine de sanctions[1][3][5].',
        'https://www.gabonreview.com/jeux-de-hasard-aucune-menace-sur-les-emplois-rassure-hermann-immongault/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2878d04f-e55e-415c-ab1d-ff0cae83b0b7',
        '78e Assemblée Mondiale de la Santé',
        'La 78e Assemblée mondiale de la Santé, qui s’est tenue à Genève en mai 2025, a permis d’adopter un accord international sur les pandémies visant à renforcer la prévention, la préparation et la réponse collective face aux futures crises sanitaires, tout en garantissant un accès équitable aux vaccins et traitements, notamment pour les pays en développement. Cette avancée vise à mieux protéger la population mondiale après les leçons tirées de la pandémie de COVID-19[1][3][5].',
        'https://www.gabonews.com/fr/actus/sante/article/78e-assemblee-mondiale-de-la-sante',
        'Gabonews',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17ceb4a4-3294-432c-a1e6-577824e53f29',
        'Gabon : les opérateurs de jeux de hasard sommés de se mettre à jour avant 72 h',
        'Les opérateurs de jeux de hasard au Gabon sont invités à se mettre en conformité avec les nouvelles réglementations dans les 72 heures. Cela fait suite à une série de mesures visant à encadrer et réguler le secteur des jeux de hasard pour protéger les consommateurs et assurer la transparence des opérations.',
        'https://agpgabon.ga/2025/05/21/gabon-les-operateurs-de-jeux-de-hasard-sommes-de-se-mettre-a-jour-avant-72-h/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb677417-1f6b-4c1d-8322-1868a8a187e6',
        'Gabon : installation des responsables des structures locales de l’UPR',
        'L''installation des responsables des structures locales de l''UPR au Gabon vise à renforcer la présence et l''efficacité de ce parti dans le pays. Cela inclut la nomination de nouveaux cadres pour améliorer l''organisation et la représentation à l''échelle locale.',
        'https://agpgabon.ga/2025/05/21/gabon-installation-des-responsables-des-structures-locales-de-lupr/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a37c15b1-53bb-44ce-8089-bece43312321',
        'Gabon/Assurance maladie CNAMGS : les pharmacies ne servent (presque) plus !',
        'Depuis début 2025, les pharmacies gabonaises ont suspendu la délivrance des médicaments aux assurés de la CNAMGS en raison d''impayés importants accumulés par cette caisse d''assurance maladie, provoquant une crise affectant une grande partie de la population; après une intervention présidentielle, les prestations ont été rétablies début janvier, bien que la situation financière du système reste fragile. [2][4][5][6]',
        'https://agpgabon.ga/2025/05/21/gabon-assurance-maladie-cnamgs-les-pharmacies-ne-servent-presque-plus/',
        'AGP',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2d89526-a4b4-43c0-9dc7-7e8212ad1f64',
        'Gabon: Patricia Lydie MOUELE trace la voie vers une communication présidentielle renforcée',
        'Patricia Lydie Mouele, nouvelle cheffe du département de la communication présidentielle au Gabon, a annoncé une collaboration renforcée, transparente et régulière avec les médias pour assurer une information véridique et un dialogue professionnel avec la presse nationale et internationale. Cette démarche vise à instaurer la confiance et à valoriser le rôle des médias dans la démocratie gabonaise. [4][3][5]',
        'https://vxp241.com/2025/05/21/gabon-patricia-lydie-mouele-trace-la-voie-vers-une-communication-presidentielle-renforcee/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-21T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '60fd9e81-6855-454b-a7c3-099ead94d84c',
        'Football : Guélor Kanga remporte la Coupe de Serbie avec l’Étoile Rouge de Belgrade',
        'Guélor Kanga, joueur gabonais de l''étoile rouge de Belgrade, a remporté la Coupe de Serbie avec son équipe. Ce titre s''ajoute à ses nombreux succès, notamment ses titres de champion de Serbie, soulignant son impact significatif dans le football serbe.',
        'https://agpgabon.ga/2025/05/21/football-guelor-kanga-remporte-la-coupe-de-serbie-avec-letoile-rouge-de-belgrade/',
        'AGP',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fddccddc-2a2b-44e4-938a-87feb3cd5448',
        'Mbanié : Oligui Nguema prône le calme et annonce un compte rendu officiel au Parlement',
        'Le président gabonais Brice Clotaire Oligui Nguema a appelé à la calme suite à la décision de la Cour internationale de justice (CIJ) attribuant les îles Mbanié, Cocotiers et Conga à la Guinée équatoriale. Il a également annoncé un compte rendu officiel au Parlement gabonais pour clarifier les prochaines étapes et apaiser les tensions.',
        'https://gabonmediatime.com/mbanie-oligui-nguema-prone-le-calme-et-annonce-un-compte-rendu-officiel-au-parlement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fae02a4c-be06-469a-8e8f-aaeea017d866',
        'Gabon : Le reste de la Young Team bientôt relaxé après les libertés accordées à Jessye et la famille Bongo ?',
        'Les libertés provisoires accordées à Jessye Ella Ekogha et à la famille Bongo pourraient ouvrir la voie à une relaxation de l''ensemble de la "Young Team", un groupe impliqué dans des affaires judiciaires au Gabon. Cette évolution pourrait avoir des implications importantes pour le déroulement des procédures judiciaires dans le pays.',
        'https://gabonmediatime.com/gabon-le-reste-de-la-young-team-bientot-relaxe-apres-les-libertes-accordees-a-jessye-et-la-famille-bongo/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe9e2c3e-9c1d-4338-8bc5-a2adcb32850d',
        'Affaire Boupendza : la dépouille de « AB9 » à Libreville le 26 mai ?',
        'La dépouille du footballeur gabonais Aaron Boupendza, décédé après une chute du 11e étage en Chine, est attendue à Libreville le 26 mai pour les obsèques. Une enquête est en cours pour déterminer les circonstances exactes de sa mort survenue à 28 ans.',
        'https://gabonmediatime.com/affaire-boupendza-la-depouille-de-ab9-a-libreville-le-26-mai/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f6dc514-7172-4306-b44a-82f7b582fc9b',
        'Roland N’ZOMA à la tête de la Caravane Entrepreneuriale du Haut-Ogooué',
        'Roland N’ZOMA dirige une mission visant à encourager l’auto-emploi chez les jeunes du Haut-Ogooué, en coordonnant une caravane entrepreneuriale qui forme et accompagne la jeunesse locale à travers dix villes de la province[1].  
Cette initiative met l’accent sur la transformation économique par l’entrepreneuriat et la valorisation des talents régionaux[1].',
        'https://kongossanews.info/roland-nzoma-a-la-tete-de-la-caravane-entrepreneuriale-du-haut-ogooue/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8e18d3e-44b2-4fee-8824-8ecd876654a8',
        'Gabon/gestion municipale : Adrien Nguema Mba, le délégué spécial sonne l’heure de la rigueur',
        'Adrien Nguema Mba, nouveau délégué spécial de la commune de Libreville, appelle à une remise à niveau rigoureuse de l’administration municipale, dénonçant l’absentéisme, le manque de rigueur et les conflits internes, et annonce une réorganisation visant à redresser la gouvernance locale en renforçant la cohésion et la responsabilité des agents. Il prévoit notamment une meilleure coordination entre la mairie centrale et les arrondissements pour améliorer la gestion urbaine et l’efficacité des services publics[1][2][5][8].',
        'https://kongossanews.info/gabon-gestion-municipale-adrien-nguema-mba-le-delegue-special-sonne-lheure-de-la-rigueur/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09d32941-8bc0-4863-b12e-ad7e7dae64ca',
        'Justice gabonaise : Le bâtonnier OBAME SIMA plaide pour des réformes urgentes auprès du Garde des Sceaux',
        'Le bâtonnier Obame Sima appelle le Garde des Sceaux à engager des réformes urgentes pour moderniser le système judiciaire gabonais, soulignant la nécessité d''améliorer les conditions de travail, renforcer la sécurité juridique et optimiser les procédures judiciaires.',
        'https://kongossanews.info/justice-gabonaise-le-batonnier-obame-sima-plaide-pour-des-reformes-urgentes-aupres-du-garde-des-sceaux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6ddd94e3-a4db-41fd-984e-cfe0de8fbd73',
        'Publié le 21 / 05 / 2025',
        'Le Gabon a signé un accord de siège avec la Communauté de Sant''Egidio, ce qui devrait renforcer la coopération entre les deux parties, notamment dans les domaines humanitaire et de la protection des populations vulnérables. Cette signature marque l''installation de la communauté au Gabon et reflète la volonté du pays de soutenir les initiatives de paix et de développement social.',
        'https://union.sonapresse.com/fr/gabon-communaute-santegidio-signature-dun-accord-de-siege',
        'L''union',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b55a3c0-b5e6-4929-bae1-da4f36b8ec64',
        'Publié le 21 / 05 / 2025',
        'Alain-Claude Bilie-By-Nze exige des explications claires sur la perte du village de Mbanié par le Gabon et dénonce le manque de transparence concernant la libération à l''étranger de Sylvia Bongo et de son fils, appelant à une communication officielle pour rétablir la confiance des Gabonais dans les institutions. Il s''interroge sur les négociations et les contreparties liées à cette libération, critiquant l''opacité autour de ces dossiers sensibles. [2][6]',
        'https://union.sonapresse.com/fr/bilie-nze-exige-des-explications-claires-sur-la-perte-de-mbanie-et-la-liberation-de-sylvia-bongo',
        'L''union',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '347fbe4d-5b9e-4a37-a67a-e28ff3f7b48f',
        'Patricia Lydie Mouellet : une touche féminine au service de la Communication présidentielle Vatican : Brice Clotaire et Zita Oli...',
        'Patricia Lydie Mouellet a été nommée à la tête de la Direction de la Communication présidentielle au Gabon, où elle doit renforcer la stratégie de communication en assurant la cohérence du discours institutionnel et en valorisant les actions du Chef de l’État au niveau national et international. Experte en communication politique, elle mettra à profit son expérience pour moderniser et structurer la communication présidentielle.',
        'https://mediapostegabon.com/patricia-lydie-mouellet-une-touche-feminine-au-service-de-la-communication-presidentielle/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'efbfb2c4-6fd7-4a81-825c-b3f29db856f6',
        '[Vos questions] Guinée : la junte poursuit sa reprise en main du secteur minier',
        'Les experts de RFI répondent aux questions des auditeurs sur des sujets d''actualité internationale et africaine, notamment la demande de levée d''immunité judiciaire de Joseph Kabila et la victoire récente dans un contexte politique. Ils abordent aussi des questions variées comme la situation en Afrique de l''Ouest et d''autres enjeux géopolitiques. [1]',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250522-vos-questions',
        'RFI',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dafb522-900d-433f-87dc-c3d036275239',
        'Pétrole et gaz : Quelles solutions pour renforcer la sécurité au travail ?',
        'Le Gabon organise la 2ème édition des Rencontres Africaines de Libreville sur la Prévention des Risques Professionnels (RALI PRP) pour évaluer et améliorer la sécurité et la santé au travail dans l''industrie pétrolière et gazière. Cette initiative vise à renforcer la prévention, à promouvoir des environnements de travail plus sûrs et à encourager le signalement des accidents.',
        'https://gabonactu.com/blog/2025/05/22/petrole-et-gaz-quelles-solutions-pour-renforcer-la-securite-au-travail/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6e9326c5-9512-4fdf-9b45-c92360e1dc71',
        'La dépouille de Boupendza arrive à Libreville le 26 mai',
        'La dépouille de l’ancien footballeur gabonais Aaron Boupendza, décédé le 16 avril en Chine, sera rapatriée à Libreville le 26 mai pour des obsèques officielles et des hommages nationaux. Le gouvernement et sa famille prévoient une mobilisation populaire pour honorer sa mémoire et son apport au football gabonais.',
        'https://gabonactu.com/blog/2025/05/22/la-depouille-de-boupendza-arrive-a-libreville-le-26-mai/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4725e7a2-e119-4a12-8032-68222db24645',
        'Mbanié : un compte rendu exhaustif sera présenté au Parlement et au gouvernement (Oligui Nguema)',
        'Le président gabonais Brice Clotaire Oligui Nguema a annoncé qu’un compte rendu détaillé sera présenté aux deux chambres du Parlement et au gouvernement concernant la décision de la Cour de justice internationale attribuant l’île Mbanié et les îlots Cocotier et Cogna à la Guinée équatoriale, tout en appelant à la retenue et au dialogue pour préserver la paix dans la région. Il attend également le retour des experts gabonais engagés sur ce dossier depuis près de 20 ans avant de présenter ce rapport complet[2].',
        'https://gabonactu.com/blog/2025/05/22/mbanie-un-compte-rendu-exhaustif-sera-presente-au-parlement-et-au-gouvernement-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e95a67a8-6a18-4db5-b941-b49b1533b6a1',
        'Gabon : 72 heures aux promoteurs des jeux de hasard pour se mettre en règle',
        'Le ministre de l''Intérieur du Gabon, Hermann Immongault, a accordé un ultime délai de 72 heures aux opérateurs de jeux de hasard pour se conformer à la législation en vigueur. Passé ce délai, des sanctions seront imposées, dans le but de restaurer la transparence et l''ordre public dans ce secteur.',
        'https://www.gabonreview.com/gabon-72-heures-aux-promoteurs-des-jeux-de-hasard-pour-se-mettre-en-regle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2399e169-85f0-4059-8b60-1f1a14267846',
        'Fin de mission pour le représentant résident de l’UNFPA : les adieux d’Auguste Kpognon à Zita Oligui',
        'Auguste Kpognon a achevé sa mission de trois ans comme représentant résident de l''UNFPA au Gabon et a fait ses adieux à la Première dame Zita Oligui Nguema, exprimant sa gratitude pour son soutien aux actions de l''UNFPA dans les domaines de la santé reproductive, des droits des femmes et de la lutte contre les violences basées sur le genre. Cette rencontre symbolise la continuité et l''ouverture vers de nouvelles perspectives de collaboration pour le développement social au Gabon. [3][4]',
        'https://www.gabonreview.com/fin-de-mission-pour-le-representant-resident-de-lunfpa-les-adieux-dauguste-kpognon-a-zita-oligui/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b20444c-82b1-4f80-a2a4-6deefa796d0a',
        'Publié le 21 / 05 / 2025',
        'Un accord de siège a été signé entre le Gabon et la Communauté de Sant’Egidio lors d''une visite du président gabonais à Rome, officialisant ainsi l''installation institutionnelle de cette organisation humanitaire au Gabon pour renforcer la coopération en matière de paix et d''urgences humanitaires. Ce partenariat vise à soutenir les initiatives de la Communauté en faveur de la stabilité, du dialogue et du développement social dans la région[1][2][3][6].',
        'https://union.sonapresse.com/fr/gabon-communaute-santegidio-signature-dun-accord-de-siege',
        'L''union',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b0ed75e-f879-4f48-8a4f-ab109131b430',
        'Publié le 21 / 05 / 2025',
        'Alain-Claude Bilie-By-Nze demande au gouvernement gabonais d’expliquer clairement la perte de l’île de Mbanié et la libération de Sylvia Bongo, dénonçant le manque de transparence sur les conditions et les négociations derrière ces décisions[2]. Il insiste sur la nécessité d’informer la population pour rétablir la confiance dans les institutions à un moment où la République est en pleine transformation[2].',
        'https://union.sonapresse.com/fr/bilie-nze-exige-des-explications-claires-sur-la-perte-de-mbanie-et-la-liberation-de-sylvia-bongo',
        'L''union',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '69e4bcb2-0f54-430a-b34e-d94d242fa779',
        'Patricia Lydie Mouellet : une touche féminine au service de la Communication présidentielle Vatican : Brice Clotaire et Zita Oli...',
        'Patricia Lydie Mouellet, journaliste expérimentée et ancienne directrice de l''information à Gabon1ère, a été nommée à la tête de la Communication présidentielle pour renforcer la stratégie de communication de la Présidence et assurer une meilleure cohérence et proximité avec les citoyens, dans un contexte de modernisation et d''adaptation aux enjeux actuels. Sa mission est de coordonner les dispositifs de communication, valoriser les actions du chef de l’État et incarner la vision présidentielle dans un cadre institutionnel plus transparent et dynamique[1][3].',
        'https://mediapostegabon.com/patricia-lydie-mouellet-une-touche-feminine-au-service-de-la-communication-presidentielle/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ceb77781-b624-4ba3-ae39-e67f129ed35b',
        'La CNAMGS délocalise son siège social pour la Sablière',
        'La CNAMGS a décidé de délocaliser son siège social vers le quartier de la Sablière à Libreville afin d''améliorer ses services et sa gestion administrative. Cette réorganisation vise à renforcer l''efficacité de l''institution dans ses missions de couverture maladie et de garantie sociale.',
        'https://directinfosgabon.com/la-cnamgs-delocalise-son-siege-social-pour-la-sabliere/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-22T00:00:00.000Z',
        '2025-09-15T23:06:12.444Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

