-- Batch 5 - Section 3/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '1dfdbbe2-aa10-4251-b093-154884c1c987',
        'Deux potes mineurs écopent de 5 ans et 10 ans de prison pour homicide volontaire à Port-Gentil',
        'Deux mineurs ont été condamnés à 5 et 10 ans de prison pour avoir commis un braquage ayant entraîné la mort d''une personne à Port-Gentil.',
        'https://gabonactu.com/blog/2025/06/25/deux-potes-mineurs-ecopent-de-5-ans-et-10-ans-de-prison-pour-homicide-volontaire-a-port-gentil/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48803621-ed6b-4f63-aba4-e7d6d1d4cf44',
        'L’association  »Les enfants de la balise » se lance pour améliorer son environnement communautaire',
        'Une nouvelle association appelée « Les enfants de la Balise » a été lancée à Port-Gentil pour améliorer l’environnement communautaire du quartier Canal Évasion.',
        'https://gabonactu.com/blog/2025/06/25/lassociation-les-enfants-de-la-balise-se-lance-pour-ameliorer-son-environnement-communautaire/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35a56342-804f-45de-9903-de9a48fba3a9',
        'L’assemblée générale constitutive du parti ‘’Les Bâtisseurs’’ reportée au 05 juillet 2025',
        'La création du parti Les Bâtisseurs a été reportée au 5 juillet 2025, selon une décision liée à la préparation de l’assemblée générale constitutive.',
        'https://gabonactu.com/blog/2025/06/25/lassemblee-generale-constitutive-du-parti-les-batisseurs-reportee-au-05-juillet-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1400d0f-e824-48e4-b2c7-0ebb2c6584f1',
        'Et si la Terre n’avait pas de poumons ?',
        'L’idée que les forêts sont les « poumons de la Terre » est une métaphore simplifiée qui risque de nuire à la compréhension réelle de l’écologie, car elle peut conduire à une vision erronée des enjeux environnementaux.',
        'https://www.gabonreview.com/et-si-la-terre-navait-pas-de-poumons/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb9be335-112d-4ddc-a101-0b63014a7290',
        'Franceville : les commerçantes célébrées comme piliers de la Transition',
        'Les commerçantes de Franceville ont été honorées lors d''une cérémonie pour reconnaître leur rôle essentiel dans la transition économique de la région.',
        'https://www.gabonreview.com/franceville-les-commercantes-celebrees-comme-piliers-de-la-transition/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2265ae6-9f67-4b83-aae3-5acbdc93f1ba',
        'Coopération : Le Royaume-Uni veut intensifier ses investissements au Gabon',
        'Le Royaume-Uni souhaite renforcer ses investissements au Gabon pour accompagner le développement économique du pays, qui cherche à accélérer sa croissance en multipliant les partenariats dans ses secteurs prioritaires.',
        'https://www.gabonreview.com/cooperation-le-royaume-uni-veut-intensifier-ses-investissements-au-gabon/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e221c62-bf40-406e-8175-d9d87b3b28b9',
        'La Fondation Marcel Doupamby Matoka fait oeuvre utile à Fougamou',
        'La Fondation Marcel Doupamby Matoka, avec le soutien de la Fondation Omar Bongo Ondimba, a offert des kits à des femmes enceintes lors d''une cérémonie à Fougamou, pour soutenir la santé maternelle dans la région.',
        'https://www.gabonews.com/fr/actus/social/article/la-fondation-marcel-doupamby-matoka-fait-oeuvre',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2fdd461-46d0-4cf6-a51a-b17c9414c8f9',
        'Gabon : gestion post-déguerpissement à Libreville',
        'Trois membres du gouvernement ont supervisé à Libreville la mise en œuvre d’un plan d’urgence pour la gestion des déchets post-déguerpissement, conformément aux instructions officielles.',
        'https://agpgabon.ga/gabon-gestion-post-deguerpissement-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'acc04fef-e595-4520-83f3-5052c492ac8b',
        'Métiers du ferroviaire : Eramet et Setrag forment 15 jeunes Gabonais',
        '15 jeunes Gabonais ont obtenu une formation dans les métiers du ferroviaire grâce au programme « Tremplin », une initiative conjointe de SETRAG et d’Eramet, lancée en mars 2024.',
        'https://directinfosgabon.com/metiers-du-ferroviaire-eramet-et-setrag-forment-15-jeunes-gabonais/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0732ccec-eac8-4d38-805e-f55301740ea4',
        'Guy Nzouba Ndama : « Démocrate » ou « Tyran » ?',
        'Un message vocal attribué à l''ancien président de l''Assemblée nationale, Guy Nzouba Ndama, suscite la controverse en raison de son ton de ralliement politique perçu comme ambigu, alimentant le débat sur sa nature démocratique ou tyrannique.',
        'https://gabonactu.com/blog/2025/06/25/guy-nzouba-ndama-democrate-ou-tyran/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5a8532b-1427-40b9-9791-f2a7bdbe1156',
        'Coopération éducative : vers l’introduction du mandarin dans le système scolaire gabonais',
        'Le Gabon prévoit d’introduire l’apprentissage du mandarin dans son système scolaire grâce à une coopération avec la Chine, notamment via l’Institut Confucius, afin de renforcer ses échanges éducatifs bilatéraux.',
        'https://gabonactu.com/blog/2025/06/25/cooperation-educative-vers-lintroduction-du-mandarin-dans-le-systeme-scolaire-gabonais/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f26455a-24b1-45b1-a95d-24a3fb123061',
        'Un manuel scolaire pour valoriser et célébrer la gastronomie gabonaise',
        'Un nouveau manuel scolaire a été présenté à la ministre de l’Éducation nationale pour valoriser la richesse de la gastronomie gabonaise et la faire connaître aux jeunes.',
        'https://gabonactu.com/blog/2025/06/25/un-manuel-scolaire-pour-valoriser-et-celebrer-la-gastronomie-gabonaise/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '02a1f451-a017-4bef-a4d7-3d99094d0024',
        'Justice et droits humains : Akure-Davain face aux réalités du système pénitentiaire',
        'Le ministre de la Justice a constaté sur le terrain que, malgré ses efforts de réforme, le système pénitentiaire à Libreville fait face à des défis comme la surpopulation, des conditions de détention difficiles et des lenteurs dans la justice.',
        'https://www.gabonreview.com/justice-et-droits-humains-akure-davain-face-aux-realites-du-systeme-penitentiaire/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f941454-36c2-462f-912b-3adc7b1c364f',
        'Cybersécurité : le Président Oligui Nguema mise sur la jeunesse gabonaise avec un ambitieux programme de formation',
        'Le président Oligui Nguema a rencontré des responsables d''une entreprise américaine pour lancer une formation en cybersécurité destinée à 1000 jeunes Gabonais, offrant ainsi de nouvelles opportunités pour la jeunesse du pays.',
        'https://www.gabonews.com/fr/actus/economie-numerique/article/cybersecurite-le-president-oligui-nguema-mise-sur',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ace8b797-0298-4390-a0dc-d69a49bbef4a',
        'Gabon/Royaume-Uni : vers une intensification des investissements britanniques',
        'Une délégation de chefs d''entreprise britanniques a rencontré les autorités gabonaises pour renforcer les investissements du Royaume-Uni dans plusieurs secteurs clés du pays, soutenant ainsi la stratégie de développement nationale.',
        'https://agpgabon.ga/gabon-royaume-uni-vers-une-intensification-des-investissements-britanniques/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db97125d-7280-4f56-9ec8-6533c7e61575',
        'Tennis de table/championnat d’Afrique Centrale : départ des sélections nationales du Gabon ce mercredi',
        'Les équipes nationales masculines et féminines de tennis de table du Gabon ont quitté Libreville pour participer au Championnat d’Afrique centrale à Brazzaville, du 27 au 29 juin 2025, avec le soutien de plusieurs partenaires.',
        'https://agpgabon.ga/tennis-de-table-championnat-dafrique-centrale-depart-des-selections-nationales-du-gabon-ce-mercredi/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc791524-94cb-4fd2-b871-83a16f0d7e7a',
        'Gabon/Transformation minière : la CSTG répond aux réserves d’Eramet',
        'La Confédération Syndicale des Travailleurs du Gabon soutient la décision du gouvernement d’interdire l’exportation du minerai de manganèse brut dès 2029, en répondant aux réserves exprimées par Eramet sur la capacité de transformation locale.',
        'https://agpgabon.ga/gabon-transformation-miniere-la-cstg-repond-aux-reserves-deramet/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '808eec3e-029a-48d8-bc41-9d801bb422b6',
        'Justine Mintsa à l’honneur des 25 ans de “Continents Noirs”',
        'Le 25 juin au Maroc, l’écrivaine gabonaise Justine Mintsa a été honorée par les éditions Gallimard à l’occasion du 25e anniversaire de leur collection « Continents Noirs », qui célèbre la littérature africaine.',
        'https://gabonactu.com/blog/2025/06/25/justine-mintsa-a-lhonneur-des-25-ans-de-continents-noirs/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e58cbafa-59e1-4461-91e1-7b9978d28902',
        'Cybersécurité : Cybastion annonce la formation de 1000 Gabonais et la construction d’un datacenter national',
        'Cybastion prévoit de former 1 000 jeunes Gabonais à la cybersécurité et de construire un datacenter national pour renforcer la sécurité informatique du pays.',
        'https://gabonactu.com/blog/2025/06/25/cybersecurite-cybastion-annonce-la-formation-de-1000-gabonais-et-la-construction-dun-datacenter-national/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc2bca47-35ca-4801-85f4-e734bd689a29',
        'Gabon : la loi de finances 2026 déjà en préparation à l’Assemblée nationale',
        'Le gouvernement gabonais travaille déjà sur la loi de finances pour 2026, qui est en cours de préparation à l''Assemblée nationale.',
        'https://gabonmediatime.com/gabon-la-loi-de-finances-2026-deja-en-preparation-a-lassemblee-nationale/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55df56ee-f4ee-4e6d-b9b5-a4a16a8a869b',
        'Gabon : Michel Ongoundou dénonce « une reconstruction sournoise du parti unique » sous Oligui Nguema !',
        'Michel Onguendou dénonce la reconstruction peu sincère du parti unique sous la direction de Nguema, qui menace la démocratie au Gabon.',
        'https://gabonmediatime.com/gabon-michel-ongoundou-denonce-une-reconstruction-sournoise-du-parti-unique-sous-oligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf88bc40-7752-43a9-9f57-e5a856ca08f3',
        'Gabon : le patronat français pour un développement des filières porteuses',
        'Le territoire gabonais cherche à développer ses filières porteuses en s’appuyant sur la coopération avec des partenaires français pour favoriser la croissance économique et la formation.',
        'https://gabonmediatime.com/gabon-le-patronat-francais-pour-un-developpement-des-filieres-porteuses/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4a046109-aa6d-4af6-b95e-d8dd0cb9d5f5',
        'AAM2025 : Afreximbank célèbre son retour à Abuja pour une Afrique résiliente et souveraine',
        'La 32ᵉ Assemblée annuelle de la Banque Africaine d’Import-Export s’est tenue à Abuja, marquant le retour de l’institution dans cette capitale après 32 ans, dans un contexte mondial d’instabilité et de tensions géopolitiques, avec pour objectif de bâtir un avenir résilient et souverain pour l’Afrique.',
        'https://agpgabon.ga/aam2025-afreximbank-celebre-son-retour-a-abuja-pour-une-afrique-resiliente-et-souveraine/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca68480f-471d-43ed-a4e2-c0935e7a54e0',
        'AAM2025/Afreximbank : la communication au cœur de la mission panafricaine de la Banque',
        'Plus de 150 journalistes de 40 pays couvrent l’Assemblée annuelle d’Afreximbank à Abuja, où l’accent est mis sur la communication et la sensibilisation au sein de la mission panafricaine de la banque.',
        'https://agpgabon.ga/aam2025-afreximbank-la-communication-au-coeur-de-la-mission-panafricaine-de-la-banque/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '84ac2d3c-0735-422b-b8ed-fe36f927871e',
        'Banques : BGFIBank Gabon participe, ce 25 juin 2025 à Paris, à la certification MSI 2000',
        'Le 25 juin 2025, BGFIBank Gabon a participé à Paris à une cérémonie de certification MSI 2000 pour renouveler sa certification précédente, organisée par Euronext, avec des représentants de la banque présents.',
        'https://agpgabon.ga/banques-bgfibank-gabon-participe-ce-25-juin-2025-a-paris-a-la-certification-msi-2000/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc64ced2-2f73-4152-a9e1-55e6ad99fe6a',
        'Défense et Sécurité : Le Chef de l''État prend part à l''exercice tactique "Ukal Dimbu 2025"',
        'Le président Brice Clotaire Oligui Nguema a participé à un exercice tactique militaire appelé "Ukal Dimbu 2025" pour renforcer la préparation et la capacité de réaction des forces de défense.',
        'https://www.gabonews.com/fr/actus/securite-207/article/defense-et-securite-le-chef-de-l-etat-prend-part',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1348d08d-d7e6-44cf-9235-ecc372411818',
        'Le Président de la République s''entretient avec ses homologues botswanais et namibien',
        'Lors du 17ᵉ Sommet des Affaires États-Unis – Afrique, le président gabonais a rencontré ses homologues du Botswana et de la Namibie pour discuter des progrès de ces pays en matière de développement.',
        'https://www.gabonews.com/fr/actus/politique/article/le-president-de-la-republique-s-entretient-avec',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c0ea1a3-f8cc-442a-b288-2f68157ede0e',
        'Le Président Oligui Nguema renforce les liens avec la communauté gabonaise en Angola',
        'Le Président Oligui Nguema a rencontré la diaspora gabonaise en Angola pour renforcer les liens et montrer son ouverture envers ses compatriotes à l’étranger.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-president-oligui-nguema-renforce-les-liens',
        'Gabonews',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e8aece9-8929-42bf-8728-9cd412ab73e8',
        'Gabon : la loi de finances 2026 déjà en préparation à l’Assemblée nationale',
        'Le projet de loi de finances 2026 du Gabon est déjà en préparation à l''Assemblée nationale, anticipant les mesures budgétaires du pays pour cette année.',
        'https://gabonmediatime.com/gabon-la-loi-de-finances-2026-deja-en-preparation-a-lassemblee-nationale/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6946886-d6a1-4dd4-a4f2-7152cdda2a98',
        'Gabon : Michel Ongoundou dénonce « une reconstruction sournoise du parti unique » sous Oligui Nguema !',
        'Michel Ongoundou critique la reconstruction jugée biaisée du parti unique en Guinée équatoriale, dénonçant un processus sous influence du pouvoir en place.',
        'https://gabonmediatime.com/gabon-michel-ongoundou-denonce-une-reconstruction-sournoise-du-parti-unique-sous-oligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3bdf7d14-59a4-4078-9448-31d36d09785c',
        'Gabon : le patronat français pour un développement des filières porteuses',
        'Le patronat français soutient le développement des filières porteuses à Gabon, favorisant ainsi leur croissance économique et l’amélioration des compétences locales.',
        'https://gabonmediatime.com/gabon-le-patronat-francais-pour-un-developpement-des-filieres-porteuses/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2bf03ada-2845-414f-982d-6d738bea6533',
        'Football : Denis Bouanga, premier buteur gabonais au mondial des clubs',
        'Denis Bouanga est devenu le premier joueur gabonais à marquer lors d''une Coupe du monde des clubs, en inscrivant un but lors du match opposant Los Angeles FC à Flamengo.',
        'https://agpgabon.ga/football-denis-bouanga-premier-buteur-gabonais-au-mondial-des-clubs/',
        'AGP',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.461Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7dc75796-9f55-4ec4-b497-bcde705720af',
        'Gabon Digital: la Transformation digitale de l’état civil et de l’identification au coeur des réflexions',
        'La digitalisation de l’administration au Gabon entame une nouvelle étape avec l''élaboration d''une feuille de route visant à renforcer la gestion identitaire et l''efficacité des services publics.',
        'https://vxp241.com/2025/06/25/gabon-digital-la-transformation-digitale-de-letat-civil-et-de-lidentification-au-coeur-des-reflexions/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-25T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a538697-5611-40fd-82a7-bfbb96dbf354',
        'Le Bloc Démocratique Chrétien installe la coordination du 5e arrondissement',
        'Le Bloc Démocratique Chrétien a installé une nouvelle coordination dans le 5e arrondissement pour renforcer ses activités politiques dans cette zone.',
        'https://kongossanews.info/le-bloc-democratique-chretien-installe-la-coordination-du-5e-arrondissement/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9489dc78-0e5e-4815-bffb-ee0cf55934d7',
        'Evrard Moumbeki : l’éclat d’un parcours d’excellence en expertise comptable',
        'Evrard Moumbeki incarne un parcours de résilience et d''excellence dans le domaine de l''expertise comptable, démontrant comment la détermination peut conduire à la réussite malgré les défis.',
        'https://kongossanews.info/evrard-moumbeki-leclat-dun-parcours-de-resilience-et-dexcellence-en-expertise-comptable/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '966a2974-d4bb-4866-acac-ea1cca21cc0e',
        'Gabon : Liste des nominations au sein du Conseil consultatif des Sages du PDG',
        'Une liste des personnes nommées au sein du Comité Consultatif des Sages du Parti Démocratique Gabonais (PDG) a été publiée, détaillant les nominations par région.',
        'https://agpgabon.ga/gabon-liste-des-nominations-au-sein-du-comite-consultatif-du-pdg/',
        'AGP',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3129a54-83f6-4a6a-b2e8-9dd5775b0fcd',
        'Pétrole : nouvelle dynamique entre le Gabon et Valco Energy',
        'Le secteur pétrolier gabonais se redynamise grâce à un partenariat renforcé avec la société américaine Valco Energy, visant à soutenir le développement stratégique de l''industrie extractive dans le pays.',
        'https://agpgabon.ga/petrole-nouvelle-dynamique-entre-le-gabon-et-valco-energy/',
        'AGP',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86a3a698-7236-4cf0-9fb7-521927e749ad',
        'Gabon/Coopération régionale : ENDA CACID en atelier à Libreville',
        'Un atelier sous-régional à Libreville a réuni des acteurs pour élaborer une feuille de route en faveur d''une transition écologique, commerciale et énergétique plus durable en Afrique centrale, en tirant profit de la zone de libre-échange continentale.',
        'https://agpgabon.ga/gabon-cooperation-regionale-enda-cacid-en-atelier-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31b3f83f-537c-48a9-ab23-5ad8efc9c865',
        'Bilie By Nze lance la campagne d’adhésion à son parti',
        'Alain Claude Bilie By Nze a lancé une campagne pour inviter les citoyens à rejoindre son parti politique.',
        'https://gabonactu.com/blog/2025/06/26/bilie-by-nze-lance-la-campagne-dadhesion-a-son-parti/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7cc35858-92df-4332-a846-64cbff9d6828',
        'Ensemble Pour le Gabon : Les adhésions sont ouvertes',
        'L''ancien candidat à la présidentielle, Alain-Claude Bilie-By-Nzé, a lancé officiellement la campagne d’adhésion à son parti politique, Ensemble Pour le Gabon (EPG).',
        'https://gabonactu.com/blog/2025/06/26/ensemble-pour-le-gabon-les-adhesions-sont-ouvertes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f90755a-d4e3-4281-855e-0831fab7d9c7',
        'Oligui Nguema dans un champ de tir avec ses hommes',
        'Oligui Nguema et ses hommes ont participé à une séance d''entraînement au tir dans un champ, renforçant leur préparation militaire.',
        'https://gabonactu.com/blog/2025/06/26/oligui-nguema-dans-un-champ-de-tir-avec-ses-hommes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51150522-e716-4aca-b81d-786956e69370',
        'Le Bloc Démocratique Chrétien installe la coordination du 5e arrondissement',
        'Le Bloc Démocratique Chrétien a installé la coordination du 5e arrondissement pour renforcer son organisation et mieux défendre ses valeurs au sein de la commune.',
        'https://kongossanews.info/le-bloc-democratique-chretien-installe-la-coordination-du-5e-arrondissement/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd50e1e2-c90c-484b-b023-b02dad15db80',
        'Evrard Moumbeki : l’éclat d’un parcours d’excellence en expertise comptable',
        'Evrard Moumbeki incarne un parcours exemplaire de résilience et d''excellence dans le domaine de l''expertise comptable, illustrant comment la détermination peut conduire au succès malgré les défis.',
        'https://kongossanews.info/evrard-moumbeki-leclat-dun-parcours-de-resilience-et-dexcellence-en-expertise-comptable/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '495ac497-0aa2-4155-925e-6e4f189e959c',
        'Publié le 25 / 06 / 2025',
        'Le texte traite des tensions et des défis liés à la politique et à l''économie en Côte d''Ivoire, soulignant une période de contestation et de changements importants pour le pays.',
        'https://union.sonapresse.com/fr/ld-branle-bas-de-combat-en-perspective',
        'L''union',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '963ecf0c-ff11-4d12-b84c-468bac94fae8',
        'Publié le 25 / 06 / 2025',
        'La création du parti politique des Bâtisseurs en Côte d''Ivoire a été reportée au 5 juillet pour permettre la finalisation de ses démarches administratives et organisationnelles.',
        'https://union.sonapresse.com/fr/parti-politique-des-batisseurs-lag-constitutive-reportee-au-5-juillet-prochain',
        'L''union',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'afd54c63-8dae-4511-8b6c-da2d3a41f306',
        'Publié le 25 / 06 / 2025',
        'Le président équatoguinéen a rencontré deux responsables lors du 17e sommet des affaires États-Unis-Afrique pour discuter de collaborations économiques et de projets de développement.',
        'https://union.sonapresse.com/fr/en-marge-du-17e-sommet-des-affaires-etats-unis-afrique-oligui-nguema-sentretient-avec-deux-de-ses',
        'L''union',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4fb527a-39c4-41c2-83d9-a923674b09e2',
        'BGFI Holding Corporation va mettre 10 % de son capital en bourse à compter du 15 juillet 2025',
        'BGFI Holding Corporation prévoit d’introduire 10 % de son capital en bourse à partir du 15 juillet 2025, suite à une Assemblée Générale Extraordinaire où cette décision a été adoptée.',
        'https://directinfosgabon.com/bgfi-holding-corporation-va-mettre-10-de-son-capital-en-bourse-a-compter-du-15-juillet-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ea268f7c-4304-4ad7-8f1f-2e9fc7385eee',
        'Hydrocarbures : VAALCO a versé près de 100 milliards de FCFA au Gabon en 2024',
        'En 2024, la société américaine Vaalco Energy a versé près de 100 milliards de FCFA aux autorités gabonaises pour ses activités dans le secteur des hydrocarbures.',
        'https://directinfosgabon.com/hydrocarbures-vaalco-a-verse-pres-de-100-milliards-de-fcfa-au-gabon-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91d655bb-0bb3-4726-862b-60f00499e962',
        '430 milliards FCFA pour les banques de la CEMAC :  Une bouffée d’oxygène pour le Gabon',
        'La Banque des États de l’Afrique centrale a augmenté son offre hebdomadaire de liquidités à 430 milliards FCFA, ce qui aide les banques de la CEMAC, notamment celles du Gabon, à mieux faire face à une forte demande de financement.',
        'https://directinfosgabon.com/430-milliards-fcfa-pour-les-banques-de-la-cemac-une-bouffee-doxygene-pour-le-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aa47ab62-1b7b-455d-af8f-b94d66005cb0',
        'Centrafrique : une explosion endeuille les épreuves du baccalauréat à Bangui',
        'Une explosion causée par un problème électrique lors du baccalauréat à Bangui a provoqué la panique parmi près de 6 000 candidats et fait une dizaine de morts.',
        'https://agpgabon.ga/centrafrique-une-explosion-endeuille-les-epreuves-du-baccalaureat-a-bangui/',
        'AGP',
        'Business Intelligence',
        '2025-06-26T00:00:00.000Z',
        '2025-09-15T23:06:12.462Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

