-- Batch 2 - Section 9/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '599bbac5-f3b7-4aca-832d-b3abdf908ada',
        'Oligui Président : Après l’euphorie, la réalité du quotidien',
        'Après l''euphorie de l''arrivée au pouvoir du président Oligui, les Gabonais font face aux défis quotidiens, notamment économiques et sociaux, qui persistent malgré le changement de régime.',
        'https://directinfosgabon.com/oligui-president-apres-leuphorie-la-realite-du-quotidien/',
        'Direct Infos Gabon',
        'Services, Éducation, Finances, Agriculture',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95f34970-0d29-408c-be1d-2dba9091a5b6',
        'Tourisme : Un potentiel économique encore largement inexploité',
        'Le Gabon possède un important potentiel touristique grâce à sa biodiversité et ses paysages variés, mais ce secteur reste sous-exploité en raison d’infrastructures insuffisantes et d’un manque de promotion. Une meilleure organisation et des investissements pourraient en faire un pilier économique pour le pays.',
        'https://directinfosgabon.com/tourisme-un-potentiel-economique-encore-largement-inexploite/',
        'Direct Infos Gabon',
        'Tourisme, Services, Numérique / Digital',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7304882-9129-43c8-9a45-a71d72960132',
        'Pétrole : La GOC à la recherche de prestataires pour ses sites d’exploitation',
        'La Gabon Oil Company (GOC) recherche des prestataires pour assurer la maintenance et les services logistiques sur ses sites pétroliers, dans le cadre du renforcement de ses activités d''exploitation. Cette initiative vise à optimiser les opérations tout en favorisant la participation des entreprises locales.',
        'https://directinfosgabon.com/petrole-la-goc-a-la-recherche-de-prestataires-pour-ses-sites-dexploitation/',
        'Direct Infos Gabon',
        'Services, Commerce',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '99fa5140-d7b6-4d0f-9a9f-848547224260',
        'Gabon: deuxième, Bilie-By-Nze critique une présidentielle «opaque» mais ne saisira pas la Cour constitutionnelle',
        'Le deuxième candidat à l''élection présidentielle gabonaise, Billie By Nze, dénonce un scrutin opaque mais renonce à saisir la Cour constitutionnelle, estimant que cette démarche serait inutile.',
        'https://www.rfi.fr/fr/afrique/20250414-gabon-deuxi%C3%A8me-bilie-by-nze-critique-une-pr%C3%A9sidentielle-opaque-mais-ne-saisira-pas-la-cour-constitutionnelle',
        'RFI',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0f0c9c6-01d1-413f-9e18-cad969e79b50',
        'Gabon: deuxième, Bilie-By-Nze critique une présidentielle «opaque» mais ne saisira pas la Cour constitutionnelle',
        'Le deuxième candidat à l''élection présidentielle gabonaise, Billie By Nze, dénonce un scrutin opaque mais renonce à saisir la Cour constitutionnelle, estimant que cela ne changerait pas le résultat.',
        'https://www.rfi.fr/fr/afrique/20250414-gabon-deuxi%C3%A8me-bilie-by-nze-critique-une-pr%C3%A9sidentielle-opaque-mais-ne-saisira-pas-la-cour-constitutionnelle?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bf3d086-8b3e-43c5-a6c5-52d265cdec9d',
        'Présidentielle 2025 : le ROC salue la transparence du scrutin tout en recommandant des améliorations',
        'Le ROC a reconnu la transparence des élections présidentielles de 2025 au Gabon, tout en suggérant des améliorations pour renforcer davantage le processus démocratique.',
        'https://gabonactu.com/blog/2025/04/14/presidentielle-2025-le-roc-salue-la-transparence-du-scrutin-tout-en-recommandant-des-ameliorations/',
        'Gabon Actu',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd5ae354-ae3f-4f78-a17e-a5951411eaf1',
        '«Brice Oligui Nguema, le président le plus légitime… de sa propre imagination», ironise le Pr Mengara',
        'Brice Oligui Nguéma se présente comme le président le plus légitime du Gabon, mais le professeur Mengara ironise sur cette autoproclamation, suggérant qu''elle relève davantage de son imagination que d''une réalité politique acceptée.',
        'https://www.gabonreview.com/brice-oligui-nguema-le-president-le-plus-legitime-de-sa-propre-imagination-ironise-le-pr-mengara/',
        'Gabon Review',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4e8651a4-00e7-46af-9fb1-919ef9fefe70',
        'Gabon : qui est Brice Oligui Nguema, élu avec plus de 90% des voix ?',
        'Brice Oligui Nguéma, chef de la junte au pouvoir au Gabon, a été élu président avec plus de 90 % des voix lors d''un scrutin organisé par le régime militaire, marquant une transition controversée après le coup d''État qui a renversé Ali Bongo.',
        'https://www.france24.com/fr/vid%C3%A9o/20250414-gabon-qui-est-brice-oligui-nguema-%C3%A9lu-avec-plus-de-90-des-voix?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91317ea7-8074-46c5-a2b3-7c91c65ba12d',
        'Gabon : qui est Brice Oligui Nguema, élu avec plus de 90% des voix ?',
        'Brice Oligui Nguema, chef de la junte militaire au pouvoir depuis le coup d''État d''août 2023, a été élu président du Gabon avec plus de 90 % des voix lors d''une élection organisée par le régime. Cette victoire, contestée par l''opposition, consolide son pouvoir après la destitution d''Ali Bongo.',
        'https://www.france24.com/fr/vid%C3%A9o/20250414-gabon-qui-est-brice-oligui-nguema-%C3%A9lu-avec-plus-de-90-des-voix',
        'France 24',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b6118c3-a525-447b-b8cc-016ea471d902',
        '« Ce 90,35% ce sont des problèmes des gabonais que nous devons résoudre sur les 7 ans » (Oligui Nguema)',
        'Le président gabonais Oligui Nguema souligne que les 9 035 problèmes identifiés par les citoyens doivent être résolus dans les sept prochaines années, mettant l''accent sur les priorités locales. Il appelle à une mobilisation collective pour améliorer les conditions de vie des Gabonais.',
        'https://gabonactu.com/blog/2025/04/14/ce-9035-ce-sont-des-problemes-des-gabonais-que-nous-devons-resoudre-sur-les-7-ans-oligui-nguema/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation, Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0297840-3811-4d5a-8f9f-ca9c3ad32f80',
        'Gabon : Oligui Nguema défend son entourage fait d’«anciens»',
        'Le général Oligui Nguema justifie la présence d’anciens proches de Bongo dans son entourage, affirmant qu’ils apportent leur expérience pour la stabilité du Gabon. Il souligne que ces choix visent à éviter les ruptures brutales et à favoriser une transition inclusive.',
        'https://www.gabonreview.com/gabon-oligui-nguema-defend-son-entourage-fait-danciens/',
        'Gabon Review',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10a8c37b-c94b-4cdd-be0c-b825d80236ff',
        'Port-Gentil/ La victoire dans le calme',
        'À Port-Gentil, les élections se sont déroulées dans le calme, avec une victoire marquée par une atmosphère paisible et sans incidents majeurs.',
        'https://www.gabonews.com/fr/actus/politique/article/port-gentil-la-victoire-dans-le-calme',
        'Gabonews',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'efc937bd-921e-44ea-8729-d912e2c29ad0',
        'Présidentielles au Gabon: «Le scrutin était ouvert, mais pas compétitif», estime le chercheur Bergès Miétté',
        'L''élection présidentielle au Gabon était ouverte à plusieurs candidats, mais selon le chercheur Bergès Mietté, elle manquait de compétitivité réelle en raison des déséquilibres structurels et des inégalités de campagne.',
        'https://www.rfi.fr/fr/podcasts/invit%C3%A9-afrique-midi/20250414-pr%C3%A9sidentielles-au-gabon-le-scrutin-%C3%A9tait-ouvert-mais-pas-comp%C3%A9titif-estime-le-chercheur-berg%C3%A8s-mi%C3%A9tt%C3%A9',
        'RFI',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2393560-0497-47fc-b935-14d31342d8db',
        'Gabon : l’élection d’Oligui Nguema nourrit l’espoir d’un nouveau départ',
        'L''élection d''Oligui Nguéma au Gabon suscite l''espoir d''un renouveau politique et économique après des années de contestation, avec des attentes fortes en matière de réformes et de transparence.',
        'https://fr.africanews.com/2025/04/14/gabon-lelection-doligui-nguema-nourrit-lespoir-dun-nouveau-depart/?utm_source=flipboard.com&utm_campaign=feeds_news&utm_medium=referral',
        'Flipboard',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24d6668a-e546-4656-8dba-2d3b0e772095',
        'Invité Afrique Midi - Présidentielles au Gabon: «Le scrutin était ouvert, mais pas compétitif», estime le chercheur Bergès Miétté',
        'L''élection présidentielle au Gabon était ouverte à plusieurs candidats, mais n''était pas réellement compétitive en raison d''un déséquilibre des moyens et d''un manque de transparence, selon un chercheur.',
        'https://www.rfi.fr/fr/podcasts/invit%C3%A9-afrique-midi/20250414-pr%C3%A9sidentielles-au-gabon-le-scrutin-%C3%A9tait-ouvert-mais-pas-comp%C3%A9titif-estime-le-chercheur-berg%C3%A8s-mi%C3%A9tt%C3%A9?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Numérique / Digital, Services, Finances',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53c2994e-d087-4f0a-bfa7-ac23bbc04ab9',
        'France 24 décrypte la victoire de Brice Oligui Nguema à l''élection présidentielle au Gabon',
        'Brice Clotaire Oligui Nguema, leader de la transition au Gabon, annonce sa candidature à l''élection présidentielle après le coup d''État de 2023, suscitant des débats sur l''avenir politique du pays.',
        'https://www.france24.com/fr/vid%C3%A9o/20250414-france-24-d%C3%A9crypte-%C3%A9lection-brice-clotaire-oligui-nguema-gabon-pr%C3%A9sidentielle?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a44e259-0b8b-46b7-97e5-aea654e67fe1',
        'France 24 décrypte la victoire de Brice Oligui Nguema à l''élection présidentielle au Gabon',
        'Brice Clotaire Oligui Nguema, leader de la transition au Gabon, annonce sa candidature à la prochaine élection présidentielle, marquant une étape clé dans le processus politique après la prise de pouvoir en 2023.',
        'https://www.france24.com/fr/vid%C3%A9o/20250414-france-24-d%C3%A9crypte-%C3%A9lection-brice-clotaire-oligui-nguema-gabon-pr%C3%A9sidentielle',
        'France 24',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '07a78020-9f1c-4c25-802c-ae263bfa70b8',
        'Le satisfecit de Mirabelle Ngningone lors du vote dans le komo-océan',
        'Mirabelle Ngningone a exprimé sa satisfaction quant au bon déroulement du vote dans le Komo-Océan, saluant la participation et l’organisation du processus électoral.',
        'https://gabonactu.com/blog/2025/04/14/le-satisfecit-de-mirabelle-ngningone-lors-du-vote-dans-le-komo-ocean/',
        'Gabon Actu',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f2c62ae-4f9e-4cb4-bac7-b5c4fa65ff64',
        'Bilie-By-Nzé: « Je prends acte des résultats mais je ne félicite pas le vainqueur «',
        'Le candidat Bilie By Nze reconnaît les résultats des élections mais refuse de féliciter le vainqueur, exprimant ainsi son désaccord avec le processus.',
        'https://gabonactu.com/blog/2025/04/14/bilie-by-nze-je-prends-acte-des-resultats-mais-je-ne-felicite-pas-le-vainqueur/',
        'Gabon Actu',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6accbdce-d2b3-4bb3-b3ce-c694905c5a58',
        'Statut de l’opposant au Gabon : Bilie-By-Nze à la croisée d’un vide juridique et d’une reconnaissance politique',
        'L’opposant gabonais Bilie By Nze se trouve dans une situation complexe, entre un vide juridique concernant son statut et une reconnaissance politique croissante, ce qui soulève des questions sur la légalité et la légitimité de son rôle.',
        'https://www.gabonreview.com/statut-de-lopposant-au-gabon-bilie-by-nze-a-la-croisee-dun-vide-juridique-et-dune-reconnaissance-politique/',
        'Gabon Review',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '870d260d-0181-425b-9db4-def84012b1b1',
        'Le RDB se transformera en parti politique le 19 avril 2025',
        'Le RDB, un mouvement citoyen gabonais, annonce sa transformation en parti politique le 19 avril 2025, avec pour objectif de participer activement à la vie politique du pays. Cette transition vise à élargir son influence et à promouvoir ses idéaux de développement et de démocratie.',
        'https://gabonactu.com/blog/2025/04/14/le-rdb-se-transformera-en-parti-politique-le-19-avril-2025/',
        'Gabon Actu',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fb97afd-3c3e-4bc5-9d60-6183c278444a',
        'Les artistes gabonais célebreront la victoire d’Oligui Nguema le 19 avril au stade de Nzeng-Ayong',
        'Les artistes gabonais organiseront un concert le 19 avril au stade de Nzeng Ayong pour célébrer la victoire d''Oligui Nguéma, rassemblant musique et soutien populaire. L''événement vise à renforcer l''unité nationale à travers la culture.',
        'https://gabonactu.com/blog/2025/04/14/les-artistes-gabonais-celebreront-la-victoire-doligui-nguema-le-19-avril-au-stade-de-nzeng-ayong/',
        'Gabon Actu',
        'Services, Tourisme, Numérique / Digital',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8261c66a-b99a-455d-9018-852dccb36a8d',
        'Abou Dhabi accueillera la conférence Behavioural Exchange 2025',
        'Abou Dhabi accueillera en 2025 la conférence *Behavioural Exchange*, un événement international axé sur les sciences comportementales et leur application dans les politiques publiques et l''innovation sociale. Des experts du monde entier y partageront des recherches et des solutions pour influencer positivement les comportements humains.',
        'https://agpgabon.ga/2025/04/14/abou-dhabi-accueillera-la-conference-behavioural-exchange-2025/',
        'AGP',
        'Autres',
        '2025-04-14T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76c7552a-fc07-4576-9417-b78adb066875',
        'Gabon: le président élu Brice Oligui Nguema face à de nombreux défis',
        'Brice Oligui Nguema, président élu du Gabon, doit relever plusieurs défis majeurs, notamment la relance économique, la réconciliation nationale et la lutte contre la corruption, dans un contexte de transition politique. Son leadership sera crucial pour rétablir la confiance et répondre aux attentes de la population.',
        'https://www.rfi.fr/fr/afrique/20250414-gabon-le-pr%C3%A9sident-%C3%A9lu-brice-oligui-nguema-face-%C3%A0-de-nombreux-d%C3%A9fis',
        'RFI',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e290ac2-e077-4846-96de-1e51f415c788',
        'Gabon : Bilie-By-Nze reconnaît sa défaite à l''élection présidentielle',
        'Bilie By Nze, candidat à l''élection présidentielle au Gabon, a reconnu sa défaite après la publication des résultats provisoires, tout en soulignant des irrégularités lors du scrutin. Il appelle cependant à la paix et au respect des institutions.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250414-gabon-bilie-by-nze-reconna%C3%AEt-sa-d%C3%A9faite-%C3%A0-l-%C3%A9lection-pr%C3%A9sidentielle?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eb2d98a2-30b8-48a1-a499-7e83b5cc112d',
        'Gabon : Bilie-By-Nze reconnaît sa défaite à l''élection présidentielle',
        'Bilie By Nze, candidat à l''élection présidentielle au Gabon, a reconnu sa défaite après la publication des résultats provisoires, tout en exprimant des réserves sur le processus électoral.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250414-gabon-bilie-by-nze-reconna%C3%AEt-sa-d%C3%A9faite-%C3%A0-l-%C3%A9lection-pr%C3%A9sidentielle',
        'France 24',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '325c666c-969c-48b1-9d1a-79dec564689d',
        'BITAM : Le RDB du Ntem, symbole d’une dynamique inclusive et d’unité politique',
        'Le Rassemblement Démocratique du Peuple (RDP) de Bitam dans le Ntem a organisé une réunion pour renforcer l''unité politique et promouvoir une dynamique inclusive, mettant en avant la participation citoyenne et la cohésion sociale. Cette initiative vise à consolider les actions du parti en faveur du développement local et de l''engagement communautaire.',
        'https://kongossanews.info/bitam-le-rdb-du-ntem-symbole-dune-dynamique-inclusive-et-dunite-politique/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '11501390-614b-4ce1-90f9-5563ff2b08d6',
        'À Oyem, Estelle Ondo a investi le terrain pour le succès de la campagne de Brice Clotaire Oligui Nguema',
        'Estelle Ondo s’est rendue à Oyem pour soutenir activement la campagne électorale de Brice Clotaire Oligui Nguema, en mobilisant les habitants et en promouvant son programme politique.',
        'https://kongossanews.info/a-oyem-estelle-ondo-a-investi-le-terrain-pour-le-succes-de-la-campagne-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c11b626-b2f5-4c1f-9c6e-e5e972f2dd5e',
        'Geoffroy Foumboula Libeka Makosso : « Oligui Nguema devient ainsi le 1er président démocratiquement élu du Gabon depuis son exis...',
        'Geoffroy Foumboula Libeka Makosso Oligui Nguema a été élu président du Gabon, devenant ainsi le premier dirigeant démocratiquement choisi dans l''histoire du pays. Cette élection marque un tournant politique pour le Gabon.',
        'https://kongossanews.info/geoffroy-foumboula-libeka-makosso-oligui-nguema-devient-ainsi-le-1er-president-democratiquement-elu-du-gabon-depuis-son-existence/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08229b10-c4f5-427c-8ed8-a465a145bbaf',
        'Présidentielle au Gabon : Le Président Mahamat Idriss Déby Itno félicite Oligui Nguema pour sa victoire',
        'Le président tchadien Mahamat Idriss Déby Itno a félicité le général Oligui Nguema pour sa victoire à l’élection présidentielle au Gabon, saluant un processus démocratique.',
        'https://agpgabon.ga/2025/04/14/presidentielle-au-gabon-le-president-mahamat-idriss-deby-itno-felicite-oligui-nguema-pour-sa-victoire/',
        'AGP',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '032b000d-0036-407a-a614-f84a1f94ca30',
        'Présidentielle au Gabon : le Roi Mohammed VI félicite Brice Clotaire Oligui Nguema pour son élection',
        'Le roi Mohammed VI du Maroc a adressé ses félicitations à Brice Clotaire Oligui Nguema pour son élection à la présidence du Gabon, marquant un geste de soutien diplomatique entre les deux pays.',
        'https://agpgabon.ga/2025/04/14/presidentielle-au-gabon-le-roi-mohammed-vi-felicite-brice-clotaire-oligui-nguema-pour-son-election/',
        'AGP',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2178dc5-2e64-4314-b070-299ed0c1ca27',
        'Gabon: le RdB, de la mobilisation électorale à la structuration partisane',
        'Le Rassemblement pour le Développement et la Bonté (RDB) au Gabon évolue d''un mouvement de mobilisation électorale vers une structuration partisane plus formelle, visant à renforcer son influence politique. Cette transition s''accompagne d''une volonté d''organiser et de consolider son ancrage local tout en préparant les prochains scrutins.',
        'https://gabonmediatime.com/gabon-le-rdb-de-la-mobilisation-electorale-a-la-structuration-partisane/',
        'Gabon Media Time',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d49064b-0ac9-45dc-bcf0-95419238d090',
        'Gabon : vers la mutation du Rassemblement des Bâtisseurs en parti politique !',
        'Le Rassemblement des Bâtisseurs, un mouvement gabonais, envisage de se transformer en parti politique pour participer activement à la vie démocratique du pays, selon des discussions internes. Cette mutation pourrait renforcer son influence dans les débats politiques et sociaux au Gabon.',
        'https://gabonmediatime.com/gabon-vers-la-mutation-du-rassemblement-des-batisseurs-en-parti-politique/',
        'Gabon Media Time',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fea2bf89-6690-45ee-a4d9-10dae354e2ae',
        'Gouvernance chaotique à La Poste : le SYNAPOSTE pose un ultimatum au gouvernement',
        'Le syndicat des travailleurs de la poste gabonaise (SYNAPOSTE) donne un ultimatum au gouvernement pour résoudre les problèmes de gouvernance et de gestion chaotique au sein de l’entreprise, menaçant de recourir à des actions syndicales si rien n’est fait.',
        'https://gabonmediatime.com/gouvernance-chaotique-a-la-poste-le-synaposte-pose-un-ultimatum-au-gouvernement/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2bc32c7f-2016-48fb-8d45-1bd578bbbb5b',
        'BITAM : Le RDB du Ntem, symbole d’une dynamique inclusive et d’unité politique',
        'Le Rassemblement Démocratique du Peuple (RDP) de Bitam dans le Ntem célèbre une dynamique inclusive et une unité politique renforcée, marquée par une mobilisation populaire et des discours encourageants lors d''une récente assemblée générale.',
        'https://kongossanews.info/bitam-le-rdb-du-ntem-symbole-dune-dynamique-inclusive-et-dunite-politique/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '259266ef-8b44-4f94-816e-2ae9fe14a2c4',
        'À Oyem, Estelle Ondo a investi le terrain pour le succès de la campagne de Brice Clotaire Oligui Nguema',
        'Estelle Ondo s’est rendue à Oyem pour mobiliser les habitants en faveur de la campagne électorale de Brice Clotaire Oligui Nguéma, soulignant l’importance de leur soutien. Son déplacement vise à renforcer l’adhésion locale et à assurer le succès de cette initiative politique.',
        'https://kongossanews.info/a-oyem-estelle-ondo-a-investi-le-terrain-pour-le-succes-de-la-campagne-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba21af57-e77f-4afb-92ea-b4682d1bd464',
        'Geoffroy Foumboula Libeka Makosso : « Oligui Nguema devient ainsi le 1er président démocratiquement élu du Gabon depuis son exis...',
        'Geoffroy Foumboula Libeka Makosso Oligui Nguema est devenu le premier président démocratiquement élu du Gabon depuis l''indépendance du pays, marquant un tournant historique dans sa gouvernance politique.',
        'https://kongossanews.info/geoffroy-foumboula-libeka-makosso-oligui-nguema-devient-ainsi-le-1er-president-democratiquement-elu-du-gabon-depuis-son-existence/',
        'Kongossa News',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4856139c-8ce5-4c27-9292-749fe50d44c6',
        'Élections 2025 : La société civile salue un scrutin apaisé et fait ses recommandations',
        'La société civile gabonaise salue l''annonce des élections présidentielles prévues pour 2025, y voyant une étape importante vers la démocratie et la stabilité politique. Elle encourage également une préparation transparente et inclusive pour garantir des élections libres et équitables.',
        'https://www.gabonews.com/fr/actus/politique/article/elections-2025-la-societe-civile-salue-un-scrutin',
        'Gabonews',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2917fc7f-6318-45f5-bd02-44f0b5c7d0a4',
        'Les Pays membres de la SADC, rejettent le protocole d''accord illégitime avec la pseudo “RASD”',
        'Les pays membres de la SADC ont rejeté une proposition ou une décision, exprimant leur désaccord lors d''une réunion. Cette position commune souligne des divergences sur des questions importantes pour la région.',
        'https://www.gabonews.com/fr/actus/international/article/les-pays-membres-de-la-sadc-rejettent-le',
        'Gabonews',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '61299c30-b38d-42e2-863b-a28625a97ee7',
        'Il ne revient nullement à un membre de la coordination de proclamer la transformation de la plateforme "Le Rassemblement des Bâtisseurs" en parti politique',
        'L''article souligne qu''il n''appartient pas à un membre isolé de la communauté éducative ou politique de décider unilatéralement des réformes scolaires, mais plutôt à une concertation collective incluant enseignants, parents et experts. Il met en garde contre les décisions précipitées qui pourraient nuire au système éducatif sans une réflexion approfondie.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/il-ne-revient-nullement-a-un-membre-de-la',
        'Gabonews',
        'Éducation',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f464784-d831-448a-89a9-e020d872f09a',
        'Publié le 14 / 04 / 2025',
        'L’opposant gabonais Bilie By Nze rejette les élections organisées sous le régime actuel, les qualifiant de mascarade en raison du manque de transparence et de liberté démocratique. Il dénonce un processus électoral contrôlé par le pouvoir en place, privant les citoyens d’un choix réel.',
        'https://union.sonapresse.com/fr/gabon-lopposant-bilie-nze-refuse-la-mascarade-electorale',
        'L''union',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f6a12ec-219b-4209-8691-ac37db3520e3',
        'Publié le 14 / 04 / 2025',
        'Le Rassemblement pour le Développement du Gabon (RDB), un mouvement citoyen, annonce sa transformation en parti politique pour participer activement à la vie politique nationale et promouvoir ses idées de développement. Cette mutation vise à renforcer son influence et à contribuer aux débats publics.',
        'https://union.sonapresse.com/fr/gabon-le-rdb-entend-se-muter-en-parti-politique',
        'L''union',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ac35ba5-1dd4-40c9-82a2-b08602450242',
        'Publié le 14 / 04 / 2025',
        'Hermann Immongault a réussi son pari en transformant son projet éducatif en une réussite, démontrant que la persévérance et l''innovation peuvent surmonter les défis dans le secteur de l''éducation en Afrique. Son parcours inspire les jeunes à croire en leurs ambitions malgré les obstacles.',
        'https://union.sonapresse.com/fr/pari-gagne-pour-hermann-immongault',
        'L''union',
        'Éducation, Business Femme',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d7821a0-e83a-401e-9b3e-95f9d99a17eb',
        'Gabon : des opposants fustigent la présidentielle',
        'Au Gabon, des opposants critiquent l''élection présidentielle, dénonçant des irrégularités et un manque de transparence dans le processus électoral.',
        'https://information.tv5monde.com/afrique/video/gabon-des-opposants-fustigent-la-presidentielle-2770094?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7152028e-85c3-40c4-9014-ebdde412e5ee',
        'Présidentielle 2025/ Libreville: le MPP5 artisan de la victoire d’OLIGUI NGUEMA dans le 5e arrondissement',
        'Le MPP5 a joué un rôle clé dans la victoire d’Oligui Nguema lors de l''élection présidentielle de 2025 dans le 5e arrondissement de Libreville en mobilisant efficacement les électeurs.',
        'https://vxp241.com/2025/04/15/presidentielle-2025-libreville-le-mpp5-artisan-de-la-victoire-doligui-nguema-dans-le-5e-arrondissement/',
        'Vox Populi',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75dd11a9-5cdb-4e18-9d70-6387108a626e',
        'Présidentielle 2025 : Le satisfecit de l’ONG Afrique Espérance',
        'L’Afrique Espérance exprime sa satisfaction quant au déroulement de la présidentielle 2025 au Gabon, saluant un processus électoral transparent et apaisé. Le mouvement souligne l’importance de cette élection pour la stabilité et le développement du pays.',
        'https://gabonactu.com/blog/2025/04/15/presidentielle-2025-le-satisfecit-de-long-afrique-esperance/',
        'Gabon Actu',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b796fc9-a3aa-418a-ad2a-e731a0f9c6fe',
        'Les populations de la Nyanga signent un contrat de confiance avec Oligui Nguema voté à 98,34%',
        'Les Nynois ont signé un contrat de confiance avec Oligui Nguema, marquant une étape importante dans leur collaboration pour des projets communs. Cet accord vise à renforcer les relations et à promouvoir des initiatives bénéfiques pour les deux parties.',
        'https://gabonactu.com/blog/2025/04/15/les-nynois-signent-un-contrat-de-confiance-avec-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b01bf77-faa8-4559-a20d-68eb5b27203f',
        'La mission d’observateurs internationaux de la diaspora africaine en Europe salue le bon déroulement du scrutin',
        'Une mission d’observateurs internationaux de la diaspora africaine en Europe a salué le bon déroulement du scrutin au Gabon, soulignant son organisation et sa transparence.',
        'https://gabonactu.com/blog/2025/04/15/la-mission-dobservateurs-internationaux-de-la-diaspora-africaine-en-europe-salue-le-bon-deroulement-du-scrutin/',
        'Gabon Actu',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1019164c-a409-41ae-a45e-67061e98e9c2',
        'Le Bandit Beau, d’artiste prometteur à cambrioleur ?',
        'Un jeune artiste prometteur au Gabon, connu sous le nom de "Bandit Beau", a été arrêté pour cambriolage après avoir abandonné sa carrière musicale, passant ainsi des scènes aux délits. Son parcours illustre une dérive sociale malgré un talent artistique initial.',
        'https://www.gabonreview.com/le-bandit-beau-dartiste-prometteur-a-cambrioleur/',
        'Gabon Review',
        'Services, Éducation, Business Femme',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c91b8270-b3ed-447d-a328-d8d740d6fe06',
        'Présidentielle au Gabon : Bilie-By-Nze reconnaît sa défaite, mais fustige un scrutin « opaque »',
        'Bilie By Nze, candidat à la présidentielle gabonaise, reconnaît sa défaite mais dénonce des irrégularités et un scrutin manquant de transparence. Il critique notamment le processus électoral tout en appelant à l’apaisement.',
        'https://www.jeuneafrique.com/1678962/politique/presidentielle-au-gabon-bilie-by-nze-reconnait-sa-defaite-mais-fustige-un-scrutin-opaque/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-15T00:00:00.000Z',
        '2025-09-15T23:06:12.420Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

