-- Batch 1 - Section 2/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '4c4dbf4b-3849-40a7-862b-9ff98fb46405',
        'Conflit homme-éléphant : Après cette 1.000e Space for Giants ambitionne de construire 900 barrières électroniques pour le minist...',
        'Le ministère des Eaux et Forêts, en partenariat avec Space for Giants, a inauguré la 1 000ᵉ barrière électrique dans la province de la Nyanga afin de réduire le conflit entre les habitants et les éléphants.',
        'https://www.gabonews.com/fr/actus/environnement/article/conflit-homme-elephant-apres-cette-1-000e-space',
        'Gabonews',
        'Numérique / Digital, Agriculture, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f568b37-b817-43df-a6a8-36f5f80a7355',
        'Présidentielle 2025 : Jacques Okoué saisit l’Union africaine contre la candidature d’Oligui Nguema',
        'Jacques Okoué a saisi l’Union africaine et la Cour africaine des droits de l’homme pour invalider la candidature d’Oligui Nguema aux élections présidentielles de 2025 au Gabon, invoquant une violation des principes démocratiques.',
        'https://gabonmediatime.com/presidentielle-2025-jacques-okoue-saisit-lunion-africaine-contre-la-candidature-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96b4bb19-a765-44bb-9ec2-4c87316a217c',
        'Santé et solidarité : une caravane médicale au service des populations de la Lombo-Bouenguidi',
        'Depuis le 24 février 2025, une caravane médicale organisée par le Ministère de la Santé fournit gratuitement des consultations, des traitements et des sensibilisations aux populations de la Lombo-Bouenguidi afin d''améliorer l''accès aux soins de santé.',
        'https://kongossanews.info/sante-et-solidarite-une-caravane-medicale-au-service-des-populations-de-la-lombo-bouenguidi/',
        'Kongossa News',
        'Santé, Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '83b675a3-39af-4708-9917-3a3f67add341',
        'IUSO : une première journée pour comprendre les difficultés des étudiants',
        'L’IUSO a organisé sa première journée dédiée à la réflexion stratégique pour identifier et améliorer les difficultés d’adaptation et d’intégration des étudiants au sein de l’université.',
        'https://union.sonapresse.com/fr/iuso-une-premiere-journee-pour-comprendre-les-difficultes-des-etudiants',
        'L''Union',
        'Éducation, Services, Numérique / Digital',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db0212a1-def1-44bd-a518-69c5f32aa24a',
        'Cinéma: « Oncle Didine » tire sa révérence Gabon: deux projets de loi en faveur de la culture sur la table des Sénateurs de la T...',
        'Adrien James Prince de Capistran, icône du cinéma gabonais surnommé "Oncle Didine", est décédé le 5 janvier 2025 à l’âge de 74 ans après une longue maladie, laissant une empreinte profonde dans le monde artistique du Gabon.',
        'https://depeches241.com/?p=22156',
        'Dépêche 241',
        'Culture, Éducation, Business Femme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '224e1e31-483d-499e-bb69-29f53969aa1f',
        'Gabon : le Groupe UBA réaffirme son engagement à financer les projets structurants',
        'Le Groupe UBA a réaffirmé son engagement à financer les projets structurants au Gabon lors d''une rencontre avec le Président Brice Clotaire Oligui Nguema.',
        'https://gabonactu.com/blog/2025/02/27/gabon-le-groupe-uba-reaffirme-son-engagement-a-financer-les-projets-structurants/',
        'Gabon Actu',
        'Finances, Business Femme, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '54ec6a0d-db90-42ef-b823-7c1ddf276e5b',
        'Angondjé : les enfants du CAPEDES pris en charge par les médecins chinois',
        'Une équipe médicale chinoise, dans le cadre de sa 26ᵉ mission, a fourni gratuitement des soins et des mesures préventives aux enfants vulnérables du CAPEDES à Angondjé, renforçant ainsi la coopération sanitaire entre le Gabon et la Chine.',
        'https://gabonmediatime.com/angondje-les-enfants-du-capedes-pris-en-charge-par-les-medecins-chinois/',
        'Gabon Media Time',
        'Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a8788626-166c-4683-8c4d-885cc5a8cf22',
        'Dr Armande Longo, épse Moulengui lance les travaux de la mise en oeuvre de la Convention de la Haye de 1945 et 1999',
        'Le ministre gabonais de la Culture, Dr Armande Longo, épouse Moulengui, a lancé à Libreville un atelier visant à renforcer la ratification et la mise en œuvre de la Convention de La Haye de 1945 et 1999 pour la protection du patrimoine culturel.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/dr-armande-longo-epouse-moulengui-lance-les',
        'Gabonews',
        'Éducation, Services, Numérique / Digital, Tourisme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f85d3b1e-8da3-469b-9db1-9c0e9b9045e1',
        'L’hôpital départemental de Leconi aux bons soins de l’association Lavè',
        'L’association Lavè a fourni des médicaments essentiels à l’hôpital départemental de Leconi afin d’améliorer la prise en charge des patients dans le département des Plateaux.',
        'https://www.gabonreview.com/lhopital-departemental-de-leconi-aux-bons-soins-de-lassociation-lave/',
        'Gabon Review',
        'Services, Santé, Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '427f10c5-1441-4993-9e06-8e360e98caab',
        'Présidentielles 2025 : les associations à l’avant-garde de la citoyenneté',
        'À l''approche des présidentielles 2025 au Gabon, les associations se positionnent en première ligne pour éduquer les citoyens, préserver la paix et promouvoir les valeurs démocratiques tout au long du processus électoral.',
        'https://union.sonapresse.com/fr/presidentielles-2025-les-associations-lavant-garde-de-la-citoyennete',
        'L''Union',
        'Éducation, Services, Business Femme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b97ed40-c74a-485a-8656-37f3fba8854e',
        '« Le Gabon a besoin d’avoir des institutions fortes, crédibles et qui garantissent les mêmes droits pour tous les gabonais », (M...',
        'Michel Ongoundou Loundah, président de REAGIR, a affirmé que le Gabon doit développer des institutions fortes, crédibles et transparentes garantissant l’égalité des droits pour tous les citoyens, plutôt que de se reposer sur un leader providentiel.',
        'https://gabonactu.com/blog/2025/02/27/le-gabon-a-besoin-davoir-des-institutions-fortes-credibles-et-qui-garantissent-les-memes-droits-pour-tous-les-gabonais-michel-ongoundou-loundah-president-de-reagir/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '199213ac-6e0a-4247-9a04-1932b14ab9f0',
        'Plaidoyer pour la lutte contre les violences faites aux femmes : L’ONG Aurore présente son rapport',
        'L’ONG Aurore a présenté un rapport détaillant l’ampleur des violences faites aux femmes au Gabon et proposant 19 recommandations concrètes pour les combattre.',
        'https://kongossanews.info/plaidoyer-pour-la-lutte-contre-les-violences-faites-aux-femmes-long-aurore-presente-son-rapport/',
        'Kongossa News',
        'Business Femme, Éducation, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.210Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53fc590f-4a53-43dc-8357-9f6c749b8231',
        'Rachat de la SMAG : Que sait-on du repreneur milliardaire ivoirien ?',
        'La Société meunière et avicole du Gabon (SMAG) a été rachetée par le groupe ivoirien AVOS, dirigé par Jean-Marie Ackah, renforçant ainsi la position d''AVOS dans le secteur agroalimentaire en Afrique de l’Ouest.',
        'https://directinfosgabon.com/rachat-de-la-smag-que-sait-on-du-repreneur-milliardaire-ivoirien/',
        'Direct infos Gabon',
        'Agriculture, Commerce, Finances',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.211Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4309f4a7-b9a8-44b6-9542-1572adf622e8',
        'Cabo Verde en soutien à l’intégrité territoriale et à la souveraineté du Maroc sur le Sahara',
        'Le ministre des Affaires étrangères de Cabo Verde a réaffirmé le soutien de son pays à l''intégrité territoriale et à la souveraineté du Maroc sur l''ensemble de son territoire, y compris la région du Sahara.',
        'https://www.gabonews.com/fr/actus/international/article/cabo-verde-en-soutien-a-l-integrite-territoriale',
        'Gabonews',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.211Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd75c3008-f937-480e-ae1f-c568eba95b94',
        'Ogooué Ivindo : Clôture des Journées littéraires de l’Ivindo à Ovan',
        'La clôture des Journées littéraires de l’Ivindo à Ovan a mis en avant le rôle de la littérature gabonaise dans la restauration de l’identité nationale à travers des ateliers, récitals et le don de livres au lycée public Daniel Hubert N’na Ekamkam.',
        'https://www.gabonreview.com/ogooue-ivindo-cloture-des-journees-litteraires-de-livindo-a-ovan/',
        'Gabon Review',
        'Éducation, Numérique / Digital, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.211Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ed2b8c65-9f96-4e46-94e0-9adead72a664',
        'Quête de souveraineté en Afrique: le Tchad met fin aux accords de sécurité et de défense avec la France Présidentielles en RDC: ...',
        'Le gouvernement tchadien a annoncé la fin de sa coopération militaire avec la France afin d’affirmer sa souveraineté nationale.',
        'https://depeches241.com/?p=21751',
        'Dépêche 241',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.212Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6acb543-8ccd-40b0-ae61-750fd72fc088',
        'Présidentielle 2025 : La diaspora africaine en Europe veut une élection apaisée pour un Gabon stable',
        'Les organisations de la diaspora africaine en Europe appellent à une élection présidentielle pacifique et respectueuse des institutions pour assurer la stabilité du Gabon en 2025.',
        'https://gabonactu.com/blog/2025/02/27/presidentielle-2025-la-diaspora-africaine-en-europe-veut-une-election-apaisee-pour-un-gabon-stable/',
        'Gabon Actu',
        'Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.214Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e3b173d-d531-46cf-8437-c14aca7805be',
        'Médiation du mouvement ICOD face au climat social délétère au sein des populations de la commune de Port-Gentil',
        'Le mouvement ICOD appelle le Président de la Transition à favoriser l’unité, l’humilité et le pardon afin de médiatiser et apaiser le climat social délétère et les tensions ethniques au sein des populations de la commune de Port-Gentil.',
        'https://www.gabonews.com/fr/actus/politique/article/mediation-du-mouvement-icod-face-au-climat-social',
        'Gabonews',
        'Numérique / Digital, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.215Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '15952d46-efb0-439d-90e0-8d8399637b19',
        'Football : Des badges aux arbitres gabonais, «une grande première» au pays du bricolage',
        'La Fédération gabonaise de football (Fegafoot) a organisé une cérémonie inédite de remise de badges aux arbitres internationaux et nationaux, marquant une étape importante dans la valorisation du corps arbitrale au Gabon.',
        'https://www.gabonreview.com/football-des-badges-aux-arbitres-gabonais-une-grande-premiere-au-pays-du-bricolage/',
        'Gabon Review',
        'Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.216Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f39abbed-d474-414c-822c-545408baa013',
        'Cérémonie de lancement des unités mobiles pour la campagne de recensement des électeurs par la plateforme C’BON',
        'Lors de la cérémonie de lancement des unités mobiles de recensement des électeurs par la plateforme C’BON à Libreville, les organisateurs ont souligné l’importance de mobiliser les citoyens pour assurer une participation démocratique massive aux prochaines élections présidentielles de 2025.',
        'https://kongossanews.info/ceremonie-de-lancement-des-unites-mobiles-pour-la-campagne-de-recensement-des-electeurs-par-la-plateforme-cbon/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.217Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9b97b9b-756f-4954-a81f-3402c310b8e0',
        'Transition: la nouvelle Constitution officiellement promulguée par Oligui Nguema  Transition: après la Constitution, place au Co...',
        'Le 19 décembre 2024, le Président de la Transition, Brice Clotaire Oligui Nguema, a officiellement promulgué la nouvelle Constitution du Gabon, marquant le début d''une nouvelle ère politique et institutionnelle dans le pays.',
        'https://depeches241.com/?p=21986',
        'Dépêche 241',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.217Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '982cc351-d128-4db4-9197-60809196ed82',
        'Séance de travail au Ministère de l’Agriculture et de l’Élevage',
        'Le 27 février 2025, la Ministre de l’Agriculture, Adette Polo Epse Panzou, a rencontré l’expert Emmanuel Ombana pour une séance de travail visant à promouvoir l’entrepreneuriat agricole des jeunes et leur implication durable dans les chaînes de valeur agricoles à l’ère numérique.',
        'https://www.gabonews.com/fr/actus/societe/article/seance-de-travail-au-ministere-de-l-agriculture',
        'Gabonews',
        'Agriculture, Numérique / Digital, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.218Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de08ec58-957e-40a0-aa6d-69bcded3a0e0',
        'Port d’Owendo : OCT forme ses équipes à la maintenance des nouveaux portiques',
        'Owendo Container Terminal a organisé une formation de cinq jours pour 27 agents gabonais afin de renforcer leurs compétences en maintenance des nouveaux portiques.',
        'https://www.gabonreview.com/port-dowendo-oct-forme-ses-equipes-a-la-maintenance-des-nouveaux-portiques/',
        'Gabon Review',
        'Éducation, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.218Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '599e9a3f-be5b-4c4d-aa64-e2775499f6f9',
        'Présidentielle au Gabon : Les membres de l’Acer connus, doutes sur leur impartialité',
        'L''article exprime des doutes sur l''impartialité des membres de l''Autorité de contrôle des élections et du référendum (Acer) au Gabon, remettant en question la transparence du processus électoral suite au coup d''État de 2025.',
        'https://www.gabonreview.com/presidentielle-au-gabon-les-membres-de-lacer-connus-doutes-sur-leur-impartialite/',
        'Gabon Review',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.219Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '71527ffb-716b-4aa0-9d05-d8a610c72fa2',
        'Makokou : Installation officielle de la Coordination OSSIMANE OGOOUÉ IVINDO dans une ambiance conviviale',
        'Le 22 février 2025, la coordination provinciale OSSIMANE OGOOUÉ IVINDO a été officiellement installée à Makokou, marquant une étape clé pour le développement et la cohésion dans la province de l’Ogooué-Ivindo.',
        'https://kongossanews.info/makokou-installation-officielle-de-la-coordination-ossimane-ogooue-ivindo-dans-une-ambiance-conviviale/',
        'Kongossa News',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.220Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e40c3fe-5b10-4b54-9788-35fef2067b32',
        'Innovation scientifique : La Turquie et le Gabon signent un accord de coopération',
        'Le 26 février 2025, la Turquie et le Gabon ont signé un protocole d’accord stratégique pour renforcer leur coopération en innovation scientifique, incluant des projets de recherche conjoints et des programmes d’échange de scientifiques.',
        'https://directinfosgabon.com/innovation-scientifique-la-turquie-et-le-gabon-signent-un-accord-de-cooperation/',
        'Direct infos Gabon',
        'Numérique / Digital, Éducation, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.221Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6b30cee3-19ff-4397-aec5-0a80a7baa6c9',
        'Affaire Sylvia et Noureddin Bongo : Un dossier «purement politique» et «totalement vide», selon Me Gisèle Eyué',
        'L’avocate Me Gisèle Eyué Bekalé dénonce l’affaire Sylvia Bongo et Nourreddin Bongo Valentin comme étant purement politique en soulignant l’ingérence du pouvoir exécutif dans la justice.',
        'https://www.gabonreview.com/affaire-sylvia-et-noureddin-bongo-dossier-purement-politique-et-totalement-vide-selon-me-gisele-eyue/',
        'Gabon Review',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.221Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4a7a0c15-655a-441e-8c8c-06b05d111cc1',
        '« Une majorité des Gabonais attend de son Chef d’État des signaux clairs, des gestes forts, des paroles de rassemblement » (Libr...',
        'Dina Koussou appelle le Président de la Transition du Gabon à adopter des mesures claires et fortes pour favoriser l''unité nationale et contrer le repli identitaire croissant.',
        'https://gabonactu.com/blog/2025/02/27/une-majorite-des-gabonais-qui-attend-de-son-chef-detat-des-signaux-clairs-des-gestes-forts-des-paroles-de-rassemblement-libre-propos-de-dina-koussou/',
        'Gabon Actu',
        'Services, Éducation, Numérique / Digital, Business Femme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.222Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f121c4cb-8090-4c20-a8a8-ada6613f2686',
        'L’ONEP appelle à la reprise du travail sur les sites pétroliers',
        'Après une réunion à Port-Gentil, l’ONEP appelle les employés des sites pétroliers à reprendre le travail suite aux garanties de l’État concernant les salaires impayés et la protection des travailleurs.',
        'https://directinfosgabon.com/lonep-appelle-a-la-reprise-du-travail-sur-les-sites-petroliers/',
        'Direct infos Gabon',
        'Services, Finances',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.223Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4cfd7b08-ce3c-449c-9e35-2f200f7eb012',
        'Délestages dans le Grand Libreville : la situation et le plan de bataille',
        'Face à une crise énergétique prolongée à Libreville, la SEEG présente un plan d’action combinant l’installation de centrales flottantes turques, la pose de câbles en fibre carbone et le développement d’une centrale terrestre pour rétablir l’approvisionnement électrique après deux décennies de sous-investissement.',
        'https://www.gabonreview.com/delestages-dans-le-grand-libreville-la-situation-et-le-plan-de-bataille/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.224Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '13baa28d-058c-4ad7-9d6f-13bdb2ee9c5d',
        'Affaire HPO : Eddy Minang face au défi de restaurer la crédibilité de la justice gabonaise',
        'L''affaire HPO met en lumière les défis d''Eddy Minang pour restaurer la crédibilité de la justice gabonaise face à des accusations d''instrumentalisation politique et de procédures controversées.',
        'https://kongossanews.info/affaire-hpo-eddy-minang-face-au-defi-de-restaurer-la-credibilite-de-la-justice-gabonaise/',
        'Kongossa News',
        'Autres',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.224Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49cf86ad-9554-49aa-b75c-3a07884007d1',
        'Air France & Afrijet signent un accord pour les destinations Bangui et Port Harcourt',
        'Les compagnies Air France et Afrijet ont signé un accord permettant aux passagers de voyager de Libreville vers Bangui et Port Harcourt avec un seul billet, faisant de l''aéroport de Libreville une plateforme de correspondances en Afrique Centrale.',
        'https://gabonactu.com/blog/2025/02/27/air-france-afrijet-signent-un-accord-pour-les-destinations-bangui-et-port-harcourt/',
        'Gabon Actu',
        'Tourisme, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.225Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7db0c61b-26ad-47c0-81dc-a581f56bb018',
        'Production agricole  : Olam cède tous ses actifs africains au groupe saoudien PIF',
        'Le géant singapourien Olam a vendu toutes ses activités agricoles en Afrique au fonds d’investissement saoudien PIF pour 1,78 milliard de dollars, tout en conservant certaines unités via sa filiale OFI.',
        'https://directinfosgabon.com/production-agricole-olam-cede-tous-ses-actifs-africains-au-groupe-saoudien-pif/',
        'Direct infos Gabon',
        'Agriculture, Finances',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.225Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dc73b13-12d7-452d-b725-1fdb82727c8a',
        'Budget 2025 de la Commune de Libreville : entre réduction des moyens et ambitions de modernisation',
        'Le Conseil ad hoc de la Mairie de Libreville a adopté à l’unanimité le budget primitif 2025 de 25,12 milliards FCFA, conciliant réduction des moyens financiers et investissements majeurs dans la digitalisation pour moderniser les services municipaux.',
        'https://www.gabonreview.com/budget-2025-de-la-commune-de-libreville-entre-reduction-des-moyens-et-ambitions-de-modernisation/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.225Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b49f9a3-0cee-4b2f-b769-f87bc3beefa4',
        'Agriculture : Olam et le Gabon c’est fini',
        'Le groupe singapourien Olam se retire définitivement du Gabon en vendant ses filiales agricoles en Afrique après 26 ans d''activité dans le pays.',
        'https://gabonactu.com/blog/2025/02/27/agriculture-olam-et-le-gabon-cest-fini/',
        'Gabon Actu',
        'Agriculture, Business Femme, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.225Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '714c3688-2ee9-42b0-be1e-fdf01ac052c6',
        'Programme « Leaders de demain » d’Assala Gabon : 57 bénéficiaires depuis son lancement',
        'Assala Gabon a formé et employé 57 jeunes grâce à son programme « Leaders de demain », offrant une formation alternée entre théorie et pratique sur ses sites de production depuis 2022.',
        'https://directinfosgabon.com/programme-leaders-de-demain-dassala-gabon-57-beneficiaires-depuis-son-lancement/',
        'Direct infos Gabon',
        'Éducation, Services, Business Femme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.226Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c491a29e-6c9c-4066-87ee-bcdd53d6d1f3',
        'Gabon : Le soutien de Tony Elumelu au processus de développement',
        'Lors de sa visite au Gabon le 25 février 2025, Tony Elumelu, président du Groupe UBA et philanthrope, a réaffirmé son engagement à soutenir le développement national en finançant les jeunes entrepreneurs et des projets structurants, renforçant ainsi le partenariat public-privé avec le gouvernement gabonais.',
        'https://www.gabonreview.com/gabon-le-soutien-de-tony-elumelu-au-processus-de-developpement/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.226Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7641e66-ed01-4576-9b43-52237b50a739',
        'Ogooué-Lolo : Compte rendu parlementaire à Lastoursville sous le signe de l’échange et de la mobilisation',
        'Le 26 février 2025, le député de la transition Jean Eudes Régis Immongault Tatangani a présenté à Lastoursville un compte rendu parlementaire axé sur les préoccupations locales en éducation, santé et infrastructures, tout en encourageant la mobilisation pour les élections présidentielles à venir.',
        'https://kongossanews.info/ogooue-lolo-compte-rendu-parlementaire-a-lastoursville-sous-le-signe-de-lechange-et-de-la-mobilisation-2/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services, Finances',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.226Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bd15fc30-fb86-4141-baaf-ba5cecd9977d',
        'Elections : la plateforme C’Bon lance un recensement des gabonais inscrits sur la liste électorale',
        'La plateforme « C’Bon », dirigée par la ministre de la Pêche Nora Kassa, a lancé une caravane de recensement des électeurs inscrits à Libreville afin de lutter contre l''abstention et garantir leur participation aux élections du 12 avril 2025.',
        'https://gabonactu.com/blog/2025/02/27/elections-la-plateforme-cbon-lance-un-recensement-des-gabonais-inscrits-sur-la-liste-electorale/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.226Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44ff4952-4d4d-4de7-8cb4-75830a57c461',
        'ANPI-Gabon : Le budget 2025 fixé à 3 milliards de FCFA',
        'L''Agence Nationale de Promotion des Investissements du Gabon (ANPI-Gabon) a adopté un budget de 3 milliards de FCFA pour 2025, ajusté légèrement à la baisse par rapport à 2024 afin d''éviter les écarts budgétaires.',
        'https://directinfosgabon.com/anpi-gabon-le-budget-2025-fixe-a-3-milliards-de-fcfa/',
        'Direct infos Gabon',
        'Finances, Services',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.227Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef062a71-9cb7-4222-88f8-81e760568a8d',
        'Des Consultations nationales au ministère de la Culture et des Arts pour l’élaboration de la stratégie culturelle de la CEMAC et...',
        'Le ministère gabonais de la Culture et des Arts a organisé des consultations nationales réunissant des représentants de la CEMAC, de l’UNESCO et des acteurs culturels afin de développer la stratégie culturelle régionale et son plan d’action.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/des-consultations-nationales-au-ministere-de-la',
        'Gabonews',
        'Numérique / Digital, Services, Éducation, Culture',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.227Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '056bf964-0f2f-4ecc-8180-41f6333f25e3',
        'Gabon/Nations unies : Une réunion stratégique pour accélérer les Objectifs de développement durable',
        'Le 27 février 2025, le gouvernement gabonais et les Nations unies ont tenu une réunion stratégique à Libreville pour accélérer la mise en œuvre des Objectifs de développement durable en renforçant la gouvernance, la transition vers une économie verte et l’inclusion sociale.',
        'https://www.gabonreview.com/gabon-nations-unies-une-reunion-strategique-pour-accelerer-les-objectifs-de-developpement-durable/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture, Business Femme',
        '2025-02-27T00:00:00.000Z',
        '2025-09-15T23:06:12.227Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0bd50a12-f301-4a11-a482-b81355ebfedb',
        'Gabon : À la rescousse d’Ali Bongo, Nicole Assélé appelle à la réconciliation',
        'Nicole Assélé appelle à la réconciliation nationale au Gabon en dénonçant l’instrumentalisation des identités politiques et en exigeant la reconnaissance de l’héritage d’Ali Bongo.',
        'https://www.gabonreview.com/gabon-a-la-rescousse-dali-bongo-nicole-assele-appelle-a-la-reconciliation/',
        'Gabon Review',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.227Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f06335ff-decf-48c2-843e-732d09040131',
        'Présidentielle à venir : Au travail…',
        'La prochaine élection présidentielle au Gabon s''annonce compétitive et imprévisible, avec de nombreux candidats novices cherchant à se positionner face au président de la Transition et à renouveler le paysage politique.',
        'https://www.gabonreview.com/presidentielle-a-venir-au-travail/',
        'Gabon Review',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.228Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25f1c00d-8e27-411a-bc77-7d44174e396c',
        'ACER : La composition inégale et les critiques de Chérie Yoni Tsango Ngoussi sur la représentation féminine',
        'Chérie Yoni Tsango Ngoussi dénonce la sous-représentation féminine au sein de l’ACER du Gabon, appelant à une parité plus équilibrée conformément à la législation en vigueur.',
        'https://www.gabonews.com/fr/actus/politique/article/acer-la-composition-inegale-et-les-critiques-de',
        'Gabonews',
        'Business Femme, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.228Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38899fe7-f401-42d8-847d-c47a22308bf0',
        'Prestations sociales : La CNSS inaugure son Centre de formation',
        'La ministre des Affaires sociales a inauguré le Centre de formation de la CNSS à Akanda afin de renforcer les compétences des agents et d''améliorer la qualité des prestations sociales offertes aux assurés.',
        'https://directinfosgabon.com/prestations-sociales-la-cnss-inaugure-son-centre-de-formation/',
        'Direct infos Gabon',
        'Éducation, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.228Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8d3089b-bd37-4df7-9714-b9c511a7115a',
        'Olam Group Limited maintient ses activités au Gabon',
        'Olam Group Limited confirme la poursuite de ses activités au Gabon via ses filiales Olam Palm Gabon et Olam Rubber Gabon, malgré l''investissement partiel de SALIC.',
        'https://kongossanews.info/olam-group-limited-maintient-ses-activites-au-gabon/',
        'Kongossa News',
        'Agriculture, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.228Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd557a347-ec1f-4c12-9562-06b358cb74b9',
        'Air France et Afrijet signent un partenariat pour desservir Bangui et Port Harcourt',
        'Air France et Afrijet ont étendu leur partenariat commercial pour inclure de nouvelles liaisons vers Port Harcourt et Bangui via Libreville, améliorant ainsi la connectivité et offrant des avantages de voyage simplifiés aux passagers en Afrique centrale.',
        'https://directinfosgabon.com/air-france-et-afrijet-signent-un-partenariat-pour-desservir-bangui-et-port-harcourt/',
        'Direct infos Gabon',
        'Tourisme, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.229Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75150dc6-d290-4229-82e1-ddcdf71e2c51',
        'Vaalco fait le point sur ses projets au Gabon et fixe ses priorités pour 2025',
        'Vaalco a passé en revue l''exécution de ses projets pétroliers au Gabon en 2024 et a fixé ses priorités pour 2025, incluant un investissement de 3,8 milliards de FCFA dans les infrastructures et l''ambition de doubler sa production pétrolière.',
        'https://www.gabonreview.com/vaalco-fait-le-point-sur-ses-projets-au-gabon-et-fixe-ses-priorites-pour-2025/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce, Éducation, Agriculture',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.229Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3a7e92d-b07f-46e5-8187-85db12f2cb45',
        'Inscription exceptionnelle sur la liste électorale : une opportunité pour les citoyens concernés',
        'Le ministère de l’Intérieur et de la Sécurité a lancé une période exceptionnelle d’inscription sur la liste électorale du 1ᵉʳ au 10 mars 2025 destinée à divers groupes de citoyens afin de garantir un processus électoral transparent et inclusif en République gabonaise.',
        'https://www.gabonreview.com/inscription-exceptionnelle-sur-la-liste-electorale-une-opportunite-pour-les-citoyens-concernes/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.229Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

