-- Batch 5 - Section 18/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '8aab73ef-e629-42d3-8d4d-8857d355a451',
        'Publié le 12 / 07 / 2025',
        'Barro Chambrier appelle la majorité présidentielle à renforcer la cohésion et à unir leurs forces pour mieux gouverner et réaliser leurs ambitions.',
        'https://union.sonapresse.com/fr/formation-de-la-majorite-presidentielle-lappel-de-barro-chambrier',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2832ed77-1ff2-4fb7-a0a3-1ac1d85ec716',
        'Publié le 12 / 07 / 2025',
        'Le séjour d''Oligui Nguema aux États-Unis est considéré comme une réussite diplomatique, appréciée par la population locale.',
        'https://union.sonapresse.com/fr/sejour-doligui-nguema-aux-usa-un-succes-diplomatique-salue-par-les-populations',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e0275de2-fe2f-41ac-b9b4-6a14a230a2aa',
        'Publié le 12 / 07 / 2025',
        'La période de dépôt des candidatures pour les élections couplées se déroule du 27 juillet au 7 août, permettant aux candidats de soumettre leur dossier dans ce délai.',
        'https://union.sonapresse.com/fr/elections-couplees-depot-de-candidatures-du-27-juillet-au-07-aout-prochain',
        'L''union',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ceacdf18-4c62-49bb-8e42-68edbb85fc5c',
        'Changement climatique : Les milliards de dollars perdus de la forêt gabonaise',
        'La déforestation au Gabon, principal puits de carbone, entraîne une perte de milliards de dollars et nuit à la lutte contre le changement climatique.',
        'https://directinfosgabon.com/changement-climatique-les-milliards-de-dollars-perdus-de-la-foret-gabonaise/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5bf3aac-7238-4abb-8337-eb5841d80808',
        'Gabon : La dette publique a atteint 72,5 % du PIB en 2024',
        'La dette publique du Gabon a atteint 72,5 % du PIB en 2024, en augmentation par rapport à l’année précédente, ce qui reflète une détérioration de la situation financière du pays.',
        'https://directinfosgabon.com/gabon-la-dette-publique-a-atteint-725-du-pib-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3964d5d6-fec5-4cae-a9b9-e7ceba0ef231',
        'L’ANINF et ST Digital s’allient pour accélérer la transformation digitale',
        'L’ANINF et ST Digital ont signé un partenariat stratégique pour accélérer la transformation numérique du Gabon, en créant un écosystème digital plus sécurisé, transparent et innovant.',
        'https://directinfosgabon.com/laninf-et-st-digital-sallient-pour-accelerer-la-transformation-digitale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12d3522f-6d9a-464d-8987-e042a9db3472',
        'Sénégal : Ousmane Sonko s’en prend à Bissirou Diomaye Faye',
        'Lors d’un discours public, Ousmane Sonko a critiqué sévèrement le président sénégalais, remettant en question certaines décisions du gouvernement et suscitant des interrogations sur l’unité de l’exécutif.',
        'https://agpgabon.ga/senegal-ousmane-sonko-sen-prend-a-bissirou-diomaye-faye/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a69555fd-6858-4a6b-8aed-87d2e8837f48',
        'La richesse nationale du Gabon a atteint 63 000 milliards de FCFA en 2020 (Banque mondiale)',
        'La richesse totale du Gabon a atteint environ 63 000 milliards de FCFA en 2020, ayant augmenté de 35 % entre 1995 et 2020, grâce principalement aux ressources naturelles et à la croissance économique.',
        'https://directinfosgabon.com/la-richesse-nationale-du-gabon-a-atteint-63-000-milliards-de-fcfa-en-2020-banque-mondiale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c80985d2-1ada-43e2-8bb5-ddaf5595cc3a',
        'Ngounié/Projet de construction de l’université de Mouila : une réunion de consultation publique pour rendre le projet inclusif',
        'Une consultation publique a été organisée à Mouila pour recueillir l’avis des populations et des autorités locales sur la construction de la nouvelle université, afin d’intégrer les préoccupations sociales et économiques dans le projet.',
        'https://agpgabon.ga/ngounie-projet-de-construction-de-luniversite-de-mouila-une-reunion-de-consultation-publique-pour-rendre-le-projet-inclusif/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a2dbb8b-efce-4ead-803c-77889ca7463f',
        'Trump dit au président du Liberia, pays anglophone, qu’il parle bien anglais: il ne l’a “pas mal pris”',
        'Le président libérien Joseph Boakai a accueilli favorablement la remarque de Donald Trump sur son niveau d''anglais, la considérant comme une simple reconnaissance de l''influence linguistique des États-Unis dans son pays.',
        'https://brut-5857f8.brut.media/fr/articles/trump-dit-au-president-du-liberia-pays-anglophone-quil-parle-bien-anglais-il-ne-la-pas-mal-pris',
        'Flipboard',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca17b76e-0d06-41c8-bc7c-c5c254c8c4ae',
        'PDG : Ali Bongo Ondimba a-t-il désavoué Blaise Louémbé ?',
        'Une note largement partagée sur les réseaux sociaux, soi-disant signée par Ali Bongo, soulève des questions sur un éventuel désaveu de Blaise Louémbé par le président du PDG, mais la véracité de cette déclaration reste incertaine.',
        'https://gabonactu.com/blog/2025/07/12/pdg-ali-bongo-a-t-il-desavoue-blaise-louembe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8fc5e723-dc11-4029-8ba3-2a33cc6ffb4d',
        'Gabon/Législative et locales 2025 : Stephan Germain Iloko Boussengui dénonce des irrégularités sur le calendrier électoral',
        'Un responsable politique gabonais a dénoncé des irrégularités dans le calendrier officiel des élections législatives et locales de 2025, notamment le report de la période de dépôt des candidatures, et appelle au respect des règles légales.',
        'https://agpgabon.ga/gabon-legislative-et-locales-2025-stephan-germain-iloko-boussengui-denonce-des-irregularites-sur-le-calendrier-electoral/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf7fd80b-ab82-469c-a457-cfcd5e2c5389',
        'Gabon/Politique :  naissance d’une nouvelle dynamique citoyenne dénommée “la Majorité Bloquante”',
        'Un nouveau mouvement citoyen appelé «Majorité Bloquante» a été lancé à Libreville, visant à s’opposer aux modifications de la Constitution par le Parlement en se positionnant comme une force d’obstruction stratégique dans le processus démocratique.',
        'https://agpgabon.ga/gabon-politique-naissance-dune-nouvelle-dynamique-citoyenne-denommee-la-majorite-bloquante/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd60b5095-1976-461b-9e1e-280849eb7a23',
        'Législatives et locales 2025 : les 12 membres de la CNOCER en fonction depuis le 9 juillet',
        'Depuis le 9 juillet, douze membres de la Commission nationale de contrôle des élections et des référendums (CNOCER) ont été officiellement en fonction pour superviser les élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-les-12-membres-de-la-cnocer-en-fonction-depuis-le-9-juillet/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cbdf0025-f6f5-408a-868e-27d0c2195774',
        'Gabon : Oligui Nguema satisfait des résultats des examens scolaires en 2025 !',
        'Le président gabonais a exprimé sa satisfaction concernant les résultats positifs des examens scolaires pour l’année 2025, soulignant les progrès réalisés dans le système éducatif.',
        'https://gabonmediatime.com/gabon-oligui-nguema-satisfait-des-resultats-des-examens-scolaires-en-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2c07d76-c3bd-4af2-acf2-a2c0d40057ad',
        'Moov Africa Gabon Télécom : Momo e-tax, solution de paiement digital d’impôts',
        'Moov Africa Gabon et Gabon Telecom ont lancé MoMo e-Tax, une solution de paiement digital permettant aux usagers de régler facilement leurs impôts et taxes en utilisant leur téléphone mobile.',
        'https://gabonmediatime.com/moov-africa-gabon-telecom-momo-e-tax-solution-de-paiement-digital-dimpots/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75abcb0d-d541-40b6-92b3-7b3e11934562',
        'Echange entre Louise Pierrette Mvono et partenaires sociaux du ministère de la Planification et de la Prospective',
        'Une rencontre entre Louise-Pierrette Mvono et ses partenaires sociaux du ministère de la Planification et de la Prospective pour échanger sur la collaboration et le suivi des projets de développement.',
        'https://kongossanews.info/echange-entre-louise-pierrette-mvono-et-partenaires-sociaux-du-ministere-de-la-planification-et-de-la-prospective/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c5417f6-72d5-4d60-bf36-389d4effbf0c',
        'Espoir de Femmes au chevet des jeunes mamans du Centre Hospitalier Universitaire de Libreville.',
        'L’association Espoir de Femmes accompagne les jeunes mamans du centre hospitalier universitaire de Libreville en leur offrant un soutien psychologique, éducatif et social pour leur permettre de mieux préparer leur avenir et celui de leurs enfants.',
        'https://kongossanews.info/espoir-de-femmes-au-chevet-des-jeunes-mamans-du-centre-hospitalier-universitaire-de-libreville/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '221ed23c-a9ed-44c5-92bc-22cf19f2b3e2',
        'Lancement de la 4ᵉ édition du ‘’33’’ Export Corporate Championship',
        'La 4ᵉ édition du championnat « Export Corporate Championship » a été lancée, offrant aux entreprises une plateforme pour promouvoir leurs produits et renforcer leur présence à l’international.',
        'https://kongossanews.info/lancement-de-la-4%e1%b5%89-edition-du-33-export-corporate-championship/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91756d6a-8bfe-4d33-a955-e52e4fb93009',
        'Gabon/Bac Technologique et Professionnel : 1973 admis sur 3679 candidats au premier tour',
        'Environ 53,63 % des candidats ont été admis au premier tour du baccalauréat technologique et professionnel au Gabon, avec 1 973 admis sur 3 679 inscrits, ce qui représente une nette amélioration par rapport à l’année précédente.',
        'https://agpgabon.ga/gabon-bac-technologique-et-professionnel-1973-admis-sur-3679-candidats-au-premier-tour/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41eb8607-a52e-4c2d-8d10-7996bc6bb441',
        'Gabon/Omnisports : célébration de la journée olympique',
        'Le Comité national olympique du Gabon a organisé au Stade de l’amitié sino-gabonais une journée sportive pour célébrer la Journée olympique, en proposant diverses activités comme le basket, le tennis, la boxe ou l’athlétisme, afin de promouvoir les valeurs de l’olympisme auprès des jeunes.',
        'https://agpgabon.ga/gabon-omnisports-celebration-de-la-journee-olympique/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '37180f26-20bd-467c-a583-f74119b733e1',
        'Gabon/Mise à jour des dossiers administratifs : le Ministère des Affaires sociales lance une vaste opération de recensement pour ses agents',
        'Le ministère des Affaires sociales lance une opération de recensement pour mettre à jour les dossiers administratifs de ses agents, dans le but de régulariser leur situation.',
        'https://agpgabon.ga/gabon-mise-a-jour-des-dossiers-administratifs-le-ministere-des-affaires-sociales-lance-une-vaste-operation-de-recensement-pour-ses-agents/',
        'AGP',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4502781a-d6d1-449c-b6a9-b4701a5d5752',
        'Législatives et locales 2025 : les 12 membres de la CNOCER en fonction depuis le 9 juillet',
        'Depuis le 9 juillet, 12 membres de la CNEC (Commission nationale de la concertation électorale et de la réglementation) ont été désignés pour organiser les élections législatives et locales de 2025 au Gabon.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-les-12-membres-de-la-cnocer-en-fonction-depuis-le-9-juillet/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86f8910e-58d0-4548-9829-891dbe191ed6',
        'Gabon : Oligui Nguema satisfait des résultats des examens scolaires en 2025 !',
        'Le président gabonais a exprimé sa satisfaction concernant les résultats satisfaisants des examens scolaires en 2025, soulignant l''amélioration du système éducatif.',
        'https://gabonmediatime.com/gabon-oligui-nguema-satisfait-des-resultats-des-examens-scolaires-en-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e47bd8a1-e029-462a-b300-448b96241f06',
        'Moov Africa Gabon Télécom : Momo e-tax, solution de paiement digital d’impôts',
        'Moov Africa Gabon et Gabon Telecom proposent une solution de paiement numérique appelée Momo e-Tax, permettant aux utilisateurs de régler facilement leurs impôts et autres formalités administratives via leur téléphone.',
        'https://gabonmediatime.com/moov-africa-gabon-telecom-momo-e-tax-solution-de-paiement-digital-dimpots/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f3a33e5-71cc-4a87-82ce-2d9a2cb8bbbf',
        'Echange entre Louise Pierrette Mvono et partenaires sociaux du ministère de la Planification et de la Prospective',
        'Une rencontre a permis à Louise-Pierrette Mvono et aux partenaires sociaux du ministère de la Planification et de la Prospective d’échanger sur des projets visant à renforcer la coopération et le développement économique.',
        'https://kongossanews.info/echange-entre-louise-pierrette-mvono-et-partenaires-sociaux-du-ministere-de-la-planification-et-de-la-prospective/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff26706e-c143-4bef-be54-b8366cc13b1c',
        'Espoir de Femmes au chevet des jeunes mamans du Centre Hospitalier Universitaire de Libreville.',
        'Une association soutient les jeunes mamans en leur offrant des formations, un accompagnement psychologique et éducatif pour favoriser leur réinsertion et leur développement.',
        'https://kongossanews.info/espoir-de-femmes-au-chevet-des-jeunes-mamans-du-centre-hospitalier-universitaire-de-libreville/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c1dfbfac-abe1-4924-a287-6e2b28854cbb',
        'Lancement de la 4ᵉ édition du ‘’33’’ Export Corporate Championship',
        'La quatrième édition du championnat Export Corporate a été lancée pour promouvoir l''exportation et renforcer la compétitivité des entreprises africaines.',
        'https://kongossanews.info/lancement-de-la-4%e1%b5%89-edition-du-33-export-corporate-championship/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-12T00:00:00.000Z',
        '2025-09-15T23:06:12.471Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '690c70a4-ffae-452c-9c34-6ed26a924609',
        'Gabon/Baccalauréat général 2025 : un taux de réussite national de 30,24% au premier tour',
        'En 2025, le taux de réussite au premier tour du baccalauréat général au Gabon est de 30,24 %, avec 7 864 candidats admis d’office sur 26 005 participants.',
        'https://agpgabon.ga/gabon-baccalaureat-general-2025-un-taux-de-reussite-national-de-3024-au-premier-tour/',
        'AGP',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf65ea17-7da1-4acb-a022-dca919367d2b',
        'Gabon : retour du président après le sommet de Washington',
        'Le président gabonais est rentré à Libreville après avoir participé au sommet de Washington avec Donald Trump et d’autres chefs d’État africains, où ils ont abordé des questions de coopération et de développement.',
        'https://information.tv5monde.com/afrique/video/gabon-retour-du-president-apres-le-sommet-de-washington-2782666?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91ae967e-1720-466d-864e-861999c7ef8a',
        'Gabon : le président Oligui Nguema à Malabo pour prendre part aux travaux préparatoires du 7ᵉ sommet de coordination entre l’UA et le CER',
        'Le président gabonais Brice Clotaire Oligui Nguema s’est rendu à Malabo pour participer aux préparatifs du 7ᵉ sommet de coordination entre l’Union africaine, les communautés régionales et les mécanismes régionaux, notamment pour discuter de la gouvernance, des nominations et des partenariats internationaux.',
        'https://agpgabon.ga/gabon-le-president-oligui-nguema-a-malabo-pour-prendre-part-aux-travaux-preparatoires-du-7%e1%b5%89-sommet-de-coordination-entre-lua-et-le-cer/',
        'AGP',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '258a838f-ad73-4445-b4ee-5af624747a4f',
        'Au Gabon, comment Brice Clotaire Oligui Nguema a refaçonné son premier cercle',
        'Après son élection en avril, le président gabonais a profondément renouvelé son équipe et son entourage politique, en mettant notamment en retrait plusieurs proches pour tourner la page de son passé.',
        'https://www.jeuneafrique.com/1699250/politique/au-gabon-comment-brice-clotaire-oligui-nguema-a-refaconne-son-premier-cercle/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b72a603e-59dc-4137-af75-6c2310793cab',
        'Oligui Nguema à Malabo pour une réunion cruciale sur l’unité africaine',
        'Le président gabonais Brice Clotaire Oligui Nguema se rend à Malabo pour participer à une réunion importante sur l’unité africaine, impliquant l’Union africaine et diverses communautés économiques régionales.',
        'https://gabonactu.com/blog/2025/07/13/oligui-nguema-a-malabo-pour-une-reunion-cruciale-sur-lunite-africaine/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92b89653-dc98-45f3-9393-45ba54c7c585',
        'Affaire Bongo : «On ne fait pas de la justice, on fait du cinéma», dénonce Maître Sur',
        'Un avocat de la famille Bongo dénonce l’instrumentalisation de la justice au Gabon, affirmant que la procédure actuelle ressemble davantage à un spectacle qu’à une véritable justice.',
        'https://www.gabonreview.com/affaire-bongo-on-ne-fait-pas-de-la-justice-on-fait-du-cinema-denonce-maitre-sur/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f13aaca-b563-4714-bc21-efb3e5abac3e',
        'Baccalauréat 2025 : Réalité contrastée, espoirs suspendus',
        'Les résultats du baccalauréat 2025 au Gabon sont en baisse dans l’enseignement général avec seulement 33,13 % de réussite au premier tour, tandis que les filières techniques obtiennent de meilleures performances, ce qui inquiète sur l’état du système éducatif.',
        'https://www.gabonreview.com/baccalaureat-2025-realite-contrastee-espoirs-suspendus/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5319078a-6eaa-47e8-8137-536d4e369352',
        'Trois signaux d’alerte du FDS face aux dérives de la République',
        'Le Front Démocratique Socialiste (FDS) alerte sur des dérives institutionnelles en République, notamment la manipulation médiatique, un décret électoral jugé illégal et l''infiltration politique du corps judiciaire.',
        'https://www.gabonreview.com/trois-signaux-dalerte-du-fds-face-aux-derives-de-la-republique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '50a02675-b456-44d3-97de-2b457168ef59',
        'São Tomé : Alexandre Barro Chambrier représente le Gabon aux festivités du 50e anniversaire de l’indépendance',
        'Le Vice-Président gabonais, Alexandre Barro Chambrier, a représenté le président lors des célébrations du 50e anniversaire de l''indépendance de São Tomé-et-Principe, témoignant de bonnes relations entre les deux pays à travers un défilé militaire et culturel.',
        'https://agpgabon.ga/sao-tome-alexandre-barro-chambrier-represente-le-gabon-aux-festivites-du-50e-anniversaire-de-lindependance/',
        'AGP',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21a78d43-c3af-4b81-9a23-7ccfcefb3733',
        'Locales 2025 : la liste gagnante de la Coalition Akanda pour le Progrès',
        'Une coalition locale a présenté sa liste gagnante pour les élections de 2025, visant à promouvoir le progrès dans la région d’Akanda.',
        'https://gabonactu.com/blog/2025/07/13/locales-2025-la-liste-gagnante-de-la-coalition-akanda-pour-le-progres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a781b35-8da8-4620-b5eb-cd9bd45fe696',
        'Football/DGI : une Coupe pour célébrer la cohésion au sein de l’administration',
        'La Direction générale des Impôts a organisé un tournoi de football pour renforcer la cohésion et l’esprit d’équipe parmi ses agents, incluant des équipes masculines et féminines, et a couronné l’équipe du Centre-ville chez les hommes.',
        'https://agpgabon.ga/football-dgi-une-coupe-pour-celebrer-la-cohesion-au-sein-de-ladministration/',
        'AGP',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c480682-e3fd-40c4-ad28-2fed5d07d2ce',
        'Cameroun/Présidentielle : Les électeurs sont appelés aux urnes le 12 Octobre 2025',
        'Les électeurs camerounais sont appelés à voter le 12 octobre 2025 pour l’élection présidentielle, avec la période de dépôt des candidatures allant jusqu’au 21 juillet et la campagne électorale se déroulant fin septembre à début octobre.',
        'https://agpgabon.ga/cameroun-presidentielle-les-electeurs-sont-appeles-aux-urnes-le-12-octobre-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ea9a972-85fe-4a47-ae3b-7e24f815399a',
        'Réparations, ZLECAF et Washington : le triple message d’Oligui au sommet de Malabo',
        'Lors du sommet de Malabo, le président gabonais a prononcé un discours soulignant l''importance de la justice réparatrice, de l''intégration africaine pragmatique, tout en abordant les enjeux liés aux réparations, à la ZLECAF et aux relations avec Washington.',
        'https://www.gabonreview.com/reparations-zlecaf-et-washington-le-triple-message-doligui-au-sommet-de-malabo/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51f9f873-0115-478d-b72e-5ed4c6965947',
        'L''édition 2025 de la Coupe Oloupi n''aura pas lieu cette année',
        'L''édition 2025 de la Coupe Oloupi est annulée cette année, selon une annonce faite lors d''un déjeuner de presse par le président fondateur, Jean Paul Eyebe Lendoye.',
        'https://www.gabonews.com/fr/actus/societe/article/l-edition-2025-de-la-coupe-oloupi-n-aura-pas-lieu',
        'Gabonews',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e5b1a61-3f1c-4796-ab1e-624f641979c4',
        'Législatives et locales 2025 : ouverture des candidatures pour l’Autorité de contrôle des élections et du référendum',
        'Les candidatures pour la nomination des membres de l''Autorité de Contrôle des Élections et du Référendum seront ouvertes dans le cadre des élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-ouverture-des-candidatures-pour-lautorite-de-controle-des-elections-et-du-referendum/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b99023b2-d006-414e-bb88-9aacdf049b05',
        'BAC Général 2025 : 12 154 admissibles attendus au 2e tour !',
        'Pour le baccalauréat général de 2025 au Gabon, 154 candidats ont été admis lors du deuxième tour, avec 12.154 admissibles attendus.',
        'https://gabonmediatime.com/bac-general-2025-12-154-admissibles-attendus-au-2e-tour/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ac155c8-f0b6-4ae1-a58a-e3375526dae3',
        'BAC Général 2025 : 23,02%, le taux d’échec au premier tour',
        'Le taux d''échec au premier tour du bac général en 2025 est de 23,02 %, une augmentation par rapport à l''année précédente.',
        'https://gabonmediatime.com/bac-general-2025-2302-le-taux-dechec-au-premier-tour/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24ab039d-4bb8-4147-9d5c-8ef1477cb8f8',
        'Le Gabon signe son grand retour au sein de l’Union africaine et plaide pour une Afrique unie et ambitieuse',
        'Le Gabon a officiellement réintégré l''Union africaine, plaidant pour une Afrique unie, ambitieuse et plus présente sur la scène internationale.',
        'https://kongossanews.info/le-gabon-signe-son-grand-retour-au-sein-de-lunion-africaine-et-plaide-pour-une-afrique-unie-et-ambitieuse/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeb94757-cdd8-444a-8e35-0279146b4ce1',
        'À Ndjolé, Yannick Mefane mobilise pour l’action et redonne espoir aux populations',
        'Ndjole Yannick Mefane mobilise les populations pour agir et leur redonne espoir face aux défis qu''elles rencontrent.',
        'https://kongossanews.info/a-ndjole-yannick-mefane-mobilise-pour-laction-et-redonne-espoir-aux-populations/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16015e67-f17b-4573-8a5b-96b315b0444e',
        'Brice Clotaire Oligui Nguema à Malabo pour le 7ᵉ sommet de coordination de l''Union africaine',
        'Le président Brice Clotaire Oligui Nguema s’est rendu à Malabo pour participer aux préparatifs du 7ᵉ sommet de coordination entre l’Union africaine, les Communautés économiques régionales et les mécanismes régionaux, notamment sur la gouvernance de l’Union africaine.',
        'https://www.gabonews.com/fr/actus/cooperation/article/brice-clotaire-oligui-nguema-a-malabo-pour-le',
        'Gabonews',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e06417a-7df6-450d-ac82-54952006a95d',
        'Législatives et locales 2025 : ouverture des candidatures pour l’Autorité de contrôle des élections et du référendum',
        'Les candidatures pour l''autorité de contrôle des élections et du référendum sont ouvertes en vue des élections législatives et locales de 2025.',
        'https://gabonmediatime.com/legislatives-et-locales-2025-ouverture-des-candidatures-pour-lautorite-de-controle-des-elections-et-du-referendum/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81dc0de3-833a-4516-bdd5-51b2f9ecf003',
        'BAC Général 2025 : 12 154 admissibles attendus au 2e tour !',
        'Pour l''examen du baccalauréat général 2025 au Gabon, 154 candidats sont admis au deuxième tour sur un total de 12 154 inscrits.',
        'https://gabonmediatime.com/bac-general-2025-12-154-admissibles-attendus-au-2e-tour/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-13T00:00:00.000Z',
        '2025-09-15T23:06:12.472Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

