-- Batch 7 - Section 12/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '2f074f42-5fd0-4816-b802-4c0ea6f957a3',
        'Haut-Ogoouée : les Affaires sociales au chevet des personnes vulnérables à Bongoville',
        'La Direction des Affaires sociales du Haut-Ogooué a organisé une opération de solidarité à Bongoville pour venir en aide aux populations vulnérables, notamment celles en situation de précarité ou de handicap, dans le but d''améliorer leurs conditions de vie et promouvoir l''inclusion.',
        'https://agpgabon.ga/haut-ogoouee-les-affaires-sociales-au-chevet-des-personnes-vulnerables-a-bongoville/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.495Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd78d29f6-9ea0-4809-a2ee-f54ca2e88eb3',
        '« Oser mon projet » : Le lauréat du 1er Prix et 9 autres jeunes entrepreneurs honorés',
        'Un concours appelé "Oser mon projet" a récompensé un jeune entrepreneur et huit autres innovateurs lors de sa première édition, après un mois de travaux.',
        'https://gabonactu.com/blog/2025/08/21/oser-mon-projet-le-laureat-du-1er-prix-et-9-autres-entrepreneurs-honores/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.495Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffe64749-5acd-4ed8-9b97-3d3de59c425a',
        'Listes des candidats aux législatives 2025 : Ensemble Pour le Gabon dénonce',
        'L’opposition dénonce des irrégularités dans la publication des listes de candidats pour les législatives de 2025 par le ministère de l’Intérieur.',
        'https://gabonactu.com/blog/2025/08/21/listes-des-candidats-aux-legislatives-2025-ensemble-pour-le-gabon-denonce/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'febe3902-4690-4c0c-be27-f1f007e97293',
        'Lancement du projet « Lumière sur le Gabon » et sortie du premier ouvrage consacré au raphia',
        'Le projet culturel « Lumière sur le Gabon » a été lancé pour valoriser le patrimoine gabonais, notamment avec la sortie du premier ouvrage dédié au raphia, une fibre naturelle importante dans la région.',
        'https://gabonactu.com/blog/2025/08/21/lancement-du-projet-lumiere-sur-le-gabon-et-du-premier-ouvrage-consacre-au-rafia/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81fccb59-8299-4fb4-9b96-cd64741788b2',
        'Législatives 2025 : au moins 23 candidats pour les deux sièges de députés des Gabonais de l’étranger',
        'Pour la première fois, deux sièges au Parlement gabonais seront réservés à des députés représentant la diaspora, avec au moins 23 candidats en lice pour ces postes lors des prochaines élections législatives de 2025.',
        'https://www.gabonreview.com/legislatives-2025-au-moins-23-candidats-pour-les-deux-sieges-de-deputes-des-gabonais-de-letranger/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '663befc6-cae2-492e-978f-eaeda61f1a8a',
        'Législatives et locales 2025 : rejet en cascade des requêtes par la Cour constitutionnelle',
        'La Cour constitutionnelle du Gabon a rejeté, le 19 août 2025, plusieurs requêtes de partis politiques contestant certaines dispositions législatives et électorales, à l''approche des élections législatives et locales prévues en septembre.',
        'https://www.gabonreview.com/legislatives-et-locales-2025-rejet-en-cascade-des-requetes-par-la-cour-constitutionnelle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '26975db9-d157-4c7a-ab90-9f244714469f',
        '«Kasongo Yéyé» : de la complainte féminine de 1977 à l’hymne viral d’une génération',
        'Une chanson de détresse en lingala datant de 1977 est devenue en 2024 un symbole viral et humoristique sur Internet, évoquant autant une plainte personnelle qu’une référence culturelle populaire à travers différentes générations.',
        'https://www.gabonreview.com/kasongo-yeye-de-la-complainte-feminine-de-1977-a-lhymne-viral-dune-generation/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40689ecc-bce6-47f9-9482-0be53a50a38b',
        'Rwanda : La diaspora gabonaise célèbre l’indépendance à travers la première Coupe du Président Oligui Nguema',
        'Pour célébrer le 65e anniversaire de son indépendance, la diaspora gabonaise au Rwanda a organisé une compétition sportive originale, baptisée la première Coupe du Président Oligui Nguema.',
        'https://gabonactu.com/blog/2025/08/21/rwanda-la-diaspora-gabonaise-celebre-lindependance-a-travers-la-premiere-coupe-du-president-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78fd33e3-63d1-448e-ba32-4f78df1d1b80',
        'Victime d’AVC, Féfé Onanga  demeure debout pour soutenir l’action d’Oligui Nguéma',
        'Féfé Onanga, leader politique dans la province de l’Ogooué Maritime, se remet d’un AVC tout en affirmant son soutien à Oligui Nguéma malgré ses difficultés de santé.',
        'https://gabonactu.com/blog/2025/08/21/victime-davc-fefe-onanga-demeure-debout-pour-soutenir-laction-doligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '148023ed-23b9-40fe-8448-ef99b12095a6',
        'Législatives : 9 face-à-face et 2 alliances pour le PDG et l’UDB dans le Haut-Ogooué',
        'Plusieurs candidats se disputent environ dix sièges dans la province du Haut-Ogooué lors des législatives, avec notamment une confrontation entre le parti au pouvoir et l’opposition dans des alliances et des face-à-face.',
        'https://www.gabonreview.com/legislatives-9-face-a-face-et-2-alliances-pour-le-pdg-et-ludb-dans-le-haut-ogooue/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '42985787-86c0-4cb0-98ae-953c2dbcdc77',
        'Accident mortel près de l’aéroport Léon Mba : le ministre Onanga Ndiaye dément toute implication de son cortège',
        'Un homme a perdu la vie dans un accident de la route près de l''aéroport Léon Mba de Libreville, après avoir été apparemment fauché lors du passage d’un cortège, que le ministre Onanga Ndiaye a nié toute implication.',
        'https://www.gabonreview.com/accident-mortel-pres-de-laeroport-leon-mba-le-ministre-onanga-ndiaye-dement-toute-implication-de-son-cortege/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4802f9e6-cf07-4315-982a-325c8c7389d5',
        'Gabon/Transport maritime : la CNNII met fin à sa collaboration avec le Groupe EBOMAF',
        'La CNNII a mis fin à son partenariat avec le groupe EBOMAF après une évaluation conjointe, tout en assurant que cette décision n’affectera pas la régularité de ses activités.',
        'https://agpgabon.ga/gabon-transport-maritime-la-cnnii-met-fin-a-sa-collaboration-avec-le-groupe-ebomaf/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeef741a-7042-4819-9544-2a123ce7d999',
        'Maroc : la Fondation Mohamed VI des sciences et la santé entre un peu plus dans l’histoire',
        'La Fondation Mohammed VI des Sciences et de la Santé a réussi pour la première fois au Maroc à transformer des cellules sanguines en cellules souches, ouvrant ainsi de nouvelles possibilités pour la recherche médicale et la médecine personnalisée.',
        'https://agpgabon.ga/maroc-la-fondation-mohamed-vi-des-sciences-et-la-sante-entre-un-peu-plus-dans-lhistoire/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0729c23e-c280-4824-8052-4624df3bac78',
        'Gabon–Bénin : l’économie locale s’organise, apaisons le débat, restons frères',
        'Les pays de Gabon et du Bénin travaillent à renforcer leur coopération économique locale en favorisant le dialogue et la fraternité pour stimuler leur développement.',
        'https://gabonactu.com/blog/2025/08/21/gabon-benin-leconomie-locale-sorganise-apaisons-le-debat-restons-freres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'edbd38fd-3fbc-42f9-bd44-596cb2286863',
        'Mouila/Santé : lancement de la campagne de médecine itinérante “Ngounié Santé 2025”',
        'Une campagne de médecine itinérante nommée “Ngounié Santé 2025” sera organisée du 22 août au 24 octobre 2025 dans la province de Ngounié, offrant des consultations médicales gratuites dans tous ses neuf départements.',
        'https://agpgabon.ga/mouila-sante-lancement-de-la-campagne-de-medecine-itinerante-ngounie-sante-2025/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'baa49fff-d75f-4474-a903-4d71b8d6d489',
        'Gabon : des perturbations en desserte  d’eau potable ce vendredi à Ntoum et Libreville',
        'Une opération de maintenance sur un château d’eau à Ntoum entraînera ce vendredi des perturbations dans la distribution d’eau potable à Ntoum, Libreville et dans certaines zones environnantes, afin d’entretenir et sécuriser les infrastructures.',
        'https://agpgabon.ga/gabon-des-perturbations-en-desserte-deau-potable-ce-vendredi-a-ntoum-et-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c90c372-c5af-4f91-8da9-89137615a4be',
        'Gabon/Basket-ball : l’entraineur Ambroise Ambourouet et le joueur Tracy Minko s’expliquent sur l’incident',
        'Un incident entre l’entraîneur Ambroise Ambourouet et le joueur Tracy Minko au sein du club NABA a conduit à une suspension, mais ils expliquent tous deux que la situation n’a pas été préméditée et que l’entraînement s’est déroulé dans un contexte tendu.',
        'https://agpgabon.ga/gabon-basket-ball-lentraineur-ambroise-ambourouet-et-le-joueur-tracy-minko-sexpliquent-sur-lincident/',
        'AGP',
        'Business Intelligence',
        '2025-08-21T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98382155-ab8f-4f9c-96f5-5e51e6aa69ef',
        'Port-Gentil : Brice Ngoma Paka vole 4 millions de FCFA pour espérer sortir sa famille de la misère',
        'Brice Ngoma Paka a volé 4 millions de FCFA à Port-Gentil dans le but de financer l’avenir de sa famille et de la sortir de la pauvreté.',
        'https://gabonactu.com/blog/2025/08/21/port-gentil-brice-ngoma-paka-vole-4-millions-de-fcfa-pour-esperer-sortir-sa-famille-de-la-misere/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65bf8a30-baf7-4401-8a39-469b1d08e4e9',
        'Opinion / L’insécurité contractuelle : le poison de notre économie',
        'L''insécurité contractuelle, c''est-à-dire le fait que les engagements et contrats ne sont pas toujours respectés ou sécurisés, nuit au développement économique au Gabon et freine la confiance des entrepreneurs.',
        'https://directinfosgabon.com/opinion-linsecurite-contractuelle-le-poison-de-notre-economie/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a45aa66d-7fa3-4b9a-b0f7-b50a509d5b55',
        'Pétrole : Panoro Energy prévoit une hausse de ses revenus au 2e semestre 2025',
        'Panoro Energy prévoit une augmentation de ses revenus au second semestre 2025 grâce à une hausse de sa production, malgré quelques difficultés en Equateur.',
        'https://directinfosgabon.com/petrole-panoro-energy-prevoit-une-hausse-de-ses-revenus-au-2e-semestre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb634134-61ac-40b7-80fe-a26d5e01d39d',
        'Grand Prix de l’Entrepreneuriat Gabon 2025 : Jusqu’à 5 millions de FCFA pour les lauréats',
        'Environ 100 jeunes entrepreneurs gabonais ont été récompensés lors du Grand Prix de l’Entrepreneuriat Gabon 2025, parmi plus de 1 200 candidatures, avec des prix en argent allant jusqu’à 5 millions FCFA pour les meilleurs.',
        'https://directinfosgabon.com/grand-prix-de-lentrepreneuriat-gabon-2025-jusqua-5-millions-de-fcfa-pour-les-laureats/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55365099-d3f2-45af-aa8f-f971986144ea',
        'Publié le 21 / 08 / 2025',
        'En 100 jours, le gouvernement d''Ongui Nguema a non seulement dirigé le pays, mais aussi réveillé la fierté et l''espoir du peuple gabonais.',
        'https://union.sonapresse.com/fr/oligui-nguema-en-100-jours-nous-navons-pas-seulement-gouverne-nous-avons-reveille-lame-du-gabon',
        'L''union',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e8f454af-5114-4b1a-9cd7-48fa36adeb17',
        'Publié le 21 / 08 / 2025',
        'L''Union pour la démocratie et le progrès social (UDPS) est en tête des alliances politiques lors des législatives, consolidant sa popularité et son influence en République démocratique du Congo.',
        'https://union.sonapresse.com/fr/legislatives-ludb-en-tete-des-alliances',
        'L''union',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '50b4f7f4-c121-4b68-8d3d-f5bd7b316bda',
        'Publié le 21 / 08 / 2025',
        'Les candidats aux législatives au Sénégal naviguent entre ambitions personnelles et stratégies pour assurer leur survie politique face aux défis du contexte local.',
        'https://union.sonapresse.com/fr/legislatives-entre-ambitions-et-strategies-de-survie',
        'L''union',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ea7e1292-819e-4a08-8325-581d956babe5',
        'Transport maritime : ce que cache la fin de relation entre la CNNII et le groupe EBOMAF',
        'La relation entre la Cnnii et le groupe Ebomaf dans le secteur maritime en Guinée se termine, mettant fin à leur collaboration.',
        'https://mediapostegabon.com/transport-maritime-fin-de-relation-entre-la-cnnii-et-le-groupe-ebomaf/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31c1452d-b4e9-4be1-82ee-efd7c2f83d93',
        'Makouké/ rupture amiable : Olam et le déni de l’article 77 du Code du travail gabonais ? DGCCRF/Grève : la charrue avant les bœu...',
        'L''article explique comment une rupture à l''amiable en droit gabonais peut contourner le principe de l''article 77 du code du travail, tout en soulevant les enjeux juridiques et pratiques liés à cette procédure.',
        'https://mediapostegabon.com/makouke-rupture-amiable-olam-et-le-deni-de-larticle-77-du-code-du-travail-gabonais/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a7ef265-2e5b-454f-b176-c672eae61261',
        '[Vos réactions] La Libre Antenne du 22 août 2025',
        'L''émission invite les auditeurs à réagir sur des sujets peu médiatisés, permettant d''aborder des thèmes importants mais souvent absents du débat public.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250822-vos-r%C3%A9actions-la-libre-antenne-du-22-ao%C3%BBt-2025',
        'RFI',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a4453ef-cdba-49f3-94e1-fec406b130b8',
        'Actes de sabotage de la SEEG : Les coupables toujours introuvables…',
        'Plus de deux mois après une série de coupures d''électricité suspectées de sabotage, les résultats de l''enquête menée par le gouvernement n''ont toujours pas été dévoilés, laissant les responsables introuvables.',
        'https://directinfosgabon.com/actes-de-sabotage-de-la-seeg-les-coupables-toujours-introuvables/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ea61128d-8bb5-48e1-b3cd-c560b4953867',
        'Moov Money et Airtel Money : 50,8 milliards de FCFA de chiffre d’affaires en 2024',
        'Le secteur du mobile money au Gabon a atteint un chiffre d''affaires de 50,86 milliards de FCFA en 2024, grâce aux opérations quotidiennes de dépôts, retraits, paiements et transferts effectués par les principaux opérateurs, Moov Money et Airtel Money.',
        'https://directinfosgabon.com/moov-money-et-airtel-money-508-milliards-de-fcfa-de-chiffre-daffaires-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '26b29774-5b05-4385-9efa-267db12823b4',
        'Exploitation forestière : La production en chute de 34 % en 2024',
        'La production forestière en 2024 a chuté de près de 35 %, atteignant environ 2,3 millions de mètres cubes, en raison de l’impact négatif de l’exploitation illégale et des difficultés dans le secteur.',
        'https://directinfosgabon.com/exploitation-forestiere-la-production-en-chute-de-34-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44dabb05-2bb8-46a6-91df-b8d1c02a0411',
        'Oligui Nguema : « tous les chantiers arriveront à leur terme »',
        'Oligui Nguema assure que tous les projets en cours progresseront jusqu''à leur achèvement, malgré les défis rencontrés.',
        'https://gabonmediatime.com/oligui-nguema-tous-les-chantiers-arriveront-a-leur-terme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '954c68d0-212d-4e5b-a8a1-89e632a77ee5',
        'Port-Gentil : quand les contrôles routiers nourrissent plus l’exaspération que la sécurité',
        'Les contrôles routiers à Port-Gentil suscitent davantage la colère des conducteurs que leur sentiment de sécurité, en raison de leur fréquence et des pratiques parfois perçues comme abusives.',
        'https://gabonmediatime.com/port-gentil-quand-les-controles-routiers-nourrissent-plus-lexasperation-que-la-securite/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd029d7a-fafe-4172-bb07-aa20c39c37e5',
        'Gabon : Oligui Nguema déplore la passivité des jeunes en matière d’entrepreneuriat',
        'Oligui Nguema déplore le manque de motivation des jeunes gabonais à se lancer dans l''entrepreneuriat et appelle à renforcer leur esprit d''initiative.',
        'https://gabonmediatime.com/gabon-oligui-nguema-deplore-la-passivite-des-jeunes-en-matiere-dentrepreneuriat/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '182016f6-0dac-420d-812c-8c279993c287',
        'Transport maritime : ce que cache la fin de relation entre la CNNII et le groupe EBOMAF',
        'La fin de la collaboration entre la CNI-NN et le groupe Ebomaf marque la rupture d''un partenariat stratégique dans le secteur maritime, affectant la gestion et le développement des activités.',
        'https://mediapostegabon.com/transport-maritime-fin-de-relation-entre-la-cnnii-et-le-groupe-ebomaf/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a9f1cfd-649b-40c3-815f-ec0a03406cc8',
        'Makouké/ rupture amiable : Olam et le déni de l’article 77 du Code du travail gabonais ? DGCCRF/Grève : la charrue avant les bœu...',
        'L’article explique que la rupture à l’amiable chez Olame peut ne pas respecter l’article 77 du Code du travail gabonais, mettant en cause la légitimité de cette procédure dans certains cas.',
        'https://mediapostegabon.com/makouke-rupture-amiable-olam-et-le-deni-de-larticle-77-du-code-du-travail-gabonais/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14767ff0-5a57-4229-aa01-33506cd7b677',
        'Programme Construire piloté par la SNI : Oligui Nguema touche du doigt l’avancement des travaux',
        'Le président Brice Clotaire Oligui Nguema s''est rendu sur le chantier du programme Construire piloté par la SNI pour constater l’avancement des travaux.',
        'https://gabonactu.com/blog/2025/08/22/programme-construire-pilote-par-la-sni-oligui-nguema-touche-du-doigtlavancement-des-travaux/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fefc7dd2-1cab-4c6c-b70f-3d310a1c81d5',
        'Le Gabon pays le plus cher d’Afrique en 2025 sur les taxes aéroportuaires (rapport)',
        'Le Gabon sera en 2025 le pays d’Afrique où les taxes aéroportuaires seront les plus élevées, selon un rapport de l’Association des compagnies aériennes africaines.',
        'https://gabonactu.com/blog/2025/08/22/le-gabon-pays-le-plus-cher-dafrique-en-2025-sur-les-taxes-aeroportuaires-rapport/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b58350e4-d6d9-4818-8761-2f4a149381bb',
        'Oligui Nguema : « tous les chantiers arriveront à leur terme »',
        'Oligui Nguema affirme que tous les projets en cours dans le pays atteindront leur achèvement dans les délais prévus.',
        'https://gabonmediatime.com/oligui-nguema-tous-les-chantiers-arriveront-a-leur-terme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cce8fa5f-3584-4f83-af58-2565a93da172',
        'Port-Gentil : quand les contrôles routiers nourrissent plus l’exaspération que la sécurité',
        'Les contrôles routiers à Port-Gentil provoquent plus de frustration chez les conducteurs que d''amélioration de la sécurité, en raison de pratiques perçues comme abusives ou inefficaces.',
        'https://gabonmediatime.com/port-gentil-quand-les-controles-routiers-nourrissent-plus-lexasperation-que-la-securite/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1192c416-ffdd-452c-9a06-e5713620d44d',
        'Gabon : Oligui Nguema déplore la passivité des jeunes en matière d’entrepreneuriat',
        'Les jeunes gabonais sont peu actifs dans l’entrepreneuriat, ce qui désole les responsables, qui appellent à une plus grande motivation et engagement pour dynamiser l’initiative entrepreneuriale dans le pays.',
        'https://gabonmediatime.com/gabon-oligui-nguema-deplore-la-passivite-des-jeunes-en-matiere-dentrepreneuriat/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65d34c21-df5d-45fd-b6ce-d04f2f7fbea3',
        'Eliminatoires Mondial 2026 : Le sifflet de Tanguy Mébiame pour Somalie – Guinée',
        'Un arbitre gabonais, Tanguy Mébiame, a été choisi par la FIFA pour diriger un match des éliminatoires de la Coupe du Monde 2026 entre la Somalie et la Guinée.',
        'https://gabonactu.com/blog/2025/08/22/eliminatoires-mondial-2026-le-sifflet-de-tanguy-mebiame-pour-somalie-guinee/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f5b868b1-4be2-4f84-8294-4649c6861eff',
        'Port-Gentil : Bryan Koumba alias Daouda Saoul envoyé au gnouf pour vol',
        'Un jeune Gabonais de 19 ans, Bryan Koumba alias Daouda Saoul, a été arrêté à Port-Gentil pour avoir commis un vol, et il a été ensuite envoyé en prison.',
        'https://gabonactu.com/blog/2025/08/22/port-gentil-bryan-koumba-alias-daouda-saoul-envoye-au-gnouf-pour-vol/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4073d1c-4c79-41ed-88e9-a8c557642b68',
        'Extradition : Outiller les praticiens, renforcer le cadre législatif et la coopération internationale',
        'Un atelier de trois jours à l’École nationale de la magistrature a permis de renforcer les compétences des praticiens et d’améliorer la législation et la coopération internationale en matière d’extradition.',
        'https://gabonactu.com/blog/2025/08/22/extraditions-outiller-les-praticiens-renforcer-le-cadre-legislatif-et-la-cooperation-internationale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24d00443-ccae-4647-873d-215f52e77870',
        'Gabon : champion continental des taxes aériennes',
        'En 2024, le Gabon affiche le coût élevé des taxes aériennes en Afrique, avec 297,7 dollars par billet international, ce qui soulève des questions sur l''accessibilité et la compétitivité du transport aérien dans le pays.',
        'https://www.gabonreview.com/gabon-champion-continental-des-taxes-aeriennes/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06cdfdb2-05da-409d-9b27-a7cc80342ea7',
        'Poste SA : les agents privés de salaire depuis juin, le Synaposte interpelle Oligui Nguema',
        'Les agents de La Poste au Gabon sont privés de leurs salaires depuis juin 2025 en raison d''une crise de gouvernance dans l''entreprise, ce que le syndicat Synaposte a dénoncé en appelant à une intervention du gouvernement.',
        'https://www.gabonreview.com/poste-sa-les-agents-prives-de-salaire-depuis-juin-le-synaposte-interpelle-oligui-nguema/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1aefa528-f718-44f7-b720-aea843f6ed40',
        'Logement accessible pour tous: OLIGUI NGUEMA promeut le programme « Construire »',
        'Le président Brice Clotaire OLIGUI NGUEMA a visité le projet « Construire » à Akieni, où il a constaté l’avancement des travaux et visité la première maison témoin, dans le but de promouvoir un logement accessible à tous.',
        'https://vxp241.com/2025/08/22/logement-accessible-pour-tous-oligui-nguema-promeut-le-programme-construire/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '150575bd-e07f-40f8-bbe7-694f074a1826',
        'Caravane touristique 2025 : Eramet – Comilog, de la partie',
        'Des représentants du groupe Eramet et de sa filiale gabonaise Comilog participent à la deuxième édition de la Caravane touristique 2025, qui explore différentes régions de la région.',
        'https://gabonactu.com/blog/2025/08/22/caravane-touristique-2025-eramet-comilog-de-la-partie/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '64f84607-daf5-49f2-a270-e313e41d576d',
        'Candidatures du PNTP « rejetées » : Jean Rémy Yama hausse le ton',
        'Jean Rémy Yama, président du PNTP, a protesté vivement contre le rejet de plusieurs candidatures de son parti et a exigé la démission du ministre de l''Intérieur.',
        'https://www.gabonreview.com/candidatures-du-pntp-rejetees-jean-remy-yama-hausse-le-ton/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f442505b-a6ee-40f6-ab83-35f3f101b3b2',
        'Gabon / Élections 2025 : Jean Rémy Yama réclame des explications sur la non-validation des candidatures du PNTP',
        'Le président du PNTP a dénoncé le rejet de plusieurs de ses candidatures aux élections législatives et locales de septembre 2025 et a demandé des explications sur cette non-validation.',
        'https://agpgabon.ga/gabon-elections-2025-jean-remy-yama-reclame-des-explications-sur-la-non-validation-des-candidatures-du-pntp/',
        'AGP',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e261fdbf-071c-4f94-8cff-ff5a76ef20b2',
        'Haut-Ogooué / Caravane : Eramet Comilog participe à la 2ᵉ édition de la Caravane Touristique dans le G2',
        'Eramet Comilog a participé à la deuxième édition de la caravane touristique dans la province du Haut-Ogooué, en mobilisant une cinquantaine d''enfants issus de son personnel pour leur faire découvrir différentes localités tout en leur offrant une expérience d’apprentissage et de partage.',
        'https://agpgabon.ga/haut-ogooue-caravane-eramet-comilog-participe-a-la-2%e1%b5%89-edition-de-la-caravane-touristique-dans-le-g2/',
        'AGP',
        'Business Intelligence',
        '2025-08-22T00:00:00.000Z',
        '2025-09-15T23:06:12.496Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

