-- Batch 6 - Section 11/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '7a17ecb5-e7a2-415d-8a60-1560772f0bdc',
        'Drame conjugal à Bongoville : Il abat sa compagne, puis se donne la mort',
        'Un homme a tué sa compagne et s’est ensuite suicidé dans la commune de Bongoville, dans un acte de violence conjugale très grave.',
        'https://www.gabonreview.com/drame-conjugal-a-bongoville-il-abat-sa-compagne-puis-se-donne-la-mort/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6b1d6da6-c4bf-4abf-baf3-3a081c423614',
        'Élections 2025 : Immongault donne le ton pour une CNOCER exemplaire',
        'Le ministre de l’Intérieur, Hermann Immongault, a dirigé une réunion avec les responsables électoraux pour préparer efficacement les prochaines élections législatives et locales.',
        'https://www.gabonreview.com/elections-2025-immongault-donne-le-ton-pour-une-cnocer-exemplaire/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e925d3ef-5eb7-486d-83fb-8296263e19da',
        'Fausse identité, vraie criminalité : trois trafiquants d’ivoire sous les verrous',
        'Trois individus ont été arrêtés à Port-Gentil pour trafic d’animaux protégés, notamment de trophées d’ivoire, lors d’une opération menée par la police, la lutte contre le braconnage et une ONG.',
        'https://www.gabonreview.com/fausse-identite-vraie-criminalite-trois-trafiquants-divoire-sous-les-verrous/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd3ab7c40-cc90-43b2-82e9-35eb67a36d51',
        'Élections législatives et locales 2025 : 88 présidents de commissions électorales dotés de moyens roulants',
        'Le gouvernement a remis des moyens de transport aux 88 présidents des commissions électorales locales pour préparer les élections législatives et locales prévues en septembre 2025.',
        'https://agpgabon.ga/elections-legislatives-et-locales-2025-88-presidents-de-commissions-electorales-dotes-de-moyens-roulants/',
        'AGP',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f56bf57-1eac-428a-85b6-9ac5df781c5d',
        'Port-Gentil:  arrestations de trois gabonais pour trafique d’Ivoire',
        'Trois Gabonais ont été arrêtés lors d''une opération conjointe contre le trafic d''ivoire à Port-Gentil, avec le soutien d''une ONG et des autorités locales.',
        'https://gabonactu.com/blog/2025/07/27/port-gentil-arrestations-de-trois-gabonais-pour-trafique-divoire/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff2ffd33-e204-4071-803d-b48281a55098',
        'Gabon : disparition inquiétante d’un enseignant à Ndjolé',
        'Un enseignant de 42 ans, Éloge Awong Meka, est porté disparu depuis le 23 juillet à Ndjolé, alors qu''il revenait à son école dans la province du Moyen-Ogooué.',
        'https://agpgabon.ga/gabon-disparition-inquietante-dun-enseignant-a-ndjole/',
        'AGP',
        'Business Intelligence',
        '2025-07-27T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4b576121-cb0e-4514-a855-c5558f9f8d39',
        'Publié le 27 / 07 / 2025',
        'La course aux élections législatives de 2025 au Sénégal commence le 27 juillet, marquant le début de la préparation des candidats pour ce scrutin important.',
        'https://union.sonapresse.com/fr/legislatives-2025-la-course-debute-ce-27-juillet',
        'L''union',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'afbe5793-d531-4c69-9180-8f04325766f8',
        'Publié le 27 / 07 / 2025',
        'L''article explique que le choix du président de la Republicaine du Congo, Cornélien, suscite des controverses en raison de ses relations avec des acteurs politiques et économiques locaux.',
        'https://union.sonapresse.com/fr/pdg-choix-cornelien',
        'L''union',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bae08bf2-59a8-44f6-b06e-300a6dea71c3',
        'Publié le 27 / 07 / 2025',
        'Les élections législatives de 2025 au Sénégal débuteront le 27 juillet, marquant le début de la compétition politique pour la majorité parlementaire.',
        'https://union.sonapresse.com/fr/legislatives-2025-la-course-debute-ce-27-juillet',
        'L''union',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98923cc2-e642-419f-8ca8-9e316eb1fb29',
        'Publié le 27 / 07 / 2025',
        'L''article explique comment Cornélien a choisi un programme pour apprendre à coder, en soulignant l''importance de la détermination et du choix d''une formation adaptée pour réussir dans le domaine de la technologie.',
        'https://union.sonapresse.com/fr/pdg-choix-cornelien',
        'L''union',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f5a677e-be50-435c-bc01-2ad58a542476',
        'Gabon : Quelle banque a réalisé le plus de bénéfices en 2024 ?',
        'En 2024, la banque gabonaise qui a réalisé le plus de bénéfices, selon les chiffres de l''Association gabonaise des usagers de banque (AGUB), est [nom spécifique si connu dans l''article], parmi sept établissements comme AFGBank, UGB, BGFIbank, Citibank, Orabank, UBA et Ecobank.',
        'https://directinfosgabon.com/gabon-quelle-banque-a-realise-le-plus-de-benefices-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e16bbc65-26ba-4863-a4af-f02fa9e23f99',
        'BAD : Téléchargez les perspectives économiques en Afrique 2025',
        'Le rapport de la Banque africaine de développement (BAD) pour 2025 présente les principales prévisions économiques, telles que la croissance et l’inflation, pour les pays africains.',
        'https://directinfosgabon.com/bad-telechargez-les-perspectives-economiques-en-afrique-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4043f50-d794-498f-a63c-51100e69a8fa',
        'Subventions aux carburants : Le Gabon a dépensé 110 milliards de FCFA en 2024',
        'Le Gabon a dépensé 110 milliards de FCFA en subventions pour les carburants en 2024, incluant aussi le maintien d’aides pour la farine de blé, la gratuité des transports publics et la baisse des prix du gaz butane.',
        'https://directinfosgabon.com/subventions-aux-carburants-le-gabon-a-depense-110-milliards-de-fcfa-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3109a42-21da-46a5-bd4c-5f3a5bae0881',
        'Gabon : Les catégories de sacs plastiques dont l’usage est autorisé à compter du 23 septembre',
        'À partir du 23 septembre 2025, l’utilisation des sacs plastiques à usage unique sera interdite en République gabonaise, mais certaines catégories de sacs seront exceptionnellement autorisées.',
        'https://directinfosgabon.com/gabon-les-categories-de-sacs-plastiques-dont-lusage-est-autorise-a-compter-du-23-septembre/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78c11cbf-2b66-4451-9eca-aa9d7951970f',
        'Concours d’éloquence SAMEAU : à Owendo, une jeunesse plurielle et engagée en pleine lumière Mission du CNEPC et DGTT : les auto-...',
        'Une jeunesse engagée et dynamique a brillé lors du concours d’éloquence Sameau à Owendo, montrant une forte capacité à s’exprimer et à défendre ses idées.',
        'https://mediapostegabon.com/concours-deloquence-sameau-a-owendo-une-jeunesse-plurielle-et-engagee-en-pleine-lumiere/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d4befef-3eef-4681-8049-630bafe32be4',
        'Moov Africa : Kévin Mea vainqueur de la 4ème édition de la E-League 2025',
        'Kévin Mea a remporté la 4ème édition de la E-League organisée par Moov Africa Gabon Telecom, après quatre jours de compétition intense.',
        'https://gabonactu.com/blog/2025/07/28/moov-africa-kevin-mea-vainqueur-de-la-4eme-edition-de-la-e-league-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '34ff0b44-c4c4-491a-bd0b-cbd357c12c6b',
        'Jeux Africains Scolaires : L’élite du Taekwondo gabonais débarque à Alger',
        'Une équipe gabonaise de cinq jeunes combattants de taekwondo participe aux Jeux africains scolaires à Alger, visant de bonnes performances dans cette compétition.',
        'https://gabonactu.com/blog/2025/07/28/jeux-africains-scolaires-lelite-du-taekwondo-gabonais-debarque-a-alger/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c99da4d4-aa36-4383-a275-3df9f8942271',
        'FlyGabon : «Louer un avion, ce n’est pas un manque, c’est une stratégie» (Nyl Moret-Mba)',
        'Le gouvernement gabonais considère la location d’avions, comme l’achat récent d’un Airbus A320, comme une stratégie économique plutôt qu’un signe de manque de moyens, en insistant sur l’intérêt d’adopter des solutions flexibles pour gérer le transport aérien.',
        'https://www.gabonreview.com/flygabon-louer-un-avion-ce-nest-pas-un-manque-cest-une-strategie-nyl-moret-mba/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a6895bb-21e7-493a-acf2-541387d3b270',
        'Foi et traditions au Gabon : le choc ou l’alliance ?',
        'Le débat continue au Gabon sur la coexistence et l''harmonie entre les traditions ancestrales et la foi chrétienne, avec une réflexion sur la nécessité d''un dialogue entre culture et religion.',
        'https://www.gabonreview.com/foi-et-traditions-au-gabon-le-choc-ou-lalliance/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d9bf8b7-47d9-4e0c-ab20-f5ed7566f0bf',
        'Concours d’éloquence SAMEAU : à Owendo, une jeunesse plurielle et engagée en pleine lumière Mission du CNEPC et DGTT : les auto-...',
        'Un concours d’éloquence a mis en valeur une jeunesse engagée et plurielle lors d’un événement à Owendo, révélant la vitalité et la diversité des jeunes dans le domaine de la parole et de la réflexion.',
        'https://mediapostegabon.com/concours-deloquence-sameau-a-owendo-une-jeunesse-plurielle-et-engagee-en-pleine-lumiere/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92963275-0099-4c48-8a25-d5fddb2c0daf',
        'BGFI Holding Corporation : L’introduction en bourse reportée',
        'L''introduction en bourse de la BGFI Holding Corporation a été reportée afin d''assurer la sécurité et la sérénité de toutes les parties concernées, en attente de la résolution de certaines requêtes.',
        'https://directinfosgabon.com/bgfi-holding-corporation-lintroduction-en-bourse-reportee/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '854ec0df-254f-4b43-bcfa-fd2b4457a206',
        'Groupe BGFIBank : Le processus d’introduction à la BVMAC est en cours',
        'BGFIBank finalise actuellement les démarches pour l’introduction en bourse de BGFI Holding Corporation à la BVMAC, afin de renforcer sa présence sur le marché financier.',
        'https://gabonactu.com/blog/2025/07/28/groupe-bgfibank-le-processus-dintroduction-a-la-bvmac-est-en-cours/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd9461db6-35ce-44ca-8a7f-e154a84f44fc',
        'Cour des comptes : EPG et Bilie-By-Nzé appellent au respect des principes républicains',
        'Le parti oppositionnel EPG et son leader Bilie-By-Nzé appellent au respect des principes républicains face à des pressions perçues comme injustes ou inappropriées.',
        'https://gabonactu.com/blog/2025/07/28/cour-des-comptes-epg-et-bilie-by-nze-appellent-au-respect-des-principes-republicains/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cc668537-7be3-4df1-87e3-e353a32b9bd6',
        'Gabon : Chômage et pauvreté, le talon d’Achille du gouvernement Oligui Nguema',
        'Le gouvernement gabonais est confronté à un chômage élevé et à la pauvreté, qui représentent ses principaux défis et points faibles à améliorer.',
        'https://gabonmediatime.com/gabon-chomage-et-pauvrete-le-talon-dachille-du-gouvernement-oligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '100b96ee-5e50-4fa2-9315-8df7e7fac73b',
        'Gabon : la Banque mondiale alerte sur le coût budgétaire des subventions anti-vie chère',
        'La Banque mondiale alerte sur le coût élevé des subventions en exploitation de carburant, qui peuvent peser sur le budget public et limiter les investissements dans d''autres secteurs essentiels.',
        'https://gabonmediatime.com/gabon-la-banque-mondiale-alerte-sur-le-cout-budgetaire-des-subventions-anti-vie-chere/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6ac9d11-877e-41d5-bbb0-5e4b6ccc5527',
        'Possible suspension du PDG : c’est déjà la cacophonie dans le camp Ali Akbar ?',
        'Des tensions surgissent au sein du camp d’Ali Akbar suite à la possible suspension du PDG, provoquant une cacophonie parmi ses partisans.',
        'https://gabonmediatime.com/possible-suspension-du-pdg-cest-deja-la-cacophonie-dans-le-camp-ali-akbar/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '318e3607-6a6c-4446-8e2f-f4e6a50025e5',
        'Législatives 2025 : le Bloc Démocratique Chrétien investit Ulrich NDONG MEYO pour le deuxième siège du département du Haut-Como',
        'Le Bloc démocratique chrétien a investi Ulrich Ndong Meyo comme candidat pour tenter d''obtenir un second siège dans le département du Haut-Komé lors des législatives de 2025.',
        'https://kongossanews.info/legislatives-2025-le-bloc-democratique-chretien-investit-ulrich-ndong-meyo-pour-le-deuxieme-siege-du-departement-du-haut-como/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63dab3c1-5c29-4076-83b8-fff492d4b15c',
        'Football: Kila Onfia rejoint le Hafia FC',
        'Kila Onfia, défenseur central gabonais, quitte Mangasport pour rejoindre le club guinéen Hafia FC, avec qui il espère participer aux compétitions africaines cette saison.',
        'https://agpgabon.ga/football-kila-onfia-rejoint-le-hafia-fc/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cc4d8957-ceea-4fad-8370-6289aee5da33',
        'Gabon/Conditions de vie des menages : les experts d’Afrique centrale et de l’ouest en conclave à Libreville',
        'Des experts d''Afrique centrale et de l''Ouest se réunissent à Libreville pour discuter de la mise en œuvre de la troisième phase de l''enquête sur les conditions de vie des ménages, visant à améliorer et harmoniser les statistiques dans la région.',
        'https://agpgabon.ga/gabon-conditions-de-vie-des-menages-les-experts-dafrique-centrale-et-de-louest-en-conclave-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '868b7339-5d40-49ff-8bb0-77c53b1f6099',
        'Gabon/Semaine du cinéma : ouverture des rideaux de 5e édition',
        'La 5e édition de la Semaine du cinéma à Libreville a débuté avec des projections de films gabonais, français et internationaux, abordant des thèmes sociaux et contemporains, devant un public enthousiaste de professionnels et passionnés du cinéma.',
        'https://agpgabon.ga/gabon-semaine-du-cinema-ouverture-des-rideaux-de-5e-edition/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47e4e247-0a2c-4281-953a-14a221e566a1',
        'Le ministère de l’économie numérique et l’UNICEF vers un partenariat pour une plus école numérique',
        'Le ministère de l’Économie numérique et l’UNICEF travaillent à renforcer l’éducation numérique en collaborant pour ouvrir davantage d’écoles numériques au Gabon.',
        'https://gabonactu.com/blog/2025/07/28/le-ministere-de-leconomie-numerique-et-lunicef-vers-un-partenariat-pour-une-plus-ecole-numerique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86015f4e-2c87-48f0-9bf0-698d10f93728',
        'Rencontre stratégique entre Anicet Engo et les jeunes cadres du Woleu-Ntem, sous l''impulsion de Lilian Ndong Edzang',
        'Une rencontre stratégique et conviviale a réuni à Oyem le président de la LNJB, Anicet Engo, et des jeunes cadres des départements du Ntem, du Haut-Ntem et de l''Okano, à l''initiative du jeune leader Lilian Ndong Edzang.',
        'https://www.gabonews.com/fr/actus/politique/article/rencontre-strategique-entre-anicet-engo-et-les',
        'Gabonews',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ab07e1a-55c6-4417-8d1b-0b85400018e2',
        'L''Honorable Pépécy Ogouliguendé face aux populations pour un compte rendu parlementaire',
        'L''honorable Pépécy Ogouliguende a organisé un rapport parlementaire dans son quartier, où elle a expliqué ses actions et répondu aux questions de la population lors d''une rencontre de près de deux heures.',
        'https://www.gabonews.com/fr/actus/politique/article/l-honorable-pepecy-ogouliguende-face-aux',
        'Gabonews',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1880442f-5ef8-43ac-a22a-1ada924665aa',
        'Gabon : Chômage et pauvreté, le talon d’Achille du gouvernement Oligui Nguema',
        'Le chômage et la pauvreté restent des défis majeurs pour le gouvernement gabonais, révélant une faiblesse dans la gestion économique et sociale du pays.',
        'https://gabonmediatime.com/gabon-chomage-et-pauvrete-le-talon-dachille-du-gouvernement-oligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b869ad6-9d0c-4423-9c35-e5267816beea',
        'Gabon : la Banque mondiale alerte sur le coût budgétaire des subventions anti-vie chère',
        'La Banque mondiale alerte sur le coût élevé des subventions en République gabonaise, qui pourraient mettre en péril la stabilité budgétaire du pays.',
        'https://gabonmediatime.com/gabon-la-banque-mondiale-alerte-sur-le-cout-budgetaire-des-subventions-anti-vie-chere/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76837163-8a59-4940-99b0-f358c25f4482',
        'Possible suspension du PDG : c’est déjà la cacophonie dans le camp Ali Akbar ?',
        'Des divergences et une certaine confusion règnent autour de la possible suspension du président du parti politique, ce qui entraîne une cacophonie au sein du camp d''Ali Akbar.',
        'https://gabonmediatime.com/possible-suspension-du-pdg-cest-deja-la-cacophonie-dans-le-camp-ali-akbar/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6b67502-dca9-4c05-855e-3f9789054c20',
        'Législatives 2025 : le Bloc Démocratique Chrétien investit Ulrich NDONG MEYO pour le deuxième siège du département du Haut-Como',
        'Le Bloc Démocratique Chrétien investit Ulrich Ndong Meyo comme candidat pour le deuxième siège du département du Haut Como lors des élections législatives de 2025.',
        'https://kongossanews.info/legislatives-2025-le-bloc-democratique-chretien-investit-ulrich-ndong-meyo-pour-le-deuxieme-siege-du-departement-du-haut-como/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e76e2ee9-30ea-4620-a64a-6b0c08596e52',
        'Ogooué-Lolo : des tenues d’apparat pour 32 auxiliaires de commandement du Canton Basse-Lombo',
        'Des tenues d’apparat ont été offertes à 32 auxiliaires de commandement du canton Basse-Lombo, grâce à l’initiative d’une native du canton, pour leur permettre d’être mieux identifiés lors des événements officiels.',
        'https://agpgabon.ga/ogooue-lolo-des-tenues-dapparat-pour-32-auxiliaires-de-commandement-du-canton-basse-lombo/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '956122fa-930c-46fa-b6f9-0d4c41baf9d4',
        '"Je ne saurais rester silencieux face aux nombreuses interpellations venant tant du monde ecclésiastique..."',
        'Un responsable politique exprime son refus de rester silencieux face aux questions et critiques concernant l’actualité politique du pays, notamment suite à un événement survenu le 3 mai.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/je-ne-saurais-rester-silencieux-face-aux',
        'Gabonews',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d488389-e195-4b02-b72b-ab02f475a60e',
        'Gabon/Festival Okano culture : l’évènement aura lieu du 15 au 30 août prochain à Mitzic',
        'Le festival Okano Culture, organisé chaque année dans la région de Mitzic, se déroulera du 15 au 30 août et vise à valoriser le patrimoine culturel gabonais à travers l’art, la cuisine, la danse et les jeux traditionnels.',
        'https://agpgabon.ga/gabon-festival-okano-culture-levenement-aura-lieu-du-15-au-30-aout-prochain-a-mitzic/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a467564-4d51-43c5-9ee1-26a30ab72b27',
        'Gabon / Entrepreneuriat : près de 1291 candidats auditionnés pour le Grand Prix 2025',
        'Plus de 1 290 candidats ont été auditionnés dans le cadre de la sélection du Grand Prix de l’Entrepreneuriat 2025 au Gabon, lors d’une étape organisée à l’ISTA sous la supervision de plusieurs ministres.',
        'https://agpgabon.ga/gabon-entrepreneuriat-pres-de-1291-candidats-auditionnes-pour-le-grand-prix-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5e17e67-30d0-4a90-9c39-7e7fa92fd3e1',
        'Ogooué-Lolo/Koulamoutou : Coup d’envoi de la 3e édition de la Coupe Jean Massima',
        'La troisième édition de la coupe Jean Massima a été lancée avec succès à Koulamoutou, impliquant huit équipes et un match d’ouverture remporté aux tirs au but.',
        'https://agpgabon.ga/ogooue-lolo-koulamoutou-coup-denvoi-de-la-3e-edition-de-la-coupe-jean-massima/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb0826e8-4343-4011-bdcb-9a49d05302dc',
        'Pétrole : Des hommes d’affaires proposent la construction d’une raffinerie de 30 à 90 000 barils/J au Gabon',
        'Des hommes d’affaires gabonais proposent de construire une raffinerie de pétrole d''une capacité allant de 30 000 à 90 000 barils par jour pour renforcer la production nationale.',
        'https://gabonactu.com/blog/2025/07/28/petrole-des-hommes-daffaires-proposent-la-construction-dune-raffinerie-de-30-a-90-000-barils-j-au-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8bb16819-df04-40e2-ab97-8dfd52564e83',
        '[Interview] Edgar Mba Ognane Nguema : «Nous sommes le wagon qui tire l’industrie»',
        'Un an après le rachat d’Assala Energy par l’État gabonais, le directeur général affirme la stabilité et la performance du secteur pétrolier, soulignant son rôle moteur dans le développement de l’industrie.',
        'https://www.gabonreview.com/interview-edgar-mba-ognane-nguema-nous-sommes-le-wagon-qui-tire-lindustrie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8b5fe2cc-9bd7-4177-984c-dbd1abfb80c9',
        'De l’héritage du PDG à la tentation hégémonique : les défis de l’UDB face aux autres',
        'L’Union démocratique des Bâtisseurs (UDB), soutenue par le pouvoir présidentiel, cherche à dominer le paysage politique gabonais, tandis que des oppositions plus radicales, comme celle menée par Alain-Claude Bilie-By-Nze, s’organisent pour défendre leurs ambitions.',
        'https://www.gabonreview.com/de-lheritage-du-pdg-a-la-tentation-hegemonique-les-defis-de-ludb-face-aux-autres/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40757b34-6d54-4b00-bd7c-8357092daeb5',
        '"Le développement que nous ambitionnons pour nos pays repose sur une exigence : celle de la vérité des faits, de la rigueur des chiffres, et de la transparence dans l''évaluation"',
        'Un atelier de formation pour préparer la collecte de données sur les conditions de vie des ménages s''est ouvert à Libreville, Gabon, pour l''édition 2025/2026 de l’Enquête Harmonisée, avec la participation de formateurs et la supervision de la ministre Louise Pierrette Mvono.',
        'https://www.gabonews.com/fr/actus/economie/article/le-developpement-que-nous-ambitionnons-pour-nos',
        'Gabonews',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6666c39-9aac-4f1f-af29-32cac2254b8b',
        'Gabon : un nouveau centre de stockage de gaz en projet',
        'Le gouvernement gabonais a rencontré une society, Petro Gabon, pour discuter d’un projet de construction d’un nouveau centre de stockage de gaz butane et d’un système de remplissage de bouteilles.',
        'https://agpgabon.ga/gabon-un-nouveau-centre-de-stockage-de-gaz-en-projet/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b463ad51-76aa-4a7b-a1ae-ab170edcc0a2',
        'Jeux Africains Scolaire d’Alger/Wushu : Ndemby Ogandaga Sydney remporte le bronze',
        'Un athlète gabonais, Ndemby Ogandaga Sydney Darcy, a remporté la médaille de bronze en wushu (changquan) lors des Jeux Africains Scolaires d’Alger, marquant ainsi la première médaille pour la délégation gabonaise dans cette compétition.',
        'https://agpgabon.ga/jeux-africains-scolaire-dalger-wushu-ndemby-ogandaga-sydney-remporte-le-bronze/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb681c2a-a9b5-4fc1-b055-01c4c1506df9',
        'Le Gabon célèbre sa Journée Nationale à l''Exposition Universelle 2025 Osaka',
        'Le Gabon a célébré sa Journée nationale lors de l''Exposition universelle 2025 à Osaka, mettant en avant le thème « Notre forêt, moteur universel qui sauve des vies », en présence de représentants gabonais, internationaux et japonais.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/le-gabon-celebre-sa-journee-nationale-a-l',
        'Gabonews',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28c14c8d-7b8f-450f-a143-b5f9f3a09844',
        'Industrie : le Gabon scelle deux partenariats stratégiques à Tokyo',
        'Le Gabon a signé deux accords stratégiques avec des partenaires au Japon pour renforcer ses industries dans les domaines des infrastructures, de l’agro-industrie et des énergies renouvelables.',
        'https://agpgabon.ga/industrie-le-gabon-scelle-deux-partenariats-strategiques-a-tokyo/',
        'AGP',
        'Business Intelligence',
        '2025-07-28T00:00:00.000Z',
        '2025-09-15T23:06:12.484Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

