-- Batch 5 - Section 1/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES (
        '203735df-2032-45cc-916d-14148e459482',
        '‘’L’Éveil de la Pensée Citoyenne’’, une nouvelle plateforme de Joseph Lapensée Essingone',
        'Joseph Lapensée Essingone a lancé une nouvelle plateforme, « L’éveil de la pensée citoyenne », pour encourager l’engagement et la participation citoyenne.',
        'https://gabonactu.com/blog/2025/06/23/leveil-de-la-pensee-citoyenne-une-nouvelle-plateforme-de-joseph-lapensee-essingone/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b5fda05-4469-485e-b4a8-01a91297b1e9',
        'BCEG : Même les vendeurs à la sauvette ont désormais leur banque',
        'La BCEG va lancer B-Cash, une banque mobile inclusive permettant aux travailleurs mobiles indépendants et même aux vendeurs informels d’accéder à des services financiers.',
        'https://gabonactu.com/blog/2025/06/23/bceg-meme-les-vendeurs-a-la-sauvette-ont-desormais-leur-banque/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f50b4e7e-241d-4b48-bce8-98d17012dfc2',
        'Manganèse : Eramet face au sursaut gabonais',
        'L''entreprise minière française Eramet est critiquée par un syndicat gabonais pour son modèle économique basé sur l''extraction, alors que le pays souhaite développer la transformation locale du manganèse.',
        'https://www.gabonreview.com/manganese-eramet-face-au-sursaut-gabonais/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cff5b921-32cc-4548-9e62-08866ee9d8b2',
        'Le Gabon renforce sa Filière forêt-bois : une nouvelle ère de concertation public-privé',
        'Une réunion importante entre l''administration et le secteur privé s''est tenue pour renforcer et rendre plus durable la filière bois au Gabon.',
        'https://www.gabonews.com/fr/actus/eaux-et-forets/article/le-gabon-renforce-sa-filiere-foret-bois-une',
        'Gabonews',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5311150-f8dd-4f44-a27a-27864d9084df',
        'L''OCI salue le leadership du Roi Mohammed VI en faveur d''Al-Qods Acharif',
        'Les pays membres de l''Organisation de la Coopération islamique ont salué l''engagement du Roi Mohammed VI, en tant que président du Comité Al-Qods, pour la défense des lieux saints musulmans à Jérusalem lors de leur réunion à Istanbul.',
        'https://www.gabonews.com/fr/actus/international/article/l-oci-salue-le-leadership-du-roi-mohammed-vi-en',
        'Gabonews',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc7f0fd8-022c-4763-872b-5f9fecedad53',
        'Bruce Springsteen à San Sebastian, on y était !',
        'Bruce Springsteen a enflammé la public à San Sebastián avec une mise en scène énergique et chaleureuse, mêlant les salutations en basque à ses chansons emblématiques.',
        'https://www.rollingstone.fr/bruce-springsteen-a-san-sebastian-on-y-etait/?utm_source=rss&utm_medium=rss&utm_campaign=bruce-springsteen-a-san-sebastian-on-y-etait',
        'Flipboard',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0304794-61b7-4390-8ee4-0c5071d3f46e',
        'Sommet des affaires États-Unis – Afrique : Oligui Nguema aux 17e Assises à Luanda',
        'Lors du 17e sommet des Affaires États-Unis–Afrique à Luanda, le président gabonais Oligui Nguema a participé à des discussions sur la coopération entre les deux régions pour promouvoir la prospérité et le partenariat.',
        'https://www.gabonreview.com/sommet-des-affaires-etats-unis-afrique-oligui-nguema-aux-17e-assises-a-luanda/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa38a39c-6370-4cba-b731-5187f497df0b',
        'Municipales 2025 : Stéphane Iloko prêt à conquérir la Mairie de Libreville',
        'Stéphane Iloko se prépare à se présenter aux élections municipales de 2025 pour conquérir la mairie de Libreville.',
        'https://gabonmediatime.com/municipales-2025-stephane-iloko-pret-a-conquerir-la-mairie-de-libreville/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55e12fd1-500f-4c01-a12d-7322b2204adf',
        'Lapensée : « Mon gestionnaire a voulu déposer mon compte de campagne, il n’a pas été reçu »',
        'Une personne explique qu’elle a tenté de déposer son compte de campagne, mais son gestionnaire n’a pas accepté sa demande.',
        'https://gabonmediatime.com/lapensee-mon-gestionnaire-a-voulu-deposer-mon-compte-de-campagne-il-na-pas-ete-recu/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '166ff5fa-970f-4508-862f-e5c1a093faf9',
        'Rome : Paulette Missambo pour un dialogue interreligieux prononcé !',
        'Rome Paulette Missambo appelle à un dialogue interreligieux pour promouvoir la paix et la compréhension entre différentes confessions.',
        'https://gabonmediatime.com/rome-paulette-missambo-pour-un-dialogue-interreligieux-prononce/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ee99fc5c-c512-4109-8243-c900b3ae3843',
        'Gabon/Taxis moto-tricycles : les usagers encore réticents',
        'Cinq mois après leur lancement officiel à Libreville, les moto-tricycles sont désormais visibles dans la ville, mais de nombreux usagers restent encore hésitants à leur utilisation, certains remettant en question leur pertinence.',
        'https://agpgabon.ga/gabon-taxis-moto-tricycles-les-usagers-encore-reticents/',
        'AGP',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7ea75d49-388d-49c1-bf93-993e34cca294',
        'Gabon : le festival Coup de Théâtre ouvre sa scène à Libreville',
        'La 11ᵉ édition du festival Coup de Théâtre se déroule du 26 au 28 juin à Libreville, réunissant diverses compagnies théâtrales pour promouvoir et réfléchir sur l’avenir du théâtre gabonais, avec des échanges et des représentations inédites autour du thème « Ô Terre ».',
        'https://agpgabon.ga/gabon-le-festival-coup-de-theatre-ouvre-sa-scene-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba5f1c13-05ce-4d3a-961b-ef868f9adace',
        'SEEG : arrêt de la station de traitement d’eau potable d’Okala suite à un acte de vandalisme',
        'La station de traitement d’eau potable d’Okala a été mise hors service suite à un acte de vandalisme, ce qui perturbe l’approvisionnement en eau dans plusieurs quartiers.',
        'https://gabonactu.com/blog/2025/06/23/seeg-arret-de-la-station-de-traitement-deau-potable-dokala-suite-a-un-acte-de-vandalisme/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '560aee54-b542-494a-b00e-d5eaf926329f',
        'Desserte d’eau perturbée à Owendo : la SEEG répare 4 grosses fuites sous le pont Nomba',
        'La SEEG a réparé quatre grosses fuites d’eau sous le pont Nomba à Owendo, ce qui a perturbé la distribution d’eau dans la région.',
        'https://gabonactu.com/blog/2025/06/23/desserte-deau-perturbee-a-owendo-la-seeg-repare-4-grosses-fuites-sous-le-pont-nomba/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9627157d-4ab3-4f34-be71-794f4ea314fc',
        'SATRAM : Près de 800 agents tirent le diable par la queue dans l’indifférence générale',
        'Près de 800 employés de la société Satram, spécialisée dans la logistique maritime, vivent dans une grande précarité, ne recevant qu’un mois de salaire depuis le début de l’année, dans un contexte d''indifférence générale.',
        'https://gabonactu.com/blog/2025/06/23/satram-pres-de-800-agents-tirent-le-diable-par-la-queue-dans-lindifference-generale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '59b109a8-0ad5-40a3-9669-7f2d0540c814',
        'Municipales 2025 : Stéphane Iloko prêt à conquérir la Mairie de Libreville',
        'Stéphane Iloko se prépare à se présenter aux municipales de 2025 pour tenter de conquérir la mairie de Libreville.',
        'https://gabonmediatime.com/municipales-2025-stephane-iloko-pret-a-conquerir-la-mairie-de-libreville/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a90ff0c-fa4e-43e7-94ff-ab772c145026',
        'Lapensée : « Mon gestionnaire a voulu déposer mon compte de campagne, il n’a pas été reçu »',
        'Un responsable a tenté de déposer son compte de campagne, mais sa demande n''a pas été acceptée, sans explication précise.',
        'https://gabonmediatime.com/lapensee-mon-gestionnaire-a-voulu-deposer-mon-compte-de-campagne-il-na-pas-ete-recu/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55a853b1-df39-4ee9-815e-0d9a6d8ea819',
        'Rome : Paulette Missambo pour un dialogue interreligieux prononcé !',
        'Rome Paulette Missambo appelle au dialogue interreligieux pour promouvoir la paix et la compréhension entre les différentes confessions.',
        'https://gabonmediatime.com/rome-paulette-missambo-pour-un-dialogue-interreligieux-prononce/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7bad4876-d508-46d9-b66e-28629c492f20',
        'CEDEAO : Julius Maada Bio succède à Bola Tinubu à la tête de l’organisation',
        'Julius Maada Bio, président de la Sierra Leone, a été élu à la tête de la CEDEAO pour un mandat d’un an, succédant à Bola Tinubu, avec pour priorités le renforcement de la démocratie et la coopération régionale.',
        'https://agpgabon.ga/cedeao-julius-maada-bio-succede-a-bola-tinubu-a-la-tete-de-lorganisation/',
        'AGP',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31d7c815-c54d-475c-92f9-78888b7549db',
        'Gabon : le PDG, ancien parti au pouvoir, renouvelle ses structures',
        'Le Parti démocratique gabonais (PDG) a renouvelé ses dirigeants dans ses différentes structures, sous la direction actuelle de Blaise Louembe.',
        'https://agpgabon.ga/gabon-le-pdg-ancien-parti-au-pouvoir-renouvelle-ses-structures-2/',
        'AGP',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f71e1d16-aa6c-485f-b4d6-7b4fe842ca68',
        'Le président malien Assimi Goïta en visite d''État en Russie',
        'Le président malien Assimi Goïta a rencontré le président russe Vladimir Poutine pour renforcer les relations entre leur pays et approfondir leur coopération.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250623-le-pr%C3%A9sident-malien-assimi-go%C3%AFta-en-visite-d-%C3%A9tat-en-russie',
        'France 24',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88e8641e-5433-4d25-b1eb-51f5013facb6',
        'Sommet d’Affaires États-Unis-Afrique : Lourenço invite les américains à investir dans le continent d’opportunités',
        'L’Afrique invite les États-Unis à investir dans ses nombreuses opportunités économiques lors d’un sommet d’affaires, encourageant une coopération accrue entre les deux continents.',
        'https://gabonactu.com/blog/2025/06/23/sommet-daffaires-etats-unis-afrique-lourenco-invite-les-americains-a-investir-dans-le-continent-dopportunites/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d2612f8-d199-4e6f-8aa9-9377cfe6fc0b',
        'La Pensée Patriotique G9 annonce un soutien 100% au parti d’Oligui Nguema',
        'L''association « La Pensée Patriotique » G9 a annoncé son soutien total au parti d’Oligui Nguema, dirigeant du Gabon.',
        'https://gabonactu.com/blog/2025/06/23/la-pensee-patriotique-g9-annonce-un-soutien-100-au-parti-doligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ee7e0f8-f70b-4558-875d-e8f1d6477fca',
        'Déguerpissement au quartier SNI-Owendo : et si le gouvernement publiait le calendrier et la liste des zones à démolir ?',
        'Le gouvernement pourrait publier un calendrier et une liste des quartiers à démolir, notamment celui de SNI Owendo, pour informer les habitants et organiser l''évacuation.',
        'https://kongossanews.info/deguerpissement-au-quartier-sni-owendo-et-si-le-gouvernement-publiait-le-calendrier-et-la-liste-des-autres-quartiers-a-demolir/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3fc824f-6d07-4746-8ea3-bff00e76edf3',
        'Publié le 23 / 06 / 2025',
        'Un parti présidentiel a été créé pour soutenir la candidature du président, mais sa mise en place soulève des questions juridiques concernant sa légalité et son fonctionnement.',
        'https://union.sonapresse.com/fr/mise-sur-pied-du-parti-presidentiel-debat-juridique',
        'L''union',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b47261bc-0127-4cc2-967d-1f11fcf15e06',
        'Publié le 23 / 06 / 2025',
        'Un nouveau parti présidentiel se met en place pour renforcer l’équilibre politique et assurer une stabilité durable après l’élection présidentielle.',
        'https://union.sonapresse.com/fr/mise-sur-pied-du-parti-presidentiel-vers-un-enracinement-des-equilibres-issus-de-la-presidentielle',
        'L''union',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92543586-38ac-41e5-98f6-8842cac8712b',
        'Publié le 22 / 06 / 2025',
        'La première session de la Conférence nationale durable a permis de rassembler des propositions optimistes pour renforcer le développement durable au Sénégal, en mettant en avant la collaboration et l’engagement de tous les acteurs concernés.',
        'https://union.sonapresse.com/fr/1ere-session-de-la-cnd-des-propositions-sur-fond-doptimisme',
        'L''union',
        'Business Intelligence',
        '2025-06-23T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc910d78-5923-4e0c-a485-83c080b13b4b',
        'Déguerpissement au quartier SNI-Owendo : et si le gouvernement publiait le calendrier et la liste des zones à démolir ?',
        'Le gouvernement pourrait publier un calendrier avec la liste des quartiers à démolir pour informer les habitants et éviter l’insécurité lors des opérations de déguerpissement au quartier SNI Owendo.',
        'https://kongossanews.info/deguerpissement-au-quartier-sni-owendo-et-si-le-gouvernement-publiait-le-calendrier-et-la-liste-des-autres-quartiers-a-demolir/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffc03efe-8329-47c3-982a-3d9f194ec66e',
        'Publié le 23 / 06 / 2025',
        'Le lancement du parti présidentiel ivoirien soulève des questions juridiques sur sa constitutionnalité et sa conformité aux lois électorales en Côte d''Ivoire.',
        'https://union.sonapresse.com/fr/mise-sur-pied-du-parti-presidentiel-debat-juridique',
        'L''union',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '34fd42a6-b030-4617-b73a-a8c2d8592cc8',
        'Publié le 23 / 06 / 2025',
        'L''article explique comment la création d''un parti présidentiel vise à renforcer la stabilité politique et à équilibrer les forces issues de l’élection présidentielle.',
        'https://union.sonapresse.com/fr/mise-sur-pied-du-parti-presidentiel-vers-un-enracinement-des-equilibres-issus-de-la-presidentielle',
        'L''union',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca09fbb9-a0f8-45f8-a81f-8a602b7ebaeb',
        'Publié le 22 / 06 / 2025',
        'La première session de la conférence nationale de développement a permis d’identifier des propositions positives pour améliorer la situation du pays, en restant optimiste quant à ses perspectives de progrès.',
        'https://union.sonapresse.com/fr/1ere-session-de-la-cnd-des-propositions-sur-fond-doptimisme',
        'L''union',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f5ae87b4-4ace-4f83-8f83-d2cf8efea19f',
        'Angola/17ᵉ Sommet des Affaires États-Unis – Afrique : Oligui Nguema plaide pour des partenariats durables',
        'Le président gabonais a participé au 17ème Sommet des Affaires États-Unis-Afrique à Luanda, où il a appelé à établir des partenariats durables pour renforcer la coopération économique entre l''Afrique et les États-Unis.',
        'https://agpgabon.ga/angola-17eme-sommet-des-affaires-etats-unis-afrique-oligui-nguema-honore-de-sa-presence/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6190f40f-cc19-4f96-97a7-96e9c6f8b930',
        'Gabon : Jean Cruz Lessagui trace de nouvelles perspectives pour la Marine Marchande',
        'Le directeur général de la Marine Marchande a présenté des mesures pour améliorer l''administration après avoir constaté des dysfonctionnements liés à la confusion des rôles au sein des équipes, en annonçant notamment des réformes structurelles.',
        'https://agpgabon.ga/gabon-jean-cruz-lessagui-trace-de-nouvelles-perspectives-pour-la-marine-marchande/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57b78116-1c71-4520-a8ff-99b752c81ba0',
        'Levée de rideau sur le 17e sommet d’Affaires États-Unis-Afrique: OLIGUI NGUEMA fait la promotion d’un Gabon ouvert aux partenariats gagnant-gagnant',
        'Le président gabonais Brice Clotaire OLIGUI NGUEMA a participé au 17e Sommet des Affaires États-Unis–Afrique à Luanda, une étape clé pour renforcer la coopération économique entre le Gabon, l’Angola et les États-Unis.',
        'https://vxp241.com/2025/06/24/levee-de-rideau-sur-le-17e-sommet-daffaires-etats-unis-afrique-oligui-nguema-fait-la-promotion-dun-gabon-ouvert-aux-partenariats-gagnant-gagnant/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '371c6795-90de-40fa-a18d-87c6ade7818e',
        '[Vos réactions] Gabon : vers une réduction du nombre de partis',
        'Le débat porte sur la réduction du nombre de partis politiques au Gabon en renforçant les critères de création, afin de promouvoir une scène politique plus stable et cohérente, mais cela pourrait également limiter la diversité politique et l’expression démocratique.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250624-vos-r%C3%A9actions-gabon-vers-une-r%C3%A9duction-du-nombre-de-partis',
        'RFI',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '15d766d0-2322-4499-a662-6fa0ce6dd5f4',
        'Comment les premières formes de vie ont résisté à l’arsenic ?',
        'Les fossiles des premières formes de vie complexe montrent qu''elles étaient capables de survivre face à des environnements riches en arsenic en développant des mécanismes d’adaptation au stress chimique.',
        'https://www.rfi.fr/fr/podcasts/autour-de-la-question-le-magazine-de-toutes-les-sciences/20250624-comment-les-premi%C3%A8res-formes-de-vie-ont-r%C3%A9sist%C3%A9-%C3%A0-l-arsenic',
        'RFI',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4878e81-702c-4246-ab54-0b820f7ff623',
        'Modèle économique du Gabon  : Tout est à refaire, selon la Banque mondiale',
        'La Banque mondiale appelle le Gabon à restructurer profondément son économie, encore largement dépendante du pétrole, pour diversifier ses sources de revenus et assurer un développement durable.',
        'https://directinfosgabon.com/modele-economique-du-gabon-tout-est-a-refaire-selon-la-banque-mondiale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f01f4b8-5810-41fb-b12d-51a3c5d2f0c2',
        'IDE : Le Gabon a capté plus de 700 milliards FCFA en 2023, record sous-régional',
        'Le Gabon a attiré plus de 700 milliards de FCFA d''investissements étrangers en 2023, ce qui en fait le pays de la CEMAC avec la plus grande valeur d’IDE, en hausse par rapport à l’année précédente.',
        'https://directinfosgabon.com/ide-le-gabon-a-capte-plus-de-700-milliards-fcfa-en-2023-record-sous-regional/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '040993a3-7238-4bfd-9a4b-27b25c91f273',
        'Transport urbain : L’agrément technique devient obligatoire',
        'Depuis le 20 juin 2025, les transporteurs urbains et suburbains doivent désormais obtenir un agrément technique délivré par la Direction Générale des Transports Terrestres pour pouvoir exercer, afin de garantir la conformité et la sécurité de leurs activités.',
        'https://directinfosgabon.com/transport-urbain-lagrement-technique-devient-obligatoire/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd27eb4a5-5b38-4fdc-b75c-1667df30b738',
        'Angola : succès d’une première chirurgie robotique à distance',
        'Une première chirurgie robotique à distance entre les États-Unis et l’Angola a été réalisée avec succès, utilisant une connexion internet haut débit pour permettre à des médecins américains d’intervenir sur un patient à Luanda, marquant une avancée importante pour l’accès aux soins spécialisés en Afrique.',
        'https://agpgabon.ga/angola-succes-dune-premiere-chirurgie-robotique-a-distance/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5389ba35-af72-4876-9824-2e42e3200a20',
        'Comores : un bateau disparu avec 19 personnes à bord',
        'Un bateau battant pavillon malgache, avec 19 personnes à bord, a disparu entre Madagascar et les Comores, et les recherches sont en cours pour le retrouver.',
        'https://agpgabon.ga/comores-un-bateau-disparu-avec-19-personnes-a-bord/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '66a09fd9-8108-421f-8c6f-82e4dd9b9328',
        'OCI : hommage aux initiatives du Roi Mohammed VI en faveur de l’Afrique',
        'Le Conseil des ministres des Affaires étrangères de l’OCI a salué les efforts du Roi Mohammed VI pour l’Afrique, notamment ses initiatives pour améliorer l’accès à l’océan Atlantique pour les pays du Sahel et renforcer la solidarité régionale.',
        'https://agpgabon.ga/oci-hommage-aux-initiatives-du-roi-mohammed-vi-en-faveur-de-lafrique/',
        'AGP',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '67db7291-9718-404c-b0ca-957f2f181e6f',
        'Panier de la ménagère : Le gouvernement suspend certaines taxes à l’importance pour doper la consommation',
        'Le gouvernement gabonais a décidé de suspendre certaines taxes à l’importation pour réduire le coût des produits de consommation courante et encourager la consommation des ménages.',
        'https://gabonactu.com/blog/2025/06/24/panier-de-la-menagere-le-gouvernement-suspend-certaines-taxes-a-limportance-pour-doper-la-consommation/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '143a50bc-1fbb-4f30-bb76-e8637034439b',
        'Gabon : concours national du grand prix de l’entrepreneuriat  du 1er au 30 juillet 2025',
        'Le concours national du grand prix de l’entrepreneuriat au Gabon se déroulera du 1er au 30 juillet 2025, avec la participation d’entrepreneurs locaux encouragés à présenter leurs projets.',
        'https://gabonactu.com/blog/2025/06/24/gabon-concours-national-du-grand-prix-de-lentrepreneuriat-du-1er-au-30-juillet-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a881a862-7559-4fab-93b0-902f8d69b18d',
        'Stations de pesage et de péage : le gouvernement revoit sa copie',
        'Le gouvernement gabonais souhaite revoir le projet de nombre de stations de pesage et de péage prévu, suite aux réserves exprimées par le ministre des Travaux Publics lors d’une réunion avec des experts.',
        'https://www.gabonreview.com/stations-de-pesage-et-de-peage-le-gouvernement-revoit-sa-copie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1d4e325-d6c1-4d9a-88d6-9462d1b7b811',
        'Gabon : Les sacs plastiques interdits dans les grandes surfaces à compter de septembre 2025',
        'Le Gabon prévoit d’interdire l’utilisation des sacs plastiques à usage unique dans les grandes surfaces à partir de septembre 2025, dans le cadre d’un plan pour réduire la pollution environnementale et promouvoir des alternatives plus durables.',
        'https://directinfosgabon.com/gabon-les-sacs-plastiques-interdits-dans-les-grandes-surfaces-a-compter-de-septembre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '348e7b63-b1c3-4bc2-bca4-3e18c2d8099e',
        'Immaculée Conception : La tutelle justifie l’exclusion d’Anna-Gwenaëlle',
        'Le ministère de l’Éducation nationale a justifié l''exclusion d''Anna-Gwenaëlle Mouwoyi-Bifaghou de l''Institution Immaculée Conception à Libreville, précisant que cette décision était conforme aux règles de l''établissement.',
        'https://gabonactu.com/blog/2025/06/24/immaculee-conception-la-tutelle-justifie-lexclusion-danna-gwenaelle/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3937d667-56bf-4eeb-b8a6-a587e004c47e',
        'MNCG : Où sont les 1500 postes budgétaires promis aux chômeurs ?',
        'Le mouvement des chômeurs du Gabon dénonce le non-respect de la promesse faite en juin 2023 d’attribuer 1500 postes budgétaires aux chômeurs, qui n’ont toujours pas été mis en place à ce jour.',
        'https://gabonactu.com/blog/2025/06/24/mncg-ou-sont-les-1500-postes-budgetaires-promis-aux-chomeurs/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8de15f93-4188-493a-9126-3cc383b2bc0a',
        'Double exclusion à l’Immaculée Conception : le ministère de l’Éducation nationale salue «une impartialité exemplaire»',
        'Le ministère de l’Éducation nationale affirme que la sanction concernant l''exclusion de deux élèves impliqués dans une bagarre à l''Institution Immaculée Conception est équitable et impartiale, malgré la polémique suscitée.',
        'https://www.gabonreview.com/double-exclusion-a-limmaculee-conception-le-ministere-de-leducation-nationale-salue-une-impartialite-exemplaire/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0bbd8d57-775c-4a25-9c4b-943051f03de5',
        'Notation sévère du Gabon : Oyima « pas tout à fait d’accord » avec Fitch Ratings',
        'Le gouvernement gabonais n’est pas entièrement d’accord avec la note de credit « CCC » donnée par Fitch Ratings, qui reflète une situation économique difficile.',
        'https://directinfosgabon.com/notation-severe-du-gabon-oyima-pas-tout-a-fait-daccord-avec-fitch-ratings/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-24T00:00:00.000Z',
        '2025-09-15T23:06:12.460Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

