-- Batch 2 - Section 1/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES (
        '24d5d9a3-7c56-4acb-9cb3-0313309e8184',
        'DU NOUVEAU A LA FEDERATION GABONAISE DES SOCIETES D’ASSURANCES			 
			TOURISME : UN MARCHÉ EXPONENTIEL			 
			OWENDO CONTAINER T...',
        'L''article annonce l''élection de Stephen Moussirou à la présidence de la Fédération gabonaise des sociétés d’assurances (Fegasa) et détaille ses initiatives visant à élargir l''offre de produits d''assurance, sensibiliser le public et renforcer la collaboration avec le gouvernement pour augmenter la pénétration du marché assurantiel au Gabon.',
        'https://echosdeleco.com/du-nouveau-a-la-federation-gabonaise-des-societes-dassurances/',
        'Les Echos de l''Eco',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '34024525-3c0f-4305-a62c-5bfb9da91616',
        'Bâtis de Femmes : un catalyseur de l’autonomisation économique des femmes et des jeunes filles vulnérables par l’entrepreneuriat',
        'L''association Bâtis de Femmes a organisé une formation gratuite destinée à autonomiser économiquement les femmes et jeunes filles vulnérables par le biais de l''entrepreneuriat.',
        'https://www.gabonews.com/fr/actus/societe/article/batis-de-femmes-un-catalyseur-de-l-autonomisation',
        'Gabonews',
        'Business Femme, Éducation',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a69085d-86e5-4297-8cee-0e146d19aeeb',
        'Mounana accueille avec ferveur le lancement de la campagne présidentielle d’Oligui Nguema',
        'Le 4 avril 2025, Brice Clotaire Oligui Nguema a officiellement lancé sa campagne présidentielle à Mounana, accueillie avec enthousiasme par une foule nombreuse et le soutien de figures locales influentes.',
        'https://kongossanews.info/mounana-accueille-avec-ferveur-le-lancement-de-la-campagne-presidentielle-doligui-nguema/',
        'Kongossa News',
        'Numérique / Digital, Services, Business Femme, Tourisme',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e9b63732-3d47-4acc-90cf-9afa93351d87',
        'Présidentielle 2025 : l’association Libota Ngounga appelle à soutenir le candidat des Bâtisseurs',
        'L’association Libota Ngounga organise une rencontre communautaire pour encourager le soutien au candidat des Bâtisseurs, Brice Clotaire Oligui Nguema, en vue des élections présidentielles de 2025.',
        'https://kongossanews.info/presidentielle-2025-lassociation-libota-ngounga-appelle-a-soutenir-le-candidat-des-batisseurs/',
        'Kongossa News',
        'Autres',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2d0b42f-ec09-46a1-b4cf-e7f9185ea74d',
        'Présidentielle 2025 : les gabonais partagés sur un débat entre les 8 candidats',
        'Les électeurs gabonais sont divisés quant à l''organisation d’un débat entre les huit candidats à la présidentielle de 2025, certains souhaitant une confrontation directe pour mieux choisir, tandis que d’autres préfèrent soutenir le président sortant.',
        'https://gabonmediatime.com/presidentielle-2025-les-gabonais-partages-sur-un-debat-entre-les-8-candidats/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41192d41-179a-46ed-aace-f2fdc1d55e5e',
        'Présidentielle 2025 : les observateurs électoraux à l’épreuve de la neutralité',
        'À huit jours du scrutin présidentiel de 2025, les observateurs électoraux au Gabon se préparent à garantir un processus crédible en respectant les principes d''impartialité, de neutralité et de légalité.',
        'https://gabonmediatime.com/presidentielle-2025-les-observateurs-electoraux-a-lepreuve-de-la-neutralite/',
        'Gabon Media Time',
        'Autres',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.410Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3c924507-8a14-45fa-b1f1-f275d692d029',
        'Crise profonde à l’ARTF : gronde sociale et soupçons de dérives managériales sous la direction d’Adrien Moukabi',
        'La direction d’Adrien Moukabi à l’ARTF est confrontée à une crise sociale et à des soupçons de dérives managériales, provoquant le mécontentement des agents et des menaces de grève.',
        'https://kongossanews.info/crise-profonde-a-lartf-gronde-sociale-et-soupcons-de-derives-manageriales-sous-la-direction-dadrien-moukabi/',
        'Kongossa News',
        'Numérique / Digital, Services, Finances',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd174b0b8-bb89-4de4-b8d3-29d33532b537',
        'Présidentielle 2025 – Oligui Nguema : « Il est temps de bâtir un Gabon libre, productif et solidaire »',
        'À l''approche de l''élection présidentielle de 2025, Brice Clotaire Oligui Nguema présente un programme ambitieux visant à diversifier l''économie gabonaise, lutter contre la corruption et promouvoir un développement libre, productif et solidaire pour transformer durablement le pays.',
        'https://gabonmediatime.com/presidentielle-2025-oligui-nguema-il-est-temps-de-batir-un-gabon-libre-productif-et-solidaire/',
        'Gabon Media Time',
        'Numérique / Digital, Agriculture, Services, Éducation',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8fc1ec87-4959-4068-98a8-2a8064694ace',
        'Présidentielle 2025 : l’Ogooué Maritime adoube Oligui Nguema',
        'Brice Clotaire Oligui Nguema a consolidé son soutien dans la province de l’Ogooué-Maritime en présentant des projets ambitieux axés sur l’amélioration des infrastructures éducatives et médicales, le développement du tourisme et l’économie, renforçant ainsi sa candidature pour la présidentielle 2025.',
        'https://gabonmediatime.com/presidentielle-2025-logooue-maritime-adoube-oligui-nguema/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Tourisme, Éducation',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f822aa15-c0f9-46bd-8408-fececd2ac8ea',
        'Les femmes de la Lombo Bouenguidi mobilisées pour l’arrivée de Brice Clotaire Oligui Nguema',
        'Les femmes du département de la Lombo Bouenguidi se sont mobilisées en soutien à la candidature de Brice Clotaire Oligui Nguema pour l''élection présidentielle de 2025.',
        'https://kongossanews.info/les-femmes-de-la-lombo-bouenguidi-mobilisees-pour-larrivee-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Business Femme, Services',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4e3f234-0deb-4620-adf6-f3652de6aead',
        'Publié le 05 / 04 / 2025',
        'Lors de la campagne présidentielle à Oyem, les candidats sont confrontés à des demandes d''argent de la part des habitants après leurs meetings, les mettant dans une position délicate entre empathie et crainte d''alimenter le clientélisme.',
        'https://union.sonapresse.com/fr/presidentielle-oyem-les-candidats-assaillis-de-demandes-dargent-apres-leurs-meetings',
        'L''Union',
        'Numérique / Digital, Services, Finances',
        '2025-04-05T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58f9cc1b-965e-44b2-950e-80107a667231',
        'Publié le 05 / 04 / 2025',
        'Lors du premier débat présidentiel organisé par la Haute autorité de la communication, la candidate Zenaba Gninga Chaning a présenté son programme axé sur l''économie, le social et la bonne gouvernance, mais a été jugée peu convaincante par les téléspectateurs.',
        'https://union.sonapresse.com/fr/presidentielle-zenaba-gninga-chaning-une-premiere-peu-convaincante',
        'L''Union',
        'Numérique / Digital, Services, Éducation, Business Femme, Finances',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '676f47de-a25c-42f1-b385-64a0a91e7286',
        'Publié le 05 / 04 / 2025',
        'Alain-Claude Bilie-By-Nze, candidat à la présidentielle gabonaise, a présenté son programme axé sur le soutien social, le développement entrepreneurial et la sécurité publique lors de sa campagne de proximité, affirmant qu''en cas de défaite, ses adversaires poursuivront sans lui.',
        'https://union.sonapresse.com/fr/presidentielle-bilie-nze-si-je-ne-gagne-pas-ils-feront-sans-moi',
        'L''Union',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.411Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd70cb28f-8c47-45db-bec3-213b9c93c9f7',
        'Publié le 05 / 04 / 2025',
        'Le ministre de l’Intérieur a annoncé de nouvelles régulations imposant des plafonds de dépenses et une transparence accrue des comptes de campagne pour garantir l’équité et la probité des élections présidentielles au Gabon.',
        'https://union.sonapresse.com/fr/presidentielle-comptes-de-campagne-pour-plus-de-transparence',
        'L''Union',
        'Numérique / Digital, Finances, Services',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.412Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c324909-82e1-481f-a119-67aa37d3f211',
        'Présidentielle 2025 : Le collectif des filles et fils du 1er arrondissement de Libreville à la rencontre des habitants de l’île ...',
        'Le collectif des filles et fils du 1er arrondissement de Libreville engage les habitants de l’île d’Akakuè à soutenir Brice Clotaire Oligui Nguema lors de la présidentielle 2025.',
        'https://kongossanews.info/presidentielle-2025-le-collectif-des-filles-et-fils-du-1er-arrondissement-de-libreville-a-la-rencontre-des-habitants-de-lile-dakakue-alibandengue/',
        'Kongossa News',
        'Services, Éducation, Transport',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.412Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f144000f-6a48-4a71-9704-baa073a70acf',
        'Données statistiques : La candidate Zenaba Gninga Chaning sans repère !',
        'Lors d’un débat présidentiel, la candidate Zenaba Gninga Chaning a exposé son programme axé sur l’économie, le social et la bonne gouvernance, mais a manqué de détails et de maîtrise des données statistiques, suscitant des doutes chez les électeurs.',
        'https://directinfosgabon.com/donnees-statistiques-la-candidate-zenaba-gninga-chaning-sans-repere/',
        'Direct infos Gabon',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.412Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ead2f18-707a-4e11-919e-c0ce8f7a815f',
        'TRIBUNE / « Présidentielle du 12 avril, notre responsabilité collective est engagée »',
        'L''auteur appelle à une responsabilité collective lors de la présidentielle du 12 avril pour orienter le Gabon vers une gouvernance exemplaire et un développement socio-économique durable.',
        'https://directinfosgabon.com/tribune-presidentielle-du-12-avril-notre-responsabilite-collective-est-engagee/',
        'Direct infos Gabon',
        'Numérique / Digital, Éducation, Services, Agriculture',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.412Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4381b4a7-0e1d-45d8-ad87-f03bc0eef48d',
        'Presidentielle 2025 : Bilie-By-Nze demande pardon et plaide pour une reconciliation nationale',
        'Alain-Claude Bilie-By-Nze, candidat à la présidentielle de 2025, a demandé pardon pour ses erreurs passées et plaidé pour une réconciliation nationale lors d''une émission spéciale sur Gabon 24.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-bilie-by-nze-demande-pardon',
        'Gabonews',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.413Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'beca53d8-a7b8-4baa-8d45-1497f367889f',
        'Gabon : une élection avec ou sans suspense ?',
        'Le Gabon se prépare pour l’élection présidentielle du 12 avril 2025 avec huit candidats en lice, analysant la campagne électorale et la possibilité d’un second tour.',
        'https://gabonactu.com/blog/2025/04/05/gabon-une-election-avec-ou-sans-suspense/',
        'Gabon Actu',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.413Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5371761-5a61-4ef7-b44d-e536f87e386f',
        'Terminal de liquéfaction du Cap Lopez : Un nouveau navire de stockage pour Pérenco',
        'Dixstone, filiale de Perenco, a acquis et converti le méthanier LNG Bayelsa en unité de stockage de gaz naturel liquéfié pour le futur terminal de liquéfaction du Cap Lopez au Gabon.',
        'https://directinfosgabon.com/terminal-de-liquefaction-du-cap-lopez-un-nouveau-navire-de-stockage-pour-perenco/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.413Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22e38ed1-1776-4de1-9dc8-74fa67849e3f',
        'Le Gabon n’achète pas de carburant au Togo qui plus est ne dispose pas de raffinerie (SOGARA)',
        'L''article traite des préparatifs et initiatives en vue de l''élection présidentielle de 2025 au Gabon, mettant en lumière les actions des différents candidats et leurs projets pour le développement économique et social du pays.',
        'https://gabonactu.com/blog/2025/04/06/le-gabon-nachete-pas-de-carburant-au-togo-qui-plus-est-ne-dispose-pas-de-raffinerie-sogara/',
        'Gabon Actu',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.413Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c66f4ee7-1d51-4cc5-bd52-e9f40555b3d8',
        'Biens mal acquis : 15 ans d’instruction et 55 milliards de FCFA de patrimoine illégal',
        'Après plus de 15 ans d''enquête, les biens mal acquis de la famille Bongo, évalués à 55 milliards de FCFA et incluant des propriétés en France, sont désormais en attente de décision judiciaire, illustrant les défis de la lutte contre la corruption internationale.',
        'https://directinfosgabon.com/biens-mal-acquis-15-ans-dinstruction-et-55-milliards-de-fcfa-de-patrimoine-illegal/',
        'Direct infos Gabon',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.413Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63f398e1-faf6-4137-9fba-d88054ded3cc',
        'Lastourville deviendra un nouveau pôle d’exploitation de manganèse au Gabon, selon Oligui Nguema',
        'Brice Clotaire Oligui Nguema annonce que Lastourville deviendra un nouveau centre d’exploitation de manganèse au Gabon, promettant la création d’emplois et le développement local.',
        'https://gabonactu.com/blog/2025/04/06/lastourville-deviendra-un-nouveau-pole-dexploitation-de-manganese-au-gabon-selon-oligui-nguema/',
        'Gabon Actu',
        'Commerce, Services, Agriculture',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d4bb284-fd5f-4d3a-9962-571058ff87dd',
        'Rationalisation de la dépense : ACBBN prévoit supprimer le Sénat, le CESE, le CND…',
        'Le candidat à la présidentielle Alain-Claude Bilie-By-Nze propose de rationaliser les dépenses publiques en supprimant le Sénat, le CESE et le CND dans le cadre de son projet de société « Osons ensemble l’espérance ».',
        'https://directinfosgabon.com/rationalisation-de-la-depense-acbbn-prevoit-supprimer-le-senat-le-cese-le-cnd/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '66bfd47b-8934-4461-9c4d-4015671b0b72',
        'Présidentielle 2025: À Akanda, la coordination du 2e arrondissement mobilise les populations en faveur de Brice Clotaire Oligui ...',
        'Lors d’un grand meeting à Akanda, la coordination locale du 2ᵉ arrondissement a mobilisé les populations en faveur de Brice Clotaire Oligui Nguema pour la présidentielles de 2025.',
        'https://kongossanews.info/presidentielle-2025-a-akanda-la-coordination-du-2e-arrondissement-mobilise-les-populations-en-faveur-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48f6c669-2078-4c84-8b87-a16bf2ffc807',
        'Présidentielle 2025 : Nouvelle Aurore pose la dissolution du PDG',
        'Lors des élections présidentielles gabonaises de 2025, le mouvement Nouvelle Aurore exige la dissolution du Parti Démocratique Gabonais (PDG) comme condition pour soutenir un candidat alternatif à Brice Clotaire Oligui Nguema, visant ainsi à restaurer la légalité politique et institutionnelle du pays.',
        'https://gabonmediatime.com/presidentielle-2025-nouvelle-aurore-pose-la-dissolution-du-pdg/',
        'Gabon Media Time',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a621a514-6e2e-4dd0-9f25-30500683c746',
        'Thierry Yvon Ngoma : « Moi élu Président, je vais encourager les femmes à faire des enfants »',
        'Le candidat à la présidentielle 2025 au Gabon, Thierry Yvon Ngoma, s''engage à encourager les femmes à faire des enfants afin de stimuler la natalité et renforcer leur rôle au sein de la société.',
        'https://gabonmediatime.com/thierry-yvon-ngoma-moi-elu-president-je-vais-encourager-les-femmes-a-faire-des-enfants/',
        'Gabon Media Time',
        'Business Femme, Services',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47de9b7b-901a-48e7-b9df-a4c9697b5aaa',
        'Préparatifs des opérations de vote dans le Moyen Ogooué : la commission électorale provinciale sur le terrain',
        'Le président de la commission électorale du Moyen Ogooué a effectué une visite surprise des centres de vote du 2 au 3 avril pour vérifier les préparatifs des opérations électorales.',
        'https://gabonactu.com/blog/2025/04/06/preparatifs-des-operations-de-vote-dans-le-moyen-ogooue-la-commission-electorale-provinciale-sur-le-terrain/',
        'Gabon Actu',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c07950a-d418-42f3-860a-16e6dbe4d132',
        'Fuite de pétrole sur le pipeline Coucal-Rabi : Perenco se mobilise et réagit',
        'Une fuite de pétrole s''est produite sur le pipeline Coucal-Rabi près de Port-Gentil dans la nuit du 5 au 6 avril 2025. Perenco, l''exploitant du site, a isolé la section touchée et lancé des opérations pour limiter les impacts, tandis qu''une enquête est en cours.',
        'https://www.gabonreview.com/fuite-de-petrole-sur-le-pipeline-coucal-rabi-perenco-se-mobilise-et-reagit/',
        'Gabon Review',
        'Services, Agriculture, Numérique / Digital',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fbb4edab-62ba-432d-9b39-bea63e86e753',
        'Présidentielle 2025 : Nouvelle Aurore pose la dissolution du PDG',
        'Un nouveau parti politique gabonais, Nouvelle Aurore, propose la dissolution du PDG, ancien parti au pouvoir, dans le cadre des préparatifs pour l''élection présidentielle de 2025. Cette initiative vise à favoriser un renouveau démocratique après la transition politique récente.',
        'https://gabonmediatime.com/presidentielle-2025-nouvelle-aurore-pose-la-dissolution-du-pdg/',
        'Gabon Media Time',
        'Autres',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '453fb92a-de84-4e86-a806-3daff3221e61',
        'Thierry Yvon Ngoma : « Moi élu Président, je vais encourager les femmes à faire des enfants »',
        'Un candidat à la présidentielle gabonaise promet d''encourager les femmes à faire plus d''enfants s''il est élu, affirmant que cela renforcera la démographie et le développement du pays.',
        'https://gabonmediatime.com/thierry-yvon-ngoma-moi-elu-president-je-vais-encourager-les-femmes-a-faire-des-enfants/',
        'Gabon Media Time',
        'Business Femme, Éducation',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.414Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f12a696-95cc-41c0-8b79-a64caca0516d',
        'Cocotiers : Le collectif « Zéro Casse, Zéro Distraction » à la rencontre de la jeunesse consciente',
        'Le collectif Zéro Casse, Zéro Distraction a organisé une rencontre avec la jeunesse du quartier Cocotier pour sensibiliser contre les violences électorales et encourager le soutien au candidat Brice Clotaire Oligui Nguema.',
        'https://kongossanews.info/cocotiers-le-collectif-zero-casse-zero-distraction-a-la-rencontre-de-la-jeunesse-consciente/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services, Business Femme',
        '2025-04-06T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eada254a-a1ad-4c3d-b4c1-2f6b9fbfefc5',
        'Crise diplomatique entre l''AES et Alger après la destruction d''un drone malien',
        'L’AES (Alliance des États du Sahel) a rompu ses relations diplomatiques avec l’Algérie après des déclarations jugées inacceptables, aggravant les tensions régionales. Cette décision intervient dans un contexte de désaccords politiques et sécuritaires entre les deux parties.',
        'https://www.gabonews.com/fr/actus/international/article/crise-diplomatique-entre-l-aes-et-alger-apres-la',
        'Gabonews',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b5dcef05-6c9f-449b-9722-8d8017161587',
        'Lombo-Bouenguidi/Pensée Patriotique : Mobilisation totale pour voter Oligui Nguema',
        'Lombo Bouenguidi appelle à une mobilisation patriotique pour le développement du Gabon, soulignant l''importance de l''unité et de l''engagement citoyen. Il insiste sur la nécessité d''une pensée collective tournée vers le progrès national.',
        'https://www.gabonews.com/fr/actus/politique/article/lombo-bouenguidi-pensee-patriotique-mobilisation',
        'Gabonews',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8c99e0a4-73af-41f1-826c-184585b680c1',
        'Publié le 06 / 04 / 2025',
        'L’article explique le rôle de Lydie Stéphanie Mamiaka dans le contrôle et l’application de la loi électorale à l’échelle provinciale, mettant en lumière son engagement pour des élections transparentes et équitables. Il souligne l’importance de son travail pour renforcer la crédibilité du processus démocratique.',
        'https://union.sonapresse.com/fr/lydie-stephanie-mamiaka-controler-et-assurer-le-respect-de-la-loi-electorale-lechelle-provinciale',
        'L''union',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c70e832e-5996-4c06-a698-b422eace3c5b',
        'Publié le 06 / 04 / 2025',
        'Le candidat Nyangamayumba critique le projet de centrale à gaz, estimant qu''il ne répond pas aux besoins énergétiques locaux et pourrait aggraver la dette publique. Il propose plutôt des solutions alternatives comme les énergies renouvelables pour un développement plus durable.',
        'https://union.sonapresse.com/fr/presidentielle-nyangamayumba-la-centrale-gaz-en-ligne-de-mire',
        'L''union',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1eee667-9389-45b1-a79e-93018e6583f2',
        'Publié le 06 / 04 / 2025',
        'La présidentielle au Congo suscite à la fois des inquiétudes face aux tensions politiques et des espoirs de changement parmi la population, dans un contexte marqué par des enjeux démocratiques et socio-économiques.',
        'https://union.sonapresse.com/fr/presidentielle-leconi-entre-inquietude-et-espoir',
        'L''union',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06b25648-deff-4998-b5bb-2008c1c198b8',
        'Le fer de Milingui : un levier pour l’industrialisation de la Nyanga, selon Oligui Nguema',
        'Le fer de Milingui pourrait stimuler l''industrialisation de la Nyanga, selon le président Oligui Nguema, qui voit dans cette ressource minière un potentiel économique important pour la région.',
        'https://gabonactu.com/blog/2025/04/07/le-fer-de-milingui-un-levier-pour-lindustrialisation-de-la-nyanga-selon-oligui-nguema/',
        'Gabon Actu',
        'Commerce, Agriculture, Finances',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'df1e5543-bdf4-4d5d-9a84-dfc3bb48140f',
        'Perenco et les autorités gabonaises mobilisées suite à un écoulement de pétrole',
        'Une fuite de pétrole au Gabon a mobilisé la société Perenco et les autorités locales pour contenir la pollution et évaluer les impacts environnementaux. Les équipes interviennent pour nettoyer la zone et prévenir d’éventuels risques écologiques.',
        'https://gabonactu.com/blog/2025/04/07/perenco-et-les-autorites-gabonaises-mobilisees-suite-a-un-ecoulement-de-petrole/',
        'Gabon Actu',
        'Environnement, Services, Numérique / Digital',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0530024-a276-4080-962c-f9277a4b8a85',
        'Moanda, Mounana et Bakoumba : les bras ouverts pour accueillir et soutenir la candidature d''Oligui Nguema',
        'Les villes de Moanda, Mounana et Bakoumba au Gabon accueillent favorablement une initiative politique, marquant une ouverture à des projets ou collaborations futures dans la région.',
        'https://www.gabonews.com/fr/actus/politique/article/moanda-mounana-et-bakoumba-les-bras-ouverts-pour',
        'Gabonews',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a3508ba-a9c2-48fa-a0bc-6297fdacc830',
        'Publié le 06 / 04 / 2025',
        'L’article explique le rôle de Lydie Stéphanie Mamiaka dans le contrôle et l’application de la loi électorale à l’échelle provinciale, mettant en lumière son engagement pour garantir des processus électoraux transparents et équitables.',
        'https://union.sonapresse.com/fr/lydie-stephanie-mamiaka-controler-et-assurer-le-respect-de-la-loi-electorale-lechelle-provinciale',
        'L''union',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '251cdb20-203b-4164-b5d3-b8b043f2b52f',
        'Publié le 06 / 04 / 2025',
        'Un candidat à la présidentielle s''engage à mettre en service la centrale à gaz de Nyangamayumba pour résoudre les problèmes d''électricité, critiquant les retards actuels du projet. Il promet également de renforcer l''éducation et la formation professionnelle pour créer des emplois.',
        'https://union.sonapresse.com/fr/presidentielle-nyangamayumba-la-centrale-gaz-en-ligne-de-mire',
        'L''union',
        'Numérique / Digital, Éducation, Services, Agriculture',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f551658b-6a1c-4afc-8f18-eaebc06a7ca2',
        'Publié le 06 / 04 / 2025',
        'La présidentielle au Congo suscite à la fois des craintes et des espoirs parmi la population, avec des interrogations sur le processus électoral et l''avenir du pays.',
        'https://union.sonapresse.com/fr/presidentielle-leconi-entre-inquietude-et-espoir',
        'L''union',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f7e1a6c-7a4f-4017-bbea-7a801ce661d4',
        'Présidentielle au Gabon: à Libreville, affluence timide dans des centres de retrait de cartes d’électeurs',
        'À Libreville, la participation est faible dans les centres de retrait des cartes d’électeurs en vue de la présidentielle gabonaise, malgré les appels des autorités à s’inscrire. Certains citoyens expriment des doutes sur l’utilité du vote, tandis que d’autres soulignent des difficultés logistiques.',
        'https://www.rfi.fr/fr/afrique/20250407-pr%C3%A9sidentielle-au-gabon-%C3%A0-libreville-affluence-timide-dans-des-centres-de-retrait-de-cartes-d-%C3%A9lecteurs',
        'RFI',
        'Numérique / Digital, Services, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf27df35-a05c-487c-be99-ec99bf128e66',
        '[Vos réactions] Gabon : une élection avec ou sans suspense ?',
        'L''article discute des réactions des citoyens gabonais concernant une élection à venir, certains anticipant un scrutin sans suspense en raison du contexte politique, tandis que d''autres espèrent une compétition plus ouverte. Les opinions reflètent des divisions sur la crédibilité et l''issue probable du vote.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250407-vos-r%C3%A9actions-gabon-une-%C3%A9lection-avec-ou-sans-suspense',
        'RFI',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b92eb73-9e54-41cc-af6c-3360f1a53128',
        'Voici les produits africains qui seront touchés par les nouveaux droits de douane américains',
        'En Côte d''Ivoire, des jeunes développent des solutions technologiques pour résoudre des problèmes locaux, comme une application de lutte contre la drépanocytose et un robot éducatif, malgré le manque de soutien financier et infrastructurel. Ces innovations montrent le potentiel de l''Afrique dans le domaine tech tout en soulignant les défis à surmonter.',
        'https://www.bbc.com/afrique/articles/cevdgv1w19ko?xtor=AL-73-%5Bpartner%5D-%5Bflipboard%5D-%5Bheadline%5D-%5Bafrique%5D-%5Bbizdev%5D-%5Bisapi%5D',
        'Flipboard',
        'Numérique / Digital, Services, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '65483f09-f794-4604-92ce-ed80207f1fca',
        'Présidentielle au Gabon: à Libreville, affluence timide dans des centres de retrait de cartes d’électeurs',
        'À Libreville, la participation est faible dans les centres de retrait des cartes électorales en vue de la présidentielle gabonaise, malgré les appels des autorités pour inciter les citoyens à s''inscrire. Certains électeurs expriment des doutes sur la transparence du processus électoral.',
        'https://www.rfi.fr/fr/afrique/20250407-pr%C3%A9sidentielle-au-gabon-%C3%A0-libreville-affluence-timide-dans-des-centres-de-retrait-de-cartes-d-%C3%A9lecteurs?utm_slink=rfi.my%2FBYsV&utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Numérique / Digital, Services, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '03303c94-bb99-46f6-a093-2fa32216ea06',
        'Le Woleu-Ntem : Un Pôle économique stratégique pour le Gabon',
        'Le Woleu-Ntem, région frontalière du Gabon, est présenté comme un pôle économique stratégique grâce à ses ressources naturelles, son potentiel agricole et sa position géographique favorable aux échanges avec les pays voisins. Son développement pourrait stimuler l''économie locale et régionale.',
        'https://www.gabonews.com/fr/actus/economie/article/le-woleu-ntem-un-pole-economique-strategique-pour',
        'Gabonews',
        'Numérique / Digital, Agriculture, Commerce',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52cd0620-85ff-49df-aa63-a35b26deafb7',
        'Justine Judith Lekogo, Nina Abouna et Élodie Sandjo au coeur de la mobilisation de Fanceville',
        'Justine Judith Lekogo, Nina Abouna et Élodie sont trois femmes engagées en politique au Gabon, dont les parcours et actions illustrent leur détermination à contribuer au développement du pays. Leurs profils mettent en lumière l’importance croissante des femmes dans la sphère politique gabonaise.',
        'https://www.gabonews.com/fr/actus/politique/article/justine-judith-lekogo-nina-abouna-et-elodie',
        'Gabonews',
        'Business Femme, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eac7c96b-7840-47b8-b5e9-bf503a563d9e',
        'Ecoulement de pétrole à Rabi : Perenco et le gouvernement coordonnent leurs efforts pour gérer l’incident',
        'Une fuite de pétrole s''est produite à Rabi, au Gabon, où Perenco et le gouvernement travaillent ensemble pour gérer l''incident et limiter les impacts environnementaux. Les équipes techniques sont mobilisées pour contrôler la situation et évaluer les dégâts.',
        'https://directinfosgabon.com/ecoulement-de-petrole-a-rabi-perenco-et-le-gouvernement-coordonnent-leurs-efforts-pour-gerer-lincident/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

