-- Batch 5 - Section 16/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'cdc03ae7-bd16-4ba4-856a-50bedbd31ea0',
        'Publié le 09 / 07 / 2025',
        'L’Union des des banques (UDB) organise un tour pour promouvoir l’inclusion financière et renforcer la collaboration entre institutions financières en Afrique.',
        'https://union.sonapresse.com/fr/udb-qui-le-tour',
        'L''union',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e6411405-81ba-4d61-9c9c-e81ddeffe4af',
        'Publié le 09 / 07 / 2025',
        'Oligui Nguema incarne un symbole de changement et de transition politique au Gabon, incarnant la continuité tout en promettant des réformes pour le pays.',
        'https://union.sonapresse.com/fr/oligui-nguema-washington-tout-un-symbole',
        'L''union',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd04d776-7314-4d3c-b0ae-9bd2599ad50e',
        'Programme d’urbanisation du Grand-Libreville : BGFIBank et Mika Service signent une  convention de financement',
        'Une convention de financement a été signée entre BGFIBank et Mika Service pour soutenir le programme d’urbanisation du Grand Libreville, visant à améliorer le développement et l’aménagement de la ville.',
        'https://mediapostegabon.com/programme-durbanisation-du-grand-libreville-bgfibank-et-mika-service-signent-une-convention-de-financement/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89425a07-4403-40cf-a731-12475a8e6401',
        'Protection sociale: le Gabon honore ses associations engagées pour la solidarité nationale Hygiène menstruelle : l’ONG La Main s...',
        'Le gouvernement gabonais a honoré et soutenu diverses associations engagées dans la solidarité sociale afin de renforcer la protection sociale dans le pays.',
        'https://mediapostegabon.com/protection-sociale-le-gabon-honore-ses-associations-engagees-pour-la-solidarite-nationale/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e5a152e-c78e-4035-aada-aa5467d46221',
        '«De super minerais» et «des grandes réserves de pétrole» : Donald Trump a reçu cinq présidents africains à la Maison-Blanche',
        'Le président américain a souligné le grand potentiel économique de l''Afrique, notamment grâce à ses ressources naturelles comme les minerais et le pétrole, et a rencontré plusieurs chefs d''État africains à la Maison Blanche pour renforcer cette coopération.',
        'https://www.lefigaro.fr/international/de-super-minerais-et-des-grandes-reserves-de-petrole-donald-trump-a-recu-cinq-presidents-africains-a-la-maison-blanche-20250710?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ce6feb5-8702-4db6-864b-c391fabb6fb3',
        'Coupe du monde des clubs: "Faites que cette saison du PSG ne s''arrête jamais"',
        'Donald Trump a changé de position concernant la guerre en Ukraine et a menacé d''imposer des droits de douane supplémentaires sur les produits brésiliens en réponse aux poursuites contre Jair Bolsonaro, tout en proposant un nouveau slogan pour l’Afrique axé sur le commerce.',
        'https://www.france24.com/fr/%C3%A9missions/dans-la-presse/20250710-coupe-du-monde-des-clubs-faites-que-cette-saison-du-psg-ne-s-arr%C3%AAte-jamais?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e3a593c-aaf4-4f59-8db0-88a25cad1d6c',
        'Donald Trump félicite le président du Liberia pour son « bon anglais »... sa langue maternelle',
        'Donald Trump a félicité le président du Liberia pour la maîtrise de son anglais, sa langue maternelle, lors d''une rencontre à la Maison Blanche avec plusieurs chefs d''État africains.',
        'https://www.huffingtonpost.fr/international/article/donald-trump-felicite-le-president-du-liberia-pour-son-bon-anglais-sa-langue-maternelle_252443.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a8633ae8-2e43-4bb9-8d3c-c7e7bac8073c',
        'Coupe du monde des clubs: "Faites que cette saison du PSG ne s''arrête jamais"',
        'Plusieurs événements politiques et sportifs occupent la une de la presse : Donald Trump change sa position sur l’Ukraine en menaçant de taxes supplémentaires, il propose de privilégier le commerce plutôt que l’aide pour l’Afrique, et le PSG a été qualifié pour la finale de la Coupe du monde des clubs après avoir battu largement le Real Madrid.',
        'https://www.france24.com/fr/%C3%A9missions/dans-la-presse/20250710-coupe-du-monde-des-clubs-faites-que-cette-saison-du-psg-ne-s-arr%C3%AAte-jamais',
        'France 24',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0dc8646-23ed-4dd9-a32c-b3b7e23ef29c',
        'Gabon : Le plan à 10 000 milliards de FCFA d’Oyima pour booster la croissance',
        'Le gouvernement gabonais prévoit un plan de développement de 10 000 milliards de FCFA pour stimuler la croissance économique du pays en mettant en œuvre de nouveaux mécanismes et investissements stratégiques.',
        'https://directinfosgabon.com/gabon-le-plan-a-10-000-milliards-de-fcfa-doyima-pour-booster-la-croissance/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0539dbe-d959-473c-804c-2eb1ca3a91a7',
        'Semaine du Gabon Expo 2025 Osaka Rencontre avec le Ministère du Tourisme – Préparatifs Expo 2025 Osaka',
        'Le comité Gabon à l''Expo 2025 Osaka a rencontré le Ministère du Tourisme pour finaliser les activités autour de la valorisation du raphia, des expressions culturelles et du potentiel touristique du Gabon.',
        'https://www.gabonews.com/fr/actus/cooperation/article/semaine-du-gabon-expo-2025-osaka-rencontre-avec',
        'Gabonews',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44d67ad7-dc8b-40b3-8a8f-e8fea895a19d',
        'Awards Makongonio 2025 : Denise Billogue dédie son prix à la ministre de la Femme',
        'La journaliste Denise Billogue a rencontré la ministre de la Femme, de la Famille et de la Protection de l''Enfance pour la remercier de son engagement en faveur de la promotion des femmes au Gabon, après avoir remporté un prix lors des Awards Makongonio 2025.',
        'https://www.gabonews.com/fr/actus/societe/article/awards-makongonio-2025-denise-billogue-dedie-son',
        'Gabonews',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52ead3c5-e5c2-408d-8df9-a28485bb9672',
        'Le Chef de l''État rencontre des investisseurs américains à la Chambre de Commerce des États-Unis',
        'Le Président gabonais a rencontré des dirigeants américains lors d’une réunion pour discuter de projets visant à développer l’économie du Gabon dans des secteurs comme les mines, l’infrastructure, l’aéronautique et l’énergie.',
        'https://www.gabonews.com/fr/actus/economie/article/le-chef-de-l-etat-rencontre-des-investisseurs',
        'Gabonews',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06cc5181-8708-445f-b7a4-bb11f1dba636',
        'USA/Afrique: le come-back du Gabon sur la scène internationale',
        'L''article souligne le renouveau de l''engagement diplomatique du Gabon sur la scène mondiale, notamment à travers la visite officielle du président Ali Bongo en Inde, qui vise à renforcer la coopération économique et politique entre les deux pays.',
        'https://vxp241.com/2025/07/10/usa-afrique-le-come-back-du-gabon-sur-la-scene-internationale/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f40285c2-ab72-430b-a68a-06df12c5dd75',
        '[Vos réactions] Etats-Unis : cinq chefs d''Etat africains à la Maison Blanche',
        'Des dirigeants de cinq pays africains sont reçus à Washington pour discuter de questions commerciales, minières et de sécurité, afin de renforcer leurs relations avec les États-Unis.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250710-vos-r%C3%A9actions-etats-unis-cinq-chefs-d-etat-africains-%C3%A0-la-maison-blanche',
        'RFI',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75ccec00-809b-40de-b9cd-b41c737b5264',
        'Donald Trump discute avec cinq présidents africains',
        'Plusieurs dirigeants africains, dont ceux du Sénégal, de la Guinée-Bissau, de la Mauritanie et du Gabon, se sont réunis pour discuter de questions régionales importantes et renforcer la coopération entre leurs pays.',
        'https://dw.com/p/4xEWh?maca=fra-RSS_fr_Flipboard-11983-xml-media',
        'Flipboard',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c006a197-c56d-45e0-ac49-045b0fc9fddc',
        'Exploitation illégale des forêts :  La mise en garde de Ntossui Allogo aux opérateurs privés',
        'Le ministère des Eaux et Forêts gabonais a lancé une opération de contrôle pour lutter contre l’exploitation illégale des forêts dans plusieurs régions, en mettant en garde les opérateurs privés contre ces pratiques.',
        'https://directinfosgabon.com/exploitation-illegale-des-forets-la-mise-en-garde-de-ntossui-allogo-aux-operateurs-prives/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '873066b6-64c3-432a-8f62-95e8fcbc69ca',
        'Gabon/USA : Brice Clotaire Oligui Nguema reçu à la Maison Blanche par Donald Trump',
        'Le président du Gabon, Brice Clotaire Oligui Nguema, a rencontré le président américain Donald Trump à Washington pour discuter du développement économique, notamment avec un projet de ligne de chemin de fer de 901 km destiné à transporter du minerai de fer et à renforcer l''infrastructure du pays.',
        'https://www.gabonews.com/fr/actus/cooperation/article/gabon-usa-brice-clotaire-oligui-nguema-recu-a-la',
        'Gabonews',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7736a336-fc80-4060-a72a-9f36b7432fd2',
        'Gaz butane : Pétro Gabon va doubler la production nationale',
        'Pétro Gabon prévoit de doubler la production nationale de gaz butane en construisant un nouveau centre d’emplissage et de stockage à Owendo, face à l’usine Sobraga.',
        'https://directinfosgabon.com/gaz-butane-petro-gabon-va-doubler-la-production-nationale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eb35392e-5850-487e-bec4-a78afbcd76a5',
        'Investissements : Oligui Nguema promeut la destination Gabon à Washington',
        'Le président de la transition gabonaise, Oligui Nguema, a rencontré des investisseurs américains à Washington pour promouvoir le pays comme une destination d''opportunités économiques et attractives pour les investissements.',
        'https://directinfosgabon.com/investissements-oligui-nguema-promeut-la-destination-gabon-a-washington/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53a95e83-6372-4cba-ae0e-b506eb2a4cbb',
        'Exploitation illégale des forêts :  La mise en garde de Ntossui Allogo aux opérateurs privés',
        'Le ministère des Eaux et Forêts du Gabon a lancé une opération pour contrôler et lutter contre l''exploitation illégale des forêts dans plusieurs provinces du pays.',
        'https://directinfosgabon.com/exploitation-illegale-des-forets-la-mise-en-garde-de-ntossui-allogo-aux-operateurs-prives/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1eb94847-2c82-4e87-8fc9-39b7175bfcf0',
        'Cinq présidents africains invités à Washington par Donald Trump',
        'Donald Trump a organisé un sommet à la Maison Blanche avec cinq présidents africains pour discuter de commerce, d’investissements et de sécurité, afin de renforcer les liens avec l’Afrique face à l’influence croissante de la Chine et de la Russie sur le continent.',
        'https://www.france24.com/fr/vid%C3%A9o/20250710-cinq-pr%C3%A9sidents-africains-invit%C3%A9s-%C3%A0-washington-par-donald-trump',
        'France 24',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8725ef0f-2df9-4ce0-a6a9-c641ef2e05d7',
        'BCEG : Crédits et financements pour les cliniques et pharmacies',
        'Le ministère de la Santé et la BCEG ont discuté des possibilités de crédits et de financements pour soutenir le développement des cliniques et pharmacies au Gabon.',
        'https://gabonactu.com/blog/2025/07/10/bceg-credits-et-financements-pour-les-cliniques-et-pharmacies/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ae3df97-2a5a-4b5f-9089-6399b14ad5d1',
        'Oligui Nguéma expose ses ‘’Business Plans’’ à Donald Trump',
        'Le président gabonais Brice Clotaire Oligui Nguema a présenté ses projets économiques à Donald Trump lors d''une rencontre à Washington.',
        'https://gabonactu.com/blog/2025/07/10/oligui-nguema-expose-ses-business-plans-a-donald-trump/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35c8c4d9-9669-43af-98d3-79c4eba5c46b',
        'Vidéos cachées de Nourredin : Akure-Davin remet les pendules à l’heure',
        'Le ministre de la Justice a clarifié officiellement le contenu des vidéos cachées de Nourredin Akure, mettant fin aux suppositions et donnant des explications sur cette affaire.',
        'https://gabonactu.com/blog/2025/07/10/videos-cachees-de-nourredin-akure-davin-remet-les-pendules-a-lheure/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '129b3f45-4f9b-48fa-9460-09688ff792bc',
        'Caméra sur instruction : la mise en scène permanente du pouvoir judiciaire gabonais',
        'L''article montre que des caméras sont utilisées en permanence dans le système judiciaire gabonais, donnant l''impression d''une mise en scène constante pour surveiller et filmer les acteurs judiciaires et politiques.',
        'https://www.gabonreview.com/camera-sur-instruction-la-mise-en-scene-permanente-du-pouvoir-judiciaire-gabonais/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57820780-9574-4789-b977-488d907b2bd6',
        'USA : Oligui Nguema rassure les Américains sur la crédibilité du passeport gabonais',
        'Olougui Nguema rassure les Américains sur la crédibilité du passeport gabonais, affirmant qu''il est valable et reconnu internationalement.',
        'https://gabonmediatime.com/usa-oligui-nguema-rassure-les-americains-sur-la-credibilite-du-passeport-gabonais/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9d34973-6f87-4f68-a35d-f189bad99568',
        'Gabon : le Barreau dénonce une violation de la DGR au cabinet de Me Eyue et appelle au « calme » !',
        'Le barreau de Gabon dénonce une violation des règles de déontologie lors d''une intervention au cabinet de Me Eyue et appelle au calme pour préserver la stabilité juridique.',
        'https://gabonmediatime.com/gabon-le-barreau-denonce-une-violation-de-la-dgr-au-cabinet-de-me-eyue-et-appelle-au-calme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '838ff6e5-12f1-4dd1-90da-4f21e63d1b51',
        'Gabon : PDG, RPM, UN et Cie à l’épreuve du positionnement après la naissance de l’UDB',
        'Le article analyse comment le Parti Démocratique Gabonais (PDG), le Rassemblement pour le Gabon (RPG) et d’autres acteurs politiques s’adaptent face à la naissance de l’Union pour la Démocratie et le Développement (UDD) et cherchent à se repositionner dans le paysage politique gabonais.',
        'https://gabonmediatime.com/gabon-pdg-rpm-un-et-cie-a-lepreuve-du-positionnement-apres-la-naissance-de-ludb/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a815df8b-47f8-4620-a270-68be990c852e',
        'Lancement officiel de la Plateforme de réflexion et d’action sur le foncier, l’habitat et l’environnement (PRAFHE)',
        'Une nouvelle plateforme a été lancée pour encourager la réflexion et l’action sur les enjeux liés au foncier, à l’habitat et à l’environnement.',
        'https://kongossanews.info/lancement-officiel-de-la-plateforme-de-reflexion-et-daction-sur-le-foncier-lhabitat-et-lenvironnement-prafhe/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'da3ff0ef-14d7-42ea-99c3-9d458d7ee255',
        'À Washington, le président Oligui Nguema renforce le partenariat stratégique Gabon–États-Unis',
        'Le président américain Joe Biden et le président gabonais Ali Bongo Ondimba ont renforcé leur partenariat stratégique lors d''une rencontre à Washington, soulignant l''importance de la coopération entre les deux pays.',
        'https://kongossanews.info/a-washington-le-president-oligui-nguema-renforce-le-partenariat-strategique-gabon-etats-unis/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '73da95d7-e4db-4599-bb35-e1378aa98e4e',
        'Gabon : l’Unicef au contact des mineurs de la prison centrale de Libreville',
        'Une délégation de l’Unicef a rendu visite aux mineurs incarcérés à la prison centrale de Libreville pour évaluer leurs conditions de détention et échanger avec eux sur leurs projets et difficultés, dans le cadre d’une politique de réinsertion.',
        'https://agpgabon.ga/gabon-lunicef-au-contact-des-mineurs-de-la-prison-centrale-de-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0783de97-255f-49d6-9771-0758c1dfd4ab',
        'Haut-Ogooué : mobilisation des jeunes et femmes du 4e arrondissement de Franceville en faveur de l’UDB',
        'Des jeunes et des femmes du 4e arrondissement de Franceville soutiennent activement la campagne d’adhésion à la nouvelle formation politique, l’Union Démocratique des Bâtisseurs (UDB), lancée récemment par le président Brice Clotaire Oligui Nguema.',
        'https://agpgabon.ga/haut-ogooue-mobilisation-des-jeunes-et-femmes-du-4e-arrondissement-de-franceville-en-faveur-de-ludb/',
        'AGP',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7cf4bd50-cc85-4d16-9ff7-2c8e99c0da07',
        'Affaire Me Eyué Békalé : Le Barreau monte au créneau et dénonce des « violations de procédures »',
        'Le barreau du Gabon accuse des violations de procédures dans le traitement de l’affaire Me Eyué Békalé et dénonce un manquement au respect des règles légales.',
        'https://gabonactu.com/blog/2025/07/10/affaire-me-eyue-bekale-le-barreau-monte-au-creneau-et-denonce-des-violations-de-procedures/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa277f74-7d34-4b11-86db-ff637394f27c',
        'USA : Oligui Nguema rassure les Américains sur la crédibilité du passeport gabonais',
        'Olougui Nguema rassure les citoyens américains sur la crédibilité du passeport gabonais, soulignant ses avancées et ses avantages pour renforcer l’image internationale du pays.',
        'https://gabonmediatime.com/usa-oligui-nguema-rassure-les-americains-sur-la-credibilite-du-passeport-gabonais/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1483ac03-6d01-4ec6-905e-da179ad17c7f',
        'Gabon : le Barreau dénonce une violation de la DGR au cabinet de Me Eyue et appelle au « calme » !',
        'Le barreau gabonais dénonce une violation de la déontologie par le cabinet de Me Eyue et appelle au calme dans le contexte d''une tension juridique.',
        'https://gabonmediatime.com/gabon-le-barreau-denonce-une-violation-de-la-dgr-au-cabinet-de-me-eyue-et-appelle-au-calme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ea06426-4b9a-476b-a0e8-c050ae959af3',
        'Gabon : PDG, RPM, UN et Cie à l’épreuve du positionnement après la naissance de l’UDB',
        'Le Parlement gabonais a adopté une loi portant création de l’Union pour la Démocratie et le Progrès (UDP), visant à renforcer la représentation politique et à promouvoir la démocratie dans le pays.',
        'https://gabonmediatime.com/gabon-pdg-rpm-un-et-cie-a-lepreuve-du-positionnement-apres-la-naissance-de-ludb/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0666cff5-ec0d-4d3f-8b55-66aaaa3fbffb',
        'Lancement officiel de la Plateforme de réflexion et d’action sur le foncier, l’habitat et l’environnement (PRAFHE)',
        'Une nouvelle plateforme a été lancée pour favoriser la réflexion et l’action sur les questions de foncier, d’habitat et d’environnement, afin d’améliorer la gestion durable de ces enjeux.',
        'https://kongossanews.info/lancement-officiel-de-la-plateforme-de-reflexion-et-daction-sur-le-foncier-lhabitat-et-lenvironnement-prafhe/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1f2a460-544f-401f-a5a3-fe81403909b8',
        'À Washington, le président Oligui Nguema renforce le partenariat stratégique Gabon–États-Unis',
        'Le président gabonais, Ali Bongo Ondimba, a renforcé le partenariat stratégique entre le Gabon et les États-Unis lors d''une rencontre avec le président américain, Joe Biden, visant à développer la coopération dans plusieurs secteurs.',
        'https://kongossanews.info/a-washington-le-president-oligui-nguema-renforce-le-partenariat-strategique-gabon-etats-unis/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01331053-28c5-445a-b1fd-9b26225fb7ba',
        'Cameroun : Paul Biya annoncé candidat à l’élection présidentielle 2025',
        'Le président camerounais Paul Biya, âgé de 92 ans, a officiellement annoncé sa candidature à la présidentielle de 2025, suscitant à la fois du soutien et des critiques.',
        'https://agpgabon.ga/cameroun-paul-biya-annonce-candidat-a-lelection-presidentielle-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-10T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ccf675cd-513a-4a41-9e27-11eaf32ac091',
        'eTax, nouveau portail de la DGI pour payer les impôts via Moov Money',
        'Un nouveau portail appelé eTax permet désormais aux contribuables de payer leurs impôts en ligne via Moov Money, facilitant ainsi la gestion des paiements fiscaux au Gabon.',
        'https://gabonactu.com/blog/2025/07/10/etax-nouveau-portail-de-la-dgi-pour-payer-les-impots-via-moov-money/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14d17a76-bc8a-43d0-bf02-3a23915fe53c',
        'Gabon/Criminalité environnementale et Conflit homme-faune : coordination transfrontalière et outils juridiques au cœur des échanges',
        'Une réunion à Libreville a abordé la lutte contre la criminalité environnementale dans le Bassin du Congo, en mettant en avant la coordination transfrontalière et les outils juridiques pour combattre efficacement les réseaux de prédation entre plusieurs pays.',
        'https://agpgabon.ga/gabon-criminalite-environnementale-et-conflit-homme-faune-coordination-transfrontaliere-et-outils-juridiques-au-coeur-des-echanges/',
        'AGP',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9014f10e-9479-493b-ba95-763c4a23e6e3',
        'Valse de chefs d’Etat à Washington… L’actualité vue par les éditorialistes africains',
        'Plusieurs chefs d’États africains se sont rendus à Washington pour un sommet axé sur des questions commerciales, sécuritaires et migratoires, reflétant un intérêt croissant des États-Unis pour renforcer leur influence en Afrique face à la Chine et à l’exploitation des ressources du continent.',
        'https://www.rfi.fr/fr/podcasts/le-d%C3%A9bat-africain/20250711-valse-de-chefs-d-etat-%C3%A0-washington-l-actualit%C3%A9-vue-par-les-%C3%A9ditorialistes-africains',
        'RFI',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '168b18f1-4589-4e27-986b-8a36d1ca29c8',
        'Publié le 10 / 07 / 2025',
        'Le gouvernement gabonais lance un appel d''offres pour produire entre 8 et 10 gigawatts d''électricité, afin de renforcer son réseau électrique et répondre à la demande croissante dans le pays.',
        'https://union.sonapresse.com/fr/gabon-oligui-nguema-lance-un-appel-doffres-pour-produire-entre-8-et-10-gw-delectricite',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aacc3f87-a61f-4704-8c11-cbb408b36dd3',
        'Publié le 10 / 07 / 2025',
        'Plusieurs investisseurs américains s’intéressent au Gabon, attirés par ses opportunités économiques et ses projets de développement dans divers secteurs.',
        'https://union.sonapresse.com/fr/des-investisseurs-americains-seduits-par-le-gabon',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.469Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '428f58dd-fe4a-4cdb-b373-fee7967f3641',
        'Publié le 10 / 07 / 2025',
        'Une nouvelle entente de 300 milliards de FCFA a été signée pour l''exploitation de la potasse de Mayumba, visant à développer cette ressource minière en Afrique centrale.',
        'https://union.sonapresse.com/fr/exploitation-de-la-potasse-de-mayumba-signature-dun-accord-de-300-milliards-de-fcfa',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b05fe691-d0e7-4af5-bdce-f3d619efc476',
        'Gabon : avec l’Union démocratique des bâtisseurs, la galaxie Oligui Nguema prend forme',
        'Le président gabonais a lancé un nouveau parti politique en juillet, en réunissant des personnalités diverses pour renforcer sa position et consolider sa sphère d''influence.',
        'https://www.jeuneafrique.com/1705282/politique/gabon-avec-lunion-democratique-des-batisseurs-la-galaxie-oligui-nguema-prend-forme/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40c88dd0-3d99-4da1-a6c6-18d185a3308d',
        'Le Gabon prêt à dépenser 450 milliards de FCFA pour l’achat de trois gros porteurs Boeing',
        'Le Gabon prévoit d’acheter trois grands avions Boeing d’ici 2029 pour moderniser sa flotte aérienne, avec un budget estimé à 450 milliards de FCFA.',
        'https://directinfosgabon.com/le-gabon-pret-a-depenser-450-milliards-de-fcfa-pour-lachat-de-trois-gros-porteurs-boeing/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc96f5cf-8296-4c0f-a127-6585a610af0c',
        'Le Gabon bientôt terre d’accueil des migrants déportés des Etats-Unis ?',
        'Le Gabon pourrait devenir prochainement un pays d''accueil pour les migrants déportés des États-Unis, suite à une demande formulée lors d''un sommet avec plusieurs présidents africains.',
        'https://directinfosgabon.com/le-gabon-bientot-terre-daccueil-des-migrants-deportes-des-etats-unis/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21fe9c93-f920-4bfa-aad5-2f500401da3e',
        'Samb’a Assurances Gabon vise le Cameroun et la RDC pour son expansion sous-régionale',
        'Samb’a Assurances Gabon, leader en micro-assurance en Afrique centrale, prévoit de s’étendre au Cameroun et en RDC pour renforcer sa présence sous-régionale.',
        'https://directinfosgabon.com/samba-assurances-gabon-vise-le-cameroun-et-la-rdc-pour-son-expansion-sous-regionale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98f9a687-2e6c-4306-a617-b250c2eae04d',
        'Publié le 10 / 07 / 2025',
        'Le Gabon cherche à lancer un appel d''offres pour produire entre 8 et 10 GW d''électricité afin de répondre à ses besoins énergétiques.',
        'https://union.sonapresse.com/fr/gabon-oligui-nguema-lance-un-appel-doffres-pour-produire-entre-8-et-10-gw-delectricite',
        'L''union',
        'Business Intelligence',
        '2025-07-11T00:00:00.000Z',
        '2025-09-15T23:06:12.470Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

