-- Batch 7 - Section 7/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'eb0ecd83-f386-443f-904d-323bb636b386',
        'Gabon/Fête de l’Indépendance : officialisation du chronogramme des célébrations',
        'Le 16 août, le président du Gabon participera à plusieurs cérémonies pour célébrer le 65e anniversaire de l’indépendance, notamment en rendant hommage au fondateur du pays, Léon Mba, et en inaugurant de nouveaux locaux.',
        'https://agpgabon.ga/gabon-fete-de-lindependance-officialisation-du-chronogramme-des-celebrations/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93ce106a-4594-455f-b939-c7141d74898e',
        'Braquage : 10 ans de réclusion criminelle pour Emerson Assoumou alias arrogance',
        'Emerson Assoumou, alias Arrogance, a été condamné à 10 ans de prison pour avoir volé avec une arme apparente lors d’un braquage à Port-Gentil.',
        'https://gabonactu.com/blog/2025/08/14/10-ans-de-reclusion-criminelle-pour-emerson-assoumou-alias-arrogance/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd274e057-5dd4-4c5b-be67-5c0e7cc5b7ed',
        'Le 10 km de Port-Gentil se tiendra le 29 novembre 2025',
        'La 7ème édition du 10 km de Port-Gentil aura lieu le 29 novembre 2025, avec l''organisation assurée lors d''une conférence à Libreville.',
        'https://gabonactu.com/blog/2025/08/14/le-10-km-de-port-gentil-se-tiendra-le-29-novembre-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '518d8767-71a8-46ef-bee8-df3412f25be3',
        'Pétrole : l’Afrique plongerait dans le chaos en cas d’arrêt total d’importation de carburant durant 30 jours',
        'Une interruption totale de l''importation de carburant en Afrique pendant 30 jours pourrait provoquer un chaos économique et social important dans la région.',
        'https://gabonactu.com/blog/2025/08/14/petrole-lafrique-plongerait-dans-le-chaos-en-cas-darret-total-dimportation-de-carburant-durant-30-jours/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9e09b97-a369-4195-8370-07684508112d',
        'Médias : le palais présidentiel maintient le «rattachement stratégique» de Gabon 24',
        'Malgré son autonomie de gestion, la chaîne d''information Gabon 24 reste sous la tutelle stratégique de la présidence, conformément à la nouvelle organisation administrative du pays.',
        'https://www.gabonreview.com/medias-le-palais-presidentiel-maintient-le-rattachement-strategique-de-gabon-24/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28f2028c-7ecb-43e5-884d-303cf21244de',
        'Le Président de la République inaugure plusieurs infrastructures à Kango et à Cocobeach.',
        'Le président a poursuivi sa tournée nationale en visitant Kango, où il a rencontré la population, participé à une cérémonie religieuse, et inauguré plusieurs projets pour le développement local.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-president-de-la-republique-inaugure-plusieurs',
        'Gabonews',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.492Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aca11948-064d-4e96-86fc-fa55656394ed',
        'BAD : Le Gabon doit mobiliser 1 milliard de dollars par an pour son développement',
        'Le Gabon doit mobiliser environ un milliard de dollars chaque année pour financer son développement afin de réduire sa dépendance au pétrole et stabiliser sa croissance économique.',
        'https://www.gabonreview.com/bad-le-gabon-doit-mobiliser-1-milliard-de-dollars-par-an-pour-son-developpement/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3bb2f77-51cf-4532-ad33-6bce83163aa9',
        '100 jours du gouvernement : État des lieux et perspectives avec le ministre des Transports',
        'Après trois mois en fonction, plusieurs ministres, dont celui des Transports, ont présenté un bilan pour évaluer les progrès et les défis du gouvernement gabonais.',
        'https://www.gabonreview.com/100-jours-du-gouvernement-etat-des-lieux-et-perspectives-avec-le-ministre-des-transports/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5ccb830-5f81-4d26-a3c2-380d10cdc630',
        'Mont‑Bouët : la Mairie veut mettre de l’ordre sur le linéaire Tour–Gare routière',
        'La mairie de Libreville a lancé une opération pour sensibiliser et marquer le long de l’axe Tour–Gare routière au marché Mont-Bouët, afin de réorganiser cet espace commercial et améliorer son organisation.',
        'https://www.gabonreview.com/mont%e2%80%91bouet-la-mairie-veut-mettre-de-lordre-sur-le-lineaire-tour-gare-routiere/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fff66e67-9bc4-4b3f-80b6-bf47c6f01f39',
        'Gabon/Économie numérique : fibre optique, paiement électronique et digitalisation au cœur du bilan des 100 jours',
        'Le Gabon a fait des progrès dans la digitalisation en développant la fibre optique, en encourageant les paiements électroniques et en modernisant l’administration, grâce aux efforts du gouvernement et au partenariat avec la Banque mondiale.',
        'https://agpgabon.ga/gabon-economie-numerique-fibre-optique-paiement-electronique-et-digitalisation-au-coeur-du-bilan-des-100-jours/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a386858-c734-44f3-8341-bd1b3cb3dd3a',
        'Production avicole : le Gabon prépare la fin de l’importation des poulets de chair',
        'Le Gabon prépare la fin de l''importation de poulets de chair en favorisant le développement de la production locale grâce à l’analyse de données agricoles et à des mesures pour soutenir l’élevage avicole.',
        'https://agpgabon.ga/production-avicole-le-gabon-prepare-la-fin-de-limportation-des-poulets-de-chair/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffbb1ac3-ae7d-4094-939b-69f5eb20578e',
        'Setrag : Un incident technique modifie les horaires des trains de voyageurs',
        'Un incident technique a entraîné la modification des horaires des trains de voyageurs de la société Setrag.',
        'https://directinfosgabon.com/setrag-un-incident-technique-modifie-les-horaires-des-trains-de-voyageurs/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffc23b6d-36b7-49fe-8c69-e12e2a11df16',
        'Athlétisme/10 KM de Port-Gentil : la 7e édition fixée au 29 novembre prochain',
        'La 7e édition du 10 km de Port-Gentil est programmée pour le 29 novembre 2025, avec la participation prévue de 13 500 athlètes.',
        'https://agpgabon.ga/athletisme-10-km-de-port-gentil-la-7e-edition-fixee-au-29-novembre-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd3f7c640-bc99-4f88-8036-f5b64ba07f59',
        'Gabon / Fourniture en eau et en énergie : 2 000 milliards pour résoudre les problèmes sur 7 ans',
        'Le gouvernement gabonais prévoit d’investir 2 000 milliards de FCFA sur sept ans pour résoudre les problèmes d’eau et d’énergie en modernisant les infrastructures et en s’attaquant aux causes structurelles de ces difficultés.',
        'https://agpgabon.ga/gabon-fourniture-en-eau-et-en-energie-2-000-milliards-pour-resoudre-les-problemes-sur-7-ans/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '462c65b6-f261-47d4-8c2e-5c56dced145c',
        'Gabon/Leadership féminin : Micheline Georgina Otounga restitue son expérience à la Vitrine F',
        'Micheline Georgina Otounga a partagé à Libreville les leçons qu''elle a tirées de sa participation à la Vitrine F au Burkina Faso, un événement qui valorise le leadership féminin africain.',
        'https://agpgabon.ga/gabon-leadership-feminin-micheline-georgina-otounga-restitue-son-experience-a-la-vitrine-f/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16331684-1fe2-4dea-9896-f88faab638b8',
        'On nous a cassés par erreur ! » Colère et détresse pour les sinistrés du Carrefour Makjoss',
        'Les habitants du Carrefour Makjoss ont découvert que leurs maisons ont été détruites sans préavis, et deux mois plus tard, ils vivent encore à la rue en dénonçant cette destruction qu''ils considèrent comme une erreur.',
        'https://gabonactu.com/blog/2025/08/14/on-nous-a-casses-par-erreur-colere-et-detresse-pour-les-sinistres-du-carrefour-makjoss/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '69546345-35ea-443a-907e-958f0cc94c04',
        '«Pendant que je cherchais l’endroit pour m’enterrer me voilà maintenant entrain de chercher ou dormir » clame le patriarche des sinistrés',
        'Deux mois après leur expulsion, les habitants de certains quartiers de Pleine-Orety cherchent toujours un endroit où dormir ou se reconstruire, exprimant leur détresse face à leur situation difficile.',
        'https://gabonactu.com/blog/2025/08/14/pendant-que-je-cherchais-lendroit-pour-menterrer-me-voila-maintenant-entrain-de-chercher-ou-dormir-clame-le-patriarche-des-sinistres-2/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e444dd1b-7c7a-46d5-ad1e-8595f580b086',
        'Le Temple du Rire : Libreville s’impose comme capitale africaine de l’humour',
        'L’humoriste Omar Defunzu a lancé deux projets importants qui visent à renforcer la scène culturelle gabonaise, notamment en faisant de Libreville la capitale africaine de l’humour.',
        'https://gabonactu.com/blog/2025/08/14/pendant-que-je-cherchais-lendroit-pour-menterrer-me-voila-maintenant-entrain-de-chercher-ou-dormir-clame-le-patriarche-des-sinistres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '516c1926-f15a-4391-930f-1b5b97b076a9',
        'Publié le 14 / 08 / 2025',
        'Lors d''une cérémonie, le président a décoré plusieurs grands serviteurs de l''État en reconnaissance de leur contribution exceptionnelle au pays.',
        'https://union.sonapresse.com/fr/distinctions-le-president-honore-plusieurs-grands-serviteurs-de-letat',
        'L''union',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c1372b71-9472-431b-a7ff-5b9493dc9894',
        'Publié le 14 / 08 / 2025',
        'Un représentant du président congolais a été reçu par le président équatoguinéen, ce qui pourrait renforcer la coopération entre les deux pays.',
        'https://union.sonapresse.com/fr/un-emissaire-du-president-congolais-recu-par-oligui-nguema',
        'L''union',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd291115c-21fb-4c46-a50e-72a36f5cf8f5',
        'Publié le 14 / 08 / 2025',
        'L''article revient sur la célébration du 65e anniversaire de l''indépendance, marquée par une forte mobilisation nationale et un sentiment d''espoir pour l''avenir du pays.',
        'https://union.sonapresse.com/fr/independance-65-premiere-edition-sous-la-ve-republique-tres-attendue',
        'L''union',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '093550dc-a67f-4d16-9106-7e62476f1793',
        'Décorations : quatre dignitaires à l’honneur « Fête de la Libération » : la Nyanga hôte de l’édition 2025 Année scolaire 2025-20...',
        'L''article célèbre quatre personnalités en leur rendant hommage lors d''une cérémonie de décoration.',
        'https://mediapostegabon.com/decorations-quatre-dignitaires-a-lhonneur/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e0630963-1b9d-4224-afea-e677be43aa9d',
        'Gabon : le Chef de l’État met en service le marché du PK 11',
        'Le président gabonais a inauguré un nouveau marché moderne de 1 300 m² dans le quartier PK 11 de Libreville, visant à soutenir l’autonomie des populations et à améliorer les conditions des commerçants, notamment des femmes.',
        'https://agpgabon.ga/gabon-le-chef-de-letat-met-en-service-le-marche-du-pk-11/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9adb51ac-71c2-4a94-b925-8d88e39636c1',
        'Gabon : le nouveau siege du CNOG inauguré',
        'Le président gabonais a inauguré un nouveau bâtiment pour le Comité national olympique, témoignant de son soutien à la promotion du sport dans le pays.',
        'https://agpgabon.ga/gabon-le-nouveau-siege-du-cnog-inaugure/',
        'AGP',
        'Business Intelligence',
        '2025-08-14T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3ac3fbb5-d0d4-466b-928b-3cc1ec0d14a9',
        'Santé/Infrastructures : Le Président Oligui Nguema tient son pari à Moanda',
        'Le 12 août 2025, la ville du Haut-Ogooué a inauguré un nouvel Hôpital Départemental, symbole du progrès médical et de l’unité nationale au Gabon.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/sante-infrastructures-le-president-oligui-nguema',
        'Gabonews',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d019229-c30b-4a03-956e-d84e770d161e',
        'Gabon : détentions abusives, innocents ruinés… et l’État se tait !',
        'L''article dénonce les abus et détentions arbitraires en Guinée, soulignant l''inaction des autorités face aux injustices qui détruisent la vie des innocents et fragilisent l''État.',
        'https://gabonmediatime.com/gabon-detentions-abusives-innocents-ruines-et-letat-se-tait/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c275fb13-c828-447b-9a6f-1ecc3ac4c8f0',
        '10 km POG : 13 500 coureurs attendus lors de la 7ème édition !',
        'Plus de 13 500 coureurs sont attendus pour la septième édition de la course de 10 km organisée à Libreville, réunissant des participants de divers horizons.',
        'https://gabonmediatime.com/10-km-pog-13-500-coureurs-attendus-lors-de-la-7eme-edition/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '504c2852-1404-4794-b38c-3794cfe5735a',
        'Gabon : Oligui Nguema fixe un cap de 10 % de croissance et durcit la discipline budgétaire',
        'Le gouvernement gabonais prévoit de maintenir une croissance économique d''environ 10 % tout en renforçant la discipline budgétaire pour stabiliser l''économie nationale.',
        'https://gabonmediatime.com/gabon-oligui-nguema-fixe-un-cap-de-10-de-croissance-et-durcit-la-discipline-budgetaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'df1664e0-51ee-4527-b9d7-3b422e58f15f',
        'FOIRE SOBRAGA : Des vacances qui s’annoncent intenses dans le Grand Libreville !',
        'La foire Sobraga à Libreville prévoit un début de vacances animé avec de nombreuses animations et activités pour le public.',
        'https://kongossanews.info/foire-sobraga-des-vacances-qui-sannoncent-intenses-dans-le-grand-libreville/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6009620e-1403-4898-83e0-25d694e320c2',
        'Tournée républicaine : à Kango et Cocobeach, le Président Oligui Nguema mise sur le social, l’éducation et les services de base',
        'Le président Oligui Nguema met en avant l''importance des services sociaux, de l''éducation et des services de base pour le développement du pays lors de sa tournée à Kango et Cocobeach.',
        'https://kongossanews.info/tournee-republicaine-a-kango-et-cocobeach-le-president-oligui-nguema-mise-sur-le-social-leducation-et-les-services-de-base/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b7d0c24-dc58-4926-9b2e-164defa38a39',
        'Brice Laccruche Alihanga dévoile la véritable signification de sa formule  »Qui boude bouge »',
        'Brice Laccruche-Alihanga explique la véritable signification de sa formule, révélant les valeurs et intentions qui la sous-tendent dans un contexte de changement et de mobilisation.',
        'https://kongossanews.info/brice-laccruche-alihanga-devoile-la-veritable-signification-de-sa-formule-qui-boude-bouge/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7a64502-1f0a-4daf-8950-87bd23fc9a47',
        'Menaces contre la communauté béninoise au Gabon : Cotonou prépare un rapatriement volontaire',
        'Face aux tensions croissantes à Lambaréné, le gouvernement béninois organise un programme de rapatriement volontaire pour sa communauté au Gabon préoccupée par des menaces et des risques.',
        'https://www.gabonreview.com/menaces-contre-la-communaute-beninoise-au-gabon-cotonou-prepare-un-rapatriement-volontaire/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f139b23f-c081-4c3a-aeff-d55198528618',
        '[Vos réactions] La Libre Antenne du 15 août 2025',
        'L’article présente un exemple d’émission où des auditeurs s''expriment librement sur des sujets divers, mettant en avant des perspectives souvent peu médiatisées.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250815-vos-r%C3%A9actions-la-libre-antenne-du-15-ao%C3%BBt-2025',
        'RFI',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f278df7-d278-4377-8c51-b51a6ddaeeb9',
        'Oyima dresse son bilan après 100 jours au gouvernement',
        'Après 100 jours au gouvernement, le ministre de l’Économie, Henri-Claude Oyima, a présenté un bilan des principales réalisations de son département lors d’un séminaire officiel.',
        'https://directinfosgabon.com/oyima-dresse-son-bilan-apres-100-jours-au-gouvernement/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '544438b8-4b61-454c-9d44-b590d0116733',
        'Centrale d’Achat du Gabon : un outil imparable contre l’inflation exagérée, selon Oyima',
        'La création de la Centrale d’Achat du Gabon vise à lutter efficacement contre l’inflation en permettant à l’État de mieux contrôler les prix et d’assurer l’approvisionnement en produits essentiels.',
        'https://directinfosgabon.com/centrale-dachat-du-gabon-un-outil-imparable-contre-linflation-exageree-selon-oyima/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62db8a7b-1bff-434f-85a0-01e15d39f2e8',
        'Gabon : Le Qatar prêt à investir jusqu’à 500 milliards de FCFA dans des secteurs stratégiques',
        'Le Qatar prévoit d’investir jusqu’à 500 milliards de FCFA dans des secteurs clés du Gabon, comme l’énergie, l’agriculture et les infrastructures, dans le cadre d’une stratégie d’expansion en Afrique.',
        'https://directinfosgabon.com/gabon-le-qatar-pret-a-investir-jusqua-500-milliards-de-fcfa-dans-des-secteurs-strategiques/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0bc1c0bb-8ec9-467b-b86a-f9d156df1509',
        'Gabon : Le Comité national olympique, son nouveau siège et son ambitieux projet de complexe sportif',
        'Le Comité national olympique du Gabon a inauguré son nouveau siège et a présenté un projet ambitieux de complexe sportif olympique dans la commune d’Akanda, visant à renforcer le développement du sport dans le pays.',
        'https://www.gabonreview.com/gabon-le-comite-national-olympique-son-nouveau-siege-et-son-ambitieux-projet-de-complexe-sportif/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78cbac37-e6a0-42ab-a597-6d8609e95d8f',
        'Gabon /DGC: au service de l’intégrité, Zephirine ETOTOWA NTUTUME remet les agents véreux à l’ordre',
        'La directrice générale du Commerce a rappelé à ses agents l''importance de la discipline et de l''intégrité, réagissant aux propos diffamatoires et aux comportements de dénigrement au sein de l''administration.',
        'https://vxp241.com/2025/08/15/gabon-dgc-au-service-de-lintegrite-zephirine-etotowa-ntutume-remet-les-agents-vereux-a-lordre/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'caf38154-87ae-4dde-9493-4809d12ee661',
        'Moanda : la ville minière se dote d’un hôpital interdépartemental',
        'La ville minière de Moanda s''équipe d’un nouvel hôpital interdépartemental pour améliorer les services de santé, dans le cadre du Plan National de Développement Sanitaire financé par l’État gabonais et les fonds RSE d’Eramet Comilog.',
        'https://gabonactu.com/blog/2025/08/15/moanda-la-ville-miniere-se-dote-dun-hopital-interdepartemental/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48d9435f-ff8f-4d50-9bb9-9af44a8b7ac0',
        'Succès fou à Nzeng Ayong pour la 2ème édition de la foire de SOBRAGA',
        'La deuxième édition de la foire organisée par SOBRAGA à Nzeng Ayong a rencontré un grand succès, attirant de nombreux visiteurs et participants.',
        'https://gabonactu.com/blog/2025/08/15/succes-fou-a-nzeng-ayong-pour-la-2eme-edition-de-la-foire-de-sobraga/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a1402eb-1fb8-4b80-b774-7753921b12d4',
        'Santé : une caravane médicale gratuite au profit des populations de Makokou',
        'Une caravane médicale gratuite a été organisée à Makokou pour offrir des examens et des soins, notamment pour les cancers féminins et de la prostate, afin d''aider la population locale.',
        'https://agpgabon.ga/sante-une-caravane-medicale-gratuite-au-profit-des-populations-de-makokou/',
        'AGP',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '283ccaf0-e839-4dc4-872a-12b2903d2c1c',
        'Natation : le Gabon bientôt doté d’une piscine olympique',
        'Le Gabon va bientôt construire une piscine olympique de 50 mètres, avec une tribune de 90 sièges, pour accueillir des compétitions sportives, dans le nouveau siège du Comité national olympique.',
        'https://agpgabon.ga/natation-le-gabon-bientot-dote-dune-piscine-olympique/',
        'AGP',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40aa4877-d9e2-4ca5-9e20-7d33d2930257',
        'Bénin : Cotonou prépare un rapatriement volontaire de ses ressortissants au Gabon',
        'Le gouvernement béninois envisage un rapatriement volontaire de ses ressortissants au Gabon en raison de tensions croissantes et de ressentiments liés à la distribution de places dans un nouveau marché, dans un contexte de restrictions pour les étrangers.',
        'https://agpgabon.ga/benin-cotonou-prepare-un-rapatriement-volontaire-de-ses-ressortissants-au-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97d6c297-c670-46f2-a3cc-0995de6b6ef9',
        'BGFI Holding Corporation : Rhinesse Katsou nommé Directeur général adjoint',
        'Rhinesse Katsou a été nommé deuxième directeur général adjoint de BGFI Holding Corporation, après une carrière au sein du groupe BGFI Bank débutée en 2009 en tant que contrôleur comptable, avec une expertise en finance et comptabilité.',
        'https://directinfosgabon.com/bgfi-holding-corporation-rhinesse-katsou-nomme-directeur-general-adjoint/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a648f4f-b6eb-4127-899d-6ae94caeec00',
        'BGFI Holding Corporation : Un total bilan record de 6957 milliards de FCFA au 1er semestre 2025',
        'Le groupe bancaire BGFI a atteint un bilan record de 6 957 milliards de FCFA au premier semestre 2025, montrant une forte croissance de ses performances financières.',
        'https://directinfosgabon.com/bgfi-holding-corporation-un-total-bilan-record-de-6957-milliards-de-fcfa-au-1er-semestre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b1c637a9-6bc5-4750-9fe9-342c7ce8cb48',
        'Port-Gentil : Flavien Franck Rebela Rogombé crache sur le RPM d’Alexandre Barro Chambrier',
        'Le conseiller spécial du président du RPM a quitté le parti d’Alexandre Barro Chambrier et a exprimé des critiques à son encontre.',
        'https://gabonactu.com/blog/2025/08/15/port-gentil-flavien-franck-rebela-rogombe-crache-sur-le-rpm-dalexandre-barro-chambrier/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0acd5ac8-bc15-4012-b75b-e28d13bcd024',
        'Gabon : Il faut 2 000 milliards de FCFA pour couvrir les besoins en eau et en électricité',
        'Il faudrait environ 2 000 milliards de FCFA pour répondre aux besoins en eau et en électricité au Gabon, selon les estimations du gouvernement.',
        'https://www.gabonreview.com/gabon-il-faut-2-000-milliards-de-fcfa-pour-couvrir-les-besoins-en-eau-et-en-electricite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f48db7df-d80a-40da-9733-74689c13d656',
        'Déguerpissement à Libreville : le drame social des «Abandonnés» du Carrefour Mackjoss',
        'Plusieurs familles ont été évacuées sans relogement ni indemnisation dans le quartier Mackjoss à Libreville, ce qui cause une crise sociale et humanitaire.',
        'https://www.gabonreview.com/deguerpissement-a-libreville-le-drame-social-des-abandonnes-du-carrefour-mackjoss/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dc55d1a-741a-4b9a-92b7-87863d088c2b',
        'Gabon/Football : des membres de l’AEEFG échangent sur l’avenir de leur corporation',
        'Des membres de l’Association des entraîneurs et éducateurs du football du Gabon se sont réunis pour discuter des difficultés qu’ils rencontrent, comme des contrats précaires et de mauvaises conditions de travail, et pour trouver des solutions afin de dynamiser leur organisation.',
        'https://agpgabon.ga/gabon-football-des-membres-de-laeefg-echangent-sur-lavenir-de-leur-corporation/',
        'AGP',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b088050-7b51-4b79-aa0c-7944fc4e3128',
        'Ogooué-Lolo/Festival culturel de Koulamoutou : un retour aux sources pour valoriser la culture',
        'Le festival culturel de Koulamoutou, organisé par le Collectif des Cadres de Koulamoutou, célèbre les traditions locales à travers des danses et activités traditionnelles pour valoriser la culture de la région.',
        'https://agpgabon.ga/ogooue-lolo-festival-culturel-de-koulamoutou-un-retour-aux-sources-pour-valoriser-la-culture/',
        'AGP',
        'Business Intelligence',
        '2025-08-15T00:00:00.000Z',
        '2025-09-15T23:06:12.493Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

