-- Batch 5 - Section 11/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'be699979-ee0c-4c04-b769-a709b35a64cc',
        'Gabon: le président Brice Clotaire Oligui Nguema lance son parti les Bâtisseurs et suscite des questions',
        'Brice Clotaire Oligui Nguema a lancé son nouveau parti politique, Les Bâtisseurs, lors d''une assemblée constitutive à Libreville, invitant ses partisans à s’y inscrire.',
        'https://www.rfi.fr/fr/afrique/20250704-gabon-le-pr%C3%A9sident-brice-clotaire-oligui-nguema-lance-son-parti-les-b%C3%A2tisseurs-et-suscite-des-questions?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a96748b-9d43-46f0-865c-f525a4b61177',
        'Affaire Sylvia et Nourredin Bongo contre l’Etat gabonais : une « stratégie de diversion et  de brouillage judiciaire », selon la Présidence',
        'La présidence gabonaise accuse Sylvia et Nourredin Bongo de tenter de détourner l''attention et de brouiller la justice dans une affaire contre l''État.',
        'https://gabonactu.com/blog/2025/07/04/affaire-sylvia-et-nourredin-bongo-contre-letat-gabonais-une-strategie-de-diversion-et-de-brouillage-judiciaire-selon-la-presidence/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '868bd8c2-27b3-4ea1-bc00-d911f0299c37',
        'Publié le 04 / 07 / 2025',
        'Oligui Nguema doit se rendre à Washington la semaine prochaine pour des discussions importantes avec des responsables américains.',
        'https://union.sonapresse.com/fr/oligui-nguema-attendu-washington-la-semaine-prochaine',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b54c2725-0f4d-4ff9-8ae0-3045af611d11',
        'Publié le 04 / 07 / 2025',
        'Le bilan de la transition évoque les avancées et les défis rencontrés par la région dans la mise en œuvre de ses processus politiques et sociaux depuis le début de la transition.',
        'https://union.sonapresse.com/fr/francophonie-regis-onanga-ndiaye-dresse-le-bilan-de-la-transition',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53312382-ab39-4e98-bcc7-d04010ae2ffb',
        'Publié le 03 / 07 / 2025',
        'Sylvia et Nourredin Bongo affirment qu''ils se défendront en présentant des preuves pour répondre aux accusations dont ils sont visés.',
        'https://union.sonapresse.com/fr/sylvia-et-nourredin-bongo-nous-nous-defendrons-preuves-lappui',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85d053d4-2e01-43fb-82b8-1bf338512f57',
        'Mairie de Libreville : L’Association des Entrepreneurs TaxiGab+ reçu à l’Hôtel de ville Association Ndabilila : mobilisation du ...',
        'L''association des entrepreneurs Taxigab de Libreville a été reçue à l''hôtel de ville pour discuter de leur activité et de leur contribution à l''économie locale.',
        'https://mediapostegabon.com/mairie-de-libreville-lassociation-des-entrepreneurs-taxigab-recu-a-lhotel-de-ville/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a62548f3-4a98-4636-b99c-656ac57456dd',
        'Médias/Awards de la presse : George Alexis Bada, meilleur journaliste sportif de l’année',
        'George Alexis Bada a été élu meilleur journaliste sportif de l’année lors des awards de la presse gabonaise « Makongonio », succédant ainsi à Fusher Edzang.',
        'https://agpgabon.ga/medias-awards-de-la-presse-george-alexis-bada-meilleur-journaliste-sportif-de-lannee/',
        'AGP',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '23388d36-ea28-4bfb-a5de-d97c57871511',
        'Publié le 04 / 07 / 2025',
        'Oligui Nguema doit se rendre à Washington la semaine prochaine pour des discussions diplomatiques et politiques importantes.',
        'https://union.sonapresse.com/fr/oligui-nguema-attendu-washington-la-semaine-prochaine',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8218310-d44f-4b4d-96be-4de17c4035bf',
        'Publié le 04 / 07 / 2025',
        'Le bilan de la transition mené par le Président Régis Onanga Ndiaye met en avant les progrès réalisés, notamment dans la stabilité politique et le développement, tout en soulignant les défis à relever pour renforcer la gouvernance et l’économie.',
        'https://union.sonapresse.com/fr/francophonie-regis-onanga-ndiaye-dresse-le-bilan-de-la-transition',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d908696-e721-4908-8694-fb8cee6158e0',
        'Publié le 03 / 07 / 2025',
        'Sylvia et Nourredin Bongo affirment qu''ils se défendront en apportant des preuves pour prouver leur innocence face aux accusations dont ils sont victimes.',
        'https://union.sonapresse.com/fr/sylvia-et-nourredin-bongo-nous-nous-defendrons-preuves-lappui',
        'L''union',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aa5ee20f-0c84-4935-9b5e-f1b184106b6f',
        'Mairie de Libreville : L’Association des Entrepreneurs TaxiGab+ reçu à l’Hôtel de ville Association Ndabilila : mobilisation du ...',
        'L''association des entrepreneurs Taxigab a été reçue à la mairie de Libreville pour discuter de leurs activités et renforcer la collaboration avec la municipalité.',
        'https://mediapostegabon.com/mairie-de-libreville-lassociation-des-entrepreneurs-taxigab-recu-a-lhotel-de-ville/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cbc5fd24-a860-45b6-adb5-561cf4b0ff31',
        'Le Centre Zita Oligui Nguema pour l''Emploi et l''Entrepreneuriat des Jeunes s''ouvre au public ce 4 Juillet 2025',
        'Le Centre de compétences professionnelles et entrepreneuriales Zita Oligui Nguema, situé à l’Université Omar Bongo, a été officiellement ouvert au public après son inauguration par le président, visant à favoriser l’emploi et l’entrepreneuriat.',
        'https://www.gabonews.com/fr/actus/societe/article/le-centre-zita-oligui-nguema-pour-l-emploi-et-l',
        'Gabonews',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6eeaf6eb-fe2d-4b17-80de-40235936458e',
        'Sensibilisation des communautés villageoises sur la problématique du Conflit Homme-Faune dans le Woleu-Ntem et l''Ogooué-Ivindo.',
        'Des ONG ont mené des activités de sensibilisation dans deux provinces du Gabon pour lutter contre le conflit entre les humains et la faune, dans le cadre du projet Biodiverse Landscape Fund financé par le Royaume-Uni.',
        'https://www.gabonews.com/fr/actus/societe/article/sensibilisation-des-communautes-villageoises-sur',
        'Gabonews',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e1cb8037-2500-481d-a1c0-3114aca16fef',
        'Gabon : les villages en première ligne face au conflit homme-faune',
        'Plus de 13 000 personnes au Gabon ont vu leur vie bouleversée par les incursions d’éléphants et d’animaux sauvages, ce qui a conduit des ONG à organiser des campagnes de sensibilisation et de cartographie pour mieux comprendre et répondre à ce conflit homme-faune.',
        'https://agpgabon.ga/gabon-les-villages-en-premiere-ligne-face-au-conflit-homme-faune/',
        'AGP',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '830f963e-49a3-4400-8721-886bd9c6aba8',
        'Sylvia et Noureddin Bongo accusent les nouvelles autorités de torture',
        'Sylvia Bongo Ondimba et son fils Noureddin, détenus depuis plus de 20 mois après le coup d’État d’août 2023, accusent les nouvelles autorités de les torturer et présentent des preuves vidéo et audio à l’appui.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250704-sylvia-et-noureddin-bongo-accusent-les-nouvelles-autorit%C3%A9s-de-torture?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3522a393-0a71-470c-979a-3d3e6d928a18',
        'Sylvia et Noureddin Bongo accusent les nouvelles autorités de torture',
        'Sylvia Bongo Ondimba et son fils Noureddin accusent les nouvelles autorités gabonaises de les avoir torturés pendant leur détention de 20 mois, en présentant des preuves vidéo et audio, ce que le gouvernement qualifie de diversion.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250704-sylvia-et-noureddin-bongo-accusent-les-nouvelles-autorit%C3%A9s-de-torture',
        'France 24',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3bae37a4-f835-477b-9b01-d7ce16b20ab9',
        'AGL lance sa campagne “Moving Africa Forward” pour la CAN Féminine au Maroc',
        'Africa Global Logistics (AGL) lance une campagne appelée « Moving Africa Forward » pour soutenir l''inclusion des femmes dans le sport et la logistique lors de la Coupe d''Afrique féminine 2024 au Maroc.',
        'https://www.gabonreview.com/agl-lance-sa-campagne-moving-africa-forward-pour-la-can-feminine-au-maroc/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96bb7c25-006c-4a5a-808a-6af4bd55bea4',
        'Gabon/Football : l’élection du président de la Lifom annulée',
        'L’élection du président de la ligue de football de l’Ogooué Maritime a été annulée par la commission de recours de la Fegafoot en raison de la participation de délégués qui ne remplissaient pas les conditions de vote.',
        'https://agpgabon.ga/gabon-football-lelection-du-president-de-la-lifom-annulee/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3f11ace-0b04-4464-8630-186e8658d26a',
        'Le Chef de l''État échange avec le Syndicat National des Magistrats du Gabon (SYNAMAG)',
        'Le président gabonais a rencontré une délégation de magistrats pour discuter de leurs revendications concernant les salaires, la prime de judicature et l''amélioration de leurs conditions de travail.',
        'https://www.gabonews.com/fr/actus/politique/article/le-chef-de-l-etat-echange-avec-le-syndicat',
        'Gabonews',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f107a55-b23d-4c33-8b08-65bbd3b79c06',
        'Théophane Nzame-Nze Biyoghe : «La justice se rend dans les prétoires, pas sur les réseaux»',
        'La justice togolaise a décidé de se rendre dans les prétoires, contrairement aux discussions sur les réseaux sociaux concernant l’affaire, mettant en avant son rôle dans la résolution des enjeux judiciaires.',
        'https://gabonmediatime.com/theophane-nzame-nze-biyoghe-la-justice-se-rend-dans-les-pretoires-pas-sur-les-reseaux/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9403cf76-6f09-4090-93d8-01dcb8c3ff6f',
        'Gabon : 100 milliards de FCFA pour la modernisation de l’Estuaire',
        'Gabon va investir 100 milliards de FCFA pour moderniser le port de l’Estuaire, renforçant ainsi sa plateforme logistique et son commerce maritime.',
        'https://gabonmediatime.com/gabon-100-milliards-de-fcfa-pour-la-modernisation-de-lestuaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a90664f3-d939-482c-b6aa-5d572239e355',
        'BGFIBank Gabon obtient le renouvellement de la certification internationale AML 30 001®',
        'BGFIBank Gabon a renouvelé la certification internationale AML 3.0.001, renforçant ainsi ses mesures de lutte contre le blanchiment d''argent et le financement du terrorisme.',
        'https://gabonmediatime.com/bgfibank-gabon-obtient-le-renouvellement-de-la-certification-internationale-aml-30-001/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b95b49d-10dc-4a14-95bc-04f82c1dc4d6',
        'Tribune libre: Le SOMMET TRUMP–AFRIQUE : POURQUOI CES 5 PAYS AFRICAINS',
        'L''article explique pourquoi cinq pays africains ont été invités à participer au sommet Trump-Afrique, soulignant leur importance stratégique et économique dans le contexte des relations entre l''Afrique et les États-Unis.',
        'https://kongossanews.info/tribune-libre-le-sommet-trump-afrique-pourquoi-ces-5-pays-africains/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a3c071b-928f-4fa8-b638-4c7b0fc926fa',
        'Franceville : l’ONG Belle Vie lance l’opération « Vacances sans sida » dans le 4ᵉ arrondissement',
        'Une opération de sensibilisation et de prévention contre le sida destinée aux jeunes a été lancée dans le 4e arrondissement de Franceville, dans le cadre d’initiatives pour promouvoir la santé et la prévention en milieu urbain.',
        'https://kongossanews.info/franceville-long-belle-vie-lance-loperation-vacances-sans-sida-dans-le-4%e1%b5%89-arrondissement/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0aa324bd-3d18-4e67-82b5-ad9856e5494a',
        'Baccalauréat 2025 : Camélia Ntoutoume Leclercq multiplie les immersions pour valoriser l’enseignement et garantir la qualité des...',
        'Camélia Ntoutoumé-Leclercq multiplie les immersions pour améliorer l''enseignement et garantir des examens de qualité lors du baccalauréat 2025.',
        'https://kongossanews.info/baccalaureat-2025-camelia-ntoutoume-leclercq-multiplie-les-immersions-pour-valoriser-lenseignement-et-garantir-la-qualite-des-examens/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1614b9ba-caef-40a4-af3c-cfe178f8622d',
        'Libreville : La mairie interdit la vente ambulante de café !',
        'La mairie de Libreville a interdit la vente ambulante de café dans toute la ville, pour respecter les lois sur l’hygiène et la salubrité.',
        'https://directinfosgabon.com/libreville-la-mairie-interdit-la-vente-ambulante-de-cafe/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '92cc8f65-cd2e-45e0-9164-d18bf6b0c10f',
        'Terminal méthanier du Cap Lopez : L’ambitieux projet à 1200 milliards de FCFA de Perenco',
        'Perenco a finalisé un investissement de 1 200 milliards de FCFA pour construire une unité flottante de liquéfaction de gaz naturel au terminal de Cap Lopez, prévue pour fonctionner en 2026.',
        'https://directinfosgabon.com/terminal-methanier-du-cap-lopez-lambitieux-projet-a-1200-milliards-de-fcfa-de-perenco/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e25065ef-29c2-407d-a7e8-672982beb49d',
        'Les Sucreries du Gabon visent une production record de 20 000 à 25 000 tonnes en 2025',
        'Les Sucreries du Gabon visent à produire entre 20 000 et 25 000 tonnes de sucre en 2025 pour répondre à la demande locale.',
        'https://directinfosgabon.com/les-sucreries-du-gabon-visent-une-production-record-de-20-000-a-25-000-tonnes-en-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a229764a-2731-4501-b0c0-7d88c7267638',
        'Le Chef de l''État préside la cérémonie de signature de la convention de financement entre l''État gabonais, BGFI Bank et MIKA Services',
        'Le président gabonais a signé un accord de financement de 100 milliards de FCFA pour lancer un programme de modernisation urbaine dans la province de l''Estuaire.',
        'https://www.gabonews.com/fr/actus/economie/article/le-chef-de-l-etat-preside-la-ceremonie-de',
        'Gabonews',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3836016-bc74-4793-ae1f-152304330ae9',
        'La 3e Édition du concours Excellence Dafra a récompensé ses lauréats',
        'La troisième édition du concours scientifique « Excellence Dafra » a récompensé les meilleurs étudiants en Maïeutique et Sciences infirmières à l’Université des Sciences de la Santé de Libreville, avec un focus sur l’éloquence et la communication scientifique.',
        'https://www.gabonews.com/fr/actus/societe/article/la-3e-edition-du-concours-excellence-dafra-a',
        'Gabonews',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eba3ceb2-6662-4080-8841-4a7ef0c03328',
        'Coopération Gabon-Chine : plus de 1 000 consultations médicales gratuites à l’USTM',
        'Plus de 1 000 personnes ont bénéficié de consultations médicales gratuites lors d''une opération organisée à l''université de Masuku en partenariat avec la mission médicale chinoise, visant à offrir des soins solidaires à la communauté.',
        'https://agpgabon.ga/cooperation-gabon-chine-plus-de-1-000-consultations-medicales-gratuites-a-lustm/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b002f6c-975a-4d05-a9cf-6a24731ee015',
        'Gabon/Armée de terre : 50 militaires promus au camp Moulende de Franceville',
        'Cinquante militaires du 2e régiment parachutiste de Franceville ont été promus à différents grades lors d''une cérémonie officielle au camp Moulende.',
        'https://agpgabon.ga/gabon-armee-de-terre-50-militaires-promus-au-camp-moulende-de-franceville/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1fa2fea3-7370-481d-ab38-3c2f460dd591',
        'Gabon/Infrastructures : des avancées notables à Minvoul malgré des défis persistants',
        'La ville de Minvoul connaît une amélioration de ses infrastructures, notamment des travaux de voiries et de bétonnage, grâce à la visite du président et à l’engagement des autorités, malgré la persistance de certains défis.',
        'https://agpgabon.ga/gabon-infrastructures-des-avancees-notables-a-minvoul-malgre-des-defis-persistants/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bb5d79d-6500-4a19-8282-92fd767c13e2',
        'Gabon/Éducation : l’enseignement technique au cœur du développement national',
        'Le renforcement de l’enseignement technique et professionnel en Guinée vise à développer les compétences des jeunes pour soutenir la croissance économique du pays.',
        'https://agpgabon.ga/gabon-education-lenseignement-technique-au-coeur-du-developpement-national/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8cd9f413-7641-4ba4-ad14-4aefd56191e6',
        'Le Ministre de l''Accès Universel à l''Eau et à l''Énergie en visite inopinée sur les sites énergétiques d''Alénakiri, et Akournam',
        'Le ministre de l''Accès universel à l''eau et à l''énergie a effectué des visites surprises sur plusieurs sites de production d''énergie à Libreville pour suivre l''avancement des projets énergétiques en cours.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-ministre-de-l-acces-universel-a-l-eau-et-a-l',
        'Gabonews',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4199d6d2-ab46-465b-9404-79686c11a3d4',
        'Gabon/Éducation : 72,71 % de réussite au BEPC 2025',
        'Environ 72,7 % des candidats inscrits au BEPC 2025 au Gabon ont réussi l''examen, avec plus de 28 500 élèves admis sur près de 40 000 inscrits.',
        'https://agpgabon.ga/gabon-education-7271-de-reussite-au-bepc-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04668283-0f17-40de-8414-7dcc43f2454f',
        '‘’L’Union démocratique des bâtisseurs’’, la nouvelle locomotive de la majorité présidentielle sous le magistère d’Oligui Nguema',
        'Une nouvelle formation politique, « l’Union démocratique des bâtisseurs », devient la principale force de la majorité présidentielle sous la direction d’Oligui Nguema, renforçant la cohesion du camp au pouvoir.',
        'https://gabonactu.com/blog/2025/07/05/lunion-democratique-des-batisseurs-la-nouvelle-locomotive-de-la-majorite-presidentielle-sous-le-magistere-doligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d00bd09-aff8-470f-ad7f-4afcc8266a5f',
        '4e édition du Mandji Battle Dance : insertion sociale, retour aux sources, occupation constructive et sensibilisation des jeunes',
        'La 4e édition du Mandji Battle Dance vise à promouvoir l''insertion sociale, la transmission des traditions, et la sensibilisation des jeunes à travers la danse urbaine.',
        'https://gabonactu.com/blog/2025/07/05/4e-edition-du-mandji-battle-dance-insertion-sociale-retour-aux-sources-occupation-constructive-et-sensibilisation-des-jeunes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '442adeef-dd0c-4041-bdfb-ffa50576f401',
        'Gabon / Pêche artisanale / Inspection des débarcadères : 52 sites illégaux recensés',
        'Deux ministres en charge des mers, de la pêche et de l’environnement ont inspecté plusieurs débarcadères artisanaux au Gabon, recensant 52 sites illégaux à travers le pays.',
        'https://agpgabon.ga/gabon-peche-artisanale-inspection-des-debarcaderes-52-sites-illegaux-recenses/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35247ba0-de27-41c8-80e3-a91de278b4f4',
        'Gabon/UPG : le secrétaire exécutif demande un congrès avant toute fusion-absorption',
        'Le secrétaire exécutif de l’UPG demande la tenue d’un congrès avant toute fusion ou absorption avec d’autres partis politiques, afin de clarifier la position du parti.',
        'https://agpgabon.ga/gabon-upg-le-secretaire-executif-demande-un-congres-avant-toute-fusion-absorption/',
        'AGP',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d83f3ed-4331-452a-8628-37d430a2d320',
        'Le Centre Zita Oligui Nguema pour l’emploi et l’entrepreneuriat des Jeunes ouvre officiellement ses portes',
        'Le Centre Zita Oligui Nguema pour l’emploi et l’entrepreneuriat des jeunes a officiellement ouvert ses portes pour soutenir la formation, l’emploi et l’entrepreneuriat des jeunes gabonais.',
        'https://gabonactu.com/blog/2025/07/05/le-centre-zita-oligui-nguema-pour-lemploi-et-lentrepreneuriat-des-jeunes-ouvre-officiellement-ses-portes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21378fdf-96bf-48fc-a194-0a6a507f6f8d',
        'SEEG : arrêt de la station de production d’eau potable d’Okala, suite à un nouvel acte de vandalisme',
        'La station de production d’eau potable d’Okala a été arrêtée suite à un acte de vandalisme, ce qui perturbe l’approvisionnement en eau dans plusieurs quartiers de la zone.',
        'https://gabonactu.com/blog/2025/07/05/seeg-arret-de-la-station-de-production-deau-potable-dokala-suite-a-un-nouvel-acte-de-vandalisme/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '420030f2-6a69-44d2-baba-1dbe7bd71b07',
        'Naissance de l''Union Démocratique des Bâtisseurs : Quand un Brice appelle un autre Brice pour bâtir',
        'L''Union Démocratique des Bâtisseurs (UDB) a été créée officiellement à Libreville, avec la participation du président Brice Clotaire Oligui Nguema et d''autres figures politiques, dans le but de contribuer au développement et à la stabilité du Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/naissance-de-l-union-democratique-des-batisseurs',
        'Gabonews',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9107182-6ad6-4768-bc33-a10622e9a8c2',
        'Publié le 05 / 07 / 2025',
        'L''OLIGUI Nguema affirme que l''UDB n''est pas un instrument pour prendre le pouvoir, mais un parti destiné à défendre les intérêts du peuple.',
        'https://union.sonapresse.com/fr/oligui-nguema-ludb-ne-sera-pas-un-outil-de-conquete-du-pouvoir',
        'L''union',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0f12ee4-dd66-4b0d-ad43-6879909f4ac5',
        'Publié le 05 / 07 / 2025',
        'Une nouvelle organisation politique, l''Union Démocratique des Bâtisseurs (UDB), a été créée au Gabon pour promouvoir la démocratie et le développement dans le pays.',
        'https://union.sonapresse.com/fr/gabon-lunion-democratique-des-batisseurs-udb-voit-le-jour',
        'L''union',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f71161e-e9a8-42d6-a786-7d3537b64e2f',
        'Publié le 05 / 07 / 2025',
        'Une affluence déjà visible au palais des sports indique un fort enthousiasme en faveur d’un parti présidentiel en pleine campagne électorale.',
        'https://union.sonapresse.com/fr/parti-presidentiel-affluence-deja-perceptible-au-palais-des-sports',
        'L''union',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f933b03-5603-4caf-94c5-66a23352a4fb',
        'Ntoum-Cocobeach : 100 milliards de francs CFA pour la construction de la route',
        'Le gouvernement gabonais prévoit d''investir 100 milliards de francs CFA pour construire une nouvelle route reliant Ntoum à Cocobeach, afin d’améliorer les infrastructures et la connectivité dans la région.',
        'https://mediapostegabon.com/ntoum-cocobeach-100-milliards-de-francs-cfa-pour-la-construction-de-la-route/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f7ae95f-1bff-45f3-8d78-a11c1c6b6b07',
        'Mairie de Libreville : près de 500 agents décorés de la médaille du travail Mairie de Libreville : l’Association des Entrepreneu...',
        'Près de 500 agents de la mairie de Libreville ont été décorés de la médaille du travail en reconnaissance de leur engagement et de leur service.',
        'https://mediapostegabon.com/mairie-de-libreville-pres-de-500-agents-decores-de-la-medaille-du-travail/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8973bd5-595d-49ec-a016-a477fa760956',
        'Espoir La Tigresse rugit aux InterContinental Music Awards aux USA',
        'Une artiste gabonaise est devenue finaliste aux InterContinental Music Awards aux États-Unis dans la catégorie African Pop, grâce à ses chansons "Poison" et "Azagneng", ce qui témoigne de sa montée en popularité internationale.',
        'https://vxp241.com/2025/07/05/espoir-la-tigresse-rugit-aux-intercontinental-music-awards-aux-usa/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b78752d3-b276-4b07-a9b5-19deeff007e8',
        'UDB : Oligui Ngeuma confie le Haut-Ogooué à Brice Laccruche Alihanga, son atout stratégique',
        'Brice Laccruche Alihanga, nouveau conseiller stratégique de l’UDB, a été présenté lors de l’assemblée générale du parti à Libreville, où il a reçu la confiance d’Oligui Ngeuma pour gérer la région du Haut-Ogooué, soulignant son rôle stratégique au sein du mouvement.',
        'https://gabonactu.com/blog/2025/07/05/udb-oligui-ngeuma-confie-le-haut-ogooue-a-brice-laccruche-alihanga-son-atout-strategique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-05T00:00:00.000Z',
        '2025-09-15T23:06:12.467Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

