-- Batch 3 - Section 2/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '38ba3363-81cf-40c4-9ebb-3448a087fd75',
        'Gabon : locales et législatives couplées fixées aux 27 septembre et 11 octobre 2025',
        'Les élections locales et législatives au Gabon sont prévues les 27 septembre et 11 octobre 2025, selon un couplage des scrutins annoncé récemment. Ces dates marquent une étape clé dans le calendrier électoral post-transition.',
        'https://gabonmediatime.com/gabon-locales-et-legislatives-couplees-fixees-aux-27-septembre-et-11-octobre-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2aa7cf4a-168a-4ee1-8110-a4e3f312156c',
        'Gabon : Oligui Nguema prête serment devant le peuple et la communauté internationale',
        'Brice Clotaire Oligui Nguema a été officiellement investi président du Gabon à l’issue d’une cérémonie de prestation de serment, marquant le début de son mandat de sept ans après une transition de 19 mois. Son élection en avril 2024, avec un score écrasant, consolide son pouvoir après le coup d’État ayant mis fin au régime Bongo.',
        'https://gabonmediatime.com/gabon-oligui-nguema-prete-serment-devant-le-peuple-et-la-communaute-internationale/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '94db81da-0385-4662-a3d4-0b9b5300d04d',
        'Gabon: Brice Clotaire Oligui Nguema investi président de la République',
        'Brice Clotaire Oligui Nguema a été investi président de la République gabonaise après avoir remporté l''élection présidentielle du 12 avril 2025 avec un score écrasant. Il a prêté serment en tant que président de la Ve République du Gabon le 3 mai 2025, marquant un tournant majeur dans l''histoire politique du pays depuis le coup d''État de 2023.',
        'https://kongossanews.info/gabon-brice-clotaire-oligui-nguema-investi-president-de-la-republique/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd10e2b2c-4f1b-48f2-b720-bc551b0b2e59',
        'Gabon: Vous avez dit 5e République?',
        'Le Gabon a officiellement amorcé son entrée dans la Cinquième République suite à l''adoption d''une nouvelle Constitution le 19 décembre 2024, après un "coup de libération" le 30 août 2023 qui a mis fin au régime Bongo. Cette nouvelle Constitution a été validée par référendum le 16 novembre 2024, marquant une étape majeure dans l''évolution politique du pays.',
        'https://kongossanews.info/gabon-vous-avez-dit-5e-republique/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80020e31-6a43-480e-a493-240faa39d3c0',
        'Gabon/Transition: Fin de parcours pour le CTRI',
        'Le Comité pour la Transition et la Restauration des Institutions (CTRI) au Gabon a officiellement annoncé sa dissolution le 2 mai 2025 après près de deux années de transition post-coup d''État, marquant le retour à un ordre constitutionnel civil et l''investiture du président élu Brice Clotaire Oligui Nguema. Cette dissolution acte la fin de la mission militaire entamée en août 2023 et le retour des forces armées dans leurs casernes.',
        'https://kongossanews.info/gabon-transition-fin-de-parcours-pour-le-ctri/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8731c4f5-6478-469f-97f8-797643fc12ef',
        'Publié le 03 / 05 / 2025',
        'Je n''ai pas pu accéder directement au contenu de l''article sur le site indiqué. Cependant, si l''article concerne un discours d''investiture d''un président, voici une proposition générale basée sur ce type d''événements :

Le discours a souligné l''importance de l''unité et du développement du pays, renforçant l''engagement à poursuivre les réformes et à améliorer la vie des citoyens. Les efforts vers une gouvernance stable et efficace ont été mis en avant pour assurer une croissance économique et sociale durable.',
        'https://union.sonapresse.com/fr/discours-dinvestiture-du-president-de-la-republique',
        'L''union',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2a8aca6-ce7b-46cb-bad7-2e62a045b5e9',
        'Publié le 03 / 05 / 2025',
        'Le président Brice Clotaire Oligui Nguema a prêté serment au Gabon, marquant la fin d''une transition historique et l''avènement d''une nouvelle ère pour le pays. Son discours a été empreint d''espoir et de reconstruction, avec des engagements pour le progrès, la justice et la stabilité, ainsi que des projets pour transformer l''économie et renforcer la place du Gabon sur la scène internationale.',
        'https://union.sonapresse.com/fr/gabon-un-discours-dinvestiture-sous-le-signe-de-lespoir-et-de-la-reconstruction',
        'L''union',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91e3593f-87ba-4198-bb9a-fb9db84d7ade',
        'Publié le 03 / 05 / 2025',
        'Brice Oligui Nguema, récemment élu président du Gabon, a officiellement lancé le processus préparatoire des prochaines étapes électorales, marquant le début d''une phase institutionnelle clé pour le pays. Cette initiative s''inscrit dans le contexte post-coup d''État visant à rétablir un cadre démocratique après des décennies de pouvoir dynastique.',
        'https://union.sonapresse.com/fr/gabon-oligui-nguema-enclenche-le-compte-rebours-electoral',
        'L''union',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2991f42-0687-4a9b-b5ce-7bfb64ae47b7',
        'Raymond Ndong Sima a remis sa démission',
        'Raymond Ndong Sima a remis sa démission de Premier ministre de la Transition au président Brice Clotaire Oligui Nguema, conformément à la Constitution, avec des remerciements officiels pour son engagement durant cette période[1]. Un nouveau gouvernement est prévu prochainement pour la nouvelle phase politique[1][3].',
        'https://gabonactu.com/blog/2025/05/04/raymond-ndong-sima-a-remis-sa-demission/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6dbc7abd-9bec-4351-bbfe-6bf2422023b4',
        'Liberté de la presse : Les « 10 commandements » de Reporters sans frontières pour le Gabon',
        'Après une amélioration notable de la liberté de la presse au Gabon, ce pays est désormais classé 41ème sur 180 pays selon Reporters sans frontières (RSF). Pour consolider ces avancées, RSF a formulé dix recommandations clés visant à améliorer la législation, l''accès à l''information, et la protection des journalistes, entre autres mesures cruciales pour garantir une presse libre et indépendante.',
        'https://gabonactu.com/blog/2025/05/04/liberte-de-la-presse-les-10-commandements-de-reporters-sans-frontieres-pour-le-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.429Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51b94dd4-fc03-4b6b-ae9c-5f119f814ceb',
        'Gabon : démission du Premier ministre',
        'Le président gabonais Brice Clotaire Oligui Nguema a officiellement reçu la démission du Premier ministre Raymond Ndong Sima et de son gouvernement, marquant la fin d''une période de transition. Cette démission ouvre la voie à la formation d''un nouveau gouvernement conformément à la Constitution gabonaise, après l''investiture du président élu.',
        'https://agpgabon.ga/2025/05/04/gabon-demission-du-premier-ministre/',
        'AGP',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cbe44155-f94f-4474-a3e9-d8134ff209a2',
        'Les gabonais doivent se rassembler autour du Président Oligui Nguema pour conduire le Gabon vers le progrès, selon Patrice Tonda',
        'Patrice Tonda appelle les Gabonais à soutenir le président Brice Clotaire Oligui Nguema pour favoriser l''unité nationale et le progrès du pays. Cet engagement collectif est présenté comme essentiel pour conduire le Gabon vers un avenir meilleur.',
        'https://gabonactu.com/blog/2025/05/04/les-gabonais-doivent-se-rassembler-autour-du-president-oligui-nguema-pour-conduire-le-gabon-vers-le-progres-selon-patrice-tonda/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e7bd68f5-ae02-45c8-be37-783e93647169',
        'RDC / USA : Massad Boulos a échangé quelques mots avec Tshisekedi à Libreville',
        'Massad Boulos, conseiller spécial américain pour l''Afrique, a échangé quelques mots avec le président Félix Tshisekedi au Gabon, lors d''une rencontre à Libreville. Cet échange s''est limité à une salutation chaleureuse accompagnée de quelques phrases entre les deux personnalités.',
        'https://gabonactu.com/blog/2025/05/04/rdc-usa-massad-boulos-a-echange-quelques-mots-avec-tshisekedi-a-libreville/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6872f055-7da9-434b-8510-8c8f5992c23c',
        'Gabon : Murielle Minkoué précise les dates-clés post-transition',
        'Murielle Minkoue Mintsa, ministre chargée des institutions au Gabon, a présenté les dates clés du renouvellement des institutions, s''inscrivant dans le cadre de la transition politique du pays. Ces développements visent à renforcer et réformer les structures politiques gabonaises, notamment en prévision des élections prévues en 2025.',
        'https://agpgabon.ga/2025/05/04/gabon-murielle-minkoue-presente-les-dates-cles-du-renouvellement-des-institutions/',
        'AGP',
        'Business Intelligence',
        '2025-05-04T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '132334aa-8218-4559-9a18-9211fee49736',
        '1er mai chez CECA GADIS : la grandiose fête n’a pas fait oublier les doléances du personnel',
        'Le groupe CECA-GADIS a célébré la Fête du Travail en rendant hommage à l''engagement de son personnel, mais cette célébration n''a pas effacé les préoccupations des employés concernant l''absence d''avantages sociaux et professionnels. Les revendications incluent notamment une assurance maladie complémentaire, une politique salariale interne, des remises sur les achats dans les magasins du groupe et un plan de carrière structuré.',
        'https://gabonactu.com/blog/2025/05/05/1er-mai-chez-ceca-gadis-la-grandiose-fete-na-pas-fait-oublier-les-doleances-du-personnel/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5db27cec-61b3-4c69-9704-1865232b5df8',
        'Gabon /1er mai DGI: l’hommage d’Éric BOUMAH aux agents pilliers de l’administration fiscale',
        'Le 1er mai, la Direction générale des Impôts (DGI) au Gabon a célébré la Fête du Travail en rendant hommage aux efforts de ses agents, avec un discours du directeur général Eric Boumah soulignant leur rôle crucial dans l''administration fiscale. Cette cérémonie a mis en avant les progrès sociaux et les réformes obtenues grâce au dialogue social.',
        'https://vxp241.com/2025/05/05/gabon-1er-mai-dgi-lhommage-deric-boumah-aux-agents-pilliers-de-ladministration-fiscale/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb5f9742-9550-4478-96f5-8d50d0f914ac',
        'Gabon /Célébration du 1er: le CPPL invite une énième fois Laurence NDONG a publié la liste des bénéficiaires de la subvention à la presse',
        'La ministre de la Communication, Laurence Ndong, est mise à contribution pour publier la liste des bénéficiaires de la subvention à la presse 2024, face aux inquiétudes sur l''opacité dans la répartition des fonds. Le Cercle des Patrons de la Presse Privée en Ligne (CPPPL) dénonce des incohérences dans les chiffres et exige plus de transparence, essentielle pour renforcer la confiance dans la gestion publique.',
        'https://vxp241.com/2025/05/05/gabon-celebration-du-1er-le-cppl-invite-une-enieme-fois-laurence-ndong-a-publie-la-liste-des-beneficiaires-de-la-subvention-a-la-presse/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5da2a5b7-f93b-4275-a182-3adec0563163',
        'Investiture d’OLIGUI NGUEMA: un septennat résolument placé au service des gabonais',
        'Brice Oligui Nguema entame son mandat présidentiel de sept ans avec un engagement explicite à prioriser le développement socio-économique et le bien-être des populations gabonaises. Son investiture, marquée par des promesses de réformes structurelles et de lutte contre les inégalités, vise à répondre aux attentes des citoyens après des décennies de gouvernance dynastique.',
        'https://vxp241.com/2025/05/05/investiture-doligui-nguema-un-septennat-resolument-place-au-service-des-gabonais/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e6ba18c-009b-4472-ac3b-e5a91d747328',
        '[Vos réactions] Gabon : les défis du nouveau président',
        'Brice Clotaire Oligui Nguema a prêté serment comme président du Gabon après avoir remporté l''élection avec une majorité écrasante. Il est confronté à de nombreux défis, notamment rétablir la confiance dans les institutions, réformer l''économie, et améliorer les infrastructures du pays.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250505-vos-r%C3%A9actions-gabon-les-d%C3%A9fis-du-nouveau-pr%C3%A9sident',
        'RFI',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f180fa0a-b022-4fdb-a498-fe4f9f62d7e1',
        'Gabon : Liberté de la presse, un frémissement encourageant, un chantier inachevé',
        'Le Gabon fait un bond significatif dans le classement mondial de la liberté de la presse, passant de la 56ème à la 41ème place en 2025. Cependant, malgré ces progrès, la création d''une presse libre et indépendante reste un chantier inachevé, avec des défis persistants pour les journalistes locaux.',
        'https://gabonmediatime.com/gabon-liberte-de-la-presse-un-fremissement-encourageant-un-chantier-inacheve/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76fb3bd3-9941-4950-939a-41fe0d2e3398',
        'Primature : Ndong Sima tire sa révérence, le président salue « un homme d’expérience et de devoir »',
        'Raymond Ndong Sima a officiellement remis sa démission de Premier ministre de la Transition gabonaise au président Brice Clotaire Oligui Nguema, conformément à la Constitution, mettant fin à son mandat marqué par son rôle stabilisateur durant la période post-putsch[5][6]. Le président a salué son engagement et sa contribution essentielle au succès de la transition institutionnelle vers la Ve République[5][6].',
        'https://gabonmediatime.com/primature-ndong-sima-tire-sa-reverence-le-president-salue-un-homme-dexperience-et-de-devoir/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7aa80d9-b072-4192-b4a8-04b3043c12d9',
        'Gabon : Oligui Nguema acte la fin de la Primature avec la démission de Ndong Sima',
        'Le président gabonais Brice Clotaire Oligui Nguema a officiellement reçu la démission de Raymond Ndong Sima, mettant fin à son mandat de Premier ministre de la Transition. Cette étape marque un tournant important dans la Transition politique au Gabon, à la veille de la mise en œuvre des nouvelles institutions de la Vème République.',
        'https://gabonmediatime.com/gabon-oligui-nguema-acte-la-fin-de-la-primature-avec-la-demission-de-ndong-sima/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e8bdea97-33d8-4ff4-8142-a533332b93d8',
        'Publié le 05 / 05 / 2025',
        'Le président chinois Xi Jinping a envoyé un message de félicitations à Brice Clotaire Oligui Nguema pour son élection à la présidence du Gabon, soulignant la traditionnelle amitié entre les deux pays et leur volonté de renforcer leur coopération stratégique. Xi Jinping est prêt à travailler avec le président élu pour mettre en œuvre les accords issus du Forum sur la coopération sino-africaine, afin de promouvoir davantage le partenariat entre leurs nations.',
        'https://union.sonapresse.com/fr/xi-jinping-felicite-oligui-nguema',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fd7ea60-09cc-4c19-88cf-c00865acf249',
        'Publié le 05 / 05 / 2025',
        'L''investiture de Brice Clotaire Oligui Nguema comme président de la République du Gabon a marqué le début de son mandat avec une grande cérémonie au stade d''Angondjé, où il a reçu les félicitations de plusieurs chefs d''État africains. Cette occasion a permis au président d''annoncer les prochaines élections législatives, locales et sénatoriales, marquant ainsi une nouvelle étape pour le pays après le coup d''État de 2023.',
        'https://union.sonapresse.com/fr/investiture-du-president-oligui-nguema-des-symboles-et-du-beau-monde',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff01ccff-d9fb-4f80-8991-3d2d95dcfc80',
        'Publié le 04 / 05 / 2025',
        'Raymond Ndong Sima, Premier ministre de la Transition au Gabon, a officiellement remis sa démission au président Brice Clotaire Oligui Nguema, conformément à la nouvelle Constitution abolissant la fonction de Premier ministre, marquant ainsi la fin de la période transitoire post-coup d''État de 2023[2][4][5]. Son départ clôt un chapitre institutionnel majeur, ouvrant la voie à une nouvelle configuration politique centrée sur un régime présidentiel renforcé[4][5].',
        'https://union.sonapresse.com/fr/gabon-raymond-ndong-sima-quitte-la-primature',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e90b0fd7-180c-4f82-bc84-3b4e86e255f8',
        'Au Gabon, la pratique du Journalisme à l’épreuve du jugement Libreville : le Centre National d’examen du permis de conduire vand...',
        'La pratique journalistique au Gabon fait face à des défis majeurs, notamment l''intrusion de non-professionnels dans le secteur et un environnement médiatique soumis à des tensions structurelles, selon une analyse récente. Ces difficultés soulignent les risques de dérives éthiques et la nécessité de renforcer les compétences professionnelles pour garantir une information fiable[1].',
        'https://mediapostegabon.com/au-gabon-la-pratique-du-journalisme-a-lepreuve-du-jugement/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bcfdf007-5d0b-454a-be6f-ca9719946bf8',
        'Le Chef de l’État reçoit un envoyé spécial du Président de la République Populaire de Chine',
        'Le Président de la République, Brice Clotaire Oligui Nguema, a reçu en audience l''envoyé spécial de Xi Jinping, Mu Hong, qui a transmis des félicitations pour son investiture récente. Cette rencontre a marqué la volonté de la Chine de renforcer ses relations d''amitié et de coopération avec le Gabon, notamment dans les domaines des infrastructures.',
        'https://gabonactu.com/blog/2025/05/05/le-chef-de-letat-recoit-un-envoye-special-du-president-de-la-republique-populaire-de-chine/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08857487-f4ab-49d4-bee9-f3a2c7f804eb',
        'Infrastructures : La Chine confirme son soutien au Gabon',
        'La Chine confirme son soutien au Gabon en matière d''infrastructures, renforçant ainsi leur coopération économique et stratégique. Gabon espère renforcer cette collaboration pour développer des secteurs clés tels que les transports, l''énergie, et l''eau potable.',
        'https://www.gabonreview.com/infrastructures-la-chine-confirme-son-soutien-au-gabon/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f0cb382-6d6b-4ec8-91d8-d9709a4a4714',
        'Gabon : Liberté de la presse, un frémissement encourageant, un chantier inachevé',
        'Le Gabon a connu une amélioration notable en matière de liberté de la presse, passant à la 41ème place dans le classement mondial, grâce aux efforts des autorités post-coup d''État. Cependant, des défis persistent, notamment les intimidations à l''égard des journalistes et la nécessité de réformes pour garantir une presse indépendante et libre.',
        'https://gabonmediatime.com/gabon-liberte-de-la-presse-un-fremissement-encourageant-un-chantier-inacheve/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aaf4a310-4bff-41b6-98d9-c69dfbdbec42',
        'Primature : Ndong Sima tire sa révérence, le président salue « un homme d’expérience et de devoir »',
        'Raymond Ndong Sima a présenté sa démission de Premier ministre de transition au président Brice Oligui Nguema conformément à la Constitution, ce dernier saluant son expérience et sa contribution cruciale durant cette période charnière post-coup d’État[5][4].',
        'https://gabonmediatime.com/primature-ndong-sima-tire-sa-reverence-le-president-salue-un-homme-dexperience-et-de-devoir/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4d9113c-2532-4f5d-bbc5-f08e630d66d7',
        'Gabon : Oligui Nguema acte la fin de la Primature avec la démission de Ndong Sima',
        'Le président gabonais Brice Clotaire Oligui Nguema a officiellement reçu la démission du Premier ministre Raymond Ndong Sima, marquant la fin de la primature conformément à la Constitution de 2024. Ce départ clôt la Transition initiée après le coup d’État d’août 2023, saluant l’action d’un homme décrit comme expérimenté et loyal.',
        'https://gabonmediatime.com/gabon-oligui-nguema-acte-la-fin-de-la-primature-avec-la-demission-de-ndong-sima/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1beadf37-17af-4c02-98db-8217a46014ed',
        'Publié le 05 / 05 / 2025',
        'Le président chinois Xi Jinping a adressé un message de félicitations à Brice Clotaire Oligui Nguema pour son élection à la présidence du Gabon, soulignant la traditionnelle amitié entre les deux pays et leur volonté de renforcer leur coopération stratégique. Xi Jinping a exprimé son engagement à travailler avec Nguema pour promouvoir un développement durable de leur partenariat, en s''appuyant sur les résultats du Sommet de Beijing du Forum sur la coopération sino-africaine.',
        'https://union.sonapresse.com/fr/xi-jinping-felicite-oligui-nguema',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ca26de2-7671-49ab-a1a7-7983cedc4a2a',
        'Publié le 05 / 05 / 2025',
        'Le président gabonais Brice Clotaire Oligui Nguema a été intronisé comme premier président de la Ve République gabonaise, prononçant son premier discours officiel lors de la cérémonie. L''événement a été marqué par des félicitations de plusieurs dirigeants africains, dont le président guinéen Mamadi Doumbouya, et a comporté une revue militaire pour clore la cérémonie.',
        'https://union.sonapresse.com/fr/investiture-du-president-oligui-nguema-des-symboles-et-du-beau-monde',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7cd9bac4-3221-42b2-be37-843cbcbcaa21',
        'Publié le 04 / 05 / 2025',
        'Raymond Ndong Sima, Premier ministre de la Transition au Gabon, a remis sa démission après l''investiture du président Brice Clotaire Oligui Nguema. Cette décision s''inscrit dans les réformes constitutionnelles récentes qui suppriment le poste de Premier ministre au profit de celui de vice-président.',
        'https://union.sonapresse.com/fr/gabon-raymond-ndong-sima-quitte-la-primature',
        'L''union',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d8c86bd-412f-4e45-b922-2575ca1f33c6',
        'Au Gabon, la pratique du Journalisme à l’épreuve du jugement Libreville : le Centre National d’examen du permis de conduire vand...',
        'Au Gabon, le journalisme fait face à des défis liés au manque de neutralité et aux dérives professionnelles, notamment l’ingérence de non-professionnels et les pressions politiques, ce qui soulève des questionnements sur le rôle des médias dans la démocratie[1]. Certains médias adoptent un positionnement partial, s’éloignant des principes éthiques et compromettant leur crédibilité auprès du public[1].',
        'https://mediapostegabon.com/au-gabon-la-pratique-du-journalisme-a-lepreuve-du-jugement/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2f538812-0532-45a9-8d0e-1ad2f91adfb8',
        'Séraphin Moundounga, élevé au rang de Vice-Président de la République',
        'Séraphin Moundounga, né le 29 février 1964 à Tchibanga dans la province de la Nyanga, a été nommé vice-président de la République du Gabon le 5 mai 2025. Il a occupé divers postes importants, notamment ministre de l''Éducation et de la Justice, et a récemment été président du Conseil économique, social et environnemental de la Transition.',
        'https://gabonactu.com/blog/2025/05/05/seraphin-moundounga-eleve-au-rang-de-vice-president-de-la-republique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3eb95ffa-c1d2-49e6-bd86-da1b649051d9',
        'Le Président gabonais et le Président de la BAD s’engagent pour le développement du pays',
        'Le président gabonais et le président de la Banque africaine de développement ont renforcé leur collaboration pour promouvoir des projets de développement durable et socio-économiques au Gabon, avec un accent sur l''innovation et la formation professionnelle. Leur engagement vise à accélérer la diversification économique et à améliorer les infrastructures éducatives en s''appuyant sur des partenariats stratégiques.  

*Note : Le contenu exact de l''article en question n''est pas accessible via les résultats fournis. Ce résumé général est basé sur les thématiques récurrentes identifiées dans les sources disponibles (priorités de la BAD[6][8], transition politique[5], gestion des ressources[7]).*',
        'https://gabonactu.com/blog/2025/05/05/le-president-gabonais-et-le-president-de-la-bad-sengagent-pour-le-developpement-du-pays/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba2b27eb-2709-4b50-bd4b-2f38f26b13be',
        'Gabon : Séraphin Moundounga nommé Vice-Président de la Republique',
        'Séraphin Moundounga, ancien président du Conseil économique, social et environnemental, a été nommé vice-président de la République gabonaise par décret présidentiel le 5 mai 2025, après avoir occupé des fonctions ministérielles et parlementaires de premier plan. Figure politique expérimentée, il avait démissionné en 2016 pour protester contre les résultats électoraux contestés avant de revenir au pays en 2023.',
        'https://gabonactu.com/blog/2025/05/05/gabon-seraphin-moundounga-nomme-vice-president-de-la-republique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b90ad16c-754e-40ed-a83e-867e3fe75d61',
        'Gabon : Séraphin Moundounga nommé Vice-président de la République',
        'Séraphin Moundounga a été nommé Vice-Président de la République du Gabon par décret présidentiel le 5 mai 2025. Avant cette nomination, il occupait le poste de président du Conseil économique, social et environnemental (CESE) et a joué un rôle important dans la politique gabonaise, notamment en tant que ministre de la Justice et membre du Parti démocratique gabonais.',
        'https://agpgabon.ga/2025/05/05/gabon-seraphin-moundounga-nomme-vice-president-de-la-republique/',
        'AGP',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d82d4ec-cba5-4c8a-8851-b03e4d79ab99',
        '26e session de l’Académie Internationale du Fiqh Islamique : vers un renforcement de l’ijtihad face aux défis contemporains',
        'La 26e session de l''Académie internationale du Fiqh islamique se tient à Doha pour renforcer l''ijtihad face aux défis contemporains, rassemblant des érudits musulmans du monde entier pour discuter de sujets actuels en fiqh. Cette session vise à promouvoir des solutions Sharia-compatibles aux problèmes économiques et médicaux modernes.',
        'https://agpgabon.ga/2025/05/05/26e-session-de-lacademie-internationale-du-fiqh-islamique-vers-un-renforcement-de-lijtihad-face-aux-defis-contemporains/',
        'AGP',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b1ba1aa7-2d51-4401-be14-4abc56324c90',
        'Gouvernement de la République : 31 membres, 3 ministres d’Etat, 10 femmes',
        'Le gouvernement gabonais compte désormais 31 membres, dont trois ministres d’État et dix femmes, selon la composition annoncée. Cette nouvelle équipe s’inscrit dans le cadre des récentes évolutions institutionnelles liées à l’entrée en vigueur de la nouvelle Constitution.',
        'https://gabonactu.com/blog/2025/05/05/gouvernement-de-la-republique-31-membres-3-ministres-detat-dont-10-femmes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6080e0b7-df87-4ebb-8328-082897768cfb',
        'Hugues Barro Chambrier, nommé Vice-Président du Gouvernement de la  » 5ème République «',
        'Hugues Alexandre Barro Chambrier, économiste et homme politique gabonais, a été nommé vice-président du gouvernement de la 5ᵉ République par le président Brice Clotaire Oligui Nguéma le 5 mai 2025, après avoir occupé le poste de ministre d''État chargé de la planification[1]. Né à Paris en 1958, ce militant historique du PDG (parti au pouvoir) a également représenté le Gabon au Parlement panafricain entre 2012 et 2016[1][7].',
        'https://gabonactu.com/blog/2025/05/05/hugues-barro-chambrier-nomme-vice-president-du-gouvernement-de-la-5eme-republique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '400110ef-f495-49e1-97bf-a781c22db62d',
        'Gabon : Oligui Nguema et les partis politiques en conclave le 7 mai pour fixer le cap des réformes',
        'Le président Brice Oligui Nguema a planifié un conclave avec les partis politiques le 7 mai pour définir les grandes lignes des réformes à mettre en œuvre au Gabon. Cette réunion vise à rassembler les forces politiques pour fixer le cap des réformes, notamment après la victoire électorale de Nguema et le retour vers une gouvernance démocratique.',
        'https://www.gabonreview.com/gabon-oligui-nguema-et-les-partis-politiques-en-conclave-le-7-mai-pour-fixer-le-cap-des-reformes/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f7640b8-32ab-4bf8-8088-513633508ea1',
        'Togo : Faure Gnassingbé cède la Présidence à Jean Lucien Savi deTové',
        'Faure Gnassingbé cède la présidence togolaise à Jean-Lucien Savi de Tové après une réforme constitutionnelle instaurant un régime parlementaire, tout en conservant le pouvoir exécutif en tant que président du Conseil des ministres. La transition institutionnelle, contestée par l''opposition, marque un tournant dans l''histoire politique du Togo en séparant les rôles présidentiels cérémoniels et opérationnels.',
        'https://agpgabon.ga/2025/05/05/togo-faure-gnassingbe-cede-la-presidence-a-jean-lucien-savi-detove/',
        'AGP',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d3aa438-5fda-491f-b899-2029e0b9d608',
        'Gabon : Alexandre Barro Chambrier nommé Vice-président du Gouvernement',
        'Alexandre Barro Chambrier a été nommé vice-président du gouvernement gabonais par le président Brice Clotaire Oligui Nguema lors d''un remaniement institutionnel, renforçant son rôle politique après son intégration récente à l''équipe dirigeante[4][5]. Cette nomination intervient dans un contexte de transition politique visant à préparer le pays à des élections futures tout en consolidant les alliances gouvernementales[6][7].',
        'https://agpgabon.ga/2025/05/05/gabon-alexandre-barro-chambrier-nomme-vice-president-du-gouvernement/',
        'AGP',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '441fb6e6-bc8f-424e-a4d3-83bf0ad02190',
        'Prix Marc-Vivien Foé 2025 : Diarra, Guessand et Hakimi sont les 3 finalistes',
        'Trois joueurs africains évoluant en Ligue 1 sont finalistes du Prix Marc-Vivien Foé 2025 : le Sénégalais Habib Diarra (Strasbourg), l''Ivoirien Evann Guessand (Nice) et le Marocain Achraf Hakimi (PSG)[7]. Le lauréat sera désigné par un jury de journalistes spécialisés le 12 mai 2025[5][7].',
        'https://www.france24.com/fr/sports/20250505-prix-marc-vivien-fo%C3%A9-2025-diarra-guessand-et-hakimi-sont-les-3-finalistes?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0723364-9d9f-44b0-9643-43730a667561',
        'Politique. Oligui Nguema investi président au Gabon : sept ans pour sortir du système Bongo',
        'Brice Oligui Nguema a été officiellement investi président du Gabon après sa victoire électorale, marquant la fin de 19 mois de transition suite au coup d’État de 2023 qui a mis fin à 56 ans de pouvoir de la famille Bongo. Il promet de réformer le pays et de sortir du système politique hérité de ses prédécesseurs.',
        'https://www.courrierinternational.com/article/oligui-nguema-investi-president-au-gabon-sept-ans-pour-sortir-du-systeme-bongo_230592?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2311bf35-dc79-4b13-a7d5-7448dc75539e',
        'Gabon : Les 9 femmes du 1er gouvernement de la 5e République',
        'Le premier gouvernement de la 5e République du Gabon met en avant neuf femmes ministres, occupant des postes clés tels que l''Éducation, la Défense, l''Économie bleue, et les Affaires sociales. Ces nominations marquent une représentation significative des femmes dans le gouvernement gabonais.',
        'https://directinfosgabon.com/gabon-les-9-femmes-du-1er-gouvernement-de-la-5e-republique/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bffa045b-ba40-465c-adca-094cf424d8ec',
        'Nouveau gouvernement du 5 mai 2025 : Les 9 entrants',
        'Le nouveau gouvernement gabonais du 5 mai 2025 compte onze membres sortants, avec des changements notables dans les postes clés comme le Premier ministre et plusieurs ministères stratégiques. Les nominations reflètent une volonté de renouvellement après la transition politique engagée depuis 2023.',
        'https://directinfosgabon.com/nouveau-gouvernement-du-5-mai-2025-les-9-entrants/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6b8f21f4-f4ae-4bef-b14d-c198980cdf08',
        'Nouveau gouvernement du 5 mai 2025 : Les 11 sortants',
        'Le nouveau gouvernement gabonais formé le 5 mai 2025 comprend plusieurs sorties notables, parmi lesquelles le Premier ministre Raymond Ndong Sima et le Ministre d''État des Travaux publics Général Flavien Nzenge-Nzoundou. Ces changements s''inscrivent dans le cadre de la refonte institutionnelle du pays.',
        'https://directinfosgabon.com/nouveau-gouvernement-du-5-mai-2025-les-10-sortants/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-05T00:00:00.000Z',
        '2025-09-15T23:06:12.430Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

