-- Batch 7 - Section 18/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '05a4e1b9-755c-4af5-962c-94bc0a637ab0',
        'Owendo face à ses défis : l''Alliance Indépendante pour le Renouveau (AIR) propose une alternative crédible',
        'Owendo fait face à des défis majeurs liés à l’insalubrité, aux infrastructures dégradées et au manque de politiques efficaces pour exploiter ses potentialités économiques croissantes.',
        'https://www.gabonews.com/fr/actus/politique/article/owendo-face-a-ses-defis-l-alliance-independante',
        'Gabonews',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b253c1b-7dd3-4879-ba74-c33780f0a104',
        'Elections locales : qui est Louis Joseph Boussougou ?',
        'Des candidats émergent dans différentes régions du Gabon, dont Louis Joseph Boussougou pour l''Union démocratiques des bâtisseurs, dans le contexte des prochaines élections législatives et locales qui suscitent l''espoir d''un changement politique.',
        'https://www.gabonews.com/fr/actus/politique/article/elections-locales-qui-est-louis-joseph-boussougou',
        'Gabonews',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95f76a38-11da-4751-9bcb-c0fe78482432',
        '"Il est essentiel de témoigner régulièrement notre affection à celles et ceux qui meublent notre existence, sans oublier de les porter dans nos prières"',
        'Une personne du district de Nzénzélé a exprimé sa compassion suite à un grave accident impliquant Angélique Ngoma, une députée et responsable politique gabonaise.',
        'https://www.gabonews.com/fr/actus/faits-divers-145/article/il-est-essentiel-de-temoigner-regulierement-notre',
        'Gabonews',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09262ffd-72de-472d-9d94-a7361d1f1dd9',
        'Gabon/Rentrée 2025 : l’État débloque des moyens et corrige les erreurs d’orientation scolaire',
        'Le gouvernement gabonais a pris de nouvelles mesures pour améliorer le système éducatif, notamment en débloquant des ressources et en corrigeant les erreurs d’orientation scolaire des élèves de sixième.',
        'https://agpgabon.ga/gabon-rentree-2025-letat-debloque-des-moyens-et-corrige-les-erreurs-dorientation-scolaire/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'beef7a8d-35d6-4da1-98d5-88521c0c3d0e',
        'La note A-/Stable d’Afreximbank confirmée par l’agence japonaise JCR',
        'La note de crédit A- avec une perspective stable attribuée à la Banque africaine d’import-export (Afreximbank) a été confirmée par l''agence japonaise JCR, qui souligne la solidité de sa gestion, sa rentabilité et son rôle dans le financement du commerce en Afrique et dans les Caraïbes.',
        'https://agpgabon.ga/la-note-a-stable-dafreximbank-confirmee-par-lagence-japonaise-jcr/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '308890f1-e30d-4d6c-8840-6d18edb1ca70',
        '« Le Gabon ne se raconte pas uniquement dans les livres, il se découvre » (Zita Oligui Nguema)',
        'La Première Dame Zita Oligui Nguema souligne que le Gabon a beaucoup à offrir et peut se découvrir à travers ses paysages, sa culture et ses habitants, au-delà des livres.',
        'https://gabonactu.com/blog/2025/08/28/le-gabon-ne-se-raconte-pas-uniquement-dans-les-livres-il-se-decouvre-zita-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c881decb-290e-4417-a10d-deb758e6c381',
        'Port-Gentil : 69 diplômés de l’IFPP sur le marché de l’emploi',
        '69 diplômés de l’IFPP de Port-Gentil ont été présentés sur le marché de l’emploi lors d’une cérémonie officielle, marquant la fin de leur formation et leur entrée dans le monde professionnel.',
        'https://gabonactu.com/blog/2025/08/28/port-gentil-69-diplomes-de-lifpp-sur-le-marche-de-lemploi/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'decc559f-310a-4cbe-90db-0803346b41f6',
        'Route Ebè – Ovan – Makokou : La côte d’alerte !',
        'La dégradation avancée de la route reliant Ebè, Ovan et Makokou en raison de l’arrivée prochaine de la saison des pluies soulève des préoccupations quant à la sécurité et à la circulation dans la région.',
        'https://gabonactu.com/blog/2025/08/28/route-ebe-ovan-makokou-la-cote-dalerte/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fcc7f97-b33d-4049-8d2f-e10f4a16fab2',
        'Législatives à venir : Un marché de dupes ?',
        'L''article critique la manière dont certains candidats se retirent des élections, soulignant que cela aurait dû être basé sur des décisions claires et stratégiques pour éviter de tromper les électeurs.',
        'https://www.gabonreview.com/legislatives-a-venir-un-marche-de-dupes/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9f7eda5-ca54-499c-9b69-0aea3a5d3ff1',
        '[Paru sur le Gabon] Bilie-By-Nzé étrille un gouvernement «sans cap et déjà à bout de souffle»',
        'L’ancien Premier ministre critique sévèrement le gouvernement gabonais actuel, dénonçant une gouvernance inefficace et une crise politique grave liée à des enjeux de pouvoir et de transparence.',
        'https://www.gabonreview.com/paru-sur-le-gabon-bilie-by-nze-etrille-un-gouvernement-sans-cap-et-deja-a-bout-de-souffle/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b29a2200-9f07-4dc7-961b-073830843733',
        'Gabon : clarifications du ministère de l’Économie sur le prélèvement des taxes',
        'Le gouvernement gabonais clarifie que la taxe de 3 % prélevée sur les transactions financières est une contribution volontaire pour soutenir le développement, et non une taxe obligatoire ou une nouvelle fiscalité.',
        'https://gabonmediatime.com/gabon-clarifications-du-ministere-de-leconomie-sur-le-prelevement-des-taxes/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45789c4b-6b52-448c-9bc8-ac3b1c6d03dd',
        'Gabon – Liban : une diplomatie économique ancrée dans des secteurs stratégiques',
        'La diplomatie économique gabonaise avec le Liban est axée sur le développement de secteurs stratégiques tels que l''agriculture, la santé, et l''industrie, afin de renforcer les échanges commerciaux et les investissements bilatéraux.',
        'https://gabonmediatime.com/gabon-liban-une-diplomatie-economique-ancree-dans-des-secteurs-strategiques/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1b56b29-ca87-4086-9e2d-53d55230c1af',
        'Gabon : SOS tabagisme plaide pour l’application stricte de la loi anti-tabac !',
        'Gabon insiste sur la nécessité de respecter strictement la loi anti-tabac pour réduire les risques liés au tabagisme et protéger la santé publique.',
        'https://gabonmediatime.com/gabon-sos-tabagisme-plaide-pour-lapplication-stricte-de-la-loi-anti-tabac/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd89117bb-5c15-474d-ae3d-6c2eba895242',
        'La Société Équatoriale des Mines (SEM) installe officiellement son premier bureau des délégués du personnel',
        'La Société Equatoriale des Mines (SEM) a officiellement installé son premier bureau des délégués du personnel, permettant une meilleure représentation et communication avec ses employés.',
        'https://kongossanews.info/la-societe-equatoriale-des-mines-sem-installe-officiellement-son-premier-bureau-des-delegues-du-personnel/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c1fc50f5-d539-43eb-ad75-96a75817e856',
        'Accident sur l’axe Mouila–Fougamou : la réactivité humaniste de Brice Clotaire Oligui Nguema',
        'Lors d’un accident sur l’axe Mouila-Fougamou, Brice Clotaire Oligui Nguema a fait preuve d’une grande humanité en réagissant rapidement pour venir en aide aux victimes.',
        'https://kongossanews.info/accident-sur-laxe-mouila-fougamou-la-reactivite-humaniste-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '159bc503-c4e3-4124-a4e5-cbffa053232c',
        'Football/Éliminatoires Coupe du monde 2026 : Emerse Faé se méfie du Gabon',
        'Le sélectionneur de la Côte d’Ivoire souligne que le Gabon, jouant à domicile, sera une équipe difficile à battre lors des éliminatoires pour la Coupe du Monde 2026, en raison de sa rapidité offensive et de sa détermination à se qualifier.',
        'https://agpgabon.ga/football-eliminatoires-coupe-du-monde-2026-emerse-fae-se-mefie-du-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '87a8e404-de8a-4a41-9542-206026ebdd23',
        'Tchibanga : Bitome conseille aux femmes de ne pas céder au mensonge des « faymans » venus de Libreville',
        'Bitome, un influenceur gabonais, avertit les femmes contre les fausses rumeurs provenant de Libreville, notamment en matière de santé sexuelle et de prévention du VIH.',
        'https://gabonactu.com/blog/2025/08/28/tchibanga-bitome-conseille-aux-femmes-de-ne-pas-ceder-au-mensonge-des-faymans-venus-de-libreville/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e9a3fe78-031d-4c01-be7a-d2d6f35f4923',
        'Un humain retrouvé mort par suicide ou simulation de pendaison à la Cité des ailes',
        'Une personne a été retrouvée morte par pendaison à la Cité des ailes, mais il reste incertain si c’est un suicide ou une mise en scène.',
        'https://gabonactu.com/blog/2025/08/28/un-humain-retrouve-mort-par-suicide-ou-simulation-de-pendaison-a-la-cite-des-ailes/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a57e9ca-9f2c-4ada-af58-c5c10ba744e2',
        'Gabon : clarifications du ministère de l’Économie sur le prélèvement des taxes',
        'Le ministère de l’Économie gabonais précise que les prélèvements fiscaux effectués sur les acteurs économiques respectent les réglementations en vigueur, afin d’éviter toute confusion ou malentendu.',
        'https://gabonmediatime.com/gabon-clarifications-du-ministere-de-leconomie-sur-le-prelevement-des-taxes/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '320a1f5f-4645-49a4-b219-dec3685b35f9',
        'Gabon – Liban : une diplomatie économique ancrée dans des secteurs stratégiques',
        'Le Gabon et le Liban renforcent leur coopération économique en se concentrant sur des secteurs stratégiques tels que l''énergie, l''agriculture et la construction, afin de stimuler le développement et les échanges bilatéraux.',
        'https://gabonmediatime.com/gabon-liban-une-diplomatie-economique-ancree-dans-des-secteurs-strategiques/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc1a9e09-8760-4091-abc1-7326ec9f83e7',
        'Gabon : SOS tabagisme plaide pour l’application stricte de la loi anti-tabac !',
        'L''association SOS Tabagisme demande une application stricte de la loi anti-tabac au Gabon pour réduire la consommation de cigarettes.',
        'https://gabonmediatime.com/gabon-sos-tabagisme-plaide-pour-lapplication-stricte-de-la-loi-anti-tabac/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a26a78db-9a98-4c50-a776-828d9cd5d1b6',
        'La Société Équatoriale des Mines (SEM) installe officiellement son premier bureau des délégués du personnel',
        'La Société Equatoriale des Mines (SEM) a officiellement installé son premier bureau des délégués du personnel, marquant une étape importante pour la représentation des employés au sein de l''entreprise.',
        'https://kongossanews.info/la-societe-equatoriale-des-mines-sem-installe-officiellement-son-premier-bureau-des-delegues-du-personnel/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3bf8ea6-44ca-4e19-aab1-aaae900581c0',
        'Accident sur l’axe Mouila–Fougamou : la réactivité humaniste de Brice Clotaire Oligui Nguema',
        'Brice Clotaire Oligui Nguema montre une réaction humaine et solidaire face à un accident sur l''axe Mouila-Fougamou, illustrant son engagement pour la sécurité et le bien-être des populations.',
        'https://kongossanews.info/accident-sur-laxe-mouila-fougamou-la-reactivite-humaniste-de-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b1eff72-835e-4f3e-b32f-1b79ac0d3fba',
        'Gabon/Accident de circulation : un mort au Charbonnage',
        'Un accident de la route à Libreville a causé la mort d’un homme nigérian, Oluikpe Chima, après qu’un camion a sorti de la route et percuté un arbre, le conducteur ayant tenté d’éviter une petite voiture.',
        'https://agpgabon.ga/gabon-accident-de-circulation-un-mort-au-charbonnage/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e9947729-aa1c-44de-ab0b-8a3d95bb37c9',
        'Gabon/Mines : vers une stratégie de transformation locale du manganèse et du fer',
        'Le gouvernement gabonais travaille à mettre en place une stratégie pour transformer localement les minerais, notamment le manganèse et le fer, afin de privilégier la production d’alliages plutôt que l’exportation brute, avec une interdiction prévue en 2029.',
        'https://agpgabon.ga/gabon-mines-vers-une-strategie-de-transformation-locale-du-manganese-et-du-fer/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0232ed5-b9b3-43cf-8467-cbd4b4fa6bf3',
        'L’état de santé d’Angélique Ngoma est stable après son accident de circulation (PDG)',
        'L’état de santé d’Angélique Ngoma, secrétaire générale du Parti démocratique gabonais, est stable après un accident de circulation.',
        'https://gabonactu.com/blog/2025/08/28/letat-de-sante-dangelique-ngoma-est-stable-pdg/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f81dad13-9128-486d-9fef-4ebd19977d61',
        'Gabon : un corps retrouvé pendu à la Cité des Ailes',
        'Un jeune homme a été trouvé pendu dans la Cité des Ailes, au camp de l’armée de l’air à Libreville, et une enquête a été ouverte pour déterminer les circonstances de sa mort.',
        'https://agpgabon.ga/gabon-un-corps-retrouve-pendu-a-la-cite-des-ailes/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd97e09cc-42ec-463b-8978-a08d58959806',
        'Crépin, mon frère, avec qui tu laisses Africa N° ? par Roger Mebang Menze',
        'L''article appelle à la reprise et à la renaissance du média Africa N°1, tout en évoquant la nécessité de revitaliser le métier de journaliste dans un contexte difficile.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/crepin-mon-frere-avec-qui-tu-laisses-africa-no',
        'Gabonews',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3372fff-0e2b-4afd-88ce-3a3fe114250b',
        'Volleyball/Jet Volley Camp : un pari gagné pour la Ligue de l’Estuaire',
        'La Ligue de volleyball de l’Estuaire a organisé avec succès une session du Jet Camp au stade de Nzeng-Ayong, mobilisant une cinquantaine d’enfants, dans le but de favoriser la découverte du volley-ball et de former de futurs champions.',
        'https://agpgabon.ga/volleyball-jet-volley-camp-un-pari-gagne-pour-la-ligue-de-lestuaire/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c04758e-b2c7-4e0e-9cd7-e7f8342b3dd5',
        'Haut- Ogooué/Football : Franceville se mobilise autour des Panthères du Gabon',
        'Les responsables de Franceville se sont réunis pour mieux préparer le match entre le Gabon et la Côte d’Ivoire du 9 septembre, en mobilisant la communauté locale autour du football national.',
        'https://agpgabon.ga/haut-ogooue-football-franceville-se-mobilise-autour-des-pantheres-du-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89f423a4-f89e-49df-bd04-1470ccb75c14',
        'Nigeria: un déraillement de train fait un mort et plusieurs blessés au nord du pays',
        'Un déraillement d’un train au nord du Nigeria a causé la mort d’une personne et blessé plusieurs autres, entraînant la suspension des services sur la ligne et l’ouverture d’une enquête.',
        'https://agpgabon.ga/nigeria-un-deraillement-de-train-fait-un-mort-et-plusieurs-blesses-au-nord-du-pays/',
        'AGP',
        'Business Intelligence',
        '2025-08-28T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6ec9a63-efee-49da-8411-f8ea303c3f15',
        'Gabon : la liste électorale désormais consultable en ligne',
        'La liste électorale du Gabon est désormais accessible en ligne via le site www.consultation.listelectorale.ga, avec un numéro d''identification unique, permettant aux citoyens de vérifier leur inscription avant les élections de 2023.',
        'https://gabonactu.com/blog/2025/08/28/gabon-la-liste-electorale-desormais-consultable-en-ligne/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b30b80a-ff92-4317-b9f4-db39f88297d2',
        'Élections couplées : Joseph Lapensée Essingone justifie l’absence de l’EPC',
        'Le parti «L’Éveil de la Pensée Citoyenne» ne participera pas aux élections législatives et locales, critiquant la mauvaise organisation du processus électoral par les mêmes responsables que lors de l’élection présidentielle.',
        'https://agpgabon.ga/elections-couplees-joseph-lapensee-essingone-justifie-labsence-de-lepc/',
        'AGP',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4d719873-fd43-42b0-8882-fd9a030e79e0',
        'SIDA : distribution massive des préservatifs à Tchibanga',
        'Une campagne de distribution massive de préservatifs a été organisée à Tchibanga pour lutter contre le VIH et sensibiliser à la prévention du SIDA dans la région de la Nyanga.',
        'https://gabonactu.com/blog/2025/08/29/sida-distribution-massive-des-preservatifs-a-tchibanga/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '20ab2d4b-1854-4d86-8adc-0135324425df',
        'Financement du projet Banio : Washington donne son feu vert',
        'Washington a approuvé un financement pour le projet Banio, marquant une étape importante dans le développement de cette initiative en Afrique.',
        'https://directinfosgabon.com/financement-du-projet-banio-washington-donne-son-feu-vert/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62002e38-fbfb-44a9-972f-bf6989c6481f',
        'Potasse de Banio : Le Gabon bientôt premier fournisseur du marché africain',
        'Le projet minier de Banio au Gabon pourrait bientôt permettre au pays de devenir le principal fournisseur de potasse en Afrique, réduisant ainsi sa dépendance aux importations et renforçant la souveraineté agricole régionale.',
        'https://directinfosgabon.com/potasse-de-banio-le-gabon-bientot-premier-fournisseur-du-marche-africain/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b99c4e7-5fa4-4efc-8631-d0e00af2cc55',
        'CEMAC : La BEAC injecte 600 milliards de FCFA pour soutenir les banques',
        'La BEAC a mis en place pour la première fois une injection de 600 milliards de FCFA dans le but de soutenir les banques commerciales de la CEMAC face aux besoins croissants de financement.',
        'https://directinfosgabon.com/cemac-la-beac-injecte-600-milliards-de-fcfa-pour-soutenir-les-banques/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3cdd10b8-b6a8-4f61-ada1-d87efcb0bcb3',
        'Gabon -Chine : 26 journalistes des médias publics et privés gabonais en formation à Pékin',
        'Un séminaire de formation pour les journalistes gabonais, publics et privés, s''est déroulé à Pékin, renforçant la coopération bilatérale entre la Chine et le Gabon dans le domaine des médias.',
        'https://www.gabonews.com/fr/actus/cooperation/article/gabon-chine-26-journalistes-des-medias-publics-et',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0453b727-eee6-4436-94c7-5093cf147b33',
        'Le mythique Lac Bleu visité par le couple présidentiel',
        'Le président et la première dame ont visité le Lac Bleu de Mouila dans le cadre d''une campagne pour mettre en valeur les richesses naturelles et culturelles du pays.',
        'https://www.gabonews.com/fr/actus/societe/article/le-mythique-lac-bleu-visite-par-le-couple',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9411c0de-0eed-4292-94ee-413bcc6215f3',
        'Gabon : Les banques ont accordé 2290 milliards de FCFA de crédits en 2024',
        'Les banques commerciales du Gabon ont accordé environ 2291 milliards de FCFA de crédits en 2024, principalement pour financer les entreprises privées et soutenir de nombreux projets économiques.',
        'https://directinfosgabon.com/gabon-les-banques-ont-accorde-2290-milliards-de-fcfa-de-credits-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab1fb39f-692e-434a-9dc7-09ac93646a90',
        'À Tchibanga, OLIGUI NGUEMA communie avec les Nynois',
        'Le Président Brice Clotaire Oligui Nguema s''est rendu à Tchibanga pour célébrer la première édition tournante du Coup de la Libération, en rencontrant ses compatriotes à cette occasion.',
        'https://vxp241.com/2025/08/29/a-tchibanga-oligui-nguema-communie-avec-les-nynois/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9232ee34-6a3b-41f0-9d64-387f7eed8964',
        'Allégations sur les pensions des conjoints survivants : vers une plainte de la CNSS contre Aminata Ondo ?',
        'La CNSS conteste les propos de la présidente de l’ASCORIM sur les pensions des conjoints survivants, envisageant une plainte contre elle pour ces accusations.',
        'https://www.gabonreview.com/allegations-sur-les-pensions-des-conjoints-survivants-vers-une-plainte-de-la-cnss-contre-aminata-ondo/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0035ba45-ed44-48d0-8db6-c49b7dd6def6',
        'Makouke/élections législatives : les pronostics donnent Jérôme Mikala, candidat du RPM favori devant l''UDB et le PDG',
        'Les électeurs du 4e siège du département de l''Ogooué et des Lacs, dans le district de Makouké, ont exprimé leur soutien au parti au pouvoir, l''UDB, en rejetant principalement certains individus qu''ils accusent de chercher uniquement leur profit personnel sous l''égide du PDG.',
        'https://www.gabonews.com/fr/actus/politique/article/makouke-elections-legislatives-les-pronostics',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad2d0f4f-5d87-4c36-a5e6-d4c717fad531',
        'Le gouvernement de Brice Clotaire Oligui Nguema critiqué par Alain-Claude Bilie-By-Nze',
        'Un opposant critique le gouvernement gabonais pour sa mauvaise gestion et l''absence de direction claire à l''approche des élections législatives et locales.',
        'https://www.gabonews.com/fr/actus/politique/article/le-gouvernement-de-brice-clotaire-oligui-nguema',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '32070049-cb91-4200-91c4-0bb0a2784336',
        'Le Chef de l''État séjourne dans la province de la Nyanga',
        'Le président Brice Clotaire Oligui Nguema s’est rendu à Tchibanga pour célébrer la première édition tournante du Coup de la Libération le 30 août, et a rencontré les habitants de la province de la Nyanga pour échanger avec eux.',
        'https://www.gabonews.com/fr/actus/politique/article/le-chef-de-l-etat-sejourne-dans-la-province-de-la',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aab96278-5f74-4129-a96f-f87647f34854',
        'Gabon/Secteur pétrolier : le Gabon et APPO renforcent leur partenariat stratégique',
        'Le Gabon renforce sa coopération avec l’Organisation des producteurs de pétrole africains (APPO), notamment en présentant la Banque Africaine de l’Énergie (BAE), créée en 2024 pour financer des projets pétroliers et gaziers sur le continent.',
        'https://agpgabon.ga/gabon-secteur-petrolier-le-gabon-et-appo-renforcent-leur-partenariat-strategique/',
        'AGP',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89681f3f-5073-4f05-bdb0-e50ff8590411',
        'L''École nationale de développement rural réhabilitée : Louise Pierrette Mvono, ministre de la Planification et de la Prospective s''en félicite',
        'La ministre Louise Pierrette Mvono a visité et exprimé sa satisfaction après la réhabilitation de l''École nationale de développement rural d''Oyem, dont les bâtiments refaits sont prêts à accueillir des étudiants.',
        'https://www.gabonews.com/fr/actus/enseignement-superieur/article/l-ecole-nationale-de-developpement-rural',
        'Gabonews',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4071d9c-eeed-4a4b-ad3d-d6a5da2a0baf',
        'Football/Éliminatoires Mondial 2026 : Didier Ibrahim Ndong dans la liste du Gabon',
        'Didier Ibrahim Ndong a été sélectionné pour jouer avec l''équipe du Gabon lors des matchs contre les Seychelles et la Côte d’Ivoire en éliminatoires de la Coupe du Monde 2026.',
        'https://agpgabon.ga/football-eliminatoires-mondial-2026-didier-ibrahim-ndong-dans-la-liste-du-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2dd572b-3776-4a8b-a0be-f360c92b2a95',
        'Gabon/Parafiscalité : les opérateurs éconministèrenvités à s’opposer à des taxes illégales',
        'Les opérateurs économiques sont invités à refuser de payer des taxes illégales non inscrites dans la loi de finances, car ces prélèvements ne sont pas reversés au Trésor public et relèvent de la parafiscalité.',
        'https://agpgabon.ga/gabon-parafiscalite-les-operateurs-econministerenvites-a-sopposer-a-des-taxes-illegales/',
        'AGP',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28589ebc-aa91-4456-a392-085473e0666a',
        'Pétrole et Gaz : renforcement de la coopération Gabon–APPO autour de la Banque africaine de l’énergie',
        'Le secrétaire général de l’APPO a rencontré le ministère gabonais du Pétrole pour renforcer la coopération entre le Gabon, l’APPO et la Banque africaine de l’énergie dans le domaine du pétrole et du gaz.',
        'https://www.gabonreview.com/petrole-et-gaz-renforcement-de-la-cooperation-gabon-appo-autour-de-la-banque-africaine-de-lenergie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-29T00:00:00.000Z',
        '2025-09-15T23:06:12.500Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

