-- Batch 7 - Section 3/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '20749c59-0224-470b-bf14-fd86e13a4046',
        'Publié le 09 / 08 / 2025',
        'L''auteur explique avoir accepté de se désister pour convaincre la direction du parti et continuer à soutenir ses engagements.',
        'https://union.sonapresse.com/fr/pour-convaincre-la-direction-du-parti-daccepter-mon-desistement-jai-pris-lengagement-daccompagner',
        'L''union',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bd2c6b36-ecda-4262-89d5-b4b19e150b3f',
        'Publié le 09 / 08 / 2025',
        'Le président Ndende Oligui Nguema a inauguré un nouveau complexe administratif à Ndéndé, destiné à améliorer la gestion publique et renforcer les services aux citoyens.',
        'https://union.sonapresse.com/fr/ndende-oligui-nguema-inaugure-le-complexe-administratif-pierre-mamboundou-mamboundou',
        'L''union',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '633023b8-a40c-4371-9a36-b9fd9dee274f',
        'SEEG : 200 nouveaux compteurs pour la ville de Booué',
        'Une opération a été lancée pour installer 200 nouveaux compteurs d''eau dans la ville de Booué, afin d''améliorer l''accès et la gestion de l''eau pour les habitants.',
        'https://directinfosgabon.com/seeg-200-nouveaux-compteurs-pour-la-ville-de-booue/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a99ec47-8273-40ad-ac33-280bab9e51aa',
        'Journée Nationale du Drapeau : Oligui Nguema place la jeunesse au cœur du patriotisme',
        'La Journée nationale du Drapeau met en avant l’importance de l’unité et du patriotisme, en soulevant le rôle central des jeunes dans la construction de l’avenir du pays.',
        'https://gabonmediatime.com/journee-nationale-du-drapeau-oligui-nguema-place-la-jeunesse-au-coeur-du-patriotisme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '897ceff9-56a2-4ba9-bdda-1e07853e6de0',
        'Gabon : Infrastructures, TGCC propose son expertise pour accompagner la vision d’Oligui Nguema',
        'TCGC propose ses compétences en infrastructures pour soutenir la vision stratégique du président Ali Bongo, visant le développement durable et la modernisation du pays.',
        'https://gabonmediatime.com/gabon-infrastructures-tgcc-propose-son-expertise-pour-accompagner-la-vision-doligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a41d8c68-6b68-4b04-b2da-09005ac9f1b1',
        'Gabon : Zita Oligui Nguema exprime son indignation après le meurtre de la petite Esther',
        'Zita Oligui Nguema exprime sa profonde tristesse et son indignation suite au meurtre de la petite Esther, dénonçant cet acte odieux et appelant à la justice.',
        'https://gabonmediatime.com/gabon-zita-oligui-nguema-exprime-son-indignation-apres-le-meurtre-de-la-petite-esther/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '83a6d525-453d-4584-80bb-35578388bda8',
        'Libreville : la Journée Nationale du Drapeau célébrée sous le signe de la jeunesse et du patriotisme',
        'La célébration de la Journée nationale du drapeau à Libreville a mis en avant l''importance de la jeunesse et du patriotisme à travers diverses activités et cérémonies.',
        'https://kongossanews.info/libreville-la-journee-nationale-du-drapeau-celebree-sous-le-signe-de-la-jeunesse-et-du-patriotisme/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e04f18b-9c80-4fca-aadb-05ed716ba6bd',
        'Ngounié : le Président Oligui Nguema inaugure une série d’infrastructures majeures',
        'Le président Oligui Nguema a inauguré plusieurs infrastructures majeures à Ngounié, visant à améliorer les services et le développement dans la région.',
        'https://kongossanews.info/ngounie-le-president-oligui-nguema-inaugure-une-serie-dinfrastructures-majeures/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b2ee298-b85c-4597-9f6d-91a8a703c596',
        'Publié le 09 / 08 / 2025',
        'L''auteur explique avoir pris l''engagement d''accompagner pour convaincre la direction du parti d''accepter son désistement.',
        'https://union.sonapresse.com/fr/pour-convaincre-la-direction-du-parti-daccepter-mon-desistement-jai-pris-lengagement-daccompagner',
        'L''union',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a818986-cf4e-4f91-959e-a34702adba1d',
        'Publié le 09 / 08 / 2025',
        'Le président Ndende Oligui Nguema a inauguré le complexe administratif Pierre Mamboundou, symbolisant le développement et la stabilité dans la région.',
        'https://union.sonapresse.com/fr/ndende-oligui-nguema-inaugure-le-complexe-administratif-pierre-mamboundou-mamboundou',
        'L''union',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '079f223f-8a86-45a4-a1f1-511083464932',
        'Woleu-Ntem : l’antenne provinciale de l’AGP dotée de nouveaux équipements de bureau',
        'L’antenne provinciale du Woleu-Ntem a reçu du matériel informatique et de bureau offert par l’Ambassade de Chine, afin d’améliorer ses capacités de travail.',
        'https://agpgabon.ga/woleu-ntem-lantenne-provinciale-de-lagp-dotee-de-nouveaux-equipements-de-bureau/',
        'AGP',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd276dbb5-0e8f-4c03-8bc2-13510a0b3f3c',
        'Gabon : le gouvernement en séminaire d’évaluation de 48 heures',
        'Le gouvernement gabonais organise un séminaire de 48 heures pour faire le bilan des 100 premiers jours d’action, poser des priorités et accélérer la mise en œuvre de son plan pour 2025-2032.',
        'https://agpgabon.ga/gabon-le-gouvernement-en-seminaire-devaluation-de-48-heures/',
        'AGP',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f7ebe7f-d843-4d7a-bdbd-b967eed06c64',
        'Moyen-Ogooué/6ᵉ édition de la course “Ma Migovéenne” : forte mobilisation à Bifoun',
        'La 6ᵉ édition de la course “Ma Migovéenne” organisée à Bifoun a réuni des femmes de tous âges, Participant à différentes catégories sur des distances allant jusqu’à plus de trois kilomètres, avec des récompenses pour les meilleures.',
        'https://agpgabon.ga/moyen-ogooue-6%e1%b5%89-edition-de-la-course-ma-migoveenne-forte-mobilisation-a-bifoun/',
        'AGP',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '925e3745-6360-4301-ae2a-81c84f8500ab',
        'Saison sèche : Quelle fraîcheur cette année !',
        'Cette année, la saison sèche à Libreville et au Gabon est marquée par une fraîcheur inhabituelle, avec des températures plus basses que d''habitude.',
        'https://gabonactu.com/blog/2025/08/10/saison-seche-quelle-fraicheur-cette-annee/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '595e4db6-0686-47dc-bb9b-a71fde76b96e',
        'Booué : La lumière partout',
        'Le gouvernement met en œuvre un programme pilote pour installer l''électricité dans les zones rurales de la province de l''Ogooué-Ivindo, afin d''améliorer l''accès à l''énergie pour toutes les communautés.',
        'https://gabonactu.com/blog/2025/08/10/boue-la-lumiere-partout/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a13b7fe-07ba-4eb0-862c-5b747a1d91fc',
        'Vyn Lorenzo : portrait d’un entrepreneur et artiste au parcours atypique',
        'Vyn Lorenzo est un entrepreneur et artiste dont le parcours atypique mêle créativité artistique et réussite commerciale.',
        'https://gabonactu.com/blog/2025/08/10/vyn-lorenzo-portrait-dun-entrepreneur-et-artiste-au-parcours-atypique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4339aad-0682-42c7-8a6a-e6c19466b0e5',
        'Législatives et locales 2025 : un délai de grâce de 48h pour compléter les dossiers',
        'Une période supplémentaire de 48 heures est accordée pour que les partis politiques et les candidats complètent leurs dossiers en vue des élections législatives et locales de 2025.',
        'https://gabonactu.com/blog/2025/08/10/legislatives-et-locales-2025-un-delai-de-grace-de-48h-pour-completer-les-dossiers/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '607617d9-48d8-4900-9a85-90bdb06cfaaf',
        'Des potences, unité de production d’oxygène, groupe électrogène pour le CHR de Port-Gentil',
        'Le Centre hospitalier régional de Port-Gentil a renforcé ses équipements avec l''ajout d''une unité de production d''oxygène, de potences et d’un groupe électrogène pour améliorer la qualité des soins aux patients.',
        'https://gabonactu.com/blog/2025/08/10/amelioration-de-la-sante-des-patients-des-potences-unite-de-production-doxygene-groupe-electrogene-pour-le-chr-de-port-gentil/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '252b6b9e-5c59-499a-804d-4efde3edbb69',
        'Gabon/Élections législatives et locales : 48 heures supplémentaires pour compléter les dossiers incomplets',
        'Le gouvernement gabonais a accordé aux candidats aux élections législatives et locales de septembre 2025 un délai supplémentaire de 48 heures, les 11 et 12 août, pour finaliser leurs dossiers incomplets.',
        'https://agpgabon.ga/gabon-elections-legislatives-et-locales-48-heures-supplementaires-pour-completer-les-dossiers-incomplets/',
        'AGP',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09bcc4e3-d324-4280-a463-dc1b75203d9b',
        'Gabon: condamné pour avoir résisté, pendant que ses bourreaux libres se pavanent en Europe',
        'Certaines personnes fuient leurs responsabilités en se présentant comme victimes, comme le font les inculpés du clan BONGO, plutôt que de les assumer ou de les nier.',
        'https://vxp241.com/2025/08/10/condamne-pour-avoir-resiste-pendant-que-ses-bourreaux-libres-se-pavanent-en-europe/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09231e2b-a211-471e-a936-97610cd5850d',
        'Gabon/COCAFE : les femmes de la fédération formées à l’entretien du foyer',
        'Une formation a été organisée pour sensibiliser les femmes chrétiennes à l’entretien du foyer, mettant en avant l’importance de leur rôle dans la gestion de la maison, l’éducation des enfants et leur épanouissement personnel.',
        'https://agpgabon.ga/gabon-cocafe-les-femmes-de-la-federation-formees-a-lentretien-du-foyer/',
        'AGP',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '90a4f4d2-f9a4-4adc-a0a7-9db5e66cdc20',
        'Sécurité alimentaire et nutritionnelle : Emmanuel Obakamba Ombana plaide pour une Commission Parlementaire dédiée, pilier de la vision du Président Brice Clotaire Oligui Nguema',
        'Le Gabon dépend fortement des importations pour sa nourriture, ce qui fragilise sa souveraineté et met en difficulté son secteur agricole, représentant seulement 5 % du PIB.',
        'https://www.gabonews.com/fr/actus/politique/article/securite-alimentaire-et-nutritionnelle-emmanuel',
        'Gabonews',
        'Business Intelligence',
        '2025-08-10T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f62ec58c-cc2f-4a00-96f4-b9c8687e9445',
        'Gabon/Assassinat d’Esther : la Première Dame au chevet de la famille de la défunte',
        'La Première Dame du Gabon, Zita Oligui Nguema, a rendu visite à la famille d’Esther Ludivine Moussavou Eyang Mba, une jeune fille victime d’un crime atroce, pour leur témoigner son soutien en ces moments difficiles.',
        'https://agpgabon.ga/gabon-assassinat-desther-la-premiere-dame-au-chevet-de-la-famille-de-la-defunte/',
        'AGP',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ede8c187-8276-47b2-ae49-ba49aa2cb0c2',
        'Gabon / Séminaire gouvernemental : bilan des cent premiers jours du mandat présidentiel',
        'Le président Brice Clotaire Oligui Nguema a présenté un bilan des cent premiers jours de son mandat lors d’un séminaire gouvernemental axé sur l’évaluation des actions entreprises et l’alignement des institutions.',
        'https://agpgabon.ga/gabon-seminaire-gouvernemental-bilan-des-cent-premiers-jours-du-mandat-presidentiel/',
        'AGP',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '720725b9-3fc8-4ae2-82c1-6bc0d2ecf35d',
        'Gabon : lancement du projet «Gab Pêche » ce lundi 11 août',
        'Le gouvernement gabonais lance officiellement le projet « Gab Pêche » pour renforcer les capacités des pêcheurs, notamment en leur fournissant des pirogues motorisées équipées de balises de géolocalisation et de kits de pêche.',
        'https://agpgabon.ga/gabon-lancement-du-projet-gab-peche-ce-lundi-11-aout/',
        'AGP',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01f23888-a981-421d-a316-bcad7d9c4de0',
        '100 jours du gouvernement : OLIGUI NGUEMA évalue les progrès',
        'Le président gabonais Brice Clotaire Oligui Nguema a présidé un séminaire gouvernemental pour faire le point sur les réalisations et l’avancement des 100 premiers jours du nouveau gouvernement, dans un esprit de rigueur, d’engagement et de transparence.',
        'https://vxp241.com/2025/08/11/100-jours-du-gouvernement-oligui-nguema-evalue-les-progres/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49dbe88a-93c1-47c2-a106-fdf36cf2725a',
        'Inauguration d’infrastructures dans la Ngounié: OLIGUI NGUEMA au cœur du développement local',
        'Le président gabonais a inauguré plusieurs infrastructures dans la province de la Ngounié le 8 août 2025, témoignant de son engagement pour le développement local et le mieux-être des populations.',
        'https://vxp241.com/2025/08/11/inauguration-dinfrastructures-dans-la-ngounie-oligui-nguema-au-coeur-du-developpement-local/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3a7c9a0-5b94-47d8-a78e-f1c7e8d666b4',
        'Le Gabon de Brice Clotaire Oligui Nguema face à la grande Histoire',
        'Brice Clotaire Oligui Nguema, nouveau président du Gabon, espérait tourner la page des conflits passés politiques, mais il doit faire face aux défis complexes de l’histoire et des enjeux sociaux du pays.',
        'https://www.jeuneafrique.com/1710007/politique/le-gabon-de-brice-clotaire-oligui-nguema-face-a-la-grande-histoire/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48520956-9183-4fd3-8000-4ffab79760af',
        'Élections 2025 : Oyiba rappelle à l’ordre les candidats investis par l’UDB sur le lancement précipité de la campagne',
        'Oyiba rappelle aux candidats investis par l''UDG de ne pas précipiter le lancement de leur campagne électorale pour respecter les règles et le calendrier prévus.',
        'https://gabonmediatime.com/elections-2025-oyiba-rappelle-a-lordre-les-candidats-investis-par-ludb-sur-le-lancement-precipite-de-la-campagne/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd67f8f97-20d9-48f5-90f8-a1b446d160af',
        'Gabon : VAALCO Energy, principal contributeur fiscal pétrolier au deuxième trimestre 2025',
        'Gabon prévoit que la contribution fiscale du secteur pétrolier Vaalco Energy atteindra son pic en deuxième trimestre 2025, renforçant ainsi ses revenus issus de cette activité.',
        'https://gabonmediatime.com/gabon-vaalco-energy-principal-contributeur-fiscal-petrolier-au-deuxieme-trimestre-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2f9f767-7eca-411c-9588-fce3a8fc97ec',
        'Faustin Boukoubi : «le PDG ne mourra pas»',
        'Faustin Boukoubi, président-directeur général, affirme qu''il ne mourra pas et reste confiant quant à l''avenir de son entreprise malgré les défis rencontrés.',
        'https://gabonmediatime.com/faustin-boukoubi-le-pdg-ne-mourra-pas/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a76a785-a8b7-4203-a547-79c4d103bcb4',
        'Zita OLIGUI aux côtés de la famille de « la petite Esther »',
        'La Première Dame du Gabon, Zita OLIGUI NGUEMA, a rendu visite à la famille de la petite Esther Ludivine Moussavou Eyang MBA, victime d’un crime odieux, pour lui exprimer sa compassion et son soutien.',
        'https://vxp241.com/2025/08/11/zita-oligui-aux-cotes-de-la-famille-de-la-petite-esther/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb686729-83cd-4e60-9047-865d76f5dad3',
        'Fly Gabon obtient son permis d’exploitation pour les vols vers Johannesburg',
        'Fly Gabon, opérée par Afrijet Business Services, a obtenu en août 2025 un permis pour effectuer des vols réguliers en Airbus A320 entre le Gabon et l’Afrique du Sud.',
        'https://directinfosgabon.com/fly-gabon-obtient-son-permis-dexploitation-pour-les-vols-vers-johannesburg/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0832b4d-bde9-4b43-aeb1-2d37dde3c34b',
        'CEMAC : Le Gabon reprogramme le sommet à septembre 2025',
        'Le sommet de la CEMAC, initialement prévu en août 2025 à Bangui, a été reporté au 10 septembre 2025 à la demande du Gabon en raison d’un conflit de dates.',
        'https://directinfosgabon.com/cemac-le-gabon-reprogramme-le-sommet-a-septembre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '694b5112-b13b-4d04-8be9-7eb491e58b7e',
        'Gabon Pêche Industrie : L’outil stratégique de Laurence Ndong',
        'La ministre de la Mer, Laurence Ndong, organise des rencontres et des visites pour renforcer la gestion et les réformes du secteur halieutique et aquacole au Gabon, notamment lors de la Foire aux poissons dans la province de la Ngounié.',
        'https://directinfosgabon.com/gabon-peche-industrie-loutil-strategique-de-laurence-ndong/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ded22846-18d0-41bb-814b-6790d783e42a',
        'Élections 2025 : Oyiba rappelle à l’ordre les candidats investis par l’UDB sur le lancement précipité de la campagne',
        'Oyiba met en garde les candidats investis par l''UDG pour les élections de 2025 contre le lancement prématuré de leur campagne, soulignant la nécessité de respecter le calendrier officiel.',
        'https://gabonmediatime.com/elections-2025-oyiba-rappelle-a-lordre-les-candidats-investis-par-ludb-sur-le-lancement-precipite-de-la-campagne/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9483e059-3e01-4e43-9c2d-41b5d33fce94',
        'Gabon : VAALCO Energy, principal contributeur fiscal pétrolier au deuxième trimestre 2025',
        'Vaalco Energy prévoit de devenir le principal contributeur fiscal pétrolier au Gabon d''ici le deuxième trimestre 2025 grâce à ses projets d''exploration et de production d''hydrocarbures.',
        'https://gabonmediatime.com/gabon-vaalco-energy-principal-contributeur-fiscal-petrolier-au-deuxieme-trimestre-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e1669c3b-0c44-4d73-af64-cee3f493353f',
        'Faustin Boukoubi : «le PDG ne mourra pas»',
        'Faustin Boukoubi rassure que le président-directeur général (PDG) ne mourra pas, évoquant des aspects liés à sa santé et à sa vitalité.',
        'https://gabonmediatime.com/faustin-boukoubi-le-pdg-ne-mourra-pas/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b69761d0-1ca7-4998-9e33-00a4edcef976',
        'La Première Dame Zita Oligui Nguema aux côtés de la famille de la petite Esther Ludivine Moussavou Eyang Mba',
        'La première dame Zita Oligui Nguema a rendu visite à la famille de la petite Esther Ludivine Moussavou Eyang Mba, montrant ainsi son soutien et son attention envers cette famille.',
        'https://kongossanews.info/la-premiere-dame-zita-oligui-nguema-aux-cotes-de-la-famille-de-la-petite-esther-ludivine-moussavou-eyang-mba/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc17b30f-137a-4617-8840-079cf0483eb2',
        'Baie des Rois : l’AGASA valide la conformité sanitaire des recettes du Chef O’miel',
        'La Baie des Rois Lagassa a validé la conformité sanitaire des recettes du chef Omiel, assurant leur sécurité pour la consommation.',
        'https://kongossanews.info/baie-des-rois-lagasa-valide-la-conformite-sanitaire-des-recettes-du-chef-omiel/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc704e87-0851-420f-a845-b3162206d700',
        'Publié le 10 / 08 / 2025',
        'Anges Kevin Nzigou se présente comme candidat à la mairie de Libreville, espérant apporter des changements dans la gestion de la capitale gabonaise.',
        'https://union.sonapresse.com/fr/fds-anges-kevin-nzigou-se-lance-la-conquete-de-la-mairie-de-libreville',
        'L''union',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76660c07-37d6-40e0-bcc5-b6aa1982ec72',
        'Zita Oligui Nguéma réconforte la famille d’Esther',
        'La Première Dame du Gabon, Zita Oligui Nguéma, a apporté son soutien à la famille d’Esther, dans un contexte lié à l’hôpital militaire du PK 9.',
        'https://gabonactu.com/blog/2025/08/11/zita-oligui-nguema-reconforte-la-famille-desther/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.490Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '596639b8-9c79-4b15-903e-9c61dc4ae027',
        'Transport aérien : L’Airbus A320 de Fly Gabon obtient son accès officiel sur le marché aérien sud-africain',
        'L''Airbus A320 de Fly Gabon a obtenu officiellement l''autorisation d''opérer sur le marché aérien sud-africain grâce à un permis délivré par l''International Air Services Council d''Afrique du Sud, renforçant la présence de la compagnie gabonaise dans la région.',
        'https://www.gabonreview.com/transport-aerien-lairbus-a320-de-fly-gabon-obtient-son-acces-officiel-sur-le-marche-aerien-sud-africain/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd992d8fa-84a2-407b-b572-e2d28c66cfb7',
        'Fly Gabon autorisée à desservir Johannesburg',
        'Fly Gabon a obtenu l''autorisation de desservir Johannesburg, grâce à la décision du Conseil international des services aériens (IASC) d''Afrique du Sud, avec Airbus A320.',
        'https://gabonactu.com/blog/2025/08/11/fly-gabon-autorisee-a-desservir-johannesburg/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ece90df8-2bef-4af6-999c-bc81c09df61f',
        'Pétrole : sortir la RSE de la pitance vers un facteur de développement inclusif (Tribune libre)',
        'L’industrie pétrolière au Gabon doit renforcer ses actions de responsabilité sociétale pour contribuer réellement au développement inclusif et durable des communautés locales.',
        'https://gabonactu.com/blog/2025/08/11/petrole-sortir-la-rse-de-la-pitance-vers-un-facteur-de-developpement-inclusif-tribune-libre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d4ed9a1-abd8-4448-bf0d-a0a175753a41',
        '« Qui boude bouge c’est pour dire que l’ancien système n’a qu’à bouger » (Brice Laccruche Alihanga)',
        'Brice Laccruche Alihanga affirme que pour que le changement advienne, l''ancien système doit accepter de se transformer et de bouger.',
        'https://gabonactu.com/blog/2025/08/11/qui-boude-bouge-cest-pour-dire-que-lancien-systeme-na-qua-bouger-brice-laccruche-alihanga/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b9e53ae-5b46-401b-b8ea-231373258345',
        'Rentrée scolaire 2025-2026 : la FESEENA menace de rompre la trêve tacite',
        'La FESEENA menace de rompre la trêve tacite si ses revendications concernant la réforme éducative et l''approche par compétences ne sont pas prises en compte rapidement.',
        'https://gabonactu.com/blog/2025/08/11/rentree-scolaire-2025-2026-la-feseena-menace-de-rompre-la-treve-tacite/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d4df42e-e885-4e3d-8781-676598b3e1a8',
        'Gabon/Délestages dans le grand Libreville : une entreprise de BTP à l’origine des coupures dans  la nuit d’hier dimanche',
        'Des coupures d’électricité dans le Grand Libreville ont été causées par un accident impliquant une entreprise de BTP ayant accroché des câbles électriques de haute tension avec un engin de chantier, entraînant des délestages dans plusieurs quartiers.',
        'https://agpgabon.ga/gabon-delestages-dans-le-grand-libreville-une-entreprise-de-btp-a-lorigine-des-coupures-dans-la-nuit-dhier-dimanche/',
        'AGP',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '261a8385-744a-4cd7-8360-15306f16ee4a',
        'L''Angola accueille l''AfroBasket 2025',
        'La 31ᵉ édition du championnat africain de basketball se déroule en Angola du 12 au 24 août, avec 16 équipes qualifiées après les éliminatoires, tandis que la Centrafrique, le Gabon, le Kenya et le Maroc ont été éliminés.',
        'https://www.rfi.fr/fr/sports/20250811-l-angola-accueille-l-afrobasket-2025?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e366f037-dd4e-4bd3-b5f5-344ccaf4fd97',
        'Laurence Ndong lance le projet « Gab Pêche » pour moderniser la pêche artisanale et renforcer l’économie bleue',
        'Le projet « Gab Pêche » lancé par la ministre Laurence Ndong vise à moderniser la pêche artisanale au Gabon et à renforcer l’économie bleue du pays.',
        'https://gabonactu.com/blog/2025/08/11/laurence-ndong-lance-le-projet-gab-peche-pour-moderniser-la-peche-artisanale-et-renforcer-leconomie-bleue/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-11T00:00:00.000Z',
        '2025-09-15T23:06:12.491Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

