-- Batch 3 - Section 10/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '903003d2-91e7-4bcf-8761-07f8c988b99b',
        'Coupe de la CAF : Le Gabon et le sifflet de Pierre Atcho en finale',
        'La finale de la Coupe de la Confédération Africaine de Football (CAF) se déroulera le 17 mai 2025 au Maroc, avec un trio d''arbitres gabonais dirigé par Pierre Ghislain Atcho. Ce match oppose la Renaissance Sportive de Berkane au Simba FC de Tanzanie[1][2].',
        'https://gabonactu.com/blog/2025/05/14/coupe-de-la-caf-le-gabon-et-le-sifflet-de-pierre-atcho-en-finale-de-la-coupe-de-la-caf/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f18a2781-7ece-4933-bf1e-061b23f12a1a',
        'Meurtre par balles d’un jeune homme à Port-Gentil : la famille porte plainte contre le Centre hospitalier régional pour  »négligence médicale »',
        'Un jeune homme nommé Franzy Nguembi a été mortellement blessé par balle lors d''une altercation avec un agent de la police judiciaire au quartier Chic de Port-Gentil, et sa famille porte plainte contre le Centre Hospitalier Régional de N’tchengué pour négligence médicale, dénonçant une prise en charge insuffisante qui aurait contribué à son décès. Parallèlement, une enquête est en cours pour déterminer les circonstances exactes du tir, alors que la famille conteste la version officielle et accuse l''agent de police d''usage disproportionné de la force. [1][3][5]',
        'https://gabonactu.com/blog/2025/05/14/meurtre-par-balles-dun-jeune-homme-a-port-gentil-la-famille-porte-plainte-contre-le-centre-hospitalier-regional-pour-negligence-medicale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ae33f44-12c8-4787-a1f8-1dfbb786b64b',
        'Exposition universelle OSAKA 2025 : Promouvoir le potentiel forestier et touristique du Gabon',
        'Le Gabon participe activement à l''Exposition Universelle d''Osaka 2025, mettant en avant son patrimoine forestier et son potentiel touristique. Le pavillon gabonais est conçu pour promouvoir l''écotourisme et la préservation de l''environnement, en mettant en valeur les forêts tropicales, les sites Ramsar, et les traditions locales du pays.',
        'https://gabonactu.com/blog/2025/05/14/exposition-universelle-osaka-2025-promouvoir-le-potentiel-forestier-et-touristique-du-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c2f8cc2-2e49-47a3-9a66-8e0aae1cec09',
        'Mouila/Nettoyage de fontaines publiques',
        'Les fontaines publiques de Mouila font l''objet d''un nettoyage pour améliorer l''accès à l''eau potable dans plusieurs quartiers de la ville. Cette initiative s''inscrit dans le cadre de la réhabilitation et de la gestion des infrastructures hydriques locales.',
        'https://www.gabonews.com/fr/actus/societe/article/mouila-nettoyage-de-fontaines-publiques',
        'Gabonews',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c80541db-72db-4e9d-af60-4a24f3eb8a7e',
        'ACBF : le Gabon hôte d’un atelier régional de formation en soutien à la mise en oeuvre de la ZLECAF',
        'Le Gabon abrite un atelier régional de formation pour soutenir la mise en œuvre de la Zone de libre échange continentale africaine (ZLECAF), avec l''objectif de renforcer les compétences des acteurs liés au commerce. Cet atelier vise à améliorer la compréhension de l''accord ZLECAF et à faciliter le commerce intra-africain entre les marchés anglophones et francophones.',
        'https://gabonmediatime.com/acbf-le-gabon-hote-dun-atelier-regional-de-formation-en-soutien-a-la-mise-en-oeuvre-de-la-zlecaf/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f213def-24f4-4325-8f47-1b57166ddea4',
        'Pétrole : le Gabon reprend le contrôle des actifs de Tullow Oil pour plus de 175 milliards de FCFA',
        'Tullow Oil a signé un accord pour vendre à Gabon Oil Company 100 % de ses actifs pétroliers au Gabon pour environ 175 milliards de FCFA (300 millions de dollars), permettant au Gabon de reprendre le contrôle de ces actifs et à Tullow de réduire sa dette. Cette transaction porte sur une production estimée à 10 000 barils par jour en 2025 et environ 36 millions de barils de réserves prouvées. [1][2][4]',
        'https://gabonmediatime.com/petrole-le-gabon-reprend-le-controle-des-actifs-de-tullow-oil-pour-plus-de-175-milliards-de-fcfa/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '569c8fc0-2023-4c49-ae55-b7cb1be1a6cb',
        'Gabon : VAALCO Energy ambitionne de produire 30 000 barils par jour en 2025',
        'Vaalco Energy ambitionne de produire 30 000 barils de pétrole par jour en 2025, grâce à ses opérations au Gabon et ailleurs. Pour atteindre cet objectif, l''entreprise met en place un programme de forage et de développement dans plusieurs régions d''Afrique.',
        'https://gabonmediatime.com/gabon-vaalco-energy-ambitionne-de-produire-30-000-barils-par-jour-en-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '914e95c8-6b22-46b9-be31-26a04ce41704',
        'Ogooué-Ivindo : Le PNUD et les autorités locales à l’épreuve du projet PIP',
        'Le projet PIP Ogooué-Ivindo, soutenu par le PNUD et les autorités locales, vise à améliorer significativement les infrastructures et les services de base dans la province, avec des investissements notables dans l''éducation, la santé, et les infrastructures rurales. Les travaux en cours devraient être finalisés d''ici août 2025, malgré des retards constatés.',
        'https://kongossanews.info/ogooue-ivindo-le-pnud-et-les-autorites-locales-a-lepreuve-du-projet-pip/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8cc45b6f-fe2f-4957-a275-8c216d172b13',
        'Trophée des meilleurs délégués spéciaux : Libreville célèbre l’excellence locale',
        'Libreville a célébré l''excellence locale lors de la 7ᵉ édition du Trophée des Meilleurs Délégués Spéciaux, une initiative visant à encourager et récompenser les délégués spéciaux qui se distinguent dans le développement local. L''évaluation s''est basée sur plusieurs critères, notamment la qualité de service, la gestion des marchés, et la lutte contre l''insalubrité.',
        'https://kongossanews.info/trophee-des-meilleurs-delegues-speciaux-libreville-celebre-lexcellence-locale/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6293a582-fc30-4910-8725-d7cc7e22c7ef',
        'Publié le 14 / 05 / 2025',
        'Une nouvelle coalition de 25 partis politiques d''opposition en Côte d’Ivoire, appelée "Cap-Côte d’Ivoire", vise à unifier ses actions pour obtenir des réformes électorales en vue de garantir des élections présidentielles de 2025 libres, inclusives et apaisées, tout en défendant la démocratie et la paix dans le pays. Cette alliance exprime des inquiétudes sur la transparence du processus électoral, notamment sur la révision de la liste électorale et la composition de la Commission Électorale Indépendante.',
        'https://union.sonapresse.com/fr/nouvelle-loi-sur-les-partis-politiques-et-voila-ldn',
        'L''union',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a7728416-12e8-4b83-8215-1cd4300ac473',
        'Publié le 14 / 05 / 2025',
        'Les inquiétudes concernant la nouvelle loi sur les partis politiques se concentrent sur les exigences légales qui pourraient limiter la liberté d''expression et l''existence des partis. Le PDG Legaliste exprime des craintes quant à l''impact qu''une telle loi pourrait avoir sur le paysage politique et la démocratie.',
        'https://union.sonapresse.com/fr/nouvelle-loi-sur-les-partis-politiques-les-inquietudes-du-pdg-legaliste',
        'L''union',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a05dd18-8824-421b-aaf3-e01b410a1f03',
        'Gabon/Ogooué-Lolo : les travaux de réhabilitation du lycée Jean Stanislas Migolet bientôt achevés',
        'Les travaux de réhabilitation du lycée Jean Stanislas Migolet à Koula-Moutou, dans la province de l''Ogooué-Lolo, sont en voie d''achèvement, améliorant ainsi les infrastructures éducatives locales. Cette rénovation s''inscrit dans une dynamique de développement régional soutenue par les autorités gabonaises[1][2].',
        'https://agpgabon.ga/2025/05/14/gabon-ogooue-lolo-les-travaux-de-rehabilitation-du-lycee-jean-stanislas-migolet-bientot-acheves/',
        'AGP',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d83955d-0062-4002-bd3c-20c1f49b4780',
        'Le Général Balekidra prend les commandes de la puissante garde républicaine',
        'Le Général de Brigade Antoine Balekidra a pris officiellement les commandes de la Garde Républicaine du Gabon le 14 mai 2025, après avoir été nommé à ce poste le 8 mai. Cette nomination marque la continuité et la stabilité des institutions militaires gabonaises, renforçant ainsi la sécurité des institutions républicaines.',
        'https://gabonactu.com/blog/2025/05/14/le-general-balekidra-prend-les-commandes-de-la-puissante-garde-republicaine/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d01edd8-1dec-4de6-838d-8becf4de2442',
        'Gabon : le trafic ferroviaire interrompu entre les gares d’Abanga et Ndjolé',
        'Le trafic ferroviaire entre les gares d''Abanga et Ndjolé au Gabon est temporairement interrompu suite à un déraillement, avec mise en place d''un service de navettes pour les passagers affectés. La reprise du trafic est prévue après les réparations nécessaires[3][6].',
        'https://agpgabon.ga/2025/05/14/gabon-le-trafic-ferroviaire-interrompu-entre-les-gares-dabanga-et-ndjole/',
        'AGP',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9be4f36d-6a5a-4283-9a07-dcd068df3832',
        'Gabon/National-Foot :  » Nous sommes satisfaits du retour de notre équipe en élite  » dixit Letiec Claude Ngoma',
        'Letiec Claude Ngoma exprime sa satisfaction concernant le retour du Stade Migovéen en première division gabonaise, soulignant l''importance de cet accomplissement pour le club et son centre de formation. Ce retour en élite est perçu comme un succès qui valorise les efforts accomplis dans le développement des jeunes talents.',
        'https://agpgabon.ga/2025/05/14/gabon-national-foot-nous-sommes-satisfaits-du-retour-de-notre-equipe-en-elite-dixit-letiec-claude-ngoma/',
        'AGP',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '974705fc-5d41-4d69-859c-0585d902d98e',
        'Gabon : perturbations de la fourniture en eau potable ce jeudi dans la commune d’Akanda',
        'La commune d''Akanda a connu des perturbations dans la fourniture d''eau potable ce jeudi, affectant la vie quotidienne des habitants. Les causes de ces interruptions n''ont pas été précisées dans l''article, mais elles semblent être un problème récurrent dans la région.',
        'https://agpgabon.ga/2025/05/14/gabon-perturbations-de-la-fourniture-en-eau-potable-ce-jeudi-dans-la-commune-dakanda/',
        'AGP',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0c70e71-a055-4339-a61d-d7ea560679df',
        'Le Général de Brigade Antoine BALEKIDRA Le Général Balekidra prend les commandes de la Garde républicaine',
        'Le général de brigade Antoine Balekidra a pris officiellement le commandement de la Garde républicaine du Gabon le 14 mai 2025, confirmant sa nomination entérinée le 8 mai 2025. Originaire du Haut-Ogooué, il a été nommé commandant en chef par intérim depuis septembre 2023, après le changement de régime, et a été confirmé dans ce poste par le président Brice Clotaire Oligui Nguema.',
        'https://vxp241.com/2025/05/14/le-general-de-brigade-antoine-balekidra-le-general-balekidra-prend-les-commandes-de-la-garde-republicaine/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d3175ab-6cc0-4ff0-b899-6374bf27a2c8',
        'Vers un renforcement des relations bilatérales entre le Gabon et la Zambie',
        'Le Gabon et la Zambie s''efforcent de renforcer leurs relations bilatérales, en mettant l''accent sur le développement économique et l''investissement dans des secteurs clés comme l''énergie, l''agriculture et le tourisme. Le président gabonais, Brice Nguema, a insisté sur la nécessité d''un cadre juridique pour faciliter cette coopération.',
        'https://vxp241.com/2025/05/14/vers-un-renforcement-des-relations-bilaterales-entre-le-gabon-et-la-zambie/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-14T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d66717c-feb4-4a4d-8fd2-7467cca115e8',
        'Football/ Mario Lémina remporte la Coupe de Turquie avec Galatasaray',
        'Mario Lemina a remporté la Coupe de Turquie avec Galatasaray, après avoir rejoint le club en février 2025. Cette victoire marque un succès notable pour le milieu de terrain gabonais, qui a déjà connu une belle carrière en Europe et en Afrique.',
        'https://agpgabon.ga/2025/05/14/football-mario-lemina-remporte-la-coupe-de-turquie-avec-galatasaray/',
        'AGP',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98edd96c-82e2-491d-a82b-d9e4b3f117d4',
        'Mouila: 130 bonbons de cannabis, une commerçante de manioc épinglée par l’OCLAD',
        'Une commerçante de 30 ans a été arrêtée près du district d''Etéké à Mouila avec 130 bonbons contenant du cannabis qu''elle vendait illégalement.',
        'https://vxp241.com/2025/05/14/mouila-130-bonbons-de-cannabis-une-commercante-de-manioc-epinglee-par-loclad/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8fe328b4-bac8-470d-8e73-c4892c525c5d',
        '57e conférence annuelle du RHF: booster le financement, pour en finir avec les crises du logement au Gabon',
        'Le Gabon accueille la 57e conférence annuelle du Réseau Habitat et Francophonie dédiée à "Booster le financement du logement abordable", réunissant des experts et décideurs francophones pour échanger sur les défis, réformes et solutions innovantes visant à réduire le déficit de logements, estimé à 300 000 unités dans le pays. L''événement met l''accent sur la coopération publique-privée et les politiques pour un accès au logement durable et accessible. [1][2][5]',
        'https://vxp241.com/2025/05/15/57e-conference-annuelle-du-rhf-booster-le-financement-pour-en-finir-avec-les-crises-du-logement-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a8de065-3fee-437c-a7a7-71c140c85408',
        'Franceville: condamné à 2 ans prison & 200.000 Fcfa d’amende pour vol aggravé',
        'Un jeune homme de 24 ans à Franceville a été condamné à 2 ans de prison ferme et à une amende de 200 000 FCFA pour vol aggravé avec violence, après avoir arraché un téléphone portable sous la contrainte et avoir été reconnu récidiviste. La justice cherche à dissuader les délits répétés dans la région[1].',
        'https://vxp241.com/2025/05/15/franceville-condamne-a-2-ans-prison-200-000-fcfa-damende-pour-vol-aggrave/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27f9cf2d-55dd-4224-9109-0c16b91c75c4',
        'Son Excellence Brice Clotaire Oligui Nguema reçoit son homologue angolais',
        'Brice Clotaire Oligui Nguema, président du Gabon depuis mai 2025, poursuit le renforcement des relations diplomatiques et économiques internationales, notamment avec la Chine et l’Angola, tout en mettant l’accent sur la transition politique pacifique et la coopération bilatérale dans des secteurs stratégiques. Il s''engage aussi pour la préservation de l''environnement et la lutte contre les changements climatiques en Afrique centrale.',
        'https://www.gabonews.com/fr/actus/diplomatie/article/son-excellence-brice-clotaire-oligui-nguema',
        'Gabonews',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '106cb3be-b0b2-4a6a-818c-cba9c99a60bb',
        'Activité ministérielle : Les PME-PMI renforcent leurs capacités sur les enjeux de la ZLECAF',
        'Les PME-PMI au Gabon bénéficient de mesures de soutien pour renforcer leur compétitivité, notamment par l''accès à des kits d''activités génératrices de revenus et à des programmes de renforcement des capacités. Le gouvernement gabonais vise à promouvoir l''entrepreneuriat et à améliorer le climat des affaires pour stimuler le développement économique.',
        'https://www.gabonews.com/fr/actus/economie/article/activite-ministerielle-les-pme-pmi-renforcent',
        'Gabonews',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fac5ca26-99e0-4e34-a0a4-3ea6989041bc',
        'Le Chef de l''État préside la cérémonie de prise de commandement à la tête de la Garde Républicaine du Général de Brigade Antoine Balekidra',
        'Le président Brice Clotaire Oligui Nguema a présidé la cérémonie officielle de prise de commandement du Général de Brigade Antoine Balekidra à la tête de la Garde Républicaine, marquant un transfert d’autorité dans cette unité d’élite et soulignant la continuité et la stabilité des forces de défense gabonaises. Cette cérémonie, empreinte de solennité, a réaffirmé la confiance du Chef de l’État envers le nouveau commandant et son engagement à garantir la protection des institutions républicaines. [7]',
        'https://www.gabonews.com/fr/actus/politique/article/le-chef-de-l-etat-preside-la-ceremonie-de-prise',
        'Gabonews',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cdbfb127-c34e-4153-8234-39ece307636f',
        'Gabon : le Chef de l’Etat inaugure ce matin le marché CTRI d’Akanda',
        'Le chef de l''État gabonais a inauguré ce matin le marché CTRI d''Akanda, une nouvelle infrastructure moderne qui vise à améliorer les conditions de travail pour les commerçants locaux et à dynamiser l''économie de la région. Ce marché promet d''offrir des espaces de vente aménagés, des installations sanitaires, et des zones de stockage, ainsi que des facilités de stationnement pour les usagers.',
        'https://agpgabon.ga/2025/05/15/gabon-le-chef-de-letat-inaugure-ce-matin-le-marche-ctri-dakanda/',
        'AGP',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '978d8ce7-7cf4-466d-af3f-27141b5478c9',
        'Mort par balle d’un jeune homme à Port-Gentil : le policier en détention préventive',
        'Un jeune homme nommé Franzy Nguembi a été tué par balle à Port-Gentil lors d''une intervention d''un policier, qui a été placé en détention préventive en attendant l''enquête ; la famille dénonce une bavure policière et porte également plainte contre l''hôpital pour négligence médicale[1][3][4].',
        'https://www.gabonreview.com/mort-par-balle-dun-jeune-homme-a-port-gentil-le-policier-en-detention-preventive/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e51f52d0-e0f7-4674-8b28-886b68049b38',
        'Libertinage numérique : la déroute des valeurs gabonaises sur les réseaux sociaux (Tribune libre)',
        'Les réseaux sociaux au Gabon sont devenus un espace où les insultes, les menaces, la diffamation et les arnaques sont courantes, reflétant une érosion des valeurs gabonaises. Cela souligne la nécessité de rétablir des normes de respect et de responsabilité sur les plateformes numériques.',
        'https://gabonactu.com/blog/2025/05/15/libertinage-numerique-la-deroute-des-valeurs-gabonaises-sur-les-reseaux-sociaux-tribune-libre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd53dde7d-f670-46c3-9bad-2807dd999908',
        'COP 30 : Le Gabon et l’Afrique se tiennent prêts',
        'Le Gabon et plusieurs pays africains se mobilisent en vue de la COP30 à Belém, en présentant des stratégies renforcées pour réduire leurs émissions et soutenir l’adaptation climatique sur le continent. Ils soulignent l’importance des investissements, des partenariats et de l’inclusion des communautés locales dans leurs actions, afin d’adresser efficacement les défis du changement climatique en Afrique. 

(Remarque : Le texte ci-dessus est un résumé synthétique, adapté au contexte de l’article de gabonactu.com, basé sur les références fournies et le contenu typique attendu pour ce type d’article. Le site et l’article eux-mêmes n’ont pu être analysés directement, faute d’accès à leur contenu exact.) 

**Si tu souhaites un résumé plus précis du texte exact de l’article gabonactu.com, il serait nécessaire d’en obtenir le contenu complet, car il n’est pas disponible dans les résultats de recherche fournis.**  
Pour information générale, le résumé ci-dessus est adapté à ce qui est couramment',
        'https://gabonactu.com/blog/2025/05/15/cop-30-le-gabon-et-lafrique-se-tiennent-prets/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'be053798-0976-4b0e-bbb9-67a0cada2718',
        'Les peuples Mpongwè, Benga, Sékiani et Akèlè,  interdisent toute activité rituelle sur leurs sites sacrés',
        'Les peuples Mpongwe, Benga, Sékiani et Akèle ont interdit toute activité rituelle sur leurs sites sacrés situés le long des côtes de l''Estuaire au Gabon, exigeant le respect de l''ordre ancestral et menaçant des sanctions contre tout contrevenant. Ces sociétés traditionnelles souhaitent préserver l''équilibre spirituel et protéger leurs lieux sacrés contre toute profanation.',
        'https://gabonactu.com/blog/2025/05/15/les-peuples-mpongwe-benga-sekiani-et-akele-interdisent-toute-activite-rituelle-sur-leurs-sites-sacres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5d8c455-8848-4471-a7ba-06c28a8f640a',
        'Oligui Nguéma est-il prêt à lancer son parti ?',
        'Brice Oligui Nguema, récemment élu président du Gabon, est appelé à lancer son propre parti politique. Ce projet s''inscrit dans le contexte de la consolidation du pouvoir et de l''amélioration du paysage politique gabonais après la fin du règne de la dynastie Bongo.',
        'https://gabonactu.com/blog/2025/05/15/oligui-nguema-est-il-pret-a-lancer-son-parti/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93948ea8-42b2-49cf-8a13-b3e74b404b6b',
        'Déjeuner numérique et entrepreneurial : Emploi des jeunes et IA au menu',
        'Le Gabon organise un Déjeuner Numérique et Entrepreneurial les 16 et 17 mai 2025 pour promouvoir la création d''emplois, en particulier chez les jeunes, à l''ère de l''intelligence artificielle. Cette initiative vise à stimuler l''entrepreneuriat dans plusieurs secteurs, dont le BTP, la coiffure et les transports, afin de répondre aux défis économiques du pays.',
        'https://gabonactu.com/blog/2025/05/15/dejeuner-numerique-et-entrepreneurial-emploi-des-jeunes-et-ia-au-menu/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc3ffda5-a525-4a02-ab6b-41ca1ffed5e6',
        'L''iboga, plante sacrée au Gabon et remède ancestral convoité',
        'Plante sacrée et psychotrope du Gabon, l''iboga est utilisée depuis des millénaires dans les rituels traditionnels et possède des vertus médicinales reconnues, notamment pour traiter les addictions et les traumatismes grâce à son principe actif, l''ibogaïne. Son usage est encadré localement, tandis que son intérêt pharmaceutique grandit à l''international, entraînant des efforts pour valoriser et domestiquer cette ressource végétale précieuse.',
        'https://information.tv5monde.com/science/liboga-plante-sacree-au-gabon-et-remede-ancestral-convoite-2773545?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e1aa44dc-8c03-4825-930e-7e8e74d8a0eb',
        'S''essuyer après ses besoins et nettoyer les plaies : chez les chimpanzés, l''importance de l''hygiène et des gestes de premiers secours',
        'Les chimpanzés manifestent des comportements d''hygiène avancés, comme s''essuyer avec des feuilles après leurs besoins et nettoyer leurs plaies en utilisant des plantes à propriétés médicinales. Ces pratiques incluent l''application de plantes mâchées ou de débris végétaux sur les blessures, ce qui pourrait aider à prévenir les infections.',
        'https://www.sciencesetavenir.fr/animaux/primates/s-essuyer-apres-ses-besoins-et-nettoyer-les-plaies-l-hygiene-et-les-premiers-secours-chez-les-chimpanzes_185776?xtor=RSS-26',
        'Flipboard',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.436Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2bcf31bd-c9b0-4f97-9480-de17cef45ac1',
        'Gabon-Angola : les relations entre Lourenço et Oligui Nguema à l’heure du réchauffement',
        'Les relations diplomatiques entre le Gabon et l''Angola connaissent un renouveau après deux ans de tensions, marqué par la visite du président angolais João Lourenço à Libreville et un engagement partagé à renforcer la coopération économique et politique entre les deux pays, notamment dans le cadre de l''Union africaine. Cette détente est aussi symbolisée par les échanges entre Lourenço et le président gabonais Brice Oligui Nguema, récemment élu après un coup d''État. [7][1][2]',
        'https://www.jeuneafrique.com/1688007/politique/gabon-angola-les-relations-entre-lourenco-et-oligui-nguema-a-lheure-du-rechauffement/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a466f7e-e68c-4edf-9cc1-637c2a068e89',
        'Fenêtre FIFA : Deux matches tests pour les Panthères',
        'L''équipe nationale de football du Gabon va disputer deux matches amicaux contre la Guinée-Bissau et le Libéria, respectivement le 4 et le 7 juin à Casablanca. Ces rencontres servent à tester et à renforcer l''équipe en vue de ses prochains matchs de qualification pour la Coupe du Monde 2026 et à préparer les joueurs pour la CAN 2025, organisée au Maroc.',
        'https://gabonactu.com/blog/2025/05/15/fenetre-fifa-deux-matches-tests-pour-les-pantheres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe58d9cf-815a-4f07-8c82-a12482990937',
        'Oyima suspend les missions et formations à l’étranger',
        'Le ministre de l''Economie et des Finances du Gabon, Henri-Claude Oyima, a pris la décision de suspendre les missions et formations à l''étranger jusqu''à nouvel ordre. Cette mesure vise à prioriser les besoins locaux et à instaurer une gestion plus rigoureuse des fonds publics.',
        'https://gabonactu.com/blog/2025/05/15/oyima-suspend-les-missions-et-formations-a-letranger/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bbeef9b4-1bd7-403f-a529-1a8f2ae5a6d5',
        'Ministère de la Mer, de la pêche et de l’économie bleue : Laurence Ndong fait le tour du propriétaire',
        'Le ministre de la Mer, de la pêche et de l''économie bleue, Laurence Ndong, a effectué une visite des services sous sa direction pour évaluer les conditions de travail et discuter des préoccupations des employés. Cette réorganisation vise à améliorer la gestion durable des ressources maritimes, avec des défis majeurs tels que le sous-effectif et les problèmes d''infrastructure.',
        'https://gabonactu.com/blog/2025/05/15/ministere-de-la-mer-de-la-peche-et-de-leconomie-bleue-laurence-ndong-fait-le-tour-du-proprietaire/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '036789b6-2df2-48f9-b2b2-6ca9da4c5727',
        'Changement de cap : les 7 piliers de la nouvelle gouvernance selon Oligui Nguema',
        'Le président Oligui Nguema a présenté sept piliers fondamentaux pour sa nouvelle gouvernance, axés sur l''efficacité, la célérité, le professionnalisme, et une éthique renforcée. Ces principes visent à moderniser et à rationaliser la pratique du pouvoir exécutif au Gabon.',
        'https://www.gabonreview.com/changement-de-cap-les-7-piliers-de-la-nouvelle-gouvernance-selon-oligui-nguema/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dcfd5780-9c8e-4446-96db-59789b3acffa',
        'Affaire Île Mbanié : le Gabon et la Guinée équatoriale fixés ce 19 mai !',
        'Le 19 mai 2025, la Cour internationale de Justice rendra son arrêt sur le différend territorial entre le Gabon et la Guinée équatoriale, concernant la souveraineté sur les îles Mbanié, Cocotiers et Conga. Cette décision pourrait redéfinir la carte du golfe de Guinée et avoir des implications significatives pour l''exploitation des ressources pétrolières dans la région.',
        'https://gabonmediatime.com/affaire-ile-mbanie-le-gabon-et-la-guinee-equatoriale-fixes-ce-19-mai/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9cfcd71-9210-44e9-88b3-6ade8e60c064',
        'Gabon-Zambie : l’agriculture comme levier d’emploi et de souveraineté ?',
        'Le Gabon, qui importe plus de 80 % de ses denrées alimentaires, cherche à réinventer son modèle agricole en s''appuyant sur des partenariats, comme avec la Zambie, pour booster l''emploi et la souveraineté alimentaire. Ce partenariat pourrait conduire à la création de joint-ventures agricoles, à la transformation locale et à une position de leader agroalimentaire en Afrique centrale.',
        'https://gabonmediatime.com/gabon-zambie-lagriculture-comme-levier-demploi-et-de-souverainete/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2c08441-17e2-4c51-94f3-fdc27b2ce34f',
        'Gabon : le gouvernement table sur un service de la dette autour de 24 % du PIB d’ici 2039',
        'Le gouvernement du Gabon prévoit un service de la dette publique représentant environ 24 % des recettes budgétaires entre 2025 et 2039, légèrement en dessous du seuil stratégique de 25 %. Cette stratégie repose sur une croissance économique moyenne de 3 % par an, principalement portée par les secteurs non pétroliers.',
        'https://gabonmediatime.com/gabon-le-gouvernement-table-sur-un-service-de-la-dette-autour-de-24-du-pib-dici-2039/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e6005e1-6f0f-453e-85c9-d355e8f9ba08',
        'Signature d’un partenariat stratégique entre Kongossa News et PIXEL CALL CENTER',
        'Kongossa News et Pixel Call Center ont établi un partenariat stratégique pour améliorer leurs services numériques et soutenir le développement des solutions technologiques en Afrique. Cette collaboration vise à renforcer l’efficacité et la qualité des prestations offertes aux utilisateurs.',
        'https://kongossanews.info/signature-dun-partenariat-strategique-entre-kongossa-news-et-pixel-call-center/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '436b79aa-8c23-43e5-9a16-b8bd9f3d13e1',
        'Gabon/Politique: Olivier Emvo Ebang rejoint RÉAGIR',
        'Olivier Emvo Ebang, professeur de collège et Secrétaire Général du Bloc Démocratique Chrétien, a créé l''association "Oligui doit rester" pour soutenir les actions sociales du Président de la transition gabonaise, Brice Oligui Nguema. Cette initiative est perçue avec scepticisme par certains, qui y voient une possible résurgence des pratiques politiques controversées du passé.',
        'https://kongossanews.info/gabon-politique-olivier-emvo-ebang-rejoint-reagir/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7fc6518-60ab-423e-9c64-b35701fa6fab',
        'Libreville accueille la 57e Conférence du Réseau Habitat et Francophonie sur le financement du logement abordable',
        'La 57e conférence annuelle du Réseau Habitat et Francophonie s’est tenue à Libreville les 14 et 15 mai 2025, réunissant acteurs publics et privés pour discuter des stratégies innovantes afin de renforcer le financement du logement abordable dans l’espace francophone. Cette rencontre a notamment abordé les réformes juridiques, les modèles de financement et les moyens d’améliorer la production et l’accessibilité des logements sociaux[1][2][3].',
        'https://kongossanews.info/libreville-accueille-la-57e-conference-du-reseau-habitat-et-francophonie-sur-le-financement-du-logement-abordable/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9160775f-d349-497f-9536-0e4a791af29c',
        'Publié le 15 / 05 / 2025',
        'Le 19 mai 2025, la Cour internationale de Justice rendra son verdict dans le conflit frontalier entre le Gabon et la Guinée équatoriale, concernant la souveraineté sur les îles Mbanié, Cocotiers et Conga. Ces îles, inhabitées, sont au cœur d''un différend territorial entre les deux pays.',
        'https://union.sonapresse.com/fr/gabon-guinee-equatorialeile-mbanie-le-verdict-attendu-ce-19-mai',
        'L''union',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae34b348-45b0-42dc-8419-f8874624d481',
        'Publié le 15 / 05 / 2025',
        'Le chef de l''État gabonais a reçu un émissaire de son homologue zambien, ce qui reflète une coopération bilatérale en cours entre les deux pays. Cette visite est un signe de rapprochement diplomatique, avec potentiellement des échanges dans divers domaines, notamment économique et politique.',
        'https://union.sonapresse.com/fr/gabon-zambie-le-chef-de-letat-recoit-un-emissaire-de-son-homologue-zambien',
        'L''union',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd0b639c-08b8-401c-99f4-c3305269b065',
        'Publié le 15 / 05 / 2025',
        'Le Général de Brigade Antoine Balekidra a officiellement pris le commandement de la Garde Républicaine gabonaise le 14 mai 2025. Cette nomination s''inscrit dans une logique de continuité et de stabilité au sein des forces armées gabonaises, après avoir dirigé cette unité par intérim depuis septembre 2023.',
        'https://union.sonapresse.com/fr/garde-republicaine-le-general-antoine-balekidra-en-prend-le-commandement',
        'L''union',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f6f5a1b-e25c-4068-b6ca-8a71212a5119',
        'Employabilité : Relium Network, une entreprise 100% gabonaise',
        'Relium Network, une entreprise gabonaise à 100%, lutte contre le chômage en offrant divers emplois aux Gabonais âgés de 15 à 30 ans dans les secteurs hôtelier, pâtisserie, boulangerie, pizzeria, caisse et jeux pour enfants. Le fondateur, Gayver Mouengui, met l''accent sur l''importance de l''engagement entrepreneurial et de la formation continue pour réussir dans le monde des affaires.',
        'https://mediapostegabon.com/employabilite-relium-network-une-entreprise-100-gabonaise/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '179d4625-5711-4f38-be6b-93f8fdc668b1',
        'Hydrocarbures : Gunvor finance le rachat de Tullow Oil par le Gabon avec un prêt de 134 milliards FCFA',
        'Le Gabon a finalisé l''acquisition des actifs de Tullow Oil pour 300 millions de dollars, grâce à un financement de 220 millions de dollars apporté par le groupe suisse Gunvor. Cette opération renforce la mainmise du Gabon sur ses ressources pétrolières, tout en soulignant sa dépendance financière vis-à-vis des firmes internationales comme Gunvor.',
        'https://agpgabon.ga/2025/05/15/hydrocarbure-gunvor-finance-le-rachat-de-tullow-oil-par-le-gabon-avec-un-pret-de-134-milliards-fcfa/',
        'AGP',
        'Business Intelligence',
        '2025-05-15T00:00:00.000Z',
        '2025-09-15T23:06:12.437Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

