-- Batch 4 - Section 14/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '61cb7b70-4896-4fe1-93fe-655c996fc9ef',
        'Gabon/Fête des Pères : L’absence paternelle, un défi pour la cellule familiale',
        'L''absence croissante de pères dans les foyers gabonais pose des problèmes pour l''équilibre familial et le développement des enfants, qui sont souvent élevés seul par leurs mères, ce qui peut nuire à leur réussite scolaire et à leur stabilité sociale.',
        'https://agpgabon.ga/gabon-fete-des-peres-labsence-paternelle-un-defi-pour-la-cellule-familiale/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38b9e976-b3cd-44ac-b25f-28bfd06d0231',
        'Gabon : Gab’Oil se redresse sous la direction de Renée-Patricia Ku-Kumbe Ivigu',
        'Depuis son arrivée en janvier 2025, Renée-Patricia Ku-Kumbe Ivigu a relancé Gab’Oil en renforçant la gestion, la transparence et la stratégie de l''entreprise, ce qui a permis d''améliorer sa situation financière en réduisant une partie de sa dette et en augmentant sa trésorerie.',
        'https://agpgabon.ga/gabon-gaboil-se-redresse-sous-la-direction-de-renee-patricia-ku-kumbe-ivigu/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '078991ff-1eff-4604-928f-9ef6221eff97',
        'Moov Africa Gabon Telecom lance sa e-carte via l’application Momo store',
        'Moov Africa Gabon Telecom a lancé une nouvelle application, Momo Store, permettant d’accéder à une carte électronique pour faciliter les transactions et améliorer ses services auprès des utilisateurs.',
        'https://vxp241.com/2025/06/16/moov-africa-gabon-telecom-lance-sa-e-carte-via-lapplication-momo-store/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '02ea7f90-ab95-437b-a801-f448df643c0c',
        'Échange constructif entre OLIGUI NGUEMA & les déguerpis de Plaine-Orety autour d’un feu de camp',
        'Le président Brice Clotaire Oligui Nguema a effectué une visite nocturne dans la zone de Plaine-Orety pour faire le point sur l’opération de reprise administrative des terrains, notamment suite aux déguerpissements réalisés dans le cadre de cette opération.',
        'https://vxp241.com/2025/06/16/echange-constructif-entre-oligui-nguema-les-deguerpis-de-plaine-orety-autour-dun-feu-de-camp/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b053488-3099-4887-9bca-cd19ace82133',
        'Mayumba : Le gisement de 25 millions de barils de pétrole bientôt en production',
        'Le gisement pétrolier de Bourdon, situé près de Mayumba au large du Gabon, sera bientôt mis en production, avec des réserves estimées à 25 millions de barils.',
        'https://directinfosgabon.com/mayumba-le-gisement-de-25-millions-de-barils-de-petrole-bientot-en-production/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b25a2246-cea1-4669-89e2-4e574b74e5fb',
        'Le Gabon parmi les pays les plus urbanisés d’Afrique selon la Banque mondiale',
        'Le Gabon est l’un des pays africains les plus urbanisés, avec plus de 90 % de sa population vivant en ville, mais cette urbanisation rapide n’a pas encore entraîné une transformation économique significative.',
        'https://directinfosgabon.com/le-gabon-parmi-les-pays-les-plus-urbanises-dafrique-selon-la-banque-mondiale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f33098a-61e3-4d2e-8d77-a7d6251c650a',
        'États-Unis : Trump menace le Gabon d’interdiction de séjour',
        'Les États-Unis envisagent d’étendre une interdiction de séjour à 36 pays, dont le Gabon, ce qui pourrait empêcher les ressortissants gabonais de voyager ou de séjourner dans le pays américain.',
        'https://directinfosgabon.com/etats-unis-trump-menace-le-gabon-dinterdiction-de-sejour/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d8d69a9-fdeb-4a1f-b22b-29901c4663d4',
        'Nö Limit Dance Studio : Soirée féerique !',
        'Lors d’un spectacle au Palais des Sports de Libreville, plus de 200 danseurs, dont certains âgés de seulement 3 ans, ont présenté leurs performances pour célébrer la fin d’année du Nö Limit Dance Studio.',
        'https://gabonactu.com/blog/2025/06/16/no-limit-dance-studio-soiree-feerique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28854909-2a9f-4931-bfe6-a425da6389c7',
        'Plaine Orety : Oligui Nguema nuitamment sur les ruines et face aux sans abris',
        'Brice Clotaire Oligui Nguema s’est rendu en urgence sur les ruines de Plaine Orety pour constater les dégâts et venir en aide aux sans-abris.',
        'https://gabonactu.com/blog/2025/06/16/plaine-orety-oligui-nguema-nuitamment-sur-les-ruines-et-face-aux-sans-abris/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f1d5abe-774f-4136-8230-1b4d4c6741ba',
        'Le Gabon sur la liste noire de 25 nouveaux pays africains interdits d’entrer aux USA',
        'Le Gabon figure parmi une liste de 36 pays, dont 25 africains, pour lesquels l’administration américaine envisage de renforcer les restrictions de voyage.',
        'https://gabonactu.com/blog/2025/06/16/le-gabon-sur-la-liste-de-25-nouveaux-pays-africains-interdits-dentrer-aux-usa/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e7a9393c-bce9-4b75-b2b5-d487c87df40d',
        'La diaspora ivoirienne appelle à une nouvelle candidature d’Alassane Ouattara',
        'La diaspora ivoirienne mobilise ses membres dans plusieurs villes du monde pour soutenir la candidature d’Alassane Ouattara à un nouveau mandat lors du prochain congrès du RHDP à Abidjan.',
        'https://www.gabonreview.com/la-diaspora-ivoirienne-appelle-a-une-nouvelle-candidature-dalassane-ouattara/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '00ec2d13-a8be-4800-bee7-c097346bcf4f',
        'Fonction publique : Pr. Ibinga devise avec les DCRH sur le recrutement !',
        'Le PR Ibinga et la DCRH ont discuté du processus de recrutement dans la fonction publique, soulignant la nécessité de transparence et de modernisation pour améliorer l''efficacité du recrutement des agents.',
        'https://gabonmediatime.com/fonction-publique-pr-ibinga-devise-avec-les-dcrh-sur-le-recrutement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01305738-aba4-477a-ab4e-d820af019a24',
        'CAN 2025 : le Gabon, 11e meilleure nation qualifiée devant la Côte d’Ivoire !',
        'Le Gabon s''est qualifié pour la Coupe d''Afrique des Nations 2025 en remportant une victoire contre la Côte d''Ivoire, ce qui lui permet d’occuper la 11e place du classement des meilleures nations qualifiées.',
        'https://gabonmediatime.com/can-2025-le-gabon-11e-meilleure-nation-qualifiee-devant-la-cote-divoire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a702715-57e8-463d-bfff-f3a0f3b4a494',
        'Gabon : Brice Clotaire Oligui Nguema à la rencontre des déguerpis',
        'Le président bricole une visite auprès des populations déplacées pour leur exprimer son soutien et recueillir leurs témoignages, tout en dénonçant la manipulation politique de leur situation.',
        'https://agpgabon.ga/gabon-brice-clotaire-oligui-nguema-a-la-rencontre-des-deguerpis/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '790ec8a9-efcd-4ebb-93eb-375e1db4c42c',
        'Gabon : le président Oligui Nguema inaugure ce lundi la station de pompage d’eau potable du PK5',
        'Le président gabonais a inauguré une nouvelle station de pompage d’eau potable à PK5 pour améliorer l’approvisionnement en eau des habitants de Libreville et réduire les inégalités.',
        'https://agpgabon.ga/gabon-le-president-oligui-nguema-inaugure-ce-lundi-la-station-de-pompage-deau-potable-du-pk5/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '90194c43-b3ad-48e0-bdcc-6d9492d5b3dd',
        'Voyage aux USA : Libreville dispose de 60 jours pour rassurer Washington sur sa sécurité',
        'Plusieurs pays africains, dont le Gabon, risquent d’être listés par les États-Unis comme sécuritaires pour leurs citoyens à cause de problèmes comme la fraude et la corruption, et disposent de 60 jours pour améliorer leur situation.',
        'https://www.gabonreview.com/voyage-aux-usa-libreville-dispose-de-60-jours-pour-rassurer-washington-sur-sa-securite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'edacfb51-8373-45c7-8757-356cb68344c1',
        'Fonction publique : Pr. Ibinga devise avec les DCRH sur le recrutement !',
        'Une réunion entre la PR Ibinga et la DCRH a porté sur la transparence et le processus de recrutement dans la fonction publique.',
        'https://gabonmediatime.com/fonction-publique-pr-ibinga-devise-avec-les-dcrh-sur-le-recrutement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2964d2fa-108c-4995-a3f8-5eef53f93ea7',
        'CAN 2025 : le Gabon, 11e meilleure nation qualifiée devant la Côte d’Ivoire !',
        'Le Gabon s’est qualifié pour la Coupe d’Afrique des Nations 2025 en se classant 11e, obtenant ainsi une place devant la Côte d’Ivoire.',
        'https://gabonmediatime.com/can-2025-le-gabon-11e-meilleure-nation-qualifiee-devant-la-cote-divoire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '50e1cae1-b281-4ca1-a755-363a08df0310',
        'Gabon/interview de Désirée Rêve Matta, Coordinatrice Générale de la FSCG : ” ANDVA, un levier indispensable pour un Gabon plus fort, plus solidaire et plus proche de ses citoyens “',
        'Désirée Rêve Matta souligne l’importance de créer l’Agence Nationale de Développement de la Vie Associative (ANDVA) pour renforcer la cohésion sociale, la solidarité et rapprocher l’État des citoyens au Gabon.',
        'https://agpgabon.ga/gabon-interview-de-desiree-reve-matta-coordinatrice-generale-de-la-fscg-andva-un-levier-indispensable-pour-un-gabon-plus-fort-plus-solidaire-et-plus-proche-de-ses-citoyens/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb8b9b93-a3d6-40ef-af3a-7f93caff7643',
        'Afrique – États-Unis : Donald Trump veut bannir 25 pays supplémentaires',
        'Aux États-Unis, Donald Trump a annoncé l''ajout de 25 pays africains à la liste des nations dont les citoyens sont soumis à des restrictions d''entrée, renforçant ainsi les mesures migratoires contre plusieurs pays du continent.',
        'https://www.jeuneafrique.com/1697358/politique/afrique-etats-unis-donald-trump-veut-bannir-25-pays-supplementaires/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fdf3956-00c6-4cb0-8c88-129478dd436b',
        'Promotion de la masculinité positive :  sensibilisation sur la lutte contre les violences basées sur le genre',
        'Une campagne d’activités à Port-Gentil vise à sensibiliser à la masculinité positive et à lutter contre les violences faites aux femmes et aux personnes vulnérables.',
        'https://gabonactu.com/blog/2025/06/16/promotion-de-la-masculinite-positive-sensibilisation-sur-la-lutte-contre-les-violences-basees-sur-le-genre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '723bffd3-db21-45a6-8c16-4297e126ca80',
        'Port-Gentil : six petits voyous au gnouf pour association de malfaiteurs',
        'Six jeunes délinquants ont été placés en détention pour avoir commis des vols en groupe, dont certains avec une arme apparente, dans le cadre d’une activité organisée.',
        'https://gabonactu.com/blog/2025/06/16/port-gentil-six-petits-voyous-au-gnouf-pour-association-de-malfaiteurs/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93e2ee66-96f1-437e-8d75-03aed9e765c4',
        'Pétrole & Gaz : Chez Nguema Nguema, BW Energy évoque le gisement de Bourdon estimée à 25 millions de barils',
        'Des responsables de BW Energy ont rencontré le ministre du Pétrole pour évoquer un gisement de pétrole appelé Bourdon, estimé à environ 25 millions de barils.',
        'https://www.gabonreview.com/petrole-gaz-chez-nguema-nguema-bw-energie-evoque-le-gisement-de-bourdon-estimee-a-25-millions-de-barils/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff3a171c-50ba-4d74-9561-3c79f30482c5',
        '"Réponse à la déclaration de M. Raymond Ndong Sima"',
        'L''article restitue une réponse d''un groupe à une déclaration du Premier ministre gabonais, en rectifiant certains faits concernant des accusations liées à des événements politiques, tout en soulignant leur point de vue sur la version officielle.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/reponse-a-la-declaration-de-m-raymond-ndong-sima',
        'Gabonews',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '538a0120-f044-48af-98f2-ed14849c73f3',
        'Pascal Nze Ndong Nze à l''écoute des habitants du Cap Caravane',
        'Le député Pascal Nze Ndong Nze a rencontré les habitants du quartier Cap Caravane pour écouter leurs préoccupations et mieux comprendre leurs conditions de vie.',
        'https://www.gabonews.com/fr/actus/politique/article/pascal-nze-ndong-nze-a-l-ecoute-des-habitants-du',
        'Gabonews',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4ba8c8a-ff5c-40b0-ad92-a0ed9d9abb4e',
        'Déguerpissement : une réponse Présidentielle entre fermeté et humanité',
        'Le président a organisé une réunion avec le gouvernement et des représentants de la société civile pour aborder la controverse autour des opérations de déguerpissement dans le pays.',
        'https://www.gabonews.com/fr/actus/societe/article/deguerpissement-une-reponse-presidentielle-entre',
        'Gabonews',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c94913fb-76b8-44ad-b46c-b1d91fc77be1',
        'Plaine Orety : une politique du bulldozer qui rappelle le cas des compatriotes sauvagement spoliés par le CNEE derrière le stade...',
        'Une politique de destruction systématique de projets ou d''infrastructures est critiquée comme étant arbitraire et négligente, rappelant des cas où des compatriotes ont été spoliés de force, illustrant un mépris pour la justice et le développement.',
        'https://kongossanews.info/plaine-orety-une-politique-du-bulldozer-qui-rappelle-le-cas-des-compatriotes-sauvagement-spolies-par-le-cnee-derriere-le-stade-dagondje/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b790840-471c-4241-a659-cd00fe40bf92',
        'Brice Oligui Nguema en immersion nocturne à Plaine-Oréty : entre réalité terrain et polémiques politiques',
        'Brice Oligui Nguema a effectué une immersion nocturne à Plaine Orey pour montrer sa proximité avec le terrain, tout en étant au centre de polémiques politiques et en restant discret sur ses intentions.',
        'https://kongossanews.info/brice-oligui-nguema-en-immersion-nocturne-a-plaine-orety-entre-realite-terrain-et-polemiques-politiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '889c81ff-0071-4244-b6be-575ee26d5114',
        'Publié le 16 / 06 / 2025',
        'L''article explique que la récupération politique ne doit pas servir à renforcer les divisions ou à exclure certains groupes, mais plutôt à favoriser l’unité et la cohésion nationale.',
        'https://union.sonapresse.com/fr/non-la-recuperation-politique',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab6277e6-9750-49f1-8d39-8a7b5e38b702',
        'Publié le 16 / 06 / 2025',
        'Le délogement des occupants en Guinée soulève des questions sur la légalité, la gestion et la suite à donner pour respecter les droits des citoyens tout en assurant l’intérêt général.',
        'https://union.sonapresse.com/fr/deguerpissement-quelle-est-la-suite',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a15677d3-0f23-4b74-98f2-b9851cc728ab',
        'Publié le 16 / 06 / 2025',
        'L''article explique comment la communication peut échouer lorsqu''elle manque de cohérence, de stratégie ou de compréhension des enjeux, menant à des malentendus et à une perte de crédibilité.',
        'https://union.sonapresse.com/fr/un-naufrage-communicationnel',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f0f0160-77fd-4afe-a298-bae890d91c79',
        'Benjamin Epps : «On ne met pas encore suffisamment de respect sur le rap»',
        'L''artiste gabonais Benjamin Epps souligne l''importance pour les rappeurs de se montrer plus respectueux et responsable, tout en utilisant de nouvelles sonorités dans son dernier album pour faire évoluer le genre.',
        'https://www.liberation.fr/culture/musique/benjamin-epps-on-ne-met-pas-encore-suffisamment-de-respect-sur-le-rap-20250616_VQ5DAWELPNC7TGDYO6S653O3RQ/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '033678cc-7fd0-484f-aa8a-f8fd0d3642fb',
        'PIEPAL : l’eau coule enfin à Libreville grâce au partenariat Gabon-BAD',
        'L''inauguration d''une nouvelle station de pompage à PK5 et d''un réservoir de 10 000 m³, financée par un partenariat entre le Gabon et la BAD, permet d''améliorer significativement l''accès à l''eau potable à Libreville.',
        'https://www.gabonreview.com/piepal-leau-coule-enfin-a-libreville-grace-au-partenariat-gabon-bad/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8083574-70bb-40ce-b987-b23a07421448',
        'Déguerpissements à Libreville : Oligui Nguema, nuitamment sur les ruines avec les victimes',
        'Le président Oligui Nguema s''est rendu discrètement sur le site de l''expulsion et de la démolition des logements à Libreville, en compagnie des victimes, suscitant des commentaires et des débats dans la société.',
        'https://www.gabonreview.com/deguerpissements-a-libreville-oligui-nguema-nuitamment-sur-les-ruines-avec-les-victimes/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31e58778-3016-4b88-b436-c6c7b1ce197e',
        'Plaine Orety : une politique du bulldozer qui rappelle le cas des compatriotes sauvagement spoliés par le CNEE derrière le stade...',
        'Une politique de déblaiement menée de manière brutale rappelle les injustices subies par des compatriotes victimes d’exactions, notamment dans le contexte de projets d’aménagements comme le stade d’Agondjé.',
        'https://kongossanews.info/plaine-orety-une-politique-du-bulldozer-qui-rappelle-le-cas-des-compatriotes-sauvagement-spolies-par-le-cnee-derriere-le-stade-dagondje/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d2cc03f-af56-46e2-9d47-489b28efaaa1',
        'Brice Oligui Nguema en immersion nocturne à Plaine-Oréty : entre réalité terrain et polémiques politiques',
        'Brice Oligui Nguema mène une immersion nocturne à Plain-Orety, suscitant débats et polémiques politiques sur sa présence sur le terrain.',
        'https://kongossanews.info/brice-oligui-nguema-en-immersion-nocturne-a-plaine-orety-entre-realite-terrain-et-polemiques-politiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd9a95531-8d49-4cf0-b376-b370a507c850',
        'Publié le 16 / 06 / 2025',
        'L''article explique que la récupération politique en Afrique limite souvent le développement démocratique, en utilisant la justice et les institutions pour des intérêts personnels plutôt que pour l’intérêt général.',
        'https://union.sonapresse.com/fr/non-la-recuperation-politique',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89528fa9-9fee-4e9c-87c3-e76198601890',
        'Publié le 16 / 06 / 2025',
        'L’article explique la situation d’expulsion des occupants et les actions à venir pour traiter cette problématique au Sénégal, en abordant notamment les démarches légales et les enjeux sociaux liés à ces délogements.',
        'https://union.sonapresse.com/fr/deguerpissement-quelle-est-la-suite',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c625be2-a585-4ea3-9497-44543be84811',
        'Publié le 16 / 06 / 2025',
        'L''article explique comment une mauvaise communication peut entraîner le déclin ou l''échec d''une organisation, en soulignant l''importance d''une stratégie claire et efficace pour préserver sa réputation.',
        'https://union.sonapresse.com/fr/un-naufrage-communicationnel',
        'L''union',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b672cb79-6e6d-483e-b9b1-8a1ca0e3cf56',
        'Libreville : Oligui Nguema inaugure une nouvelle station de pompage au PK5',
        'Une nouvelle station de pompage a été inaugurée à Libreville, capable de produire 57 600 m³ d’eau chaque jour, pour améliorer l’approvisionnement en eau potable dans la ville.',
        'https://gabonactu.com/blog/2025/06/16/libreville-oligui-nguema-inaugure-une-nouvelle-station-de-pompage-au-pk5/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4c83028-d04b-4a0b-b7cd-4b0066d74c5e',
        'Le président de la République aux cotés des sinistrés de Plaine-Orety logés à Ondogho',
        'Le président Brice Clotaire Oligui Nguema a visité et apporté son soutien aux familles évacuées de Libreville, notamment celles logées à Ondogho après avoir été affectées par des sinistres.',
        'https://www.gabonews.com/fr/actus/politique/article/le-president-de-la-republique-aux-cotes-des',
        'Gabonews',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e4c1500-493a-43e1-8dac-597cb8c0c687',
        'Gabon/Logement : Ludovic Megne Ndong met la pression sur les chantiers d’Agondjé et Mindoubé',
        'Le ministre du Logement exhorte les entreprises à accélérer les travaux de construction à Agondjé et Mindoubé pour respecter les délais et répondre à la forte demande en logements.',
        'https://agpgabon.ga/gabon-logement-ludovic-megne-ndong-met-la-pression-sur-les-chantiers-dagondje-et-mindoube/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeb20622-13a5-4c87-bf82-62eaf857059b',
        'Gabon/Santé : l’ONG Gabon AVC sensibilise et dépiste à l’Agence Gabonaise de Presse',
        'Une campagne de sensibilisation et de dépistage sur le diabète et les maladies cérébrovasculaires a été organisée à Libreville pour informer le personnel sur les risques, les symptômes et l''importance d''une détection précoce de ces pathologies.',
        'https://agpgabon.ga/gabon-sante-long-gabon-avc-sensibilise-et-depiste-a-lagence-gabonaise-de-presse/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c92060b1-1551-4ccc-8730-9c00ce85e2da',
        'Gabon/ CEMAC : les Trésors publics en quête de soutenabilité budgétaire à Libreville',
        'La réunion du Cadre permanent de concertation des Trésors publics de la CEMAC à Libreville a porté sur les réformes fiscales et la gestion durable du marché des valeurs du Trésor pour renforcer les finances publiques des pays membres.',
        'https://agpgabon.ga/gabon-cemac-les-tresors-publics-en-quete-de-soutenabilite-budgetaire-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04ef223d-f880-4d9a-b4b3-e0ed0b2ec989',
        'Déguerpis de Plaine-Orety & environs: OLIGUI NGUEMA à Ondogho à l’écoute des sinistrés',
        'Une femme gabonaise a proposé ses appartements en cours de finition pour héberger et soulager les personnes déplacées par les déguerpissements à Plaine-Orety, un geste qui a été salué par le Président de la République.',
        'https://vxp241.com/2025/06/16/deguerpis-de-plaine-orety-environs-oligui-nguema-a-ondogho-a-lecoute-des-sinistres/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a13e5ca-add4-4471-b580-e5540ed52d32',
        'USTM: Assala booste la formation en géoscience',
        'Assala Gabon a offert un don à l’Université des Sciences et Techniques de Masuku (USTM) pour renforcer la formation et la recherche en géosciences, notamment dans le domaine des hydrocarbures.',
        'https://gabonactu.com/blog/2025/06/16/lustm-booste-la-formation-en-geoscience-grace-a-un-don-dassala-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9eeb4ee4-2f52-41ea-8a80-b3c2d06ccc43',
        'Déguerpissement de Plaine Orety : la compassion du Président Oligui Nguema aux sinistrés relogés provisoirement à Ondogho',
        'Le président Oligui Nguema a exprimé sa compassion envers les sinistrés de Plaine Orety, qu''il a visités et qui ont été provisoirement relogés à Ondogho suite à leur évacuation.',
        'https://gabonactu.com/blog/2025/06/16/deguerpissement-de-plaine-orety-la-compassion-du-president-oligui-nguema-aux-sinistres-reloges-provisoirement-a-ondogho/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4162f5d-7fbf-4234-926f-c3f4c466d507',
        'Ndambo d’Or 2025 : Récompense du National Foot 1/2 et les gabonais de l’Étranger',
        'Les sportifs gabonais, qu''ils jouent en championnat national ou à l''étranger, ont été mis à l''honneur lors de la cérémonie du Ndambo d’Or 2025, qui récompense les meilleurs talents du football gabonais.',
        'https://gabonactu.com/blog/2025/06/16/ndambo-dor-2025-recompense-du-national-foot-1-2-et-les-gabonais-de-letranger/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eae68971-4ffd-4a7b-98a4-b78634e69c67',
        'La station de pompage d''eau potable du PK5 inaugurée par le chef de l''Etat',
        'Une nouvelle station de pompage d’eau potable a été inaugurée à Libreville pour améliorer l’approvisionnement en eau dans la ville, en aidant à remplir un réservoir de 10 000 m³ dans le quartier du PK5.',
        'https://www.gabonews.com/fr/actus/politique/article/la-station-de-pompage-d-eau-potable-du-pk5',
        'Gabonews',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ec3fbdf8-1910-40a3-8753-f07edbde86af',
        'Gabon/Accès à l’eau : le chef de l’État met en service la station du PK5',
        'Le président gabonais a officiellement mis en service une nouvelle station de pompage à Libreville pour améliorer l’accès à l’eau potable dans le cadre d’un programme national.',
        'https://agpgabon.ga/gabon-acces-a-leau-le-chef-de-letat-met-en-service-la-station-du-pk5/',
        'AGP',
        'Business Intelligence',
        '2025-06-16T00:00:00.000Z',
        '2025-09-15T23:06:12.457Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

