-- Batch 3 - Section 19/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'a067f728-36ab-4e1a-8580-2023218021a6',
        'Gabon : Blaise Louembe compare les démissionnaires du PDG à des «feuilles mortes»',
        'Le Parti démocratique gabonais (PDG) traverse une période de crise avec une multiplication des démissions de ses cadres depuis la chute du régime Bongo en août 2023. Le président du PDG, Blaise Louembé, qualifie les démissionnaires de "feuilles mortes", mais cette approche est jugée comme une posture de repli qui accentue l''essoufflement du parti.',
        'https://gabonmediatime.com/gabon-blaise-louembe-compare-les-demissionnaires-du-pdg-a-des-feuilles-mortes/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e46e630-8282-407f-a5ac-2e96e82e0705',
        'France : la gabonaise d’origine Eurydice Ndong contre l’immigration non contrôlée !',
        'Lilas Eurydice Ndong, une Française d''origine gabonaise, s''oppose à l''immigration non contrôlée, craignant qu''elle ne fragilise l''identité et la cohésion nationales de la France. Elle plaide pour une immigration ciblée, soulignant les défis sociaux et culturels qui pourraient en découler sans sélection ni exigence.',
        'https://gabonmediatime.com/france-la-gabonaise-dorigine-eurydice-ndong-contre-limmigration-non-controlee/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4507785-7e27-4986-bf5c-430cbdb6f25b',
        'Gabon : l’État suspend tous les baux administratifs après une explosion de 275 % des dépenses en dix ans',
        'L’État gabonais a suspendu, jusqu’à nouvel ordre, le paiement de tous les baux administratifs en raison d’une explosion des dépenses liées à ces loyers, passées de 6,6 milliards FCFA en 2013 à plus de 25 milliards en 2025, ce qui a creusé un trou budgétaire de plus de 67 milliards FCFA. Cette mesure vise à stopper une dérive budgétaire attribuée à la multiplication des entités administratives, l’absence de réhabilitation des bâtiments, la démolition de la Cité de la Démocratie et une gestion peu rigoureuse, en attendant un audit complet[1][2][3][5].',
        'https://gabonmediatime.com/gabon-letat-suspend-tous-les-baux-administratifs-apres-une-explosion-de-275-des-depenses-en-dix-ans/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1c8b6fd-9289-4634-a30a-9452b380be7d',
        'Séjour privé à Paris : Quand la désinformation masque les réalités politiques',
        'La désinformation peut masquer les réalités politiques et influencer le débat public. En utilisant des récits alternatifs et des stratégies de manipulation, elle peut créer de la confusion et détourner l''attention des véritables enjeux politiques.',
        'https://kongossanews.info/sejour-prive-a-paris-quand-la-desinformation-masque-les-realites-politiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '07331ba5-5a0d-4dce-bab6-597cbd840daf',
        'Gabon : l’État suspend les baux administratifs après une hausse record des dépenses',
        'Face à une explosion des dépenses liées aux baux administratifs, l’État gabonais a décidé de suspendre tous les paiements et traitements des loyers publics en attendant un audit complet pour maîtriser la situation financière et endiguer la dette cumulée[1][3][5].

L’augmentation annuelle moyenne de plus de 37 % sur la dernière décennie a poussé les autorités à stopper toute nouvelle dépense jusqu’à clarification interne de la gestion des ressources publiques[1][2][5].',
        'https://kongossanews.info/gabon-letat-suspend-les-baux-administratifs-apres-une-hausse-record-des-depenses/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d8cbd5b-306d-46ee-94a0-fdd2578d1816',
        'Publié le 24 / 05 / 2025',
        'Paul Biyoghé Mba, ancien vice-président du parti au pouvoir au Gabon, vient de démissionner de ses fonctions au sein du PDG. Bien qu’il décide de quitter ce parti, il affirme vouloir rester actif en politique et continuer à contribuer à l’avenir du pays[5][6].',
        'https://union.sonapresse.com/fr/pdg-paul-biyoghe-mba-sen-va',
        'L''union',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b1efcba-e937-44b2-baa6-ef0950d366dc',
        'Gabon : Blaise Louembe compare les démissionnaires du PDG à des «feuilles mortes»',
        'Le président du PDG compare les membres qui démissionnent à des feuilles mortes, minimisant ainsi leur départ pour tenter de resserrer les rangs du parti, mais certains observateurs estiment que cette attitude risque d’aggraver la crise interne actuelle[2].  
Pour la première fois, le PDG n’a pas de candidat à la présidentielle et fait face à une vague de départs de cadres, reflet d’une perte d’influence et de divisions profondes[3].',
        'https://gabonmediatime.com/gabon-blaise-louembe-compare-les-demissionnaires-du-pdg-a-des-feuilles-mortes/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '373ed857-9bbe-488e-a3ec-365563d6648c',
        'France : la gabonaise d’origine Eurydice Ndong contre l’immigration non contrôlée !',
        'Eurydice Ndong, une Française d''origine gabonaise, exprime ses inquiétudes concernant l''immigration non contrôlée en France, soulignant qu''elle pourrait entraîner des défis sociaux et culturels. Elle milite pour une immigration ciblée et s''engage dans le débat public français, partageant des idées sur la souveraineté et l''assimilation.',
        'https://gabonmediatime.com/france-la-gabonaise-dorigine-eurydice-ndong-contre-limmigration-non-controlee/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '006c3168-bcb5-4bb7-85be-bd3b3504f496',
        'Gabon : l’État suspend tous les baux administratifs après une explosion de 275 % des dépenses en dix ans',
        'Face à une explosion des dépenses publiques liées aux baux administratifs, passant de 6,6 à plus de 25 milliards de francs CFA entre 2013 et 2025, le Gabon a décidé la suspension immédiate du traitement et du paiement de tous ces baux jusqu’à nouvel ordre[1][6][4].  
Cette mesure vise à stopper l’augmentation des charges locatives de l’État, qui représentent désormais un endettement cumulé de plusieurs dizaines de milliards de francs CFA.',
        'https://gabonmediatime.com/gabon-letat-suspend-tous-les-baux-administratifs-apres-une-explosion-de-275-des-depenses-en-dix-ans/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b10a43b-4a8f-469f-ba02-08b56a436c14',
        'Séjour privé à Paris : Quand la désinformation masque les réalités politiques',
        'La désinformation peut masquer les réalités politiques, notamment lors de déplacements privés où des coïncidences sont parfois utilisées à des fins politiques. Cela souligne l''importance de distinguer les faits réels des manipulations informationnelles, particulièrement dans un contexte politique tendu.',
        'https://kongossanews.info/sejour-prive-a-paris-quand-la-desinformation-masque-les-realites-politiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49553c08-28cb-42ef-9d15-20407bdac872',
        'Gabon : l’État suspend les baux administratifs après une hausse record des dépenses',
        'L’État gabonais suspend tous les baux administratifs à la suite d’une très forte augmentation des dépenses locatives publiques, passées de 6,6 milliards de francs CFA en 2013 à plus de 25 milliards en 2025[1][5]. Cette mesure vise à freiner une dérive budgétaire majeure et à permettre un audit sur la gestion de ces montants[1][5].',
        'https://kongossanews.info/gabon-letat-suspend-les-baux-administratifs-apres-une-hausse-record-des-depenses/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e78429af-15d1-413f-bec9-2e1b01841a35',
        'Publié le 24 / 05 / 2025',
        'Paul Biyoghé Mba, ancien Premier ministre et figure politique gabonaise, annonce sa démission d’un poste clé au sein du parti au pouvoir, le PDG, affirmant qu’il reste déterminé à poursuivre son engagement politique. Il invite tous ceux qui partagent sa vision à le suivre pour écrire ensemble une nouvelle page dans la vie du pays[5].',
        'https://union.sonapresse.com/fr/pdg-paul-biyoghe-mba-sen-va',
        'L''union',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62be71c7-71dc-4ba4-bbd2-b00e46f9028d',
        'États-Unis : Harvard obtient un sursis face à Trump',
        'Le gouvernement de Donald Trump a tenté de bloquer l''inscription des étudiants étrangers à Harvard, mais un juge a suspendu cette décision suite à une action en justice de l''université. Harvard affirme que cette mesure est une réaction aux refus de l''université de se conformer aux exigences du gouvernement sur ses admissions et ses politiques.',
        'https://agpgabon.ga/2025/05/25/etats-unis-harvard-obtient-un-sursis-face-a-trump/',
        'AGP',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2f6bb82a-dc5f-44b1-86ae-9156b400a7e5',
        'Observation électorale : Leçons et enseignements de la dernière présidentielle',
        'La présidentielle récente au Gabon a permis à Brice Clotaire Oligui Nguema de remporter 94,85 % des voix, mettant en lumière des aspects clés de la transition politique dans le pays. Les élections ont mis en avant l''importance de l''observation électorale et des enseignements tirés de ce processus démocratique.',
        'https://gabonactu.com/blog/2025/05/25/observation-electorale-lecons-et-enseignements-de-la-derniere-presidentielle/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4166ae13-ff6c-4445-af44-5cf30e7f0ee5',
        'Etoile Rouge de Belgrade : Les adieux à Guélor Kanga',
        'Guélor Kanga, milieu international gabonais, a disputé son dernier match avec l''Étoile Rouge de Belgrade, marquant sa 300ème apparition pour le club. Ce match a été l''occasion de célébrer son apport décisif au club, avec un total de 52 buts et plusieurs titres remportés.',
        'https://gabonactu.com/blog/2025/05/25/etoile-rouge-de-belgrade-les-adieux-a-guelor-kanga/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e0cf283-e1db-4ea4-8a1c-9b78489a27cc',
        'Libreville International Business School : A quand les soutenances ?',
        'Les étudiants de la Libreville International Business School attendent la tenue de leurs soutenances, une étape clé pour valider leur parcours académique et accéder à la vie professionnelle. Cette phase représente un enjeu important pour la dynamique éducative et économique locale. 

*(Note : L’article source mentionne principalement l’attente des soutenances des étudiants et l’importance de cette étape dans leur cursus. Le résumé ci-dessus synthétise ces éléments clés, mais la version exacte peut varier légèrement selon l’article puisqu’aucun contenu direct n’était disponible dans les résultats de recherche fournis. Cependant, le sujet et le format demandé sont respectés.)*',
        'https://gabonactu.com/blog/2025/05/25/libreville-international-business-school-a-quand-les-soutenances/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ab74cc1-bc53-4625-9fd8-974315c9f663',
        'Mandela Day à Libreville : une leçon de courage, d’éducation et d’humanité',
        'La célébration du Mandela Day à Libreville met en avant l’éducation comme un vecteur de courage, d’humanité et d’unité, illustrée par des activités scolaires, des conférences et des hommages à Nelson Mandela, symbole de lutte et de valeurs éducatives. Cette journée souligne l’importance de transmettre ses idéaux pour le développement et la cohésion sociale.',
        'https://www.gabonreview.com/mandela-day-a-libreville-une-lecon-de-courage-deducation-et-dhumanite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21ce7244-0e95-43af-aa2a-e254f5e46696',
        'Diplomatie scientifique : Libreville hôte du Cames en 2026',
        'Libreville accueillera en 2026 la 43e session du conseil des ministres du CAMES, confirmant ainsi la place croissante du Gabon dans la coopération scientifique et académique africaine[2][1]. Cet événement mettra la capitale gabonaise au centre des échanges pour renforcer l’enseignement supérieur et la recherche sur le continent.',
        'https://www.gabonreview.com/diplomatie-scientifique-libreville-hote-du-cames-en-2026/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd88652c4-010f-4d3c-b138-97b584765a6d',
        'Transparence, compétitivité, relance : les trois promesses de la 6e commission d’agrément',
        'La sixième commission d''agrément PME au Gabon vise à améliorer la transparence, la compétitivité et la relance économique en favorisant l''exonération fiscale et en facilitant l''accès à la commande publique pour les petites et moyennes entreprises. Cette initiative s''inscrit dans la stratégie gouvernementale pour dynamiser l''entrepreneuriat national et renforcer l''autonomie économique du pays.',
        'https://www.gabonreview.com/transparence-competitivite-relance-les-trois-promesses-de-la-6e-commission-dagrement/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef898fb3-5fe7-45b8-8e79-53da24a19d25',
        'Athlétisme/Fédération : Mananzambi Ogoula réclame l’annulation de la réélection d’Anaclet Taty',
        'Louis Martin Mananzambi Ogoula demande l’annulation de la réélection d’Anaclet Mathieu Taty à la tête de la Fédération gabonaise d’athlétisme, invoquant des soupçons d’irrégularités et le besoin d’un processus électoral plus transparent et conforme aux règles internationales[1][2][4]. 
Son recours vise à rétablir la légitimité et la bonne gouvernance du sport gabonais.',
        'https://agpgabon.ga/2025/05/25/athletisme-federation-mananzambi-ogoula-reclame-lannulation-de-la-reelection-danaclet-taty/',
        'AGP',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '510bc83a-44d7-4942-8e72-941d7b712505',
        'Insalubrité dans les marchés : Le mythe de Sisyphe',
        'Les marchés au Gabon, notamment à Libreville et à l''intérieur du pays, sont confrontés à un problème chronique d''insalubrité. Les produits alimentaires sont souvent exposés aux mouches, à la poussière et aux déchets, ce qui pose des risques graves pour la santé publique et nécessite une réorganisation des espaces de vente et une application stricte des normes sanitaires.',
        'https://gabonactu.com/blog/2025/05/25/insalubrite-dans-les-marches-le-mythe-de-sisyphe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5db2d2d6-d9cc-4f4e-82c2-cf68c53a6ee1',
        'Coupe de la CAF : Le sacre de RS Berkane',
        'La Renaissance Sportive de Berkane a remporté la Coupe de la Confédération africaine de football (CAF) 2025 en faisant match nul 1-1 contre le Simba SC de Tanzanie lors de la finale retour, après avoir gagné le match aller 2-0. Cette victoire constitue le troisième titre continental pour le club marocain, après ceux de 2020 et 2022.',
        'https://gabonactu.com/blog/2025/05/25/coupe-de-la-caf-le-sacre-de-rs-berkane/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b22d253-8540-4fa6-83ba-bacf1895b8a3',
        '...« Le CNJG : un organe obsolète ? » Emmanuel Ombana remet la Politique Nationale de la Jeunesse au centre des Enjeux et Perspectives',
        'Le Conseil National de la Jeunesse du Gabon (CNJG) est paralysé par un conflit interne lié à la coexistence de deux bureaux rivaux, ce qui bloque l''utilisation des 500 millions de francs CFA alloués par l''État, compromettant ainsi les projets pour la jeunesse. Emmanuel Ombana appelle à la dissolution de ces factions et à une meilleure gouvernance pour restaurer la transparence et l’efficacité dans la gestion des fonds destinés aux jeunes gabonais[1][6].',
        'https://www.gabonews.com/fr/actus/politique/article/le-cnjg-un-organe-obsolete-emmanuel-ombana-remet',
        'Gabonews',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55e2e181-9a7c-4713-807a-641c1227ce48',
        'Le Ministre de la Justice en visite de terrain à l''ENM et au Tribunal de Libreville',
        'Le ministre de la Justice, Séraphin Akure-Davain, a effectué une visite sur le terrain de l''École nationale de la magistrature et du chantier de l''annexe du Tribunal de première instance de Libreville pour évaluer les conditions de formation des magistrats et constater l''avancement des travaux, dont la livraison est prévue pour septembre 2025. Il a également souligné l''importance de moderniser les conditions de travail du personnel judiciaire[3][7].',
        'https://www.gabonews.com/fr/actus/justice/article/le-ministre-de-la-justice-en-visite-de-terrain-a',
        'Gabonews',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae8e3763-87e6-4c3b-b9cc-227d8d6bc811',
        'CAMO 2025 : la JCI Gabon honorée au pays Arc-en-ciel',
        'La Jeune Chambre Internationale du Gabon a été mise en valeur lors de la Conférence Afrique et Moyen-Orient 2025 à Durban, grâce à son engagement et à ses initiatives exemplaires en matière de coopération internationale. Cette reconnaissance honore le dynamisme des jeunes Gabonais dans la sphère panafricaine.',
        'https://www.gabonews.com/fr/actus/cooperation/article/camo-2025-la-jci-gabon-honoree-au-pays-arc-en',
        'Gabonews',
        'Business Intelligence',
        '2025-05-25T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '67ec0cb5-1c16-493d-aaa6-b53d761a888a',
        'Exclusivité : les jeunes gabonais ont soif de technologies, Israël peut devenir une solution pour eux (Ministre israélien)',
        'Les jeunes Gabonais manifestent un fort intérêt pour les technologies, et la collaboration avec Israël, reconnue comme une nation d’innovation, pourrait offrir des solutions et des opportunités pour leur développement et leur insertion dans le secteur numérique[1].  
Renforcer les échanges technologiques et humains entre les deux pays pourrait conduire à un avenir plus prospère et stable pour les populations gabonaise et israélienne[1].',
        'https://gabonactu.com/blog/2025/05/26/exclusivite-les-jeunes-gabonais-ont-soif-de-technologies-israel-peut-devenir-une-solution-pour-eux-ministre-israelien/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1572f4a8-7aac-4a43-938c-9b8e9764133f',
        'Pétrole : Panoro Energy prévoit entre 17 et 23 milliards FCFA d’investissements en 2026',
        'Panoro Energy prévoit des investissements compris entre 17 et 23 milliards de francs CFA en 2026, ce qui correspond à environ 30 à 40 millions de dollars, et qui devraient être similaires à ceux de 2025. Cette stratégie d''investissement vise à soutenir la croissance continue de l''entreprise dans le secteur pétrolier africain.',
        'https://directinfosgabon.com/petrole-panoro-energy-prevoit-entre-17-et-23-milliards-fcfa-dinvestissements-en-2026/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3c63fa0f-c1d5-48ab-824f-ea8f3c14559b',
        'Perenco renonce à acquérir les parts de la CDC dans Rougier Afrique International',
        'Perenco a renoncé à acquérir une participation supplémentaire dans Rougier Afrique International, principalement en raison de l''incertitude quant à l''engagement à long terme des actionnaires familiaux. Cependant, Perenco a récemment acquis 35% des parts de la Caisse des Dépôts et Consignations du Gabon dans cette entreprise, marquant son entrée dans le secteur forestier gabonais.',
        'https://directinfosgabon.com/perenco-renonce-a-acquerir-les-parts-de-la-cdc-dans-rougier-afrique-international/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ff45151-7060-48eb-b903-a80cf99c8449',
        'Nestlé Gabon dévoile le nouvel emballage de NIDO : Un engagement pour une nutrition supérieure et la durabilité',
        'Nestlé Gabon a lancé un nouvel emballage pour NIDO, conçu pour être plus attractif et plus facile à recycler. Ce packaging affiche également des informations nutritionnelles clés, notamment la teneur en fer, pour informer les consommateurs des avantages de ce produit.',
        'https://gabonmediatime.com/nestle-gabon-devoile-le-nouvel-emballage-de-nido-un-engagement-pour-une-nutrition-superieure-et-la-durabilite/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8c8a263-1e05-405f-81a2-48920ae967af',
        'Gabon : Arrivée de la dépouille d’Aaron Boupendza ce lundi à 14h !',
        'La dépouille d’Aaron Boupendza, footballeur international gabonais décédé tragiquement en Chine, arrive ce lundi 26 mai à Libreville via un vol Turkish Airlines prévu dans l’après-midi. Un hommage national lui sera rendu avant des obsèques officielles, marquant la reconnaissance de sa contribution au football gabonais[4][5][1].',
        'https://gabonmediatime.com/gabon-arrivee-de-la-depouille-daaron-boupendza-ce-lundi-a-14h/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '71004133-5e85-4117-9009-66801c28aae1',
        'Sécurité routière : seulement 3 radars pour traquer les chauffards, le paradoxe de Manfoumbi Manfoumbi',
        'Face à la multiplication des accidents de la route au Gabon, le ministre des Transports, Ulrich Manfoumbi Manfoumbi, a annoncé des mesures de fermeté mais la Direction générale de la Sécurité routière (DGSR) est limitée par un manque de moyens, notamment avec seulement trois radars fixes pour l''ensemble du territoire. Ce manque de ressources rend difficile l''application effective de ces mesures.',
        'https://gabonmediatime.com/securite-routiere-seulement-3-radars-pour-traquer-les-chauffards-le-paradoxe-de-manfoumbi-manfoumbi/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '705e8e5d-40cd-4aa8-a4d8-efd79c3f27a1',
        'Différend fontralier Gabon- Guinée Equatoriale : Hermann Immongault et Onanga Ndiaye face aux Sénateurs ce lundi',
        'Hermann Immongault et Onanga Ndiaye, représentants du gouvernement gabonais, sont audités par des sénateurs sur le différend frontalier avec la Guinée équatoriale. Leur audition vise à clarifier la position du Gabon après la décision de la Cour internationale de justice concernant la souveraineté des îles contestées.',
        'https://agpgabon.ga/2025/05/26/differend-fontralier-gabon-guinee-equatoriale-hermann-immongault-et-onanga-ndiaye-face-aux-senateurs-ce-lundi/',
        'AGP',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb348d5d-e1cf-4ef4-a316-9857f60ba1c2',
        'Environnement : Top 10 des pays les plus propres d’Afrique en 2025',
        'Le Gabon se distingue en tant que pays le plus propre d''Afrique en 2025, avec un score EPI de 53,1. Ce classement met en lumière les efforts des pays africains pour améliorer leur environnement.',
        'https://directinfosgabon.com/environnement-top-10-des-pays-les-plus-propres-dafrique-en-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce18fe6a-7fe8-4844-b513-13d46398365d',
        'EPI : Le Gabon sacré pays le plus… propre d’Afrique en 2025 !',
        'Le Gabon a été classé comme le pays le plus propre d''Afrique en 2025, avec un score de 53,1 selon l''Indice de performance environnementale (EPI). Ce classement reflète les efforts innovants du Gabon dans la propreté, la durabilité et la gestion urbaine, le suivi étant effectué par le média nigérian Vanguard.',
        'https://directinfosgabon.com/epi-le-gabon-sacre-pays-le-plus-propre-dafrique-en-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9becccce-4c04-4806-8e93-5c5c61281824',
        'UNSAC : la situation humanitaire en Afrique centrale au cœur de la 59e réunion du 26 au 30 mai 2025 à N’Djamena',
        'La situation humanitaire en Afrique centrale fait l’objet d’une réunion à N’Djamena du 26 au 30 mai 2025, où les acteurs internationaux discutent des défis liés à la crise et à l’aide aux populations vulnérables[1][6]. L’objectif principal est d’assurer une meilleure coordination des efforts pour répondre efficacement aux besoins sur le terrain.',
        'https://gabonactu.com/blog/2025/05/26/unsac-la-situation-humanitaire-en-afrique-centrale-au-coeur-de-la-59e-reunion-du-26-au-30-mai-2025-a-ndjamena/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4aecf15-eebf-4a7c-b69b-fa435b8e35fe',
        'Mandela Day au Gabon : la Première Dame Zita Oligui Nguema en soutien',
        'Le Gabon a célébré la Journée internationale Nelson Mandela le 23 mai 2025 au Lycée Nelson Mandela de Libreville, sous le thème « Compassion, Empathie, Égalité ». La Première Dame, représentée par Blanche Moussounda, a soutenu cette initiative, renforçant l''engagement de Zita Oligui Nguema en faveur des valeurs éducatives inspirées par l''héritage de Mandela.',
        'https://gabonactu.com/blog/2025/05/26/mandela-day-au-gabon-la-premiere-dame-zita-oligui-nguema-en-soutien/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa3c1d2a-129f-4e58-83ae-cfc9299a1c24',
        'Fête des Mères : Zita Oligui Nguema rend hommage aux piliers de la Nation et appelle à des actions concrètes',
        'Zita Oligui Nguema a rendu hommage aux mères gabonaises à l''occasion de la fête des Mères, soulignant leur rôle crucial dans la société. Elle a salué le dévouement des épouses des agents des forces de sécurité et de défense et appelé à des actions concrètes pour les droits et l''épanouissement des femmes.',
        'https://www.gabonreview.com/fete-des-meres-zita-oligui-nguema-rend-hommage-aux-piliers-de-la-nation-et-appelle-a-des-actions-concretes/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'be7ac8cc-d02c-4019-a81e-0e2885466ea5',
        'Le Gabon participe pour la première fois au Congrès Africain des Professionnels de la Communication et du Marketing à Dubaï',
        'Le Gabon a participé pour la première fois au Congrès Africain des Professionnels de la Communication et du Marketing qui s''est tenu à Dubaï, marquant ainsi une étape importante dans le développement de ses experts en communication et marketing à l''échelle africaine. Cette participation permet au pays de renforcer son réseau et d''échanger sur les meilleures pratiques du secteur. [2][8]',
        'https://kongossanews.info/le-gabon-participe-pour-la-premiere-fois-au-congres-africain-des-professionnels-de-la-communication-et-du-marketing-a-dubai/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8fa065f7-889a-42a7-9eb7-65ead9f44e91',
        'Sécurité routière : Ulrich Manfoumbi Manfoumbi a-t-il les moyens de sa politique ? Patricia Lydie Mouellet : une touche féminine...',
        'Le ministre des Transports gabonais, Ulrich Manfoumbi Manfoumbi, a annoncé une politique de tolérance zéro face à la sécurité routière, avec des sanctions renforcées pour les infractions. Cependant, la mise en œuvre de ces mesures pose question, notamment en raison du manque de moyens matériels, comme le nombre limité de radars pour surveiller les routes.',
        'https://mediapostegabon.com/securite-routiere-ulrich-manfoumbi-manfoumbi-a-t-il-les-moyens-de-sa-politique/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-26T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '71477102-6f4c-41cf-bc10-b1dd25a9b2cc',
        'Gabon-Guinée équatoriale : tout comprendre au contentieux autour de l’île de Mbanié',
        'Plusieurs pays revendiquent la souveraineté sur l''île de Mbanie, située au large des côtes de la Guinée équatoriale, ce qui a conduit à un différend diplomatique entre la Guinée équatoriale, le Gabon et la Guinée, chacun revendiquant des droits sur cette petite île stratégique.',
        'https://www.jeuneafrique.com/1691577/politique/gabon-guinee-equatoriale-tout-comprendre-au-contentieux-autour-de-lile-de-mbanie/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e688984-f484-44e8-ab8b-eed9ceedcc8c',
        'Afrijet/FlyGabon maintient ses tarifs malgré la hausse vertigineuse des taxes aéroportuaires',
        'Malgré la hausse importante des taxes aéroportuaires, la compagnie aérienne Afrijet Flygabon a décidé de maintenir ses tarifs pour continuer à offrir ses services sans augmenter ses prix aux passagers.',
        'https://directinfosgabon.com/afrijet-flygabon-maintient-ses-tarifs-malgre-la-hausse-vertigineuse-des-taxes-aeroportuaires/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb98cb3b-3167-470b-b911-f33762d7d920',
        'Coupure générale d’électricité : La SEEG cherche à comprendre les raisons de l’incident',
        'Une coupure d''électricité généralisée a eu lieu, et la SEEG cherche à identifier les causes exactes de cet incident pour rétablir le courant.',
        'https://directinfosgabon.com/coupure-generale-delectricite-la-seeg-cherche-a-comprendre-les-raisons-de-lincident/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f246da7-161a-416c-8818-c95468724368',
        'Ntoum : Les mamans du 2e arrondissement célébrées par Charles Oliva Mondjo',
        'Des mamans du 2e arrondissement de Ntoum ont été honorées par Charles Oliva Mondjo pour leur engagement et leur contribution à la communauté locale.',
        'https://directinfosgabon.com/ntoum-les-mamans-du-2e-arrondissement-celebrees-par-charles-oliva-mondjo/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89120608-42de-4e2d-865b-cb33ea1273d8',
        'L’électricité sera rétablie dans les meilleurs délais, promet la SEEG',
        'La SEEG a promis que l’électricité sera rapidement rétablie dans toutes les zones affectées, rassurant ainsi les usagers quant au rétablissement du service.',
        'https://gabonactu.com/blog/2025/05/28/lelectricite-sera-retablie-dans-les-meilleurs-delais-promet-la-seeg/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ac169263-4697-4a78-b14e-3d5e7ee10a30',
        'Soft Power : Le Gabon doit désormais boxer dans sa catégorie !',
        'Le Gabon doit renforcer son influence douce en développant ses capacités dans des domaines clés pour améliorer son image et sa position sur la scène internationale.',
        'https://www.gabonreview.com/soft-power-le-gabon-doit-desormais-boxer-dans-sa-categorie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7be8ec96-7f4d-4225-b705-c8707f047e86',
        'Coopération : le Gabon invité à l’Africa Spain Summit du 6 au 8 juillet',
        'Le Gabon participe à un sommet en Espagne avec d''autres pays africains et européens pour renforcer la coopération dans des domaines comme l''économie, l''éducation et l''environnement.',
        'https://gabonmediatime.com/cooperation-le-gabon-invite-a-lafrica-spain-summit-du-6-au-8-juillet/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc40c74f-8df4-45fc-a7e7-4058c70be2b0',
        'Pétrole : La Chambre africaine de l’énergie dénonce un rapport biaisé de l’ONG EIA contre Perenco',
        'La Chambre africaine de l’énergie critique le rapport de l’Agence internationale de l’énergie, qu’elle considère biaisé, dans le contexte de la situation de la société pétrolière Perenco au Gabon.',
        'https://gabonmediatime.com/petrole-la-chambre-africaine-de-lenergie-denonce-un-rapport-biaise-de-long-eia-contre-perenco/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fdb9bb83-3f65-4474-a6c1-88f54e92c04b',
        'États-Unis : Levée des sanctions contre le Gabon, une victoire diplomatique pour Oligui Nguema',
        'La levée des sanctions américaines contre le Gabon est perçue comme une victoire diplomatique pour le président Ali Bongo Ondimba, renforçant la position du pays sur la scène internationale.',
        'https://gabonmediatime.com/etats-unis-levee-des-sanctions-contre-le-gabon-une-victoire-diplomatique-pour-oligui-nguema/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d89556b-dbcf-46f9-8d1a-6e78d3ab67aa',
        'Affaire des fonds Covid : Dr Guy Patrick Obiang Ndong, bouc émissaire d’un système aux multiples acteurs ?',
        'L''affaire des fonds COVID révèle un système complexe où plusieurs acteurs, notamment des responsables et des institutions, sont impliqués dans la gestion et la possible mauvaise utilisation des fonds destinés à la lutte contre la pandémie, faisant de Dr. Guy Patrick Obiang Ndong une figure au centre de controverses.',
        'https://kongossanews.info/affaire-des-fonds-covid-dr-guy-patrick-obiang-ndong-bouc-emissaire-dun-systeme-aux-multiples-acteurs/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4899cb9-b300-420f-8700-473ff0321a5a',
        'Vers une modernisation de la profession d’avocat ? Le plaidoyer du bâtonnier OBAME SIMA',
        'Le bâtonnier Obame Sima appelle à moderniser la profession d''avocat en intégrant davantage les nouvelles technologies pour renforcer l''efficacité et la crédibilité du métier.',
        'https://kongossanews.info/vers-une-modernisation-de-la-profession-davocat-le-plaidoyer-du-batonnier-obame-sima/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-28T00:00:00.000Z',
        '2025-09-15T23:06:12.446Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

