-- Batch 6 - Section 15/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'dfe3deae-d97a-41a4-9a77-35981d88fb37',
        'Gabon/Nyanga/Politique : le Vice-Président de la République attendu à Tchibanga',
        'Le Vice-Président de la République, Dr Séraphin Moundounga, se rendra à Tchibanga du 1er au 3 août pour préparer la Journée nationale de la Libération et rencontrer les autorités locales et socio-professionnelles de la région.',
        'https://agpgabon.ga/gabon-nyanga-politique-le-vice-president-de-la-republique-attendu-a-tchibanga/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ff45a66-1b9a-45a4-8a2a-1bbc9e375c27',
        'Diplomatie : Séraphin Moundounga à Mongomo et Brazzaville',
        'Le Vice-Président gabonais, Séraphin Moundounga, a effectué une visite officielle à Mongomo en Guinée-Équatoriale et à Brazzaville au Congo, où il a rencontré les dirigeants pour discuter de la coopération entre les pays et des enjeux de la région d’Afrique centrale.',
        'https://agpgabon.ga/diplomatie-seraphin-moundounga-a-mongomo-et-brazzaville/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ac1fd30-982e-4eec-9c05-78a6468c537a',
        'Publié le 31 / 07 / 2025',
        'Bilie Nze, ancien secrétaire général du Conseil économique, social et environnemental, envisage de quitter ses fonctions pour se lancer dans la politique, ce qui pourrait bouleverser le paysage institutionnel au Cameroun.',
        'https://union.sonapresse.com/fr/quitus-de-la-cour-des-comptes-bilie-nze-vers-une-sortie-de-piste',
        'L''union',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2f1a939b-8ae8-4d64-9ab6-26184000811d',
        'Publié le 31 / 07 / 2025',
        'La Cour des comptes exige désormais que les anciens candidats à certains concours présentent un quitus confirmant leur régularité fiscale, ce qui peut éliminer leur candidature.',
        'https://union.sonapresse.com/fr/quitus-de-la-cour-des-comptes-une-exigence-eliminatoire-pour-les-anciens-candidats-la',
        'L''union',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dde3feff-5363-4f75-86f2-8f332c6e101e',
        'Publié le 31 / 07 / 2025',
        'Le partenariat entre le Gabon et la Turquie vise à accélérer le développement économique et technologique du pays en renforçant la coopération dans divers secteurs stratégiques.',
        'https://union.sonapresse.com/fr/gabon-turquie-le-coup-daccelerateur',
        'L''union',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48db6010-0083-47a4-bc8a-b8866d6e7235',
        'Potasse de la Banio : Millennial Potash mobilise 4 milliards de FCFA sur les marchés',
        'Une société canadienne a levé près de 4,1 milliards de francs CFA pour développer son projet d''exploitation de potasse à Banio, dans le sud du Gabon.',
        'https://directinfosgabon.com/potasse-de-la-banio-millennial-potash-mobilise-4-milliards-de-fcfa-sur-les-marches/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6587f51d-72b7-4f25-9253-fd99aa0496c9',
        'Escroquerie par mobile : Un Gabonais sur deux ciblé en 2024',
        'Près de la moitié des adultes gabonais ont reçu en 2024 un appel ou un SMS frauduleux, ce qui montre que la sensibilisation et la prévention contre les escroqueries par mobile sont indispensables dans le pays.',
        'https://directinfosgabon.com/escroquerie-par-mobile-un-gabonais-sur-deux-cible-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49c69856-f19f-41e0-840f-cff6471d5783',
        'Grand Prix national de l’Entrepreneuriat 2025 : Plus de 1300 candidats pour 10 lauréats',
        'Plus de 1 300 candidats ont concouru pour seulement 10 places de lauréats lors de la première édition du Grand Prix national de l’entrepreneuriat au Gabon, lancée en juillet 2025 pour valoriser les meilleures start-ups du pays.',
        'https://directinfosgabon.com/grand-prix-national-de-lentrepreneuriat-2025-plus-de-1300-candidats-pour-10-laureats/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8131d393-64d3-4187-b144-21a9ae6c3092',
        'SEEG : Pas de perturbations majeures sur le réseau électrique',
        'Le communiqué indique qu''il n''y aura pas de perturbations majeures sur le réseau électrique du Grand Libreville dans un futur proche.',
        'https://gabonactu.com/blog/2025/08/01/seeg-pas-de-perturbations-majeures-sur-le-reseau-electrique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7951333a-8ad9-4004-bd45-6f17b6d510ba',
        'Protection des données à caractère personnel : Le terrain après la pédagogie',
        'L''Autorité de protection des données intensifie ses contrôles sur le terrain pour assurer la protection des informations personnelles dans le secteur éducatif et professionnel.',
        'https://gabonactu.com/blog/2025/08/01/protection-des-donnees-a-caractere-personnel-de-la-pedagogie-au-travail-de-terrain/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91689ca4-5b9a-49e5-86c3-2caa52e8e7d3',
        'Affaire Rinaldi : cinq ans après, le silence des coupables et une hypothèse équato-guinéenne troublante',
        'Cinq ans après la disparition du petit Rinaldi, la justice a condamné des suspects sans révéler où se trouve l’enfant, une hypothèse selon laquelle il aurait été transféré en Guinée équatoriale alimentant les interrogations.',
        'https://www.gabonreview.com/affaire-rinaldi-cinq-ans-apres-le-silence-des-coupables-et-une-hypothese-equato-guineenne-troublante/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0af94c76-f1d7-473f-97b0-c8e85f0b44fa',
        'Après l’A320, Fly Gabon se dote d’un nouvel ATR flambant neuf',
        'Fly Gabon a récemment reçu un nouvel avion ATR 42-500, en plus de l''Airbus A320 déjà acquis, afin de renforcer sa flotte aérienne.',
        'https://directinfosgabon.com/apres-la320-fly-gabon-se-dote-dun-nouvel-atr-flambant-neuf/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd4b2078-8bfd-40d0-acb9-6dbd390c46fa',
        'Pétrole : Quand le marché hésite, le Gabon doit avancer',
        'Face à la stabilité récente des prix du pétrole, le Gabon doit continuer à évoluer et à s''adapter malgré l''hésitation du marché, afin d''assurer son développement économique.',
        'https://directinfosgabon.com/petrole-quand-le-marche-hesite-le-gabon-doit-avancer/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '967cab05-85a8-4e43-bac0-00eaa3327837',
        'Présidence de la FEGAHAND : La tutelle a-t-elle choisi son camp ?',
        'L''organisation de l’élection à la FEGAHAND soulève des tensions et des questions sur une possible ingérence ou favoritisme de la tutelle dans le choix du camp de certains candidats.',
        'https://gabonactu.com/blog/2025/08/01/presidence-de-la-fegahand-la-tutelle-a-t-elle-choisi-son-camp/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a9716ef-7324-4b06-a70d-35d1b4e899ef',
        'FlyGabon renforce sa flotte avec un nouvel ATR 42-500 baptisé «Mayumba»',
        'FlyGabon a acquis un nouvel avion ATR 42-500 baptisé « Mayumba » pour moderniser et développer le transport aérien au Gabon.',
        'https://www.gabonreview.com/fly-gabon-renforce-sa-flotte-avec-un-nouvel-atr-42-500-baptise-mayumba/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e8ada65-6a74-43d2-803e-05ea65471bb2',
        'AFG 2025 : les femmes gabonaises sous les projecteurs du mérite',
        'Une cérémonie à Libreville a mis en lumière treize femmes gabonaises exceptionnelles, reconnues pour leur leadership et leur engagement, lors de la première édition des Awards de la Femme Gabonaise.',
        'https://www.gabonreview.com/afg-2025-les-femmes-gabonaises-sous-les-projecteurs-du-merite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd62e5d91-4e36-430a-b15a-6aa093badb74',
        'Finances publiques : Oyima ferme le robinet des arrangements fiscaux',
        'Le gouvernement gabonais met fin aux arrangements fiscaux spéciaux pour renforcer la transparence et assurer une meilleure gestion des finances publiques.',
        'https://gabonmediatime.com/finances-publiques-oyima-ferme-le-robinet-des-arrangements-fiscaux/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9defa431-95d0-4595-8480-db8e3e5f5845',
        'Législatives et locales : 4 candidats à la présidentielle appellent au réaménagement du calendrier électoral',
        'Quatre candidats à la présidentielle en Guinée demandent un réaménagement du calendrier électoral, notamment le report des élections législatives et locales.',
        'https://gabonmediatime.com/legislatives-et-locales-4-candidats-a-la-presidentielle-appellent-au-reamenagement-du-calendrier-electoral/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c29924e1-84ac-4069-bfa1-c8f3a545cb1f',
        'Gabon : des ambitions économiques démesurées pour un Etat prédateur',
        'L''article critique l''ambition économique démesurée du gouvernement gabonais, la qualifiant de prédatrice et risquée pour la stabilité du pays.',
        'https://gabonmediatime.com/gabon-des-ambitions-economiques-demesurees-pour-un-etat-predateur/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f9f9107-85b0-451f-bfca-d8e2c1a7bb45',
        'Hommage à Atatürk : le Président Oligui Nguema s’incline devant la mémoire du fondateur de la République turque',
        'Le président Oligui Nguema a rendu hommage à Atatürk, le fondateur de la République turque, en se souvenant de son rôle important dans la construction d''une nation moderne.',
        'https://kongossanews.info/hommage-a-ataturk-le-president-oligui-nguema-sincline-devant-la-memoire-du-fondateur-de-la-republique-turque/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9fa2fe37-2493-4278-afc8-7e5ffd40a3e1',
        'Gabon–Turquie : découvrez quelques accords stratégiques signés à Ankara pour une coopération renforcée',
        'Trois accords stratégiques ont été signés entre le Gabon et la Turquie pour renforcer leur coopération dans les domaines économique, éducatif et de la jeunesse.',
        'https://kongossanews.info/gabon-turquie-decouvrez-quelques-accords-strategiques-signes-a-ankara-pour-une-cooperation-renforcee/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'acae2e42-8761-4c5e-a37d-4c12de246789',
        'Championnats du monde de natation : Noélie Lacour termine 4e de sa série',
        'Noélie Lacour, nageuse gabonaise de 19 ans, a terminé 4e dans sa série du 50 mètres papillon en améliorant son record national, et elle va maintenant se préparer pour le 50 mètres nage libre lors des Championnats du monde.',
        'https://agpgabon.ga/championnats-du-monde-de-natation-noelie-lacour-termine-4e-de-sa-serie/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b0f6056-5f4b-4998-834d-aad10388a637',
        'OLIGUI NGUEMA scelle un partenariat stratégique avec la République de Turquie',
        'Le Gabon et la Turquie ont renforcé leur partenariat en signant huit accords de coopération, illustrant leur volonté commune de diversifier leurs relations et d''attirer de nouveaux investissements.',
        'https://vxp241.com/2025/08/01/oligui-nguema-scelle-un-partenariat-strategique-avec-la-republique-de-turquie/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '502c905e-ffbe-416d-87c3-4546f4de3cb2',
        'Finances publiques : Oyima ferme le robinet des arrangements fiscaux',
        'Le gouvernement gabonais, par la voix d’Oyima, annonce la fin des arrangements fiscaux spéciaux pour renforcer la transparence et la gestion des finances publiques.',
        'https://gabonmediatime.com/finances-publiques-oyima-ferme-le-robinet-des-arrangements-fiscaux/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '02490761-de20-45e9-af0e-0e8950050b55',
        'Législatives et locales : 4 candidats à la présidentielle appellent au réaménagement du calendrier électoral',
        'Quatre candidats à la présidentielle en Côte d''Ivoire appellent à un report du calendrier électoral pour mieux préparer les élections législatives et locales.',
        'https://gabonmediatime.com/legislatives-et-locales-4-candidats-a-la-presidentielle-appellent-au-reamenagement-du-calendrier-electoral/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2d42354-11cb-4343-94c8-cca03a795324',
        'Gabon : des ambitions économiques démesurées pour un Etat prédateur',
        'L''article critique la gestion économique de l''État gabonais, qu''il considère comme un « État prédateur » en raison de ses ambitions démesurées qui nuisent au développement durable du pays.',
        'https://gabonmediatime.com/gabon-des-ambitions-economiques-demesurees-pour-un-etat-predateur/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a974b42a-5e18-425a-a113-f56c439f2efd',
        'Hommage à Atatürk : le Président Oligui Nguema s’incline devant la mémoire du fondateur de la République turque',
        'Le président Oligui Nguema a rendu hommage à Atatürk, fondateur de la République turque, en se recueillant sur sa tombe pour saluer sa contribution à la modernisation et à l’indépendance de la Turquie.',
        'https://kongossanews.info/hommage-a-ataturk-le-president-oligui-nguema-sincline-devant-la-memoire-du-fondateur-de-la-republique-turque/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e58e624-d8cd-4c2b-ac63-d360270c4ab6',
        'Gabon–Turquie : découvrez quelques accords stratégiques signés à Ankara pour une coopération renforcée',
        'La visite officielle en Turquie a permis la signature de plusieurs accords stratégiques visant à renforcer la coopération entre le Gabon et la Turquie dans différents domaines comme l''économie, l''énergie, et la formation.',
        'https://kongossanews.info/gabon-turquie-decouvrez-quelques-accords-strategiques-signes-a-ankara-pour-une-cooperation-renforcee/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ec31907e-98d3-49dd-98b0-1a9973c24c71',
        'Gabon : lancement d’un programme de mentorat pour les femmes politiques',
        'Une plateforme a lancé un programme de mentorat pour encourager et soutenir la participation politique des femmes en Afrique, à l’occasion de la journée internationale de la femme africaine.',
        'https://agpgabon.ga/gabon-lancement-dun-programme-de-mentorat-pour-les-femmes-politiques/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a306a205-de66-469b-a5dc-aaaccd959139',
        'Clôture de l’atelier EHCVM : vers des données comparables pour des politiques plus inclusives',
        'L’atelier de formation a permis aux pays de la CEMAC et de l’UEMOA de renforcer leurs compétences pour collecter et analyser des données comparables sur les conditions de vie des ménages, afin d’élaborer des politiques plus inclusives.',
        'https://agpgabon.ga/cloture-de-latelier-ehcvm-vers-des-donnees-comparables-pour-des-politiques-plus-inclusives/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25d1b605-b7e1-4b83-8ad3-c3ad839c0555',
        'Gabon/Turquie : huit protocoles d’accords bilatéraux signés entre les deux pays',
        'Le président gabonais et le président turc ont discuté et signé huit accords bilatéraux pour renforcer la coopération entre leurs pays, notamment la création d’un Conseil d’affaires Gabon-Turquie.',
        'https://agpgabon.ga/gabon-turquie-huit-protocoles-daccords-bilateraux-signes-entre-les-deux-pays/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef733c21-0857-430f-a084-83ef8b99b620',
        'Écouter, comprendre, agir : la méthode Ulrich Manfoumbi Mafoumbi pour moderniser les transports',
        'Le Ministre d’État Ulrich Manfoumbi Manfoumbi a rencontré les agents du ministère des Transports pour discuter de l''amélioration des conditions de travail, de la formation et des perspectives de carrière afin de mieux servir le public.',
        'https://www.gabonews.com/fr/actus/transports/article/ecouter-comprendre-agir-la-methode-ulrich',
        'Gabonews',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2cd76adb-4c3c-4d3f-8aff-589ba08312ef',
        'Les Présidents Brice Clotaire Oligui Nguema et Recep Tayyip Erdogan redynamisent leurs relations bilatérales',
        'Le président du Gabon, Brice Clotaire Oligui Nguema, a rencontré le président turc Recep Tayyip Erdoğan à Ankara pour renforcer leur partenariat stratégique.',
        'https://www.gabonews.com/fr/actus/cooperation/article/les-presidents-brice-clotaire-oligui-nguema-et',
        'Gabonews',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e57390b6-5036-446e-8e7a-312d7f366660',
        'Gabon /Mines: Millennial Potash lève 4,5 milliards FCFA pour le projet de potasse de Mayumba',
        'Une société canadienne a levé environ 4,5 milliards de FCFA pour financer l''exploitation d''une mine de potasse à Mayumba, au sud du Gabon, afin de poursuivre ses travaux d''exploration et de développement.',
        'https://agpgabon.ga/gabon-mines-millennial-potash-leve-45-milliards-fcfa-pour-le-projet-de-potasse-de-mayumba/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5bff7ae-6d13-4115-83d7-d00adf2211a0',
        'Jeux Africains Scolaires d’Alger : le judo offre deux médailles supplémentaires au Gabon',
        'Les judokas gabonais Charles André Ngoulou Alevina et Sarah Ashley Bikaghessa ont remporté chacun une médaille de bronze aux Jeux Africains Scolaires d’Alger, portant le total des médailles du Gabon à cinq (quatre en bronze et une en argent).',
        'https://agpgabon.ga/jeux-africains-scolaires-dalger-le-judo-offre-deux-medailles-supplementaires-au-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9612ba06-789f-439f-a4ce-291254908c2f',
        'Franceville/Infrastructures routière : le ministère des Travaux Publics Consulte les habitants du quartier Dialogue dans le cadre du PADIG',
        'Le ministère des Travaux publics a organisé une consultation dans le quartier Dialogue à Franceville pour recueillir l’avis des habitants sur la rénovation de deux tronçons de route prioritaires dans le cadre du projet PADIG financé par la Banque mondiale.',
        'https://agpgabon.ga/franceville-infrastructures-routiere-le-ministere-des-travaux-publics-consulte-les-habitants-du-quartier-dialogue-dans-le-cadre-du-padig/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ac9d8e0a-10b3-4723-b251-4d587d465db0',
        'Gabon / Clôture du One Forest Youth 2025 : 656 millions FCFA pour soutenir le volontariat vert en Afrique',
        'Lors du sommet One Forest Youth à Libreville, des jeunes africains ont été encouragés à s’engager dans le volontariat écologique pour protéger les forêts et la biodiversité, avec un soutien financier de 656 millions FCFA pour renforcer ces actions à travers des cadres juridiques nationaux.',
        'https://agpgabon.ga/gabon-cloture-du-one-forest-youth-2025-656-millions-fcfa-pour-soutenir-le-volontariat-vert-en-afrique/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89e3b75f-410e-4ee6-b51d-5873a57fd63d',
        'Gabon/Kongo : une seconde édition pour réveiller les mémoires et fédérer les peuples',
        'Une deuxième édition des Rencontres Kongo se tiendra à Mouila du 8 au 10 août, avec des activités culturelles, sportives et intellectuelles visant à rappeler l’histoire commune et à renforcer les liens entre les peuples.',
        'https://agpgabon.ga/gabon-kongo-une-seconde-edition-pour-reveiller-les-memoires-et-federer-les-peuples/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba8a211e-1736-4523-950b-79bcaf7b7a22',
        'Entrepreunariat : “beer Minko”, une initiative gabonaise qui se fait de la place en France',
        'Un entrepreneur gabonais installé en France, Prince Arnaud Obiang Minko, a créé une bière artisanale appelée “Beer Minko” qui rencontre déjà du succès sur le marché français et pourrait être bientôt commercialisée au Gabon.',
        'https://agpgabon.ga/entrepreunariat-beer-minko-une-initiative-gabonaise-qui-se-fait-de-la-place-en-france/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd2906c9-37bb-410e-a89a-e4465697f87c',
        'Application de la Taxe carbone maritime : Un risque pour le secteur portuaire gabonais ?',
        'Le Gabon envisage d’étendre sa taxe carbone aux navires maritime pour préparer la mise en place d’un mécanisme mondial de tarification du carbone, ce qui pourrait représenter un risque pour le secteur portuaire du pays.',
        'https://directinfosgabon.com/application-de-la-taxe-carbone-maritime-un-risque-pour-le-secteur-portuaire-gabonais/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0116d909-99ab-4df7-b489-f49bb77835ef',
        'Pétrole : Le Gabon propulse les résultats de BW Energy au 1er semestre 2025',
        'BW Energy a réalisé de très bons résultats au premier semestre 2025 grâce à ses activités pétrolières au large du Gabon, notamment avec la production de près de 26 600 barils au deuxième trimestre.',
        'https://directinfosgabon.com/petrole-le-gabon-propulse-les-resultats-de-bw-energy-au-1er-semestre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4d3004c7-adb9-47c1-8edc-b7800afde276',
        'Publié le 01 / 08 / 2025',
        'Les commissions électorales sont calmes et la ville de Libreville est tranquille en attendant la présentation des candidats aux élections.',
        'https://union.sonapresse.com/fr/commissions-electorales-calme-plat-libreville-en-attendant-les-candidats',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a12504fe-87a1-4d6d-b2c0-2e92ee05570c',
        'Publié le 01 / 08 / 2025',
        'Le Gabon et la Turquie renforcent leur coopération en signant de nouveaux accords dans divers domaines, marquant une étape importante dans leurs relations diplomatiques et économiques.',
        'https://union.sonapresse.com/fr/gabon-turquie-une-nouvelle-page',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a6d45a5-11d8-4ea7-85e1-82d2c83ba67d',
        'Publié le 01 / 08 / 2025',
        'Le président gabonais et le président turc ont discuté de renforcer leur coopération économique et diplomatique lors de leur rencontre officielle.',
        'https://union.sonapresse.com/fr/gabon-turquie-un-tete-tete-fructueux-entre-les-deux-presidents',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5cc9bf2e-5a98-4c2e-a526-63c6b5bef265',
        'Gabon/Football : des joueurs de la sélection nationale reçus par le président Oligui Nguema',
        'Le président gabonais a rencontré des joueurs de l''équipe nationale de football en Turquie pour discuter de leur engagement et des prochains compétitions comme la Coupe d’Afrique des nations et la qualification pour la Coupe du Monde 2026.',
        'https://agpgabon.ga/gabon-football-des-joueurs-de-la-selection-nationale-recus-par-le-president-oligui-nguema/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2eaa9d2-6710-4aa5-96b5-a6fff71384bb',
        'Publié le 01 / 08 / 2025',
        'Le calme prévaut à Libreville en attendant la présentation des candidats aux élections, dans un contexte de sérénité au sein des commissions électorales.',
        'https://union.sonapresse.com/fr/commissions-electorales-calme-plat-libreville-en-attendant-les-candidats',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5031892f-9b4b-4a7d-9649-9bb31c884eb9',
        'Publié le 01 / 08 / 2025',
        'Le Gabon renforce ses relations avec la Turquie en développant de nouveaux partenariats économiques et éducatifs pour favoriser son développement.',
        'https://union.sonapresse.com/fr/gabon-turquie-une-nouvelle-page',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7e9e566-12b2-495b-80e0-9a597ef7eef1',
        'Publié le 01 / 08 / 2025',
        'Le président gabonais et le président turc ont eu un entretien fructueux, abordant notamment la coopération économique et les relations diplomatiques entre leurs deux pays.',
        'https://union.sonapresse.com/fr/gabon-turquie-un-tete-tete-fructueux-entre-les-deux-presidents',
        'L''union',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3a8cfdf-6e46-4858-83e6-52788fec5ffb',
        'Tennis de table : une délégation de la JICA échange avec des pongistes gabonais',
        'Une délégation de la JICA a rencontré et observé les pongistes gabonais lors d’une séance d’entraînement, marquant ainsi un partenariat visant à développer la pratique du tennis de table au Gabon.',
        'https://agpgabon.ga/tennis-de-table-une-delegation-de-la-jica-echange-avec-des-pongistes-gabonais/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '604b38d6-6fa7-4b63-a06e-2edcc277d798',
        'Gabon/Football : des joueurs de la sélection nationale reçus par le président Oligui Nguema',
        'Le président gabonais a rencontré des joueurs de l''équipe nationale qui jouent en Turquie pour discuter des compétitions à venir et leur a exprimé sa reconnaissance pour leur engagement à représenter le pays.',
        'https://agpgabon.ga/gabon-football-des-joueurs-de-la-selection-nationale-recus-par-le-president-oligui-nguema/',
        'AGP',
        'Business Intelligence',
        '2025-08-02T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

