-- Batch 3 - Section 6/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'ab9be896-f76c-4629-a6d3-e4e28ef7c49c',
        'Patricia Lydie Mouellet: la nouvelle patronne de la communication présidentielle',
        'Patricia Lydie Mouellet, une journaliste émérite de Gabon 1ère, a été nommée chef du département de la communication présidentielle dans le cadre de la nouvelle République gabonaise. Cette nomination intervient alors que le pays cherche à renforcer l''image du palais présidentiel et à dynamiser les relations entre le gouvernement et la presse nationale.',
        'https://kongossanews.info/patricia-lydie-mouellet-nommee-chef-de-la-communication-presidentielle-au-gabon/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52c4ac72-23ae-4ff2-bf05-7a104ca06087',
        'Publié le 09 / 05 / 2025',
        'La Déclaration de Libreville, adoptée lors d''une conférence de haut niveau, engage les parlements d''Afrique centrale et de l''Ouest à jouer un rôle clé dans la transition démocratique en garantissant une gouvernance transparente, la protection des droits des citoyens et le développement durable. Cette déclaration vise à faire des institutions législatives des sentinelles de la démocratie et de l''État de droit, contribuant ainsi à l''instauration de régimes post-transition respectueux des principes démocratiques[2][4][7].',
        'https://union.sonapresse.com/fr/role-des-parlements-en-transition-adoption-de-la-declaration-de-libreville',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5ed608c-466e-497b-9a7d-ccbacd2ae844',
        'Publié le 09 / 05 / 2025',
        'Séraphin Moundounga a été nommé Vice-Président de la République gabonaise le 5 mai 2025 et a pris ses fonctions peu après, avec pour mission d''assister le président Brice Clotaire Oligui Nguema dans ses responsabilités, sous la nouvelle constitution de la Ve République. Ce gouvernement, plus inclusif avec une forte représentation féminine, marque une étape importante dans la stabilisation politique et le développement du Gabon après le coup d''État d''août 2023[3][4][5][6][8].',
        'https://union.sonapresse.com/fr/ve-republique-oligui-nguema-recoit-le-serment-de-seraphin-moundounga-et-du-gouvernement',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e891ae58-74b3-4c25-8698-a7f3e2d144d1',
        'Publié le 09 / 05 / 2025',
        'Le président gabonais Brice Clotaire Oligui Nguema exige une action rapide et efficace de son gouvernement, visant à éradiquer le chômage et à améliorer la situation économique. Cette nouvelle équipe, formée dans le cadre de la Ve République, est chargée de traduire en actes les aspirations du peuple gabonais pour une gouvernance plus efficace.',
        'https://union.sonapresse.com/fr/gouvernement-daction-pour-batir-le-gabon-nouveau-executif-au-travail-et-tout-de-suite',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68542193-066e-4df1-b71b-6318613fd63e',
        'Libreville : Noélie Mékama, la force montante du 6e arrondissement Partenariat : le groupe « Apollo Africa » reçu à la Fondation...',
        'Noélie Mékama s''impose comme une figure montante du 6e arrondissement de Libreville, jouant un rôle clé au sein de l''Union des femmes du Parti démocratique gabonais (PDG) et s''engageant activement dans le développement local.',
        'https://mediapostegabon.com/libreville-noelie-mekama-la-force-montante-du-6e-arrondissement/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72ee1be4-abad-4cfc-b5a7-69f2e698e9d9',
        'Post-transition : Oligui Nguéma peut compter avec l’association AGIR',
        'L''association Agir soutient fermement le président Brice Oligui Nguema dans la phase post-transition, en l''accompagnant pour promouvoir le développement et la stabilité au Gabon. Cette collaboration vise à renforcer les actions sociales et économiques dans le pays sous la nouvelle gouvernance.',
        'https://gabonactu.com/blog/2025/05/09/post-transition-oligui-nguema-peut-compter-avec-lassociation-agir/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '191cc252-6bac-4bf1-95cf-2a604d6acbbf',
        'Gabon : Oyima prend officiellement les rênes du super-ministère de l’Économie, des Finances, de la Dette et des Participations',
        'Henri-Claude Oyima a officiellement pris la tête du super-ministère de l''Économie, des Finances, de la Dette et des Participations au Gabon, avec pour mission de restaurer la rigueur budgétaire et de lutter contre la vie chère. Cette nomination marque un tournant majeur dans la gouvernance économique du pays, à la veille de la cinquième République.',
        'https://gabonmediatime.com/gabon-oyima-prend-officiellement-les-renes-du-super-ministere-de-leconomie-des-finances-de-la-dette-et-des-participations/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a86002c-798f-44a8-9884-12c620bf7b74',
        'Gabon : la présidence de la République réorganisée autour de huit pôles sous la V République',
        'La Présidence de la République du Gabon a été réorganisée autour de huit pôles clés dans le cadre de la Ve République, visant une réforme significative de son fonctionnement et de ses attributions. Cette réorganisation s''inscrit dans le contexte d''une nouvelle structure gouvernementale, répondant aux besoins de gouvernance efficace et de refondation de l''action de l''État.',
        'https://gabonmediatime.com/gabon-la-presidence-de-la-republique-reorganisee-autour-de-huit-poles-sous-la-v-republique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6713ce9-7926-470e-9ead-226d7401d6b5',
        'Gabon : l’ingénieur Sosthène Nguema Nguema face aux défis du secteur pétro-gazier',
        'Sosthène Nguema Nguema, nouveau ministre gabonais du Pétrole et du Gaz, incarne une vision renouvelée de la gouvernance des ressources stratégiques. Son parcours, marqué par une formation scientifique solide et une expérience dans l''industrie extractive, le positionne comme un acteur clé pour relever les défis du secteur pétro-gazier.',
        'https://gabonmediatime.com/gabon-lingenieur-sosthene-nguema-nguema-face-aux-defis-du-secteur-petro-gazier/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '058f98ed-d03d-40e9-af27-6102b59fec50',
        'Publié le 09 / 05 / 2025',
        'Les parlements d''Afrique centrale et de l''Ouest ont adopté la Déclaration de Libreville, qui vise à renforcer la démocratie et l''État de droit durant les transitions politiques. Cette déclaration engage les parlements à jouer un rôle clé dans la promotion de la transparence, du dialogue national et de la stabilité institutionnelle.',
        'https://union.sonapresse.com/fr/role-des-parlements-en-transition-adoption-de-la-declaration-de-libreville',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '35934cb7-1017-4ebd-95c6-f188d1ef1f8c',
        'Publié le 09 / 05 / 2025',
        'Séraphin Moundounga a prêté serment en tant que vice-président de la République du Gabon, marquant une nouvelle étape dans la transition politique du pays. Le gouvernement de Brice Clotaire Oligui Nguema est en place, avec une composition renouvelée et divers objectifs pour le développement national.',
        'https://union.sonapresse.com/fr/ve-republique-oligui-nguema-recoit-le-serment-de-seraphin-moundounga-et-du-gouvernement',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7969791b-ddc7-4ad7-bcd1-1b638c3fb7b5',
        'Publié le 09 / 05 / 2025',
        'Le président gabonais Brice Clotaire Oligui Nguema exige une action rapide et efficace de son gouvernement, mettant l''accent sur l''éradication du chômage et la création de conditions favorables au développement économique. Ce nouveau gouvernement, composé de 30 membres, vise à assurer la stabilité politique et économique, à promouvoir une gouvernance transparente et inclusive, et à préparer les réformes nécessaires pour diversifier l''économie gabonaise.',
        'https://union.sonapresse.com/fr/gouvernement-daction-pour-batir-le-gabon-nouveau-executif-au-travail-et-tout-de-suite',
        'L''union',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6149e74d-1faa-46c5-9687-df75dc393395',
        'Libreville : Noélie Mékama, la force montante du 6e arrondissement Partenariat : le groupe « Apollo Africa » reçu à la Fondation...',
        'Noélie Mékama, déléguée communale des femmes du Parti démocratique gabonais (PDG) dans le 6e arrondissement de Libreville, se distingue par son engagement communautaire. Elle est considérée comme une force montante dans cet arrondissement, dynamique et en croissance démographique notable[1].',
        'https://mediapostegabon.com/libreville-noelie-mekama-la-force-montante-du-6e-arrondissement/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c66b8081-499c-4b53-ab93-1a7abd99153e',
        'Airtel Africa plc  Résultats pour l’exercice clos le 31 mars 2025',
        'Airtel Africa a enregistré une croissance de 8,7 % de sa base de clients pour atteindre 166,1 millions et une augmentation de 14,1 % de ses clients de données à 73,4 millions. Les revenus ont augmenté de 21,1 % en monnaie constante, mais ont diminué de 0,5 % en monnaie rapportée en raison de la dévaluation des devises.',
        'https://vxp241.com/2025/05/09/airtel-africa-plc-resultats-pour-lexercice-clos-le-31-mars-2025/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bd4addb6-3935-4e0c-a466-a1e6894c3138',
        'Des médicaments pour le Centre hospitalier régional de N’tchengue',
        'Le Centre hospitalier régional de N''tchengue a reçu le 7 mai 2025 un don de médicaments en présence de l’inspecteur régional des services de santé. Cette dotation vise à soutenir et améliorer l’approvisionnement en produits pharmaceutiques de l’établissement[2].',
        'https://gabonactu.com/blog/2025/05/09/des-medicaments-pour-le-centre-hospitalier-regional-de-ntchengue/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8d0219c-b6ae-4a56-95b6-7058a2ea0f71',
        'Élaboration et gestion des projets : réflexion des acteurs associatifs à Port-Gentil',
        'Les ONG et les associations à Port-Gentil élaborent fréquemment des projets, qu''ils soient communs ou individuels. Il est essentiel que leurs dirigeants soient formés pour assurent une gestion efficace de ces projets.',
        'https://gabonactu.com/blog/2025/05/09/elaboration-et-gestion-des-projets-reflexion-des-acteurs-associatifs-a-port-gentil/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '32445108-2de0-4a83-ad37-6ca2ae768d25',
        'Journée nationale de la femme : Aurore et Conacce Chaplains jouent les prolongations et sensibilisent',
        'L’ONG Aurore et les femmes de la Conacce Chaplains Gabon ont organisé une conférence à Libreville pour sensibiliser sur les droits des femmes et leur autonomisation, mettant en avant des témoignages d’expertes et des solutions concrètes comme la transformation des produits locaux et le soutien aux victimes de violences. Une deuxième session de cette rencontre est prévue à Port-Gentil afin de poursuivre ces actions de promotion et d’accompagnement des femmes gabonaises[2].',
        'https://gabonactu.com/blog/2025/05/09/journee-nationale-de-la-femme-aurore-et-conacce-chaplains-jouent-les-prolongations-et-sensibilisent/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7980ffb1-405a-4b6f-aa37-95b241e105e7',
        'Gabon : Air France dans le viseur pour manquements présumés à la loi sur les données personnelles',
        'Air France est en difficulté à Gabon en raison de manquements présumés à la loi sur les données personnelles, ce qui pourrait entraîner des sanctions lourdes en raison du manque de coopération. Les autorités locales examinent de près les pratiques de l''entreprise pour garantir le respect de la législation gabonaise en matière de protection des données personnelles.',
        'https://www.gabonreview.com/gabon-air-france-dans-le-viseur-pour-manquements-presumes-a-la-loi-sur-les-donnees-personnelles/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eacbf4dc-e0e8-484b-ab68-01c0c459ad32',
        'PDG Woleu-Ntem : les cadres militants démissionnent et font un clin d’œil à Oligui Nguema',
        'Plusieurs cadres éminents du Parti démocratique gabonais (PDG) du Woleu-Ntem ont démissionné collectivement, invoquant les dysfonctionnements internes et exprimant leur soutien au président Oligui Nguema pour assurer une transformation radicale du pays. Ils appellent également les militants du PDG à se rallier à cette nouvelle dynamique politique sous la direction d’Oligui Nguema[1][2].',
        'https://gabonactu.com/blog/2025/05/09/pdg-woleu-ntem-les-cadres-militants-demissionnent-et-font-un-clin-doeil-a-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e42ad860-d8fb-4e2f-97f7-a3a941568ffe',
        'Gabon/Economie Bleue : Laurence Mengue-Me-Nzoghe officiellement installée',
        'Laurence Mengue Me Nzoghe a été officiellement installée dans ses fonctions de ministre de la Mer, de la Pêche et de l’Économie bleue, et porte-parole du gouvernement gabonais, dans le cadre du nouveau gouvernement de la Ve République. Cette nomination marque une nouvelle étape dans la gestion des ressources marines et la relance de l’économie bleue au Gabon[1][2][4].',
        'https://agpgabon.ga/2025/05/09/gabon-economie-bleue-laurence-mengue-me-nzoghe-officiellement-installee/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9ab3c3b-2660-4c2f-86f5-d918b86ea38f',
        'Gabon/Ministère des Sports : Dr Armande Longo-Moulengui a officiellement pris ses fonctions',
        'Dr Armande Longo Moulengui a officiellement pris ses fonctions de ministre de la Jeunesse, des Sports, du Rayonnement culturel et des Arts, chargée de la Vie associative, succédant à Patrick Barbera Isaac et cumulant désormais la culture, la jeunesse et le sport au Gabon. Sa nomination est perçue comme un atout pour dynamiser ces secteurs, grâce à son expérience en enseignement et en administration, ainsi qu’à ses actions récentes en faveur des étudiants et des agents culturels[1][3][7].',
        'https://agpgabon.ga/2025/05/09/gabon-ministere-des-sports-dr-armande-longo-moulengui-a-officiellement-pris-ses-fonctions/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd95e3749-e29d-423c-9041-d1859404396f',
        'Religion/Première homélie du nouveau Pape : Léon XIV déplore le recul de la foi au profit de « l’argent »',
        'Le pape Léon XIV déplore lors de sa première homélie le recul de la foi chrétienne, souvent remplacée par la recherche de la technologie, de l’argent, du pouvoir ou du plaisir, ce qui entraîne des conséquences sociales graves comme la crise de la famille et la perte de la dignité humaine. Il appelle à une mission urgente pour restaurer la foi et à ne pas réduire Jésus à un simple leader charismatique ou surhomme[1][4][5][6].',
        'https://agpgabon.ga/2025/05/09/religion-premiere-homelie-du-nouveau-pape-leon-xiv-deplore-le-recul-de-la-foi-au-profit-de-largent/',
        'AGP',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7bbc06c-308e-4724-ae4a-841f5e54e177',
        'Le Président de la République reçoit les lettres de créances  du nouvel Ambassadeur d’Angola accrédité au Gabon',
        'Le président de la République du Gabon a reçu les lettres de créance du nouvel ambassadeur d’Angola, marquant ainsi le début officiel de sa mission diplomatique au Gabon et renforçant les relations bilatérales entre les deux pays. Cette cérémonie symbolise la volonté des deux nations de poursuivre leur coopération politique et économique.',
        'https://vxp241.com/2025/05/09/le-president-de-la-republique-recoit-les-lettres-de-creances-du-nouvel-ambassadeur-dangola-accredite-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-09T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2c293f24-14ef-4325-b593-0c19b3f86aca',
        'Protection de la biodiversité marine : Le Gabon se met à jour',
        'Le Gabon avance dans la protection de la biodiversité marine en ratifiant un accord international pour la conservation durable des zones marines au-delà de sa juridiction nationale, s''inscrivant dans son engagement à protéger 30% de ses écosystèmes terrestres, d''eau douce et marins d''ici 2030. Cette démarche s''accompagne d''efforts pour renforcer la gestion des aires marines protégées, lutter contre la pêche illégale et promouvoir un partage équitable des ressources marines. [5][4][6]',
        'https://gabonactu.com/blog/2025/05/10/protection-de-la-biodiversite-marine-le-gabon-se-met-a-jour/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f6791761-8ff8-4eaa-bf15-96b1dbc2bfea',
        'L''iboga, une plante sacrée au Gabon et un remède convoité',
        'L''iboga est une plante sacrée au Gabon, utilisée pour ses propriétés psychotropes et médicinales, notamment dans le traitement des addictions. Elle joue un rôle central dans les cérémonies initiatiques bwiti, où elle est considérée comme un élément essentiel pour se connecter avec les ancêtres et favoriser la guérison spirituelle et physique.',
        'https://www.lopinion.fr/international/liboga-une-plante-sacree-au-gabon-et-un-remede-convoite?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d45db08-5a7c-41c9-bc0a-9f11c6b09751',
        '« 5ème République » : Des femmes parlementaires plaident pour plus d’inclusivité et d’implication de la gent féminine',
        'Des femmes parlementaires gabonaises plaident pour une plus grande inclusivité et implication des femmes dans la vie politique, soulignant l''importance de leur participation active dans le contexte de la 5ème République. Cette demande vise à renforcer l''égalité des genres et à accroître la représentation féminine dans les sphères décisionnelles du pays.',
        'https://gabonactu.com/blog/2025/05/10/5eme-republique-des-femmes-parlementaires-plaident-pour-plus-dinclusivite-et-dimplication-de-la-gent-feminine/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '73187ed9-49ce-4f7f-bdcd-cd7aa16b3c0e',
        'Coopération Gabon – Turquie : Les acquis, les enjeux et les perspectives',
        'La coopération entre le Gabon et la Turquie se concentre sur le développement durable et vise à renforcer leurs liens dans les domaines de l''enseignement supérieur, de la recherche scientifique et technologique. Cette collaboration inclut des projets conjoints de recherche et d''innovation, ainsi que des programmes d''échange de scientifiques pour favoriser l''intégration des écosystèmes d''innovation des deux pays.',
        'https://gabonactu.com/blog/2025/05/10/cooperation-gabon-turquie-les-acquis-les-enjeux-et-les-perspectives/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16113b05-d79a-4411-8392-d323ea7c4b02',
        'Sylvia et Noureddin Bongo quittent la prison pour la résidence surveillée',
        'Sylvia Bongo Ondimba et son fils Noureddin, épouse et fils de l''ex-président Ali Bongo, ont été transférés en résidence surveillée à leur villa de la Sablière, après avoir quitté la prison le 9 mai 2025. Cette décision intervient alors que la famille fait face à des suspicions de détournements de fonds publics, suivant le putsch militaire d''août 2023 au Gabon.',
        'https://www.gabonreview.com/gabon-sylvia-et-noureddin-bongo-desormais-en-residence-surveillee/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '447a73cb-fadf-4fb1-bd9a-74ce058673a6',
        'Gabon : Oligui Nguema fixe les 6 piliers de l’action gouvernementale',
        'Le Président gabonais Brice Clotaire Oligui Nguema a dévoilé une feuille de route gouvernementale structurée autour de six piliers stratégiques et quinze engagements prioritaires pour son septennat, visant à transformer le pays et à améliorer la vie des citoyens. Les engagements incluent l''accès universel à l''eau potable et à l''électricité, un système de santé performant, ainsi qu''une relance économique basée sur la création d''emplois durables.',
        'https://gabonmediatime.com/gabon-oligui-nguema-fixe-les-6-piliers-de-laction-gouvernementale/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25847714-4f1c-4676-816c-c17c54691a5c',
        'Gabon : Denise Mekam’ne quitte son poste de SGA1 du PDG',
        'Denise Mekam’ne a démissionné de ses fonctions de secrétaire générale adjointe 1er du Parti démocratique gabonais (PDG) pour se consacrer à ses engagements personnels, tout en restant militante et fidèle au parti. Ce départ s’inscrit dans un contexte de mutation politique au sein du PDG, qui cherche à se réinventer après la chute du régime en 2023.',
        'https://gabonmediatime.com/gabon-denise-mekamne-quitte-son-poste-de-sga1-du-pdg/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4a132060-c556-41bc-a0f3-99f85aa2c34e',
        'BGFIBank : 122 milliards FCFA de résultat net bénéficiaire en 2024 !',
        'En 2024, le groupe BGFIBank a réalisé un résultat net de 122 milliards FCFA, ce qui représente une augmentation de 27 % par rapport à l''année précédente. Le total de bilan s''est élevé à 5 951 milliards FCFA, avec des dépôts de clientèle en hausse de 17 % et des crédits à la clientèle progressant de 16 %[4].',
        'https://gabonmediatime.com/bgfibank-122-milliards-fcfa-de-resultat-net-beneficiaire-en-2024/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09c47bb2-8939-4e24-9b20-c57d0ab1c969',
        'Conseil des Ministres : Régis Immongault Tatangani, nommé Ambassadeur extraordinaire et plénipotentiaire de la République Gabona...',
        'Régis Immongault Tatangani a été nommé ambassadeur extraordinaire et plénipotentiaire du Gabon auprès du Benelux, ainsi que représentant permanent auprès de l’Union européenne et de l’Organisation des États d’Afrique, des Caraïbes et du Pacifique, marquant sa première fonction officielle d’ambassadeur avec pour mission principale de renforcer les relations diplomatiques et économiques du Gabon en Europe. Cette nomination illustre la volonté du président Brice Clotaire Oligui Nguema de s’appuyer sur des profils expérimentés pour moderniser la diplomatie gabonaise après la transition politique récente.',
        'https://kongossanews.info/conseil-des-ministres-regis-immongault-tatangani-nomme-ambassadeur-extraordinaire-et-plenipotentiaire-de-la-republique-gabonaise-aupres-du-benelux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f9e636e-7fa3-4b42-9cf2-3853ce3aed6b',
        'ANAC : Attention à l’arnaque !',
        'Je n''ai pas accès au contenu spécifique de l''article mentionné sur le site Gabon Actu. Pour un résumé précis, il faudrait consulter directement l''article "ANAC : attention à l''arnaque". Cependant, voici une approche générale sur le sujet ANAC au Gabon : L''Agence Nationale de l''Aviation Civile (ANAC) du Gabon joue un rôle crucial dans la sécurité aérienne, en renforçant les contrôles et en élaborant des protocoles pour améliorer la sûreté des aéroports gabonais. Elle travaille également à maintenir la conformité aux normes internationales, comme celles de l''OACI.',
        'https://gabonactu.com/blog/2025/05/10/anac-attention-a-larnaque/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e7468f06-e9d3-434f-a8e5-e6fd25475a16',
        'RPM 4ème arrondissement : Bravo à Barro Chambrier, merci à Oligui Nguéma',
        'Alexandre Barro Chambrier, président du Rassemblement pour la Patrie et la Modernité (RPM), a mené une campagne dans le 4ème arrondissement littoral de Libreville, suscitant des félicitations pour son engagement. Les remerciements ont également été adressés à Brice Clotaire Oligui Nguema, soulignant une dynamique de soutien au sein du parti.',
        'https://gabonactu.com/blog/2025/05/10/rpm-4eme-arrondissement-bravo-a-barro-chambrier-merci-a-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad756a99-267b-4a00-aa4e-b90ddf871ece',
        'Concours d’entrée à l’USTS, le 25 mai',
        'Le concours d''entrée à l''USTS est prévu pour le 25 mai 2025. Les candidats doivent se préparer en suivant les étapes de candidature, qui incluent notamment la préparation des documents nécessaires et la bonne compréhension des exigences pour l''inscription.',
        'https://gabonactu.com/blog/2025/05/10/concours-dentree-a-lusts-le-25-mai/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '720e5040-804d-4e44-b05b-6829d84fb64b',
        'Gabon : Oligui Nguema fixe les 6 piliers de l’action gouvernementale',
        'Le président Brice Clotaire Oligui Nguema a dévoilé une feuille de route gouvernementale axée sur six piliers stratégiques et quinze engagements prioritaires pour son septennat, visant à améliorer la vie des citoyens gabonais. Cette approche inclut des objectifs tels que l''accès universel à l''eau potable et à l''électricité, ainsi que la création d''un pôle numérique national.',
        'https://gabonmediatime.com/gabon-oligui-nguema-fixe-les-6-piliers-de-laction-gouvernementale/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4bc92511-99c2-4b8a-9423-e20f45a39936',
        'Gabon : Denise Mekam’ne quitte son poste de SGA1 du PDG',
        'Denise Mekam’ne a démissionné de ses fonctions de secrétaire générale adjointe 1 (SGA1) au sein du Parti démocratique gabonais (PDG) pour se consacrer à ses engagements personnels, tout en restant militante fidèle du parti. Ce départ s’inscrit dans un contexte de transformation interne du PDG, sans marquer une rupture avec le parti. [1][2]',
        'https://gabonmediatime.com/gabon-denise-mekamne-quitte-son-poste-de-sga1-du-pdg/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '843aedd3-d2d7-4889-9d17-664bba1a71e3',
        'BGFIBank : 122 milliards FCFA de résultat net bénéficiaire en 2024 !',
        'En 2024, BGFIBank a réalisé un résultat net bénéficiaire de 122,41 milliards FCFA, en hausse de 27 % par rapport à l''année précédente, avec un total de bilan atteignant 5 951 milliards FCFA. Les dépôts de la clientèle ont augmenté de 17 % et les crédits à la clientèle de 16 %, reflétant une solide performance commerciale et une gestion équilibrée des fonds.',
        'https://gabonmediatime.com/bgfibank-122-milliards-fcfa-de-resultat-net-beneficiaire-en-2024/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85b3c985-4ed8-4351-bed1-6e4dd0b0ef5e',
        'Conseil des Ministres : Régis Immongault Tatangani, nommé Ambassadeur extraordinaire et plénipotentiaire de la République Gabona...',
        'Régis Immongault Tatangani a été nommé ambassadeur extraordinaire et plénipotentiaire du Gabon auprès du Benelux, ainsi que représentant permanent auprès de l’Union européenne et de l’Organisation des États d’Afrique, des Caraïbes et du Pacifique, dans le cadre d’une stratégie visant à renforcer la diplomatie gabonaise après une transition politique. Ancien ministre et économiste de formation, il aura pour mission de défendre les intérêts du Gabon en Europe, notamment à travers la renégociation d’accords commerciaux et l’attraction d’investissements.',
        'https://kongossanews.info/conseil-des-ministres-regis-immongault-tatangani-nomme-ambassadeur-extraordinaire-et-plenipotentiaire-de-la-republique-gabonaise-aupres-du-benelux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5696f34f-8c19-401d-b21a-784586cd82dc',
        'Publié le 10 / 05 / 2025',
        'Le Parti démocratique gabonais (PDG) fait face à une série de démissions au sein de ses rangs, mais le parti brandit son règlement intérieur pour encadrer ces départs. Cela montre que le PDG a des règles strictes pour gérer les démissions, comme l''indique l''article 53 de son Manuel de Procédure de la Commission Centrale.',
        'https://union.sonapresse.com/fr/pdg-face-aux-demissions-en-cascade-le-parti-brandit-son-reglement-interieur',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '779084e0-8ff8-4df7-a13e-35e0a7cb6bb4',
        'Publié le 10 / 05 / 2025',
        'Oligui Nguema a reçu les lettres de créance du nouvel ambassadeur d''Angola, marquant ainsi une étape importante dans les relations diplomatiques entre les deux pays. Cette cérémonie souligne la volonté de renforcer la coopération bilatérale entre l''Angola et le Gabon, pays membres de la Communauté économique et monétaire de l''Afrique centrale (CEMAC).',
        'https://union.sonapresse.com/fr/diplomatie-oligui-nguema-recoit-les-lettres-de-creance-du-nouvel-ambassadeur-dangola',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9640cde5-9d8f-4f27-972a-5bb2b72563aa',
        'Publié le 09 / 05 / 2025',
        'Denise Mekam''ne, ancienne ministre sous la présidence d’Ali Bongo Ondimba, a démissionné de son poste de secrétaire générale adjointe du Parti démocratique gabonais (PDG), mais elle conserve son statut de militante au sein du parti pour se concentrer sur des activités personnelles. Cette décision reflète une réévaluation de ses priorités tout en maintenant son engagement politique.',
        'https://union.sonapresse.com/fr/pdg-denise-mekamne-quitte-son-poste-de-sga-mais-reste-militante',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6519da7-b5a6-49b0-966d-42e7e55e0013',
        'Gabon : une agression filmée relance le débat sur la lutte contre les violences en milieu scolaire',
        'Une vidéo de violences entre élèves d''un établissement scolaire au Gabon a récemment alimenté le débat sur la lutte contre les violences en milieu scolaire. Ce phénomène souligne l''urgence d''actions concrètes pour assurer un environnement sûr et éducatif pour tous les élèves.',
        'https://agpgabon.ga/2025/05/10/gabon-une-agression-filmee-relance-le-debat-sur-la-lutte-contre-les-violences-en-milieu-scolaire/',
        'AGP',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cd3e7205-9401-46fd-a74c-d72f8e164325',
        'Ministère de l’Économie numérique : le général Bonjean Mbanza dit avoir exécuté sa feuille de route avec brio',
        'Le général Bonjean Mbanza affirme avoir mené avec succès sa feuille de route à la tête du ministère de l''Économie numérique, en mettant l''accent sur le développement des infrastructures numériques et la modernisation de l''offre de formation, notamment via des projets stratégiques comme la construction du câble sous-marin Médusa Afrique et la réforme de l''Institut Africain d''Informatique. Ces initiatives visent à renforcer la transformation digitale du Gabon et à positionner le pays comme un hub technologique en Afrique centrale. [1][2][3][5][6]',
        'https://gabonactu.com/blog/2025/05/10/ministere-de-leconomie-numerique-le-general-bonjean-mbanza-dit-avoir-execute-sa-feuille-de-route-avec-brio/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.433Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '654ef6eb-07ce-47cc-8ffb-13455a126ed9',
        'Publié le 10 / 05 / 2025',
        'Le Parti Démocratique Gabonais (PDG) rappelle que toute démission doit respecter strictement la procédure interne, estimant que les démissions non conformes sont nulles et sans effet. Cette déclaration vise à maintenir le contrôle interne du parti face à des démissions en cascade, soulignant l''importance de vérifier que les militants sont à jour de leurs obligations statutaires avant de quitter.',
        'https://union.sonapresse.com/fr/pdg-face-aux-demissions-en-cascade-le-parti-brandit-son-reglement-interieur',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4bb97554-44e2-4ac7-9112-a90a6ace368c',
        'Publié le 10 / 05 / 2025',
        'Le nouveau président gabonais, Brice Clotaire Oligui Nguema, a reçu les lettres de créance du nouvel ambassadeur d''Angola, marquant ainsi une étape importante dans les relations diplomatiques entre les deux pays. Cet échange renforce la coopération bilatérale et souligne les efforts des deux nations pour maintenir des liens solides dans divers domaines.',
        'https://union.sonapresse.com/fr/diplomatie-oligui-nguema-recoit-les-lettres-de-creance-du-nouvel-ambassadeur-dangola',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3921705-210b-406f-89b6-0149a3807f71',
        'Publié le 09 / 05 / 2025',
        'Denise Mekam''ne a démissionné de son poste de secrétaire générale adjointe du Parti démocratique gabonais (PDG) pour se consacrer davantage à ses activités personnelles, tout en restant simple militante au sein du parti.',
        'https://union.sonapresse.com/fr/pdg-denise-mekamne-quitte-son-poste-de-sga-mais-reste-militante',
        'L''union',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04c093e8-ee09-4802-b7f4-b3a85a04c694',
        'La démission collective du PDG des cadres du Woleu-Ntem jugée irrecevable par le Secrétariat Exécutif du parti',
        'Le secretariat exécutif du Parti démocratique gabonais (PDG) a jugé irrecevable la démission collective des cadres du Woleu-Ntem, parmi lesquels se trouvent Dr Guy Patrick Obiang et Charles Mve Ella. Cette décision intervient après que plusieurs cadres ont contesté cette démission, considérant qu''elle n''a pas été concertée et ne reflète pas la volonté de tous les membres du parti dans cette province.',
        'https://gabonactu.com/blog/2025/05/10/la-demission-collective-du-pdg-des-cadres-du-woleu-ntem-jugee-irrecevable-par-le-secretariat-executif-du-parti/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '15305e6e-5b58-4635-a9d9-0a8a0e6c90cd',
        'Gabon : la journée internationale des familles célébrée le 15 mai prochain à Libreville',
        'La Journée internationale des familles sera célébrée le 15 mai prochain à Libreville, avec un programme destiné à renforcer les liens familiaux et intergénérationnels. Cette célébration vise à valoriser l''importance de la famille dans la société gabonaise.',
        'https://agpgabon.ga/2025/05/10/gabon-la-journee-internationale-des-familles-celebree-le-15-mai-prochain-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5dd1d64d-3dd3-4085-b057-37ae68ecc9a7',
        'Gabon : Sylvia et Noureddin Bongo désormais en résidence surveillée',
        'Sylvia Bongo Ondimba et son fils Noureddin Bongo ont été transférés en résidence surveillée dans leur villa de la Sablière le 9 mai 2025, après plusieurs mois de détention pour des accusations de détournement de fonds et corruption. Ce changement intervient une semaine après l''investiture du président Brice Clotaire Oligui Nguema, suscitant des spéculations sur les influences politiques entourant ce dossier.',
        'https://agpgabon.ga/2025/05/10/gabon-sylvia-et-noureddin-bongo-desormais-en-residence-surveillee/',
        'AGP',
        'Business Intelligence',
        '2025-05-10T00:00:00.000Z',
        '2025-09-15T23:06:12.434Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

