-- Batch 1 - Section 11/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '6c0ee3f0-bd00-4b6d-b0eb-cff5c9040a8b',
        'ITIE et transparence au Gabon : un progrès insuffisant face aux exigences internationales',
        'L''évaluation de la mise en œuvre de la Norme ITIE 2019 au Gabon a révélé des progrès significatifs en termes d''impact et de résultats, mais a souligné des insuffisances en matière de transparence, obligeant le pays à adopter 17 mesures correctives d''ici juillet 2027.',
        'https://www.gabonreview.com/itie-et-transparence-au-gabon-un-progres-insuffisant-face-aux-exigences-internationales/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-03-19T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8396cfc8-f309-468e-bc97-2334c4a48690',
        'Gouvernance, ZLECAf et développement durable : les priorités de l’Africa CEO Forum 2025',
        'L’Africa CEO Forum 2025 à Abidjan réunira plus de 2 000 leaders pour discuter d’un nouveau partenariat public-privé visant à renforcer la gouvernance, accélérer la ZLECAf et promouvoir le développement durable en Afrique dans un contexte mondial complexe.',
        'https://www.gabonreview.com/gouvernance-zlecaf-et-developpement-durable-les-priorites-de-lafrica-ceo-forum-2025/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '338d5c76-f0a8-495a-8755-21aa92b8c390',
        'Éducation numérique : le Gabon fait un pas vers l’avenir avec YouScribe',
        'Le ministère de l’Éducation nationale du Gabon s''associe à YouScribe pour créer des bibliothèques numériques dans les lycées, facilitant ainsi l''accès aux ressources éducatives en ligne pour élèves et enseignants.',
        'https://www.gabonreview.com/education-numerique-le-gabon-fait-un-pas-vers-lavenir-avec-youscribe/',
        'Gabon Review',
        'Numérique / Digital, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c66ec21a-963a-4e45-9777-7f90290bb322',
        'Moyen-Ogooué : Oligui Nguema lance les travaux de construction du Pont de la Transition à Ebel Abanga',
        'Le Président Brice Clotaire Oligui Nguema a officiellement lancé les travaux de construction du Pont de la Transition à Ebel Abanga dans le département de l’Abanga-Bigné, visant à améliorer l’infrastructure et la fluidité du trafic dans la région du Moyen-Ogooué.',
        'https://gabonmediatime.com/moyen-ogooue-oligui-nguema-lance-les-travaux-de-construction-du-pont-de-la-transition-a-ebel-abanga/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Commerce, Finances, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bac3d258-8194-4976-b4c7-c285a689e0f9',
        'Publié le 19 / 03 / 2025',
        'Jean Ping assume la direction du Rassemblement pour la Nouvelle République et doit affronter de nombreux défis politiques aux côtés de Brice Clotaire Oligui Nguema dans le contexte des prochaines élections au Gabon.',
        'https://union.sonapresse.com/fr/presidentielle-le-rnr-de-jean-ping-aux-cotes-doligui-nguema-veritables-challenges',
        'L''Union',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd0c521cd-a338-4015-88a7-3969342f0de9',
        'Présidentielle 2025 : Une saisine de Pélagie Itsana à la Cour constitutionnelle aux fins d’invalidation des candidatures',
        'Marie Joselle Pélagie Itsana, présidente du Front des citoyennes pour la transparence électorale, a saisi la Cour constitutionnelle pour invalider les candidatures à l''élection présidentielle du 12 avril 2025 en raison de graves irrégularités constitutionnelles et organisationnelles.',
        'https://www.gabonreview.com/presidentielle-2025-une-saisine-de-pelagie-itsana-a-la-cour-constitutionnelle-aux-fins-dinvalidation-des-candidatures/',
        'Gabon Review',
        'Services, Éducation, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb575449-e8e2-41f7-a81a-eb20e8f489da',
        'Francophonie : le Niger, le Mali et le Burkina-Faso claquent la porte',
        'Le Mali, le Niger et le Burkina Faso se retirent de l’Organisation internationale de la francophonie en raison de sanctions sélectives et de perceptions d’ingérence, remettant en question le rôle de l’OIF en Afrique de l’Ouest.',
        'https://gabonmediatime.com/francophonie-le-niger-le-mali-et-le-burkina-faso-claquent-la-porte/',
        'Gabon Media Time',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7ba1945a-c529-4d47-a3e7-3592d682c05d',
        'Port-Gentil : Brice Clotaire Oligui Nguema annonce des projets d’AGR, d’entrepreneuriat et d’autonomisation des jeunes',
        'Lors d’une allocution à Port-Gentil, le président Brice Clotaire Oligui Nguema a annoncé des initiatives en agriculture, entrepreneuriat et autonomisation des jeunes pour réduire le chômage et stimuler l’économie locale.',
        'https://www.gabonreview.com/port-gentil-brice-clotaire-oligui-nguema-annonce-des-projets-dagr-dentrepreneuriat-et-dautonomisation-des-jeunes/',
        'Gabon Review',
        'Numérique / Digital, Services, Agriculture, Éducation, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.319Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9571b2d-88df-448f-b25d-e91dc63727df',
        'Publié le 19 / 03 / 2025',
        'Le Rassemblement pour la Nouvelle République (RNR), dirigé par Jean Ping, soutient la candidature de Brice Clotaire Oligui Nguema à l’élection présidentielle gabonaise du 12 avril 2025.',
        'https://union.sonapresse.com/fr/presidentielle-le-rnr-de-jean-ping-aux-cotes-doligui-nguema',
        'L''Union',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55e8094e-eb38-4a74-9dc9-22a525377455',
        'Une ambiance électrique au quartier Camp de Police pour le lancement du Rassemblement des Bâtisseurs',
        'Le Rassemblement des Bâtisseurs a été officiellement lancé dans une ambiance électrisante à Camp de Police, réunissant leaders politiques et citoyens pour promouvoir le développement et l''unité nationale au Gabon.',
        'https://kongossanews.info/une-ambiance-electrique-au-quartier-camp-de-police-pour-le-lancement-du-rassemblement-des-batisseurs/',
        'Kongossa News',
        'Numérique / Digital, Services, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a231830-0512-4009-b589-2acddc2abd9a',
        'Gabon : K.IN.G dit « Oui » à la candidature d’Oligui Nguema !',
        'L''association Kümba Y’Inôngô, Guwanani (K.IN.G) a officiellement soutenu la candidature de Brice Clotaire Oligui Nguema à l''élection présidentielle de 2025, encourageant les Gabonais à s''unir pour poursuivre ses réalisations et garantir un avenir prospère pour le pays.',
        'https://gabonmediatime.com/gabon-k-in-g-dit-oui-a-la-candidature-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6d75ba6-24f4-4e8d-a061-f2deb951f1ba',
        'Publié le 19 / 03 / 2025',
        'La Cour constitutionnelle a achevé les auditions des candidats présidentiels rejetés pour des motifs administratifs, incluant le ministre de l’Intérieur Hermann Immongault, et la décision finale est attendue jeudi.',
        'https://union.sonapresse.com/fr/cour-constitutionnelle-fin-de-la-phase-des-auditions',
        'L''Union',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad231af0-cbcc-4847-84eb-e090b0ec776b',
        'Présidentielle 2025 : le PDG fait languir et maintient le suspense sur son choix de candidat',
        'Le Parti démocratique gabonais (PDG) retarde sa décision de soutien pour l''élection présidentielle de 2025, préférant observer les dynamiques politiques actuelles et attendre une meilleure clarté des programmes des candidats avant de s''engager.',
        'https://www.gabonreview.com/presidentielle-2025-le-pdg-fait-languir-et-maintient-le-suspense-sur-son-choix-de-candidat/',
        'Gabon Review',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '939f0d7e-a69f-4118-b47d-ceed40252962',
        'Présidentielle 2025 : Oligui Nguema rejoint le RDB',
        'Brice Clotaire Oligui Nguema, président de la Transition et candidat à l''élection présidentielle de 2025, a officiellement rejoint le Rassemblement des Bâtisseurs (RDB) en signant sa fiche d’adhésion et en clarifiant sa position politique.',
        'https://gabonmediatime.com/presidentielle-2025-oligui-nguema-rejoint-le-rdb/',
        'Gabon Media Time',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.320Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de7af103-c21d-45cd-a54a-d8ce987fedcc',
        'Publié le 19 / 03 / 2025',
        'Le président de la Transition a annoncé le renommage de l’aéroport international de Port-Gentil en l’honneur de Joseph Rendjambe Issani, célébrant ainsi sa mémoire et initiant un projet de rénovation des infrastructures aéroportuaires gabonaises pour stimuler le développement économique et touristique.',
        'https://union.sonapresse.com/fr/port-gentil-joseph-rendjambe-issani-jamais',
        'L''Union',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.321Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10eb057d-3e78-45ed-a289-bf7bf1f92e0e',
        'Dr Marie Itsana, présidente du Front des Citoyens pour la Transparence Électorale (FCTE), saisit la Cour constitutionnelle pour ...',
        'Dr Marie Itsana du Front des Citoyens pour la Transparence Électorale saisit la Cour constitutionnelle pour invalider les candidatures à l’élection présidentielle prévue en avril 2025 en raison d’irrégularités électorales et de problèmes de nationalité des candidats.',
        'https://kongossanews.info/dr-marie-itsana-presidente-du-front-des-citoyens-pour-la-transparence-electorale-fcte-saisit-la-cour-constitutionnelle-pour-invalider-les-candidatures-a-lelection-presidentielle/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.321Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6253fdce-08f9-44ed-9b6a-3b810cac8b6d',
        'Gabon : Oligui Nguema nie vouloir absorber tous les partis politiques avec son mouvement',
        'Brice Clotaire Oligui Nguema, candidat à la présidentielle gabonaise de 2025, affirme que son mouvement, le Rassemblement des Bâtisseurs, vise à rassembler des soutiens sans pour autant absorber ou museler les partis politiques existants.',
        'https://www.gabonreview.com/gabon-oligui-nguema-nie-vouloir-absorber-tous-les-partis-politiques-avec-son-mouvement/',
        'Gabon Review',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.321Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e44e39cd-fc6a-4f40-a29e-7549ae48e3ee',
        'Bilie-By-Nze : « le système Bongo-PDG n’a pas disparu »',
        'Alain-Claude Bilie-By-Nze, candidat à la présidentielle du Gabon en 2025, affirme que le système Bongo-PDG persiste malgré le coup d''État de 2023, critiquant l''absence de véritables changements dans la transition politique.',
        'https://gabonmediatime.com/bilie-by-nze-le-systeme-bongo-pdg-na-pas-disparu/',
        'Gabon Media Time',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.321Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fb7f9f1-033c-4412-9a19-274d0f19b851',
        'Taxi Gab+ : 400 taxi, 2 772 candidats et 720 sélectionnés pour la phase 2',
        'Le projet Taxi Gab+ a achevé sa deuxième phase avec 2 772 candidatures reçues et 720 promoteurs sélectionnés pour obtenir l’un des 400 taxis, dans le but de moderniser le secteur des transports en commun et de former des chauffeurs entrepreneurs au Gabon.',
        'https://www.gabonreview.com/taxi-gab-400-taxi-2-772-candidats-et-720-selectionnes-pour-la-phase-2/',
        'Gabon Review',
        'Numérique / Digital, Services, Business Femme, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.321Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd3e92321-795a-4845-94e2-495e15e49081',
        'Publié le 19 / 03 / 2025',
        'Le président Brice Clotaire Oligui Nguema a visité Mpaga-village, évalué les conditions de vie difficiles et annoncé un financement de 500 millions de francs pour la réhabilitation des infrastructures locales.',
        'https://union.sonapresse.com/fr/au-plus-pres-des-realites-de-mpaga-village',
        'L''Union',
        'Numérique / Digital, Services, Commerce, Agriculture, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.322Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e891557-4812-4d3f-baee-7dab05b0610e',
        'Murielle Minkué galvanise les troupes de « La Pensée Patriotique » dans le 2ème arrondissement',
        'Murielle Minkué a orchestré une mobilisation de plus de 2 000 habitants dans le 2ᵉ arrondissement de Libreville pour établir les coordinations locales de « La Pensée Patriotique », renforçant ainsi le soutien au projet politique de Brice Clotaire Oligui Nguema.',
        'https://kongossanews.info/murielle-minkue-galvanise-les-troupes-de-la-pensee-patriotique-dans-le-2eme-arrondissement/',
        'Kongossa News',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.322Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6345acfc-d38f-44be-9f5b-76e8cf9114f0',
        '5e édition « Un refuge pour elles » : l’appel à l’aide de l’ONG Aurore pour achever les travaux',
        'La présidente de l''ONG Aurore lance un appel urgent pour finaliser le projet "Un refuge pour elles", destiné à accueillir les femmes victimes de violences au Gabon.',
        'https://www.gabonreview.com/5e-edition-un-refuge-pour-elles-lappel-a-laide-de-long-aurore-pour-achever-les-travaux/',
        'Gabon Review',
        'Services, Business Femme, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.322Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33e8181a-0caf-4953-ad28-743f54785c16',
        'Transport maritime : Zita Oligui dans les locaux de Sotrasmar',
        'La Première dame du Gabon, Zita Oligui Nguema, a visité les bureaux de Sotrasmar pour réaffirmer son engagement envers le développement du secteur maritime gabonais à la suite de l''inauguration de deux nouvelles pilotines.',
        'https://www.gabonreview.com/transport-maritime-zita-oligui-dans-les-locaux-de-sotrasmar/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.322Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f729c32e-0107-4b9e-93cc-bd463874b486',
        'Les jeunes de l’Union Nationale soutiennent Brice Clotaire OLIGUI NGUEMA   pour la présidentielle avec 8 recommandations.',
        'Lors du 3ᵉ Congrès Extraordinaire de l’Union Nationale à Libreville, les jeunes du parti ont manifesté leur soutien à Brice Clotaire Oligui Nguema pour l’élection présidentielle de 12 avril 2025, en formulant huit recommandations pour renforcer l''autonomisation, l''éducation et l''emploi des jeunes gabonais.',
        'https://kongossanews.info/les-jeunes-de-lunion-nationale-soutiennent-brice-clotaire-oligui-nguema-pour-la-presidentielle-avec-8-recommandations/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services, Finances, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.323Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf1f9916-1986-4755-8985-f477ced3f2e0',
        'Lambaréné : Les journalistes outillés pour une couverture responsable de la présidentielle',
        'À l’approche de l’élection présidentielle de 2025, une session à Lambaréné organisée par la Haute autorité de la communication vise à renforcer la liberté de la presse, à protéger les journalistes et à lutter contre la désinformation pendant la période électorale.',
        'https://www.gabonreview.com/lambarene-les-journalistes-outilles-pour-une-couverture-responsable-de-la-presidentielle/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.323Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05a38dda-d5e1-4840-8c2d-d9fc835ef979',
        'Présidentielle 2025 : Les 5 idées de chantiers de Minlama Mintogo à Oligui Nguema pour le septennat',
        'Dieudonné Minlama Mintogo soutient le président de la Transition Brice Clotaire Oligui Nguema pour la présidentielle 2025 au Gabon et propose cinq chantiers pour les sept prochaines années de son mandat.',
        'https://www.gabonreview.com/presidentielle-2025-les-5-idees-de-chantiers-de-minlama-mintogo-a-oligui-nguema-pour-le-septennat/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture, Finances, Tourisme, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.323Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e794ff0-1c55-47f9-9d36-ba036629ff76',
        'SOBRAGA, premier partenaire industriel du PNPE',
        'SOBRAGA, premier partenaire industriel du PNPE, participe activement aux Assises Nationales sur l’Emploi au Gabon, affirmant son engagement envers la formation professionnelle et l’insertion des jeunes sur le marché du travail.',
        'https://kongossanews.info/sobraga-premier-partenaire-industriel-du-pnpe/',
        'Kongossa News',
        'Éducation, Services, Finances, Business Femme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.323Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aba44161-bf20-4eaf-9c7e-ccb50590610d',
        'Mounana : Une rencontre politique majeure de l’Union nationale en soutien à Oligui Nguema',
        'La ville de Mounana accueillera une rencontre politique organisée par le Pr Guy Stéphane Padzys de l’Union nationale pour expliquer le soutien du parti à la candidature de Brice Clotaire Oligui Nguema à la présidentielle de 2025.',
        'https://www.gabonreview.com/mounana-une-rencontre-politique-majeure-de-lunion-nationale-en-soutien-a-oligui-nguema/',
        'Gabon Review',
        'Agriculture, Éducation, Services, Tourisme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.323Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b5199f1-0794-4e2f-bbc8-27376262bc89',
        'Stabilité sociale : COMILOG et ses partenaires sociaux signent un protocole d’accord décisif',
        'COMILOG et ses partenaires sociaux ont signé un protocole d’accord décisif visant à améliorer les conditions de travail, revaloriser les salaires et renforcer le dialogue social pour assurer la stabilité au sein de l’entreprise.',
        'https://directinfosgabon.com/stabilite-sociale-comilog-et-ses-partenaires-sociaux-signent-un-protocole-daccord-decisif/',
        'Direct infos Gabon',
        'Services, Finances, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.324Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ceeab8d-353b-4385-a07c-27d22e3cba34',
        'Pose de la première pierre du pont d’Ebel-Abanga : une infrastructure pour booster l’économie locale',
        'Le président de la Transition, le général Brice Clotaire Oligui Nguema, a inauguré la pose de la première pierre du pont d’Ebel-Abanga dans le Moyen-Ogooué, un projet de 7 milliards de francs CFA visant à moderniser les infrastructures routières, améliorer la sécurité, fluidifier le trafic et dynamiser l’économie locale.',
        'https://www.gabonreview.com/pose-de-la-premiere-pierre-du-pont-debel-abanga-une-infrastructure-pour-booster-leconomie-locale/',
        'Gabon Review',
        'Commerce, Services, Infrastructure, Agriculture, Tourisme',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.324Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f2ff318-db2c-4df9-adf1-e436bac4382e',
        'Présidentielle 2025 : Nicole Assélé explique pourquoi elle appelle à voter Bilie By Nze (déclaration intégrale)',
        'Dans une déclaration, le Dr Nicole Assélé, ancienne ministre et femme politique gabonaise, appelle les électeurs à soutenir Alain Claude Bilie By Nze lors de la présidentielle de 2025, soulignant son intégrité et son engagement pour un renouveau national.',
        'https://gabonactu.com/blog/2025/03/20/presidentielle-2025-nicole-assele-explique-pourquoi-elle-appelle-a-voter-bilie-by-nze-declaration-integrale/',
        'Gabon Actu',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.324Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7052a15-e60e-4073-af09-2ac416f6a0e7',
        'Iniva Tourism & Hospitality ambitionne de faire du Gabon une destination d’exception',
        'Iniva Tourism & Hospitality, une startup gabonaise fondée il y a un an, ambitionne de faire du Gabon une destination touristique d’exception en investissant plus de 5 milliards de FCFA d’ici 2028 et en favorisant un développement économique, environnemental et social durable.',
        'https://directinfosgabon.com/iniva-tourism-hospitality-ambitionne-de-faire-du-gabon-une-destination-dexception/',
        'Direct infos Gabon',
        'Tourisme, Services, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.325Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c6fb63d9-ff88-4f59-969a-9f6bcb6b3099',
        'Comilog : Un protocole de fin de médiation, des engagements et un tournant décisif pour l’entreprise',
        'La Compagnie minière de l’Ogooué (Comilog) a signé un protocole de fin de médiation incluant des augmentations salariales et des engagements pour stabiliser l''entreprise et prévenir les grèves jusqu''aux élections professionnelles de janvier 2026.',
        'https://www.gabonreview.com/comilog-un-protocole-de-fin-de-mediation-des-engagements-et-un-tournant-decisif-pour-lentreprise/',
        'Gabon Review',
        'Services, Éducation, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.325Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12763d45-69a0-429c-bdad-968418493bce',
        'COMILOG : Le dialogue, la trêve et la paix sociales se consolident',
        'La Compagnie minière de l’Ogooué (COMILOG) a signé un protocole de médiation renforçant le dialogue social, instauré une trêve sociale jusqu’en janvier 2026, et mis en place des augmentations salariales et des améliorations des conditions de travail pour assurer la stabilité et la paix au sein de l’entreprise.',
        'https://gabonactu.com/blog/2025/03/20/comilog-le-dialogue-la-treve-et-la-paix-sociales-se-consolident/',
        'Gabon Actu',
        'Services, Éducation, Finances',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.325Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6d6b70e2-e004-406b-8868-51b91ce7d1b9',
        'Employabilité des Jeunes :  Les opportunités de la Setrag exposées au Salon de l’Emploi',
        'La Setrag a présenté ses opportunités d''emploi et de formation pour les jeunes au Salon de l’Emploi de mars 2025, démontrant son engagement à promouvoir l''employabilité des jeunes dans le secteur ferroviaire.',
        'https://directinfosgabon.com/employabilite-des-jeunes-les-opportunites-de-la-setrag-exposees-au-salon-de-lemploi/',
        'Direct infos Gabon',
        'Éducation, Services, Numérique / Digital',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.325Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c6748a8c-0e7d-43c5-b3ea-b950ce086deb',
        'Infrastructures : les promesses de la Banque mondiale pour le Gabon',
        'La Banque Mondiale s’engage à soutenir le développement du Gabon en accélérant des projets structurants tels que la digitalisation du système de santé, la construction d’infrastructures urbaines dans sept villes de l’arrière-pays, et l’amélioration de l’accès à l’eau et à l’électricité.',
        'https://mediapostegabon.com/infrastructures-les-promesses-de-la-banque-mondiale-a-lendroit-du-gabon/',
        'Media Poste Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Agriculture',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.326Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44e0890e-e146-406d-9cf1-c722ffe9d748',
        'Diplomatie : Oligui Nguema a voyagé 36 fois hors du Gabon en 18 mois',
        'En 18 mois de transition, le président Brice Clotaire Oligui Nguema a réalisé 36 voyages à l’étranger pour défendre les intérêts du Gabon et éviter des sanctions internationales.',
        'https://www.gabonreview.com/cooperation-oligui-nguema-a-voyage-36-fois-hors-du-gabon-en-18-mois/',
        'Gabon Review',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.326Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '145bfd36-7172-4b53-aa8c-b471c87aac74',
        'Le REFELA Gabon reçu par la Ministre de la Femme, Elodie Diane Fouefoue épouse Sandjoh',
        'Une délégation du REFELA Gabon, dirigée par Gysèle Itoumba, a été reçue par la Ministre de la Femme et de la Protection de l’Enfance, Élodie Diane Fouefoue, le 19 mars.',
        'https://www.gabonews.com/fr/actus/politique/article/le-refela-gabon-recu-par-la-ministre-de-la-femme',
        'Gabonews',
        'Business Femme, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.326Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d0c1b84-71ea-43e0-8dac-ebaf4ff9fea1',
        'Oligui Nguema lance les travaux du nouveau pont d’Ebel-Abanga',
        'Le président Brice Clotaire Oligui Nguema a inauguré la construction du nouveau pont d’Ebel-Abanga visant à moderniser les infrastructures routières, améliorer la sécurité et stimuler l''économie locale au Gabon.',
        'https://gabonactu.com/blog/2025/03/19/oligui-nguema-lance-les-travaux-du-nouveau-pont-sur-la-banga-avec-la-pose-de-la-premiere-pierre/',
        'Gabon Actu',
        'Infrastructures, Services, Agriculture, Business Femme, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.326Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5c70a07-56fe-4fc9-abe0-8609caa1815a',
        'RSE : Sobraga offre 13 500 litres d’eau à 14 centres hospitaliers dans le Grand Libreville',
        'Sobraga poursuit son engagement sociétal en fournissant 13 500 litres d’eau potable à 14 centres hospitaliers du Grand Libreville dans le cadre de sa caravane de sensibilisation Akewa.',
        'https://directinfosgabon.com/rse-sobraga-offre-13-500-litres-deau-a-14-centres-hospitaliers-dans-le-grand-libreville/',
        'Direct infos Gabon',
        'Autres',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.327Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '05f86946-919c-4d55-9468-6ab56d7ad6a5',
        'Bilie-By-Nze : Entre héritage assumé et promesse de renouveau',
        'Alain-Claude Bilie-By-Nze, candidat à la présidentielle gabonaise de 2025, propose un programme ambitieux visant à réformer profondément les structures économiques et politiques du Gabon en abandonnant la rente pétrolière, en supprimant le Sénat, et en instaurant une société basée sur la transparence et la méritocratie pour restaurer la confiance des citoyens.',
        'https://www.gabonreview.com/bilie-by-nze-entre-heritage-assume-et-promesse-de-renouveau/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-20T00:00:00.000Z',
        '2025-09-15T23:06:12.327Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '684ed305-7dea-4826-848e-dc7cd6baae06',
        'Tribune / OLIGUI NGUEMA :  Défis et enjeux économiques (Par Jean-Fidèle Otandault)',
        'L''article analyse les défis économiques du Gabon et présente les initiatives du président de la Transition Brice Clotaire Oligui Nguema visant à moderniser le pays, diversifier son économie et promouvoir un développement durable.',
        'https://directinfosgabon.com/tribune-oligui-nguema-defis-et-enjeux-economiques-par-jean-fidele-otandault/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture, Tourisme',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.327Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc339c4a-a672-4c52-9508-6030bf87b2ef',
        'Oligui Nguema interpellé sur la situation précaire des 7 000 employés de la Holding HPO & Associés',
        'L''UDIS interpelle le président de la transition concernant la précarité de 7 000 employés de la Holding HPO & Associés, affectés par les problèmes judiciaires et l''arrêt brutal des activités de l''entreprise.',
        'https://www.gabonreview.com/oligui-nguema-interpelle-sur-la-situation-precaire-des-7-000-employes-de-la-holding-hpo-associes/',
        'Gabon Review',
        'Services, Éducation, Finances, Business Femme',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.327Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e027828a-f301-4950-b5e8-2cc0c2bd7e0c',
        'Le Chef de l’Etat communie avec les populations de Port-Gentil',
        'Le Chef de l’État gabonais, Général Brice Clotaire Oligui Nguema, a visité Port-Gentil où il a honoré la mémoire de Joseph Rendjambe Issani, annoncé la réhabilitation de l’ancien hôtel Dowé, la modernisation des infrastructures aéroportuaires, et échangé avec les populations locales sur les enjeux économiques, sociaux et sécuritaires.',
        'https://www.gabonews.com/fr/actus/societe/article/le-chef-de-l-etat-communie-avec-les-populations',
        'Gabonews',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14949fdc-2547-47b2-95cf-2a71c05be3c2',
        'L’Afrique face aux défis de l’intelligence artificielle : Une réunion ministérielle sous présidence marocaine',
        'Une réunion ministérielle présidée par le Maroc rassemble les responsables africains pour examiner les défis et les implications de l’intelligence artificielle sur la stabilité, la gouvernance et le développement du continent.',
        'https://www.gabonews.com/fr/actus/economie-numerique/article/l-afrique-face-aux-defis-de-l-intelligence',
        'Gabonews',
        'Numérique / Digital, Éducation, Services',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2f0f1c1-09fc-47bd-b64c-4a470de297dd',
        'Élim/CDM 2026 : les Seychelles dominés (3-0) par le Gabon !',
        'Les Panthères du Gabon ont remporté une victoire convaincante 3-0 contre les Seychelles lors de la 5e journée des éliminatoires de la Coupe du Monde 2026, renforçant ainsi leur position en tête du groupe F.',
        'https://gabonmediatime.com/elim-cdm-2026-les-seychelles-domines-3-0-par-le-gabon/',
        'Gabon Media Time',
        'Autres',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a8e87ece-38a4-44bd-b2b0-1383ee04610d',
        'Assemblée nationale : Trois projets de loi de Charles M’ba à la Commission des Finances',
        'Le ministre des Comptes publics et de la Dette, Charles M’ba, a présenté trois projets de loi à la Commission des Finances de l’Assemblée nationale visant à ratifier des ordonnances permettant à l’État gabonais de contracter des emprunts internationaux pour financer des projets d’infrastructure majeurs.',
        'https://www.gabonreview.com/assemblee-nationale-trois-projets-de-loi-de-charles-mba-a-la-commission-des-finances/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services, Agriculture',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b822c8f3-c3a7-4d85-b1c6-9ebd6cd980e9',
        'Gabon : Signature d’une convention pour l’exploitation du fer de Baniaka',
        'Le Gabon a signé une convention minière avec la société Reminac pour exploiter le gisement de fer de Baniaka, créant environ 700 emplois directs et 2 000 emplois indirects tout en stimulant le développement économique local.',
        'https://gabonmediatime.com/gabon-signature-dune-convention-pour-lexploitation-du-fer-de-baniaka/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b27f8d75-d3c9-4a7b-a5d7-207e6e3f0cf9',
        'Publié le 20 / 03 / 2025',
        'Le Parti démocratique gabonais annonce qu''il décidera de son soutien lors des élections présidentielles du 12 avril après avoir examiné les programmes des différents candidats.',
        'https://union.sonapresse.com/fr/le-pdg-joue-lequilibrisme-politique',
        'L''Union',
        'Autres',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'abcba95c-5941-4b02-b8cd-2fdf11981e93',
        'Présidentielle 2025 : Nicole Assélé appelle au sursaut patriotique et annonce son soutien à Bilie-By-Nzé',
        'Nicole Assélé appelle à l''unité patriotique et annonce son soutien au candidat Alain Claude Bilie-By-Nzé pour instaurer un changement radical lors de la présidentielle 2025 au Gabon.',
        'https://gabonmediatime.com/presidentielle-2025-nicole-assele-appelle-au-sursaut-patriotique-et-annonce-son-soutien-a-bilie-by-nze/',
        'Gabon Media Time',
        'Autres',
        '2025-03-21T00:00:00.000Z',
        '2025-09-15T23:06:12.328Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

