-- Batch 7 - Section 9/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'c70e26a5-a53a-4a42-a201-19e7e5435326',
        'Gabon : Activités commerciales exercées par des expatriés, la loi existe, il faut l’appliquer !',
        'La réglementation en vigueur en Guinée pour les activités commerciales exercées par des expatriés doit être appliquée pour garantir leur légalité et éviter toute infraction.',
        'https://gabonmediatime.com/gabon-activites-commerciales-exercees-par-des-expatries-la-loi-existe-il-faut-lappliquer/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8044855-bc4e-4365-9a6b-fe9d3edb267e',
        'Gabon : Tita Nzebi enfin en concert, là où tout a commencé !',
        'Tita Nzebi a enfin réalisé son premier concert, marquant un moment important dans sa carrière musicale en Guinée équatoriale.',
        'https://gabonmediatime.com/gabon-tita-nzebi-enfin-en-concert-la-ou-tout-a-commence/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1941e174-a0f8-427c-bf57-490219b9dd88',
        'Gabon : Oligui Nguema promet une «souveraineté économique» et une planification équitable du développement',
        'Olégui Nguema promet une souveraineté économique pour le Gabon en mettant en place une planification équitable du développement.',
        'https://gabonmediatime.com/gabon-oligui-nguema-promet-une-souverainete-economique-et-une-planification-equitable-du-developpement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d8c7af6-ed68-477e-b71a-42e80dec7f31',
        'Tribune libre à Son Excellence le Président de la République, Chef de l’État, Brice Clotaire OLIGUI NGUEMA',
        'Le président de la République adresse un message sincère et engagé, soulignant l''importance de la cohésion nationale et de l''effort collectif pour le développement du pays.',
        'https://kongossanews.info/tribune-libre-a-son-excellence-le-president-de-la-republique-chef-de-letat-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '783d9956-805a-4b82-b850-ec691962ad5f',
        '[Editorial] Souveraineté, chantiers, ambitions : la Ve République à l’épreuve de l’économie',
        'L''article examine les défis liés à la souveraineté et à l''économie en Afrique, en soulignant la nécessité de renforcer les capacités locales et d''adopter des stratégies ambitieuses pour assurer un développement durable et indépendant.',
        'https://kongossanews.info/editorial-souverainete-chantiers-ambitions-la-ve-republique-a-lepreuve-de-leconomie/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ecc15e6-7c7a-4484-bfd2-45ddaa2799d8',
        'Gabon/Émirats arabes unis : Libreville et Abou Dhabi accélèrent sur les partenariats stratégiques',
        'Le Gabon et les Émirats arabes unis renforcent leur coopération à travers la signature de nouveaux accords stratégiques visant à développer des partenariats dans divers secteurs.',
        'https://kongossanews.info/gabon-emirats-arabes-unis-libreville-et-abou-dhabi-accelerent-sur-les-partenariats-strategiques/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e327bb02-6523-4481-a769-d2cb4475077f',
        'Gabon : Activités commerciales exercées par des expatriés, la loi existe, il faut l’appliquer !',
        'L''article explique que la loi gabonaise sur l’exercice des activités commerciales par des étrangers doit être appliquée pour réguler la présence d’expatriés exerçant des activités commerciales sans respecter la réglementation en vigueur.',
        'https://gabonmediatime.com/gabon-activites-commerciales-exercees-par-des-expatries-la-loi-existe-il-faut-lappliquer/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e583eda0-943e-43e8-92c1-d5cfa1c18bde',
        'Gabon : Tita Nzebi enfin en concert, là où tout a commencé !',
        'Tita Nzebi a enfin donné un concert à Libreville, marquant le début d''une nouvelle étape dans sa carrière musicale après une longue période d''attente.',
        'https://gabonmediatime.com/gabon-tita-nzebi-enfin-en-concert-la-ou-tout-a-commence/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '656dbe97-4d07-4eeb-8c4c-90f9c756bd63',
        'Gabon : Oligui Nguema promet une «souveraineté économique» et une planification équitable du développement',
        'Le président Gabonais a promis de renforcer la souveraineté économique du pays et de promouvoir un développement équitable grâce à une planification stratégique.',
        'https://gabonmediatime.com/gabon-oligui-nguema-promet-une-souverainete-economique-et-une-planification-equitable-du-developpement/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '714cb1c1-b0ed-4035-bc52-8c106b2fe963',
        'Commerce : Le Togo demeure le premier founisseur africain du Gabon au 1er trimestre 2025',
        'Au premier trimestre 2025, le Togo est resté le principal fournisseur africain du Gabon, principalement grâce à ses exportations de produits pétroliers, avec une part de marché de 4,1 %.',
        'https://directinfosgabon.com/commerce-le-togo-demeure-le-premier-founisseur-africain-du-gabon-au-1er-trimestre-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '755ecf16-fb8e-4a36-8728-7bbd294d7f92',
        'Secteur informel au Gabon : Plus de 80 % des entreprises détenues par des étrangers',
        'Le secteur informel au Gabon représente plus de 62 % des entreprises, avec une forte présence d’étrangers, soulignant une économie largement non formelle et peu régulée.',
        'https://directinfosgabon.com/secteur-informel-au-gabon-plus-de-80-des-entreprises-detenues-par-des-etrangers/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06eece25-de65-4cec-983a-ccb7323f15c4',
        'Omar Denis Junior Bongo Ondimba reprend la gestion de l’Hôtel Poubara',
        'Omar Denis Junior Bongo Ondimba, fils de l''ancien président gabonais, reprend la gestion de l''hôtel Poubara en créant une société dédiée, indiquant une orientation vers le secteur hôtelier plutôt que la politique.',
        'https://directinfosgabon.com/omar-denis-junior-bongo-ondimba-reprend-la-gestion-de-lhotel-poubara/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fef6d99-0bc9-4f78-9f94-421b6769b19c',
        'Population : Le Gabon premier pays africain en proportion d’immigrés',
        'Le Gabon compte la plus grande proportion d’immigrés en Afrique, avec près de 19 % de sa population composée d’étrangers, grâce à sa stabilité et ses opportunités économiques.',
        'https://directinfosgabon.com/population-le-gabon-premier-pays-africain-en-proportion-dimmigres/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'caff1e72-7e92-44fb-ae03-8b1349628f69',
        'Van Rudy Bouka Bouassi  écope de 17 ans de prison pour vol aggravé',
        'Van Rudy Bouka Bouassi a été condamné à 17 ans de prison pour plusieurs infractions, dont des vols aggravés.',
        'https://gabonactu.com/blog/2025/08/18/van-rudy-bouka-bouassi-ecope-de-17-ans-de-prison-pour-vol-aggrave/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '041ce2f2-c008-44b8-b748-aea76179c075',
        'Un jeune juriste « assassiné » dans son domicile à Akanda',
        'Un jeune juriste a été assassiné à son domicile à Akanda, une commune proche de Libreville.',
        'https://gabonactu.com/blog/2025/08/18/un-jeune-juriste-assassine-pres-de-son-domicile-a-akanda/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b179a94f-1695-44d4-98ce-2a3acd0b2b7c',
        'Port-Gentil : le tribunal inflige 15 ans de prison à Stephen Enda Zokou pour coups mortels',
        'Un homme gabonais de 35 ans a été condamné à 15 ans de prison pour avoir tué quelqu’un lors d''une agression.',
        'https://gabonactu.com/blog/2025/08/18/port-gentil-le-tribunal-inflige-15-ans-de-prison-a-stephen-enda-zokou-pour-coups-mortels/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '851c6540-4262-407f-801c-6045ad753e67',
        'Basket-ball : l’entraineur Ambroise Ambourouet suspendu à titre conservatoire',
        'L’entraîneur Ambroise Ambourouet a été suspendu provisoirement par la Ligue de basket-ball de l’Estuaire en attendant une décision disciplinaire, tandis que son club accepte les sanctions et demande le paiement d’une amende.',
        'https://agpgabon.ga/basket-ball-lentraineur-ambroise-ambourouet-suspendu-a-titre-conservatoire/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cfb35889-402e-4267-a388-c5cb8a1d068e',
        'Inauguration du plus grand drapeau du Gabon au Mont-Bouët : un symbole d’unité et de souveraineté',
        'Le président gabonais a inauguré le plus grand drapeau du pays au Mont-Bouët, symbole d’unité et de souveraineté, à l’occasion du 65e anniversaire de l’indépendance.',
        'https://gabonactu.com/blog/2025/08/18/inauguration-du-plus-grand-drapeau-du-gabon-au-mont-bouet-un-symbole-dunite-et-de-souverainete/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc1d62b0-4b3d-42a8-b017-7da43c84137a',
        'L’intelligence artificielle au service de l’inclusion numérique en Afrique',
        'L''intelligence artificielle peut aider à réduire la fracture numérique en Afrique en facilitant l''accès à l''éducation, à la santé et aux services financiers pour tous.',
        'https://www.gabonreview.com/lintelligence-artificielle-au-service-de-linclusion-numerique-en-afrique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '88c0b065-c7c5-4b35-9474-f5a6fd8b3abf',
        'Gabon/Accident de la route : un mort et plusieurs blessés sur l’axe Lambaréné-Fougamou',
        'Un accident sur l’axe Lambaréné-Fougamou a fait un mort et plusieurs blessés après qu’un camion a violemment percuté un bus lorsqu’il a essayé d’éviter un nid-de-poule.',
        'https://agpgabon.ga/gabon-accident-de-la-route-un-mort-et-plusieurs-blesses-sur-laxe-lambarene-fougamou/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af7db116-ecc0-4c65-9493-5d964bc6f3fc',
        'Le Chef de l’État s’entretient avec le Ministre du CommerceExtérieur des Émirats Arabes Unis',
        'Le président de la République a rencontré le ministre du Commerce extérieur des Émirats Arabes Unis pour renforcer la coopération bilatérale et explorer de nouveaux partenariats économiques.',
        'https://vxp241.com/2025/08/18/le-chef-de-letat-sentretient-avec-le-ministre-du-commerceexterieur-des-emirats-arabes-unis/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2c7262e7-f344-4841-86a5-36bad291e440',
        'Auto entreprenariat et insertion sociale : Des kits de démarrage pour 155 jeunes filles',
        '155 jeunes filles déscolarisées ont reçu des kits de démarrage pour favoriser leur autonomie et leur insertion sociale après avoir suivi une formation qualifiante grâce à un partenariat avec le ministère des Affaires sociales.',
        'https://gabonactu.com/blog/2025/08/18/autonomie-et-insertion-sociale-des-kits-de-demarrage-pour-155-jeunes-filles/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c62eb074-f1af-46dc-b4f6-2a648f0c64b4',
        'ULCO : Nouvelle application de gestion scolaire',
        'Une startup gabonaise a développé une application appelée ULCO pour simplifier la gestion des écoles et le suivi des élèves.',
        'https://gabonactu.com/blog/2025/08/18/ulco-nouvelle-application-de-gestion-scolaire/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9bd7ab16-8525-413c-b2f4-4fc26ad35fee',
        'Tragique découverte à Ndjolé : Éloge Awong Meka retrouvé sans vie dans l’Ogooué',
        'Un enseignant respecté à Ndjolé a été retrouvé mort dans l’Ogooué, plongeant la ville dans le deuil.',
        'https://gabonactu.com/blog/2025/08/18/tragique-decouverte-a-ndjole-eloge-awong-meka-retrouve-sans-vie-dans-logooue/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d044757-9f92-4f6d-983f-0015a9a6265b',
        'Gabon, Roi Béni et Nazih : quand le crime organisé fraye avec les élites du pouvoir',
        'L''article montre comment des activités criminelles, impliquant des figures comme Roi Béni et Nazih, sont liées à des relations de pacte et de complicité entre des élites politiques, militaires et criminelles au sein de l''État gabonais.',
        'https://www.gabonreview.com/gabon-roi-beni-et-nazih-quand-le-crime-organise-fraye-avec-les-elites-du-pouvoir/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ac58072-192c-40e7-9ca2-248724613029',
        'Des drapeaux et des tenus d''apparat pour les auxiliaires de commandement remis par Maël Nkoghe Abeghe',
        'Maël Nkoghe Abeghe a distribué des drapeaux et des tenues d''apparat à plus de 71 chefs de villages et responsables locaux du département du Haut-Ntem, pour renforcer l''esprit patriotique et valoriser les symboles de la République gabonaise.',
        'https://www.gabonews.com/fr/actus/politique/article/des-drapeaux-et-des-tenus-d-apparat-pour-les',
        'Gabonews',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93110d6d-5646-46ed-a03e-fdfb5ee5e0f4',
        'Bénin : un bus chute dans le fleuve Ouémé, un passager tué et 44 portés disparus',
        'Un bus qui transportait 54 personnes est tombé dans le fleuve Ouémé en voyageant au centre du Bénin, faisant un mort et laissant 44 personnes portées disparues.',
        'https://agpgabon.ga/benin-un-bus-chute-dans-le-fleuve-oueme-un-passager-tue-et-44-portes-disparus/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc1edc0f-c5e9-40f4-a556-e43e8339ed70',
        'L’Ambassade de la République de Corée recrute un Expert chargé de l’Énergie et des Infrastructures',
        'L''ambassade de Corée au Gabon cherche à recruter un expert chargé de l''énergie et des infrastructures pour analyser les problématiques du secteur, organiser des rencontres professionnelles et soutenir la coopération économique entre les deux pays.',
        'https://agpgabon.ga/lambassade-de-la-republique-de-coree-recrute-un-expert-charge-de-lenergie-et-des-infrastructures/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01f645bc-2707-4d5c-b364-e96a6fcf301b',
        'Extraditions judiciaires : Harmoniser les procédures et les pratiques',
        'Un atelier a été lancé pour uniformiser les procédures et pratiques d''extradition judiciaire entre les pays afin de renforcer la coopération judiciaire.',
        'https://gabonactu.com/blog/2025/08/18/extraditions-judiciaires-harmoniser-les-procedures-et-les-pratiques/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b10a48b5-d34c-4515-93e9-77558ce79053',
        'Fin annoncée de la géopolitique : 35 ans de surplace',
        'L''article critique le fait que la géopolitique en Afrique, notamment au Gabon, est restée stagnante depuis 35 ans, malgré les enjeux politiques et sociaux importants, et invite à une réflexion sur son futur.',
        'https://www.gabonreview.com/fin-annoncee-de-la-geopolitique-35-ans-de-surplace/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f7c104b-56b5-44d8-8a51-baccb43a0ea2',
        'Gabon/Éducation nationale : Camélia Ntoutoume Leclercq fait le point sur l’orientation en sixième',
        'Le ministre de l’Éducation nationale a rencontré l''administration et les parents pour discuter de l''affectation des enseignants, des mutations et de l''orientation en classe de sixième, avec un nombre record d''élèves entrant dans cette classe cette année.',
        'https://agpgabon.ga/gabon-education-nationale-camelia-ntoutoume-leclercq-fait-le-point-sur-lorientation-en-sixieme/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '542445f6-e33b-4eb3-a010-b08260734ba6',
        'Gabon/National Foot 1 : Saturnin Ibela, nouvel entraîneur d’Oyem AC',
        'Saturnin Ibela devient l''entraîneur d''Oyem AC pour sa première saison en D1, en remplacement de Patrick Nshimirimana, et mise sur son expérience avec Bouenguidi Sports.',
        'https://agpgabon.ga/gabon-national-foot-1-saturnin-ibela-nouvel-entraineur-doyem-ac/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '152e235b-472e-44bc-8de0-9492c0e5aa26',
        'Madagascar-Sommet de la SADC : Renforcer la coopération régionale et le développement durable',
        'Le sommet de la SADC en Madagascar a permis aux pays membres de discuter de projets pour renforcer leur coopération économique, sécuritaire et leur capacité à faire face aux défis environnementaux, en se concentrant sur la mise en œuvre du plan stratégique régional.',
        'https://agpgabon.ga/madagascar-sommet-de-la-sadc-renforcer-la-cooperation-regionale-et-le-developpement-durable/',
        'AGP',
        'Business Intelligence',
        '2025-08-18T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f28bacdd-ea76-4b93-a8a9-4e1f5a3206a4',
        'Trans’urb gratuit à Libreville va faire fortune en province',
        'La gratuité du transport en commun à Libreville pourrait générer de nouvelles opportunités économiques dans les provinces comme Oyem, Tchibanga, Mouila ou Makokou.',
        'https://gabonactu.com/blog/2025/08/18/transurb-gratuit-a-libreville-va-faire-fortune-en-province/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b625886a-e331-421f-831b-ab32a3d001cd',
        'Publié le 18 / 08 / 2025',
        'L''article explique comment le nouveau modèle éducatif gabonais vise à améliorer la formation des jeunes en mettant l''accent sur l''innovation, la formation professionnelle et l''adaptation aux besoins du marché.',
        'https://union.sonapresse.com/fr/editorial-le-nouveau-modele-gabonais',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1663c6e4-faf1-4d79-84ca-757d12dcfabf',
        'Publié le 18 / 08 / 2025',
        'Les forces de défense et de sécurité du Sénégal ont montré leur puissance et leur organisation lors du 65e anniversaire de l’indépendance, soulignant leur rôle dans la stabilité du pays.',
        'https://union.sonapresse.com/fr/independance-65-les-forces-de-defense-et-de-securite-dans-leur-splendeur',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '43217541-e294-4aa3-937a-08b7cacb4b46',
        'Publié le 18 / 08 / 2025',
        'Le blog rend hommage au Père de la Nation tout en inaugurant de nouveaux édifices publics destinés à améliorer la vie des citoyens.',
        'https://union.sonapresse.com/fr/hommage-au-pere-de-la-nation-et-inaugurations-dedifices-publics',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a7ae6e39-60ee-4e11-a08c-5c59065a908a',
        'Mouvement d’humeur : les employés d’Olam Makouké montent au créneau Habitat : des maisons pour les Forces de Défense et de Sécur...',
        'Les employés d''Olam Makouke dénoncent des pratiques injustes et exigent de meilleures conditions de travail à travers un mouvement de mobilisation.',
        'https://mediapostegabon.com/mouvement-dhumour-les-employes-dolam-makouke-montent-au-creneau/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '078b8ce5-55a0-4323-8ddb-d915da1af62b',
        'Gabon/Musique : Koba Building annonce son retour au pays',
        'Le rappeur gabonais Koba Building a annoncé sur Facebook son intention de rentrer au pays après plusieurs années d''exil, suscitant l''enthousiasme de ses fans.',
        'https://agpgabon.ga/gabon-musique-koba-building-annonce-son-retour-au-pays/',
        'AGP',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e1876e0-842d-4767-9ac0-7f515b9d3f2a',
        'Publié le 18 / 08 / 2025',
        'L’article présente un nouveau modèle éducatif au Gabon visant à moderniser le système scolaire en intégrant davantage les technologies et en adaptant l’enseignement aux enjeux du développement durable et de l''économie numérique.',
        'https://union.sonapresse.com/fr/editorial-le-nouveau-modele-gabonais',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'acbcbcde-1c1a-456d-a29f-cdf7ff3a24f9',
        'Publié le 18 / 08 / 2025',
        'Les forces de défense et de sécurité du Mali ont montré leur puissance et leur organisation lors du 65e anniversaire de l’indépendance, mettant en valeur leur rôle dans la stabilité du pays.',
        'https://union.sonapresse.com/fr/independance-65-les-forces-de-defense-et-de-securite-dans-leur-splendeur',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'df8293d2-1eef-42f9-9ed0-677fcaeda306',
        'Publié le 18 / 08 / 2025',
        'L''article rend hommage au père de la nation et relate l''inauguration de plusieurs édifices publics en son honneur, symbolisant la reconnaissance et le développement dans le pays.',
        'https://union.sonapresse.com/fr/hommage-au-pere-de-la-nation-et-inaugurations-dedifices-publics',
        'L''union',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a4f815d-e6dd-4080-bac5-1d4400497c20',
        'Mouvement d’humeur : les employés d’Olam Makouké montent au créneau Habitat : des maisons pour les Forces de Défense et de Sécur...',
        'Les employés d’Olam Makouke ont réagi à un mouvement humoristique en exprimant leur soutien et en dénonçant les incompréhensions ou tensions liées à cette initiative.',
        'https://mediapostegabon.com/mouvement-dhumour-les-employes-dolam-makouke-montent-au-creneau/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c0f4dfc-139c-4b01-9c37-05f6f30ea2cc',
        'Tensions entre internautes béninois et gabonais : Cotonou réagit, Libreville se mure dans le silence',
        'Des tensions apparaissent entre internautes béninois et gabonais sur les réseaux sociaux, et le gouvernement gabonais reste silencieux face à ces échanges.',
        'https://gabonmediatime.com/tensions-entre-internautes-beninois-et-gabonais-cotonou-reagit-libreville-se-mure-dans-le-silence/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9660f8d4-ca24-4898-b942-cbbadfbaa04f',
        'Gabon : entre pacte tacite et République, quel avenir pour la Mairie de Libreville ?',
        'L''article examine l''avenir de la mairie de Libreville face à l''équilibre fragile entre un pacte tacite et une République, soulignant les enjeux de gouvernance et de gestion locale.',
        'https://gabonmediatime.com/gabon-entre-pacte-tacite-et-republique-quel-avenir-pour-la-mairie-de-libreville/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47a97e29-183c-4d0f-adce-6e20a4ae2fa5',
        'Kôba  Building annonce son retour au Gabon !',
        'Koba Building annonce son retour au Gabon pour relancer ses activités de construction et de développement immobilier dans le pays.',
        'https://gabonmediatime.com/koba-building-annonce-son-retour-au-gabon/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '20dc667c-2233-4fb5-8f79-f586045fdb9b',
        'Louétsi-Bibaka : La population dénonce une tentative de manipulation politique',
        'Les populations dénoncent une tentative de manipulation politique lors du processus électoral, dénonçant des pratiques visant à influencer le vote ou à fausser la transparence du scrutin.',
        'https://kongossanews.info/louetsi-bibaka-la-population-denonce-une-tentative-de-manipulation-politique/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6ffe72a4-7cbd-4f88-83ac-9778fb7bc838',
        'Politique. Emplois interdits aux étrangers au Gabon : “Attention aux dérives xénophobes !”',
        'Le gouvernement gabonais prévoit d''interdire aux ressortissants d''autres pays africains d''exercer certaines activités dans le commerce informel, ce qui suscite des préoccupations concernant la xénophobie et ses possibles dérives.',
        'https://www.courrierinternational.com/article/politique-emplois-interdits-aux-etrangers-au-gabon-attention-aux-derives-xenophobes_234089?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74b4426a-34cc-4d82-b827-9969e11f658a',
        'Carte de séjour au Gabon : Pourquoi 150 000 FCFA pour les Français et 800 000 pour les Africains ?',
        'Au Gabon, les étrangers résidents paient beaucoup moins cher (150 000 FCFA) pour leur carte de séjour que les citoyens africains (jusqu’à 800 000 FCFA), ce qui soulève des questions d''inégalité.',
        'https://directinfosgabon.com/carte-de-sejour-au-gabon-pourquoi-150-000-fcfa-pour-les-francais-et-800-000-pour-les-africains/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cbe05da7-d377-46cc-903d-3e3c5d53093a',
        'Décoration urbaine : Le marocain Nasli Holding prêt à relooker Libreville',
        'Une entreprise marocaine, Nasli Holding, prévoit de réaménager et décorer la ville de Libreville au Gabon en s''inspirant de son concept de rue piétonne haut de gamme, similaire à celui de Marrakech.',
        'https://directinfosgabon.com/decoration-urbaine-le-marocain-nasli-holding-pret-a-relooker-libreville/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-19T00:00:00.000Z',
        '2025-09-15T23:06:12.494Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

