-- Batch 5 - Section 5/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '8b653ae2-059f-4b96-8255-2e9b64f117c4',
        'Afreximbank 2025 : Oligui Nguema à Abuja pour élargir les partenariats du Gabon',
        'Le président gabonais a participé à une conférence à Abuja pour renforcer la coopération économique et établir de nouveaux partenariats dans le cadre de la diversification de l’économie du Gabon.',
        'https://www.gabonreview.com/afreximbank-2025-oligui-nguema-a-abuja-pour-elargir-les-partenariats-du-gabon/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04e6bb20-573f-42e6-ae24-711c90d02326',
        'Le Chef de l''État reçoit un émissaire du Président de la République de Guinée Equatoriale',
        'Le président gabonais a rencontré un ministre équatoguinéen, porteur d’un message du président de la Guinée équatoriale, pour renforcer les liens entre les deux pays.',
        'https://www.gabonews.com/fr/actus/diplomatie/article/le-chef-de-l-etat-recoit-un-emissaire-du-20989',
        'Gabonews',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3e7b898-71c8-43cd-934e-49759ea2a743',
        'Au Gabon, la pièce «Mudumumbula» enfièvre le festival «Coup de théâtre»',
        'Un festival de théâtre nommé « Coup de théâtre » s''est ouvert au Gabon du 26 au 28 juin 2025, avec la représentation de plusieurs pièces, dont un monologue intitulé « Mudumumbula » (le tonnerre), adapté d''une œuvre de l''auteur franco-colombien Armando Vargas Sarmiento.',
        'https://www.rfi.fr/fr/afrique/20250627-au-gabon-la-pi%C3%A8ce-mudumumbula-enfi%C3%A8vre-le-festival-coup-de-th%C3%A9%C3%A2tre',
        'RFI',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0882b081-971e-413b-9383-e60a6f435a17',
        'Mine de fer de Milingui : Havilah Mining Gabon prête pour la transformation locale du minerai',
        'L''entreprise sud-africaine Havilah Mining Gabon prévoit de valoriser le minerai de fer de la mine de Milingui en le transformant localement au Gabon, dans le cadre de la politique nationale de valorisation des ressources minérales.',
        'https://www.gabonreview.com/mine-de-fer-de-milingui-havilah-mining-gabon-prete-pour-la-transformation-locale-du-minerai/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5797d6de-0ba2-4d09-a582-aa4798f98403',
        'Gabon : Boostée par ses résultats, Samb’a Assurances voit plus grand et plus loin',
        'Samb’a Assurances Gabon, après une croissance exceptionnelle en six mois avec un chiffre d’affaires de 187 millions de FCFA en 2024, prévoit de s’étendre en Afrique, notamment au Cameroun et en RDC.',
        'https://www.gabonreview.com/gabon-boostee-par-ses-resultats-samba-assurances-voit-plus-grand-et-plus-loin/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6bec567d-a62b-42ab-8338-b5e6fc25fc70',
        'Foire agricole Marigovèenne à prix bas du 25 au 30 août 2025 à Port-Gentil',
        'Une foire agricole organisée à Port-Gentil du 25 au 30 août 2025 vise à promouvoir la valorisation et la transformation des produits locaux pour lutter contre le coût de la vie.',
        'https://gabonactu.com/blog/2025/06/27/foire-agricole-marigoveenne-a-prix-bas-du-25-au-30-aout-2025-a-port-gentil/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '820c6ae8-0da9-46ed-b613-822e12e8579e',
        'Madagascar fait appel à l’expertise d’une entreprise émiratie pour la construction d’une centrale solaire de 50 MW',
        'Les autorités malgaches ont choisi l''entreprise émiratie Global South Utilities pour construire une centrale solaire de 50 MW dans le pays.',
        'https://gabonactu.com/blog/2025/06/27/madagascar-fait-appel-a-lexpertise-dune-entreprise-emiratie-pour-la-construction-dune-centrale-solaire-de-50-mw/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '84eae21e-91e5-4873-86d9-bf5b1e47edba',
        '80 ans de l’ONU : le Gabon réaffirme son attachement au multilatéralisme à New York',
        'Le Gabon a participé à une cérémonie à New York pour célébrer les 80 ans de l’ONU, réaffirmant son engagement en faveur du multilatéralisme et de la coopération internationale.',
        'https://gabonactu.com/blog/2025/06/27/80-ans-de-lonu-le-gabon-reaffirme-son-attachement-au-multilateralisme-a-new-york/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4947c946-e105-4387-ad47-d0a601ef2893',
        'Débarcadères d’Ambowe, de Bambouchines et d’Ozoungué : des constats alarmants, mais aussi des espoirs',
        'Des observations alarmantes ont été faites sur l’état des débarcadères d’Ambowe, Bambouchines et Ozoungué, mais il existe aussi des initiatives et des espoirs pour améliorer leur gestion et leur développement.',
        'https://www.gabonreview.com/debarcaderes-dambowe-de-bambouchines-et-dozoungue-des-constats-alarmants-mais-aussi-des-espoirs/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f2063e0-ee38-4e92-9192-cd187275de02',
        'Gabon : 34,6 % de la population vit sous le seuil de pauvreté, selon la Banque mondiale',
        'Plus d’un tiers de la population gabonaise vit sous le seuil de pauvreté, en dépit d’une croissance économique modérée, en raison du manque d’opportunités d’emploi et de faibles dépenses sociales.',
        'https://www.gabonreview.com/gabon-346-de-la-population-vit-sous-le-seuil-de-pauvrete-selon-la-banque-mondiale/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0db3bb3b-60c1-4e0a-a116-4bcbd48c3bc1',
        'Le Président Oligui Nguema à Abuja pour la 32ᵉ Assemblée annuelle d''Afreximbank',
        'Le président Brice Clotaire Oligui Nguema a rendu hommage aux forces armées avant de partir pour Abuja, où il a rencontré des autorités pour renforcer la stabilité et l’unité nationale.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-president-oligui-nguema-a-abuja-pour-la-32%E1%B5%89',
        'Gabonews',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab7acd08-d742-4170-9ebf-ed1fd5fa20b3',
        'Mbigou – Le PDG à l''épreuve du renouveau : entre fidélité au terrain et réorganisation stratégique',
        'Le Parti Démocratique Gabonais (PDG), absent du pouvoir depuis 2023, prépare une relance politique pour rester influent en vue des prochaines élections législatives et locales.',
        'https://www.gabonews.com/fr/actus/politique/article/mbigou-le-pdg-a-l-epreuve-du-renouveau-entre',
        'Gabonews',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bf83550-0570-4f6e-96f0-cc20ca050020',
        'Renforcement de la coopération économique : Le Président Oligui Nguema reçoit Tony Elumelu à Abuja',
        'Le président gabonais a rencontré le responsable du groupe bancaire nigérian UBA à Abuja pour renforcer les liens économiques entre le Gabon et le Nigeria.',
        'https://www.gabonews.com/fr/actus/economie/article/renforcement-de-la-cooperation-economique-le',
        'Gabonews',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dee5a755-02a9-48ef-869e-00fa85c6be51',
        'ANBG : Place au leadership de Paule Elisabeth Désirée Mboumba Lassy',
        'Le ministre de l''Enseignement supérieur a installé Paule Elisabeth Désirée Mboumba Lassy en tant que nouvelle directrice générale de l’Agence nationale, soulignant l''importance de son leadership.',
        'https://gabonactu.com/blog/2025/06/27/anbg-place-au-leadership-de-paul-elisabeth-desiree-mboumba-lassy/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95cad6bb-dac9-475f-a24e-4435fb538b1f',
        'Port- Gentil : deux ateliers pour former les inspecteurs à la lutte contre la pêche illégale.',
        'Deux ateliers de formation organisés en mai et juin 2025 à Port-Gentil ont permis de renforcer les compétences des inspecteurs dans la lutte contre la pêche illégale.',
        'https://gabonactu.com/blog/2025/06/27/port-gentil-deux-ateliers-pour-former-les-inspecteurs-a-la-lutte-contre-la-peche-illegale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '018471c3-ee27-404f-9bbe-55ec0fea17d5',
        '80e anniversaire de l’ONU : le Gabon toujours attaché aux valeurs de la Charte fondatrice',
        'Le Gabon réaffirme son attachement aux valeurs fondamentales de la Charte de l''ONU, lors de la célébration du 80e anniversaire de l''organisation, en soulignant son engagement envers la paix et la coopération internationale.',
        'https://www.gabonreview.com/80e-anniversaire-de-lonu-le-gabon-toujours-attache-aux-valeurs-de-la-charte-fondatrice/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6f4a774-6286-4911-9804-248894379c76',
        'Gabon/Faits divers : CIMAF Gabon mis en cause après un incident à Ntoum impliquant un enfant',
        'Un jeune garçon de 6 ans a été gravement blessé par la chute d’un bloc de ciment mal entreposé près d’un chantier de CIMAF Gabon à Ntoum, mais il est maintenant hors de danger.',
        'https://agpgabon.ga/gabon-faits-divers-cimaf-gabon-mis-en-cause-apres-un-incident-a-ntoum-impliquant-un-enfant/',
        'AGP',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cda62a81-75fd-4a15-a43a-a140fabddd90',
        'Karaté/Election Fégakama : Me Jean René Akoghet veut structurer la discipline',
        'Me Jean-René Akoghet, candidat à la présidence de la fédération de karaté au Gabon, souhaite mettre en place un système structuré, inclusif et performant pour garantir aux pratiquants des conditions optimales de développement et d''excellence dans la discipline.',
        'https://agpgabon.ga/karate-election-fegakama-me-jean-rene-akoghet-veut-structurer-la-discipline/',
        'AGP',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5f77f19-4335-4e02-8f7d-f5a9c8cf15f2',
        'Nigéria/AAM2025 – Débat de haut niveau sur l’autonomie financière de l’Afrique dans un monde multipolaire',
        'Des anciens chefs d''État africains ont discuté à Abuja de l’importance de renforcer l’autonomie financière de l’Afrique en s’appuyant sur ses ressources internes et en réformant l’architecture financière mondiale, face aux enjeux de souveraineté et d''intégration régionale.',
        'https://agpgabon.ga/nigeria-aam2025-debat-de-haut-niveau-sur-lautonomie-financiere-de-lafrique-dans-un-monde-multipolaire/',
        'AGP',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d03e290-20b0-4a95-8034-320909848e32',
        'Gabon–Afreximbank : un partenariat stratégique de 3,2 milliards de dollars pour propulser l’industrialisation',
        'Le Gabon a signé avec Afreximbank un partenariat de 3,2 milliards de dollars pour développer ses ressources minières, améliorer son énergie et moderniser ses infrastructures, dans le but d’accélérer son industrialisation.',
        'https://www.gabonreview.com/gabon-afreximbank-un-partenariat-strategique-de-32-milliards-de-dollars-pour-propulser-lindustrialisation/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '835e4dc4-9596-42dc-bc41-3e58fee59b3c',
        'L’AGADEV réunit le secteur aérien pour faciliter la mise en œuvre de la Contribution Carbone au Gabon',
        'Un atelier de concertation organisé par l''AGADEV a réuni les acteurs du secteur aérien gabonais pour faciliter la mise en œuvre de la Contribution Carbone, un dispositif visant à réduire l''impact environnemental du transport aérien dans le pays.',
        'https://vxp241.com/2025/06/27/lagadev-reunit-le-secteur-aerien-pour-faciliter-la-mise-en-oeuvre-de-la-contribution-carbone-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9fc0433-f86b-4d28-9798-bfcb631b8ebf',
        'Nigéria/AAM2025 : le Gabon obtient 1600 milliards FCFA d’Afreximbank pour accélérer sa transformation industrielle',
        'Le Gabon a obtenu plus de 1700 milliards FCFA de la part d’Afreximbank pour financer des projets d’infrastructures liées au manganèse, à l’énergie et au transport ferroviaire, afin d’accélérer sa transformation économique.',
        'https://agpgabon.ga/nigeria-aam2025-le-gabon-obtient-1600-milliards-fcfa-dafreximbank-pour-accelerer-sa-transformation-industrielle/',
        'AGP',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd03810ab-4c5f-43ef-89b9-d657e5674dd4',
        'Abuja : le Gabon décroche 1600 milliards FCFA auprès d’Afreximbank pour sa transformation industrielle',
        'Le Gabon a obtenu un prêt de 1 600 milliards de francs CFA auprès de la Banque africaine d''import-export (Afreximbank) pour financer sa transformation industrielle.',
        'https://gabonmediatime.com/abuja-le-gabon-decroche-1600-milliards-fcfa-aupres-dafreximbank-pour-sa-transformation-industrielle/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7515ea6f-7f94-4824-8f0d-42058462ce31',
        'Plaine Orety : les familles non-indemnisées bientôt relogées à Bikélé Zong',
        'Les familles non indemnisées par le programme Plaine Orey oute seront bientôt relogées à Bikele Zong pour leur fournir un logement adéquat.',
        'https://gabonmediatime.com/plaine-orety-les-familles-non-indemnisees-bientot-relogees-a-bikele-zong/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ea038ca2-4176-46a5-8dfe-b52db56922a4',
        'Akanda : chien empoisonné, portes défoncées, Olivier Mebiame Assame agressé à domicile !',
        'Une attaque à l’acide a endommagé la maison d’Akanda Chien, tandis que plusieurs personnes, dont Olivier Mebiame, ont été agressées ou blessées lors d’événements violents.',
        'https://gabonmediatime.com/akanda-chien-empoisonne-portes-defoncees-olivier-mebiame-assame-agresse-a-domicile/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-27T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '64fc562f-b96f-432d-9bdf-43c632619711',
        'Abuja : le Gabon décroche 1600 milliards FCFA auprès d’Afreximbank pour sa transformation industrielle',
        'Le Gabon a obtenu un prêt de 1 600 milliards FCFA auprès de la banque africaine d''import-export pour financer ses projets de transformation industrielle.',
        'https://gabonmediatime.com/abuja-le-gabon-decroche-1600-milliards-fcfa-aupres-dafreximbank-pour-sa-transformation-industrielle/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ff0f7e2-a0d0-49da-bbfc-9410e38fe61d',
        'Plaine Orety : les familles non-indemnisées bientôt relogées à Bikélé Zong',
        'Les familles non indemnisées pour la relogée à Bikélé Zong seront prochainement relogées dans de nouvelles habitations, pour améliorer leurs conditions de vie.',
        'https://gabonmediatime.com/plaine-orety-les-familles-non-indemnisees-bientot-relogees-a-bikele-zong/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8fbd5d6b-6666-4662-95cf-34a7515c264f',
        'Akanda : chien empoisonné, portes défoncées, Olivier Mebiame Assame agressé à domicile !',
        'Une rixe a éclaté entre les proches d’Akanda Chien, entraînant son empoisonnement, la destruction de ses portes, et une agression à domicile contre Olivier Mebiame.',
        'https://gabonmediatime.com/akanda-chien-empoisonne-portes-defoncees-olivier-mebiame-assame-agresse-a-domicile/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '151bf11d-fe28-4097-b273-a851385fa92b',
        'Projets miniers : le Gabon sécurise un financement de 1 600 milliards FCFA auprès d’Afreximbank',
        'Le Gabon a obtenu un financement de 1 600 milliards de FCFA auprès de la Afreximbank pour sécuriser ses projets miniers et soutenir le développement économique du pays.',
        'https://kongossanews.info/projets-miniers-le-gabon-securise-un-financement-de-1-600-milliards-fcfa-aupres-dafreximbank/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc9d6ed0-e1d9-4775-9b67-a169fa715ec3',
        'Fer de Milingui : Havilah Mining Gabon, un moteur de développement pour la Nyanga et le Gabon.',
        'L’exploitation de la mine de fer de Moanda, dans la province de la Nyanga au Gabon, est un enjeu clé pour le développement économique de la région, créant des opportunités d’emplois et d’infrastructures.',
        'https://kongossanews.info/fer-de-milingui-havilah-mining-gabon-un-moteur-de-developpement-pour-la-nyanga/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6cb05f8c-79da-42d1-a447-846dc6971d5a',
        'Plaine Orety/Mouvement prévu au Trocadéro : gare aux « matengous » de Paris',
        'Une marche prévue au Trocadéro à Paris attire l’attention sur des enjeux militants, notamment liés à la situation au Mali, et mobilise des personnes venues exprimer leur solidarité.',
        'https://kongossanews.info/plaine-orety-mouvement-prevu-au-trocadero-gare-aux-matengous-de-paris/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95ffc4e8-66f9-42dc-b21b-910c71b2f635',
        'Football/Élection présidence de la Lifom : Donatien Afatoughe-Bie s’étonne du recours de la candidate battue',
        'Donatien Afatoughe-Bie, déclaré vainqueur à l’élection de la Ligue de football de l’Ogooué-Maritime, a exprimé son étonnement face au recours en annulation déposé par sa rivale, qui pourrait l’empêcher de participer au congrès de la fédération.',
        'https://agpgabon.ga/football-election-presidence-de-la-lifom-donatien-afatoughe-bie-setonne-du-recours-de-la-candidate-battue/',
        'AGP',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '18db0f4e-cf5a-42f2-a3b7-f7dd267a21f0',
        'Projets miniers : le Gabon sécurise un financement de 1 600 milliards FCFA auprès d’Afreximbank',
        'Le Gabon a obtenu un financement de 1 600 milliards de FCFA auprès de la Céntrébanque africaine d''import-export (Afreximbank) pour soutenir ses projets miniers.',
        'https://kongossanews.info/projets-miniers-le-gabon-securise-un-financement-de-1-600-milliards-fcfa-aupres-dafreximbank/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7132152-2f14-435b-8e09-06d74ba81586',
        'Fer de Milingui : Havilah Mining Gabon, un moteur de développement pour la Nyanga et le Gabon.',
        'L’exploitation du fer de l’oppidum de Milingui par Havilah Mining pourrait stimuler le développement économique et social de la région de la Nyanga au Gabon.',
        'https://kongossanews.info/fer-de-milingui-havilah-mining-gabon-un-moteur-de-developpement-pour-la-nyanga/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a21997a-9645-4350-a84a-99c94875e330',
        'Plaine Orety/Mouvement prévu au Trocadéro : gare aux « matengous » de Paris',
        'Une procession organisée au Trocadéro à Paris vise à soutenir la Côte d''Ivoire, mais des troubles et une intervention policière ont perturbé l''événement.',
        'https://kongossanews.info/plaine-orety-mouvement-prevu-au-trocadero-gare-aux-matengous-de-paris/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f6cfb922-f310-4254-aa6e-7ee0a2e817f0',
        'Clôture de la 32ᵉ Assemblée annuelle d''Afreximbank : le Président de la République prend part à la Session présidentielle',
        'Le président Brice Clotaire Oligui Nguema a assisté à la clôture de la 32e Assemblée annuelle de la Banque africaine d''import-export (Afreximbank), dont le thème était « Bâtir l''avenir sur des décennies de résilience », axée sur la promotion des opportunités commerciales en Afrique.',
        'https://www.gabonews.com/fr/actus/economie/article/cloture-de-la-32%E1%B5%89-assemblee-annuelle-d',
        'Gabonews',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c4666ea-affa-48dc-9640-4efb2ad2da29',
        'Le Gabon signe 2 conventions majeures pour un montant de 1712 milliards à la 32ème Assemblée annuelle d''Afreximbank à Abuja au Nigéria',
        'Le Gabon a signé deux importantes conventions pour renforcer son développement économique en partenariat avec des institutions financières lors de l''assemblée annuelle d''Afreximbank à Abuja.',
        'https://www.gabonews.com/fr/actus/economie/article/le-gabon-signe-2-conventions-majeures-pour-un',
        'Gabonews',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a22c25b-d9e8-46b3-b2a5-b4d0797e6b8d',
        'États-Unis : Vers une désignation du Polisario comme organisation terroriste',
        'Des membres du Congrès américain ont proposé de désigner le Front Polisario comme organisation terroriste étrangère afin de soutenir l''intégrité territoriale du Maroc et de dénoncer ses actions dans la région.',
        'https://www.gabonews.com/fr/actus/international/article/etats-unis-vers-une-designation-du-polisario',
        'Gabonews',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '778fc067-5421-4f7c-be2d-6a1d8f70d23f',
        'Publié le 27 / 06 / 2025',
        'Une commission mixte paritaire se réunit pour travailler sur des réformes politiques, visant à mettre en œuvre des ajustements législatifs et institutionnels.',
        'https://union.sonapresse.com/fr/reformes-politiques-la-commission-mixte-paritaire-pied-doeuvre-0',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b257ba6d-1f01-4bb5-861b-c93bdc4bab62',
        'Publié le 27 / 06 / 2025',
        'Une commission mixte paritaire travaille à harmoniser les réformes politiques pour faciliter leur mise en œuvre.',
        'https://union.sonapresse.com/fr/reformes-politiques-la-commission-mixte-paritaire-pied-doeuvre',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '79c36d31-f118-4d8c-99e7-e6e50a3b84a6',
        'Publié le 27 / 06 / 2025',
        'Une délégation équato-guinéenne a rencontré le président pour discuter de sujets importants liés aux relations bilatérales.',
        'https://union.sonapresse.com/fr/un-emissaire-du-president-equato-guineen-au-palais',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '84d704f0-7e71-4680-a55d-2d0204d1696f',
        'Gabon : Afreximbank injecte 1 600 milliards FCFA dans la transformation minière',
        'Le Gabon a signé deux accords avec la banque panafricaine Afreximbank pour obtenir 1 600 milliards FCFA, afin de financer la transformation locale du secteur minier, notamment le manganèse.',
        'https://directinfosgabon.com/gabon-afreximbank-injecte-1-600-milliards-fcfa-dans-la-transformation-miniere/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bbc5e217-3a5e-4492-8ec2-157d75884a79',
        'Audience Ministre des Transports - Ambassadeur de France au Gabon',
        'Le Ministre des Transports du Gabon a rencontré l''ambassadeur de France pour discuter du renforcement de la coopération bilatérale, notamment dans le secteur ferroviaire.',
        'https://www.gabonews.com/fr/actus/cooperation/article/audience-ministre-des-transports-ambassadeur-de',
        'Gabonews',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9e0eab2-0431-43b3-b75b-606f7e5e0a16',
        'Publié le 27 / 06 / 2025',
        'Une commission mixte paritaire travaille pour mettre en place les réformes politiques en réunissant différentes forces politiques pour élaborer des propositions communes.',
        'https://union.sonapresse.com/fr/reformes-politiques-la-commission-mixte-paritaire-pied-doeuvre-0',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f252bf8-c7f2-4201-809e-94c9de73b75e',
        'Publié le 27 / 06 / 2025',
        'Une commission mixte paritaire a été mise en place pour examiner et harmoniser les réformes politiques, notamment la proposition de nouvelle constitution.',
        'https://union.sonapresse.com/fr/reformes-politiques-la-commission-mixte-paritaire-pied-doeuvre',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5c0a343-f4ab-4f5c-bfec-90308c014f36',
        'Publié le 27 / 06 / 2025',
        'Un représentant du président équato-guinéen a rencontré le palais pour discuter de questions diplomatiques et de coopération entre les deux pays.',
        'https://union.sonapresse.com/fr/un-emissaire-du-president-equato-guineen-au-palais',
        'L''union',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f3174a3-dacc-4715-b817-b6c6fb36b229',
        'Assemblée annuelle d’Afreximbank /Délestages: OLIGUI NGUEMA signe portant sur la construction de 3 centrales thermiques',
        'Le Président Brice Clotaire OLIGUI NGUEMA a participé à la clôture de la 32ᵉ Assemblée annuelle de la Banque africaine d’import-export (Afreximbank) à Abuja, où ont été abordés des projets importants pour le développement économique panafricain.',
        'https://vxp241.com/2025/06/28/assemblee-annuelle-dafreximbank-delestages-oligui-nguema-signe-portant-sur-la-construction-de-3-centrales-thermiques/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '099cbb54-d5b0-4049-adef-ffeb477d761a',
        'Fer de Milingui : Havilah Mining Gabon s’engage dans la transformation locale',
        'Havilah Mining Gabon s’engage à valoriser localement le fer de Milingui en développant des activités de transformation sur place pour créer plus de valeur ajoutée.',
        'https://gabonactu.com/blog/2025/06/28/fer-de-milingui-havilah-mining-gabon-sengage-a-la-transformation-locale-pour-plus-de-plus-value/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd90e360a-01bc-41ca-beb4-28733c5e3529',
        'Cambriolage au bureau du Vice-président Barro Chambrier : qui a franchi la ligne rouge ?',
        'Un cambriolage ciblé dans les bureaux du vice-président gabonais révèle des failles de sécurité inquiétantes et soulève des interrogations sur les enjeux politiques et symboliques liés à cet incident.',
        'https://www.gabonreview.com/cambriolage-au-bureau-du-vice-president-barro-chambrier-qui-a-franchi-la-ligne-rouge/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74e4828e-8daa-4c17-89a9-3ba6ef9d04aa',
        'Modernisation et aménagement de Libreville : Déguerpissement et expropriations aux Charbonnages',
        'Le gouvernement prévoit de poursuivre la démolition et l’expulsion dans plusieurs quartiers de Libreville afin de moderniser la ville et aménager ses espaces.',
        'https://gabonactu.com/blog/2025/06/28/modernisation-et-amenagement-de-libreville-deguerpissement-et-expropriations-aux-charbonnages/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-28T00:00:00.000Z',
        '2025-09-15T23:06:12.463Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

