-- Batch 2 - Section 6/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '55472319-98e7-4ab0-8f3a-627992723a82',
        'Présidentielle 2025 au Gabon : l’ONU lance un appel pour la tenue d’une élection transparente, sincère et apaisée',
        'L''ONU appelle à des élections présidentielles transparentes, sincères et apaisées au Gabon en 2025, pour garantir un processus démocratique crédible. Elle souligne l''importance du dialogue et du respect des droits pour une transition pacifique.',
        'https://gabonactu.com/blog/2025/04/11/presidentielle-2025-au-gabon-lonu-lance-un-appel-pour-la-tenue-dune-election-transparente-sincere-et-apaisee/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5563f7a5-100f-4947-97f3-f77ab6d330b1',
        'Transparence électorale : 914 observateurs pour la présidentielle de ce samedi',
        '914 observateurs nationaux et internationaux seront déployés pour surveiller le scrutin présidentiel de ce samedi au Gabon, afin d’assurer la transparence et la crédibilité du processus électoral.',
        'https://gabonactu.com/blog/2025/04/11/transparence-electorale-914-observateurs-pour-la-presidentielle-de-ce-samedi/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8b072b8a-0c36-4c36-ab80-bac1aa555097',
        'VIDÉO. Trump se déhanchait sur YMCA, le favori à la présidentielle gabonaise excelle en breakdance',
        'Le favori à la présidentielle gabonaise a impressionné en montrant ses talents de breakdance lors d’un événement, rappelant une vidéo où Trump dansait sur YMCA.',
        'https://www.ouest-france.fr/insolite/video-trump-se-dehanchait-sur-ymca-le-favori-a-la-presidentielle-gabonaise-excelle-en-breakdance-08c34528-1600-11f0-9759-9654df6b878b?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc673f78-1ee0-4fd2-ab36-077ea736c1b8',
        'Port-Gentil : l’AIDE  gonfle des muscles pour la victoire de C’bon',
        'Le port de Port-Gentil se mobilise et renforce ses capacités pour soutenir activement la victoire de l''équipe C''BON, en démontrant un engagement collectif envers le succès sportif.',
        'https://gabonactu.com/blog/2025/04/11/port-gentil-laide-gonfle-des-muscles-pour-la-victoire-de-cbon/',
        'Gabon Actu',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5b1f40e-eabc-4c77-906e-0dfcd455bc1a',
        'Présidentielle 2025 à Port-Gentil : Jean Fidèle Otandault  mobilise une « caravane de la victoire » pour Brice Clotaire Oligui Nguema',
        'À Port-Gentil, Jean-Fidèle Otandault a organisé une caravane en soutien à Brice Clotaire Oligui Nguema en vue de l’élection présidentielle de 2025, mobilisant des partisans pour sa campagne.',
        'https://gabonactu.com/blog/2025/04/11/presidentielle-2025-a-port-gentil-jean-fidele-otandault-mobilise-une-caravane-de-la-victoire-pour-brice-clotaire-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '109aa2dd-1d88-4367-911a-6735866e0414',
        'Gabon : Vers une élection présidentielle historique ce 12 avril 2025',
        'Le Gabon se prépare pour une élection présidentielle historique qui pourrait marquer un tournant dans la vie politique du pays, avec des enjeux majeurs pour la démocratie et le développement.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/gabon-vers-une-election-presidentielle-historique',
        'Gabonews',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0aac94a2-3bd2-472f-8dff-ede2f7d1f99a',
        'Présidentielle 2025 à Andem : CAGL mobilise pour un vote massif en faveur du candidat Oligui Nguema',
        'Le mouvement A-ANDEM-CAGL appelle à une mobilisation massive pour soutenir la candidature d''Oligui Nguema lors de la présidentielle 2025 au Gabon, en incitant les citoyens à voter en sa faveur.',
        'https://gabonactu.com/blog/2025/04/11/presidentielle-2025-a-andem-cagl-mobilise-pour-un-vote-massif-en-faveur-du-candidat-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e15aa79-84fb-43d0-a175-c768a184c6ab',
        'Dernier jour de campagne : Pana en pleine ébullition électorale',
        'Le dernier jour de campagne électorale au Gabon a été marqué par une forte mobilisation des partis politiques, notamment le PANA, qui a intensifié ses efforts pour convaincre les électeurs avant le scrutin. Les meetings et les discours ont dominé cette journée cruciale pour les candidats.',
        'https://www.gabonews.com/fr/actus/politique/article/dernier-jour-de-campagne-pana-en-pleine',
        'Gabonews',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f05c4980-c426-441a-b1eb-5764bf4a3e77',
        'Élection présidentielle 2025 : La coordination départementale de campagne de Brice Clotaire Oligui Nguema conclut son opération ...',
        'La coordination départementale de campagne de Brice Clotaire Oligui Nguéma a terminé sa tournée de sensibilisation dans le canton de Poungui, rencontrant les populations pour renforcer son ancrage local en vue des élections présidentielles de 2025. L’initiative vise à consolider les soutiens dans cette région symbolique, qualifiée de « terre des guerriers ».',
        'https://kongossanews.info/election-presidentielle-2025-la-coordination-departementale-de-campagne-de-brice-clotaire-oligui-nguema-conclut-son-operation-seduction-dans-le-canton-poungui-terre-des-guerriers/',
        'Kongossa News',
        'Autres',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca7e7da5-5fcb-4bc4-a71c-746b29715549',
        'Alain Simplice BOUNGOUERES : l’espérance incarnée pour le renouveau du Gabon',
        'Alain Simplice Boungouerès représente un espoir de renouveau politique et économique pour le Gabon, avec un engagement en faveur de la jeunesse, de l''éducation et de la lutte contre la corruption. Son parcours et ses propositions visent à redynamiser le pays en misant sur la transparence et l''innovation.',
        'https://kongossanews.info/alain-simplice-boungoueres-lesperance-incarnee-pour-le-renouveau-du-gabon/',
        'Kongossa News',
        'Éducation, Numérique / Digital, Services',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0311242-bbe9-473e-90c1-9734465505d2',
        'Présidentielle 2025 : La contribution de la Jeunesse de l’Union Nationale.',
        'La jeunesse de l''Union Nationale s''engage à contribuer activement à la présidentielle de 2025 en mobilisant ses membres pour soutenir le processus électoral et promouvoir la participation citoyenne. Leur action vise à renforcer la démocratie et l''inclusion des jeunes dans les décisions politiques.',
        'https://kongossanews.info/presidentielle-2025-la-contribution-de-la-jeunesse-de-lunion-nationale/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services',
        '2025-04-11T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1b686518-012c-4b2c-9c9f-a8168f5a759f',
        'Gabon : derniers préparatifs avant l''élection',
        'Le Gabon se prépare pour une élection présidentielle cruciale, avec des mesures de sécurité renforcées et des inquiétudes concernant la transparence du scrutin. Les autorités assurent du bon déroulement du vote, tandis que l''opposition et la société civile restent vigilantes.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250411-gabon-derniers-pr%C3%A9paratifs-avant-l-%C3%A9lection',
        'France 24',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f47a0312-4371-4659-b1ad-b7db85666e84',
        'Ogooué-Ivindo/Makokou : Des associations sur tous les fronts',
        'Des associations de Makokou dans l’Ogooué-Ivindo expriment leurs préoccupations face aux défis socio-économiques locaux et demandent plus d’implication des autorités pour améliorer les conditions de vie.',
        'https://www.gabonews.com/fr/actus/politique/article/ogooue-ivindo-makokou-des-associations-sur-tous',
        'Gabonews',
        'Services, Finances, Éducation, Business Femme',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1efae8cb-904d-4fc2-844f-be0cda02ba33',
        'Présidentielle 2025 : Formation des scrutateurs pour le jour du vote',
        'Des formations sont organisées pour préparer les scrutateurs aux élections présidentielles de 2025, afin d’assurer le bon déroulement du scrutin et la transparence du processus électoral.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-formation-des-scrutateurs',
        'Gabonews',
        'Éducation, Services',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c96bf7df-9536-4ac6-b56b-55353723fdcb',
        'Vers une élection transparente : les observateurs citoyens au rendez vous',
        'Des observateurs électoraux internationaux et locaux se mobilisent pour garantir la transparence des prochaines élections au Gabon, en surveillant le processus et en promouvant des pratiques démocratiques.',
        'https://www.gabonews.com/fr/actus/politique/article/vers-une-election-transparente-les-observateurs',
        'Gabonews',
        'Numérique / Digital, Services, Éducation',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '668eb8e4-7581-4687-97a1-0c7224e449ff',
        'Présidentielle 2025 : Voter, c’est choisir, la dignité du citoyen face aux impostures politiques',
        'L''article souligne l''importance des élections présidentielles de 2025 au Gabon comme un moment crucial pour les citoyens de choisir des dirigeants intègres et de rejeter les manipulations politiques. Il appelle à une prise de conscience collective pour préserver la dignité nationale face aux promesses mensongères.',
        'https://gabonmediatime.com/presidentielle-2025-voter-cest-choisir-la-dignite-du-citoyen-face-aux-impostures-politiques/',
        'Gabon Media Time',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9deabd5-c714-4217-bc3c-9ab50b44d263',
        'Présidentielle 2025 : Bilie-By-Nze s’interroge sur le silence des opposants d’hier sur l’attaque du QG de Ping',
        'L’article s’interroge sur le silence des anciens opposants politiques gabonais face à l’attaque récente du quartier général d’Albert Ondo Ossa, candidat à la présidentielle de 2025, alors qu’ils avaient dénoncé des violences similaires par le passé. Cette situation soulève des questions sur la cohérence et les motivations de ces acteurs politiques.',
        'https://gabonmediatime.com/presidentielle-2025-bilie-by-nze-sinterroge-sur-le-silence-des-opposants-dhier-sur-lattaque-du-qg-de-ping/',
        'Gabon Media Time',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2977ef7-5915-404b-a86c-3c2b77af07cc',
        'Présidentielle 2025 : discrètement, la SETRAG au cœur la mobilisation électorale',
        'La SETRAG, entreprise ferroviaire au Gabon, jouerait un rôle discret dans la mobilisation électorale en vue de la présidentielle de 2025, selon des informations relayées. Son implication soulève des questions sur son influence dans le processus politique.',
        'https://gabonmediatime.com/presidentielle-2025-discretement-la-setrag-au-coeur-la-mobilisation-electorale/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80a58ed8-d309-48ab-9b92-d2db7a3453a1',
        'Gabon/Présidentielle 2025 : Les derniers mots de campagne d’Alain Simplice Boungoueres',
        'Alain Simplice Boungouéré a prononcé ses derniers mots de campagne avant la présidentielle de 2025 au Gabon, appelant à l’unité et promettant des réformes pour le développement du pays. Son discours a insisté sur la transparence et la justice sociale comme priorités.',
        'https://agpgabon.ga/2025/04/11/gabon-presidentielle-2025-les-derniers-mots-de-campagne-dalain-simplice-boungoueres/',
        'AGP',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fcf10e4-bb44-4e71-a3f7-ef84d0122798',
        'Présidentielle 2025 : Voter, c’est choisir, la dignité du citoyen face aux impostures politiques',
        'L''article souligne l''importance du vote lors des élections présidentielles de 2025 au Gabon, en encourageant les citoyens à choisir des dirigeants intègres pour préserver leur dignité face aux promesses politiques trompeuses. Il appelle à une participation responsable pour éviter les manipulations et garantir un avenir meilleur.',
        'https://gabonmediatime.com/presidentielle-2025-voter-cest-choisir-la-dignite-du-citoyen-face-aux-impostures-politiques/',
        'Gabon Media Time',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8eefd758-dade-4069-89c7-c919c0b91d86',
        'Présidentielle 2025 : Bilie-By-Nze s’interroge sur le silence des opposants d’hier sur l’attaque du QG de Ping',
        'L’article s’interroge sur le silence des anciens opposants gabonais face à l’attaque du quartier général du président de transition Brice Oligui Nguema, soulignant une absence de réaction critique malgré leur passé contestataire.',
        'https://gabonmediatime.com/presidentielle-2025-bilie-by-nze-sinterroge-sur-le-silence-des-opposants-dhier-sur-lattaque-du-qg-de-ping/',
        'Gabon Media Time',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f0d7fc4-5bfc-4635-9816-b2ecc33095ad',
        'Présidentielle 2025 : discrètement, la SETRAG au cœur la mobilisation électorale',
        'La SETRAG, entreprise ferroviaire gabonaise, jouerait un rôle discret dans la préparation de l’élection présidentielle de 2025 en facilitant la mobilisation électorale, selon des sources internes.',
        'https://gabonmediatime.com/presidentielle-2025-discretement-la-setrag-au-coeur-la-mobilisation-electorale/',
        'Gabon Media Time',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '949e4f5f-16ae-4d54-b418-aedb00718674',
        'Publié le 11 / 04 / 2025',
        'La charte de la transition et les organes du Comité de transition et de redressement institutionnel (CTRI) seront supprimés, marquant une étape vers la normalisation politique. Cette décision s''inscrit dans un contexte de réformes visant à stabiliser les institutions.',
        'https://union.sonapresse.com/fr/steeve-davin-moughiama-la-charte-de-la-transition-et-les-organes-du-ctri-disparaitront',
        'L''union',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7168ad45-680b-4958-83b0-ef90d421f33b',
        'Publié le 11 / 04 / 2025',
        'Un jeune entrepreneur camerounais, Ilowi Mbani, mène une campagne de sensibilisation pour lutter contre l''abstention électorale en encourageant les citoyens, surtout les jeunes, à s''inscrire sur les listes électorales et à voter. Son initiative utilise des méthodes innovantes comme le porte-à-porte et les réseaux sociaux pour toucher un large public.',
        'https://union.sonapresse.com/fr/lutte-contre-labstention-ilowi-mbani-sur-le-terrain',
        'L''union',
        'Numérique / Digital, Services, Éducation',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4d05424-c00a-489c-bc85-b63b9a77ef16',
        'Publié le 11 / 04 / 2025',
        'Hermann Immongault affirme que les conditions sont réunies pour des élections exemplaires au Gabon, soulignant la transparence et la mobilisation des acteurs politiques.',
        'https://union.sonapresse.com/fr/hermann-immongault-tout-est-reuni-pour-un-scrutin-exemplaire',
        'L''union',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2361b02c-d383-4bf7-a90e-e3dda0e6ad03',
        'Gabon : le général Brice Oligui Nguema, putschiste en voie d’élection',
        'Le général Brice Oligui Nguema, auteur du coup d’État au Gabon en 2023, se présente désormais comme candidat à l’élection présidentielle, marquant une transition controversée du pouvoir militaire vers un processus électoral.',
        'https://www.lemonde.fr/afrique/article/2025/04/12/gabon-le-general-brice-oligui-nguema-putschiste-en-voie-d-election_6594504_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25dbcb0f-d9c1-4383-8b14-ff6432772ce7',
        'Présidentielle au Gabon: les bureaux de vote ont ouvert leurs portes pour les 920 000 électeurs',
        'Près de 920 000 électeurs gabonais sont attendus aux urnes ce samedi pour élire leur président, dans un scrutin marqué par la candidature du général Oligui Nguema, qui dirige le pays depuis le coup d’État d’août 2023.',
        'https://www.rfi.fr/fr/afrique/20250412-pr%C3%A9sidentielle-gabon-920-000-%C3%A9lecteurs-appeles-urnes-samedi-oligui-nguema',
        'RFI',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8f38bd6-4da3-49b3-9e01-93c3ce2df511',
        'Présidentielle au Gabon : Oligui Nguema veut « un score soviétique » face à une opposition fantôme',
        'Le général Oligui Nguema, candidat à la présidentielle gabonaise, vise une victoire écrasante face à une opposition affaiblie et divisée, dans un contexte politique marqué par des tensions et des critiques sur la transparence du processus électoral.',
        'https://www.jeuneafrique.com/1678293/politique/presidentielle-au-gabon-oligui-nguema-veut-un-score-sovietique-face-a-une-opposition-fantome/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb4ddf59-1905-4fc2-a036-f3c8d5498a07',
        'Présidentielle au Gabon : Oligui Nguema veut « un score soviétique » face à une opposition fantôme',
        'Le général Oligui Nguema, candidat à la présidentielle gabonaise, vise une victoire écrasante face à une opposition affaiblie et peu visible, dans un contexte politique marqué par des tensions.',
        'https://www.jeuneafrique.com/1678293/politique/presidentielle-au-gabon-oligui-nguema-veut-un-score-sovietique-face-a-une-opposition-fantome/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae4eb79e-a1da-4c11-ba8b-9e2836e66cde',
        'Les Gabonais élisent leur président après 19 mois de régime militaire',
        'Les Gabonais votent pour élire leur nouveau président après 19 mois de transition militaire, marquant un retour à un régime civil. Ce scrutin est un test pour la stabilité du pays après le coup d’État de 2023.',
        'https://www.france24.com/fr/vid%C3%A9o/20250412-les-gabonais-%C3%A9lisent-leur-pr%C3%A9sident-apr%C3%A8s-19-mois-de-r%C3%A9gime-militaire-1',
        'France 24',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dbbc827b-5144-4fd8-8c28-a6281005fa82',
        'Présidentielle 2025 : Aux urnes citoyens !',
        'Les élections présidentielles de 2025 au Gabon mobilisent les citoyens pour un scrutin crucial, marqué par des enjeux politiques et socio-économiques majeurs. La participation active de la population est encouragée pour façonner l’avenir du pays.',
        'https://gabonactu.com/blog/2025/04/12/presidentielle-2025-au-urnes-citoyens/',
        'Gabon Actu',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aecd6788-b58f-4c4c-9a15-eb473dbf7da5',
        'PRÉSIDENTIELLE 2025 : Les musulmans de la 5ème République en soutien massif au candidat Oligui Nguema',
        'Les musulmans de la 5ème circonscription du Gabon s''engagent à soutenir activement le processus électoral pour la présidentielle de 2025, en appelant à la paix et à l''unité nationale.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-les-musulmans-de-la-5eme',
        'Gabonews',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93c63c57-7ff4-4d0d-b6a6-58456ef6daec',
        'Eric Danny Mouelet au coeur de la mobilisation et sensibilisation des électeurs à Koulamoutou et environs',
        'Eric Danny Mouelet participe activement à une mobilisation politique au Gabon, suscitant des discussions sur son engagement et son influence dans le paysage politique local.',
        'https://www.gabonews.com/fr/actus/politique/article/eric-danny-mouelet-au-coeur-de-la-mobilisation-et',
        'Gabonews',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf35efaf-8569-4143-9aa3-dc2118a3ce2e',
        'Gabon/Présidentielle 2025 : début effectif du vote à l’ambassade du Gabon en Côte d’Ivoire',
        'Le vote pour l’élection présidentielle gabonaise de 2025 a commencé à l’ambassade du Gabon en Côte d’Ivoire, marquant le début effectif du scrutin pour la diaspora.',
        'https://agpgabon.ga/2025/04/12/gabon-presidentielle-2025-debut-effectif-du-vote-a-lambassade-du-gabon-en-cote-divoire/',
        'AGP',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ddac737c-a397-41ea-bb86-a929e3464383',
        'Les Émirats arabes unis et le Brésil collaborent pour développer les compétences des agriculteurs en Angola et en Guinée-Bissau',
        'Les Émirats arabes unis et le Brésil unissent leurs efforts pour former des agriculteurs en Angola et en Guinée-Bissau, afin d''améliorer leurs compétences et renforcer la sécurité alimentaire dans ces pays.',
        'https://agpgabon.ga/2025/04/12/les-emirats-arabes-unis-et-le-bresil-collaborent-pour-developper-les-competences-des-agriculteurs-en-angola-et-en-guinee-bissau/',
        'AGP',
        'Agriculture, Éducation',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33780aee-b461-4f24-b560-ff502a14a9a1',
        'Gabon/Présidentielle 2025 : début dans le calme des opérations de vote à Makokou',
        'Les opérations de vote pour la présidentielle 2025 au Gabon ont débuté dans le calme à Makokou, sans incidents majeurs signalés lors de l''ouverture des bureaux.',
        'https://agpgabon.ga/2025/04/12/gabon-presidentielle-2025-debut-dans-le-calme-des-operations-de-vote-a-makokou/',
        'AGP',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e9f3d39-b357-4d20-907f-680d0bbc343e',
        'Gabon/Présidentielle 2025 : calme et affluence progressive dans les bureaux de vote à Port-Gentil',
        'Le scrutin présidentiel gabonais de 2025 se déroule dans le calme à Port-Gentil, avec une affluence progressive observée dans les bureaux de vote.',
        'https://agpgabon.ga/2025/04/12/gabon-presidentielle-2025-calme-et-affluence-progressive-dans-les-bureaux-de-vote-a-port-gentil/',
        'AGP',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a3f67760-857a-4b94-bdfc-44543cac2349',
        'Gabon/Présidentielle 2025 : début effectif du vote à Libreville',
        'Les élections présidentielles de 2025 au Gabon ont officiellement commencé dans le Grand Libreville, avec un démarrage effectif du processus de vote. Les électeurs se rendent aux urnes pour choisir leur futur dirigeant.',
        'https://agpgabon.ga/2025/04/12/gabon-presidentielle-2025-debut-effectif-du-vote-dans-le-grand-libreville/',
        'AGP',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0acf2f74-41b9-469e-ba1e-110313960933',
        'Gabon : les habitants affluent dans les bureaux de vote pour la présidentielle',
        'Les habitants du Gabon se rendent massivement aux bureaux de vote pour participer à l''élection présidentielle, marquant un engagement notable dans le processus démocratique.',
        'https://www.lefigaro.fr/international/gabon-les-habitants-affluent-dans-les-bureaux-de-vote-pour-la-presidentielle-20250412?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bffc88d6-b59c-4493-8f72-b3ff0f6339ba',
        'Présidentielle 2025 : Mbatchi Pambou a voté',
        'Lors des élections présidentielles de 2025, Mbatchi Pambou a exercé son droit de vote, marquant ainsi sa participation au processus démocratique.',
        'https://gabonactu.com/blog/2025/04/12/presidentielle-2025-mbatchi-pambou-a-vote/',
        'Gabon Actu',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '50ab9efe-c02e-4d6a-a40c-3aa58486704b',
        'Présidentielle au Gabon : « Brice Oligui Nguema nous a sortis d’un système pourri »',
        'Brice Oligui Nguema, actuel dirigeant du Gabon, affirme avoir libéré le pays d''un système corrompu après le coup d''État de 2023, tout en promettant une transition démocratique malgré les critiques sur la légitimité de son pouvoir.',
        'https://www.lemonde.fr/afrique/article/2025/04/12/presidentielle-au-gabon-brice-oligui-nguema-nous-a-sortis-d-un-systeme-pourri_6594843_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '69030f1b-a793-4c98-8edb-1d09a22c4230',
        'Les Gabonais affluent dans les bureaux de vote pour la présidentielle',
        'Les Gabonais se rendent massivement aux bureaux de vote pour participer à l''élection présidentielle, montrant un engagement marqué dans le processus démocratique.',
        'https://www.france24.com/fr/vid%C3%A9o/20250412-les-gabonais-affluent-dans-les-bureaux-de-vote-pour-la-pr%C3%A9sidentielle?utm_source=flipboard&utm_content=topic/fr-actualit%C3%A9s',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fd8e283a-29da-4b3a-95f9-33afe52ac1fe',
        'Les Gabonais affluent dans les bureaux de vote pour la présidentielle',
        'Les Gabonais se rendent massivement aux urnes pour l''élection présidentielle, montrant un engagement marqué dans le processus démocratique.',
        'https://www.france24.com/fr/vid%C3%A9o/20250412-les-gabonais-affluent-dans-les-bureaux-de-vote-pour-la-pr%C3%A9sidentielle',
        'France 24',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1c9374a5-07c6-4abb-854f-e45cfd32cd4f',
        'C’est une nouvelle République qui se crée aujourd’hui pour les gabonais (Oligui Nguema)',
        'Le président gabonais Oligui Nguema annonce la création d''une nouvelle République, marquant un tournant historique pour le pays avec des réformes politiques et sociales promises. Cette transition vise à répondre aux attentes des citoyens après des années de contestation.',
        'https://gabonactu.com/blog/2025/04/12/cest-une-nouvelle-republique-qui-se-cree-aujourdhui-pour-les-gabonais-oligui-nguema/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation, Agriculture, Business Femme',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4f3ac56-744a-4963-82f6-e71a01da16a5',
        'Présidentielle 2025 : Affluence record à la mi-journée',
        'À mi-journée de la présidentielle 2025 au Gabon, une affluence record a été observée dans les bureaux de vote, marquant un engagement massif des électeurs. Cette participation élevée témoigne d''un intérêt marqué pour ce scrutin crucial.',
        'https://gabonactu.com/blog/2025/04/12/presidentielle-2025-affluence-record-a-la-mi-journee/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '719c37c1-ec31-4467-a865-56145fb2cc96',
        '[Présidentielle] : Des observateurs du ROC empêchés d’exercer',
        'Des observateurs électoraux du Réseau des organisations de la société civile pour l’observation des élections au Gabon (ROSCE-Gabon) ont été empêchés d’exercer leur mission lors de la présidentielle, malgré leur accréditation officielle. Certains ont été retenus par des forces de sécurité ou n’ont pas pu accéder aux bureaux de vote.',
        'https://www.gabonreview.com/presidentielle-des-observateurs-du-roc-empeches-dexercer/',
        'Gabon Review',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2030c9e6-198b-4a15-9037-9284f0a3270e',
        'Rencontre entre le Groupe des Ambassadeurs francophones et la mission électorale de l''OIF',
        'Des ambassadeurs du Groupe Afrique-Caraïbes-Pacifique (ACP) ont rencontré des représentants gabonais pour renforcer la coopération en matière de développement, notamment dans les domaines de l''éducation et des technologies. Les discussions ont porté sur des projets concrets visant à soutenir la croissance économique et sociale du Gabon.',
        'https://www.gabonews.com/fr/actus/cooperation/article/rencontre-entre-le-groupe-des-ambassadeurs',
        'Gabonews',
        'Éducation, Numérique / Digital, Services',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ec0f0db-911b-4c44-9cac-440662e40364',
        'Les électeurs séreinement dans les bureaux de vote à Mounana',
        'Les électeurs se rendent calmement dans les bureaux de vote pour participer aux élections, dans une atmosphère paisible et organisée.',
        'https://www.gabonews.com/fr/actus/politique/article/les-electeurs-sereinement-dans-les-bureaux-de',
        'Gabonews',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '027c7864-aca8-47b5-b160-d038dbe420ea',
        'Au Gabon, fin d''une transition militaire, mais quel avenir ?',
        'L’article explique comment des étudiants africains utilisent l’intelligence artificielle pour améliorer l’éducation, notamment en créant des outils numériques adaptés aux besoins locaux comme des chatbots en langues africaines. Ces innovations visent à combler les lacunes éducatives et à rendre l’apprentissage plus accessible.',
        'https://dw.com/p/4t3tE?maca=fra-RSS_fr_Flipboard-11983-xml-media',
        'Flipboard',
        'Numérique / Digital, Éducation',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c450064f-0ea0-42ec-98c8-9e4fdd28cda9',
        'Présidentielle au Gabon : à Libreville, Brice Clotaire Oligui Nguema affiche sa confiance',
        'Brice Clotaire Oligui Nguema, général gabonais, exprime sa confiance dans le processus électoral en cours à Libreville, lors de la présidentielle au Gabon, malgré les tensions politiques.',
        'https://www.jeuneafrique.com/1678458/politique/presidentielle-au-gabon-a-libreville-brice-clotaire-oligui-nguema-affiche-sa-confiance/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-12T00:00:00.000Z',
        '2025-09-15T23:06:12.418Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

