-- Batch 4 - Section 12/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '56eff0cb-2247-4b84-baea-2bd79c965053',
        'Le ministère de l''Habitat en audience à la Présidence de la République',
        'Le président brice oligui nguema a rencontré des responsables gouvernementaux pour faire le point sur la reprise administrative des terrains publics.',
        'https://www.gabonews.com/fr/actus/habitat/article/le-ministere-de-l-habitat-en-audience-a-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '69c83839-78e2-478f-a7b4-99e83bb2d40a',
        'Conférence de Presse du Porte Parole de la Présidence de la République',
        'Une conférence de presse a été organisée au Palais de la République pour informer le public sur les politiques et initiatives du gouvernement, en insistant sur la transparence et la pédagogie.',
        'https://www.gabonews.com/fr/actus/communication/article/conference-de-presse-du-porte-parole-de-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '82a823b0-8b47-4bc0-9a8f-9b3124b22cad',
        'Les épreuves du concours d’entrée au prytanée militaire se tiendra le 21 juin 2025',
        'Le concours d’entrée aux Prytanées militaires aura lieu le 21 juin 2025 à 7 heures dans diverses régions.',
        'https://gabonactu.com/blog/2025/06/12/les-epreuves-du-concours-dentree-au-prytanee-militaire-se-tiendra-le-21-juin-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cacf19b5-a9d5-4489-9da0-0585ffcd0209',
        'Département des transports : Le ministre de tutelle équipe les services sous tutelle',
        'Le ministre des Transports a procédé à la remise de véhicules et de matériel informatique pour renforcer les services sous sa tutelle.',
        'https://gabonactu.com/blog/2025/06/12/vehicules-et-materiels-informatiques-ulrich-manfoumbi-manfoumbi-dote-son-ministere-dimportant-lots/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'add7680d-a36a-4764-96c6-fe4d8b8e28f1',
        'Obsèques d’Idriss Ngari: L’ancien dignitaire élevé à la dignité de Grand-Croix dans l’Ordre de la Panthère Noire à titre posthume',
        'Les funérailles d’Idriss Ngari, ancien dignitaire militaire, ont permis de lui rendre hommage en lui décernant à titre posthume la dignité de Grand-Croix dans l’Ordre de la Panthère Noire, en présence de hautes autorités du pays.',
        'https://gabonactu.com/blog/2025/06/12/derniers-honneurs-idriss-ngari%e3%80%8ageneral-tonnerre%e3%80%8b-eleve-a-la-dignite-de-grand-croix-dans-lordre-de-la-panthere-noire/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '192935a9-853b-44df-9eeb-7fc6bff77263',
        'Le ministre Mark Alexandre Doumba échange avec la FEG sur l''accélération de la digitalisation de l''économie',
        'Le ministre de l''Économie numérique du Gabon a rencontré la Fédération des Entreprises pour renforcer la collaboration public-privé, en insistant sur la nécessité de développer une infrastructure numérique solide pour encourager les investissements et moderniser les procédures.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-ministre-mark-alexandre-doumba-echange-avec-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7acf12a9-082b-4925-80c1-233ac35da2f5',
        'Gabon/Fégakama : le renouvellement du bureau directeur fixé au 28 juin prochain',
        'L’élection du nouveau bureau de la Fédération gabonaise de karaté-do et arts martiaux affinitaires (Fégakama) aura lieu le 28 juin 2025, avec la campagne électorale du 13 au 27 juin.',
        'https://agpgabon.ga/gabon-fegakama-le-renouvellement-du-bureau-directeur-fixe-au-28-juin-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6514e472-c6eb-4f86-b359-85f09dfb129b',
        'Gabon/Sports : les fédérations nationales exposent leurs préoccupations au ministre Armande Longo-Moulengui',
        'Les présidents des fédérations sportives nationales ont rencontré la ministre des Sports pour partager leurs difficultés et attentes, en soulignant la nécessité de travailler ensemble une fois le budget voté.',
        'https://agpgabon.ga/gabon-sports-les-federations-nationales-exposent-leurs-preoccupations-au-ministre-armande-longo-moulengui/',
        'AGP',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc213b98-b35d-4515-9824-ce63f5ee4eca',
        'Accord de partenariat de pêche durable UE: le Gabon perdant sur tous les points depuis 2007',
        'La rupture de l’Accord de partenariat de pêche durable entre l’UE et le Gabon s’explique par des désaccords sur la gestion des ressources et le respect des engagements, révélant des difficultés à maintenir une coopération équilibrée depuis 2007.',
        'https://vxp241.com/2025/06/13/accord-de-partenariat-de-peche-durable-ue-le-gabon-perdant-sur-tous-les-points-depuis-2007/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a8d8b1e8-2465-4c68-97d7-f39bb6fe0e7e',
        'Déguerpissement de Libreville : Pour J.R. Yama «le décret du 14 février 2024» ne remplit pas les critères',
        'Jean Rémy Yama critique le décret du 14 février 2024 sur les déguerpissements à Libreville, affirmant qu''il ne respecte pas les critères légaux et ne doit pas être appliqué tel quel.',
        'https://www.gabonreview.com/deguerpissement-de-libreville-pour-j-r-yama-le-decret-du-14-fevrier-2024-ne-remplit-pas-les-criteres/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f233591f-63c1-4716-92c8-a678e2f50cea',
        'Gabon : le verrouillage du Port d’Owendo, une réforme punitive qui asphyxie les importateurs',
        'Le verrouillage du port d’Owendo par les autorités gabonaises, dans le cadre d''une réforme, empêche les importateurs de décharger leurs marchandises, aggravant ainsi leurs difficultés économiques.',
        'https://gabonmediatime.com/gabon-le-verrouillage-du-port-dowendo-une-reforme-punitive-qui-asphyxie-les-importateurs/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '773ec682-3679-4233-ba63-46dc11811c8f',
        'Création d’un parti présidentiel : Oligui Nguema peut le faire… mais au prix de son mandat',
        'La création d’un parti présidentiel en Guinée équivaut à un enjeu de pouvoir que le président peut prendre en compte pendant son mandat, mais cela pourrait également compromettre la stabilité politique du pays.',
        'https://gabonmediatime.com/creation-dun-parti-presidentiel-oligui-nguema-peut-le-faire-mais-au-prix-de-son-mandat/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01ac9e9e-7b2d-4174-902a-81302f144da4',
        'Gabon–Liban : relance stratégique de la coopération bilatérale autour de l’économie et du tourisme',
        'Le Gabon et le Liban souhaitent relancer leur coopération bilatérale, en mettant l’accent sur le développement économique et le tourisme pour renforcer leurs liens.',
        'https://gabonmediatime.com/gabon-liban-relance-strategique-de-la-cooperation-bilaterale-autour-de-leconomie-et-du-tourisme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0d3de57-a1d1-4d08-8a8a-bb588bf6f1a1',
        'L’hommage d’OLIGUI NGUEMA au feu Idriss NGARI',
        'Le président Brice Clotaire Oligui Nguema a rendu un dernier hommage au général Idriss Firmin Ngari, décédé récemment à l''âge de 79 ans, lors d''une cérémonie au camp Capitaine Ntchore de Baraka.',
        'https://vxp241.com/2025/06/13/lhommage-doligui-nguema-au-feu-idriss-ngari/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22aaab10-119f-483d-9c40-98c936405ecd',
        'Gabon : le verrouillage du Port d’Owendo, une réforme punitive qui asphyxie les importateurs',
        'Le verrouillage du port d''Owendo en Guinée équatoriale par le Gabon vise à réformer la gestion portuaire, mais il pénalise fortement les importateurs qui doivent faire face à des restrictions et à des retards.',
        'https://gabonmediatime.com/gabon-le-verrouillage-du-port-dowendo-une-reforme-punitive-qui-asphyxie-les-importateurs/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '11146f53-b4da-4102-a0c9-e42930807ccd',
        'Création d’un parti présidentiel : Oligui Nguema peut le faire… mais au prix de son mandat',
        'La création d’un parti présidentiel en Guinée équivaut à une opération possible pour le président, mais elle risquerait de lui coûter son mandat en raison des tensions sociales qu’elle pourrait engendrer.',
        'https://gabonmediatime.com/creation-dun-parti-presidentiel-oligui-nguema-peut-le-faire-mais-au-prix-de-son-mandat/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a034c96-76a5-40b5-a86e-d197299e27dc',
        'Gabon–Liban : relance stratégique de la coopération bilatérale autour de l’économie et du tourisme',
        'La coopération bilatérale entre le Gabon et le Liban a été relancée, avec un accent sur le développement économique et touristique pour renforcer leurs relations.',
        'https://gabonmediatime.com/gabon-liban-relance-strategique-de-la-cooperation-bilaterale-autour-de-leconomie-et-du-tourisme/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2a9c5ca0-33bc-4404-91a1-cc59128b90db',
        'Gabon : Le Porte-parole de la Présidence présente les orientations stratégiques du nouveau mandat',
        'Le porte-parole de la présidence gabonaise a présenté les grandes orientations stratégiques pour la nouvelle phase du mandat présidentiel, visant à renforcer le développement économique et social du pays.',
        'https://kongossanews.info/gabon-le-porte-parole-de-la-presidence-presente-les-orientations-strategiques-du-nouveau-mandat/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3ac30bb-f44e-4a8e-b02f-0860da45e105',
        'Journée mondiale de l’Environnement : SOBRAGA aux côtés de l’ONG SOS KOMO OCEAN pour protéger le littoral gabonais',
        'Sobraga a organisé des activités pour sensibiliser à la protection du littoral gabonais lors de la Journée mondiale de l’environnement, en partenariat avec l’ONG SOS Komo Ocean.',
        'https://kongossanews.info/journee-mondiale-de-lenvironnement-sobraga-aux-cotes-de-long-sos-komo-ocean-pour-proteger-le-littoral-gabonais/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21cca9bd-d4c5-485d-83d1-2630c8942b72',
        'Publié le 13 / 06 / 2025',
        'Le Nigeria a lancé une plateforme numérique éducative pour améliorer l’accès à l’enseignement dans tout le pays.',
        'https://union.sonapresse.com/fr/lhommage-de-la-nation-au-general-idriss-firmin-ngari',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '157846eb-8d93-4044-a8cf-ca98756ced88',
        'Publié le 13 / 06 / 2025',
        'Le président a suivi de près la situation dans la région, montrant son engagement à résoudre les problèmes rencontrés par la population locale.',
        'https://union.sonapresse.com/fr/theophane-nzame-nze-biyoghe-le-chef-de-letat-suit-la-situation-de-pres',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bfa87a84-6b9e-4741-9527-b4b3f53cb2b0',
        'Publié le 12 / 06 / 2025',
        'L''article demande à Bilie Nze de fournir des comptes pour clarifier la demande d''indemnisation liée aux dégâts subis.',
        'https://union.sonapresse.com/fr/indemnisation-des-deguerpis-bilie-nze-demande-des-comptes',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a770484-b18c-4660-8abc-8b5e79bbfb93',
        'Journée mondiale de la sécurité et la santé au travail : la Sobraga veut prévenir les risques liés à l’alcool au travail Face à ...',
        'La SOBRAGA sensibilise à la prévention des risques liés à l''alcool au travail pour assurer la sécurité et la santé des employés.',
        'https://mediapostegabon.com/journee-mondiale-de-la-securite-et-la-sante-au-travail-la-sobraga-veut-prevenir-les-risques-lies-a-lalcool-au-travail/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b93ae768-37d7-45c6-b2e3-14c4e9487387',
        'Future Cité administrative : Oligui Nguema pour un démarrage rapide des travaux Déguerpissement de Derrière-l’Assemblée : des fa...',
        'Le projet de la Future Cite administrative à Libreville vise un démarrage rapide des travaux pour moderniser et organiser l''administration de la capitale gabonaise.',
        'https://mediapostegabon.com/future-cite-administrative-oligui-nguema-pour-un-demarrage-rapide-des-travaux/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22e00dcf-7769-4038-bcb3-7abc28478732',
        'JME : L’engagement fort de la Sobraga et de l’ONG Komo Océan pour le littoral gabonais',
        'Lors de la Journée mondiale de l’Environnement, la SOBRAGA a renforcé son engagement pour protéger le littoral gabonais en participant à une opération de nettoyage menée par l’ONG SOS Komo Ocean.',
        'https://directinfosgabon.com/jme-lengagement-fort-de-la-sobraga-et-de-long-komo-ocean-pour-le-littoral-gabonais/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55e148ea-2a09-4c0f-b783-f0edaf9f3686',
        '« Comme tout le monde, le Gabon a les yeux tournés vers l’Iran »',
        'Le Gabon suit avec attention les enjeux géopolitiques liés à l''Iran, notamment en raison des tensions internationales pouvant affecter le marché mondial de l’énergie et ses impacts pour le pays.',
        'https://directinfosgabon.com/comme-tout-le-monde-le-gabon-a-les-yeux-tournes-vers-liran/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ae46612-dc1c-43fb-b4e4-bfc39c1ea4e3',
        'Le Chinois CABC veut réhabiliter la Sogara et construire une nouvelle raffinerie',
        'Le groupe chinois CABC souhaite réhabiliter la centrale Sogara au Gabon et construire une nouvelle raffinerie pour améliorer la production locale de pétrole.',
        'https://directinfosgabon.com/le-chinois-cabc-veut-rehabiliter-la-sogara-et-construire-une-nouvelle-raffinerie/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '696ea812-1c71-481b-8990-3c492b419352',
        'AGASA : Un plan triennal ambitieux pour une sécurité alimentaire sans faille',
        'L’Agence gabonaise de sécurité alimentaire (AGASA) a présenté un plan triennal ambitieux visant à renforcer la sécurité alimentaire dans le pays.',
        'https://gabonactu.com/blog/2025/06/13/agasa-un-plan-triennal-ambitieux-pour-une-securite-alimentaire-sans-faille/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'adc88f60-d833-4d7c-9af3-2db0437bb7cf',
        'Guerre à Gaza : le Gabon exige un cessez-le-feu immédiat et permanent',
        'Le Gabon a voté en faveur d’un appel à un cessez-le-feu immédiat, inconditionnel et permanent à Gaza lors d''une session d''urgence à l’ONU, où la majorité des pays ont adopté cette résolution bien qu’elle ne soit pas contraignante.',
        'https://www.gabonreview.com/guerre-a-gaza-le-gabon-exige-un-cessez-le-feu-immediat-et-permanent/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff4fc80c-8c24-4ddf-a9da-8a9bdc87ef07',
        'Oligui Nguema rend hommage au général Ngari, figure emblématique du Gabon',
        'Le président gabonais a rendu hommage au général Idriss Firmin Ngari, une figure importante de l’histoire militaire et politique du Gabon, lors d''une cérémonie nationale à Libreville après son décès.',
        'https://www.gabonreview.com/oligui-nguema-rend-hommage-au-general-ngari-figure-emblematique-du-gabon/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3c9dd00-f97e-4768-bdbd-cc9f80cd8064',
        'Gabon : Le Porte-parole de la Présidence présente les orientations stratégiques du nouveau mandat',
        'Le porte-parole de la présidence gabonaise a présenté les grandes orientations du nouveau mandat, axées sur le développement économique, la consolidation de la paix et la modernisation du pays.',
        'https://kongossanews.info/gabon-le-porte-parole-de-la-presidence-presente-les-orientations-strategiques-du-nouveau-mandat/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ee45c5cc-5c1f-4529-9c46-234242162d66',
        'Journée mondiale de l’Environnement : SOBRAGA aux côtés de l’ONG SOS KOMO OCEAN pour protéger le littoral gabonais',
        'Sobraga, en collaboration avec SOS Komo Ocean, a organisé des activités pour sensibiliser à la protection du littoral gabonais lors de la Journée mondiale de l’environnement.',
        'https://kongossanews.info/journee-mondiale-de-lenvironnement-sobraga-aux-cotes-de-long-sos-komo-ocean-pour-proteger-le-littoral-gabonais/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5117cff5-9936-4807-adec-c61cc6a922de',
        'Publié le 13 / 06 / 2025',
        'Le Nigeria a lancé une nouvelle plateforme éducative numérique visant à rendre l''apprentissage plus accessible et interactif pour les étudiants à travers le pays.',
        'https://union.sonapresse.com/fr/lhommage-de-la-nation-au-general-idriss-firmin-ngari',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fba08541-372b-4a86-a082-6804626e94bb',
        'Publié le 13 / 06 / 2025',
        'Le président a suivi de près la situation actuelle, soulignant la nécessité de rester uni et de prendre des mesures concrètes pour le développement du pays.',
        'https://union.sonapresse.com/fr/theophane-nzame-nze-biyoghe-le-chef-de-letat-suit-la-situation-de-pres',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f96d8cae-74fd-486d-80c9-3537232e92c6',
        'Publié le 12 / 06 / 2025',
        'L’article explique la demande de Bilie Nze pour obtenir le décompte précis des indemnités dues suite à des déguerpissements, afin de faire valoir ses droits.',
        'https://union.sonapresse.com/fr/indemnisation-des-deguerpis-bilie-nze-demande-des-comptes',
        'L''union',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd314bf5d-713d-4b16-80b2-cd1626509621',
        'Journée mondiale de la sécurité et la santé au travail : la Sobraga veut prévenir les risques liés à l’alcool au travail Face à ...',
        'La Sobraga souhaite sensibiliser et prévenir les risques liés à la consommation d''alcool au travail pour garantir la sécurité et la santé des employés.',
        'https://mediapostegabon.com/journee-mondiale-de-la-securite-et-la-sante-au-travail-la-sobraga-veut-prevenir-les-risques-lies-a-lalcool-au-travail/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b238ffe-6757-40a4-8977-68160cc7c0db',
        'Future Cité administrative : Oligui Nguema pour un démarrage rapide des travaux Déguerpissement de Derrière-l’Assemblée : des fa...',
        'Le projet de la Future Cite Administrative d''Olougui Nguema vise à démarrer rapidement les travaux pour créer un centre administratif moderne, afin de répondre aux besoins de gestion urbaine à Libreville.',
        'https://mediapostegabon.com/future-cite-administrative-oligui-nguema-pour-un-demarrage-rapide-des-travaux/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16677cf5-6d18-49fa-97ad-9f1b6b054fa8',
        'Football/Linafp : la cérémonie du Ndambo d’Or fait son retour',
        'La cérémonie du Ndambo d’Or, qui récompense les meilleurs joueurs de football au Gabon, revient cette année après une pause, pour célébrer la saison 2024-2025.',
        'https://agpgabon.ga/football-linafp-la-ceremonie-du-ndambo-dor-fait-son-retour/',
        'AGP',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81a1bc19-776c-4562-aa84-ce4a964cd23c',
        'Gabon/Médias : Radio Gabon poursuit son programme de délocalisation de l’antenne',
        'Radio Gabon continue sa démarche de délocalisation en diffusant ses programmes depuis Cocobeach, une localité à 120 km de Libreville, sous la supervision du ministre de la Communication.',
        'https://agpgabon.ga/gabon-medias-radio-gabon-poursuit-son-programme-de-delocalisation-de-lantenne/',
        'AGP',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6cb295ef-1758-4181-8a88-958216740206',
        'Gabon/Bac 2025 : hébergement exceptionnel pour les candidats de Plaine-Orety',
        'À partir du 17 juin 2025, des internats pilotes seront ouverts dans la province de l’Estuaire pour héberger en priorité les élèves de terminale issus de la zone de Plaine-Orety, avec un encadrement renforcé pour assurer leur préparation sereine au bac.',
        'https://agpgabon.ga/gabon-bac-2025-hebergement-exceptionnel-pour-les-candidats-de-plaine-orety/',
        'AGP',
        'Business Intelligence',
        '2025-06-13T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc07b6b7-d41a-496d-bdf4-79c3de0655b2',
        'Gabon : pourquoi la loi électorale ne doit pas être modifiée pour convenance présidentielle !',
        'La modification de la loi électorale en Guinée-Bissau pourrait compromettre la stabilité du processus démocratique et favoriser des manipulations politiques.',
        'https://gabonmediatime.com/gabon-pourquoi-la-loi-electorale-ne-doit-pas-etre-modifiee-pour-convenance-presidentielle/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e401293-ca19-4389-9938-8d8c64c243b2',
        'Gabon : la SNI engage une réforme stratégique du logement à l’horizon 2030',
        'La société nationale immobilière du Gabon (Sni) prévoit une réforme stratégique du logement d’ici 2030 pour améliorer l’accès et la qualité des habitations dans le pays.',
        'https://gabonmediatime.com/gabon-la-sni-engage-une-reforme-strategique-du-logement-a-lhorizon-2030/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93b2bc80-16d2-4de7-b6b9-dc139c900c22',
        'Bilie-By-Nze : « le gouvernement incapable de publier la liste des personnes indemnisées »',
        'Le gouvernement gabonais peine à publier la liste des personnes indemnisées, ce qui suscite la méfiance et remet en question la transparence du processus d''indemnisation.',
        'https://gabonmediatime.com/bilie-by-nze-le-gouvernement-incapable-de-publier-la-liste-des-personnes-indemnisees/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '784aa3f7-ec08-4ea6-b21c-bbd785a06caa',
        'Igor Ngombamoye et son projet de société pour la commune de Bakoumba (Haut-Ogooué)',
        'Igor Ngombamoye présente son projet pour redynamiser la commune de Bakoumba en mettant en avant son histoire tout en préparant sa candidature aux prochaines élections législatives et locales.',
        'https://www.gabonews.com/fr/actus/politique/article/igor-ngombamoye-et-son-projet-de-societe-pour-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b97445a-f5c9-4ba3-8cba-fe38f9add7da',
        'Gabon : pourquoi la loi électorale ne doit pas être modifiée pour convenance présidentielle !',
        'Modifier la loi électorale pour répondre aux intérêts du président pourrait fragiliser la démocratie et la stabilité politique du pays.',
        'https://gabonmediatime.com/gabon-pourquoi-la-loi-electorale-ne-doit-pas-etre-modifiee-pour-convenance-presidentielle/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5e81f38-c75d-4d57-887a-149cd26469e4',
        'Gabon : la SNI engage une réforme stratégique du logement à l’horizon 2030',
        'La Société Nationale Immobilière (SNI) de Gabon prévoit de mettre en œuvre une réforme stratégique du secteur du logement d''ici 2030 pour améliorer l''accès au logement et répondre aux besoins de la population.',
        'https://gabonmediatime.com/gabon-la-sni-engage-une-reforme-strategique-du-logement-a-lhorizon-2030/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4dd172da-1e4a-4674-ae33-caba7b9f94f2',
        'Bilie-By-Nze : « le gouvernement incapable de publier la liste des personnes indemnisées »',
        'Le gouvernement gabonais est incapable de publier la liste des personnes indemnisées, ce qui soulève des questions sur la transparence et la gestion de cette indemnisation.',
        'https://gabonmediatime.com/bilie-by-nze-le-gouvernement-incapable-de-publier-la-liste-des-personnes-indemnisees/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b09adc3-adb8-45af-a4ba-eb83d6bb059a',
        'Oyima trouve les bureaux du Ministère de l’Économie trop vieux et travaille depuis BGFI',
        'Oyima a constaté que les bureaux du ministère de l’Économie à Abidjan sont vieux et mal entretenus, puisqu''il travaille depuis une ancienne bâtisse louée par BGFI.',
        'https://kongossanews.info/oyima-trouve-les-bureaux-du-ministere-de-leconomie-trop-vieux-et-travaille-depuis-bgfi/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4366e3b9-75f1-40c1-977f-da4f85962b83',
        'Publié le 14 / 06 / 2025',
        'L''article révèle des irregularités et des incohérences dans le processus de déguerpissement mené par Jean Rémy Yama, soulignant des préoccupations concernant la transparence et la légalité des opérations.',
        'https://union.sonapresse.com/fr/deguerpissements-jean-remy-yama-pointe-des-irregularites',
        'L''union',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7cfdb436-97fd-4bd4-8b1f-5ee8dddeea03',
        'Publié le 13 / 06 / 2025',
        'Le projet de réforme sur le financement et la structuration des partis politiques ivoiriens a été examiné au parlement, visant à renforcer la transparence et la démocratie à travers de nouvelles normes législatives.',
        'https://union.sonapresse.com/fr/reforme-des-partis-politiques-le-projet-de-loi-lexamen-au-palais-leon-mba',
        'L''union',
        'Business Intelligence',
        '2025-06-14T00:00:00.000Z',
        '2025-09-15T23:06:12.456Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

