-- Batch 4 - Section 8/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '5d5bb47a-41dc-4c42-83ad-565799777bd5',
        'Football/ Match amical : le Gabon battu par le Niger (3-4)',
        'Le Gabon a perdu un match amical contre le Niger avec un score de 3-4, en raison notamment des erreurs du gardien Noubi Fotso, malgré l’absence de deux de ses meilleurs attaquants.',
        'https://agpgabon.ga/2025/06/06/football-match-amical-le-gabon-battu-par-le-niger-3-4/',
        'AGP',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '29f209b6-4d75-445e-ac6d-a9f23cd3e9f6',
        'ANBG/l’impunité persiste: La réforme du Pr. Ruphin Ndjambou dérange les réseaux mafieux',
        'L''opposition LINPULおite continue de défendre la réforme du PR Ruphın Ndjambou, malgré la résistance de réseaux mafieux qui cherchent à la déstabiliser.',
        'https://kongossanews.info/anbg-limpunite-persiste-la-reforme-du-pr-ruphin-ndjambou-derange-les-reseaux-mafieux/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '432f8d7a-894e-46b4-be50-0e14488df7e0',
        'Le Gabon lance la commercialisation des voitures 100 % électriques',
        'Le Gabon a lancé la commercialisation de voitures entièrement électriques, avec l''arrivée de la marque chinoise BYD sur le marché gabonais, offrant désormais des véhicules à la location ou à l’achat.',
        'https://directinfosgabon.com/le-gabon-lance-la-commercialisation-des-voitures-100-electriques/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7a6bf3d-8146-4db6-a9c1-bab854c686ef',
        'Match amical/Gabon-Niger : ” Le football est fait d’erreurs”, dixit Thierry Mouyouma',
        'Le sélectionneur gabonais Thierry Mouyouma a déclaré que les erreurs font partie du football et a choisi de soutenir son gardien, malgré ses fautes lors d’un match amical perdu face au Niger.',
        'https://agpgabon.ga/2025/06/07/match-amical-gabon-niger-le-football-est-fait-derreurs-dixit-thierry-mouyouma/',
        'AGP',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4a64c8a4-8ef4-45b2-9328-c87e754704da',
        'Gabon: les habitants d’un quartier inondable manifestent contre les déguerpissements',
        'Depuis le 6 juin, l’État gabonais a démoli plusieurs maisons dans certains quartiers de Libreville pour construire une cité administrative et un boulevard, ce qui a provoqué la colère et la tristesse des habitants délogés qui dorment à la belle étoile, malgré les indemnisations annoncées.',
        'https://www.rfi.fr/fr/afrique/20250607-gabon-les-habitants-d-un-quartier-inondable-manifestent-contre-les-d%C3%A9guerpissements',
        'RFI',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8ff7405-8d1c-4b4f-9979-73f6d871531d',
        'Ministère de la Femme… Elodie Diane Fouéfoué Sandjoh en parle aux femmes de POG',
        'La ministre de la Femme, de la famille et de la protection de l’enfance a échangé avec les femmes de Port-Gentil pour discuter de leurs préoccupations et de l’amélioration de leur conditions.',
        'https://gabonactu.com/blog/2025/06/07/ministere-de-la-femme-elodie-diane-fouefoue-sandjoh-en-parle-aux-femmes-de-pog/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25ea85e3-e998-4d56-8cc2-e2a523f20266',
        'Gabon : 7 mineurs détenus de la prison centrale de Libreville ont participé à l’examen du CEP 2025',
        'Sept mineurs en conflit avec la loi ont participé à l’examen du Certificat d’Études Primaires (CEP) 2025 à la prison centrale de Libreville, dans le cadre d’une initiative visant à favoriser leur accès à l''éducation.',
        'https://gabonactu.com/blog/2025/06/07/gabon-7-mineurs-detenus-de-la-prison-centrale-de-libreville-ont-participe-a-lexamen-du-cep-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9d24a8b-b8d7-4dc3-afc2-13e16f607245',
        '« Nouvelle Reine » : La plus grande téléréalité panafricaine débarque sur CANAL+ POP dès ce samedi, 20h30 GMT',
        'Une nouvelle télé-réalité panafricaine appelée « Nouvelle Reine » débute ce samedi sur CANAL+POP, avec plus de 300 candidates, pour divertir et mettre en valeur des jeunes femmes d’Afrique.',
        'https://gabonactu.com/blog/2025/06/07/nouvelle-reine-la-plus-grande-telerealite-panafricaine-debarque-sur-canal-pop-des-ce-samedi-20h30-gmt/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ce5d5d6-b5f3-4e56-a8e2-73605a6ada4a',
        'Priscilia Causette Akouma Aboue : « La jeunesse gabonaise doit prendre sa place dans l''histoire ».',
        'Depuis l''arrivée du Comité pour la Transition et la Restauration des Institutions, le Gabon amorce une réforme majeure, en misant notamment sur la jeunesse, qui constitue une majorité de la population, comme acteur clé du changement.',
        'https://www.gabonews.com/fr/actus/politique/article/priscilia-causette-akouma-aboue-la-jeunesse',
        'Gabonews',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a83e864b-fdce-4648-8adf-6c8e9a59c0c1',
        'Amour Bekale Nzé officiellement candidat aux élections législatives de 2025.',
        'Les habitants d''Ebel-Abanga ont exprimé leur souhait que leur compatriote Amour Bekale Nzé se présente aux élections législatives de septembre, ce qu''il a accepté en réponse à leur appel.',
        'https://www.gabonews.com/fr/actus/politique/article/amour-bekale-nze-officiellement-candidat-aux',
        'Gabonews',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2b6d1f0e-124d-42e9-9520-0f1ed47f104f',
        'Gabon : le Vice-Président gabonais échange avec l’Ambassadeur de Chine',
        'Le Vice-Président gabonais a rencontré l’ambassadeur de Chine, qui lui a transmis un message de félicitations du vice-président chinois, soulignant l’excellence des relations bilatérales entre les deux pays.',
        'https://agpgabon.ga/2025/06/07/gabon-le-vice-president-gabonais-echange-avec-lambassadeur-de-chine/',
        'AGP',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'efdbe296-545d-4a37-8c52-440b5d58f7fc',
        'Secondaire : Les bourses seront payées cette fin du mois',
        'Les bourses des élèves du secondaire seront versées d’ici la fin du mois, suite à des instructions du président transmises au Vice-président du Gouvernement.',
        'https://gabonactu.com/blog/2025/06/07/secondaire-les-bourses-seront-payees-cette-fin-du-mois/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '058d5a82-5a87-45ba-9d4e-0c22b6342323',
        'Gabon/Karaté : Me Thibault Ngassi, nouveau président de la Ligue de l’Estuaire',
        'Thibault Ngassi a été élu président de la Ligue de karaté de l’Estuaire pour un mandat de 4 ans, lors d''un scrutin qui a opposé 17 clubs sur 32 à son adversaire.',
        'https://agpgabon.ga/2025/06/07/gabon-karate-me-thibault-ngassi-nouveau-president-de-la-ligue-de-lestuaire/',
        'AGP',
        'Business Intelligence',
        '2025-06-07T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce5ba4dc-7d5e-45de-b0f4-42e4768c37bf',
        'Les Panthères du Gabon : l’urgence d’un renforcement du staff technique !',
        'Le staff technique des Panthères du Gabon est en train d’être renforcé pour améliorer la performance de l''équipe nationale gabonaise.',
        'https://gabonmediatime.com/les-pantheres-du-gabon-lurgence-dun-renforcement-du-staff-technique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e314d7c-ff0a-4673-ac4e-3e5ff1b8a4a6',
        'Malabo : Oligui Nguema s’imprègne du modèle de développement équato-guinéen',
        'Malabo adopte un modèle de développement basé sur l’exploitation des ressources naturelles, évoquant un parallèle avec le modèle équato-guinéen, mais cette stratégie soulève des questions sur sa durabilité et ses impacts sociaux.',
        'https://gabonmediatime.com/malabo-oligui-nguema-simpregne-du-modele-de-developpement-equato-guineen/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d725f63-3913-4c8a-b523-6de0e1bbe411',
        'Gabon : le 1er tour des élections locales fixé au 27 septembre 2025',
        'Le premier tour des élections locales en Gabon est prévu pour le 27 septembre 2025.',
        'https://gabonmediatime.com/gabon-le-1er-tour-des-elections-locales-fixe-au-27-septembre-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4192e29-7a33-401e-96a0-a507921475fb',
        'Brice Clotaire Oligui Nguema rassure la communauté gabonaise de Guinée équatoriale',
        'Le président Brice Clotaire Oligui Nguema a rassuré la communauté gabonaise en Guinée équatoriale en répondant à leurs préoccupations, notamment concernant l’établissement des pièces d’état civil, lors d’une rencontre officielle.',
        'https://agpgabon.ga/2025/06/07/brice-clotaire-oligui-nguema-rassure-la-communaute-gabonaise-de-guinee-equatoriale/',
        'AGP',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04a1eaad-8f95-41a9-85f1-ac8c09e8e9f1',
        'RDC-Rwanda : Kigali annonce son retrait de la CEEAC après le sommet de Malabo',
        'Le Rwanda a annoncé son retrait de la CEEAC après le sommet de Malabo, accusant la RDC de vouloir prendre le contrôle de l’organisation en ignorant leur droit à la présidence rotative.',
        'https://agpgabon.ga/2025/06/07/rdc-rwanda-kigali-annonce-son-retrait-de-la-ceeac-apres-le-sommet-de-malabo/',
        'AGP',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36113fa9-1483-41b5-a916-404f766b1852',
        'Les Panthères du Gabon : l’urgence d’un renforcement du staff technique !',
        'Les "Panthères" du Gabon renforcent leur staff technique pour améliorer leurs performances et préparer efficacement les compétitions à venir.',
        'https://gabonmediatime.com/les-pantheres-du-gabon-lurgence-dun-renforcement-du-staff-technique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a8602de5-9a30-42fe-9fe3-9e29e60e4802',
        'Malabo : Oligui Nguema s’imprègne du modèle de développement équato-guinéen',
        'Malabo impose un modèle de développement inspiré de l''Equateur, ce qui pourrait renforcer son indépendance économique mais soulève aussi des enjeux liés à la dépendance et à la gestion des ressources.',
        'https://gabonmediatime.com/malabo-oligui-nguema-simpregne-du-modele-de-developpement-equato-guineen/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dbb7e6a4-c28e-47d8-8af6-5b4e305cf5ff',
        'Gabon : le 1er tour des élections locales fixé au 27 septembre 2025',
        'La date du premier tour des élections locales au Gabon est fixée au 27 septembre 2025.',
        'https://gabonmediatime.com/gabon-le-1er-tour-des-elections-locales-fixe-au-27-septembre-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '650ff9c7-65b0-4d4b-b356-868fa408b78f',
        'Publié le 08 / 06 / 2025',
        'Le Rwanda a annoncé qu''il quitte la Communauté économique des États de l''Afrique centrale (CEEAC) à cause de désaccords et de problèmes de gouvernance au sein de l''organisation.',
        'https://union.sonapresse.com/fr/ceeac-le-rwanda-claque-la-porte-de-lorganisation',
        'L''union',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40138fdb-6c83-447e-9d51-94db3998bdcb',
        'Publié le 07 / 06 / 2025',
        'Le calendrier officiel des élections législatives, départementales et municipales de 2025 a été dévoilé, précisant les dates clés pour l''organisation de ces scrutins en France.',
        'https://union.sonapresse.com/fr/elections-2025-le-calendrier-officiel-des-legislatives-departementales-et-municipales-devoile',
        'L''union',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c0e89e2-ac40-490d-9601-21790c6c7f38',
        'Violence conjugale : Prisca Mabambatsi M’Kanza scrute le tabou chez les hommes au Gabon Libreville : série de démolitions au « B...',
        'L''article explique comment la violence conjugale est encore un sujet tabou chez certains hommes au Gabon, ce qui empêche souvent les victimes de parler ou de demander de l’aide.',
        'https://mediapostegabon.com/violence-conjugale-prisca-mabambatsi-mkanza-le-tabou-chez-les-hommes-au-gabon/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '079845a6-a10f-4d11-8551-996cf4595b6b',
        'Développer et moderniser le Gabon : méthode et stratégie (tribune libre)',
        'L''article propose une approche stratégique pour moderniser et développer le Gabon en s''appuyant sur des méthodes innovantes, des réformes structurantes et une vision à long terme pour impulser la croissance et la stabilité du pays.',
        'https://gabonactu.com/blog/2025/06/08/developper-et-moderniser-le-gabon-methode-et-strategie-tribune-libre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a034f616-1889-4202-9024-bfbc011fee96',
        'Omar Bongo : 16 ans déjà après sa mort',
        '16 ans après sa mort, Omar Bongo demeure une figure centrale de la politique gabonaise, dont l''héritage influence encore le pays, notamment à travers le PDG et le contexte post-Bongo.',
        'https://gabonactu.com/blog/2025/06/08/omar-bongo-16-ans-deja-apres-sa-mort/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '23e5cccb-8fd2-45d6-a343-4a3aa8a978ac',
        'Les nominés de la 2ème édition des Awards de la presse gabonaise » Makongonio »',
        'La deuxième édition des Awards de la presse gabonaise "Makongonio" annonce ses nominés dans plusieurs catégories, dont le Prix de l''Innovation 2025 et le Meilleur Journaliste Politique.',
        'https://www.gabonews.com/fr/actus/communication/article/les-nomines-de-la-2eme-edition-des-awards-de-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8681ef4e-d51d-4c97-b3dc-d9272661be11',
        'Présidence tournante de la CEEAC: départ du Rwanda, la Guinée Équatoriale garde la main',
        'Le président Brice Clotaire OLIGUI NGUEMA a participé à la 26e session de la Conférence des Chefs d’État de la CEEAC, organisée en Guinée équatoriale, qui a notamment abordé la gestion de la présidence tournante sous-régionale.',
        'https://vxp241.com/2025/06/08/presidence-tournante-de-la-ceeac-depart-du-rwanda-la-guinee-equatoriale-garde-la-main/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e125fdb-c856-4e52-be1f-210c006e7df5',
        'Journée africaine des frontières : Etat des lieux des frontières gabonaises',
        'Les membres de la Commission nationale des frontières ont évoqué l’état actuel des frontières gabonaises lors d’une conférence organisée dans le cadre de la 15ème édition de la Journée africaine des frontières.',
        'https://gabonactu.com/blog/2025/06/08/journee-africaine-des-frontieres-etat-des-lieux-des-frontieres-gabonaises/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4091c3bb-67de-48f6-bbf7-38175b9f4ec6',
        '«De quoi avez-vous besoin ?» : le numérique gabonais face à ses défis',
        'L''article souligne les défis du secteur numérique au Gabon, notamment le besoin d''infrastructures solides, de formations adaptées et d''une meilleure coordination pour stimuler l''innovation et accompagner la transition digitale du pays.',
        'https://www.gabonreview.com/de-quoi-avez-vous-besoin-le-numerique-gabonais-face-a-ses-defis/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dd3a0ac1-66f3-4de7-b301-12370df51eb6',
        'Les Gabonitudes de Lybek à l’Université : quand la BD devient miroir de société',
        'La bande dessinée francophone, notamment l''œuvre engagée du auteur gabonais Lybek, est utilisée comme miroir de la société lors d''une journée académique, permettant de réfléchir sur des thèmes comme l''identité, la citoyenneté et les enjeux sociaux.',
        'https://www.gabonreview.com/les-gabonitudes-de-lybek-a-luniversite-quand-la-bd-devient-miroir-de-societe/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8b0001e3-b83e-4754-b448-474ca8bceb59',
        'Et vint l’UGN… un nouvel acteur politique en marche vers les législatives et locales',
        'L’Union pour un Gabon Nouveau (UGN), un nouveau parti politique créé en juin à Libreville, rassemble des membres issus de deux mouvements existants et se prépare à participer aux prochaines élections législatives et locales.',
        'https://www.gabonreview.com/et-vint-lugn-un-nouvel-acteur-politique-en-marche-vers-les-legislatives-et-locales/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5f82499-4a11-4507-8345-17fba386e189',
        'Législatives et locales 2025 : Les associations membres du PNSPA dans les starting-blocks',
        'Les associations membres du PNSPA se préparent activement pour les élections législatives et locales de 2025, en participant à une cérémonie officielle pour marquer leur engagement et leur organisation.',
        'https://gabonactu.com/blog/2025/06/08/legislatives-et-locales-2025-les-associations-membres-du-pnspa-dans-les-starting-blocks/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3870f60c-21d6-4bde-9da1-3f484589544e',
        '« Baby Champion » : Les pépites du taekwondo sur les tatamis ces 21 et 22 juin',
        'Un championnat de taekwondo réservé aux jeunes talents, appelé « Baby Champion », aura lieu les 21 et 22 juin, organisé par l’AGATAMA, pour découvrir et encourager la relève dans ce sport.',
        'https://gabonactu.com/blog/2025/06/08/baby-champion-les-pepites-du-taekwondo-sur-les-tatamis-ces-21-et-22-juin/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '918adae4-c726-4b7d-b971-528623ecf6aa',
        'Gabon/Axe Libreville-Ntoum : les nouveaux tarifs dévoilés',
        'Les nouveaux tarifs pour le transport entre Libreville et Ntoum, adaptés à la réduction du nombre de passagers par véhicule, entreront en vigueur dès le 9 juin 2025, conformément aux réglementations en vigueur.',
        'https://agpgabon.ga/2025/06/08/gabon-axe-libreville-ntoum-les-nouveaux-tarifs-devoiles/',
        'AGP',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce8d04df-dadc-45ef-b192-75270bb1a7bb',
        'Football/ Panthères du Gabon : à quand la fin du Mouyouma bashing?',
        'Depuis la défaite du Gabon face au Niger, l''entraîneur Thierry Mouyouma est victime d''une campagne de critique dans les médias, bien que sa nomination ait été initialement saluée par le public gabonais souhaitant un technicien local.',
        'https://agpgabon.ga/2025/06/08/football-pantheres-du-gabon-a-quand-la-fin-du-mouyouma-bashing/',
        'AGP',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b096edd6-251f-4634-9ecf-198241a9b928',
        'Canton Bissok : Les retrouvailles',
        'Des ressortissants du Canton Bissok de la région de Mitzic se sont retrouvés à Libreville pour une rencontre organisée par l’Abbé Bruno Ondo Mintsa, renforçant ainsi leurs liens communautaires.',
        'https://gabonactu.com/blog/2025/06/08/canton-bissok-les-retrouvailles/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd75aafa1-d410-4b53-b3fd-878027075503',
        'PDG Woleu -Ntem : Antoine Menie M''eyi en tournée de sensibilisation et d''information dans le "Grand Nord"',
        'Le secrétaire général adjoint 2 du PDG parcourt la province du Woleu Ntem pour sensibiliser les responsables locaux, préparer la visite du président du parti à Oyem et renforcer la mobilisation en vue des prochaines échéances politiques.',
        'https://www.gabonews.com/fr/actus/politique/article/pdg-woleu-ntem-antoine-menie-m-eyi-en-tournee-de',
        'Gabonews',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7003567-7b95-4232-b7f2-60bd25ce73ed',
        'Gabon/Commémoration : Brice Clotaire Oligui Nguema rend hommage à feu Omar Bongo Ondimba',
        'Le président gabonais s’est rendu au mausolée d’Omar Bongo Ondimba pour rendre hommage au 16e anniversaire de son décès et saluer son héritage de paix.',
        'https://agpgabon.ga/2025/06/08/gabon-commemoration-brice-clotaire-oligui-nguema-rend-hommage-a-feu-omar-bongo-ondimba/',
        'AGP',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e6a25b9-7e7e-43b2-aa60-a793325119aa',
        '6ème édition du Top 100 : La Comilog encourage l’excellence à l’école',
        'La Comilog a récompensé les 100 meilleurs élèves de Moanda pour encourager l''excellence scolaire lors de la 6ème édition du « Top 100 » pour l’année académique 2024-2025.',
        'https://gabonactu.com/blog/2025/06/08/6eme-edition-du-top-100-la-comilog-encourage-lexcellence-a-lecole/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-08T00:00:00.000Z',
        '2025-09-15T23:06:12.452Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f19f1a1-c896-45a6-a4c5-7b1aa123ea9f',
        'Les miniers face au défi du Gabon de transformer localement le manganèse',
        'Le gouvernement gabonais a décidé qu''avant 2029, tout le manganèse produit dans le pays doit subir au moins une première transformation locale afin de créer des emplois et soutenir le développement industriel.',
        'https://www.rfi.fr/fr/podcasts/chronique-des-mati%C3%A8res-premi%C3%A8res/20250608-les-miniers-face-au-d%C3%A9fi-du-gabon-de-transformer-localement-le-mangan%C3%A8se',
        'RFI',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4163a1fa-1839-49d2-8a83-58af3fba6d9a',
        'Hommage à Omar Bongo : Oligui Nguema salue l’héritage d’un bâtisseur de la Nation',
        'Omar Bongo Ondimba est salué pour son rôle de bâtisseur de la nation gabonaise et pour avoir laissé un héritage important dans l''histoire du pays.',
        'https://gabonmediatime.com/hommage-a-omar-bongo-oligui-nguema-salue-lheritage-dun-batisseur-de-la-nation/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9c87ec78-550b-4fda-806f-90b9891b9824',
        'Lutte contre l’insalubrité : Adrien Nguema Mba sur les traces du Gen. Judes Ibrahim Rapontchombo ?',
        'Adrien Nguema Mbade souligne l''importance de lutter contre l''insalubrité pour améliorer la santé publique au Gabon, en s''inspirant du combat du général Ibrahim Rapontchombo.',
        'https://gabonmediatime.com/lutte-contre-linsalubrite-adrien-nguema-mba-sur-les-traces-du-gen-judes-ibrahim-rapontchombo/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1a6fddd-8d99-43c0-a77e-15080abe99a7',
        'Hommage à Omar Bongo : Oligui Nguema salue l’héritage d’un bâtisseur de la Nation',
        'Omar Bongo Ondimba est salué pour son rôle de bâtisseur de la nation gabonaise et pour son héritage de développement et de stabilité.',
        'https://gabonmediatime.com/hommage-a-omar-bongo-oligui-nguema-salue-lheritage-dun-batisseur-de-la-nation/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ecc420f9-6935-4910-bc8c-e4e75e1bb644',
        'Lutte contre l’insalubrité : Adrien Nguema Mba sur les traces du Gen. Judes Ibrahim Rapontchombo ?',
        'Adrien Nguema Mbá aborde la lutte contre l’insalubrité au Gabon en soulignant l''importance de l’engagement collectif pour améliorer les conditions de vie et préserver l’environnement.',
        'https://gabonmediatime.com/lutte-contre-linsalubrite-adrien-nguema-mba-sur-les-traces-du-gen-judes-ibrahim-rapontchombo/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5ecd9c6-02ec-471e-9cef-94fc091ab753',
        'AFRIK’AN LEGEND : “Terminus”, un nouveau départ pour un groupe déjà incontournable ?',
        'Le groupe africain Terminus marque un nouveau départ en se réinventant pour renforcer son influence et ses activités dans le secteur du divertissement et de la technologie.',
        'https://kongossanews.info/afrikan-legend-terminus-un-nouveau-depart-pour-un-groupe-deja-incontournable/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b83a9152-67a5-43a1-9b79-5c57ece416b7',
        'COMILOG récompense l’excellence scolaire et sportive à Moanda lors de la 6e édition du Top 100',
        'Comilog a récompensé les élèves et sportifs les plus méritants de Moanda lors de la 6e édition du Top 100, encourageant ainsi l''excellence scolaire et sportive dans la région.',
        'https://kongossanews.info/comilog-recompense-lexcellence-scolaire-et-sportive-a-moanda-lors-de-la-6e-edition-du-top-100/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '30c5b741-65f1-4b0b-84c8-2c4f2c33f89e',
        'Visite de terrain du Ministre Philippe Tonangoye à la centrale solaire de Solen Énergie',
        'Le ministre de l''Accès Universel à l''Eau et à l''Énergie a visité une centrale solaire pour vérifier l''avancement technique et infrastructurel du projet.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/visite-de-terrain-du-ministre-philippe-tonangoye',
        'Gabonews',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e478c0c-e5b8-4a9a-8662-f9555be4b56f',
        'Marathon consultatif de la Jeunesse : Une mobilisation en vue des élections législatives et locales de 2025',
        'La jeunesse gabonaise organisera un marathon de consultations dans les neuf provinces du pays pour discuter des enjeux électoraux, des offres politiques et des moyens d''autonomisation économique et sociale en vue des élections de 2025.',
        'https://www.gabonews.com/fr/actus/politique/article/marathon-consultatif-de-la-jeunesse-une',
        'Gabonews',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '77ccdba5-45f5-4b78-b074-0d3bbdfa93b6',
        'AFRIK’AN LEGEND : “Terminus”, un nouveau départ pour un groupe déjà incontournable ?',
        'Le groupe africain Terminus évolue pour renforcer son influence dans le secteur des technologies, marquant ainsi un nouveau départ pour continuer à s''imposer comme une référence incontournable en Afrique.',
        'https://kongossanews.info/afrikan-legend-terminus-un-nouveau-depart-pour-un-groupe-deja-incontournable/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-09T00:00:00.000Z',
        '2025-09-15T23:06:12.453Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

