-- Batch 6 - Section 5/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'b70d075d-f59f-48a5-b328-2dd3fad75781',
        'Publié le 21 / 07 / 2025',
        'Le parti politique en question voit ses membres se réduire et ses activités diminuer, ce qui soulève des inquiétudes sur sa capacité à rester pertinent et à continuer d''influencer la scène politique.',
        'https://union.sonapresse.com/fr/pdg-entre-temps-le-parti-se-vide',
        'L''union',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '52ca5cb1-58d1-4342-bde4-a93c1ffee742',
        'Publié le 21 / 07 / 2025',
        'Le risque d''escalade est une menace croissante pour la stabilité mondiale, nécessitant une vigilance accrue et des efforts diplomatiques pour prévenir les conflits.',
        'https://union.sonapresse.com/fr/pdg-risque-descalade-aujourdhui-louis',
        'L''union',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '04f9cd91-2863-4f13-9d18-edeb58dc4435',
        'Gabon : lancement des adhésions à l’Union Démocratique des Bâtisseurs (UDB) à Mounana',
        'La ville de Mounana a lancé officiellement les adhésions au parti Union Démocratique des Bâtisseurs (UDB), avec l’appel à rejoindre ce parti pour jouer un rôle important en politique nationale.',
        'https://agpgabon.ga/gabon-lancement-des-adhesions-a-lunion-democratique-des-batisseurs-udb-a-mounana/',
        'AGP',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c686648-8407-4d0a-a1bc-ae548cf0a801',
        'Pierre Mwegaya acquitté après 8 ans de prison pour rien',
        'Après avoir passé huit ans en prison sans preuve suffisante, Pierre Mwegaya a finalement été acquitté et retrouve la liberté.',
        'https://gabonactu.com/blog/2025/07/21/pierre-mwegaya-acquitte-apres-8-ans-de-prison-pour-rien/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f802f185-a9f6-41cb-8724-eddb4737b5a1',
        'Publié le 21 / 07 / 2025',
        'Le parti politique se vide peu à peu de ses membres, ce qui soulève des inquiétudes concernant sa stabilité et son avenir politique.',
        'https://union.sonapresse.com/fr/pdg-entre-temps-le-parti-se-vide',
        'L''union',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f5f8aa7-d5f3-4a8f-8f3d-90938b0990f2',
        'Publié le 21 / 07 / 2025',
        'Le risque de montée des tensions et des conflits aujourd''hui reste élevé, notamment en raison des défis économiques, politiques et sociaux auxquels plusieurs pays sont confrontés.',
        'https://union.sonapresse.com/fr/pdg-risque-descalade-aujourdhui-louis',
        'L''union',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e054eb52-be7d-4552-98ea-9558ca416346',
        'Gabon : ouverture des conférences budgétaires 2026 pour un budget réaliste et orienté vers les résultats',
        'Le gouvernement gabonais a lancé la préparation du budget pour 2026 lors de conférences organisées en deux phases, afin d’assurer une allocation efficace des ressources en fonction des priorités du pays.',
        'https://agpgabon.ga/gabon-ouverture-des-conferences-budgetaires-2026-pour-un-budget-realiste-et-oriente-vers-les-resultats/',
        'AGP',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6af5a0f2-6f1c-4972-859d-8a201d157fb4',
        'Première Foire Chine-Gabon : un pont économique entre Libreville et Pékin',
        'Le Gabon et la Chine renforcent leur partenariat économique avec la première Foire des Produits Chine-Gabon, qui se déroule du 24 au 27 juillet à Libreville, réunissant plus de 70 exposants de divers secteurs pour favoriser les échanges commerciaux.',
        'https://agpgabon.ga/premiere-foire-chine-gabon-un-pont-economique-entre-libreville-et-pekin/',
        'AGP',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '343aeece-eae9-40cf-9f5a-92de38af2143',
        'Conflit au PDG : L’aile Onanga Y’Obégué interdite de réunion au siège de Louis',
        'Une faction du Parti démocratique gabonais (PDG), dirigée par Onanga Y’Obégué, a été interdite d’organiser une réunion au siège du parti, provoquant des tensions avec la direction.',
        'https://www.gabonreview.com/conflit-au-pdg-laile-onanga-yobegue-interdite-de-reunion-au-siege-de-louis/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2edba5e1-0eb5-49bb-9e38-b6cad01c0142',
        'Élections locales : le choix contesté de Cyriaque Moukoundji, une menace pour la cohérence des Bâtisseurs ?',
        'Une controverse dépasse la désignation présumée de Cyriaque Moukoundji comme candidat à Mbigou, suscitant la méfiance et des critiques de la part des habitants face à cette décision politique.',
        'https://www.gabonews.com/fr/actus/politique/article/elections-locales-le-choix-conteste-de-cyriaque',
        'Gabonews',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9237e86-e124-4f18-87bb-d604063a323e',
        'Audience avec GVA Afrique chez le Ministre de l''Économie numérique',
        'Le Ministre de l''Économie numérique du Gabon a rencontré les responsables de GVA Afrique, rappelant que leur modèle a été lancé en 2013 au Gabon avant d’être adopté dans neuf autres pays africains.',
        'https://www.gabonews.com/fr/actus/economie-numerique/article/audience-avec-gva-afrique-chez-le-ministre-de-l',
        'Gabonews',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '15156efe-cd74-4b60-b60e-852fa2047f40',
        'Mbigou/ l''association Kundu Mulebe récompense les bacheliers méritants et honore ses promesses',
        'Des bacheliers de Mbigou ayant obtenu une moyenne supérieure ou égale à 12/20 ont reçu des ordinateurs portables offerts par l''association Kundu Mulebe, en récompense de leur réussite, lors d''une cérémonie présidée par Hilaire Leckat.',
        'https://www.gabonews.com/fr/actus/societe/article/mbigou-l-association-kundu-mulebe-recompense-les',
        'Gabonews',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81f370ae-d26e-40c6-8378-cd6dc4414356',
        'Mission du CNEPC et DGTT : les auto-écoles invitées à faire des efforts Cadre de vie : la Cité des Sapeurs-Pompiers du Centre de...',
        'Les auto-écoles sont invitées à fournir des efforts pour respecter les missions et directives fixées par le CNEPC et la DGTT, afin d''améliorer la qualité de la formation et la sécurité routière.',
        'https://mediapostegabon.com/mission-du-cnepc-et-dgtt-les-auto-ecoles-invitees-a-faire-des-efforts/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '20cd287c-733f-4628-a6e6-3214b9b2f0f0',
        'Transparence & Bonne gouvernance: OLIGUI NGUEMA & la société civile passe à l’offensive',
        'Le président Brice Clotaire OLIGUI NGUEMA a rencontré des représentants de la société civile pour discuter de la transparence, de la bonne gouvernance et de la gestion rigoureuse des fonds publics, notamment la lutte contre l’enrichissement illicite.',
        'https://vxp241.com/2025/07/21/transparence-bonne-gouvernance-oligui-nguema-la-societe-civile-passe-a-loffensive/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-21T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c95b84f0-5378-4124-b986-dc9a00e7b300',
        'Mission du CNEPC et DGTT : les auto-écoles invitées à faire des efforts Cadre de vie : la Cité des Sapeurs-Pompiers du Centre de...',
        'Les auto-écoles sont invitées à renforcer leurs efforts pour améliorer la qualité de la formation et respecter les réglementations en vigueur, dans le cadre de la mission du CNEPC et de la DGTT.',
        'https://mediapostegabon.com/mission-du-cnepc-et-dgtt-les-auto-ecoles-invitees-a-faire-des-efforts/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ed395487-1a24-4818-aff3-141318411d51',
        'Gabon/Crise au PDG : les militants du clan Ali Akbar Y’Obegue refoulés du siège du parti',
        'Des militants proches d’Ali Akbar Y’Obegue du PDG ont été empêchés d’entrer dans le siège du parti à Libreville, lorsque qu’une réunion stratégique prévue pour les élections a été annulée.',
        'https://agpgabon.ga/gabon-crise-au-pdg-les-militants-du-clan-ali-akbar-yobegue-refoules-du-siege-du-parti/',
        'AGP',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b440c61b-7f84-454b-b431-6118a9cb48b5',
        'Gabon/Diplomatie : le Chef de l’État reçoit le Secrétaire général de l’OEACP',
        'Le président gabonais a rencontré le Secrétaire général de l’OEACP pour évoquer les priorités de l’organisation et préparer le sommet prévu à Malabo à la fin de l’année.',
        'https://agpgabon.ga/gabon-diplomatie-le-chef-de-letat-recoit-le-secretaire-general-de-loeacp/',
        'AGP',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe3d4010-7996-4218-b439-8da98402c572',
        'Gabon : Adoption du compte administratif de gestion de l’exercice 2024 de la commune de Makokou',
        'Le budget 2024 de la commune de Makokou a été adopté, avec un montant de 598,9 millions FCFA, soit une réduction par rapport à l''année précédente.',
        'https://agpgabon.ga/gabon-adoption-du-compte-administratif-de-gestion-de-lexercice-2024-de-la-commune-de-makokou/',
        'AGP',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd498145b-52aa-40cb-943c-91b913b617ec',
        'PDG : Bataille du siège sur fond de bataille de légalité',
        'Le conflit au sein du Parti démocratique gabonais (PDG) oppose des factions autour de la légitimité de la direction et du contrôle du siège, révélant des tensions entre ses différents membres.',
        'https://gabonactu.com/blog/2025/07/22/pdg-bataille-du-siege-sur-fond-de-bataille-de-legalite/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c1b540a3-9e15-4fd8-841f-74edf17c3c03',
        'Hôtellerie-restauration : 6 entreprises sur 10 échappent encore à la CNSS à Akanda',
        'Une majorité d’hôtels, restaurants et snack-bars à Akanda ne sont pas encore enregistrés auprès de la CNSS, malgré une opération de contrôle lancée pour renforcer leur conformité aux obligations sociales.',
        'https://directinfosgabon.com/hotellerie-restauration-6-entreprises-sur-10-echappent-encore-a-la-cnss-a-akanda/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.476Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '77c323aa-0ccf-4098-b9e0-c72526951dd1',
        'Conférences budgétaires 2026 : Un nouveau format pour coller à l’objectif de 10 % de croissance',
        'Les conférences budgétaires pour 2026 innovent en s’organisant en deux étapes distinctes, d’abord pour les recettes puis pour les dépenses, afin d’atteindre l’objectif de croissance de 10 %.',
        'https://directinfosgabon.com/conferences-budgetaires-2026-un-nouveau-format-pour-coller-a-lobjectif-de-10-de-croissance/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44fa2672-059e-44d2-b83b-26dac16a13f8',
        'Setrag : Des rails plus robustes pour le tronçon Oyan-Ebel Abanga',
        'La société Setrag modernise et renforce le réseau ferroviaire gabonais en remplaçant les vieux rails par des matériaux plus solides sur le tronçon Oyan-Ebel Abanga dans le cadre de son programme de sécurisation.',
        'https://directinfosgabon.com/setrag-des-rails-plus-robustes-pour-le-troncon-oyan-ebel-abanga/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5fa34950-54b2-47b7-bde3-ab57f99c8203',
        'Gabon : bientôt une plainte pour corruption contre des responsables de l’ancien régime',
        'Une plainte pour corruption pourrait soon être déposée contre d''anciens responsables du régime gabonais, suite à des révélations sur des détournements de fonds.',
        'https://gabonmediatime.com/gabon-bientot-une-plainte-pour-corruption-contre-des-responsables-de-lancien-regime/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e51b17ca-d972-4bd2-ad40-44151b1cc79c',
        'Mouila : 1 mois de cours de soutien offerts par Pr. Marcelle Ibinga aux élèves',
        'Pr. Marcelle Ibinga offre un mois de cours de soutien gratuit aux élèves de Moïla pour améliorer leur apprentissage.',
        'https://gabonmediatime.com/mouila-1-mois-de-cours-de-soutien-offerts-par-pr-marcelle-ibinga-aux-eleves/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2f147fc-e0d3-4101-b2ff-c84cc2c45119',
        'PDG : la bataille de Louis n’a pas eu lieu',
        'La bataille de Louis N’Dame, qui aurait dû opposer deux groupes de rebelles, n’a pas eu lieu en raison d’un accord de paix entre les factions rivales.',
        'https://gabonmediatime.com/pdg-la-bataille-de-louis-na-pas-eu-lieu/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd31abaca-7b06-4102-9c4d-fd7cdcc07def',
        'Souveraineté économique et alimentaire : Louise Pierrette Mvono mobilise les partenaires au développement',
        'Lundi, lors d’une rencontre avec des partenaires du développement, Louise-Pierrette Mvono a souligné l’importance de renforcer la souveraineté économique et alimentaire du pays en mobilisant l’aide extérieure pour soutenir ces secteurs clés.',
        'https://kongossanews.info/souverainete-economique-et-alimentaire-louise-pierrette-mvono-mobilise-les-partenaires-au-developpement/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8590c1b2-021e-4669-8fea-6d039f66299e',
        'Le Président Oligui Nguema inaugure la cité rénovée des sapeurs-pompiers de Nomba à Owendo',
        'Le président Olingui Nguema a inauguré la nouvelle cité rénovée des sapeurs-pompiers de Nomba à Owendo, visant à améliorer la sécurité et la capacité d’intervention dans la région.',
        'https://kongossanews.info/le-president-oligui-nguema-inaugure-la-cite-renovee-des-sapeurs-pompiers-de-nomba-a-owendo/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a44d8f4-3a42-4d26-af83-51bd13124393',
        'Minerais critique : l’Europe supplantée',
        'L''Europe souhaite réduire sa dépendance aux minerais en développant ses propres ressources, tandis que certains pays africains critiquent cette démarche, considérant qu''elle pourrait limiter leurs opportunités d''exportation et de développement économique.',
        'https://kongossanews.info/minerais-critique-leurope-supplantee/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ebfbb5e3-f10b-4fb2-be37-04d16f677f46',
        'La finale du concours « Djino Live Music Compétition » se déroulera ce dimanche 27 juillet : Gabon',
        'Onze jeunes talents ont participé à un concours de musique sur la plage du lycée Léon Mba, et la finale se déroulera ce dimanche 27 juillet pour désigner le gagnant.',
        'https://vxp241.com/2025/07/22/la-finale-du-concours-djino-live-music-competition-se-deroulera-ce-dimanche-27-juillet-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1a80170-7185-4218-8e57-58ddb2af452e',
        'À la Une: turbulences au sein du Parti démocratique gabonais',
        'Des tensions persistent au sein du Parti démocratique gabonais, avec des conflits internes qui fragilisent la stabilité du parti au pouvoir dans le pays.',
        'https://www.rfi.fr/fr/podcasts/revue-de-presse-afrique/20250722-%C3%A0-la-une-turbulences-au-sein-du-parti-d%C3%A9mocratique-gabonais',
        'RFI',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a774de6-f4eb-4ef1-a2e3-8e28de1310c6',
        'Gabon: le litige entre nouvelle direction du PDG et pro-Bongo se poursuit devant le siège du parti',
        'Une nouvelle crise éclate au sein du Parti démocratique gabonais, opposant deux factions rivales qui se disputent le contrôle du parti, secteur clé de la politique gabonaise.',
        'https://www.rfi.fr/fr/afrique/20250722-gabon-le-litige-entre-nouvelle-direction-du-pdg-et-pro-bongo-se-poursuit-devant-le-si%C3%A8ge-du-parti',
        'RFI',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a1c634de-fa36-41d6-b08c-6e265cf10f69',
        'Gabon: le litige entre nouvelle direction du PDG et pro-Bongo se poursuit devant le siège du parti',
        'Des querelles opposent différentes factions au sein du Parti démocratique gabonais, ancien parti au pouvoir, autour de la tenue d’une réunion au siège du parti, ce qui reflète des tensions après le renversement de l''ancien président Ali Bongo en 2023.',
        'https://www.rfi.fr/fr/afrique/20250722-gabon-le-litige-entre-nouvelle-direction-du-pdg-et-pro-bongo-se-poursuit-devant-le-si%C3%A8ge-du-parti?utm_slink=rfi.my%2FBrXR&utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '43d49709-a2cd-4a3a-b677-fe3bf1b205a7',
        'Gabon : bientôt une plainte pour corruption contre des responsables de l’ancien régime',
        'Une plainte pour corruption contre des responsables de l’ancien régime gabonais est en préparation, visant à lutter contre la corruption et à rendre justice.',
        'https://gabonmediatime.com/gabon-bientot-une-plainte-pour-corruption-contre-des-responsables-de-lancien-regime/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3126c4a0-e55f-4065-887f-92894f8d336b',
        'Mouila : 1 mois de cours de soutien offerts par Pr. Marcelle Ibinga aux élèves',
        'Pr Marcelle Ibinga a offert un mois de cours de soutien gratuits aux élèves de Mouila pour les aider à améliorer leurs performances scolaires.',
        'https://gabonmediatime.com/mouila-1-mois-de-cours-de-soutien-offerts-par-pr-marcelle-ibinga-aux-eleves/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab5809d8-f4b5-4580-9b87-730f61a9c05d',
        'PDG : la bataille de Louis n’a pas eu lieu',
        'L''information selon laquelle le président Louis Na aurait été victime d''une attaque ou d''une bataille n''est pas avérée, et aucun incident de ce type n''a eu lieu.',
        'https://gabonmediatime.com/pdg-la-bataille-de-louis-na-pas-eu-lieu/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d0d8841-59fc-4fc5-969a-26fdde1bdb4d',
        'Souveraineté économique et alimentaire : Louise Pierrette Mvono mobilise les partenaires au développement',
        'Louise Pierrette Mvono appelle à mobiliser les partenaires pour renforcer la souveraineté économique et alimentaire du Cameroun.',
        'https://kongossanews.info/souverainete-economique-et-alimentaire-louise-pierrette-mvono-mobilise-les-partenaires-au-developpement/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e79f7cb-a3c9-416a-8b42-cfca2876804c',
        'Le Président Oligui Nguema inaugure la cité rénovée des sapeurs-pompiers de Nomba à Owendo',
        'Le président Oligui Nguema a inauguré la nouvelle cité rénovée des sapeurs-pompiers de Nomba à Owendo, améliorant ainsi les infrastructures de secours dans la région.',
        'https://kongossanews.info/le-president-oligui-nguema-inaugure-la-cite-renovee-des-sapeurs-pompiers-de-nomba-a-owendo/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e9732034-0ec3-4763-8c24-4fa06e9fc658',
        'Minerais critique : l’Europe supplantée',
        'L''Europe souhaite réduire sa dépendance aux importations de minerais en développant ses propres ressources, mais certains pays critiques, comme la Chine, soulignent que cela pourrait affecter la stabilité du marché mondial.',
        'https://kongossanews.info/minerais-critique-leurope-supplantee/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a26791ca-74bf-4844-8e1d-3b44b5393db4',
        'Gabon: environ 2000 parcelles viabilisées par l’ANUTTC d’ici fin 2025',
        'L’ANUTTC a lancé un projet pour viabiliser environ 2 000 parcelles à Libreville d’ici fin 2025, visant à améliorer la délivrance des titres fonciers et à répondre aux besoins des populations en matière d’aménagement et de sécurité foncière.',
        'https://vxp241.com/2025/07/22/gabon-environ-2000-parcelles-viabilisees-par-lanuttc-dici-fin-2025/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4e909d4b-8bf4-4fac-bbf0-9307bf3264f9',
        'UGB : Toujours pas d’agence ni de GAB à Angondge !',
        'La banque AttijariwafaBank, l’une des principales du Gabon, ne possède toujours pas d''agence ni de distributeurs automatiques dans le quartier huppé d’Angondgé, ce qui soulève des questions sur sa prise en compte de cette clientèle privilégiée.',
        'https://directinfosgabon.com/ugb-toujours-pas-dagence-ni-de-gab-a-angondge/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2f2527aa-4329-403e-b5ee-fd72a63b21ac',
        'Oyima : « Toutes les recettes doivent être reversées systématiquement et obligatoirement au Trésor »',
        'Lors des conférences budgétaires 2026, le ministre a rappelé que toutes les recettes générées sur le territoire doivent être obligatoirement reversées au Trésor, afin de centraliser les finances publiques.',
        'https://directinfosgabon.com/oyima-toutes-les-recettes-doivent-etre-reversees-systematiquement-et-obligatoirement-au-tresor/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4fdf92e6-82d6-4911-8671-ff217fc2ba40',
        'Village culturel et environnemental de la communauté Orungu trône désormais à Port-Gentil',
        'Le week-end dernier, un village culturel et environnemental dédié à la communauté Orungu a été inauguré à Port-Gentil, permettant de préserver et valoriser leur patrimoine culturel et naturel.',
        'https://gabonactu.com/blog/2025/07/22/village-culturel-et-environnemental-de-la-communaute-orungu-trone-desormais-a-port-gentil/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '021ae934-54b1-48dc-a8be-d05b7d6451df',
        'Football/Mercato : Aubameyang attendu à Marseille ce mardi',
        'Pierre-Emerick Aubameyang doit arriver à Marseille pour passer sa visite médicale et signer un contrat de deux ans avec l''équipe, après avoir quitté son ancien club.',
        'https://agpgabon.ga/football-mercato-aubameyang-attendu-a-marseille-ce-mardi/',
        'AGP',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '632e969d-1d56-4461-b669-88723ea45f2b',
        'SEEG : 71 % des ménages déclarent ne pas avoir un accès régulier à l’eau potable',
        'Selon une étude nationale, 71 % des ménages gabonais n''ont pas un accès régulier à l''eau potable, principalement en raison de l''absence de réseau de distribution, d''installations dans les logements ou de la proximité des points d''eau.',
        'https://directinfosgabon.com/seeg-71-des-menages-declarent-ne-pas-avoir-un-acces-regulier-a-leau-potable/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '332b1b7d-7dbb-4725-8850-eee16ce5842e',
        'Pétrole : Le groupe Maurel & Prom génère…72 % de son chiffres d’affaires au Gabon',
        'Le groupe Maurel & Prom a produit en moyenne 37 637 barils équivalent pétrole par jour au premier semestre 2025, dont 41 % proviennent du Gabon, qui représente 72 % de son chiffre d''affaires dans cette région.',
        'https://directinfosgabon.com/petrole-le-groupe-maurel-prom-genere-72-de-son-chiffres-daffaires-au-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0883e671-9d1d-4a31-9af2-2d85df8f289c',
        '« Guinness Slam Tour » : Le concours d’art oratoire de Sobraga est lancé',
        'Sobraga, représentée par la marque Guinness, a lancé un concours d’art oratoire appelé le Guinness Slam Tour, destiné à encourager l’expression orale et la créativité des jeunes au Gabon.',
        'https://gabonactu.com/blog/2025/07/22/guinness-slam-tour-le-concours-dart-oratoire-de-sobraga-est-lance/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c6350af-5c41-4191-921e-8e2ff360f71e',
        'Le Gabon à l’Expo 2025 Osaka Kansai au Japon du 23 au 30 juillet prochain',
        'Le Gabon participera à l''Exposition universelle Osaka-Kansai au Japon du 23 au 30 juillet 2025 pour mettre en valeur ses ressources naturelles, comme la forêt, et ses innovations économiques.',
        'https://gabonactu.com/blog/2025/07/22/le-gabon-a-lexpo-2025-osaka-kansai-au-japon-du-23-au-30-juillet-prochain/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'faa65598-7ca8-481d-bb6a-62153ab3bac1',
        'Partenariat stratégique : l’OEACP mise sur le Gabon pour renforcer ses actions en Afrique centrale',
        'Le secrétaire général de l’OEACP s’est rendu au Gabon pour renforcer la coopération avec le pays, notamment en préparation d’un sommet destiné à renforcer l’action de l’organisation en Afrique centrale.',
        'https://www.gabonreview.com/partenariat-strategique-loeacp-mise-sur-le-gabon-pour-renforcer-ses-actions-en-afrique-centrale/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '687a52da-e96e-4a70-97b8-d769a74223de',
        'Cérémonie d''ouverture des conférences budgétaires',
        'Le gouvernement gabonais a lancé ses conférences budgétaires pour élaborer la loi de finances 2026, en insistant sur la transparence, la responsabilité et l''efficacité dans la gestion des recettes de l''État.',
        'https://www.gabonews.com/fr/actus/economie/article/ceremonie-d-ouverture-des-conferences-budgetaires',
        'Gabonews',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd131f1de-92ca-4b82-b8a9-5f2e9a8fdf43',
        'Le Chef de l''État reçoit le Secrétaire Général de l''OAECP',
        'Le président Brice Clotaire Oligui Nguema a rencontré le Secrétaire général de l’OEACP, Moussa Saleh Batraki, qui a présenté ses priorités pour ses cinq années de mandat afin de renforcer la coopération entre 79 États membres.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-chef-de-l-etat-recoit-le-secretaire-general-de',
        'Gabonews',
        'Business Intelligence',
        '2025-07-22T00:00:00.000Z',
        '2025-09-15T23:06:12.477Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

