-- Batch 2 - Section 4/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '41f9f7b0-3d22-40a1-b2f3-9d1082e6cb72',
        'Libre propos de l’Ambassadeur de Chine au Gabon : « L’ouverture et la coopération sont la tendance de l’histoire et l’abus des droits de douane est impopulaire », (Zhou Ping)',
        'L’ambassadeur de Chine au Gabon souligne l’importance de l’ouverture et de la coopération internationale comme tendance historique, tout en critiquant l’utilisation excessive des droits de douane comme mesure impopulaire. Il met en avant les bénéfices mutuels d’une collaboration respectueuse entre les nations.',
        'https://agpgabon.ga/2025/04/09/libre-propos-ambassadeur-de-chine-louverture-et-la-cooperation-sont-la-tendance-de-lhistoire-et-labus-des-droits-de-douane-est-impopulaire-zhou-ping/',
        'AGP',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4250e27c-ec3e-4898-ade9-d115e832cd0f',
        'Présidentielle 2025 : Gabon Mindset se mobilise pour voter le candidat Oligui Nguema',
        'Le mouvement citoyen Mindset Gabon mobilise ses membres pour soutenir la candidature du général Oligui Nguéma à l’élection présidentielle de 2025, en mettant l’accent sur la participation démocratique et l’engagement des jeunes.',
        'https://gabonactu.com/blog/2025/04/09/presidentielle-2025-gabon-mindset-se-mobilise-pour-voter-le-candidat-oligui-nguema/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6be226af-c48a-436f-9458-dda7474edcc3',
        'Le PRD au chevet de indigents de Ndendé pour soutenir le candidat Oligui Nguema',
        'Le Parti du Rassemblement pour le Développement (PRD) a distribué des aides aux personnes démunies de Ndendé dans le but de soutenir la candidature d''Oligui Nguema aux prochaines élections. Cette action sociale vise à renforcer les liens avec la population locale en période électorale.',
        'https://gabonactu.com/blog/2025/04/09/le-prd-au-chevet-de-indigents-de-ndende-pour-soutenir-le-candidat-oligui-nguema/',
        'Gabon Actu',
        'Services, Business Femme',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ed5f76d9-c477-4319-8661-13dbfe5c2110',
        'le bilan provisoire de dégâts causés par les pluies diluviennes à Kinshasa',
        'Les intempéries ont causé d''importants dégâts matériels et des pertes humaines dans plusieurs régions, avec des inondations et des glissements de terrain signalés comme principales conséquences. Les autorités continuent d''évaluer la situation et de coordonner les secours pour les populations affectées.',
        'https://www.gabonews.com/fr/actus/international/article/le-bilan-provisoire-de-degats-causes-par-les',
        'Gabonews',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cb0baee1-cfb6-4dbb-bd94-235d0df9109c',
        'Le Ghana invité d''honneur au salon de l''entrepreneuriat Africain et de la diaspora à Nantes',
        'Le Ghana est l''invité d''honneur du Salon du livre de Paris 2024, mettant en avant sa littérature et sa culture à travers des rencontres et des débats. Cette participation vise à promouvoir les échanges culturels et la diversité littéraire africaine.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/le-ghana-invite-d-honneur-au-salon-de-l',
        'Gabonews',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb7e0791-f482-4d02-8cbe-6419c0530412',
        'Présidentielle 2025 : face à la presse, Oligui Nguema déroule un projet de société structuré et affirme sa vision souverainiste',
        'Le général Oligui Nguema présente un projet de société structuré et une vision souverainiste pour la présidentielle 2025, mettant en avant des priorités comme l''éducation et la technologie lors de son échange avec la presse.',
        'https://gabonmediatime.com/presidentielle-2025-face-a-la-presse-oligui-nguema-deroule-un-projet-de-societe-structure-et-affirme-sa-vision-souverainiste/',
        'Gabon Media Time',
        'Numérique / Digital, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7f82edc-7766-48f2-8525-b9062a6b58ea',
        'Présidentielle 2025 : le tournant libéral promis par Bilie-By-Nze',
        'Bilie By Nze promet une orientation libérale pour les élections présidentielles de 2025 au Gabon, mettant l''accent sur des réformes économiques et politiques pour moderniser le pays.',
        'https://gabonmediatime.com/presidentielle-2025-le-tournant-liberal-promis-par-bilie-by-nze/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '90052d9e-d041-45cf-82e5-cef81d4700d2',
        'Présidentielle 2025 : en violation du principe de neutralité, le ministère de l’Agriculture prend fait et cause pour un candidat...',
        'Le ministère de l''Agriculture du Gabon est accusé de violer le principe de neutralité en soutenant ouvertement un candidat à l''élection présidentielle de 2025, ce qui soulève des inquiétudes quant au respect des règles électorales.',
        'https://gabonmediatime.com/presidentielle-2025-en-violation-du-principe-de-neutralite-le-ministere-de-lagriculture-prend-fait-et-cause-pour-un-candidat/',
        'Gabon Media Time',
        'Autres',
        '2025-04-09T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4eb42d00-48ba-4998-ae99-bce786445398',
        'Présidentielle au Gabon: la question de la dette, un enjeu majeur de la campagne électorale',
        'La dette publique du Gabon, estimée à près de 80 % du PIB, est un sujet central de la campagne présidentielle, avec des candidats proposant des solutions divergentes pour la réduire tout en maintenant les investissements sociaux. Certains prônent une renégociation avec les créanciers, tandis que d’autres misent sur une meilleure gestion des ressources naturelles.',
        'https://www.rfi.fr/fr/podcasts/afrique-%C3%A9conomie/20250409-pr%C3%A9sidentielle-au-gabon-la-question-de-la-dette-un-enjeu-majeur-de-la-campagne-%C3%A9lectorale',
        'RFI',
        'Finances, Services, Numérique / Digital',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a68b3f6-abe6-4226-9b38-de66b04c5734',
        'Afrique économie - Présidentielle au Gabon: la question de la dette, un enjeu majeur de la campagne électorale',
        'La dette publique du Gabon, estimée à près de 80 % du PIB, est un sujet central de la campagne présidentielle, avec des candidats proposant des solutions divergentes pour la réduire tout en évitant les mesures d''austérité impopulaires.',
        'https://www.rfi.fr/fr/podcasts/afrique-%C3%A9conomie/20250409-pr%C3%A9sidentielle-au-gabon-la-question-de-la-dette-un-enjeu-majeur-de-la-campagne-%C3%A9lectorale?utm_source=flipboard&utm_content=topic/fr-%C3%A9conomie',
        'Flipboard',
        'Finances, Services',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '79ea7ebd-8a0f-42a7-95c2-df129ce1a9a0',
        'Présidentielle 2025 : L’Eglise du Gabon donne de la voix',
        'L’Église du Gabon appelle à des élections présidentielles de 2025 transparentes et pacifiques, tout en encourageant les citoyens à participer de manière responsable et dans le respect des valeurs démocratiques. Elle souligne l’importance du dialogue et de l’unité nationale durant cette période électorale.',
        'https://gabonactu.com/blog/2025/04/09/presidentielle-2025-leglise-du-gabon-donne-de-la-voix/',
        'Gabon Actu',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85f30eed-ef26-4954-bebd-0f7b62e0930a',
        'Présidentielle 2025 : face à la presse, Oligui Nguema déroule un projet de société structuré et affirme sa vision souverainiste',
        'Le général Oligui Nguema présente un projet de société structuré et une vision souverainiste pour la présidentielle de 2025, mettant l''accent sur la stabilité et l''indépendance du Gabon face à la presse.',
        'https://gabonmediatime.com/presidentielle-2025-face-a-la-presse-oligui-nguema-deroule-un-projet-de-societe-structure-et-affirme-sa-vision-souverainiste/',
        'Gabon Media Time',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f3cb420-6478-43fd-86c1-74b1bf8487ec',
        'Présidentielle 2025 : le tournant libéral promis par Bilie-By-Nze',
        'Bilie By Nze promet un tournant libéral pour les élections présidentielles de 2025 au Gabon, avec des réformes économiques et politiques visant à moderniser le pays. Son approche mise sur la transparence et l''ouverture pour attirer les investissements et améliorer la gouvernance.',
        'https://gabonmediatime.com/presidentielle-2025-le-tournant-liberal-promis-par-bilie-by-nze/',
        'Gabon Media Time',
        'Numérique / Digital, Finances, Services',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a47da036-bd39-4b3e-9570-6ab7f5caee2d',
        'Présidentielle 2025 : en violation du principe de neutralité, le ministère de l’Agriculture prend fait et cause pour un candidat...',
        'Le ministère gabonais de l''Agriculture est accusé de violer la neutralité administrative en soutenant ouvertement un candidat à la présidentielle de 2025, ce qui soulève des inquiétudes quant au respect des principes démocratiques. Cette prise de position pourrait influencer indûment le processus électoral.',
        'https://gabonmediatime.com/presidentielle-2025-en-violation-du-principe-de-neutralite-le-ministere-de-lagriculture-prend-fait-et-cause-pour-un-candidat/',
        'Gabon Media Time',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd3580c33-9957-48e7-bbb0-3b3863f67819',
        'Publié le 09 / 04 / 2025',
        'Les Woleu-Ntem affichent un soutien massif au président Oligui Nguéma lors de la présidentielle, manifestant une unité forte derrière son leadership.',
        'https://union.sonapresse.com/fr/presidentielle-les-woleuntemois-en-bloc-soude-derriere-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36666e10-f103-4b77-bbfc-a42acae4dd85',
        'Publié le 09 / 04 / 2025',
        'Le président de l’Union des journalistes africains, Bilie By Nze, en convalescence à Mouila après une hospitalisation, reprend progressivement des forces et poursuit son rétablissement.',
        'https://union.sonapresse.com/fr/presidentiellengounie-bilie-nze-reprend-des-forces-mouila',
        'L''union',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e8df16d5-20da-4fa5-bab2-853fae831473',
        'Publié le 09 / 04 / 2025',
        'Un grand enthousiasme a marqué les retraits des cartes d’électeurs à Nyanga Tchibanga, avec une forte mobilisation des citoyens pour participer au processus démocratique. Les autorités locales ont salué cet engagement, soulignant l’importance de la participation électorale.',
        'https://union.sonapresse.com/fr/nyangatchibanga-engouement-lors-des-retraits-des-cartes-delecteurs',
        'L''union',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31f39ae1-de57-4a8a-984c-28903f893b04',
        'Bamako-Alger : relations distendues après l''accident d''un drone abattu',
        'Un drone algérien a été abattu près de la frontière malienne, entraînant des tensions diplomatiques entre le Mali et l’Algérie, qui s’accusent mutuellement de violation de l’espace aérien. L’incident révèle des relations déjà tendues entre les deux pays, notamment sur des questions sécuritaires et politiques.',
        'https://www.france24.com/fr/%C3%A9missions/journal-de-l-afrique/20250409-bamako-alger-relations-distendues-apr%C3%A8s-l-accident-d-un-drone-abattu',
        'France 24',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4d5470b-c5e3-4c3d-a82e-12ab4ffcfd36',
        'Transition et présidentielle : Les femmes du RAFEGAC crient à la marginalisation',
        'Les femmes du RAFEGAC dénoncent leur marginalisation dans le processus de transition politique et la préparation de la présidentielle au Gabon, appelant à une meilleure inclusion dans les décisions nationales.',
        'https://gabonactu.com/blog/2025/04/10/transition-et-presidentielle-les-femmes-du-rafegac-crient-a-la-marginalisation/',
        'Gabon Actu',
        'Business Femme, Services, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '26b0cab6-788d-4f8b-b417-b19003c9756f',
        'Publié le 09 / 04 / 2025',
        'Les Woleu-Ntem affichent un soutien massif au président Oligui Nguéma lors de la présidentielle, manifestant ainsi leur unité derrière son leadership. Cette région montre une adhésion forte à sa candidature, reflétant une mobilisation collective.',
        'https://union.sonapresse.com/fr/presidentielle-les-woleuntemois-en-bloc-soude-derriere-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '410305f3-9ebc-41f8-b411-006bb4181a2a',
        'Publié le 09 / 04 / 2025',
        'Bilie By Nze, président du Sénat gabonais, reprend progressivement des forces après son hospitalisation à Mouila, où il bénéficie d’un suivi médical attentif. Son état de santé s’améliore, rassurant ses proches et les observateurs politiques.',
        'https://union.sonapresse.com/fr/presidentiellengounie-bilie-nze-reprend-des-forces-mouila',
        'L''union',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3354b3a0-1008-48b4-8837-090a882bf6c7',
        'Publié le 09 / 04 / 2025',
        'Un grand enthousiasme a marqué les retraits des cartes d’électeurs à Nyanga Tchibanga, avec une forte mobilisation des citoyens pour participer au processus démocratique. Les autorités locales ont salué cette participation massive, signe d’un engagement civique prometteur.',
        'https://union.sonapresse.com/fr/nyangatchibanga-engouement-lors-des-retraits-des-cartes-delecteurs',
        'L''union',
        'Numérique / Digital, Services, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa0a7188-673b-4c95-a277-c78ecbe77dfa',
        'Gabon: vers une présidentielle sans surprises?',
        'Le Gabon se prépare pour une élection présidentielle anticipée en août 2025, mais l''opposition dénonce un processus électoral verrouillé en faveur du pouvoir en place, limitant les chances d''un scrutin équitable.',
        'https://www.rfi.fr/fr/afrique/20250410-gabon-vers-une-pr%C3%A9sidentielle-sans-surprises',
        'RFI',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85952b68-a332-4a0d-bc83-b06bad01dce2',
        'Gabon: vers une présidentielle sans surprises?',
        'Le Gabon se prépare pour une élection présidentielle anticipée en août 2024, où le candidat du pouvoir, Brice Clotaire Oligui Nguema, est largement favorisé face à une opposition fragmentée et un contexte politique marqué par des réformes contestées.',
        'https://www.rfi.fr/fr/afrique/20250410-gabon-vers-une-pr%C3%A9sidentielle-sans-surprises?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a897b702-165c-4e0d-b0b3-8f06aeb3a761',
        'Travaux de mise en conformité de la conduite DN 200 E sur le réseau de distribution d’eau potable de Libreville',
        'Des travaux de mise en conformité sont en cours sur la conduite DN 200 du réseau de distribution d''eau potable à Libreville pour améliorer le service et éviter les perturbations. Ces interventions visent à garantir un approvisionnement en eau plus fiable pour les habitants.',
        'https://gabonactu.com/blog/2025/04/10/travaux-de-mise-en-conformite-de-la-conduite-dn-200-e-sur-le-reseau-de-distribution-deau-potable-de-libreville/',
        'Gabon Actu',
        'Services, Agriculture',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2722e05d-44c8-42e2-a546-46026f26c62a',
        '[Vos réactions] Gabon : que retenir de la transition ?',
        'La transition politique au Gabon suscite des réactions mitigées, entre espoirs de renouveau et scepticisme face aux promesses des nouvelles autorités, notamment concernant la démocratie et la lutte contre la corruption. Les citoyens expriment leur attente de changements concrets après des années de pouvoir autoritaire.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250410-vos-r%C3%A9actions-gabon-que-retenir-de-la-transition',
        'RFI',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fd27108-3663-47a4-a584-0192442de218',
        'Mobilisation pour Oligui Nguema : La Coordination provinciale de l’Estuaire en force à Ntoum et Kango',
        'La coordination provinciale de l’Estuaire s’est mobilisée à Ntoum et Kango pour soutenir le général Oligui Nguema, marquant une forte implication locale en sa faveur.',
        'https://www.gabonreview.com/mobilisation-pour-oligui-nguema-la-coordination-provinciale-de-lestuaire-en-force-a-ntoum-et-kango/',
        'Gabon Review',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c3027f0-a6d6-4509-a330-b5f4761c1ab5',
        '"La campagne électorale est bien effective dans l''ensemble du pays"',
        'La campagne électorale au Gabon est en cours, avec des candidats et militants actifs sur le terrain malgré des défis logistiques et des tensions politiques. Les partis multiplient les rassemblements pour mobiliser les électeurs en vue des prochaines élections.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/la-campagne-electorale-est-bien-effective-dans-l',
        'Gabonews',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c7493a6-5994-4e25-9016-50805f6c9d0d',
        'Présidentielle 2025 : Chantal Mandzaka mobilise la Lombo-Bouenguidi pour C''BON',
        'Chantal Mandzaka se mobilise en vue de l''élection présidentielle de 2025 au Gabon, en rencontrant des acteurs politiques et sociaux pour préparer sa campagne. Son engagement vise à rassembler des soutiens autour de son projet politique.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-chantal-mandzaka-mobilise-la',
        'Gabonews',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cc29d608-cb12-4b16-a603-e0a03ee1218c',
        'Présidentielle au Gabon: Oligui Nguema clôture sa campagne dans le nord, les observateurs internationaux se préparent à Libreville',
        'Le général Oligui Nguema a conclu sa campagne électorale dans le nord du Gabon avant la présidentielle, tandis que les observateurs internationaux arrivent à Libreville pour surveiller le scrutin.',
        'https://www.rfi.fr/fr/afrique/20250410-pr%C3%A9sidentielle-au-gabon-oligui-nguema-cl%C3%B4ture-sa-campagne-dans-le-nord-les-observateurs-internationaux-se-pr%C3%A9parent-%C3%A0-libreville',
        'RFI',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bd3780e7-cf83-4ef9-a435-772730477fb4',
        'Revenus Pétroliers et pollution : Le Gabon pris en otage ?',
        'Le Gabon dépend fortement des revenus pétroliers, mais cette exploitation entraîne une pollution environnementale importante, créant un dilemme entre développement économique et protection écologique. Les populations locales subissent les conséquences de cette situation sans en tirer suffisamment de bénéfices.',
        'https://directinfosgabon.com/revenus-petroliers-et-pollution-le-gabon-pris-en-otage/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8c1141e0-1962-4d30-9e95-9115a93a7268',
        'Diversification de l’économie gabonaise : La BAD appelle à un changement de cap stratégique',
        'La Banque africaine de développement (BAD) encourage le Gabon à diversifier son économie au-delà du pétrole en misant sur l’agriculture, les mines et les énergies renouvelables pour une croissance durable et inclusive. Elle souligne l’importance d’investir dans les infrastructures et la formation pour soutenir cette transition stratégique.',
        'https://directinfosgabon.com/diversification-de-leconomie-gabonaise-la-bad-appelle-a-un-changement-de-cap-strategique/',
        'Direct Infos Gabon',
        'Numérique / Digital, Agriculture, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25a1982f-dc18-4265-a3c5-0f4fa3634faa',
        'Paiement des rappels de solde : De gros couacs sur le terrain',
        'Des retards et des dysfonctionnements persistent dans le paiement des rappels de solde des fonctionnaires au Gabon, causant des frustrations malgré les promesses gouvernementales.',
        'https://directinfosgabon.com/paiement-des-rappels-de-solde-de-gros-couacs-sur-le-terrain/',
        'Direct Infos Gabon',
        'Finances, Services, Numérique / Digital',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d738d1f-d8dc-49db-a97c-43ee617a70aa',
        'Présidentielle 2025 : La CAGL persiste et signe pour Oligui Nguéma et le RDB',
        'La CAGL continue de soutenir la candidature d''Oligui Nguéma et du RDB pour la présidentielle de 2025, malgré les critiques et les défis politiques. Ce mouvement réaffirme son engagement en faveur de ce choix, considéré comme stratégique pour l''avenir du pays.',
        'https://gabonactu.com/blog/2025/04/10/presidentielle-2025-la-cagl-persiste-et-signe-pour-oligui-nguema-et-le-rdb/',
        'Gabon Actu',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b80325fd-7239-497b-92ec-880c9b261b3a',
        'Eboulement dramatique du PK6 : Oligui Nguema offre une villa à la famille endeuillée',
        'Un éboulement au PK6 a causé un drame, et le président Oligui Nguéma a offert une villa à la famille endeuillée en guise de soutien.',
        'https://gabonactu.com/blog/2025/04/10/eboulement-dramatique-du-pk6-oligui-nguema-offre-une-villa-a-la-famille-endeuillee/',
        'Gabon Actu',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc2bb4d0-f7b9-4b15-8944-e3708bcaae7a',
        '«Nous protégeons la vie, mais qui protège la nôtre ?» — Le cri d’alerte des oubliés de l’environnement au Gabon',
        'Des travailleurs gabonais de l''environnement dénoncent leurs conditions précaires et le manque de protection face aux dangers de leur métier, malgré leur rôle crucial dans la préservation des écosystèmes. Ils appellent à une meilleure reconnaissance et à des mesures concrètes pour leur sécurité.',
        'https://www.gabonreview.com/nous-protegeons-la-vie-mais-qui-protege-la-notre-le-cri-dalerte-des-oublies-de-lenvironnement-au-gabon/',
        'Gabon Review',
        'Services, Business Femme, Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4092354-30bd-47e8-9852-ebee7bdb9b2d',
        'Présidentielle 2025 : L’OIF au Gabon pour «évaluer le déroulement des opérations électorales»',
        'L’OIF envoie une mission au Gabon pour évaluer le déroulement des opérations électorales en vue de la présidentielle de 2025, afin d’assurer un processus transparent et démocratique. Cette initiative vise à renforcer la crédibilité du scrutin.',
        'https://www.gabonreview.com/presidentielle-2025-loif-au-gabon-pour-evaluer-le-deroulement-des-operations-electorales/',
        'Gabon Review',
        'Services, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62f5080a-073d-4d1d-9f9a-0cb4e0569b5a',
        'Pourquoi le leader du coup d''État au Gabon va à contre-courant de la tendance en adoptant la démocratie',
        'Des entrepreneurs africains développent des solutions technologiques locales pour répondre aux défis du continent, comme l''accès à l''énergie ou l''éducation, en s''appuyant sur l''innovation et les partenariats. Ces initiatives montrent comment la technologie peut améliorer les conditions de vie tout en créant des opportunités économiques.',
        'https://www.bbc.com/afrique/articles/c8dgg36mpezo?xtor=AL-73-%5Bpartner%5D-%5Bflipboard%5D-%5Bheadline%5D-%5Bafrique%5D-%5Bbizdev%5D-%5Bisapi%5D',
        'Flipboard',
        'Numérique / Digital, Éducation, Services',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93e3b6b1-8497-40cc-a62b-61be88f781ac',
        '« Les 11 accords qui ont été signés il y a plus de 50 ans entre le Gabon et la France sont aujourd’hui caducs » (Dr Thierry Yvon Ngoma)',
        'Les 11 accords signés il y a plus de 50 ans entre le Gabon et la France sont aujourd’hui considérés comme caducs, selon le Dr Thierry Yvon Ngoma, marquant la fin de leur validité juridique. Ces traités, autrefois structurants, n’ont plus d’effet dans les relations actuelles entre les deux pays.',
        'https://gabonactu.com/blog/2025/04/10/les-11-accords-qui-ont-ete-signes-il-y-a-plus-de-50-ans-entre-le-gabon-et-la-france-sont-aujourdhui-caducs-dr-thierry-yvon-ngoma/',
        'Gabon Actu',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bce50bc9-3505-4d30-9b17-f22a7c51d71a',
        'Présidentielle 2025: Les bâtisseurs agissent en 48h pour rétablir l’accès à l’eau potable après des mois de pénurie',
        'Des bénévoles gabonais ont rétabli l''accès à l''eau potable en 48 heures dans un quartier après sept mois de pénurie, grâce à des réparations rapides et une mobilisation communautaire. Leur action démontre l''efficacité des initiatives locales face aux défis d''infrastructure.',
        'https://gabonactu.com/blog/2025/04/10/les-batisseurs-agissent-en-48h-pour-retablir-lacces-a-leau-potable-apres-7-mois-de-penurie/',
        'Gabon Actu',
        'Services, Agriculture, Numérique / Digital',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '987aa784-6d33-45e8-857e-d62595814bbd',
        'Présidentielle 2025 : Minlama Mintogo jette son dévolu sur Oligui Nguéma',
        'Minlama Mintogo, candidat à la présidentielle gabonaise de 2025, a annoncé son soutien à Oligui Nguema, marquant un rapprochement politique significatif avant les élections. Cette alliance pourrait influencer la dynamique électorale en faveur du candidat soutenu.',
        'https://gabonactu.com/blog/2025/04/10/presidentielle-2025-minlama-mintogo-jette-son-devolu-sur-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0bfcc512-ca2d-4933-9538-15a2e2c073c0',
        'Présidentielle 2025: le Woleu-Ntem accueille OLIGUI NGUEMA',
        'Oligui Nguema s’est rendu dans le Woleu-Ntem pour sa campagne présidentielle de 2025, rencontrant des partisans et présentant ses projets pour la région. Cette visite vise à renforcer son ancrage local avant les élections.',
        'https://vxp241.com/2025/04/10/presidentielle-2025-le-woleu-ntem-accueille-oligui-nguema/',
        'Vox Populi',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8952ca6c-60c0-47b7-be70-9e027f8009bd',
        'Gabon /tragedie PK6: OLIGUI NGUEMA offre une villa SNI aux sinistrés',
        'Le président gabonais Oligui Nguéma a offert une villa de la SNI aux sinistrés du tragique accident du PK6, visant à soutenir les victimes et leurs familles. Cette initiative s''inscrit dans une démarche de solidarité nationale après cette catastrophe.',
        'https://vxp241.com/2025/04/10/gabon-tragedie-pk6-oligui-nguema-offre-une-villa-sni-aux-sinistres/',
        'Vox Populi',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e10d7d29-fa2c-4af1-989a-f73e68c4284c',
        'Nature préservée et peu de visiteurs : en Afrique, le «dernier éden» vise un tourisme sélectif',
        'L''Afrique mise sur un tourisme sélectif pour préserver ses espaces naturels encore peu fréquentés, comme au Gabon, où l''accent est mis sur une offre haut de gamme et respectueuse de l''environnement. Cette approche vise à attirer des visiteurs responsables tout en protégeant la biodiversité unique du continent.',
        'https://www.lefigaro.fr/voyages/nature-preservee-et-peu-de-visiteurs-en-afrique-le-dernier-eden-vise-un-tourisme-selectif-20250410?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Tourisme, Numérique / Digital',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ffd0520b-6120-4a64-9653-04f18e8664e6',
        'Oligui Nguema, Bilie By Nze... Au Gabon, huit candidats à l''élection présidentielle',
        'Huit candidats, dont le président de transition Oligui Nguema, se présentent à l''élection présidentielle anticipée au Gabon, prévue pour août 2024, après le coup d''État de 2023. La Cour constitutionnelle a validé ces candidatures, marquant une étape clé dans la transition politique du pays.',
        'https://www.france24.com/fr/afrique/20250410-oligui-nguema-bilie-by-nze-au-gabon-huit-candidats-%C3%A9lection-pr%C3%A9sidentielle',
        'France 24',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '425de145-1b68-45e5-8b4e-186503e3101f',
        'Gabon : après les Bongo, qui est Brice Oligui Nguema, l’homme d’une nouvelle dynastie',
        'Brice Oligui Nguema, chef de la transition au Gabon après le coup d''État contre Ali Bongo, incarne une possible nouvelle dynastie politique, bien que ses intentions réelles pour le pays restent incertaines.',
        'https://www.humanite.fr/monde/ali-bongo/gabon-apres-les-bongo-qui-est-brice-oligui-nguema-lhomme-dune-nouvelle-dynastie',
        'L''Humanité',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1f6effe-0983-48d9-812d-235026724afd',
        'Port-Gentil : engagée dans une caravane de proximité, AIDE décrypte le déroulé du vote aux populations',
        'Une caravane de proximité à Port-Gentil explique aux populations le déroulement du vote, afin de les informer et de les encourager à participer au processus électoral. Cette initiative vise à renforcer la transparence et la compréhension des étapes du scrutin.',
        'https://gabonactu.com/blog/2025/04/10/port-gentil-engagee-dans-une-caravane-de-proximite-aide-decrypte-le-deroule-du-vote-aux-populations/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3fb2864e-e23f-475c-868f-dd487bf57e7f',
        'SEEG : fermeture exceptionnelle des agences commerciales',
        'Les agences commerciales de la SEEG au Gabon ferment exceptionnellement pour une journée en raison d’un mouvement de grève, perturbant temporairement les services aux clients.',
        'https://gabonactu.com/blog/2025/04/10/seeg-fermeture-exceptionnelle-des-agences-commerciales/',
        'Gabon Actu',
        'Numérique / Digital, Services',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7211fb2-bc5f-4632-bb10-51c442840302',
        'Présidentielle au Gabon : une élection jouée d’avance ?',
        'La présidentielle au Gabon semble déjà jouée en faveur du président sortant Ali Bongo, malgré une opposition divisée et des critiques sur la transparence du processus électoral.',
        'https://www.jeuneafrique.com/1677801/politique/presidentielle-au-gabon-une-election-jouee-davance/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76f488b8-950e-4452-bd39-646046584754',
        'Les partis politiques membres du RDB se mobilise pour une campagne de proximité',
        'Les partis politiques membres du RDB organisent une campagne de proximité pour renforcer leur présence et échanger directement avec les citoyens. Cette initiative vise à mieux comprendre les préoccupations locales et à promouvoir leurs actions.',
        'https://gabonactu.com/blog/2025/04/10/les-partis-politiques-membres-du-rdb-se-mobilise-pour-une-campagne-de-proximite/',
        'Gabon Actu',
        'Services, Éducation, Tourisme',
        '2025-04-10T00:00:00.000Z',
        '2025-09-15T23:06:12.417Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

