-- Batch 2 - Section 16/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '4715e5d6-c6e9-4f11-8020-d8c907eae43b',
        'Gabon-Investiture du chef de l’Etat : Obiang Nguema Mbasogo attendu à Libreville',
        'Le chef de l’État gabonais, Obiang Nguema Mbasogo, doit être investi à Libreville lors d’une cérémonie officielle marquant son nouveau mandat. L’événement rassemble des dignitaires et symbolise la continuité politique du pays.',
        'https://agpgabon.ga/2025/04/24/gabon-investiture-du-chef-de-letat-obiang-nguema-mbasogo-attendu-a-libreville/',
        'AGP',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e74a3eac-2f09-481d-a2c5-5cb5a18425a5',
        'Gabon/Infrastructures routières : lancement des travaux de bitumage du tronçon Ovan-Makokou',
        'Le Gabon a lancé les travaux de bitumage du tronçon Ovan-Makokou, un projet routier visant à améliorer les infrastructures et la circulation dans la région. Cette initiative s''inscrit dans les efforts du gouvernement pour moderniser le réseau routier national.',
        'https://agpgabon.ga/2025/04/24/gabon-infrastructures-routieres-lancement-des-travaux-de-bitumage-du-troncon-ovan-makokou/',
        'AGP',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f70f78e-4724-48c1-872e-a680ce37fb9d',
        'Route Bizango-Rails : On circule à nouveau',
        'La route Bizango-Rails est à nouveau ouverte à la circulation après des travaux de réhabilitation, améliorant ainsi la mobilité et les échanges dans la région.',
        'https://gabonactu.com/blog/2025/04/24/route-bizango-rails-on-circule-a-nouveau/',
        'Gabon Actu',
        'Services, Commerce, Tourisme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6911590f-cea4-4c60-b36a-5dcb99ac0ba3',
        'ERAMET : Partenaire clé du développement économique et social du Gabon',
        'Eramet, entreprise minière, contribue au développement économique et social du Gabon à travers des investissements dans l''éducation, la santé et les infrastructures locales, tout en renforçant la formation professionnelle des jeunes. Ses actions visent à créer un impact durable en soutenant les communautés et en favorisant l''emploi.',
        'https://gabonactu.com/blog/2025/04/24/eramet-partenaire-cle-du-developpement-economique-et-social-du-gabon/',
        'Gabon Actu',
        'Éducation, Services, Agriculture',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4473465-8561-4a74-a3a1-063f9b6f85d2',
        'Gabon : après deux années en poste, l’ambassadeur de Suisse fait ses adieux à Ndong Sima',
        'L’ambassadeur de Suisse au Gabon a pris congé après deux ans de mission, marquant la fin de son mandat par une rencontre officielle avec le Premier ministre gabonais. Les échanges ont porté sur les relations bilatérales et les projets de coopération entre les deux pays.',
        'https://gabonmediatime.com/gabon-apres-deux-annees-en-poste-lambassadeur-de-suisse-fait-ses-adieux-a-ndong-sima/',
        'Gabon Media Time',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81e98e1c-60cb-4abc-a1ca-b268f0ee3ae1',
        'Mabanda : les chefs de quartiers dotés en congélateurs par le président Brice Clotaire Oligui Nguema',
        'Les chefs de quartier de Mabanda ont reçu des congélateurs offerts par le président Brice Clotaire Oligui Nguema, dans le cadre d’une initiative visant à améliorer leurs conditions de vie et leur capacité de conservation des aliments.',
        'https://kongossanews.info/mabanda-les-chefs-de-quartiers-dotes-en-congelateurs-par-le-president-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Services, Agriculture, Numérique / Digital',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '806b2f08-db1a-495b-86be-fa73cdef0a97',
        'Publié le 24 / 04 / 2025',
        'L''article explore les défis et opportunités pour les PDG légalistes en Afrique, soulignant l''importance de l''innovation et de l''adaptation aux régulations pour assurer un avenir durable. Il met en lumière comment ces dirigeants peuvent concilier conformité et croissance dans un environnement économique en mutation.',
        'https://union.sonapresse.com/fr/pdg-legaliste-quel-avenir',
        'L''union',
        'Numérique / Digital, Services, Éducation',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22ac427a-ebe2-49a8-b1db-11eb68107f82',
        'Publié le 24 / 04 / 2025',
        'L’ambassadeur de Suisse au Togo a rencontré le Premier ministre pour une visite d’adieu, marquant la fin de sa mission diplomatique dans le pays. Ils ont évoqué les relations bilatérales et les projets de coopération entre les deux nations.',
        'https://union.sonapresse.com/fr/lambassadeur-suisse-fait-ses-adieux-au-premier-ministre',
        'L''union',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3ba0eb76-cbfc-4355-96ec-4e6326fe0fd8',
        '8e édition de collage de vignettes: un partenariat solide entre Moov africa Gabon Telecom & Hôtel de ville de Libreville',
        'La 8e édition du collage de vignettes a renforcé le partenariat entre Moov Africa Gabon, Gabon Télécom et la mairie de Libreville, visant à simplifier les démarches administratives pour les usagers. Cette collaboration facilite l’accès aux services publics tout en promouvant l’innovation technologique locale.',
        'https://vxp241.com/2025/04/24/8e-edition-de-collage-de-vignettes-un-partenariat-solide-entre-moov-africa-gabon-telecom-hotel-de-ville-de-libreville/',
        'Vox Populi',
        'Numérique / Digital, Services',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a4778df-19a7-477c-9ff5-3a8b7c5728de',
        'Publié le 24 / 04 / 2025',
        'L''article explore les défis et opportunités pour les PDG légalistes en Afrique, soulignant l''importance d''adapter les stratégies d''entreprise aux contextes juridiques et économiques locaux tout en innovant pour un développement durable.',
        'https://union.sonapresse.com/fr/pdg-legaliste-quel-avenir',
        'L''union',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '007ac319-e935-4ddd-9050-9e5d0b1eae86',
        'Publié le 24 / 04 / 2025',
        'L''ambassadeur de Suisse au Togo a rencontré le Premier ministre pour une visite d''adieu, marquant la fin de sa mission diplomatique dans le pays. Ils ont évoqué les relations bilatérales et les projets de coopération entre les deux nations.',
        'https://union.sonapresse.com/fr/lambassadeur-suisse-fait-ses-adieux-au-premier-ministre',
        'L''union',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0d6ef64-8f7b-440d-89b3-f98934f9316d',
        'Sur les traces des premiers Gabonais de la préhistoire',
        'Des archéologues ont découvert des outils en pierre vieux de 400 000 ans au Gabon, révélant une présence humaine bien plus ancienne que ce que l''on pensait auparavant. Ces trouvailles éclairent l''histoire des premiers habitants de la région et leur adaptation à l''environnement forestier.',
        'https://www.rfi.fr/fr/podcasts/reportage-afrique/20250424-sur-les-traces-des-premiers-gabonais-de-la-pr%C3%A9histoire',
        'RFI',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '809b19a9-fe02-4290-8b02-be1ccd911492',
        'Ministère des transports : Odeur de grève',
        'Des agents du ministère des Transports au Gabon menacent de faire grève en raison du non-paiement de leurs primes et indemnités depuis plusieurs mois, ce qui pourrait perturber les services publics.',
        'https://gabonactu.com/blog/2025/04/24/ministere-des-transports-odeur-de-greve/',
        'Gabon Actu',
        'Services, Finances, Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6fa292c7-55e3-455a-ba06-03e674e3553d',
        'Gabon/Présidentielle 2025 : la Cour constitutionnelle proclame les résultats ce vendredi',
        'La Cour constitutionnelle du Gabon a proclamé les résultats de l''élection présidentielle 2025 ce vendredi, confirmant ainsi l''issue du scrutin. Les détails des votes et les réactions des acteurs politiques ont été rendus publics à cette occasion.',
        'https://agpgabon.ga/2025/04/24/gabon-presidentielle-2025-la-cour-constitutionnelle-proclame-les-resultats-ce-vendredi/',
        'AGP',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a21107cc-0832-4737-af8c-b3e5f72402d9',
        'La Cour constitutionnelle « autorise » Oligui Nguema à prêter serment',
        'La Cour constitutionnelle du Gabon a autorisé le général Oligui Nguema, chef de la transition, à prêter serment, confirmant ainsi sa légitimité à diriger le pays après le coup d''État de 2023. Cette décision ouvre la voie à une nouvelle étape dans le processus de transition politique.',
        'https://gabonactu.com/blog/2025/04/25/la-cour-constitutionnelle-autorise-oligui-nguema-a-preter-serment/',
        'Gabon Actu',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '099bf97d-e008-48d6-aeb1-7468b2fccb18',
        'Lancement officiel de la cartographie des projets de développement au Gabon',
        'Le Gabon a lancé officiellement une cartographie des projets pour recenser et suivre les initiatives de développement sur son territoire, visant à améliorer la transparence et la coordination des actions publiques et privées. Cet outil permettra aux citoyens et aux acteurs locaux d’avoir une vision claire des réalisations en cours.',
        'https://www.gabonews.com/fr/actus/societe/article/lancement-officiel-de-la-cartographie-des-projets',
        'Gabonews',
        'Numérique / Digital, Services, Éducation',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6da7103c-e565-4edd-9f0a-1bec3715abc9',
        'Leader Associatif : Flaubert Méyé, au cœur de tous les projets à Oyem',
        'Flaubert Meye, leader associatif gabonais, s''engage activement dans des actions sociales et éducatives pour soutenir les jeunes et les communautés défavorisées. Son travail se concentre sur l''autonomisation et l''inclusion à travers des projets concrets et des partenariats locaux.',
        'https://www.gabonews.com/fr/actus/societe/article/leader-associatif-flaubert-meye-au-coeur-de-tous',
        'Gabonews',
        'Éducation, Services, Business Femme',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a069ab23-ceb0-4bd7-8282-f58063af2de4',
        'Oyem/EEG/Paroisse Sougoudzapville : La Résurrection de Christ célébrée avec faste',
        'La paroisse de Sougoudzapville à Oyem a célébré la fête de Pâques avec une messe marquant la résurrection du Christ, rassemblant les fidèles pour un moment de prière et de partage. L''événement a renforcé la foi communautaire et souligné l''importance de cette fête religieuse.',
        'https://www.gabonews.com/fr/actus/religion/article/oyem-eeg-paroisse-sougoudzapville-la-resurrection',
        'Gabonews',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1ae542f3-323a-436a-920f-d564406c876b',
        'SEEG : Il faut 1000 milliards de FCFA pour tout régler !',
        'La SEEG estime qu''il faut 1 000 milliards de FCFA pour résoudre les problèmes d''eau et d''électricité au Gabon, notamment en modernisant les infrastructures et en réduisant les coupures fréquentes.',
        'https://directinfosgabon.com/seeg-il-faut-1000-milliards-de-fcfa-pour-tout-regler/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '192d3873-e714-488e-862b-e685a58c573f',
        'Pétrole au Gabon : « Comment défendre notre souveraineté sans renoncer à notre attractivité »',
        'Le Gabon cherche à protéger sa souveraineté pétrolière tout en restant attractif pour les investisseurs étrangers, en révisant sa politique fiscale et en renforçant la transparence pour équilibrer intérêts nationaux et partenariats internationaux.',
        'https://directinfosgabon.com/petrole-au-gabon-comment-defendre-notre-souverainete-sans-renoncer-a-notre-attractivite/',
        'Direct Infos Gabon',
        'Numérique / Digital, Finances',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86bd6a56-36ee-4af7-88f0-37ab54a72ba0',
        'La dette du Gabon évaluée à 7048 milliards de francs à fin décembre 2024',
        'La dette publique du Gabon est estimée à 7 048 milliards de FCFA fin décembre 2024, représentant environ 59,3 % du PIB, avec une augmentation significative par rapport aux années précédentes. Cette hausse s’explique principalement par les emprunts internes et externes pour financer les projets de développement et faire face aux crises économiques.',
        'https://directinfosgabon.com/la-dette-du-gabon-evaluee-a-7048-milliards-de-francs-a-fin-decembre-2024/',
        'Direct Infos Gabon',
        'Finances, Services',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd97552bb-de64-429c-a162-dfff76783f9c',
        'Dette : Le Gabon va emprunter 902 milliards de francs en 2025',
        'Le Gabon prévoit d''emprunter 902 milliards de francs CFA en 2025 pour financer ses projets de développement et faire face à ses obligations financières. Cette décision s''inscrit dans le cadre de la gestion de sa dette publique et des investissements prioritaires du pays.',
        'https://directinfosgabon.com/dette-le-gabon-va-emprunter-902-milliards-de-francs-en-2025/',
        'Direct Infos Gabon',
        'Finances, Services',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab313e45-6612-4f9b-92e3-ebfeb1c23fd8',
        'Gabon : l’inclusion de la Société civile dans le processus électoral consolide la transparence et la légitimité, selon Pepecy Ogouliguendé',
        'L''inclusion de la société civile gabonaise dans le processus électoral renforce la transparence et la légitimité des élections, selon Pepecy Ogouliguende. Cette participation favorise une meilleure confiance des citoyens dans le système démocratique.',
        'https://gabonactu.com/blog/2025/04/25/gabon-linclusion-de-la-societe-civile-dans-le-processus-electoral-consolide-la-transparence-et-la-legitimite-selon-pepecy-ogouliguende/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c631dcfa-ca9c-46f5-bbfb-c17a01a640e8',
        'Pêche : le Gabon et le Japon renforcent leur coopération',
        'Le Gabon et le Japon renforcent leur collaboration dans le secteur de la pêche, visant à améliorer les techniques et la durabilité des ressources halieutiques. Cet accord vise aussi à soutenir les communautés locales et à promouvoir une gestion responsable des océans.',
        'https://gabonactu.com/blog/2025/04/25/peche-le-gabon-et-le-japon-renforcent-leur-cooperation/',
        'Gabon Actu',
        'Services, Agriculture, Numérique / Digital',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4fe4c147-c39d-4bf1-bd15-5dd9fdd1e318',
        'Présidentielle du 12 avril : la Cour constitutionnelle valide les résultats sans contestation',
        'La Cour constitutionnelle du Gabon a validé les résultats de l''élection présidentielle du 12 avril, confirmant la victoire sans aucune contestation majeure. Le scrutin s''est déroulé dans un cadre légal et les recours ont été rejetés faute de preuves suffisantes.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-la-cour-constitutionnelle-valide-les-resultats-sans-contestation/',
        'Gabon Review',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c9b1f5ab-d5d4-4c06-8e7f-b4ed7b3081d2',
        'RENAJI : Ferdinand Demba désigné Président du Comité d''organisation de la Journée mondiale de la Liberté de la Presse',
        'Renaji Ferdinand Demba a été nommé président du conseil d’administration de l’Agence de Régulation des Communications Électroniques et des Postes (ARCEP) du Gabon, succédant ainsi à Alain-Claude Bilie-By-Nze.',
        'https://www.gabonews.com/fr/actus/communication/article/renaji-ferdinand-demba-designe-president-du',
        'Gabonews',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab4e3f5d-7740-4d93-b9c4-3fbd5b1f6878',
        'Obsèques du Pape François : Oligui Nguema attendu à Rome',
        'Le président gabonais Brice Clotaire Oligui Nguema doit se rendre à Rome pour assister aux obsèques du pape François, selon des sources officielles. Sa présence s’inscrit dans le cadre des hommages internationaux rendus au souverain pontife.',
        'https://agpgabon.ga/2025/04/25/obseques-du-pape-francois-oligui-nguema-attendu-a-rome/',
        'AGP',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '13954187-c0de-41dd-a4e8-c06c76e5ed3b',
        'Gabon/Présidentielle 2025 : la Cour constitutionnelle confirme la victoire de Brice Clotaire Oligui Nguema',
        'La Cour constitutionnelle du Gabon a confirmé la victoire de Brice Clotaire Oligui Nguema à l’élection présidentielle de 2025, validant ainsi les résultats officiels. Cette décision met fin aux incertitudes politiques et consolide le pouvoir du nouveau président.',
        'https://agpgabon.ga/2025/04/25/gabon-presidentielle-2025-la-cour-constitutionnelle-confirme-la-victoire-de-brice-clotaire-oligui-nguema/',
        'AGP',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d65ecb8-06b0-4df8-8ffc-0f71c2341fb1',
        'Gabon: Brice Clotaire Oligui Nguema a remporté la présidentielle avec 94,85% des voix, selon les résultats définitifs proclamés par la Cour constitutionnelle',
        'Brice Clotaire Oligui Nguema a remporté l''élection présidentielle au Gabon avec 94,85 % des voix, selon les résultats définitifs proclamés par la Cour constitutionnelle.',
        'https://www.rfi.fr/fr/en-bref/20250425-gabon-brice-clotaire-oligui-nguema-a-remport%C3%A9-la-pr%C3%A9sidentielle-avec-94-85-des-voix-selon-les-r%C3%A9sultats-d%C3%A9finitifs-proclam%C3%A9s-par-la-cour-constitutionnelle?utm_slink=rfi.my%2FBc6I&utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e071fc3e-65d0-46ed-b236-b8d500e0cf23',
        '94,85% des voix, la Cour constitutionnelle confirme la victoire d’OLIGUI NGUEMA',
        'La Cour constitutionnelle gabonaise a confirmé la victoire d''Oligui Nguema à l''élection présidentielle, rejetant les recours contestant les résultats et validant ainsi son mandat.',
        'https://vxp241.com/2025/04/25/9485-des-voix-la-cour-constitutionnelle-confirme-la-victoire-doligui-nguema/',
        'Vox Populi',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a6cd21a-ae60-4f22-9eaf-2d8cf6fce996',
        'Au Gabon, Brice Oligui Nguema élu président avec 94,85 % des suffrages',
        'Brice Oligui Nguema a été élu président du Gabon avec 94,85 % des voix lors d''un scrutin marqué par une forte participation, selon les résultats officiels. Cette élection fait suite à la transition politique après le coup d''État d''août 2023 qui a renversé Ali Bongo.',
        'https://www.lemonde.fr/afrique/article/2025/04/25/au-gabon-brice-oligui-nguema-elu-president-avec-94-85-des-suffrages_6600004_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5e79a592-7fc1-4b11-b6c8-0abd83b96514',
        'Gare d’Ivindo : Un accident tragique entraîne le décès d’une passagère',
        'Un accident tragique s’est produit à la gare de Divindo, causant le décès d’une passagère. Les circonstances de l’incident restent floues, mais les autorités ont ouvert une enquête pour élucider les faits.',
        'https://directinfosgabon.com/gare-divindo-un-accident-tragique-entraine-le-deces-dune-passagere/',
        'Direct Infos Gabon',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c125c936-52cd-4502-ba50-ba1b125b138c',
        'Gabon : Réinvestir dans la lutte contre le paludisme pour espérer l’éradiquer d’ici 2030',
        'Le Gabon renforce ses efforts contre le paludisme en augmentant les investissements et les campagnes de prévention pour espérer éradiquer la maladie d’ici 2030. Des actions ciblées incluent la distribution de moustiquaires et des sensibilisations communautaires.',
        'https://www.gabonreview.com/gabon-reinvestir-dans-la-lutte-contre-le-paludisme-pour-esperer-leradiquer-dici-2030/',
        'Gabon Review',
        'Santé, Services, Éducation',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f41b36de-f1a4-4bdc-beda-eba32dca2c22',
        'Présidentielle au Gabon : la victoire d’Oligui Nguema confirmée par la Cour constitutionnelle',
        'La Cour constitutionnelle du Gabon a confirmé la victoire d’Ali Bongo Ondimba à l’élection présidentielle, rejetant les recours de l’opposition qui dénonçait des irrégularités. Cette décision entérine un troisième mandat pour le président sortant, malgré les contestations.',
        'https://www.jeuneafrique.com/1683055/politique/presidentielle-au-gabon-la-victoire-doligui-nguema-confirmee-par-la-cour-constitutionnelle/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e9ee0d6-343e-4a28-8301-7ad38c7d4ea2',
        'Gabon : Sylvia et Noureddin Bongo en grève de la faim ?',
        'Sylvia et Noureddin Bongo, enfants de l’ancien président gabonais Omar Bongo, ont entamé une grève de la faim pour protester contre le gel de leurs comptes bancaires et la saisie de leurs biens par les autorités gabonaises. Ils dénoncent une mesure qu’ils jugent injuste et politiquement motivée.',
        'https://www.gabonreview.com/gabon-sylvia-et-noureddin-bongo-en-greve-de-la-faim/',
        'Gabon Review',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0531570-527d-43ca-905d-b7e41399aee2',
        '"Les condoléances de la Primature gabonaise au Vatican',
        'La Primature gabonaise présente ses condoléances suite au décès d’un proche collaborateur, exprimant sa tristesse et son soutien à la famille endeuillée.',
        'https://www.gabonews.com/fr/actus/necrologie/article/les-condoleances-de-la-primature-gabonaise-au',
        'Gabonews',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ddf2f14c-151f-4d3c-a32b-4499d8ae9d3e',
        'Congo-Brazzaville : Jeunesse et parlementaires au cœur de l''atelier de formation sous – régional sur le droit à l''alimentation et l''agriculture sensible à la nutrition',
        'Des jeunes et des parlementaires au Congo-Brazzaville ont échangé sur des questions liées à l''éducation, l''emploi et la participation citoyenne, dans le but de renforcer le dialogue intergénérationnel et les politiques publiques en faveur de la jeunesse.',
        'https://www.gabonews.com/fr/actus/societe/article/congo-brazzaville-jeunesse-et-parlementaires-au',
        'Gabonews',
        'Éducation, Agriculture, Services',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5ea6b75-d71a-478f-99ed-919cab7a676c',
        '"Message de Félicitations à Brice Clotaire Oligui Nguema" Justine Judith Lekogo Députée de la Transition',
        'Le président de la transition du Gabon, Brice Clotaire Oligui Nguema, a reçu des félicitations pour son leadership et ses efforts en faveur de la stabilité et du développement du pays.',
        'https://www.gabonews.com/fr/actus/politique/article/message-de-felicitations-a-brice-clotaire-oligui',
        'Gabonews',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e96f0620-f750-4c76-a409-51fd0097dc73',
        'Gabon : AFGBank, une banque engagée dans la lutte contre le paludisme',
        'AFGBank au Gabon soutient la lutte contre le paludisme en distribuant des moustiquaires imprégnées et en sensibilisant les populations, s''engageant ainsi dans des actions concrètes pour réduire cette maladie.',
        'https://gabonmediatime.com/gabon-afgbank-une-banque-engagee-dans-la-lutte-contre-le-paludisme/',
        'Gabon Media Time',
        'Services, Éducation, Finances',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10965bf8-a604-47a5-b11d-749dffc5bf61',
        'Gabon : la croissance économique estimée à 3,2% à la fin de 2024',
        'La croissance économique du Gabon est estimée à 3,2 % pour fin 2024, portée par la hausse des investissements publics et une reprise dans les secteurs pétrolier et minier. Cette progression reste toutefois modérée en raison des défis structurels et de la dépendance aux ressources naturelles.',
        'https://gabonmediatime.com/gabon-la-croissance-economique-estimee-a-32-a-la-fin-de-2024/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Commerce, Agriculture',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '336e611a-8003-4253-9f73-f9086e386586',
        'Présidentielle 2025 : La Cour constitutionnelle confirme le plébiscite d’Oligui Nguema',
        'La Cour constitutionnelle du Gabon a confirmé la large victoire d’Ali Bongo Ondimba (surnommé Oligui Nguema) à l’élection présidentielle de 2025, validant ainsi son plébiscite par les électeurs. Cette décision clôt le processus électoral et renforce sa légitimité à la tête du pays.',
        'https://gabonmediatime.com/presidentielle-2025-la-cour-constitutionnelle-confirme-le-plebiscite-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '43dbeba9-6d52-4e7a-b6d0-64e74290cf1b',
        'Insalubrité à Libreville : quand les habitants deviennent leurs propres bourreaux',
        'Les habitants de Libreville contribuent malgré eux à l''insalubrité de leur ville en jetant des déchets dans la nature, aggravant ainsi les problèmes sanitaires et environnementaux. Malgré les efforts des autorités, le manque de civisme persiste, rendant la situation difficile à améliorer.',
        'https://kongossanews.info/insalubrite-a-libreville-quand-les-habitants-deviennent-leurs-propres-bourreaux/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9945435b-a840-441b-998a-7ec4e9b514bf',
        'Bung Pinze : un acteur culturel au service du Gabon face à des critiques infondées',
        'Bung Pinze, acteur culturel gabonais engagé, fait face à des critiques jugées injustifiées malgré son travail pour promouvoir la culture locale et soutenir la jeunesse. Certains remettent en cause ses actions, mais ses initiatives restent reconnues pour leur impact positif.',
        'https://kongossanews.info/bung-pinze-un-acteur-culturel-au-service-du-gabon-face-a-des-critiques-infondees/',
        'Kongossa News',
        'Services, Education, Business Femme',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f8707369-4409-4a11-92ca-917203dc9197',
        'Publié le 25 / 04 / 2025',
        'La Cour constitutionnelle du Gabon a confirmé l''élection de Brice Clotaire Oligui Nguema à la présidence lors du scrutin de 2025, validant ainsi les résultats officiels. Cette décision met fin aux contestations et consolide sa légitimité à la tête du pays.',
        'https://union.sonapresse.com/fr/presidentielle-2025-la-cour-constitutionnelle-confirme-lelection-de-brice-clotaire-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22421bf6-fd1a-4de6-ba36-c82f9c947100',
        'Publié le 25 / 04 / 2025',
        'Oligui Nguéma a été investi président de la transition au Gabon lors d''une cérémonie officielle à Libreville, marquant une nouvelle étape après la prise de pouvoir en août 2023. Son frère, l''ancien président Ali Bongo Ondimba, était absent de l''événement.',
        'https://union.sonapresse.com/fr/investiture-doligui-nguema-obiang-nguema-mbasogo-attendu-libreville',
        'L''union',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e006e956-c02c-4c3d-9166-e4d4d9d1a8a6',
        'Insalubrité à Libreville : la montée de l’incivisme empire la situation',
        'L''insalubrité à Libreville s''aggrave en raison de l''incivisme croissant des habitants, qui jettent souvent leurs déchets dans les rues malgré les efforts des autorités pour nettoyer la ville. Cette situation pose des problèmes sanitaires et environnementaux majeurs pour la capitale gabonaise.',
        'https://gabonactu.com/blog/2025/04/25/insalubrite-a-libreville-la-montee-de-lincivisme-empire-la-situation/',
        'Gabon Actu',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e6c7533-50d8-4fda-9bce-ec4abfec4f58',
        'Gabon : AFGBank, une banque engagée dans la lutte contre le paludisme',
        'AFGBank au Gabon soutient la lutte contre le paludisme en finançant des campagnes de sensibilisation et en distribuant des moustiquaires imprégnées pour protéger les populations vulnérables. Cette initiative s''inscrit dans une démarche de responsabilité sociale visant à réduire l''impact de cette maladie.',
        'https://gabonmediatime.com/gabon-afgbank-une-banque-engagee-dans-la-lutte-contre-le-paludisme/',
        'Gabon Media Time',
        'Finances, Services, Santé',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5cbdd705-fca0-4de6-a2b7-11608fcb0a70',
        'Gabon : la croissance économique estimée à 3,2% à la fin de 2024',
        'La croissance économique du Gabon est estimée à 3,2 % pour fin 2024, tirée principalement par la hausse des prix du pétrole et une légère amélioration de la production. Cette progression reste toutefois modérée en raison des défis structurels et de la dépendance aux hydrocarbures.',
        'https://gabonmediatime.com/gabon-la-croissance-economique-estimee-a-32-a-la-fin-de-2024/',
        'Gabon Media Time',
        'Commerce, Finances, Services',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e8889b9-5faf-41da-a4f0-662cbbc5163f',
        'Présidentielle 2025 : La Cour constitutionnelle confirme le plébiscite d’Oligui Nguema',
        'La Cour constitutionnelle du Gabon a confirmé la large victoire d’Ali Bongo Ondimba à l’élection présidentielle de 2025, validant ainsi son plébiscite par les électeurs. Cette décision met fin aux contestations et consolide sa légitimité à la tête du pays.',
        'https://gabonmediatime.com/presidentielle-2025-la-cour-constitutionnelle-confirme-le-plebiscite-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80fc7b7a-8f3b-4e15-8520-bd1269196f97',
        'Insalubrité à Libreville : quand les habitants deviennent leurs propres bourreaux',
        'À Libreville, les habitants contribuent malgré eux à l''insalubrité en jetant leurs déchets dans la rue, aggravant les problèmes d''hygiène et de santé publique. Malgré les efforts des autorités, le manque de civisme et d''infrastructures adaptées rend la situation difficile à améliorer.',
        'https://kongossanews.info/insalubrite-a-libreville-quand-les-habitants-deviennent-leurs-propres-bourreaux/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-04-25T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

