-- Batch 2 - Section 11/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'edf6b83b-3e8c-4a36-9230-8e0511ed5381',
        'Pour Elza Ritchuelle Boukandou, les attentes du peuple envers Brice Clotaire Oligui Nguema reflètent un besoin légitime de chang...',
        'Elza Ritchuelle Boukandou souligne que les attentes du peuple gabonais envers Brice Clotaire Oligui Nguéma traduisent un désir légitime de changement, notamment en matière de gouvernance et de justice sociale.',
        'https://kongossanews.info/pour-elza-ritchuelle-boukandou-les-attentes-du-peuple-envers-brice-clotaire-oligui-nguema-refletent-un-besoin-legitime-de-changement/',
        'Kongossa News',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c2292bc-848e-4bb5-ad07-d7aa9334be2b',
        'Tribune/Gabon : Le pari risqué du « Rassemblement des Bâtisseurs » devenu parti politique',
        'Le Rassemblement des Bâtisseurs, initialement un mouvement citoyen au Gabon, se transforme en parti politique pour participer aux élections, mais ce changement soulève des questions sur sa capacité à maintenir son indépendance et son impact. Certains craignent que cette transition ne dilue ses idéaux originaux face aux réalités du jeu politique.',
        'https://kongossanews.info/tribune-gabon-le-pari-risque-du-rassemblement-des-batisseurs-devenu-parti-politique/',
        'Kongossa News',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f572a934-c1b4-4eda-ba3d-852b922aab3a',
        'Complot présumé contre HPO : les avocats dénoncent une justice instrumentalisée',
        'Des avocats dénoncent une instrumentalisation de la justice dans une affaire présumée de complot contre le Haut Patronat ivoirien, soulignant des irrégularités et des pressions politiques. Ils estiment que cette situation porte atteinte à l’indépendance de la justice et aux droits des personnes mises en cause.',
        'https://kongossanews.info/complot-presume-contre-hpo-les-avocats-denoncent-une-justice-instrumentalisee/',
        'Kongossa News',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0965ddc3-66e3-46aa-9cfc-660285ba8d82',
        'Gabon : le RdB reporte son Assemblée générale pour privilégier la concertation',
        'Le RDB a reporté son assemblée générale pour favoriser des discussions plus approfondies avec ses membres et partenaires, dans un souci de consensus et de transparence. Cette décision vise à mieux préparer les futures orientations stratégiques de l’organisation.',
        'https://gabonmediatime.com/gabon-le-rdb-reporte-son-assemblee-generale-pour-privilegier-la-concertation/',
        'Gabon Media Time',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '675a0768-633d-4b7f-ac77-c81bbc910f5e',
        'Gabon : La réforme de l’administration en ligne de mire',
        'Le Gabon lance une réforme administrative visant à moderniser et simplifier les services publics, en particulier grâce à la digitalisation, pour améliorer l''efficacité et la transparence. Cette initiative s''inscrit dans un effort plus large de modernisation de l''État et de lutte contre la bureaucratie.',
        'https://gabonmediatime.com/gabon-la-reforme-de-ladministration-en-ligne-de-mire/',
        'Gabon Media Time',
        'Numérique / Digital, Services',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e6d274b-5fb4-4ec6-a3e5-4a47237ceb2e',
        'Gabon : le RdB sur les traces d’En Marche pour la République',
        'Le Rassemblement pour le Développement du Gabon (RDB) s''inspire du modèle d''En Marche pour construire un projet politique centré sur la république, en mobilisant les citoyens autour des valeurs de transparence et de renouveau. Ce mouvement cherche à rassembler les Gabonais autour d''une vision commune pour l''avenir du pays.',
        'https://gabonmediatime.com/gabon-le-rdb-sur-les-traces-den-marche-pour-la-republique/',
        'Gabon Media Time',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12eb5154-5d21-4f3b-964e-51e5b71c4240',
        'Vers une plainte contre Laurence NDONG pour « gestion opaque & disciminatoire » de la subvention à la presse? Vive la 5e République !',
        'Des accusations de gestion opaque et discriminatoire de subventions à la presse visent Laurence Ndong, directrice de Vive la 5e République, suscitant des menaces de plainte pour manque de transparence dans la répartition des fonds.',
        'https://vxp241.com/2025/04/17/vers-une-plainte-contre-laurence-ndong-pour-gestion-opaque-disciminatoire-de-la-subvention-a-la-presse-vive-la-5e-republique/',
        'Vox Populi',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49caed86-3cb6-424b-8a23-7a9995169a36',
        'Oligui Nguema peut compter sur la prière et le soutien de ceux qui veulent le bien du Gabon (Nkoghe Bekale)',
        'Le président gabonais Oligui Nguema bénéficie du soutien et des prières de ceux qui souhaitent le bien du Gabon, selon une déclaration de Nkoghe Bekale. Cette affirmation met en avant l’importance de l’unité nationale et de la spiritualité dans la reconstruction du pays.',
        'https://gabonactu.com/blog/2025/04/17/oligui-nguema-peut-compter-sur-la-priere-et-le-soutien-de-ceux-qui-veulent-le-bien-du-gabon-nkoghe-bekale/',
        'Gabon Actu',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f38440eb-2062-4da0-93a3-36617b7f56fd',
        'La compagnie pétrolière Maurel & Prom a annoncé avoir réalisé une',
        'La compagnie pétrolière Maurel & Prom a annoncé avoir réalisé une production record au Gabon en 2024, atteignant un niveau historique grâce à l''optimisation de ses opérations et à l''exploitation efficace de ses champs pétroliers. Cette performance renforce sa position sur le marché énergétique africain.',
        'https://gabonactu.com/blog/2025/04/17/la-compagnie-petroliere-maurel-prom-a-annonce-avoir-realise-une/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances, Commerce, Agriculture',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '028fb898-ec77-48ab-aaf2-05c7cafdd5ad',
        'Gabon : le RdB reporte son Assemblée générale pour privilégier la concertation',
        'Le RDB a reporté son assemblée générale pour favoriser des discussions plus approfondies avec ses membres et partenaires, dans un souci de consensus et de transparence. Cette décision vise à mieux préparer les futures orientations stratégiques de l’organisation.',
        'https://gabonmediatime.com/gabon-le-rdb-reporte-son-assemblee-generale-pour-privilegier-la-concertation/',
        'Gabon Media Time',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '87c73781-99ae-4bd7-97ef-65d997e7864c',
        'Gabon : La réforme de l’administration en ligne de mire',
        'Le Gabon lance une réforme administrative visant à moderniser et simplifier les procédures publiques, avec pour objectif d''améliorer l''efficacité des services et la transparence de l''État. Cette initiative inclut la digitalisation des démarches et une rationalisation des structures gouvernementales.',
        'https://gabonmediatime.com/gabon-la-reforme-de-ladministration-en-ligne-de-mire/',
        'Gabon Media Time',
        'Numérique / Digital, Services',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ba59866-3a25-41cb-8d83-c53c83f4960a',
        'Gabon : le RdB sur les traces d’En Marche pour la République',
        'Le Rassemblement pour le Développement du Gabon (RDB) s''inspire du modèle d''En Marche pour la République, cherchant à moderniser son approche politique et à mobiliser les citoyens autour d''un projet de renouveau national. Ce mouvement vise à promouvoir une gouvernance plus inclusive et transparente, en s''appuyant sur les aspirations de la jeunesse gabonaise.',
        'https://gabonmediatime.com/gabon-le-rdb-sur-les-traces-den-marche-pour-la-republique/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '255bc255-d352-4ceb-88f5-ee71de48fdc8',
        'Publié le 16 / 04 / 2025',
        'L''article annonce qu''ILOKO reconnaît la victoire du "Bâtisseur en chef", mettant en avant son rôle clé dans un projet ou une initiative importante. Cette reconnaissance souligne son impact et son leadership dans le domaine concerné.',
        'https://union.sonapresse.com/index.php/fr/iloko-reconnait-la-victoire-du-batisseur-en-chef',
        'L''union',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9a69b59-cb95-484e-9dcc-b68ab5d64018',
        'Publié le 16 / 04 / 2025',
        'Pierre Claver Maganga Moussavou affirme que les résultats des élections sont clairs et que le président sortant Ali Bongo Ondimba les a remportées, malgré les contestations de l''opposition.',
        'https://union.sonapresse.com/index.php/fr/pierre-claver-maganga-moussavou-les-resultats-sont-la-oligui-nguema-bien-gagne-les-elections',
        'L''union',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3c454343-7225-4e75-b6ef-0124e19cfb96',
        'Publié le 16 / 04 / 2025',
        'L''article aborde la réforme de l''administration sous la Ve République en France, soulignant l''importance d''une collaboration inclusive avec tous les acteurs concernés pour moderniser et optimiser le système. Il met en avant les défis et les opportunités liés à cette transformation structurelle.',
        'https://union.sonapresse.com/index.php/fr/ve-republique-le-grand-chantier-de-la-reforme-de-ladministration-travailler-avec-tout-le-monde',
        'L''union',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b73735b-8010-4d10-bcda-177fa76cfaf1',
        'Gabon: retour progressif à l’ordre Constitutionnel & aux coupures d’électricité',
        'Le Gabon connaît des coupures d''électricité fréquentes malgré les efforts pour rétablir l''ordre constitutionnel après la crise politique récente, affectant la vie quotidienne et les activités économiques.',
        'https://vxp241.com/2025/04/17/gabon-retour-progressif-a-lordre-constitutionnel-aux-coupures-delectricite/',
        'Vox Populi',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2264dc4-d350-4a62-a12b-f46174d9602e',
        'France : Tassyla Doumbeneny heureuse d’avoir transformé l’ambassade en point de ralliement des gabonais',
        'L’ambassadrice de France au Gabon, Tassyla Doumbeneny, se réjouit d’avoir fait de l’ambassade un lieu de rassemblement et d’échanges pour la communauté gabonaise, favorisant les liens entre les deux pays.',
        'https://gabonactu.com/blog/2025/04/17/france-tassyla-doumbeneny-heureuse-davoir-transforme-lambassade-en-point-de-ralliement-des-gabonais/',
        'Gabon Actu',
        'Services, Tourisme, Business Femme',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e01d8905-c17a-406e-9cc4-8bcf08ca7cdb',
        'Gabon : Les observateurs chrétiens refusent l’expression «score à la soviétique» pour la victoire d’Oligui Nguema',
        'Les observateurs chrétiens au Gabon contestent l''expression "score à la soviétique" utilisée pour décrire la victoire d''Oligui Nguéma, la jugeant inappropriée et excessive. Ils appellent à un langage plus mesuré et constructif dans le débat politique.',
        'https://www.gabonreview.com/gabon-les-observateurs-chretiens-refusent-lexpression-score-a-la-sovietique-pour-la-victoire-doligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e01b1c2-c61d-4810-9f1c-18093e4f4933',
        'Transformation du RdB en parti politique : un report qui en dit long',
        'La transformation du Rassemblement pour le développement du Gabon (RDB) en parti politique est reportée, un délai qui soulève des questions sur les motivations et la préparation de cette transition. Ce report suggère des tensions ou des défis internes non résolus.',
        'https://www.gabonreview.com/transformation-du-rdb-en-parti-politique-un-report-qui-en-dit-long/',
        'Gabon Review',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '479a7e85-8d7c-417c-96f4-4f20d55139ca',
        'Réduire le train de vie de l''Etat pour bâtir l''édifice nouveau auquel tous nous rêvons',
        'Réduire les dépenses excessives de l''État permettrait de libérer des ressources pour investir dans des projets prioritaires comme l''éducation et les infrastructures, essentiels au développement du Gabon. Une meilleure gestion des finances publiques est nécessaire pour éviter le gaspillage et favoriser une croissance durable.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/reduire-le-train-de-vie-de-l-etat-pour-batir-l',
        'Gabonews',
        'Numérique / Digital, Finances, Éducation, Infrastructure',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1bb10160-6aa0-41ba-b171-69e939c6bc16',
        '‘"C''est avec l''expérience des anciens et le dynamisme de la jeunesse qu''on atteindra l''essor vers la félicité" dixit Jerry Bibang.',
        'L''article souligne l''importance de combiner l''expérience des anciens dirigeants avec l''énergie des jeunes pour progresser, en mettant l''accent sur la collaboration intergénérationnelle dans le développement politique.',
        'https://www.gabonews.com/fr/actus/politique/article/c-est-avec-l-experience-des-anciens-et-le',
        'Gabonews',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4b4c1285-4d37-4f39-a40b-450fdd2787c3',
        'Gabon/Journée Nationale de la Femme',
        'Le Gabon a célébré la Journée nationale de la femme, mettant en lumière les progrès et les défis liés à l''égalité des genres et à l''autonomisation des femmes dans le pays. Des activités et discours ont souligné l''importance de leur rôle dans le développement socio-économique.',
        'https://www.gabonews.com/fr/actus/societe/article/gabon-journee-nationale-de-la-femme',
        'Gabonews',
        'Business Femme, Éducation, Services',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12851ec8-7070-4a71-a285-690493f6c08a',
        'Gabon : baisse de 5,2% des activités extractives au quatrième trimestre 2024',
        'Les activités extractives au Gabon ont enregistré une baisse de 52 % au quatrième trimestre 2024, selon les données officielles. Cette contraction s’explique principalement par des difficultés logistiques et une baisse de la demande mondiale.',
        'https://agpgabon.ga/2025/04/17/gabon-baisse-de-52-des-activites-extractives-au-quatrieme-trimestre-2024/',
        'AGP',
        'Numérique / Digital, Services, Finances, Commerce, Agriculture',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4fe9d7b3-7da1-4612-89d3-b3814ce8eee6',
        'Union Africaine : le président Mahamoud Ali Youssouf se félicite du bon déroulement de l’élection présidentielle au Gabon',
        'Le président de la Commission de l’Union africaine, Mahamoud Ali Youssouf, salue le bon déroulement de l’élection présidentielle au Gabon, soulignant son caractère pacifique et démocratique.',
        'https://agpgabon.ga/2025/04/17/union-africaine-le-president-mahamoud-ali-youssouf-se-felicite-du-bon-deroulement-de-lelection-presidentielle-au-gabon/',
        'AGP',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '296a1e2d-7887-4404-8ce8-07d7a495f813',
        'RDB : d’Association à parti politique, la mue attendra',
        'L’article explique que l’association RDB, malgré ses ambitions politiques, n’a pas encore effectué sa transformation officielle en parti politique, retardant ainsi son engagement dans la sphère partisane. Les raisons de ce délai ne sont pas précisées, mais cela soulève des questions sur sa stratégie future.',
        'https://gabonactu.com/blog/2025/04/17/rdb-dassociation-a-parti-politique-la-mue-attendra/',
        'Gabon Actu',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd0c09a9c-3ea2-416f-a6a5-864f144879df',
        'Quel poste pour le Colonel Ulrich Manfoumbi figure tutélaire du CTRI ?',
        'Le colonel Ulrich Manfoumbi, figure influente du CTRi, pourrait se voir attribuer un nouveau poste, suscitant des interrogations sur son rôle futur dans cette institution. Sa position stratégique continue d’attirer l’attention dans le paysage politique et sécuritaire gabonais.',
        'https://gabonactu.com/blog/2025/04/17/quel-poste-pour-le-colonel-ulrich-manfoumbi-figure-tutelaire-du-ctri/',
        'Gabon Actu',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96592cbe-28c0-468e-a8a7-b12bcfc5b380',
        'Bon perdant, Germain Iloko annonce la création de son parti politique',
        'Germain Iloko, ancien candidat à la présidentielle gabonaise, annonce la création de son propre parti politique après sa défaite, affirmant vouloir continuer à œuvrer pour le développement du pays.',
        'https://www.gabonreview.com/bon-perdant-germain-iloko-annonce-la-creation-de-son-parti-politique/',
        'Gabon Review',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '783ceb1a-956d-407f-9a41-74f645eb6b8f',
        'Gabon : l’assemblée générale du Rassemblement des bâtisseurs reportée à une date ultérieure',
        'L’Assemblée générale du Rassemblement des Bâtisseurs, initialement prévue, a été reportée à une date ultérieure sans précision des raisons ou du nouveau calendrier.',
        'https://agpgabon.ga/2025/04/17/gabon-lassemblee-generale-du-rassemblement-des-batisseurs-reportee-a-une-date-ulterieure/',
        'AGP',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '71e08a09-23d3-488d-8bf5-5f05745df10d',
        'Panthères du Gabon : le gouvernement affirme avoir soldé  la dette de Patrice Neveu',
        'Le gouvernement gabonais déclare avoir réglé la dette envers Patrice Neveu, l''ancien sélectionneur des Panthères du Gabon, mettant ainsi fin à un contentieux financier lié à son contrat. Cette annonce vise à apaiser les tensions et à rassurer sur la gestion des fonds publics dans le sport.',
        'https://gabonactu.com/blog/2025/04/17/pantheres-du-gabon-le-gouvernement-affirme-avoir-solde-la-dette-de-patrice-neveu/',
        'Gabon Actu',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f54dc06e-0323-401e-aab3-74af4965c426',
        'Les Musulmans de la 5e République exhortent le Président Oligui Nguema à ne pas se laisser distraire par les perfides trompeurs',
        'Les musulmans de la 5e République encouragent le président Oligui Nguema à rester concentré sur ses priorités et à ne pas se laisser influencer par des individus malintentionnés.',
        'https://gabonactu.com/blog/2025/04/17/les-musulmans-de-la-5e-republique-exhortent-le-president-oligui-nguema-a-ne-pas-se-laisser-distraire-par-les-perfides-trompeurs/',
        'Gabon Actu',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5443f885-d6e6-4aa2-9844-97a81add89e8',
        'Un incendie cause des dégâts matériels importants à Port-Gentil',
        'Un incendie a provoqué d''importants dégâts matériels à Port-Gentil, sans faire de victimes selon les premières informations. Les causes du sinistre restent encore inconnues.',
        'https://gabonactu.com/blog/2025/04/17/un-incendie-cause-des-degats-materiels-importants-a-port-gentil/',
        'Gabon Actu',
        'Services, Commerce',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e306ea96-b4c9-4f09-9908-de4d9bfa37ed',
        'Leadership : Mark Doumba propulse le Gabon dans le cercle des décideurs mondiaux',
        'Mark Doumba, expert en leadership, représente désormais le Gabon parmi les décideurs mondiaux grâce à son influence dans les domaines technologiques et éducatifs, renforçant ainsi la visibilité du pays sur la scène internationale.',
        'https://www.gabonreview.com/leadership-mark-doumba-propulse-le-gabon-dans-le-cercle-des-decideurs-mondiaux/',
        'Gabon Review',
        'Numérique / Digital, Éducation',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ad639185-1f75-4fe4-bbca-aae115037fbe',
        'Une victoire nette et sans appel, consacrée par 90,35 % des suffrages exprimés en la faveur de Brice Clotaire Oligui Nguema',
        'Le candidat a remporté une victoire écrasante avec 90 % des voix, confirmant un large soutien populaire lors des élections.',
        'https://www.gabonews.com/fr/actus/politique/article/une-victoire-nette-et-sans-appel-consacree-par-90',
        'Gabonews',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc30040d-2dcd-4fe7-b9b3-a94851bc9227',
        'Bilan tragique et mesures d''urgence suite aux pluies diluviennes d''avril 2025 à Kinshasa',
        'Un violent incendie dans un immeuble résidentiel en Afrique du Sud a causé de nombreux morts et blessés, poussant les autorités à renforcer les mesures de sécurité et à secourir les survivants. Les causes du drame restent sous enquête tandis que des aides d''urgence sont déployées pour les victimes.',
        'https://www.gabonews.com/fr/actus/international/article/bilan-tragique-et-mesures-d-urgence-suite-aux',
        'Gabonews',
        'Autres',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0d6e56e-c2ec-495d-b5a6-6d78c2d19644',
        '"Hommage à toutes les femmes gabonaises"',
        'L''article rend hommage aux femmes gabonaises, soulignant leur courage, leur résilience et leur contribution essentielle au développement socio-économique du pays à travers divers secteurs. Il met en lumière leur rôle souvent méconnu mais déterminant dans la société gabonaise.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/hommage-a-toutes-les-femmes-gabonaises',
        'Gabonews',
        'Business Femme, Éducation',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '06e2c967-5454-431c-8342-4ab85f2b067e',
        'Gabon : Mark Alexandre Doumba honoré parmi les Young Global Leader 2025',
        'Mark Alexandre Doumba, entrepreneur gabonais, a été sélectionné parmi les Young Global Leaders 2025 pour son impact dans les domaines de la technologie et de l''éducation en Afrique. Cette distinction récompense son engagement en faveur de l''innovation et du développement sur le continent.',
        'https://agpgabon.ga/2025/04/17/gabon-mark-alexandre-doumba-honore-parmi-les-young-global-leader-2025/',
        'AGP',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-04-17T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6e9c13d6-a467-4440-984e-16c9727f758b',
        'Gabon, Soudan, Gaza…L’actualité vue par les éditorialistes africains',
        'L''article présente les perspectives d''éditorialistes africains sur des sujets d''actualité comme la situation politique au Gabon et au Soudan, ainsi que le conflit à Gaza, offrant une analyse locale de ces enjeux internationaux.',
        'https://www.rfi.fr/fr/podcasts/le-d%C3%A9bat-africain/20250418-gabon-soudan-gaza-l-actualit%C3%A9-vue-par-les-%C3%A9ditorialistes-africains',
        'RFI',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.421Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e3cc43d-f59f-4a74-bc47-f626af864823',
        '[Vos réactions] La Libre Antenne du 18 avril 2025',
        'L''article présente les réactions des auditeurs lors d''une libre antenne radiophonique du 18 avril 2025, abordant des sujets d''actualité variés à travers des échanges spontanés et des débats. Les contributions reflètent des opinions diversifiées sur des thèmes sociaux, politiques ou culturels du moment.',
        'https://www.rfi.fr/fr/podcasts/appels-sur-l-actualit%C3%A9/20250418-vos-r%C3%A9actions-la-libre-antenne-du-18-avril-2025',
        'RFI',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72b50e57-3f26-4331-9268-35eed6bb864c',
        'Mines : Millennial Potash réaffirme son engagement auprès du Gabon',
        'La société Millennial Potash réaffirme son engagement minier au Gabon, soulignant son respect des normes environnementales et son soutien aux communautés locales. Elle vise à développer des projets durables tout en collaborant avec les autorités gabonaises.',
        'https://directinfosgabon.com/mines-millennial-potash-reaffirme-son-engagement-aupres-du-gabon/',
        'Direct Infos Gabon',
        'Services, Agriculture',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd4700f7f-504f-4300-b253-daff0be4851d',
        'Gabon : Les 4 grands chantiers du président Oligui Nguema pendant son magistère',
        'Le président gabonais Oligui Nguema a lancé quatre grands chantiers prioritaires : la réforme des institutions, la relance économique, l''amélioration des services sociaux et la modernisation des infrastructures pour redresser le pays. Ces actions visent à stabiliser le Gabon et à améliorer les conditions de vie des citoyens.',
        'https://directinfosgabon.com/gabon-les-4-grands-chantiers-du-president-oligui-nguema-pendant-son-magistere/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture, Tourisme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27975e78-0758-42d8-9c46-0608bb7eb5ce',
        'Gabon : Ella Nguema veut initier une loi pour sauver les femmes du célibat',
        'Une députée gabonaise propose une loi pour lutter contre le célibat féminin en encourageant le mariage et en soutenant les femmes célibataires. Son initiative vise à promouvoir l’équilibre familial et social.',
        'https://gabonmediatime.com/gabon-ella-nguema-veut-initier-une-loi-pour-sauver-les-femmes-du-celibat/',
        'Gabon Media Time',
        'Services, Business Femme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3ac0730-ccf5-479e-93cc-b6eacb40dc68',
        'Décès Boupendza : les supporters du Zhejiang FC choqués après le maintien d’un match de championnat',
        'Les supporters du Zhejiang FC sont choqués après le maintien d’un match de championnat malgré le décès de leur joueur Boupendza, estimant que la décision manque de respect envers le défunt.',
        'https://gabonmediatime.com/deces-boupendza-les-supporters-du-zhejiang-fc-choques-apres-le-maintien-dun-match-de-championnat/',
        'Gabon Media Time',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd61d060b-5771-45a6-9814-48f0db6eed60',
        'Affaire Opiangah : vers une condamnation du Gabon par la Commission africaine des droits de l’Homme ?',
        'La Commission africaine des droits de l''homme pourrait condamner le Gabon pour la détention arbitraire et les mauvais traitements infligés à l''opposant Marc Opiangah, dont le cas soulève des inquiétudes sur le respect des droits humains dans le pays.',
        'https://gabonmediatime.com/affaire-opiangah-vers-une-condamnation-du-gabon-par-la-commission-africaine-des-droits-de-lhomme/',
        'Gabon Media Time',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '553b53c5-fea0-41fc-bc1e-12d1d51fe4ba',
        'Publié le 18 / 04 / 2025',
        'L''article analyse la situation politique au Gabon à travers le prisme des élections présidentielles, en soulignant les enjeux de gouvernance et les défis démocratiques dans un contexte africain. Il illustre comment le pays sert d''exemple pour comprendre les dynamiques du pouvoir et les tensions institutionnelles sur le continent.',
        'https://union.sonapresse.com/fr/presidentielle-le-gabon-un-cas-decole',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f63b7077-e7b7-4627-aec5-44c6b87b418b',
        'Publié le 18 / 04 / 2025',
        'Le président gabonais Oligui Nguema rend hommage à l’attaquant Aaron Boupendza, décédé, en saluant son talent et sa carrière remarquable dans le football.',
        'https://union.sonapresse.com/fr/deces-daaron-boupendza-le-president-oligui-nguema-salue-la-memoire-dun-avant-centre-de-talent',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '77e63946-370f-46fe-812e-9976ac6148a1',
        'Publié le 17 / 04 / 2025',
        'La plateforme RDB a annulé son assemblée générale prévue initialement le samedi 19 avril, sans fournir de détails supplémentaires sur les raisons de cette décision.',
        'https://union.sonapresse.com/fr/rdb-la-plateforme-annule-son-ag-prevue-ce-samedi-19-avril',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3c6fe772-1c83-4534-b1ee-fde9a164099a',
        'Tensions France-Algérie, Nguema élu au Gabon, deux ans de guerre au Soudan : l’hebdo Afrique',
        'Les tensions entre la France et l''Algérie persistent, tandis qu''au Gabon, Nguema est élu président et le Soudan marque deux ans d''une guerre dévastatrice. Ces événements illustrent les défis politiques et sécuritaires en Afrique.',
        'https://www.france24.com/fr/afrique/20250418-hebdo-afrique-tensions-france-alg%C3%A9rie-nguema-%C3%A9lu-au-gabon-deux-ans-de-guerre-au-soudan?utm_source=flipboard&utm_content=topic/fr-actualit%C3%A9s',
        'Flipboard',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd4e1f060-15f3-4b05-8219-2398d31015e9',
        'Tensions France-Algérie, Nguema élu au Gabon, deux ans de guerre au Soudan : l’hebdo Afrique',
        'Les tensions entre la France et l''Algérie persistent, tandis qu''au Gabon, Nguema est élu président après une période de transition, et au Soudan, la guerre civile entre factions militaires entre dans sa deuxième année.',
        'https://www.france24.com/fr/afrique/20250418-hebdo-afrique-tensions-france-alg%C3%A9rie-nguema-%C3%A9lu-au-gabon-deux-ans-de-guerre-au-soudan',
        'France 24',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '269066ee-b867-4db6-86f5-6ea6b0c24dc9',
        'Pétrole : Maurel & Prom mise sur le Gabon malgré un 1er trimestre 2025 en repli',
        'Malgré une baisse de ses activités au premier trimestre 2025, Maurel & Prom maintient sa confiance dans le secteur pétrolier gabonais et continue d’investir dans le pays.',
        'https://directinfosgabon.com/petrole-maurel-prom-mise-sur-le-gabon-malgre-un-1er-trimestre-2025-en-repli/',
        'Direct Infos Gabon',
        'Commerce, Finances, Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '505ea5a2-8a25-4e87-accd-00ffd81ab6f7',
        'Arise Ports & Logistics : Olam cède ses parts pour plus de 100 milliards FCFA',
        'ARISE Ports & Logistics a racheté les parts d’Olam dans une coentreprise gabonaise pour plus de 100 milliards de FCFA, renforçant ainsi son contrôle dans les infrastructures portuaires et logistiques locales. Cette transaction s’inscrit dans une stratégie d’expansion en Afrique.',
        'https://directinfosgabon.com/arise-ports-logistics-olam-cede-ses-parts-pour-plus-de-100-milliards-fcfa/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Commerce',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

