-- Batch 2 - Section 14/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'df68484c-6907-43c9-9d6a-7e8ab823e005',
        'Publié le 21 / 04 / 2025',
        'L''article souligne les aspects positifs du HCANEG (Haut Conseil des Acteurs Non Étatiques de Guinée) lors de la présidentielle, notamment son rôle dans la promotion du dialogue et de la transparence électorale. Il met en avant ses efforts pour renforcer la participation citoyenne et la crédibilité du processus démocratique.',
        'https://union.sonapresse.com/fr/presidentielle-les-bons-points-du-hcaneg',
        'L''union',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '809391c3-1868-4ac2-a9a6-af2afdc52843',
        'Département de la Zadié : Estevil Bouya, le cœur dans le social Tchibanga/Mongo : le beau geste de Dame Massounga épse Ignoumba ...',
        'Le département de la Zadié-Est sous la direction d''Estevil Bouya s''engage dans des actions sociales pour améliorer les conditions de vie des populations locales, notamment à travers des projets éducatifs et sanitaires.',
        'https://mediapostegabon.com/departement-de-la-zadie-estevil-bouya-le-coeur-dans-le-social/',
        'Media Poste Gabon',
        'Numérique / Digital, Services, Éducation, Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc8f4f0f-c186-49b0-97e5-3253e358ba93',
        'L’agence d’aide des Émirats arabes unis signe un accord pour la construction de la mosquée Cheikh Zayed et d’un centre culturel au Tchad',
        'L’Agence d’aide des Émirats arabes unis a signé un accord pour financer la construction de la mosquée Sheikh Zayed et d’un centre culturel au Tchad, dans le cadre de projets visant à renforcer les liens culturels et religieux.',
        'https://agpgabon.ga/2025/04/21/lagence-daide-des-emirats-arabes-unis-signe-un-accord-pour-la-construction-de-la-mosquee-cheikh-zayed-et-dun-centre-culturel-au-tchad/',
        'AGP',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aa11ec4e-7cb2-49a3-aa76-ea0aaf93f1ea',
        'Pape François : son message de foi, de paix et d’humilité restera une source d’inspiration (Oligui Nguema)',
        'Le président gabonais Oligui Nguema rend hommage au message de foi, de paix et d’humilité du pape François, soulignant que son héritage continuera d’inspirer les générations futures. Il salue son engagement en faveur de l’unité et de la justice sociale.',
        'https://gabonactu.com/blog/2025/04/21/pape-francois-son-message-de-foi-de-paix-et-dhumilite-restera-une-source-dinspiration-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '780173e6-514e-49a4-9b77-e652ac369e6b',
        'Aucune source ou rivière n’a été affectée suite à la perte de confinement d’un pipeline',
        'Aucune source d''eau ou rivière n''a été contaminée après la fuite d''un pipeline, selon les autorités, qui affirment que la situation est sous contrôle et que des mesures ont été prises pour éviter tout impact environnemental.',
        'https://gabonactu.com/blog/2025/04/21/aucune-source-ou-riviere-na-ete-affectee-suite-a-la-perte-de-confinement-dun-pipeline/',
        'Gabon Actu',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f2876b1-ef13-464f-9f00-b7a7eb93fd8b',
        'Le PDG version Y’Obegue dénonce une ‘’mascarade électorale’’  et rejoint l’opposition',
        'Le PDG de Version Yobègue dénonce une mascarade électorale au Gabon et annonce son ralliement à l’opposition, critiquant le manque de transparence du processus.',
        'https://www.gabonreview.com/le-pdg-version-yobegue-denonce-une-mascarade-electorale-et-rejoint-lopposition/',
        'Gabon Review',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '200f6b86-9d1c-41d3-9b49-d085c657f1de',
        'La CFU expliquée : entre simplification fiscale et élargissement de l’assiette',
        'La CFU (Contribution Fiscal Unique) au Gabon vise à simplifier le système fiscal en fusionnant plusieurs taxes, tout en élargissant l''assiette fiscale pour augmenter les recettes de l''État. Cette réforme cherche à équilibrer facilitation pour les entreprises et renforcement des ressources publiques.',
        'https://www.gabonreview.com/la-cfu-expliquee-entre-simplification-fiscale-et-elargissement-de-lassiette/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e77e0dd5-3c8e-46c4-8139-01c71e3be314',
        '"La problématique de la gestion hospitalière au Gabon"',
        'L''article aborde les défis de la gestion hospitalière au Gabon, soulignant les problèmes d''organisation, de manque de ressources et d''efficacité qui impactent la qualité des soins. Il met en lumière la nécessité d''une réforme pour améliorer le système de santé.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/la-problematique-de-la-gestion-hospitaliere-au',
        'Gabonews',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d0147f9-6bd4-40b7-ae2b-31b1e317a0d2',
        'Le Maroc et l''Union africaine s''unissent pour renforcer l''observation électorale sur le continent',
        'Le Maroc et l''Union africaine renforcent leur coopération dans les domaines de l''éducation, de la science et de la technologie pour favoriser le développement du continent. Cette collaboration vise à promouvoir l''innovation et la formation des jeunes Africains.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-maroc-et-l-union-africaine-s-unissent-pour',
        'Gabonews',
        'Éducation, Numérique / Digital',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c46892d3-f95f-4f45-b94c-41290d4700dd',
        'Port-Gentil : pour incitation à la violence et trouble à l’ordre public, il file en prison',
        'Un individu a été condamné à de la prison à Port-Gentil pour incitation à la violence et trouble à l’ordre public après des propos jugés dangereux. Son arrestation vise à préserver la paix sociale dans la région.',
        'https://gabonactu.com/blog/2025/04/21/port-gentil-pour-incitation-a-la-violence-et-trouble-a-lordre-public-il-file-en-prison/',
        'Gabon Actu',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5816a765-108a-46a6-b649-bf797b8d254e',
        'Bilie By Nze avait un bon projet mais sa crédibilité et sa réputation ne passent aux yeux des Gabonais, selon Petit Lambert Owono',
        'Bilie By Nze avait un projet prometteur, mais sa crédibilité et sa réputation sont remises en question par les Gabonais, d''après Petit Lambert Owono.',
        'https://gabonactu.com/blog/2025/04/21/bilie-by-nze-avait-un-bon-projet-mais-sa-credibilite-et-sa-reputation-ne-passent-aux-yeux-des-gabonais-selon-petit-lambert-owono/',
        'Gabon Actu',
        'Autres',
        '2025-04-21T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85f1da5a-1f3b-4c3e-bc99-d7829b3d3c92',
        'Gabon/Dégradation de la voie au niveau de l’échangeur de Nzeng-Ayong : un danger pour les usagers',
        'La dégradation de la voie au niveau de l’échangeur de Nzeng Ayong à Libreville représente un danger pour les usagers, avec des nids-de-poule et des fissures qui risquent de provoquer des accidents. Les autorités sont appelées à intervenir rapidement pour réparer cette infrastructure routière essentielle.',
        'https://agpgabon.ga/2025/04/21/gabon-degradation-de-la-voie-au-niveau-de-lechangeur-de-nzeng-ayong-un-danger-pour-les-usagers/',
        'AGP',
        'Services, Commerce, Numérique / Digital',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8457b132-bc0a-4e8a-93b0-a6046305d97a',
        'Réglementation des changes : Bras de fer entre la BEAC et les pétroliers',
        'La BEAC impose aux compagnies pétrolières de rapatrier leurs recettes d’exportation dans les banques locales, mais ces dernières résistent en invoquant des contraintes opérationnelles et des risques financiers. Ce désaccord révèle des tensions sur la régulation des changes en zone CEMAC.',
        'https://directinfosgabon.com/reglementation-des-changes-bras-de-fer-entre-la-beac-et-les-petroliers/',
        'Direct Infos Gabon',
        'Numérique / Digital, Finances, Services',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9ffb8a3-8439-41ac-8168-819ac63ca67a',
        'CEMAC : La BEAC injecte 400 milliards de FCFA pour soutenir les banques',
        'La BEAC a injecté 400 milliards de FCFA dans les banques de la CEMAC pour renforcer leur liquidité et soutenir l’économie régionale face aux défis financiers. Cette mesure vise à éviter les tensions et à garantir le bon fonctionnement du système bancaire.',
        'https://directinfosgabon.com/cemac-la-beac-injecte-400-milliards-de-fcfa-pour-soutenir-les-banques/',
        'Direct Infos Gabon',
        'Finances, Services',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e59d73a5-83ed-4c38-9b9c-e7a83f06c0ea',
        'Incident à Coucal : Aucune source ou rivière impactée',
        'Un incident technique a provoqué une fuite d’hydrocarbures à Coucal, mais les autorités affirment qu’aucune source d’eau ou rivière n’a été impactée, et les opérations de nettoyage sont en cours.',
        'https://directinfosgabon.com/incident-a-coucal-aucune-source-ou-riviere-impactee/',
        'Direct Infos Gabon',
        'Services, Agriculture, Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4eec93d-c972-4a9e-95e6-a7efeae4ef2e',
        'Tribune / « Et si Akanda devenait la première ville climatique du Gabon ? »',
        'Akanda pourrait devenir la première ville climatique du Gabon en intégrant des solutions durables pour lutter contre les inondations et promouvoir un développement urbain respectueux de l''environnement. Cette initiative vise à transformer la ville en un modèle écologique tout en améliorant la qualité de vie des habitants.',
        'https://directinfosgabon.com/tribune-et-si-akanda-devenait-la-premiere-ville-climatique-du-gabon/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Agriculture, Tourisme',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d3f7576-69c4-4787-90b3-a68979c90935',
        'Présidentielle 2025 : la Cour constitutionnelle finalise l’examen des résultats',
        'La Cour constitutionnelle du Gabon finalise l''examen des résultats de l''élection présidentielle de 2025, une étape cruciale pour valider le scrutin. Ce processus vise à garantir la transparence et la conformité aux règles électorales.',
        'https://www.gabonreview.com/presidentielle-2025-la-cour-constitutionnelle-finalise-lexamen-des-resultats/',
        'Gabon Review',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '59c39974-0dd8-41f5-98a3-20b64f300e5b',
        'Affaire SNOM Consulting/Orabank : la banque condamnée à verser 500 millions de francs CFA de dommages et intérêts',
        'Orabank Gabon a été condamnée à payer 500 millions de FCFA à Snom Consulting pour rupture abusive de contrat et préjudice subi, selon un jugement du tribunal de Libreville. La banque conteste cette décision et envisage de faire appel.',
        'https://www.gabonreview.com/affaire-snom-consulting-orabank-la-banque-condamnee-a-verser-500-millions-de-francs-cfa-de-dommages-et-interets/',
        'Gabon Review',
        'Finances, Services',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b58eb1bd-93ed-49df-8428-185564ecc75d',
        'Supervision des CDC : le Gabon et le Cameroun défient la COBAC au nom de leur souveraineté',
        'Le Gabon et le Cameroun contestent la supervision de leurs caisses de dépôts et consignations par la COBAC, arguant du respect de leur souveraineté nationale et de leurs lois locales. Cette opposition illustre les tensions entre les régulations régionales et les prérogatives des États en matière de contrôle financier.',
        'https://www.gabonreview.com/supervision-des-cdc-le-gabon-et-le-cameroun-defient-la-cobac-au-nom-de-leur-souverainete/',
        'Gabon Review',
        'Finances, Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '200b1e86-d1b6-49a2-a8fc-1d05eefe511f',
        'Les hommages des sœurs Moulombi au Pape François',
        'Les sœurs Muloumbi ont rendu hommage au pape François pour son engagement en faveur de la paix et de l''unité, soulignant son influence positive dans le monde. Leur message met en avant les valeurs de compassion et de dialogue promues par le pape.',
        'https://www.gabonews.com/fr/actus/religion/article/les-hommages-des-soeurs-moulombi-au-pape-francois',
        'Gabonews',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce42f4ff-1ed1-45be-bbbe-7169430e30dd',
        'Port-Gentil : bientôt une prison  pour enfants',
        'Une prison pour mineurs est en construction à Port-Gentil, au Gabon, afin de répondre aux besoins spécifiques des jeunes délinquants et de les séparer des adultes dans le système carcéral. Ce projet vise à offrir un environnement adapté pour la réinsertion sociale des enfants en conflit avec la loi.',
        'https://gabonactu.com/blog/2025/04/22/port-gentil-bientot-une-prison-pour-enfants/',
        'Gabon Actu',
        'Éducation, Services, Business Femme',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '890ed150-21ef-4641-8d25-8a49783094b8',
        'Dénonciation et cri de détresse du collectif des marins de Peschaud Gabon',
        'Des marins gabonais du collectif Peschaud dénoncent leurs conditions de travail précaires, réclamant le paiement de salaires impayés et une amélioration de leurs droits sociaux face à l''inaction des autorités.',
        'https://gabonactu.com/blog/2025/04/22/denonciation-et-cri-de-detresse-du-collectif-des-marins-de-peschaud-gabon/',
        'Gabon Actu',
        'Services, Finances, Business Femme',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '471afe5c-9405-41b7-b771-d61bd8b42eb0',
        'Une dame meurt percutée par un véhicule fou à Port-Gentil',
        'Une femme est décédée après avoir été percutée par un véhicule incontrôlé à Port-Gentil. L''accident s''est produit dans des circonstances encore floues, suscitant l''émoi parmi les habitants.',
        'https://gabonactu.com/blog/2025/04/22/une-dame-meurt-percutee-par-un-vehicule-fou-a-port-gentil/',
        'Gabon Actu',
        'Services, Éducation, Numérique / Digital',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ca9f1ef-39e7-471e-9e41-ce4e3fad2bf5',
        'Coopération Gabon – Chine : Xi Jinping «prêt à travailler» avec Oligui Nguema',
        'Le président chinois Xi Jinping a exprimé sa volonté de renforcer la coopération avec le Gabon sous la direction du général Oligui Nguema, notamment dans les domaines économiques et des infrastructures. Cette collaboration vise à soutenir le développement du Gabon tout en consolidant les relations bilatérales entre les deux pays.',
        'https://www.gabonreview.com/cooperation-gabon-chine-xi-jinping-pret-a-travailler-avec-oligui-nguema/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce, Finances, Infrastructure',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'effba2d0-9a82-4c2d-a352-09d36290b2e4',
        'Gabon : Après la présidentielle, Chaning Zenaba envisage la création d’un parti politique',
        'Après les élections présidentielles au Gabon, Chaning Zenaba, ancienne candidate, envisage de créer un nouveau parti politique pour poursuivre son engagement dans la vie publique.',
        'https://www.gabonreview.com/gabon-apres-la-presidentielle-chaning-zenaba-envisage-la-creation-dun-parti-politique/',
        'Gabon Review',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58bf52b7-3543-4d5a-932e-3422d7d8f186',
        'OMS : Afrique, continent le plus touché par les suicides !',
        'L''Afrique est le continent le plus touché par les suicides, selon l''OMS, avec des taux alarmants liés à des facteurs comme la pauvreté, les conflits et le manque d''accès aux soins mentaux. Les jeunes et les personnes âgées sont particulièrement vulnérables face à cette crise de santé publique.',
        'https://gabonmediatime.com/oms-afrique-continent-le-plus-touche-par-les-suicides/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85cf454b-4151-4c8f-90a3-12cd0180f8c2',
        'Réformes de la Ve République : un chantier titanesque pour une gouvernance en quête d’efficacité',
        'Les réformes de la Ve République au Gabon visent à améliorer l''efficacité de la gouvernance, mais elles représentent un défi complexe en raison des obstacles structurels et politiques. Ces changements ambitionnent de moderniser les institutions pour répondre aux attentes des citoyens.',
        'https://gabonmediatime.com/reformes-de-la-ve-republique-un-chantier-titanesque-pour-une-gouvernance-en-quete-defficacite/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33fbf709-6b9c-4b3b-ba09-9b1e83e6e405',
        'Fuite de pétrole à Coucal : plus des deux tiers des 400 barils déjà récupérés par Perenco Oil & Gas Gabon',
        'Plus des deux tiers des 400 barils de pétrole fuis à Coucal au Gabon ont été récupérés par Perenco Oil & Gas, limitant ainsi l''impact environnemental. Les opérations de nettoyage se poursuivent pour traiter le reste de la pollution.',
        'https://gabonmediatime.com/fuite-de-petrole-a-coucal-plus-des-deux-tiers-des-400-barils-deja-recuperes-par-perenco-oil-gas-gabon/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Agriculture, Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '567287ec-b882-4318-969d-fb07864faa94',
        'Publié le 22 / 04 / 2025',
        'Des messages de félicitations ont été adressés au président Brice Clotaire Oligui Nguema pour son leadership, soulignant son engagement en faveur du développement et de la stabilité du pays.',
        'https://union.sonapresse.com/fr/messages-de-felicitations-au-president-brice-clotaire-oligui-nguema-0',
        'L''union',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '28059297-67ef-4614-b7b3-9803e7f0d43f',
        'Publié le 22 / 04 / 2025',
        'Le PDG du groupe Légaliste, Onanga Yobègue, encourage la formation d''un front politique solide pour renforcer l''unité et la stabilité en Afrique, en insistant sur la nécessité d''une collaboration entre différents acteurs.',
        'https://union.sonapresse.com/fr/pdg-legaliste-onanga-yobegue-appelle-la-constitution-dun-front-politique-solide',
        'L''union',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f8ea55d3-d500-4e9a-87b1-c9caea1480c4',
        'Diplomatie Israël/France : Israël interdit à une délégation d’élus français de se rendre sur son territoire',
        'Israël a interdit à une délégation d''élus français d''entrer sur son territoire, marquant une tension diplomatique entre les deux pays. Cette décision intervient dans un contexte de relations tendues autour des questions politiques et sécuritaires.',
        'https://agpgabon.ga/2025/04/22/diplomatie-israel-france-israel-interdit-a-une-delegation-delus-francais-de-se-rendre-sur-son-territoire/',
        'AGP',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e0465a2-ecab-4cea-b52d-fa1c476ab17f',
        'OMS : Afrique, continent le plus touché par les suicides !',
        'L''Afrique est le continent le plus touché par les suicides, selon l''OMS, avec des taux alarmants liés à des facteurs comme la pauvreté, les conflits et le manque d''accès aux soins mentaux. Les jeunes et les personnes âgées sont particulièrement vulnérables face à cette crise silencieuse.',
        'https://gabonmediatime.com/oms-afrique-continent-le-plus-touche-par-les-suicides/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '601e7830-625f-4c7c-815c-6602e36bb93b',
        'Réformes de la Ve République : un chantier titanesque pour une gouvernance en quête d’efficacité',
        'Les réformes de la Ve République au Gabon visent à améliorer l''efficacité de la gouvernance, mais leur mise en œuvre reste un défi complexe en raison des obstacles structurels et politiques.',
        'https://gabonmediatime.com/reformes-de-la-ve-republique-un-chantier-titanesque-pour-une-gouvernance-en-quete-defficacite/',
        'Gabon Media Time',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1f3af3a-aa27-4c9d-bc32-39bf445cada0',
        'Fuite de pétrole à Coucal : plus des deux tiers des 400 barils déjà récupérés par Perenco Oil & Gas Gabon',
        'Plus des deux tiers des 400 barils de pétrole fuis à Coucal au Gabon ont déjà été récupérés par Perenco Oil & Gas, limitant ainsi l''impact environnemental de l''incident.',
        'https://gabonmediatime.com/fuite-de-petrole-a-coucal-plus-des-deux-tiers-des-400-barils-deja-recuperes-par-perenco-oil-gas-gabon/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Agriculture, Tourisme',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c648bcf4-c00f-4299-ac19-da0065525ba5',
        'Publié le 22 / 04 / 2025',
        'Des messages de félicitations ont été adressés au président Brice Clotaire Oligui Nguéma pour son leadership, soulignant les espoirs placés en lui pour le développement du pays. Les soutiens exprimés reflètent une attente de stabilité et de progrès sous sa direction.',
        'https://union.sonapresse.com/fr/messages-de-felicitations-au-president-brice-clotaire-oligui-nguema-0',
        'L''union',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '513dc00e-139a-4f31-b95c-e89fe0dfacf9',
        'Publié le 22 / 04 / 2025',
        'Le PDG du groupe Légaliste, Onanga Yobègue, encourage la formation d''un front politique solide pour renforcer la cohésion et l''efficacité des actions en faveur du développement et de la stabilité en Afrique. Il souligne l''importance d''une collaboration structurée entre différents acteurs politiques pour atteindre des objectifs communs.',
        'https://union.sonapresse.com/fr/pdg-legaliste-onanga-yobegue-appelle-la-constitution-dun-front-politique-solide',
        'L''union',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c09b1480-3f04-43af-948b-d2ea8ff5dfd7',
        'Au Gabon, autour de Brice Clotaire Oligui Nguema, la bataille des postes a déjà commencé',
        'Au Gabon, après le coup d''État, des rivalités émergent autour du général Oligui Nguema pour le contrôle des postes clés, alors que la transition politique s''organise.',
        'https://www.jeuneafrique.com/1681015/politique/au-gabon-autour-de-brice-clotaire-oligui-nguema-la-bataille-des-postes-a-deja-commence/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95d76e1c-d8bd-4521-89dd-88835092ad41',
        'Turquie :  Aaron Appindangoye monte en super ligue turque',
        'Le joueur gabonais Aaron Appindangoye rejoint la Super Ligue turque, marquant une étape importante dans sa carrière footballistique.',
        'https://gabonactu.com/blog/2025/04/22/turquie-aaron-appindangoye-monte-en-super-ligue-turque/',
        'Gabon Actu',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31ee5818-a6e3-4755-a995-c4be06444557',
        'Naufrage de l’Esther Miracle : les familles des victimes réclament toujours justice',
        'Les familles des victimes du naufrage de l’Esther Miracle continuent de réclamer justice, insatisfaites des réponses des autorités malgré le temps écoulé depuis la tragédie.',
        'https://gabonactu.com/blog/2025/04/22/naufrage-de-lesther-miracle-les-familles-des-victimes-reclament-toujours-justice/',
        'Gabon Actu',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f6a82ca-3cb5-41be-8930-18aea88fe62e',
        'Les étudiants de l’ENAM barricadent brièvement la nationale N°1 pour réclamer 7 mois d’arriérés de bourse',
        'Des étudiants de l’ENAM ont brièvement bloqué la Nationale 1 pour réclamer le paiement de sept mois d’arriérés de bourses, perturbant temporairement la circulation. Leur action visait à alerter les autorités sur leurs difficultés financières persistantes.',
        'https://gabonactu.com/blog/2025/04/22/les-etudiants-de-lenam-barricadent-brievement-la-nationale-n1-pour-reclamer-7-mois-darrieres-de-bourse/',
        'Gabon Actu',
        'Finances, Services, Éducation',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9164fcc-08ed-4b3d-8165-b84b6fd71735',
        'Mort du Pape François : Les hommages du Gabon',
        'Le Gabon a rendu hommage au pape François à l''occasion de son décès, exprimant tristesse et reconnaissance pour son engagement en faveur de la paix et du dialogue. Les autorités et citoyens ont salué son héritage spirituel et son influence positive.',
        'https://www.gabonreview.com/mort-du-pape-francois-les-hommages-du-gabon/',
        'Gabon Review',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bcb1a55b-8fc4-4fe6-8388-aaf7ad543710',
        'Au Gabon, autour de Brice Clotaire Oligui Nguema, la bataille des postes a déjà commencé',
        'Au Gabon, après le coup d''État, des rivalités émergent autour du général Oligui Nguema pour le contrôle des postes clés, alors que la transition politique s''organise. Les anciennes élites et de nouveaux acteurs se disputent les positions influentes dans ce contexte incertain.',
        'https://www.jeuneafrique.com/1681015/politique/au-gabon-autour-de-brice-clotaire-oligui-nguema-la-bataille-des-postes-a-deja-commence/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-22T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d335bbb-b7a0-4d92-915f-a3a015cbc464',
        'Gabon : la dette publique en recul de 280 milliards FCFA en 2024',
        'La dette publique du Gabon a diminué de 280 milliards de FCFA en 2024, marquant une amélioration significative de la situation financière du pays. Cette baisse résulte des efforts du gouvernement pour mieux gérer les finances publiques et réduire l''endettement.',
        'https://agpgabon.ga/2025/04/22/gabon-la-dette-publique-en-recul-de-280-milliards-fcfa-en-2024/',
        'AGP',
        'Finances',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a5c32cd-64c4-4c46-a4dc-48fb3d7f8b8d',
        'Au Gabon, Brice Clotaire Oligui Nguema peut-il réussir ? - Jeune Afrique.com',
        'Brice Clotaire Oligui Nguema, leader de la transition au Gabon, doit relever des défis majeurs comme la relance économique et la réconciliation nationale pour réussir son mandat. Son approche et ses décisions détermineront si la population gabonaise soutiendra son projet de réformes.',
        'https://www.jeuneafrique.com/1669101/politique/au-gabon-brice-clotaire-oligui-nguema-peut-il-reussir/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7c81cfc-19e0-4d2a-9cf6-6ac19072c5c2',
        'BW Energy : Une découverte à 56 millions de barils de pétrole au large du Gabon',
        'Une découverte pétrolière de 56 millions de barils a été annoncée au large du Gabon par la société BW Energy, renforçant ainsi le potentiel énergétique du pays. Cette trouvaille pourrait stimuler l''économie locale et confirme l''importance du Gabon dans la production pétrolière africaine.',
        'https://directinfosgabon.com/bw-energy-une-decouverte-a-56-millions-de-barils-de-petrole-au-large-du-gabon/',
        'Direct Infos Gabon',
        'Numérique / Digital, Service, Finances, Commerce, Tourisme',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25543237-cd00-4afa-83c4-992f4a2c03fb',
        'Fer Baniaka : Genmin et Sinohydro vont lancer la production d’ici fin 2026',
        'Genmin et Sinohydro prévoient de lancer la production de fer à Baniaka d’ici fin 2026, marquant une étape clé dans le développement minier du Gabon. Ce projet vise à exploiter les ressources locales et à stimuler l’économie régionale.',
        'https://directinfosgabon.com/fer-baniaka-genmin-et-sinohydro-vont-lancer-la-production-dici-fin-2026/',
        'Direct Infos Gabon',
        'Services, Finances, Commerce, Agriculture',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a3fe498b-a145-4da2-9ced-ba592a3bc903',
        'Potasse de la Banio : Millennial Potash confirme le grand potentiel du site',
        'Millennial Potash confirme que le site de potasse de la Banio au Gabon présente un potentiel significatif, avec des ressources minérales importantes et des perspectives économiques prometteuses. Les études préliminaires indiquent une viabilité technique et financière pour le développement du projet.',
        'https://directinfosgabon.com/potasse-de-la-banio-millennial-potash-confirme-le-grand-potentiel-du-site/',
        'Direct Infos Gabon',
        'Agriculture, Finances, Commerce',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a65daf54-f6fe-4ad0-84b6-c70b44ebb03c',
        'Contribution Foncière Unique : Eric Boumah veut récolter 23 milliards de francs',
        'Le ministre gabonais Eric Boumah vise à collecter 23 milliards de francs CFA grâce à la contribution foncière unique, une taxe destinée à renforcer les recettes publiques. Cette mesure s’inscrit dans une stratégie d’optimisation fiscale pour soutenir le développement économique du pays.',
        'https://directinfosgabon.com/contribution-fonciere-unique-eric-boumah-veut-recolter-23-milliards-de-francs/',
        'Direct Infos Gabon',
        'Finances, Services, Numérique / Digital',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.423Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e2b569dd-3455-4ed1-a504-66c5ccad8632',
        'Africa Capital Markets Forum 2025 : Libreville carrefour stratégique pour les marchés financiers africains',
        'Le Forum des marchés de capitaux africains 2025 se tiendra à Libreville, offrant une plateforme stratégique pour renforcer les échanges et les collaborations entre les acteurs financiers du continent. Cet événement vise à dynamiser l''intégration et la croissance des marchés financiers africains.',
        'https://directinfosgabon.com/africa-capital-markets-forum-2025-libreville-carrefour-strategique-pour-les-marches-financiers-africains/',
        'Direct Infos Gabon',
        'Finances, Service, Numérique / Digital',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68d94ce6-4d10-4795-822e-dfce2b0153c7',
        'ENAM : Le calme après la tempête',
        'Après une période de tensions et de perturbations, l’École nationale d’administration et de magistrature (ENAM) du Gabon retrouve un climat apaisé, marquant un retour à la normale pour les étudiants et le personnel. Les mesures prises ont permis de résoudre les conflits et de rétablir le fonctionnement habituel de l’institution.',
        'https://gabonactu.com/blog/2025/04/23/enam-le-calme-apres-la-tempete/',
        'Gabon Actu',
        'Éducation, Services',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

