-- Batch 4 - Section 19/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '678aaded-5442-44cf-8e59-6da0ea1ccbd8',
        'Publié le 20 / 06 / 2025',
        'L’article souligne la nécessité de réformes des partis politiques en Afrique, en insistant sur l''adoption de critères stricts pour assurer leur transparence, leur stabilité et leur représentation démocratique.',
        'https://union.sonapresse.com/fr/reformes-des-partis-politiques-des-criteres-contraignants',
        'L''union',
        'Business Intelligence',
        '2025-06-20T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c2dcad31-07b2-4028-be80-423ede168085',
        'Publié le 20 / 06 / 2025',
        'La date limite pour déposer les comptes de campagne présidentielle est fixée au 25 juin.',
        'https://union.sonapresse.com/fr/cour-des-comptespresidentielle-25-juin-date-butoir-du-depot-des-comptes-de-campagne',
        'L''union',
        'Business Intelligence',
        '2025-06-20T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca6b1dda-6085-40c7-89d2-d52ad0fc7f8f',
        'Gabon : Leconi privée d’eau après un acte de vandalisme',
        'Une personne a volé le câble électrique qui alimente la prise d’eau de Leconi, ce qui a coupé l’eau potable dans la ville, provoquant une crise.',
        'https://agpgabon.ga/gabon-leconi-privee-deau-apres-un-acte-de-vandalisme/',
        'AGP',
        'Business Intelligence',
        '2025-06-20T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38b212dd-6067-4cd3-88d6-346821a11b44',
        'Gabon/Réforme institutionnelle : Alexis Boutamba Mbina soumet un plan pour renforcer la Médiature',
        'Le Médiateur de la République a présenté au ministre de la Réforme un projet de réforme visant à renforcer la Médiature en augmentant son budget, en améliorant sa présence dans toutes les provinces et en renforçant ses ressources humaines.',
        'https://agpgabon.ga/gabon-reforme-institutionnelle-alexis-boutamba-mbina-soumet-un-plan-pour-renforcer-la-mediature/',
        'AGP',
        'Business Intelligence',
        '2025-06-20T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '66b12485-fbe4-4065-a536-0846bf4653b8',
        'Le Gabon et Huawei : vers une révolution numérique',
        'Le Gabon projette de moderniser ses infrastructures numériques grâce à un partenariat avec Huawei, visant à renforcer la connectivité et à favoriser la transformation digitale du pays.',
        'https://gabonactu.com/blog/2025/06/20/le-gabon-et-huawei-vers-une-revolution-numerique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f02a94d-b3a2-4605-8e32-44028843edfa',
        'Le Chef de l’État renforce la coopération numérique avec Huawei',
        'Le chef de l''État a renforcé la coopération numérique avec Huawei pour développer les infrastructures technologiques et digitales dans le pays.',
        'https://kongossanews.info/le-chef-de-letat-renforce-la-cooperation-numerique-avec-huawei/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '174d0fe8-1a14-4737-8eb8-6bef350efe86',
        'Publié le 20 / 06 / 2025',
        'L''article explique que la réforme des partis politiques doit suivre des critères stricts pour renforcer la démocratie et la transparence.',
        'https://union.sonapresse.com/fr/reformes-des-partis-politiques-des-criteres-contraignants',
        'L''union',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '59ec56fa-6b9d-4aba-9bdc-3cc9f14bb7f4',
        'Publié le 20 / 06 / 2025',
        'La date limite pour le dépôt des comptes de campagne présidentielle est fixée au 25 juin.',
        'https://union.sonapresse.com/fr/cour-des-comptespresidentielle-25-juin-date-butoir-du-depot-des-comptes-de-campagne',
        'L''union',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e426f2a-f541-4211-bda7-1e21e2affea0',
        'Football / Ndambo d’or : Aubameyang sacré meilleur joueur gabonais de l’étranger',
        'Pierre-Emerick Aubameyang a été élu meilleur joueur gabonais évoluant à l’étranger en 2025, grâce à sa belle saison en Saudi Pro League où il a marqué 17 buts.',
        'https://agpgabon.ga/football-ndambo-dor-aubameyang-sacre-meilleur-joueur-gabonais-de-letranger/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9146176b-3ea0-4f94-a578-648c336dada1',
        'Toutes les nominations du Conseil des ministres du 20 juin 2025',
        'Le Conseil des ministres du 20 juin 2025 a procédé à plusieurs nominations de nouveaux membres dans le gouvernement gabonais, selon un communiqué officiel.',
        'https://directinfosgabon.com/toutes-les-nominations-du-conseil-des-ministres-du-20-juin-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33797f9b-e453-42ab-bb1c-a9fb97c4b5bb',
        'Les ministres gabonais ne voyageront plus en 1ère classe',
        'Les ministres gabonais ne voyageront plus en première classe afin de réduire les dépenses publiques et promouvoir une gestion plus responsable des ressources.',
        'https://gabonactu.com/blog/2025/06/21/les-ministres-gabonais-ne-voyageront-plus-en-1ere-classe/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '754cb962-d764-46a3-b93c-56411cdd8ff7',
        'SOGATRA et Trans Urb’ : bientôt la fin du « ngori » !',
        'L''État gabonais prévoit de mettre fin au système informel de transport appelé « ngori » en développant des services de transport modernes et organisés.',
        'https://gabonactu.com/blog/2025/06/21/sogatra-et-trans-urb-bientot-la-fin-du-ngori/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3c1d3b61-cd45-4037-96b9-87ebfa2a11ee',
        'Communiqué Final du Conseil des Ministres du 20 juin 2025',
        'Le conseil des ministres a examiné plusieurs projets et mesures pour le développement du pays, sous la direction du président Oligui Nguema, lors de sa réunion du 20 juin 2025.',
        'https://gabonactu.com/blog/2025/06/21/communique-final-du-conseil-des-ministres-du-20-juin-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ce1d255-222e-4356-8970-c52da7ec0941',
        'Gabon/Football : Derrick Assoumou Obame sacré Ndambo d’or 2025',
        'Derrick Assoumou Obame, jeune milieu de terrain de 19 ans, a remporté le prix du Ndambo d’or 2025 en tant que meilleur joueur de la saison de football au Gabon, tout en étant aussi élu meilleur espoir.',
        'https://agpgabon.ga/gabon-football-derrick-assoumou-obame-sacre-ndambo-dor-2025/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '19f92c03-a45e-436a-80dd-e5055fc9d8ad',
        'Construction d’une ville interconnectée & mise en place d’un Centre national de données, ces ambitions de Huawei pour le Gabon',
        'Huawei prévoit de déployer au Gabon un centre de données national pour renforcer la connectivité, la digitalisation et soutenir le développement technologique du pays.',
        'https://vxp241.com/2025/06/21/construction-dune-ville-interconnectee-mise-en-place-dun-centre-national-de-donnees-ces-ambitions-de-huawei-pour-le-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b9d24ec-ad77-4791-8210-d151e98b1247',
        'Gabon /ANBG: NDJAMBOU évincé, Désirée MBOUMBA LASSY prend les commandes',
        'Le gouvernement gabonais a remplacé le directeur de l''Agence nationale des bourses par une nouvelle responsable, dans le cadre potentiellement d''une réforme du financement des études.',
        'https://vxp241.com/2025/06/21/gabon-anbg-ndjambou-evince-desiree-mboumba-lassy-prend-les-commandes/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e69c0d06-1eb2-4c0e-8579-db70e4802fe6',
        'Transport urbain : Fin annoncée de la gratuité pour Trans’Urb et SOGATRA',
        'Le gouvernement gabonais prévoit de mettre fin progressivement à la gratuité du transport urbain, instaurée pendant la pandémie de Covid-19, en raison de ses impacts financiers sur les entreprises Trans’Urb et SOGATRA.',
        'https://directinfosgabon.com/transport-urbain-fin-annoncee-de-la-gratuite-pour-transurb-et-sogatra/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e23e304-4bb8-406e-a115-5ee66a4407da',
        'Pizolub proche de la faillite avec une dette de 13 milliards de FCFA',
        'L''entreprise gabonaise Pizolub, spécialisée dans les lubrifiants, fait face à de graves difficultés financières avec une dette de 13 milliards de FCFA, ce qui la rapproche de la faillite.',
        'https://directinfosgabon.com/pizolub-proche-de-la-faillite-avec-une-dette-de-13-milliards-fcfa/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8603b741-28a3-4289-a99a-de6e21abd4a3',
        'Missions à l’étranger : Les DG voyageront désormais en classe « Eco »',
        'À partir du 20 juin 2025, les responsables administratifs et membres du gouvernement en mission officielle à l’étranger devront voyager en classe économique, selon une décision du Conseil des ministres.',
        'https://directinfosgabon.com/missions-a-letranger-les-dg-voyageront-desormais-en-classe-eco/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4388a535-9415-4777-9709-f306947c76ce',
        'Gabon/Déplacements officiels : l’État renforce la discipline budgétaire',
        'Le gouvernement gabonais a instauré de nouvelles règles pour limiter les dépenses liées aux déplacements officiels à l’étranger, en imposant notamment la classe économique pour la plupart des agents et en réservant la classe affaires aux membres du gouvernement et la première classe aux ministres d’État.',
        'https://agpgabon.ga/gabon-deplacements-officiels-letat-renforce-la-discipline-budgetaire/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '46256dc4-a8f4-41d4-ae3d-bf794097e356',
        'Étienne Massard Kabinda Makaga : De puissant ministre à simple conseiller technique',
        'L’ancien ministre Étienne Massard Kabinda Makaga, qui occupait des postes importants comme celui de secrétaire général de la présidence, voit aujourd’hui sa position diminuer en étant nommé simple conseiller technique, marquant une baisse de son influence politique.',
        'https://directinfosgabon.com/etienne-massard-kabinda-makaga-de-puissant-ministre-a-simple-conseiller-technique/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4636d02a-0d9c-4c02-8ed9-85561a94face',
        'Voyages officiels : le Gabon revoit à la baisse les privilèges des membres du gouvernement',
        'Le gouvernement gabonais a décidé de réduire les privilèges liés aux voyages officiels en limitant notamment le classement des avions pour les membres du gouvernement, afin de respecter une gestion budgétaire plus rigoureuse.',
        'https://www.gabonreview.com/voyages-officiels-le-gabon-revoit-a-la-baisse-les-privileges-des-membres-du-gouvernement/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40900000-7efc-4fc7-82f0-a227028cf203',
        'Le Gabon s’invite à la conférence mondiale sur les sciences psychédéliques à Denver',
        'Pour la première fois, une délégation gabonaise a représenté les communautés traditionnelles lors d’une grande conférence mondiale sur les psychédéliques, mettant en avant l’importance de la plante sacrée iboga dans la culture locale et sa reconnaissance scientifique.',
        'https://www.gabonreview.com/le-gabon-sinvite-a-la-conference-mondiale-sur-les-sciences-psychedeliques-a-denver/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '224ba001-3b89-4283-b416-f2995f78e35d',
        'Communiqué final du Conseil des Ministres du 20 juin 2025',
        'Le Conseil des Ministres s''est réuni le 20 juin 2025 sous la présidence du Président de la République, qui a rappelé l''importance pour le gouvernement de rester concentré sur la réalisation de ses objectifs de transformation.',
        'https://www.gabonews.com/fr/actus/conseil-des-ministres/article/communique-final-du-conseil-des-ministres-du-20-20956',
        'Gabonews',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6bc23f81-efe6-4c00-8dd9-e0503a7ae0db',
        'Gabon/Journée de l’artisanat : une exposition clôturée à Koulamoutou',
        'Une exposition de produits artisanaux s’est tenue pendant trois jours à Koulamoutou, réunissant une vingtaine d’artisans pour présenter leurs savoir-faire dans divers domaines comme la vannerie, la cuisine et la peinture, à l''occasion de la Journée internationale de l''artisanat.',
        'https://agpgabon.ga/gabon-journee-de-lartisanat-une-exposition-cloturee-a-koulamoutou/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '73c1beee-f93b-4551-8d01-1b5eeaf6bc6d',
        'Gabon : un plan d’urgence adopté pour la gestion des déchets postdéguerpissement',
        'Le gouvernement gabonais a adopté un plan d''urgence pour gérer les déchets issus des opérations de déguerpissement dans le quartier Plaine Orety, afin d''assurer une gestion conforme aux normes sanitaires et environnementales.',
        'https://agpgabon.ga/gabon-un-plan-durgence-adopte-pour-la-gestion-des-dechets-postdeguerpissement/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '37c5b125-4cf5-4ca1-b631-1e10fd20846b',
        'Football/CMC : fin de parcours des Los Angeles FC et Denis Bouanga',
        'Le Los Angeles FC, avec le joueur gabonais Denis Bouanga, a perdu son match contre l’Espérance de Tunis (0-1) lors du Mondial des clubs, ce qui met fin à leur parcours dans la compétition.',
        'https://agpgabon.ga/football-cmc-fin-de-parcours-des-los-angeles-fc-et-denis-bouanga/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95f0524c-3192-4582-81c0-6de4ecbfad1b',
        'Maurel & Prom Gabon honore et congratule ses collaborateurs',
        'Maurel & Prom Gabon a organisé une cérémonie pour féliciter et honorer ses collaborateurs lors d’une soirée festive, renouant avec cette tradition après quatre ans.',
        'https://gabonactu.com/blog/2025/06/21/maurel-prom-gabon-honore-et-congratule-ses-collaborateurs/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e3742877-3f7f-461e-9f81-e17e4042c2eb',
        'Gabon : Etienne Massard nommé conseiller technique aux Eaux et forêts',
        'Étienne Massard a été nommé conseiller technique aux Eaux et Forêts au Gabon, en charge de soutenir la gestion durable des ressources forestières et hydrauliques du pays.',
        'https://gabonmediatime.com/gabon-etienne-massard-nomme-conseiller-technique-aux-eaux-et-forets/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '994a06c5-8989-4e0f-9246-e0aa22379611',
        'ANBG : Le Pr. Ruphin Ndjambou évincé suite à une pétition d’étudiants ?',
        'Le ministre de l’Enseignement supérieur a rencontré les étudiants suite à une pétition, afin de clarifier les revendications et discuter des solutions pour améliorer leur situation.',
        'https://gabonmediatime.com/anbg-le-pr-ruphin-ndjambou-evince-suite-a-une-petition-detudiants/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fd31b90-e76d-4a2f-a5e5-299a4724fa60',
        'Gabon : suspension pour 6 mois des droits et taxes à l’importation des produits de première nécessité !',
        'Le gouvernement gabonais suspend pour six mois l''application des droits et taxes à l''importation des produits de première nécessité afin de faciliter leur accès dans le pays.',
        'https://gabonmediatime.com/gabon-suspension-pour-6-mois-des-droits-et-taxes-a-limportation-des-produits-de-premiere-necessite/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3850b84-d5e3-4bfa-9c2b-a4d280a07a8e',
        'Franceville : notables et chefs de quartiers honorés par leur fils Luther Steeven Abouna Yangui',
        'Luther Steeven Abouna Yangui, directeur général de la comptabilité publique et du Trésor, a honoré plusieurs notables et chefs de quartiers de Franceville, en reconnaissance de leur engagement dans la communauté.',
        'https://gabonactu.com/blog/2025/06/21/franceville-notables-et-chefs-de-quartiers-honores-par-leur-fils-luther-steeven-abouna-yangui/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89fb7459-de72-48ac-99e0-d76e67b6e924',
        'Gabon : Etienne Massard nommé conseiller technique aux Eaux et forêts',
        'Etienne Massard a été nommé conseiller technique aux Eaux et Forêts au Gabon, renforçant ainsi la gouvernance et la gestion durable des ressources naturelles dans le pays.',
        'https://gabonmediatime.com/gabon-etienne-massard-nomme-conseiller-technique-aux-eaux-et-forets/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '29095acf-50dc-4421-9ff8-057896e6303b',
        'ANBG : Le Pr. Ruphin Ndjambou évincé suite à une pétition d’étudiants ?',
        'Le Premier ministre, Ruphain N''djambou, a rencontré des étudiants à la suite d''une pétition pour discuter de leurs préoccupations.',
        'https://gabonmediatime.com/anbg-le-pr-ruphin-ndjambou-evince-suite-a-une-petition-detudiants/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c06217a-e59b-43b9-a1eb-f77a3ccc5cb4',
        'Gabon : suspension pour 6 mois des droits et taxes à l’importation des produits de première nécessité !',
        'Le gouvernement gabonais a décidé de suspendre pendant six mois les droits et taxes à l''importation sur certains produits de première nécessité afin de faciliter leur accès et réduire leur coût pour la population.',
        'https://gabonmediatime.com/gabon-suspension-pour-6-mois-des-droits-et-taxes-a-limportation-des-produits-de-premiere-necessite/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '114476af-6c38-4395-9bde-f378ba1555c6',
        'Libreville en chantier : le Président Oligui Nguema inspecte les avancées du programme d’urbanisation',
        'Le président Oligui Nguema a effectué une visite pour vérifier l''avancement du programme d''urbanisation à Libreville, visant à améliorer le développement et l''aménagement de la ville.',
        'https://kongossanews.info/libreville-en-chantier-le-president-oligui-nguema-inspecte-les-avancees-du-programme-durbanisation/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e87d0b7c-ec1b-41fe-baa8-ce2ef094b145',
        'Transport urbain/Gabon : vers une réforme audacieuse pour sortir de l’impasse',
        'Gabon envisage une réforme ambitieuse du transport urbain pour sortir de l''impasse, en modernisant le secteur et en améliorant la mobilité des citoyens.',
        'https://kongossanews.info/transport-urbain-gabon-vers-une-reforme-audacieuse-pour-sortir-de-limpasse/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8aa34570-59a5-4806-8def-27354006c174',
        'Classe économique pour tous : le gouvernement gabonais serre la ceinture',
        'Le gouvernement gabonais met en place des mesures d’austérité pour réduire les dépenses et maîtriser la situation économique du pays.',
        'https://kongossanews.info/classe-economique-pour-tous-le-gouvernement-gabonais-serre-la-ceinture/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6877a94-2f34-4edc-a604-c6921b5a97ef',
        'Publié le 21 / 06 / 2025',
        'Le gouvernement ivoirien a renforcé les règles concernant les déplacements officiels, en imposant un encadrement strict pour mieux contrôler les dépenses liées à ces missions.',
        'https://union.sonapresse.com/fr/disciplines-budgetaires-renforcees-le-gouvernement-encadre-stricte-ment-les-deplacements-officiels',
        'L''union',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'afcfcb97-0d7c-4c12-bfba-1a5189db8dc0',
        'Publié le 21 / 06 / 2025',
        'Le gouvernement gabonais suspend temporairement les droits et taxes à l''importation sur certains produits afin de faciliter leur accès et soutenir l’économie locale.',
        'https://union.sonapresse.com/fr/gabon-le-gouvernement-suspend-les-droits-et-les-taxes-limportation-sur-certains-produits',
        'L''union',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb71741c-83fc-4983-82be-138f626b9170',
        'Publié le 21 / 06 / 2025',
        'Le passage au paiement dans les transports urbains de Dakar et de Saint-Louis va mettre fin à la gratuité des lignes pour certains usagers, notamment les scolaires et les populations vulnérables.',
        'https://union.sonapresse.com/fr/transport-urbain-vers-la-fin-de-la-gratuite-chez-transurb-et-sogatra',
        'L''union',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db8a444b-cccc-41c3-a772-3309d8875ded',
        'Gabon : Oligui Nguema lance son parti politique le 28 juin',
        'Le président gabonais Brice Clotaire Oligui Nguema va lancer officiellement son parti politique le 28 juin 2025 à Libreville, marquant la naissance de son mouvement.',
        'https://agpgabon.ga/gabon-oligui-nguema-lance-son-parti-politique-le-28-juin/',
        'AGP',
        'Business Intelligence',
        '2025-06-21T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75dda2f7-bc39-4b3e-859a-66c4baade585',
        'Libreville en chantier : le Président Oligui Nguema inspecte les avancées du programme d’urbanisation',
        'Le président Oligui Nguema a inspecté l’avancement du programme de développement urbain à Libreville, soulignant l’importance des projets pour moderniser la capitale.',
        'https://kongossanews.info/libreville-en-chantier-le-president-oligui-nguema-inspecte-les-avancees-du-programme-durbanisation/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d651ac6-610c-4431-85a5-4df2967d2aaf',
        'Transport urbain/Gabon : vers une réforme audacieuse pour sortir de l’impasse',
        'Le gouvernement gabonais envisage une réforme audacieuse du transport urbain pour sortir de l’impasse, visant à moderniser et améliorer le service pour les usagers.',
        'https://kongossanews.info/transport-urbain-gabon-vers-une-reforme-audacieuse-pour-sortir-de-limpasse/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '73bf0ad1-e610-4dd4-8bac-52c9e4bd95ad',
        'Classe économique pour tous : le gouvernement gabonais serre la ceinture',
        'Le gouvernement gabonais prévoit de réduire ses dépenses pour faire face à des difficultés économiques, en imposant des mesures d''austérité destinées à limiter la consommation et à suivre une politique budgétaire rigoureuse.',
        'https://kongossanews.info/classe-economique-pour-tous-le-gouvernement-gabonais-serre-la-ceinture/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0f1b333d-d0f1-40ec-b92c-dc9935a3b946',
        'Publié le 21 / 06 / 2025',
        'Le gouvernement ivoirien a renforcé la gestion des dépenses publiques en limitant strictement les déplacements officiels afin de maîtriser le budget.',
        'https://union.sonapresse.com/fr/disciplines-budgetaires-renforcees-le-gouvernement-encadre-stricte-ment-les-deplacements-officiels',
        'L''union',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b343831-93a7-4d48-b56e-fcf08ca311db',
        'Publié le 21 / 06 / 2025',
        'Le gouvernement gabonais a décidé de suspendre temporairement les droits et taxes à l''importation sur certains produits pour favoriser leur accessibilité.',
        'https://union.sonapresse.com/fr/gabon-le-gouvernement-suspend-les-droits-et-les-taxes-limportation-sur-certains-produits',
        'L''union',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c11ef2d-aa64-41bb-b787-ac568e3d47ef',
        'Publié le 21 / 06 / 2025',
        'Le gouvernement prévoit de mettre fin à la gratuité des transports urbains pour financer l''amélioration des services de Transurb et Sogatra.',
        'https://union.sonapresse.com/fr/transport-urbain-vers-la-fin-de-la-gratuite-chez-transurb-et-sogatra',
        'L''union',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63b427e8-59d8-49d8-bcdc-ecf037eb3155',
        'Taekwondo/Tournoi   Baby Champions : 300 combats au menu de la première journée',
        'La première journée du tournoi Baby Champions à Libreville a regroupé plus de 300 combats de taekwondo, mettant en valeur la passion et le respect des jeunes participants issus de différentes régions.',
        'https://agpgabon.ga/taekwondo-tournoi-baby-champions-300-combats-au-menu-de-la-premiere-journee/',
        'AGP',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2404bfef-3088-498f-8192-b33a468d1d67',
        'Oligui Nguéma dévoile son parti politique le 28 juin à Libreville',
        'Brice Clotaire Oligui Nguema, président du Gabon, dévoilera officiellement son nouveau parti politique, le Rassemblement des bâtisseurs (RDB), le 28 juin à Libreville.',
        'https://gabonactu.com/blog/2025/06/22/oligui-nguema-devoile-son-parti-politique-le-28-juin-a-libreville/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-22T00:00:00.000Z',
        '2025-09-15T23:06:12.459Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

