-- Batch 3 - Section 13/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '12ae97b5-c287-49ed-ba12-9223f0d69054',
        'Hausse des indemnités des chefs de quartier : le gouvernement acte une revalorisation attendue',
        'Les indemnités des chefs de quartier dans la province de l’Estuaire, notamment dans la commune de Libreville, augmentent de 100 000 à 130 000 FCFA, reflétant une politique de revalorisation décidée par le gouvernement[1]. Cette mesure vise à améliorer la rémunération des auxiliaires de commandement sur le territoire.',
        'https://www.gabonreview.com/hausse-des-indemnites-des-chefs-de-quartier-le-gouvernement-acte-une-revalorisation-attendue/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9757f17b-6acf-4312-ac46-639d35fc2f1c',
        '57e conférence annuelle du RHF: une clôture sur fond d’engagement',
        'La 57e Conférence annuelle du Réseau Habitat et Francophonie, tenue à Libreville, a rassemblé des acteurs de 22 pays francophones pour discuter et engager des solutions concrètes visant à améliorer le financement et l''accès au logement abordable, notamment par la signature d''un protocole d''accord entre promoteurs immobiliers d''Afrique centrale et de l''Ouest. Cette rencontre a souligné l''urgence collective d''agir face au déficit important de logements dans plusieurs régions francophones.',
        'https://vxp241.com/2025/05/17/57e-conference-annuelle-du-rhf-une-cloture-sur-fond-dengagement/',
        'Vox Populi',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7dcd77b1-5145-458c-9aea-0059e362f803',
        'Le couple presidentiel attendu à la messe inaugurale du pontificat du Pape Léon XIV',
        'Le couple présidentiel du Gabon a participé à une messe religieuse, marquant leur engagement spirituel et leur soutien aux communautés religieuses du pays. Cette participation reflète leur volonté de rassembler et de soutenir les Gabonais dans une atmosphère de ferveur et de recueillement.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-couple-presidentiel-attendu-a-la-messe',
        'Gabonews',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0707154-4654-4afd-906e-addc4b7c489f',
        'Gabon : le président Oligui Nguema prendra part ce dimanche à la première messe du pape Léon XIV',
        'Le président gabonais Brice Clotaire Oligui Nguema participera le dimanche 18 mai 2025 à Rome à la messe inaugurale du pontificat du pape Léon XIV, un événement marquant pour l''Église catholique réunissant de nombreux chefs d''État et représentants internationaux. Cette présence souligne les liens historiques entre le Gabon et le Saint-Siège ainsi que la volonté du pays d''affirmer sa place dans les rencontres internationales à caractère spirituel et diplomatique[1].',
        'https://agpgabon.ga/2025/05/17/gabon-le-president-oligui-nguema-prendra-part-ce-dimanche-a-la-premiere-messe-du-pape-leon-xiv/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fe6b246-caa1-498c-a585-6a36d467870b',
        'Oligui Nguema à la messe inaugurale du pontificat du Pape Léon XIV ce dimanche au Vatican',
        'Le président gabonais, Brice Clotaire Oligui Nguema, participera dimanche 18 mai 2025 à la messe inaugurale du pontificat du pape Léon XIV au Vatican. Cette cérémonie symbolise une occasion importante pour le Gabon d''affirmer son rôle dans les grandes rencontres internationales à caractère spirituel et diplomatique.',
        'https://gabonactu.com/blog/2025/05/17/oligui-nguema-a-la-messe-inaugurale-du-pontificat-du-pape-leon-xiv-ce-dimanche-au-vatican/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0cea9ea1-ffe1-41dd-89f1-1af3a53665f1',
        'Gabon : le Président Oligui Nguema incarne-t-il une justice humaine face à l’héritage brutal du régime Bongo ?',
        'Le président Oligui Nguema, à la tête du Gabon depuis le renversement de la dynastie Bongo, est confronté à la tâche de rétablir la justice et la stabilité dans un pays marqué par des décennies de gouvernance autoritaire. Face à l''héritage complexe du régime Bongo, il doit équilibrer justice et réconciliation nationale.',
        'https://gabonactu.com/blog/2025/05/17/gabon-le-president-oligui-nguema-incarne-t-il-une-justice-humaine-face-a-lheritage-brutal-du-regime-bongo/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '82c1d137-e3fa-43ce-964a-b8454be5ded0',
        'Port-Gentil : le voleur  présumé d’écrans plasma  en détention préventive',
        'Lud Vignon Mounzéo, un jeune gabonais de 23 ans, a été arrêté à Port-Gentil pour avoir volé plusieurs écrans plasma et revendu ces biens en ligne ; il est en détention provisoire en attendant son procès et a déjà un passé judiciaire pour détention de drogue. Son arrestation a été facilitée par un proche qui a collaboré avec la police[1][3].',
        'https://gabonactu.com/blog/2025/05/17/port-gentil-le-voleur-presume-decrans-plasma-en-detention-preventive/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '13179d3f-bb7f-4731-ab17-fbf40996d4c2',
        'National-Foot 2 : le Stade Migovéen champion du Gabon',
        'Le Stade Migovéen, basé à Lambaréné au Gabon, a remporté le championnat du Gabon en deuxième division, ce qui constitue une réalisation significative pour l''équipe. Cette victoire reflète le succès de l''équipe dans le football gabonais après avoir été reléguée en deuxième division.',
        'https://agpgabon.ga/2025/05/17/national-foot-2-le-stade-migoveen-champion-du-gabon/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '49e6f831-7b47-497b-998a-0018ebb68ab1',
        'Gabon : prestation de serment des nouveaux responsables du Contrôle général d’Etat',
        'Les nouveaux responsables du Contrôle Général de l''État au Gabon ont prêté serment, renforçant ainsi la structure institutionnelle chargée de veiller à la gestion efficace et transparente des ressources publiques. Cette cérémonie fait partie des efforts visant à renforcer la bonne gouvernance et l''intégrité dans l''administration publique gabonaise.',
        'https://agpgabon.ga/2025/05/17/gabon-prestation-de-serment-des-nouveaux-responsables-du-controle-general-detat/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62ea1a46-f4f9-4313-9bdb-c2fa9668bc8f',
        'Journée internationale de l’infirmier à EM Gabon-Université : des ateliers pour améliorer la qualité des soins et la sécurité des patients',
        'À l''occasion de la Journée Internationale des Infirmières, l''Université de Gabon a organisé des ateliers pour améliorer la qualité des soins et la sécurité des patients. Ces ateliers visent à renforcer l''excellence professionnelle des infirmières, essentielles à la santé publique.',
        'https://gabonactu.com/blog/2025/05/17/journee-internationale-de-linfirmier-a-em-gabon-universite-des-ateliers-pour-ameliorer-la-qualite-des-soins-et-la-securite-des-patients/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.440Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fb8b8c8-808f-4450-a4db-6b78eb2d73fb',
        'Escroquerie : des voyous usurpent l’identité du Dr Eric Baye pour promouvoir un faux traitement contre le diabète',
        'Des escrocs ont usurpé l''identité du Dr. Eric Baye pour promouvoir un faux traitement contre le diabète. Cette escroquerie utilise la réputation du Dr. Baye pour tromper les victimes potentiels.',
        'https://gabonactu.com/blog/2025/05/17/escroquerie-des-voyous-usurpent-lidentite-du-dr-eric-baye-pour-promouvoir-un-faux-traitement-contre-le-diabete/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '84caee11-aa21-42c2-be20-f8b896e90036',
        'National Foot 2/Agression du corps arbitral : la direction d’Oyem AC annonce l’ouverture d’une enquête en interne',
        'La direction de Doyen AC a annoncé l''ouverture d''une enquête interne suite à une agression du corps arbitral lors d''un match de football. Cette enquête vise à établir les faits et à prendre des mesures appropriées pour éviter de tels incidents à l''avenir.',
        'https://agpgabon.ga/2025/05/17/national-foot-2-agression-du-corps-arbitral-la-direction-doyem-ac-annonce-louverture-dune-enquete-en-interne/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aeaf3570-670b-4ffb-861a-546da85287c6',
        'Gabon/Démission collective au PDG : 8 cadres du Woleu-Ntem exclus',
        'Plusieurs cadres du Parti Démocratique Gabonais (PDG) dans la province du Woleu-Ntem ont annoncé une démission collective, démarche vivement désavouée par d’autres membres qui dénoncent un acte non concerté et contraire au règlement intérieur du parti, lequel exige des démissions individuelles. Cette situation reflète des tensions et divisions internes au sein du PDG dans un contexte politique marqué par une recomposition du pouvoir au Gabon[1][2][5][6].',
        'https://agpgabon.ga/2025/05/17/gabon-demission-collective-au-pdg-8-cadres-du-woleu-ntem-exclus/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'daa9a589-6a5c-488b-b2b5-f3518b5fbbce',
        'Gabon/Auxiliaire du commandement : Augmentation des endemnités allouées aux chefs de quartiers',
        'Les indemnités allouées aux chefs de quartiers dans le cadre de l''auxiliaire du commandement au Gabon ont été augmentées. Cette décision a pour but d''améliorer les conditions de vie des personnels militaires en leur offrant des compensations financières supplémentaires.',
        'https://agpgabon.ga/2025/05/17/gabon-auxiliaire-du-commandement-augmentation-des-endemnites-allouees-aux-chefs-de-quartiers/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2146c621-6b87-4d8e-8ce8-052293a50ae8',
        'Barro Chambrier parle sans tabou d’Oyima ses fonctions de ministre et de PDG de BGFIBank',
        'Alexandre Barro Chambrier défend la double fonction d''Henri Claude Oyima, ministre de l''Économie et PDG de BGFIBank, en soulignant son expérience et son rôle clé, tout en estimant que la gestion privée de la banque relève des actionnaires et ne gêne pas ses responsabilités gouvernementales.',
        'https://gabonactu.com/blog/2025/05/17/barro-chambrier-parle-sans-tabou-doyima-ses-fonctions-de-ministre-et-de-pdg-de-bgfibank/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '90db0b8a-8005-470c-bc6b-a16fb757cf51',
        'Le Gabon a commémoré la première Journée nationale de commémoration des ancêtres',
        'Le Gabon a célébré pour la première fois la Journée nationale de commémoration des ancêtres, lors de laquelle le Conseil national des rites et traditions a appelé à préserver l’identité gabonaise et à défendre les traditions communes à tous les Gabonais. Cette célébration souligne l’importance du respect du patrimoine culturel et spirituel partagé par l’ensemble des citoyens, indépendamment de leurs origines. [1]',
        'https://gabonactu.com/blog/2025/05/17/le-gabon-a-commemore-la-premiere-journee-nationale-de-commemoration-des-ancetres/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '67cb757f-6ad0-4c22-b63f-ad43d439969c',
        'Drame au PK 9 : l’inertie des autorités en question après un accident mortel impliquant un grumier sans signalisation',
        'Un accident mortel s''est produit au PK 9 à Libreville, où un véhicule a percuté un grumier en panne sans signalisation, tuant le conducteur et blessant trois passagers. Cet incident met en lumière l''inaction des autorités concernant la sécurité routière, notamment en ce qui concerne la signalisation des véhicules en panne.',
        'https://gabonmediatime.com/drame-au-pk-9-linertie-des-autorites-en-question-apres-un-accident-mortel-impliquant-un-grumier-sans-signalisation/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c5ec3ef6-85d5-40a9-a15e-2c85ff590222',
        'Gabon : exfiltration de la famille Bongo, sortie peu convaincante de Barro Chambrier !',
        'L’exfiltration nocturne de la famille Bongo vers l’Angola a suscité de nombreuses réactions au Gabon, avec un silence glacial de la part du gouvernement. Le vice-président Alexandre Barro Chambrier a tardivement commenté cette affaire, mais ses explications ont été jugées peu convaincantes par l''opinion publique.',
        'https://gabonmediatime.com/gabon-exfiltration-de-la-famille-bongo-sortie-peu-convaincante-de-barro-chambrier/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2fa651bf-70e1-4ccf-aaed-87601d1fc113',
        'Gabon : fermeture jusqu’à nouvel ordre de la Cathédrale Notre-Dame de l’Assomption Sainte Marie',
        'La cathédrale Notre-Dame de l''Assomption Sainte Marie à Libreville est fermée jusqu''à nouvel ordre en raison de l''état de dégradation du plafond, qui représente un risque pour la sécurité des fidèles. Cette décision a été prise par l''Archevêché de Libreville après une concertation avec les Conseils paroissiaux.',
        'https://gabonmediatime.com/gabon-fermeture-jusqua-nouvel-ordre-de-la-cathedrale-notre-dame-de-lassomption-sainte-marie/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '752734a0-f9ea-4d7f-b0da-d8aa5efe4016',
        'Cartes grises au Gabon : un système gangrené par la corruption et l’impunité?',
        'Le système de cartes grises au Gabon est fortement affecté par la corruption et l''impunité, ce qui entraîne de nombreuses affaires controversées. Cette situation corrompt le système entier, entraînant des conséquences importantes sur l''économie et la gouvernance du pays.',
        'https://kongossanews.info/cartes-grises-au-gabon-un-systeme-gangrene-par-la-corruption-et-limpunite-2/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dcdea1f2-bfe0-4e4f-805b-bb30f93d82c0',
        'Autisme et trisomie : un pari gagnant pour l’avenir grâce au REFESEG',
        'L''article met en avant l''importance d''une prise en charge multidisciplinaire pour les enfants présentant à la fois de l''autisme et de la trisomie 21, soulignant que cette approche est cruciale pour leur développement et leur intégration sociale. Grâce à des initiatives pédagogiques adaptées, ces enfants peuvent bénéficier d''un soutien éducatif et thérapeutique qui favorise leur inclusion dans la société.',
        'https://kongossanews.info/autisme-et-trisomie-un-pari-gagnant-pour-lavenir-grace-au-refeseg/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0b60903-f65e-4a1c-a47a-6e96d5f5eb24',
        'Publié le 17 / 05 / 2025',
        'Le Parti Démocratique Gabonais a exclu Guy Patrick Obiang Ndong et Charles Mve Ellah pour défiance et insubordination. Cette décision intervient après leur absence lors d''une audition convoquée par la CCDP, suivie d''une déclaration de démission diffusée sur les réseaux sociaux, ce qui a été considéré comme une atteinte grave à l''unité du parti.',
        'https://union.sonapresse.com/fr/crise-au-sein-du-pdg-guy-patrick-obiang-ndong-et-charles-mve-ellah-exclus-pour-defiance-et',
        'L''union',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e783569b-c00c-4f27-8894-c65ba763b34e',
        'Publié le 17 / 05 / 2025',
        'Régis Immongault Tatangani, nommé ambassadeur extraordinaire et plénipotentiaire du Gabon auprès du Benelux et représentant permanent à l''Union européenne, a été reçu par le président pour recevoir ses instructions. Cette nomination vise à renforcer la diplomatie gabonaise dans un contexte de réorientation géopolitique et économique.',
        'https://union.sonapresse.com/fr/diplomatie-le-president-de-la-republique-instruit-regis-immongault-tatangani',
        'L''union',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '506a3649-5a6e-457b-9c18-548806fd0d8f',
        'Publié le 17 / 05 / 2025',
        'Sylvia Bongo et son fils Noureddin ont été libérés de la prison centrale de Gros Bouquet pour des raisons de santé. Cette décision a été prise par la première Chambre d''accusation spécialisée, en raison de leur état de santé devenu incompatible avec le milieu carcéral.',
        'https://union.sonapresse.com/fr/famille-ali-bongo-une-mise-en-liberte-pour-des-raisons-de-sante',
        'L''union',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9a1a821a-a65d-4350-ad09-b7b773bc3e38',
        'National-Foot 1/24e journée : Vautour Club battu par Mangasport (0-1)',
        'Lors de la 24e journée du Championnat National D1, le Vautour Club a été battu par Mangasport sur le score de 0 à 1. Cette victoire a permis à Mangasport de renforcer sa position de leader dans le classement.',
        'https://agpgabon.ga/2025/05/17/national-foot-1-24e-journee-vautour-club-battu-par-mangasport-0-1/',
        'AGP',
        'Business Intelligence',
        '2025-05-17T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74947a9c-2991-4495-a239-889b30da9470',
        'Décentralisation : Oligui Nguema offre un bonus de 30 000 FCFA / mois à tous les 1 065 chefs de quartier du Gabon',
        'Le président gabonais, Brice Clotaire Oligui Nguema, a décidé d''augmenter les indemnités de 30 000 FCFA par mois pour tous les chefs de quartier du Gabon, dans le cadre de la décentralisation et pour améliorer leurs conditions de vie. Cette mesure, inscrite dans la Loi de Finances rectificative 2025, vise à renforcer le rôle des collectivités locales et à redonner une dignité sociale aux agents municipaux.',
        'https://gabonactu.com/blog/2025/05/17/decentralisation-oligui-nguema-offre-un-bonus-de-30-000-fcfa-mois-a-tous-les-1-065-chefs-de-quartier-du-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9c4ba6fb-5d9c-42f0-8cb0-54333a292d14',
        'Drame au PK 9 : l’inertie des autorités en question après un accident mortel impliquant un grumier sans signalisation',
        'Un accident mortel s''est produit au PK 9 à Libreville, où un véhicule a percuté un grumier en panne sans signalisation stationné depuis la veille près d''une brigade de gendarmerie. Cet incident a souligné le laxisme des autorités responsables de la sécurité routière, mettant en lumière leur inaction face à de tels risques sur les routes gabonaises.',
        'https://gabonmediatime.com/drame-au-pk-9-linertie-des-autorites-en-question-apres-un-accident-mortel-impliquant-un-grumier-sans-signalisation/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '595d3cc6-96ee-4906-b82b-e820a52ac75a',
        'Gabon : exfiltration de la famille Bongo, sortie peu convaincante de Barro Chambrier !',
        'L''ex-président gabonais Ali Bongo et sa famille, détenus depuis le coup d''État d''août 2023, ont été libérés et transférés en Angola, après plusieurs mois de résidence surveillée et de pressions judiciaires. Leur départ intervient dans un contexte politique tendu marqué par l''arrivée au pouvoir du général Brice Oligui Nguema et la réintégration du Gabon à l''Union africaine[1][2][3][4][6].',
        'https://gabonmediatime.com/gabon-exfiltration-de-la-famille-bongo-sortie-peu-convaincante-de-barro-chambrier/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ebd554ad-65cf-4d1d-ae20-121fb9796f4b',
        'Gabon : fermeture jusqu’à nouvel ordre de la Cathédrale Notre-Dame de l’Assomption Sainte Marie',
        'La cathédrale Notre-Dame de l''Assomption Sainte Marie au Gabon a fermé ses portes jusqu''à nouvel ordre, entraînant l''annulation des célébrations religieuses. Cette fermeture temporaire a lieu dans le contexte de travaux nécessaires à l''édifice.',
        'https://gabonmediatime.com/gabon-fermeture-jusqua-nouvel-ordre-de-la-cathedrale-notre-dame-de-lassomption-sainte-marie/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0ecc3fd-a6f6-4713-acba-db26b957b290',
        'Cartes grises au Gabon : un système gangrené par la corruption et l’impunité?',
        'Le système de cartes grises au Gabon est marqué par la corruption et l''impunité, avec des responsables impliqués dans de nombreuses affaires frauduleuses autour de la production et de la gestion de ces documents. Des cas récents, comme le détournement de véhicules et la modification suspecte des données de propriété, mettent en lumière les failles du système informatique et la complicité des fonctionnaires.',
        'https://kongossanews.info/cartes-grises-au-gabon-un-systeme-gangrene-par-la-corruption-et-limpunite-2/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62038c58-0b1b-4d5e-94b8-ecfcb288ae4a',
        'Autisme et trisomie : un pari gagnant pour l’avenir grâce au REFESEG',
        'Les initiatives visant à intégrer les enfants porteurs de trisomie 21 et d''autisme dans la société sont cruciales pour leur inclusion et leur éducation. Ces efforts, souvent soutenus par des programmes éducatifs et des associations locales, permettent de briser les stéréotypes et de promouvoir un soutien adapté aux besoins spécifiques de ces enfants.',
        'https://kongossanews.info/autisme-et-trisomie-un-pari-gagnant-pour-lavenir-grace-au-refeseg/',
        'Kongossa News',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b4ae8fc2-d10f-4e6a-86b5-a9e1691ec76a',
        'Publié le 17 / 05 / 2025',
        'Guy Patrick Obiang Ndong et Charles Mve Ellah ont été exclus du Parti Démocratique Gabonais (PDG) pour défiance et insubordination, après avoir maintenu leur position malgré des appels à la révision. Cette décision vise à réaffirmer la discipline au sein du parti, en particulier à la veille de rendez-vous politiques importants.',
        'https://union.sonapresse.com/fr/crise-au-sein-du-pdg-guy-patrick-obiang-ndong-et-charles-mve-ellah-exclus-pour-defiance-et',
        'L''union',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b655a3b4-18b5-4a37-8d76-fb7d3eebacc5',
        'Publié le 17 / 05 / 2025',
        'Le président Brice Clotaire Oligui Nguema a reçu Régis Immongault Tatangani, nommé ambassadeur extraordinaire et plénipotentiaire du Gabon près le Benelux et représentant permanent auprès de l''Union européenne. Lors de cette rencontre, le chef de l''État a transmis des orientations visant à renforcer les liens politiques, économiques et militaires avec les partenaires européens.',
        'https://union.sonapresse.com/fr/diplomatie-le-president-de-la-republique-instruit-regis-immongault-tatangani',
        'L''union',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ee0d2de-000b-4a9a-939f-b5f683461797',
        'Publié le 17 / 05 / 2025',
        'Noureddin Bongo Valentin et Sylvia Bongo Ondimba ont obtenu une liberté provisoire accordée par la première Chambre d''accusation spécialisée pour des raisons médicales, leur état de santé étant jugé incompatible avec la détention en prison. Cette décision, soutenue par des certificats médicaux, a été faite après des demandes de leur avocate et avec l’absence d’opposition de l’Agence judiciaire de l’État, poursuivante dans leur dossier[3].',
        'https://union.sonapresse.com/fr/famille-ali-bongo-une-mise-en-liberte-pour-des-raisons-de-sante',
        'L''union',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41fbe7ca-f1fa-43ea-8dcd-2daed83fe328',
        'Le Réseau des femmes sénateurs du Gabon facilite l’insertion des plusieurs enfants handicapés  au sein de la Fondation Horizons nouveaux',
        'Le Réseau des femmes sénateurs du Gabon collabore avec l''ONG "Tous différents et exceptionnels" pour faciliter l''insertion d''enfants handicapés à la Fondation Horizons Nouveaux, une structure spécialisée dans la prise en charge de personnes vulnérables. Cette initiative vise à offrir aux enfants des conditions favorables pour un avenir prometteur, suivant les directives des autorités supérieures.',
        'https://gabonactu.com/blog/2025/05/18/le-reseau-des-femmes-senateurs-du-gabon-facilite-linsertion-des-plusieurs-enfants-handicapes-au-sein-de-la-fondation-horizons-nouveaux/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b823fb9-f662-49e4-83d7-d3757d6cf75c',
        'Crise des déchets à Libreville : le projet de Nkoltang otage de 6 milliards manquants',
        'Le projet de gestion des déchets à Nkoltang, destiné à résoudre la crise des déchets à Libreville, est confronté à un manque de financement de 6 milliards, ce qui compromet son achèvement. Ce projet vise à accueillir tous les déchets du Grand Libreville, mais son retard pourrait aggraver les problèmes environnementaux et sanitaires dans la région.',
        'https://www.gabonreview.com/crise-des-dechets-a-libreville-le-projet-de-nkoltang-otage-de-6-milliards-manquants/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '91d56e8f-6d3c-423a-af11-a6ad76483122',
        'Arnaque au faux traitement du diabète : le Dr Eric Baye dénonce l’usurpation de son identité',
        'Le Dr Eric Baye, un endocrinologue renommé du Gabon, dénonce l''usurpation de son identité par des escrocs qui promeuvent un faux traitement contre le diabète. Ces fraudeurs utilisent son nom pour vendre un produit non testé et non réglementé, que le Dr Baye a vivement déconseillé, soulignant les dangers de telles arnaques pour la santé publique.',
        'https://www.gabonreview.com/arnaque-au-faux-traitement-du-diabete-le-dr-eric-baye-denonce-lusurpation-de-son-identite/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6fea2ec4-3807-4595-91bf-72d6514fb31a',
        'Deux ans pour ‘normaliser’ l’eau et l’électricité : le pari choc de Barro Chambrier',
        'Alexandre Barro Chambrier, Vice-président du gouvernement gabonais, a lancé un défi pour stabiliser l''accès à l''eau et à l''électricité dans le pays en deux ans. Cet objectif vise à améliorer significativement le quotidien des populations gabonaises, souvent confrontées à des coupures répétitives et des pénuries dans ces secteurs essentiels.',
        'https://www.gabonreview.com/deux-ans-pour-normaliser-leau-et-lelectricite-le-pari-choc-de-barro-chambrier/',
        'Gabon Review',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c184169-a9d8-474c-823a-53c2c3724927',
        'Chorale « Les héritiers de la louange » : 40 ans d’évangélisation, ça se célèbre !',
        'La chorale « Les héritiers de la louange » fête ses 40 ans d''existence, fondée en 1985 à la paroisse Saint-Joseph Moukassa à Franceville. Pendant quatre décennies, elle a contribué à l''évangélisation et à la promotion de la musique chrétienne au Gabon.',
        'https://gabonactu.com/blog/2025/05/18/chorale-les-heritiers-de-la-louange-40-ans-devangelisation-ca-se-celebre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55e79b7c-632f-4055-bcd3-c0ecd63bb7ac',
        'Les rideaux tombent sur la Quinzaine de l’Europe au Gabon',
        'L''article aborde les relations entre l''Union européenne et le Gabon, soulignant leur coopération dans divers domaines tels que la transition verte, le développement économique, et l''éducation. Cependant, je n''ai pas pu accéder au contenu spécifique de l''article pour en extraire le résumé exact.',
        'https://gabonactu.com/blog/2025/05/18/les-rideaux-tombent-sur-la-quinzaine-de-leurope-au-gabon/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '423d7ae6-71da-4d7c-8e20-0f3558bb1d2a',
        'Gabon : le Président Oligui Nguema a pris part à la messe inaugurale du pontificat du pape Léon XIV',
        'Le président gabonais Brice Clotaire Oligui Nguema et son épouse Zita ont participé à la messe inaugurale du pontificat du Pape Léon XIV, qui a eu lieu dimanche dernier au Vatican. Cette visite suit leur présence aux obsèques du Pape François, décédé le 21 avril 2025[2].',
        'https://agpgabon.ga/2025/05/18/gabon-le-president-oligui-nguema-a-pris-part-a-la-messe-inaugurale-du-pontificat-du-pape-leon-xiv/',
        'AGP',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2f07dcaa-b9bd-4f8b-b6f7-1615aa5c746f',
        'Oligui Nguéma, exalté par les leaders associatifs',
        'Brice Oligui Nguema est largement acclamé par les leaders associatifs, qui voient en lui un symbole de changement après la chute de la dynastie Bongo. Il a été élu président avec une majorité écrasante, renforçant ainsi son influence politique au Gabon.',
        'https://gabonactu.com/blog/2025/05/18/oligui-nguema-exalte-par-les-leaders-associatifs/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '21c5d3d4-e08b-4d2e-810b-180b49aaf20c',
        'MITZIC : Cohésion et développement local autour de l’Alliance Patriotique',
        'À Mitzic, le Dr Marie Zoé Mfoumou a lancé un projet de développement local visant à soutenir les familles, notamment à travers des activités génératrices de revenus financées par des cotisations volontaires. Cette initiative, saluée par le Secrétaire général de l''Alliance Patriotique, Wilfrid Nguéma Mvé, vise à promouvoir la solidarité et la performance au sein de la communauté.',
        'https://gabonactu.com/blog/2025/05/18/mitzic-cohesion-et-developpement-local-autour-de-lalliance-patriotique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a81bb5b0-f0b9-4b5d-aff7-1c5563082c35',
        'SOS Chancia',
        'Chancia, une jeune femme gabonaise de 27 ans, demande de l''aide après qu''une explosion de bouteille de gaz a gravement brûlé sa famille, laissant sa fille en soins intensifs et causant la mort du chef de famille ; elle fait appel à la solidarité pour financer les soins et subvenir aux besoins essentiels.',
        'https://gabonactu.com/blog/2025/05/18/sos-chancia/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62900ed9-0c25-4dd4-9e91-f5e5df02b234',
        'Ali Bongo, Alpha Condé, Mohamed Bazoum, fortunes diverses',
        'Je n''ai pas accès à l''article spécifique de DW, mais je peux te dire que l''Afrique est le théâtre de nombreuses innovations technologiques qui transforment l''éducation. Des startups africaines, comme Mjangale et BrainShare, créent des outils éducatifs qui améliorent l''apprentissage grâce à des applications, des tablettes interactives et des plateformes de partage de cours.',
        'https://dw.com/p/4uYfB?maca=fra-RSS_fr_Flipboard-11983-xml-media',
        'Flipboard',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '93792688-c28b-421f-b177-b3e76c56a66d',
        'Sortie de prison de Sylvia et Noureddin : manifestation pacifique ce lundi devant le ministère de la Justice',
        'Sylvia et Noureddin Bongo, détenus depuis le coup d''État de 2023, ont été libérés de prison et placés en résidence surveillée avant de quitter le Gabon pour l''Angola avec l''ancien président Ali Bongo. Une manifestation pacifique a eu lieu devant le ministère de la Justice pour demander leur libération et défendre leurs droits. [1][4][5]',
        'https://gabonactu.com/blog/2025/05/18/sortie-de-prison-de-sylvia-et-noureddin-manifestation-pacifique-ce-lundi-devant-le-ministere-de-la-justice/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '87952fc5-ae73-4883-a891-226c370f031a',
        'Un mort dans un grave accident qui a plongé le tronçon Kango-Bifoun dans le noir',
        'Un accident survenu dans la nuit du 17 au 18 mai 2025 au village Gnanam, près de Kango, a causé la mort d''un enfant de 4 ans et endommagé un poteau électrique, provoquant une coupure d''électricité sur la ligne Kango-Bifoun. Les équipes techniques ont dû intervenir rapidement pour rétablir le courant, soulignant l''importance du respect des règles de sécurité routière pour prévenir de tels incidents. [1]',
        'https://gabonactu.com/blog/2025/05/18/un-mort-dans-un-grave-accident-qui-a-plonge-le-troncon-kango-bifoun-dans-le-noir/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b49bc2f-ddeb-45a2-b756-69127272e5f0',
        'Gabon/BGFIBank reporte son entrée en bourse à septembre 2025',
        'L''entrée en bourse de BGFIBank, initialement prévue avant juin 2025, est désormais reportée à septembre 2025. Cette opération, qui vise à renforcer la visibilité et la fiabilité du groupe bancaire, est attendue avec intérêt dans le contexte du développement du marché financier de la CEMAC.',
        'https://agpgabon.ga/2025/05/18/gabon-bgfibank-reporte-son-entree-en-bourse-a-septembre-2025/',
        'AGP',
        'Business Intelligence',
        '2025-05-18T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5a0a4fcc-f1ef-4758-ac01-1b899e8d8074',
        'Cathédrale Sainte Marie : Fermée jusqu’à nouvel ordre',
        'La cathédrale Sainte-Marie de Libreville est temporairement fermée pour des raisons de sécurité, principalement en raison de la détérioration de son plafond, qui représente un risque pour les fidèles. Les célébrations religieuses sont déplacées vers d''autres lieux pendant cette période.',
        'https://gabonactu.com/blog/2025/05/18/cathedrale-sainte-marie-fermee-jusqua-nouvel-ordre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-19T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5566968f-3448-427a-994b-67142730b037',
        'Total Gabon : production et chiffre d’affaires en baisse de 3% au premier trimestre 2025',
        'TotalEnergies EP Gabon a connu une baisse de 3% de son chiffre d''affaires au premier trimestre 2025, atteignant 117 millions de dollars, principalement en raison de la diminution des prix du pétrole brut. La production de pétrole a également diminué de 3% par rapport au même trimestre de l''année précédente, en raison du déclin naturel des champs pétrolifères.',
        'https://gabonactu.com/blog/2025/05/18/total-gabon-production-et-chiffre-daffaires-en-baisse-de-3-au-premier-trimestre-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-05-19T00:00:00.000Z',
        '2025-09-15T23:06:12.441Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

