-- Batch 1 - Section 8/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'c5c3d8ff-ba2b-4ef8-9f5b-3ed878bf9ffd',
        'Droits des femmes : les employées de la SEEG plaident pour le respect de la parité',
        'Les employées de la SEEG réclament le respect de la parité et une meilleure représentation féminine dans les postes de responsabilité au sein de l''entreprise.',
        'https://www.gabonreview.com/droits-des-femmes-les-employees-de-la-seeg-plaident-pour-le-respect-de-la-parite/',
        'Gabon Review',
        'Numérique / Digital, Business Femme, Services',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f58f5fc-2539-497e-85bd-97a7f0f6d3b0',
        'BW Energy : L’Onep déclenche la grève',
        'L’Organisation nationale des employés du pétrole (ONEP) a décidé de déclencher immédiatement une grève sur toutes les installations de BW Energy et BW Offshore au Gabon en raison du refus de la direction de satisfaire les revendications des employés.',
        'https://www.gabonreview.com/bw-energy-lonep-declenche-la-greve/',
        'Gabon Review',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.288Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d722eff-d2ca-4132-b3d7-7769a51a26ad',
        'Le Rassemblement pour la patrie et la modernité (RPM) s’active à Bakoumba',
        'Le Rassemblement pour la Patrie et la Modernité (RPM) a organisé une rencontre citoyenne à Bakoumba pour préparer son congrès extraordinaire du 15 mars et réaffirmer son soutien au candidat présidentiel Brice Clotaire Oligui Nguema.',
        'https://www.gabonews.com/fr/actus/politique/article/rassemblement-pour-la-patrie-et-la-modernite-rpm',
        'Gabonews',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.289Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5d622939-0f50-4ccb-83d2-246d50b3366f',
        'Afrijet/Fly Gabon ouvre officiellement sa desserte sur Bangui en RCA',
        'Afrijet/Fly Gabon a officiellement lancé sa nouvelle desserte aérienne vers Bangui, en République centrafricaine, avec des vols hebdomadaires initialement tous les mercredis et une augmentation à trois rotations hebdomadaires dès avril 2025.',
        'https://directinfosgabon.com/afrijet-fly-gabon-ouvre-officiellement-sa-desserte-sur-bangui-en-rca/',
        'Direct infos Gabon',
        'Tourisme, Services',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.289Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3db7d752-7a0a-4d23-91bc-9b364a1b95ea',
        'PLC : Anges Kevin Nzigou démissionne !',
        'Anges Kevin Nzigou, secrétaire exécutif du Parti pour le Changement au Gabon, démissionne en raison de profondes divergences internes et annonce la création d’un nouveau mouvement politique axé sur l’intégrité et le respect des principes.',
        'https://www.gabonreview.com/plc-anges-kevin-nzigou-demissionne/',
        'Gabon Review',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.289Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86e50bf9-d165-4428-ae63-4cb4f79aaf2c',
        'Le PDG réitère son pardon au peuple gabonais',
        'Le président du Parti démocratique gabonais, Blaise Louembé, a renouvelé sa demande de pardon au peuple gabonais lors de la célébration du 57e anniversaire du parti, soulignant son engagement en faveur de la réconciliation nationale et de la restauration de la confiance.',
        'https://gabonactu.com/blog/2025/03/14/le-pdg-reitere-son-pardon-au-peuple-gabonais/',
        'Gabon Actu',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.290Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '972c9688-9cac-4054-9651-0e714274ba7d',
        'Modernisation du chemin de fer : Le gouvernement et Setrag signent une nouvelle convention',
        'Le gouvernement gabonais et la société Setrag ont signé une convention pour moderniser et sécuriser le chemin de fer Transgabonais par des investissements en infrastructure et un ajustement tarifaire, renforçant ainsi les infrastructures ferroviaires du pays.',
        'https://directinfosgabon.com/modernisation-du-chemin-de-fer-le-gouvernement-et-setrag-signent-une-nouvelle-convention/',
        'Direct infos Gabon',
        'Infrastructure, Services, Finances',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.290Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd97aeee4-75d9-4554-99c1-a28fe0609e04',
        'Droit des femmes :  les femmes doivent se former pour parvenir à leur autonomisation',
        'Lors de la Journée internationale des Droits de la Femme, une conférence organisée par AUF-Gabon a souligné l’importance de la formation des femmes pour leur autonomisation et l’intégration de l’intelligence artificielle dans l’éducation afin de promouvoir une société inclusive et durable.',
        'https://www.gabonews.com/fr/actus/societe/article/droit-des-femmes-les-femmes-doivent-se-former',
        'Gabonews',
        'Éducation, Business Femme, Numérique / Digital',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.290Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d33ef97-7bea-49b7-9542-7e416f2c559a',
        'Protection des données : Brice Clotaire Oligui Nguema en conformité avec la réglementation',
        'Le général Brice Clotaire Oligui Nguema a soumis sa déclaration de conformité à l’Autorité pour la protection des données personnelles et de la vie privée afin de encadrer l’utilisation des données personnelles durant sa campagne électorale.',
        'https://www.gabonreview.com/protection-des-donnees-brice-clotaire-oligui-nguema-en-conformite-avec-la-reglementation/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.290Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3aac1c82-23f5-4de4-ba8b-1bb06cee2079',
        'COMILOG : Revalorisation des salaires et fin de la grève',
        'La Compagnie minière de l’Ogooué (COMILOG) a revalorisé les salaires de tous ses employés à partir du 1er janvier 2025, mettant fin à la grève et rétablissant un climat social apaisé au sein de l’entreprise.',
        'https://gabonactu.com/blog/2025/03/14/comilog-revalorisation-des-salaires-et-fin-de-la-greve/',
        'Gabon Actu',
        'Services, Finances, Business Femme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.290Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '428998ce-18b0-4325-a088-85b47c47c65c',
        'La Comilog prend acte de la fin du conflit et de la reprise complète des activités opérationnelles',
        'La COMILOG annonce la fin du conflit et la reprise complète de ses activités opérationnelles, instaurée une trêve sociale et revalorisé les salaires de ses employés.',
        'https://directinfosgabon.com/la-comilog-prend-acte-de-la-fin-du-conflit-et-de-la-reprise-complete-des-activites-operationnelles/',
        'Direct infos Gabon',
        'Services, Finances, Business Femme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.291Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3dee3fa-e9d4-4b01-9a04-b51350742e5c',
        'Gabon : Plus de 300 titres fonciers pour des familles gabonaises à Igoumié',
        'Le président de la Transition gabonaise, Brice Clotaire Oligui Nguema, a distribué 300 titres fonciers à des familles d''Igoumié dans le cadre du programme social « Un Gabonais, une parcelle » visant à faciliter l''accès à la propriété et le développement urbain.',
        'https://www.gabonreview.com/gabon-plus-de-300-titres-fonciers-pour-des-familles-gabonaises-a-igoumie/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.291Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4025915e-d72b-4b15-b780-0322a7a17c52',
        'Ivindo Iron : Les futurs ouvriers de la mine en partance pour l’Australie',
        'Ivindo Iron envoie une trentaine d''étudiants gabonais en Australie pour une formation professionnelle dans le secteur minier, préparant ainsi le personnel local pour l''exploitation future du gisement de fer de Bélinga.',
        'https://gabonactu.com/blog/2025/03/13/ivindo-iron-les-futurs-ouvriers-de-la-mine-en-partance-pour-laustralie/',
        'Gabon Actu',
        'Éducation, Services',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.291Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '061cebf6-e55a-4375-940f-ee6a2f9dbc2d',
        'Le Gabon en quête de 670 milliards de FCFA pour atteindre ses objectifs de financement en 2025',
        'Le Gabon ambitionne de lever 978,4 milliards de FCFA pour l’exercice budgétaire 2025, ayant déjà mobilisé 310 milliards et cherchant à obtenir 670 milliards supplémentaires par divers mécanismes de financement pour atteindre ses objectifs.',
        'https://directinfosgabon.com/le-gabon-en-quete-de-670-milliards-de-fcfa-pour-atteindre-ses-objectifs-de-financement-en-2025/',
        'Direct infos Gabon',
        'Finances, Numérique / Digital',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.291Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf6d1d1c-2f98-4450-83b4-d6fce7557942',
        'Logement : des titres fonciers pour 300 familles à Owendo A Minvoul, Brice Clotaire Oligui Nguema promet un mieux-être aux popul...',
        'Le Président de la Transition du Gabon, Général Brice Clotaire Oligui Nguema, a délivré des titres fonciers à 300 familles à Owendo dans le cadre d’un programme immobilier visant à élargir et améliorer l’accès à la propriété foncière pour les Gabonais.',
        'https://mediapostegabon.com/logement-des-titres-fonciers-pour-300-familles-a-owendo/',
        'Media Poste Gabon',
        'Services, Commerce',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.292Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '726bfa77-49a5-4edb-906e-8299e6e5d5a7',
        'Gabon : Le PDG sonne l’heure du pardon et de la réconciliation avec le peuple',
        'À l’occasion de son 57ᵉ anniversaire, le président du Parti démocratique gabonais, Blaise Louembé, a publiquement reconnu les erreurs passées et demandé pardon au peuple gabonais dans le cadre d’un processus de réconciliation et de modernisation du parti.',
        'https://www.gabonreview.com/gabon-le-pdg-sonne-lheure-du-pardon-et-de-la-reconciliation-avec-le-peuple/',
        'Gabon Review',
        'Numérique / Digital, Services, Business Femme, Éducation',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.292Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d32f795-b582-40cc-9119-d49b1a42fd2a',
        'L’UGB célèbre la Journée Internationale des Droits des Femmes',
        'Le 8 mars 2025, l’Union Gabonaise de Banque a célébré la Journée Internationale des Droits des Femmes en organisant une soirée dans plusieurs villes, honorant la contribution des femmes au développement de la banque et intégrant des éléments culturels et festifs.',
        'https://directinfosgabon.com/lugb-celebre-la-journee-internationale-des-droits-des-femmes/',
        'Direct infos Gabon',
        'Business Femme, Services, Tourisme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.292Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ed349646-609e-4647-a727-7ff9801e5fd1',
        'Gabon : Réagir annonce un congrès de clarification et de refondation',
        'Le parti politique gabonais Réagir a annoncé la tenue de son deuxième congrès ordinaire de clarification et de refondation le 15 mars 2025, visant à redynamiser le parti et renforcer son influence dans le paysage politique du Gabon.',
        'https://www.gabonreview.com/gabon-reagir-annonce-un-congres-de-clarification-et-de-refondation/',
        'Gabon Review',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.292Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9093945f-fcef-4e1d-83ad-eb4355313c73',
        'Présidentielle du 12 avril : l’ADERE réaffirme son soutien à Brice Clotaire Oligui Nguema',
        'L''Alliance démocratique et républicaine (ADERE) réaffirme son soutien indéfectible à Brice Clotaire Oligui Nguema pour l''élection présidentielle du 12 avril 2025, appelant à une mobilisation massive des citoyens gabonais.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-ladere-reaffirme-son-soutien-a-brice-clotaire-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c49d8ae1-8b4d-44c8-bdac-162e550dd28c',
        'Présidentielle 2025 : Le « Rassemblement des Bâtisseurs » ouvre ses portes aux associations',
        'Brice Clotaire Oligui Nguéma, président de la Transition et candidat à la présidentielle 2025, invite toutes les associations du Grand Libreville à adhérer à sa plateforme "Le Rassemblement des Bâtisseurs" lors d''une session d''inscription prévue le 15 mars au Palais des Sports de Libreville, avec des enregistrements supplémentaires à venir sur tout le territoire.',
        'https://www.gabonreview.com/presidentielle-2025-le-rassemblement-des-batisseurs-ouvre-ses-portes-aux-associations/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '135f8ae1-e177-47a5-bff9-88f8a2fad5ec',
        'Assises nationales sur l’emploi : un cap fixé pour l’avenir du travail au Gabon',
        'Les Assises nationales sur l’Emploi, présidées par le Premier ministre au stade d’Agondjé, ont abouti à des recommandations visant à améliorer l’employabilité des jeunes et à dynamiser le marché du travail au Gabon.',
        'https://www.gabonreview.com/assises-nationales-sur-lemploi-un-cap-fixe-pour-lavenir-du-travail-au-gabon/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services, Finances',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '64651e6d-5d71-4c71-88b9-e39705266e11',
        'Présidentielle 2025 : Anges Kevin Nzigou, le symbole du renouveau politique !',
        'Lors des élections présidentielles de 2025 au Gabon, Anges Kevin Nzigou est présenté comme le symbole du renouveau politique grâce à son engagement en faveur de la justice, de la transparence et de la mobilisation des jeunes.',
        'https://gabonmediatime.com/presidentielle-2025-anges-kevin-nzigou-le-symbole-du-renouveau-politique/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72bbdf64-beca-42cc-a382-8e3ff79cb1e7',
        'Présidentielle 2025 : Le Rassemblement des Bâtisseurs ouvre ses adhésions aux associations et syndicats',
        'Le Rassemblement des Bâtisseurs, dirigé par Brice Clotaire Oligui Nguema, ouvre officiellement ses adhésions aux associations, syndicats et ONG en vue de l''élection présidentielle de 2025.',
        'https://gabonmediatime.com/presidentielle-2025-le-rassemblement-des-batisseurs-ouvre-ses-adhesions-aux-associations-et-syndicats/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '13bd26d2-0b81-4f05-9343-4463f877ad95',
        '14 mars 2025
                                                                              Kongossanews
                        ...',
        'La troisième édition de l’Africa Political Outlook se tient à Bruxelles le 14 mars 2025 sous le thème « Nouveau Sud, Ancien Monde ».',
        'https://kongossanews.info/2025/03',
        'Kongossa News',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c350afc8-45bf-46e9-b9ba-726e6f06a60c',
        '23280 Publié le 14 / 03 / 2025 Crise au PLC : le Secrétaire exécutif Ange Kévin Nzigou claque la porte du parti  23268 Publié le...',
        'Le secrétaire exécutif Ange Kévin Nzigou démissionne du PLC en dénonçant des désaccords internes et annonce la création d’un nouveau mouvement politique.',
        'https://union.sonapresse.com/fr/crise-au-plc-le-secretaire-executif-ange-kevin-nzigou-claque-la-porte-du-parti',
        'L''Union',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.293Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c4eec5e-5583-44e1-b30d-0134c7645b96',
        'Crise au PLC : le Secrétaire exécutif Ange Kévin Nzigou claque la porte du parti  Présidentielle/CLR : un congrès pour consacrer...',
        'Le secrétaire exécutif du PLC, Ange Kevin Nzigou, démissionne en accusant le vice-président Nicolas Nguema de poursuites personnelles et annonce la création d''un nouveau mouvement politique, fragilisant ainsi le parti avant son congrès extraordinaire.',
        'https://union.sonapresse.com/fr/crise-au-plc-le-secretaire-executif-ange-kevin-nzigou-claque-la-porte-du-parti',
        'L''Union',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.294Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e5b3b968-6af1-4c5e-b0d3-17c3dc8b2c1a',
        'Au seuil de la présidentielle : Comme un retour en arrière',
        'À l’approche des élections présidentielles, l’article souligne le retour des cultes de la personnalité et des pratiques politiques régressives au Gabon, remettant en question l’état de la démocratie malgré les efforts de transition.',
        'https://www.gabonreview.com/au-seuil-de-la-presidentielle-comme-un-retour-en-arriere/',
        'Gabon Review',
        'Autres',
        '2025-03-14T00:00:00.000Z',
        '2025-09-15T23:06:12.295Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '23694996-5d5e-4d17-aae8-df408b43437e',
        'Gabon : Coris Bank International veut accompagner les PME/PMI gabonaises',
        'Le fondateur de Coris Bank International, Nassa Idrissa, a rencontré le Président de la Transition gabonaise pour présenter la vision de la banque visant à soutenir les PME/PMI gabonaises et l''entrepreneuriat local.',
        'https://gabonmediatime.com/gabon-coris-bank-international-veut-accompagner-les-pme-pmi-gabonaises/',
        'Gabon Media Time',
        'Finances, Services, Commerce',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.295Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b608d5b6-bfe5-4495-8288-1108accbd957',
        'Panthères du Gabon : une liste de 25 joueurs avec le retour d’André Poko !',
        'Le sélectionneur des Panthères du Gabon, Thierry Mouyouma, a annoncé une liste de 25 joueurs pour les éliminatoires de la Coupe du Monde 2026, incluant le retour d’André Poko.',
        'https://gabonmediatime.com/pantheres-du-gabon-une-liste-de-25-joueurs-avec-le-retour-dandre-poko/',
        'Gabon Media Time',
        'Autres',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.295Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c960c294-1ef8-4ee5-a85f-7bb74e1c2457',
        'Gabon : Anges Kevin Nzigou quitte le PLC avec armes et bagages',
        'Anges Kevin Nzigou, ancien Secrétaire exécutif du PLC, quitte le parti en dénonçant une dérive opportuniste et rejoint le Rassemblement des Bâtisseurs, entraînant plusieurs sections locales et internationales dans sa démarche de renouveau politique avant les élections présidentielles de 2025 au Gabon.',
        'https://gabonmediatime.com/gabon-anges-kevin-nzigou-quitte-le-plc-avec-armes-et-bagages/',
        'Gabon Media Time',
        'Autres',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.295Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a55bd6dc-192c-4cd9-ac2c-de11fc621f1e',
        'Fonds de soutien patriotique : les Burkinabè du Gabon mobilisent 19,1 millions de FCFA',
        'La communauté burkinabè du Gabon a mobilisé plus de 19 millions de francs CFA via le Fonds de soutien patriotique pour appuyer les efforts de reconquête du territoire un an après son lancement par le capitaine Ibrahim Traoré.',
        'https://www.gabonreview.com/fonds-de-soutien-patriotique-les-burkinabe-du-gabon-mobilisent-191-millions-de-fcfa/',
        'Gabon Review',
        'Finances, Autres',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.295Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a48d611-c6f8-45ba-8b47-3ae6b165a131',
        'Avec Ange Kevin Nzigou : le pari gagnant de Brice Clotaire Oligui Nguema',
        'La nomination d’Ange Kevin Nzigou par Brice Clotaire Oligui Nguema comme Coordinateur général du Rassemblement des Bâtisseurs symbolise un pari audacieux en faveur du leadership jeunesse et marque un tournant significatif dans la politique gabonaise.',
        'https://www.gabonews.com/fr/actus/politique/article/avec-ange-kevin-nzigou-le-pari-gagnant-de-brice',
        'Gabonews',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.296Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4b9150f3-4ec9-40b8-b43d-cd86259288db',
        'La Fédération des femmes leaders  en atelier de formation à Port-Gentil pour un meilleur engagement citoyen',
        'La Fédération des Femmes Leaders de Port-Gentil a organisé un atelier de formation visant à redéfinir le rôle des femmes dans la société et à promouvoir leur engagement citoyen et leur autonomisation.',
        'https://gabonactu.com/blog/2025/03/15/la-federation-des-femmes-leaders-en-atelier-de-formation-a-port-gentil-pour-un-meilleur-engagement-citoyen/',
        'Gabon Actu',
        'Éducation, Business Femme',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.296Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f569623-56f4-4e5c-877d-ebca2fc6342d',
        'Enseignement supérieur : SAPMESURES fait son entrée syndicale sous fond de revendications légitimes',
        'Le syndicat SAPMESURES a officiellement lancé ses activités syndicales lors de son assemblée générale, soulignant des avancées significatives et exprimant l’espoir d’améliorer les conditions de travail et de combattre les inégalités au sein du ministère de l’Enseignement Supérieur et de la Recherche Scientifique.',
        'https://www.gabonews.com/fr/actus/enseignement-superieur/article/enseignement-superieur-sapmesures-fait-son-entree',
        'Gabonews',
        'Éducation, Services, Business Femme',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.296Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '867e0e67-fb0a-4cd3-833a-0148f4bbe6a2',
        'Le groupe burkinabè Coris bank veut ouvrir une filiale au Gabon',
        'Le groupe burkinabè Coris Bank envisage d''ouvrir une filiale au Gabon dans le cadre de son expansion en Afrique centrale.',
        'https://gabonactu.com/blog/2025/03/14/le-groupe-burkinabe-coris-bank-veut-ouvrir-une-filiale-au-gabon/',
        'Gabon Actu',
        'Finances, Services',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3821ff64-83de-49d6-bdac-3bca7201b256',
        'Présidentielle 2025 : le PDG, en perte de vitesse, contraint de soutenir son propre bourreau',
        'Le Parti démocratique gabonais (PDG), longtemps dominant, ne présente aucun candidat à l''élection présidentielle de 2025, reflétant ainsi son déclin et son soutien discret à Brice Clotaire Oligui Nguema.',
        'https://gabonmediatime.com/presidentielle-2025-le-pdg-en-perte-de-vitesse-contraint-de-soutenir-son-propre-bourreau/',
        'Gabon Media Time',
        'Autres',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98f8fe9c-0696-47b1-aad7-41228a46e98a',
        'Politique : USG et MAPD fusionnent avec REAGIR Gouvernance : le PDG demande pardon au peuple gabonais Présidentielle : week-end ...',
        'L’Union Socialiste Gabonaise (USG) et le Mouvement Alternatif pour le Développement (MAPD) ont annoncé leur fusion avec REAGIR lors du congrès de cette formation politique, visant à renforcer leur influence sur la scène nationale.',
        'https://union.sonapresse.com/fr/politique-usg-et-mapd-fusionnent-avec-reagir',
        'L''Union',
        'Autres',
        '2025-03-15T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e72b7cd-d4ed-45f4-822d-c15a908367dd',
        'Gabon : Un incident à l’origine des perturbations sur une partie du réseau électrique du Grand Libreville',
        'Un incident survenu le 15 mars 2025 au poste électrique 979 à Mindoubé a provoqué des coupures d''électricité dans plusieurs quartiers du Grand Libreville, avec un rétablissement attendu en fin de soirée grâce à l''intervention rapide des équipes SEEG.',
        'https://gabonmediatime.com/gabon-un-incident-a-lorigine-des-perturbations-sur-une-partie-du-reseau-electrique-du-grand-libreville/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51da1b70-1793-44e8-90a2-18ca1524b1b0',
        'Présidentielle 2025 : l’Alliance patriotique en soutien à la candidature d’Oligui Nguema',
        'L''Alliance patriotique soutient officiellement la candidature de Brice Clotaire Oligui Nguema à la présidence gabonaise lors de son deuxième congrès extraordinaire.',
        'https://gabonmediatime.com/presidentielle-2025-lalliance-patriotique-en-soutien-a-la-candidature-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17ec2e33-ace9-4b48-a340-1ddd3d69a788',
        'Affaire Opiangah : l’Udis interpelle à nouveau Oligui Nguema',
        'L''UDIS interpelle de nouveau le président de la Transition, appelant à la libération d''Hervé Patrick Opiangah et dénonçant un acharnement judiciaire présumé.',
        'https://gabonmediatime.com/affaire-opiangah-ludis-interpelle-a-nouveau-oligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '374d8d09-a241-46bc-9022-72fb229c0659',
        'BEAC : la nouvelle gamme de pièces de monnaie en circulation en juillet 2025',
        'La Banque des États de l''Afrique centrale (BEAC) lancera une nouvelle série de pièces de monnaie en juillet 2025 pour moderniser le système monétaire et renforcer la sécurité contre la contrefaçon.',
        'https://gabonmediatime.com/beac-la-nouvelle-gamme-de-pieces-de-monnaie-en-circulation-en-juillet-2025/',
        'Gabon Media Time',
        'Numérique / Digital, Finances, Services',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a2d304d-dafa-4d4f-af3c-1f6750968cf7',
        'Ndzomoé : Bientôt des routes et un quai pour la capitale du Komo Océan',
        'Le président de la transition gabonaise, Brice Clotaire Oligui Nguema, annonce le lancement imminent de la construction de routes et d’un quai à Ndzomoé, capitale du département du Komo Océan, afin d’améliorer les infrastructures et le cadre de vie des habitants.',
        'https://gabonactu.com/blog/2025/03/16/ndzomoe-bientot-des-routes-et-un-quai-pour-la-capitale-du-komo-ocean/',
        'Gabon Actu',
        'Services, Commerce, Tourisme',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd6341271-6705-43c3-8ee9-38ac44fc0bc3',
        'Culture : le Gabon et l’Espagne renforcent leur coopération',
        'Le Gabon et l’Espagne renforcent leur coopération culturelle avec le lancement de la collection « Lumière sur le Gabon » et la signature prochaine d’une convention entre le Musée national des Arts et Culture du Gabon et le Musée du Prado.',
        'https://www.gabonreview.com/culture-le-gabon-et-lespagne-renforcent-leur-cooperation/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Tourisme',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.297Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f1802725-e6ba-48e8-ab0a-0602f93aa462',
        'Présidentielle 2025 : Ndong Sima et sa troupe choisissent Oligui Nguema',
        'À l''approche des élections présidentielles de 2025 au Gabon, l''Alliance Patriotique dirigée par Raymond Ndong Sima a choisi de soutenir Brice Clotaire Oligui Nguema comme candidat.',
        'https://www.gabonreview.com/presidentielle-2025-ndong-sima-et-sa-troupe-choisissent-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fabf9b6f-df6c-4094-9cf6-880cacd9ab3c',
        'Présidentielle 2025 : Anges Kevin Nzigou décline les objectifs du RDB',
        'Anges Kevin Nzigou, coordinateur général du Rassemblement des Bâtisseurs, a présenté les objectifs de la plateforme visant à soutenir Brice Clotaire Oligui Nguema pour une victoire assurée lors de la présidentielle gabonaise de 2025 en promouvant un État fort, inclusif et prospère.',
        'https://gabonmediatime.com/presidentielle-2025-anges-kevin-nzigou-decline-les-objectifs-du-rdb/',
        'Gabon Media Time',
        'Autres',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '86a2d099-0739-414c-b424-daea53c62f07',
        'Aux Assises nationales sur l’emploi, Foberd Gabon s’illustre et impacte',
        'Lors des Assises nationales sur l’emploi, Foberd Gabon s’est distingué en mettant en avant ses initiatives pour l’emploi des jeunes et des femmes, ainsi que ses projets de diversification et d’expansion au Gabon.',
        'https://www.gabonreview.com/aux-assises-nationales-sur-lemploi-foberd-gabon-sillustre-et-impacte/',
        'Gabon Review',
        'Numérique / Digital, Services, Business Femme, Éducation',
        '2025-03-16T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ec9b1da5-2fc9-4088-9216-4b34496869a4',
        'Port-Gentil : Andy Freddy aux arrêts pour maltraitance sur ses enfants',
        'Andy Freddy Nzue Mfene a été interpellé à Port-Gentil pour avoir maltraité ses enfants, suite à une dénonciation aux services sociaux.',
        'https://gabonmediatime.com/port-gentil-andy-freddy-aux-arrets-pour-maltraitance-sur-ses-enfants/',
        'Gabon Media Time',
        'Autres',
        '2025-03-17T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '727f25fd-d310-4a8e-b537-269af8382211',
        'Port-Gentil : «Le PDG n’est pas mort ! Il est dans l’air du temps !›› (Ferdinand Ndo Ella)',
        'Lors de la célébration différée de son 57ᵉ anniversaire à Port-Gentil, le Parti démocratique gabonais (PDG) a réaffirmé sa vitalité et annoncé sa volonté de reconquérir les espaces politiques perdus en vue des prochaines élections locales et législatives.',
        'https://www.gabonreview.com/port-gentil-le-pdg-nest-pas-mort-il-est-dans-lair-du-temps-ferdinand-ndo-ella/',
        'Gabon Review',
        'Autres',
        '2025-03-17T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a348ef3-2e06-4661-a65f-5029f2ed1dee',
        'Gabon : Syrielle Zora Kassa à pied d’œuvre pour une filière halieutique dynamique !',
        'Syrielle Zora Kassa, ministre gabonaise de la Pêche et de la Mer, a dynamisé le secteur halieutique en fournissant des équipements techniques au centre de pêche artisanale de Mayumba, favorisant ainsi une pêche durable et compétitive.',
        'https://gabonmediatime.com/gabon-syrielle-zora-kassa-a-pied-doeuvre-pour-une-filiere-halieutique-dynamique/',
        'Gabon Media Time',
        'Agriculture, Services, Éducation',
        '2025-03-17T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c425ccea-9629-4395-a9f0-fcc741f51189',
        'Gabon Espoir déploie ses structures et officialise son soutien à Oligui Nguema',
        'Le parti politique Gabon Espoir a installé ses structures de base dans l’Ogooué-Maritime et officialisé son soutien à Brice Clotaire Oligui Nguema en vue des élections présidentielles du 12 avril.',
        'https://www.gabonreview.com/gabon-espoir-deploie-ses-structures-et-officialise-son-soutien-a-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-17T00:00:00.000Z',
        '2025-09-15T23:06:12.298Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

