-- Batch 7 - Section 14/19 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '03cc3f1b-9115-4911-aa49-e2d6e12398d7',
        'Publié le 24 / 08 / 2025',
        'Une délégation béninoise doit se rendre à Libreville pour renforcer la coopération diplomatique et signer de nouveaux accords entre le Bénin et la République gabonaise.',
        'https://union.sonapresse.com/fr/diplomatie-une-delegation-beninoise-attendue-libreville',
        'L''union',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7fe673a4-3178-4ebc-b866-4c0d4e9d291a',
        'Publié le 23 / 08 / 2025',
        'Haresse Kengué figure désormais sur la liste électorale du 6e arrondissement, marquant une première victoire dans ses démarches pour participer aux élections.',
        'https://union.sonapresse.com/fr/retour-de-haresse-kengue-sur-la-liste-electorale-du-6-arrondissement-une-premiere-victoire',
        'L''union',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '67950af8-5e03-4075-bdaf-bbd7ab881344',
        'Publié le 23 / 08 / 2025',
        'Jean Rémy Yama demande la publication de la liste des candidats rejetés aux élections législatives et locales pour garantir la transparence du processus électoral.',
        'https://union.sonapresse.com/fr/legislatives-et-locales-jean-remy-yama-plaide-pour-la-publication-de-la-liste-des-rejets-avec-leurs',
        'L''union',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '242fef81-c0e6-49c0-af58-99de0510f204',
        'Immigration : l’agonie des « popos » et des « aofiens » Makouké/ rupture amiable : Olam et le déni de l’article 77 du Code du tr...',
        'L''article explique que l''afflux de migrants ivoiriens, notamment ceux qui recherchent une vie meilleure, crée des tensions et des difficultés d''intégration dans la région de la frontière entre le Ghana et la Côte d''Ivoire.',
        'https://mediapostegabon.com/immigration-lagonie-des-popos-et-des-aofiens/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '78cf99e0-faa0-4bd8-9355-2717b35d3b42',
        'Les Émirats arabes unis envoient 30 tonnes d’aide médicale au Tchad pour faire face au choléra',
        'Les Émirats arabes unis ont envoyé 30 tonnes de fournitures médicales, dont des médicaments d’urgence, pour aider le Tchad à lutter contre une épidémie de choléra et soutenir les systèmes de santé africains.',
        'https://agpgabon.ga/les-emirats-arabes-unis-envoient-30-tonnes-daide-medicale-au-tchad-pour-faire-face-au-cholera/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '64881a87-6485-4f31-926b-036fd9ae043f',
        'MoyenOgooué/Législatives et locales : l’UDB présente ses candidats et commissaires à Lambaréné',
        'L’Union Démocratique des Bâtisseurs (UDB) a présenté ses candidats et responsables pour les élections législatives et locales prévues en septembre et octobre à Lambaréné, dans le cadre de sa tournée dans plusieurs villes du pays.',
        'https://agpgabon.ga/moyenogooue-legislatives-et-locales-ludb-presente-ses-candidats-et-commissaires-a-lambarene/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a871d07-d928-410b-9e32-6c32b3f6ea6e',
        'Élections Législatives 2025:  Anges Kevin Nzigou lance sa campagne au 5ᵉ arrondissement avec un « pacte d’inclusion »',
        'Anges Kevin Nzigou, candidat du FDS à la mairie centrale de Libreville, a lancé sa campagne dans le 5ème arrondissement en proposant un « pacte d’inclusion » pour promouvoir la participation de tous.',
        'https://gabonactu.com/blog/2025/08/24/elections-legislatives-2025-anges-kevin-nzigou-lance-sa-campagne-au-5%e1%b5%89-arrondissement-avec-un-pacte-dinclusion/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58310bc5-8a13-4904-a55a-530cce8b792f',
        'Port-Gentil : Bouka Aliou sous mandat de dépôt pour coups et blessures volontaires',
        'Un jeune homme de 27 ans a été placé en détention provisoire après avoir blessé gravement une personne avec un tonfa lors d''une altercation à Port-Gentil.',
        'https://gabonactu.com/blog/2025/08/24/port-gentil-bouka-aliou-sous-mandat-de-depot-pour-coups-et-blessures-volontaires/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72861c73-fb0b-4238-8335-84696cad7b8b',
        'Aubameyang ramène du beau temps à Marseille',
        'Pierre-Emerick Aubameyang a brillamment aidé l''OM à gagner contre le Paris FC avec un excellent match, marqué par plusieurs buts.',
        'https://gabonactu.com/blog/2025/08/24/aubameyang-ramene-du-beau-temps-a-marseille/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '777c7188-b648-44b2-bff2-1c59e6d98617',
        'Contestations préélectorales : Bilie-By-Nze renvoie Oligui Nguema à ses responsabilités constitutionnelles',
        'Alain-Claude Bilie-By-Nzé rappelle que la responsabilité des listes électorales incombe au président, en réponse aux accusations du ministère de l’Intérieur qui met en cause d’autres responsables.',
        'https://www.gabonreview.com/contestations-preelectorales-bilie-by-nze-renvoie-oligui-nguema-a-ses-responsabilites-constitutionnelles/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4f845837-99de-4143-b95c-8c9a8a32b222',
        'Tripatouillage ou transparence : Oligui trace la ligne rouge face aux dérives électorales',
        'Le président Oligui Nguema a demandé au ministère de l’Intérieur de garantir la transparence et la rigueur dans la publication des listes de candidatures, face aux soupçons de fraude et de manipulation électorale.',
        'https://www.gabonreview.com/tripatouillage-ou-transparence-oligui-trace-la-ligne-rouge-face-aux-derives-electorales/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f87d0bc-da1d-4d8b-80dd-f551adbd2091',
        'Ciment en hausse, tôles en chute : le contraste des industries de transformation',
        'Au premier trimestre 2025, le secteur de la transformation au Gabon a montré des performances contrastées, avec une hausse de la production de ciment et une chute de la fabrication de tôles.',
        'https://www.gabonreview.com/ciment-en-hausse-toles-en-chute-le-contraste-des-industries-de-transformation/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b57306b2-aef2-4696-9a68-6a2daa593d71',
        'Gabon-Benin : une délégation de Cotonou attendue à Libreville pour apaiser les tensions',
        'Une délégation béninoise est attendue à Libreville pour tenter de calmer les tensions diplomatiques entre le Gabon et le Bénin.',
        'https://gabonmediatime.com/gabon-benin-une-delegation-de-cotonou-attendue-a-libreville-pour-apaiser-les-tensions/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7b00c82-83f6-4ec8-a412-ad1170fa036d',
        'Gabon : industries de transformation, entre reprise du ciment et effondrement des tôles',
        'L''industrie gabonaise connaît une reprise dans la production de ciment, mais fait face à une chute importante des prix des tôles, impactant ainsi la transformation économique du secteur.',
        'https://gabonmediatime.com/gabon-industries-de-transformation-entre-reprise-du-ciment-et-effondrement-des-toles/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f6029bf-73b9-4910-90b8-ccddd15a455d',
        'Élections 2025 : Oligui Nguema désavoue son ministère de l’Intérieur',
        'Le ministre de l’Intérieur d’Ogou Nguema a été désavoué par le chef de l’État, ce qui soulève des tensions dans l’organisation des élections de 2025.',
        'https://gabonmediatime.com/elections-2025-oligui-nguema-desavoue-son-ministere-de-linterieur/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3790c8d-9228-4f5a-af78-cb9f4035f7aa',
        'Owendo/Législatives et locales : Pharel Boukika Mouketou, candidat UDIS, se lance pour “tourner la page de l’immobilisme”',
        'Pharel Boukika Mouketou se présente comme candidat aux législatives et aux locales à Owendo, souhaitant mettre fin à l''immobilisme politique local.',
        'https://kongossanews.info/owendo-legislatives-et-locales-pharel-boukika-mouketou-candidat-udis-se-lance-pour-tourner-la-page-de-limmobilisme/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f30410c-9a50-450e-96a9-752825a09112',
        'Gabon/2e édition de la caravane touristique : Eramet Comilog s’engage pour la valorisation du patrimoine gabonais',
        'La seconde édition de la caravane touristique organisée par Eramet et Comilog vise à valoriser le patrimoine gabonais en sensibilisant le public à la richesse culturelle et touristique du pays.',
        'https://kongossanews.info/gabon-2e-edition-de-la-caravane-touristique-eramet-comilog-sengage-pour-la-valorisation-du-patrimoine-gabonais/',
        'Kongossa News',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3bf2c454-e9d9-41ac-8be3-e0bb38f567ab',
        'Immigration : l’agonie des « popos » et des « aofiens » Makouké/ rupture amiable : Olam et le déni de l’article 77 du Code du tr...',
        'La population de la région du lac Tchad fait face à une crise migratoire due à l’insécurité, la pauvreté et les conflits, ce qui provoque des déplacements massifs de populations et des tensions dans la région.',
        'https://mediapostegabon.com/immigration-lagonie-des-popos-et-des-aofiens/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '752f3588-0a07-429e-85d0-df2c67c2eaa0',
        'Education : Olivier Rebienot Pellegrin remet à 700 élèves du 4eme arrondissement des kits scolaires.‎',
        '700 élèves du 4ème arrondissement de Libreville ont reçu des kits scolaires offerts par le directeur général de la CNSS, Olivier Rebienot Pellegrin, pour soutenir leur rentrée scolaire.',
        'https://gabonactu.com/blog/2025/08/24/education-olivier-rebienot-pellegrin-remet-a-700-eleves-du-4eme-arrondissement-des-kits-scolaires/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7f3498f-9e7c-4e5d-ae19-fecbb67567ad',
        'La gestion des finances du PDG désormais digitalisée',
        'Le Parti démocratique gabonais (PDG) a mis en place une gestion financière entièrement numérisée, suite à un séminaire dédié à cette transition, en impliquant ses trésoriers et commissaires aux comptes.',
        'https://gabonactu.com/blog/2025/08/24/la-gestion-des-finances-du-pdg-desormais-digitalisee/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38a72f5b-74ce-4af8-8e9b-3b75cf2d789c',
        'Politique/PDG : Séminaire de formation sur la gestion de la trésorerie',
        'Le Parti Démocratique Gabonais organise jusqu’à mardi un séminaire de formation pour renforcer les compétences de ses responsables financiers en gestion rigoureuse, transparente et responsable des ressources.',
        'https://agpgabon.ga/politique-pdg-seminaire-de-formation-sur-la-gestion-de-la-tresorerie/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '99946cc6-8355-44d8-a801-fc1cad54ecca',
        'Gabon / Digitalisation de la trésorerie : le PDG franchit une étape importante',
        'Le Parti Démocratique Gabonais a organisé un séminaire de formation pour digitaliser la gestion de sa trésorerie, afin de moderniser ses processus internes.',
        'https://vxp241.com/2025/08/24/gabon-digitalisation-de-la-tresorerie-le-dg-franchit-une-etape-importante/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c793e28b-b033-41d0-8e36-2e851b2cf07b',
        'Guinée : suspension de plusieurs partis d’opposition pour trois mois',
        'Les autorités de transition en Guinée ont suspendu pour trois mois plusieurs partis d’opposition, invoquant des manquements aux lois encadrant leur activité, sans préciser la nature exacte de ces infractions.',
        'https://agpgabon.ga/guinee-suspension-de-plusieurs-partis-dopposition-pour-trois-mois/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '00f09242-e670-41ed-b1aa-85490113fc22',
        'Gabon/Élections 2025 : le PDG forme ses candidats aux stratégies de campagne',
        'Le Parti Démocratique Gabonais organise une formation pour ses candidats afin de leur fournir des outils politiques et stratégiques pour mieux se préparer aux prochaines élections législatives et locales.',
        'https://agpgabon.ga/gabon-elections-2025-le-pdg-forme-ses-candidats-aux-strategies-de-campagne/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6725c7ca-f6c5-4e64-8fdd-d73674d3e7b0',
        'Cameroun : le Conseil constitutionnel valide la candidature de Paul Biya',
        'Le Conseil constitutionnel du Cameroun a rejeté la demande d''invalidation de la candidature de Paul Biya, permettant ainsi sa participation à l''élection présidentielle de 2024.',
        'https://agpgabon.ga/cameroun-le-conseil-constitutionnel-valide-la-candidature-de-paul-biya/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca80611e-b5c8-476e-8551-a6b4fa42bca9',
        'Gabon: Brice Oligui Nguema s''insurge face au rejet de certaines candidatures aux législatives',
        'Le président gabonais Brice Oligui Nguema a exprimé son soutien aux candidats disqualifiés aux élections législatives et locales, dénonçant des pratiques d''opacité et d''iniquité dans l''organisation du scrutin par le ministère de l’Intérieur.',
        'https://www.rfi.fr/fr/afrique/20250824-gabon-brice-oligui-nguema-s-insurge-face-au-rejet-de-certaines-candidatures-aux-l%C3%A9gislatives',
        'RFI',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1d41ad3-9d74-4996-984d-85b5012c9892',
        'Gabon: Brice Oligui Nguema s''insurge face au rejet de certaines candidatures aux législatives',
        'Plusieurs candidats récalés aux élections législatives et locales au Gabon ont exprimé leur mécontentement, ce qui a poussé le président Brice Clotaire Oligui Nguema à réagir personnellement pour apaiser la situation.',
        'https://www.rfi.fr/fr/afrique/20250824-gabon-brice-oligui-nguema-s-insurge-face-au-rejet-de-certaines-candidatures-aux-l%C3%A9gislatives?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '982f3756-a229-49e0-8ab2-12e4503ad732',
        'Gabon/Fête de la Libération : la Nyanga finalise les préparatifs',
        'Les préparatifs pour la célébration de la fête de la Libération, prévue à Tchibanga dans la province de la Nyanga, sont en cours, avec une réunion de coordination menée par le vice-président de la République pour organiser le déplacement et les activités de cette commémoration.',
        'https://agpgabon.ga/gabon-fete-de-la-liberation-la-nyanga-finalise-les-preparatifs/',
        'AGP',
        'Business Intelligence',
        '2025-08-24T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bed8bf58-a177-43ca-8495-0c40445ae775',
        'Football : Fghaut Ndama remporte le tournoi de l’inclusivité',
        'L''équipe de Fghaut Ndama a remporté la 2e édition du tournoi de l’inclusivité en battant Génération Miracle 2-0 en finale, dans le cadre d’une initiative visant à occuper et rassembler la jeunesse d’Alibandeng.',
        'https://agpgabon.ga/football-fghaut-ndama-remporte-le-tournoi-de-linclusivite/',
        'AGP',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09ef8ebd-89b1-4fef-865c-01a595ed2e86',
        'Gabon/Politique : Marc Ona Essangui mobilise les ressortissants du Woleu à Libreville',
        'Le sénateur Marc Ona Essangui a rencontré des ressortissants du Woleu à Libreville pour les sensibiliser aux enjeux des élections et encourager leur mobilisation dans leur région.',
        'https://agpgabon.ga/gabon-politique-marc-ona-essangui-mobilise-les-ressortissants-du-woleu-a-libreville/',
        'AGP',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9ff0cf8-8d4b-4c39-a693-04285d27a68d',
        'Gabon/Journée nationale du 30 août : le vice-président boucle sa tournée des chantiers dans la Nyanga',
        'Le vice-président de la République a inspecté les chantiers dans la Nyanga en vue des préparatifs pour la célébration de la Journée de la Libération, certains travaux progressent bien tandis que d''autres accusent des retards.',
        'https://agpgabon.ga/gabon-journee-nationale-du-30-aout-le-vice-president-boucle-sa-tournee-des-chantiers-dans-la-nyanga/',
        'AGP',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c65bcf20-249f-4a12-b857-3cf6ade95c14',
        'L''honorable Justine Judith Lekogo dénonce une mascarade politique et condamne avec fermeté les candidatures « groupées »',
        'L''honorable Justine Judith Lekogo dénonce la création de listes de candidatures fusionnées, qu''elle considère comme une mascarade politique sans base légale ni transparence.',
        'https://www.gabonews.com/fr/actus/politique/article/l-honorable-justine-judith-lekogo-denonce-une',
        'Gabonews',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6337b24d-0704-43a5-ad6b-4ef7da14f184',
        'Élections législatives et municipales 2025: OLIGUI NGUEMA exige des autorités diligence et impartialité',
        'Le président Oligui Nguema a exprimé ses préoccupations concernant des irrégularités dans la préparation des listes de candidatures pour les élections législatives et locales, soulignant que ces anomalies compromettent l’équité du processus électoral et la démocratie.',
        'https://vxp241.com/2025/08/25/elections-legislatives-et-municipales-2025-oligui-nguema-exige-des-autorites-diligence-et-impartialite/',
        'Vox Populi',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3bcae082-6833-4ef1-9a7e-8bef7f9e78b7',
        'Chantiers à l’arrêt : 338 milliards de FCFA mobilisés en 100 jours pour rembourser des dettes',
        'Le gouvernement gabonais a mobilisé 338 milliards de FCFA en 100 jours pour rembourser des dettes, ce qui a entraîné l''arrêt temporaire de certains chantiers en raison de paiements tardifs.',
        'https://directinfosgabon.com/chantiers-a-larret-338-milliards-de-fcfa-mobilises-en-100-jours-pour-rembourser-des-dettes/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0f89b27-51ad-4b3d-b069-7d0e065d0bcf',
        'Délestages : Le turc Kapowership va doubler sa capacité de production au Gabon',
        'Le projet turc Kapowership prévoit de doubler sa capacité de production d’électricité au Gabon pour réduire les coupures, notamment dans la région du Grand Libreville.',
        'https://directinfosgabon.com/delestages-le-turc-kapowership-va-doubler-sa-capacite-de-production-au-gabon/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab01c452-d662-49a1-bc21-f83f2d40a655',
        'Caravane Touristique:  Eramet Comilog mise sur le tourisme pour stimuler l’économie locale',
        'L''entreprise Eramet Comilog participe à une caravane touristique dans la région du Haut-Ogooué pour promouvoir le tourisme local et stimuler l''économie de la région.',
        'https://directinfosgabon.com/caravane-touristique-eramet-comilog-mise-sur-le-tourisme-pour-stimuler-leconomie-locale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6794e82c-500b-4d9c-85d4-9ac279ed58f3',
        'APPEL A MANIFESTATION D’INTERET N°83495724 (recrutement d’une société de gardiennage à Oyem)',
        'Une société de gardiennage est recherchée pour assurer la sécurité du bureau GIZ-TRIDOM à Oyem dans le cadre d''un projet lié à la conservation des forêts en coopération avec les organismes partenaires.',
        'https://gabonactu.com/blog/2025/08/25/appel-a-manifestation-dinteret-n83495724-recrutement-dune-societe-de-gardiennage-a-oyem/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4bae605f-9cb7-4293-bde2-4feb074fca54',
        'Franceville : un agent municipal au gnouf pour de la nourriture et des vêtements volés au marché',
        'Un agent municipal de Franceville a été condamné à un an de prison ferme pour avoir volé de la nourriture et des vêtements au marché.',
        'https://www.gabonreview.com/franceville-un-agent-municipal-au-gnouf-pour-de-la-nourriture-et-des-vetements-voles-au-marche/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd9d92a54-5b0c-434f-a4a2-9f83577dccf6',
        'Gabon : La valeur totale des transactions en monnaie électronique a atteint 4087 milliards de FCFA en 2024',
        'En 2024, la valeur totale des transactions en monnaie électronique au Gabon a atteint 4 087 milliards de FCFA, avec une progression de plus de 16 % du nombre de opérations par rapport à l’année précédente.',
        'https://directinfosgabon.com/gabon-la-valeur-totale-des-transactions-en-monnaie-electronique-a-atteint-4087-milliards-de-fcfa-en-2024/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a67cdb4-b925-4c4c-8e2d-34e24afde323',
        'Le Procès de la Transition : quand le rire s''invite à la fête',
        'Le 6 septembre, des humoristes gabonais présenteront une pièce satirique mettant en scène un procès fictif des militaires responsables du changement politique, promettant de divertir tout en faisant réfléchir sur la transition en cours.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/le-proces-de-la-transition-quand-le-rire-s-invite',
        'Gabonews',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6dad57cc-e6e1-4d6c-bc76-5f429f81e577',
        'Coup d''envoi de la 2ᵉ édition du Grand Cross de Ngouoni',
        'Le président Brice Clotaire Oligui Nguema et la Première Dame ont lancé la deuxième édition du Grand Cross de Ngouoni, un événement sportif réunissant plus d''une centaine de participants de tous âges, visant à promouvoir la santé, la solidarité et le dépassement de soi.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/coup-d-envoi-de-la-2%E1%B5%89-edition-du-grand-cross-de',
        'Gabonews',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f314801-991a-4c0c-8948-61aab9e9627e',
        'Publié le 25 / 08 / 2025',
        'Oligui Nguema insiste sur l''importance du respect des règles de transparence pour garantir la légitimité et la crédibilité des élections législatives et locales au Gabon.',
        'https://union.sonapresse.com/fr/legislatives-et-locales-oligui-nguema-intransigeant-sur-le-respect-des-regles-de-transparence',
        'L''union',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c718c11f-0b30-4b7f-8ea7-a36ccb91eb29',
        'Infrastructures : le ministre de l’Intérieur en visite des chantiers dans l’Ogoouée-Lolo',
        'Le ministre de l’Intérieur a visité plusieurs chantiers de construction, d’agrandissement et de réhabilitation dans la province de l’Ogooué-Lolo pour améliorer les écoles et infrastructures locales.',
        'https://agpgabon.ga/infrastructures-le-ministre-de-linterieur-en-visite-des-chantiers-dans-logoouee-lolo/',
        'AGP',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85d851a3-bf33-4306-b5a0-78256e7466b0',
        'Business : la 1ère édition du forum « Richesse d’Afrique » suscite l’espoir',
        'La première édition du forum « Richesse d’Afrique » à Libreville a inspiré espoir chez de nombreux entrepreneurs et dirigeants, grâce à des rencontres axées sur le coaching et le développement économique.',
        'https://gabonactu.com/blog/2025/08/25/business-la-1ere-edition-du-forum-richesse-dafrique-suscite-lespoir/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7049a03b-a580-4143-9a2a-d4d104a33005',
        'Oyem : GIZ recherche une société de gardiennage pour sécuriser ses bureaux',
        'La GIZ à Oyem cherche une société de gardiennage pour assurer la sécurité de ses bureaux.',
        'https://gabonactu.com/blog/2025/08/25/oyem-la-giz-recherche-une-societe-de-gardiennage-pour-securiser-ses-bureaux/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f562dbf6-7594-4baa-8f50-cf89155525a4',
        'Quelle place pour Schweitzer dans l’histoire du Gabon ? L’UOB ouvre le débat académique',
        'L’Université Omar Bongo organise un colloque en janvier 2026 pour réfléchir à la place d’Albert Schweitzer dans l’histoire, la mémoire et l’identité du Gabon, plus de cinquante ans après sa mort.',
        'https://www.gabonreview.com/quelle-place-pour-schweitzer-dans-lhistoire-du-gabon-luob-ouvre-le-debat-academique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '747a7346-d7ed-479b-a7a5-9faaf98a03a7',
        'Élections locales à Libreville : Me Nzigou scelle un pacte de confiance avec le 4ᵉ arrondissement',
        'Me Anges Kevin Nzigou a officialisé sa candidature aux élections locales pour le 4e et 5e arrondissement de Libreville, en établissant un pacte de confiance avec les habitants du quartier de Nzeng-Ayong.',
        'https://www.gabonreview.com/elections-locales-a-libreville-me-nzigou-scelle-un-pacte-de-confiance-avec-le-4%e1%b5%89-arrondissement/',
        'Gabon Review',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f84e8a9-da6d-4403-ad30-18a05aad21aa',
        'Oligui Nguema : «Nos 100 jours ne sont pas des effets d’annonce»',
        'Oligui Nguema affirme que ses 100 premiers jours au pouvoir ne doivent pas être considérés comme une période électorale ou de simple transition, mais comme une étape pour stabiliser le pays et engager des réformes.',
        'https://gabonmediatime.com/oligui-nguema-nos-100-jours-ne-sont-pas-des-effets-dannonce/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2634763-15d8-4203-952d-d6aebcdb357b',
        'Gabon : la production de manganèse recule de 5,3% en 2024 malgré la résistance des prix',
        'La production de manganèse en Gabon a diminué de 53 % en 2024, malgré la stabilité des prix du marché.',
        'https://gabonmediatime.com/gabon-la-production-de-manganese-recule-de-53-en-2024-malgre-la-resistance-des-prix/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31dd8f60-e812-4881-ad73-56573d96b993',
        'Législatives 2025 : les députés de la transition sans base électorale face au verdict des urnes',
        'Les députés issus de la transition en 2025 risquent de ne pas bénéficier d''une base électorale solide, ce qui pourrait influencer leur crédibilité lors des prochaines élections législatives.',
        'https://gabonmediatime.com/legislatives-2025-les-deputes-de-la-transition-sans-base-electorale-face-au-verdict-des-urnes/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-08-25T00:00:00.000Z',
        '2025-09-15T23:06:12.497Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

