-- Batch 1 - Section 3/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '5858b3d8-1088-49ac-8570-5aac2bc616ab',
        'Décryptage politique des messages de soutien du Haut-Como à Brice Clotaire Oligui Nguema',
        'À l’approche des élections présidentielles de 2025, l’article analyse les messages de soutien affichés au Haut-Como en faveur du Général Brice Clotaire Oligui Nguema, illustrant une mobilisation populaire et une stratégie de communication renforçant son ancrage politique.',
        'https://kongossanews.info/decryptage-politique-des-messages-de-soutien-du-haut-como-a-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.230Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47a8177c-ab97-4852-95eb-b1a559873fd8',
        'Transition: la plateforme Gabon Éveil appelle la jeunesse à s’engager sans complexe sur le plan politique et citoyen Gabon: Olig...',
        'La plateforme Gabon Éveil invite la jeunesse gabonaise à s’engager activement et de manière responsable dans la vie politique et citoyenne afin de promouvoir un renouveau national.',
        'https://depeches241.com/?p=22734',
        'Dépêche 241',
        'Éducation, Business Femme, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.230Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98b4bc90-61fd-4dca-8d66-06d00db87648',
        'Chantiers du CTRI : Au Gabon, les militaires sonnent l’heure de l’évaluation',
        'Les militaires du CTRI au Gabon lancent une évaluation des chantiers d''infrastructures récemment initiés afin de vérifier leur avancement et assurer le respect des délais de livraison.',
        'https://www.gabonreview.com/chantiers-du-ctri-au-gabon-les-militaires-sonnent-lheure-de-levaluation/',
        'Gabon Review',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.230Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '81c49bcf-42eb-49d4-8b54-307125680182',
        'Nicole Assélé : « Que cessent l’acharnement sur Ali Bongo Ondimba et les tentatives éhontées de réécriture de l’histoire du Gabo...',
        'Nicole Assélé appelle à mettre fin à l''acharnement contre Ali Bongo Ondimba et aux tentatives de réécriture de l''histoire du Gabon, tout en exhortant à la cohésion nationale face au repli identitaire.',
        'https://gabonactu.com/blog/2025/02/28/nicole-assele-que-cesse-lacharnement-sur-ali-bongo-ondimba-et-les-tentatives-ehontees-de-reecriture-de-lhistoire-du-gabon/',
        'Gabon Actu',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.230Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '24103df0-970f-4d4c-8451-9256988c5d39',
        'Gabon : Ouverture d’une période exceptionnelle d’inscription et de réclamation sur la liste électorale',
        'Le ministère de l’Intérieur et de la Sécurité du Gabon annonce une période exceptionnelle d’inscription et de réclamation sur la liste électorale du 1er au 10 mars 2025 afin de favoriser une participation élargie et de corriger d’éventuelles irrégularités avant les prochaines élections.',
        'https://kongossanews.info/gabon-ouverture-dune-periode-exceptionnelle-dinscription-et-de-reclamation-sur-la-liste-electorale/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.231Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ecbe322d-418d-4a89-a3f6-df4774174a78',
        'Transport aérien : Afrijet Air et France renforcent et augmentent leur connectivité régionale et internationale',
        'Les compagnies aériennes gabonaise Afrijet et française Air France ont renforcé leur coopération en ajoutant les destinations Port Harcourt au Nigeria et Bangui en République centrafricaine, faisant de l’aéroport international Léon Mba de Libreville une plateforme clé de correspondance en Afrique centrale.',
        'https://www.gabonreview.com/transport-aerien-afrijet-air-et-france-renforcent-et-augmentent-leur-connectivite-regionale-et-internationale/',
        'Gabon Review',
        'Tourisme, Numérique / Digital, Transport aériens',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.231Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ead070b-c0cd-4c09-a1ea-3356010e7702',
        'Gabon : Vaalco Energy prévoit d’investir 3,8 milliards de FCFA en 2025 dans des projets sociaux',
        'En 2025, la société pétrolière américaine Vaalco Energy prévoit d''investir 3,8 milliards de FCFA dans des projets sociaux au Gabon.',
        'https://directinfosgabon.com/gabon-vaalco-energy-prevoit-dinvestir-38-milliards-de-fcfa-en-2025-dans-des-projets-sociaux/',
        'Direct infos Gabon',
        'Services, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.231Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0ca4e66-9b1b-459b-99aa-f6562a776496',
        'Gabon/Présidentielle 2025 : Renforcement des capacités des journalistes pour une couverture médiatique responsable',
        'En préparation des élections présidentielles de 2025, le ministère de la Communication et des Médias du Gabon a lancé un atelier de formation destiné aux journalistes pour promouvoir une couverture médiatique responsable et transparente.',
        'https://kongossanews.info/gabon-presidentielle-2025-renforcement-des-capacites-des-journalistes-pour-une-couverture-mediatique-responsable/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.231Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b6e3105-7a18-4860-b664-4814b5f67aae',
        'Chantiers de la Transition : Oligui lance un vaste audit de contrôle',
        'Le Comité de transition pour la restauration des institutions lancera un vaste audit des principaux chantiers de transition dans des secteurs stratégiques tels que les infrastructures, l’éducation, la santé et l’économie afin d’évaluer leur avancement et leur conformité aux objectifs de développement national.',
        'https://directinfosgabon.com/chantiers-de-la-transition-oligui-lance-un-vaste-audit-de-controle/',
        'Direct infos Gabon',
        'Numéro / Digital, Éducation, Services, Finances',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.232Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c818e22-355f-4645-ba91-fdbe26a47ad0',
        'De Singapour au Golfe Persique : Ce que la reprise d’Olam Agri par SALIC signifie pour le Gabon',
        'Le groupe singapourien Olam Agriculture a vendu ses activités au Gabon à la société saoudienne SALIC pour 1,78 milliard de dollars, marquant un tournant économique majeur pour le pays avec des incertitudes sur l’avenir des emplois, des investissements agricoles et de la gestion environnementale.',
        'https://www.gabonreview.com/de-singapour-au-golfe-persique-ce-que-la-reprise-dolam-agri-par-salic-signifie-pour-le-gabon/',
        'Gabon Review',
        'Agriculture, Services, Finances, Numérique / Digital, Environnement',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.232Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5cdc3f89-158f-4464-8515-8b1335af3aca',
        'CNSS : Plus de 90 % des effectifs sont hors des métiers de la protection sociale !',
        'Lors de l''inauguration du Centre de formation de la CNSS, le Directeur Général a révélé que plus de 90 % des employés ne sont pas issus des métiers de la protection sociale, soulignant ainsi la nécessité de professionnaliser l’organisme.',
        'https://directinfosgabon.com/cnss-plus-de-90-des-effectifs-sont-hors-des-metiers-de-la-protection-sociale/',
        'Direct infos Gabon',
        'Éducation, Services, Numérique / Digital',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.232Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2294320e-2b42-43f6-a35c-a829592504e3',
        'Gabon/Chantiers CTRI : le Chef de l’État déploie des équipes de contrôle pour garantir le respect des délais',
        'Le Président de la Transition gabonaise, le Général Brice Clotaire Oligui Nguema, a annoncé le déploiement d’équipes de contrôle nationales supervisées par le CTRI pour garantir le respect des délais et la qualité des chantiers publics, renforçant ainsi la transparence et l’efficacité des projets prioritaires du pays.',
        'https://kongossanews.info/gabon-chantiers-ctri-le-chef-de-letat-deploie-des-equipes-de-controle-pour-garantir-le-respect-des-delais/',
        'Kongossa News',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.233Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '14a1fcb4-00d2-4bb1-a3a3-a690983c635f',
        'Instrumentalisation de la justice : Sans pudeur Gondjout demande la liste des magistrats grévistes Gabon: HPO poursuivi sur la b...',
        'Le ministre de la Justice gabonais, Paul-Marie Gondjout, a exigé la liste des magistrats en grève, suscitant des inquiétudes quant à une possible instrumentalisation de la justice et une atteinte à l’indépendance judiciaire.',
        'https://depeches241.com/?p=22742',
        'Dépêche 241',
        'Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.233Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f1f2cfd-2a1f-4310-82a3-1c505bee1515',
        'Travaux sur la Route Nationale 1 : une conduite DN 450 mm endommagée à Nkoltang',
        'Le 27 février 2025, une conduite d’eau de 450 mm endommagée par une entreprise de BTP à Nkoltang a causé des perturbations dans le réseau d’eau potable du Grand Libreville, mais les réparations nocturnes ont permis une remise en eau progressive dès le lendemain matin.',
        'https://www.gabonreview.com/travaux-sur-la-route-nationale-1-une-conduite-dn-450-mm-endommagee-a-nkoltang/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.233Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff3b96b1-af66-4e6f-9949-10e2d08899fa',
        'Gabon/Foire agricole de Libreville (FAL) : l’entrepreneuriat agricole au cœur de la croissance économique',
        'La Foire agricole de Libreville 2025 met en avant l’entrepreneuriat agricole comme levier essentiel de la diversification et de la croissance économique du Gabon.',
        'https://kongossanews.info/gabon-foire-agricole-de-libreville-fal-lentrepreneuriat-agricole-au-coeur-de-la-croissance-economique/',
        'Kongossa News',
        'Agriculture, Services, Éducation, Business Femme',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.233Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f0c3fab-1228-42c8-aff0-e93170a6db88',
        'Affaire Opiangah: la chambre d’accusation à l’épreuve de l’inévitable obligation de dire le droit Instrumentalisation de la just...',
        'Dans l’affaire Opiangah, le transfert du dossier HPO à la chambre d’accusation met en lumière les dysfonctionnements et les manipulations au sein du parquet, soulignant l’urgence de rétablir l’intégrité et la crédibilité de la justice gabonaise.',
        'https://depeches241.com/?p=22752',
        'Dépêche 241',
        'Justice, Autres',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.233Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27a7c276-3c37-4e85-b4c2-182e3725d044',
        'Présidentielle 2025: Alain Simplice Boungoueres propose une charte d’éthique pour des élections apaisées',
        'Le président du Parti des Patriotes Gabonais, Alain Simplice Boungoueres, a proposé une charte d’éthique visant à garantir des élections présidentielles de 2025 transparentes et pacifiques au Gabon.',
        'https://kongossanews.info/presidentielle-2025-alain-simplice-boungoueres-propose-une-charte-dethique-pour-des-elections-apaisees/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.234Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '89db6850-7048-475f-b80f-0acc903205d4',
        'Présidentielle 2025 : des journalistes formés à la gestion de l’Information',
        'À l’approche des élections présidentielles de 2025 au Gabon, un atelier organisé par le PNUD et ses partenaires a formé des journalistes à la gestion de l’information pour garantir une couverture médiatique objective et transparente.',
        'https://gabonactu.com/blog/2025/02/28/presidentielle-2025-des-journalistes-formes-a-la-gestion-de-linformation/',
        'Gabon Actu',
        'Éducation, Numérique / Digital, Services',
        '2025-02-28T00:00:00.000Z',
        '2025-09-15T23:06:12.234Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f037d3eb-8958-4733-95b2-ae8f82f9f812',
        '286 nouveaux retraités vont percevoir leur première pension dès ce 3 mars',
        '286 nouveaux retraités percevront leur première pension entre le 3 et le 7 mars 2025, selon le calendrier de la Caisse Nationale de Sécurité de Sociale (CNSS).',
        'https://gabonactu.com/blog/2025/02/28/286-nouveaux-retraites-vont-percevoir-leur-premiere-pension-des-ce-3-mars/',
        'Gabon Actu',
        'Finances, Services, Numérique / Digital',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.235Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf3f30b3-4ec1-483c-8f1d-1149e67c62ea',
        'Signature de la résolution désignant le Collège médical pour l’évaluation des candidats à la présidentielle',
        'Le Sénat de la transition et l''Assemblée nationale ont signé une résolution désignant un Collège médical chargé d’évaluer l’aptitude physique et mentale des candidats à l’élection présidentielle de 2025.',
        'https://www.gabonews.com/fr/actus/politique/article/signature-de-la-resolution-designant-le-college',
        'Gabonews',
        'Autres',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.235Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f439bb5b-75f9-4470-8a04-d981ea2eb967',
        'Le Président de la récompense les lauréats de la 4e édition du Concours National des Meilleurs Élèves',
        'Le Président de la République, Général Brice Clotaire Oligui Nguema, a honoré 162 lauréats de la 4e édition du Concours National des Meilleurs Élèves lors d''une cérémonie au Palais de la Rénovation, en introduisant de nouveaux prix pour les meilleurs établissements et enseignants.',
        'https://www.gabonews.com/fr/actus/education/article/le-president-de-la-recompense-les-laureats-de-la',
        'Gabonews',
        'Éducation, Business Femme',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.235Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ba7de103-cc5c-4e0a-b51f-c04233f3129c',
        'Présidentielle 2025 : Jean Remy Yama candidat à la candidature pour sortir le Gabon des ténèbres',
        'Jean Rémy Yama, président du Parti national pour le travail et le progrès, annonce sa candidature à l''élection présidentielle de 2025 afin de rompre avec l''ancien régime et instaurer un État de droit au Gabon.',
        'https://gabonactu.com/blog/2025/03/01/presidentielle-2025-jean-remy-yama-candidat-a-la-candidature-pour-sortir-le-gabon-des-tenebres/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.235Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd5b5abb8-873f-468f-a563-13939f50a938',
        'Coupe du Monde Cuisine & Pâtisserie : Le Gabon rafle 4 médailles d’or',
        'Le Gabon a remporté quatre médailles d’or lors de la Coupe du Monde de Cuisine et de Pâtisserie en Tunisie.',
        'https://www.gabonews.com/fr/actus/arts-culture/article/coupe-du-monde-cuisine-patisserie-le-gabon-rafle',
        'Gabonews',
        'Éducation, Tourisme, Services',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.236Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68f842e9-c539-467e-9b76-4ad9a2ba33a8',
        'Concours national des meilleurs élèves : les lauréats de la 4e édition récompensés par le chef de l’État Electricité : mise en m...',
        'Lors de la 4e édition du Concours National des Meilleurs Élèves au Gabon, 162 étudiants des neuf provinces ont été honorés par le chef de l’État, soulignant l’engagement national envers l’éducation et l’excellence.',
        'https://mediapostegabon.com/concours-national-des-meilleurs-eleves-les-laureats-de-la-4e-edition-recompenses-par-le-chef-de-letat/',
        'Media Poste Gabon',
        'Éducation, Numérique / Digital, Services',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.236Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f7b74e8-0d45-45f7-8b25-66a67cb899e2',
        'CPS de l’UA : La présidence du Maroc pour le mois de mars s’inscrit dans la continuité des engagements du Royaume pour une Afriq...',
        'Le Maroc assure la présidence du Conseil de Paix et de Sécurité de l’Union africaine pour mars 2025, poursuivant ainsi ses engagements en faveur d’une Afrique pacifique, stable et prospère.',
        'https://www.gabonews.com/fr/actus/international/article/cps-de-l-ua-la-presidence-du-maroc-pour-le-mois',
        'Gabonews',
        'Autres',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.236Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '77969d15-1b12-48dc-aa6a-24143b9c734a',
        'Présidentielle 2025 : Jean Rémy Yama entre en lice pour la rupture et la lumière',
        'Jean Rémy Yama a annoncé sa candidature à l''élection présidentielle gabonaise du 12 avril 2025 en se présentant comme un candidat porteur de rupture et de changement face au système actuel.',
        'https://www.gabonreview.com/presidentielle-2025-jean-remy-yama-entre-en-lice-pour-la-rupture-et-la-lumiere/',
        'Gabon Review',
        'Autres',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.237Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9957fdd7-e9f4-4eb7-bebc-6c33633969aa',
        'Port-Gentil : le groupe Féfé Onanga lance sa campagne par une veillée d’unification sociale et politique',
        'Le groupe Féfé Onanga a inauguré à Port-Gentil une veillée d’unification sociale et politique visant à soutenir la candidature de Brice Clotaire Oligui Nguema aux élections du 12 avril 2025.',
        'https://gabonactu.com/blog/2025/03/01/port-gentil-le-groupe-fefe-onanga-lance-sa-campagne-par-une-veillee-dunification-sociale-et-politique/',
        'Gabon Actu',
        'Autres',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.237Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4367144f-e059-4f6a-844e-666bc8085c6f',
        'Olam Group Limited réaffirme son engagement au Gabon malgré la cession d’Olam Agri',
        'Olam Group Limited réaffirme son engagement au Gabon en maintenant ses opérations dans les secteurs du palmier à huile et du caoutchouc malgré la cession d’Olam Agri à SALIC.',
        'https://www.gabonreview.com/olam-group-limited-reaffirme-son-engagement-au-gabon-malgre-la-cession-dolam-agri/',
        'Gabon Review',
        'Agriculture, Finances, Services',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.237Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '42481ac7-c420-42da-8853-8f6a9a62edd4',
        'Mise en service des centrales électriques : Est-ce la fin des délestages ?',
        'Le président de la Transition gabonaise a inauguré les centrales électriques flottantes de Karpowership à Owendo afin de stabiliser l''approvisionnement en électricité et de mettre fin aux délestages récurrents.',
        'https://directinfosgabon.com/mise-en-service-des-centrales-electriques-est-ce-la-fin-des-delestages/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.237Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27bd68bd-9963-429c-9a64-27e3051c7bf6',
        'Wenceslas Mamboundou : Un expert en processus électoraux pour diriger l’ACER ?',
        'Wenceslas Mamboundou, expert en processus électoraux, est considéré comme le candidat idéal pour présider l’ACER, visant à renforcer la transparence et la crédibilité des élections au Gabon.',
        'https://directinfosgabon.com/wenceslas-mamboundou-un-expert-en-processus-electoraux-pour-diriger-lacer/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Éducation',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.237Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4d6cd7ff-4b01-431b-a302-ac518ae5678f',
        'BGFI Holding : Une entrée en bourse pour lever 100 milliards de FCFA en 2025',
        'BGFI Holding prévoit son introduction en bourse d''ici juin 2025 pour lever jusqu''à 100 milliards de FCFA, soutenue par une forte croissance financière récente, afin de renforcer sa position sur le marché financier et accélérer son expansion en Afrique.',
        'https://directinfosgabon.com/bgfi-holding-une-entree-en-bourse-pour-lever-100-milliards-de-fcfa-en-2025/',
        'Direct infos Gabon',
        'Finances, Numérique / Digital',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.238Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33d3d16b-2194-47f8-be8d-1694133d4186',
        'Ce que Dieu admire, révèle ce que Dieu est. Nous admirons le pragmatisme du Chef de l’État Oligui Nguema"',
        'Le président du Mouvement National pour la Dignité et la Justice, Davy Macaire Ntoutoume Essone Ayong, appelle à la candidature de Brice Clotaire Oligui Nguema pour la présidentielle du 12 avril, soulignant son pragmatisme et ses qualités de bâtisseur et de fédérateur.',
        'https://www.gabonews.com/fr/actus/politique/article/ce-que-dieu-admire-revele-ce-que-dieu-est',
        'Gabonews',
        'Autres',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.238Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7b022b8-c5c0-4e92-8450-2f3a4f80c4ec',
        'Le Chef de l’État procède à mise en service des centrales électriques flottantes du groupe Karpowership Libreville le 28 février...',
        'Le Chef de l’État a inauguré le 28 février 2025 les centrales électriques flottantes du groupe Karpowership à Libreville pour améliorer l''approvisionnement en électricité et réduire les délestages dans la région.',
        'https://gabonactu.com/blog/2025/03/01/le-chef-de-letat-procede-a-mise-en-service-des-centrales-electriques-flottantes-du-groupe-karpowership-libreville-le-28-fevrier-2025/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances',
        '2025-03-01T00:00:00.000Z',
        '2025-09-15T23:06:12.238Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f52079f-c41f-433f-ab0b-952d10988a61',
        'REAGIR affûte en marche pour L’élection présidentielle d’avril 2025',
        'Le parti politique REAGIR intensifie ses préparatifs et installations à travers le pays en vue de l’élection présidentielle du 12 avril 2025.',
        'https://www.gabonews.com/fr/actus/politique/article/reagir-affute-en-marche-pour-l-election',
        'Gabonews',
        'Politique, Services, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.238Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a5082b2-5475-48e1-9fc4-65ce963e6a7d',
        'OCT présente sa plateforme innovante pour générer ses factures en ligne',
        'Owendo Container Terminal (OCT) a lancé sa plateforme numérique IPAKI Extranet Solution (IES) lors d’ateliers, permettant aux clients de générer des factures en ligne et d’accéder à divers services, renforçant ainsi son engagement envers la digitalisation et l’amélioration de l’expérience client.',
        'https://directinfosgabon.com/oct-presente-sa-plateforme-innovante-pour-generer-ses-factures-en-ligne/',
        'Direct infos Gabon',
        'Numérique / Digital, Services',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.239Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5797eefe-801f-40f5-b154-213bb6eaacc7',
        'Téléchargez le Bilan alimentaire du Gabon pour la période 2020-2021',
        'L''article présente et propose le téléchargement du Bilan alimentaire du Gabon pour 2020-2021, décrivant son rôle dans l''analyse de la sécurité alimentaire nationale et les priorités de la stratégie de relance économique agricole.',
        'https://directinfosgabon.com/telechargez-le-bilan-alimentaire-du-gabon-pour-la-periode-2020-2021/',
        'Direct infos Gabon',
        'Agriculture, Services, Finances',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.239Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d872bed-a8b8-4297-bea2-4b0d81881d12',
        'Performances : Classement des 9 premières entreprises gabonaises en 2025',
        'En 2025, neuf entreprises gabonaises, principalement actives dans les secteurs pétrolier et minier, sont classées parmi les 500 premières entreprises africaines en termes de chiffre d’affaires.',
        'https://directinfosgabon.com/performances-classement-des-9-premieres-entreprises-gabonaises-en-2025/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.239Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ee15959-e448-4e46-aadc-db03ac8367ca',
        'Présidentielle 2025 : dernière chance jusqu’au 10 mars pour les non-inscrits sur la liste électorale',
        'La dernière opportunité pour les électeurs non inscrits de s''enregistrer sur la liste électorale se termine le 10 mars 2025 en vue de la présidentielle.',
        'https://gabonactu.com/blog/2025/03/02/presidentielle-2025-derniere-chance-jusquau-10-mars-pour-les-non-inscrits-sur-la-liste-electorale/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.239Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd9358664-60ff-4a5f-ae87-0000ee46d96f',
        'Téléchargez et consultez la Loi de finances 2025 (Officiel)',
        'L''article annonce la disponibilité officielle de la Loi de finances 2025 du Gabon, adoptée par les deux chambres du Parlement et publiée le 20 janvier 2025 dans le Journal officiel.',
        'https://directinfosgabon.com/telechargez-et-consultez-la-loi-de-finances-2025-officiel/',
        'Direct infos Gabon',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.240Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8ad18d1-1a77-4b95-83ed-295c1268698b',
        'Présidentielle 2025 : Teodoro Obiang Nguema accusé d’ingérence au Gabon',
        'Trois leaders politiques gabonais accusent le président de la Guinée équatoriale, Teodoro Obiang Nguema, d’ingérence dans les affaires intérieures du Gabon en conseillant les électeurs à soutenir le président de la Transition pour l’élection présidentielle de 2025.',
        'https://gabonactu.com/blog/2025/03/02/presidentielle-2025-teodoro-obiang-nguema-accuse-dingerence-au-gabon/',
        'Gabon Actu',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.240Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bbd2a659-7453-4c21-b684-37af0b01b7d8',
        'Football : Un match amical entre AS Tchenga et AS Malanga marque la préparation des grands tournois cantonaux',
        'Un match amical de football entre l''AS Tchenga et l''AS Malanga s''est terminé sur un score de 1-1, marquant la préparation des grands tournois cantonaux de Poungui et Leyou.',
        'https://kongossanews.info/football-un-match-amical-entre-as-tchenga-et-as-malanga-marque-la-preparation-des-grands-tournois-cantonaux/',
        'Kongossa News',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.240Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7486e001-ba59-4580-82e4-69b901b4777d',
        'Marchés itinérants : Nzeng-Ayong est encore ouvert ce dimanche',
        'La première édition des marchés itinérants de Nzeng-Ayong à Libreville connaît un succès notable, incitant les autorités à envisager des éditions mensuelles pour promouvoir le commerce local et rapprocher vendeurs et consommateurs.',
        'https://gabonactu.com/blog/2025/03/02/marches-itinerants-nzeng-ayong-est-encore-ouvert-ce-dimanche/',
        'Gabon Actu',
        'Commerce, Services, Numérique / Digital',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.240Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08bed3f0-898e-492f-83ac-a70ad231c9de',
        'Pour chasser les ténèbres du Gabon, le PNTP présente son candidat à l’élection présidentielle du 12 avril prochain.',
        'Le Parti National pour la Transformation Populaire (PNTP) annonce la candidature de Jean Rémy Yama pour l’élection présidentielle du 12 avril prochain au Gabon, appelant à une rupture avec le système actuel et à un renouveau fondé sur l’intégrité et l’unité nationale.',
        'https://kongossanews.info/pour-chasser-les-tenebres-du-gabon-le-pntp-presente-son-candidat-a-lelection-presidentielle-du-12-avril-prochain/',
        'Kongossa News',
        'Numérique / Digital, Services, Finances, Éducation, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.241Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ab22792-5ed7-4084-9e9f-c48cdc5de8f1',
        'Présidentielle 2025 : ‘’L’opposition’’ exige le report',
        'Trois des quatre principaux leaders de l''opposition gabonaise demandent le report des élections présidentielles de 2025 en raison d''irrégularités électorales et d''un manque de transparence dans le processus.',
        'https://gabonactu.com/blog/2025/03/02/presidentielle-2025-lopposition-exige-le-report/',
        'Gabon Actu',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.241Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76774ed4-32ba-44b2-b3a6-a20f022bad2d',
        'Présidentielle 2025 : ACTE soutiendra Oligui Nguéma',
        'La plateforme ACTE a annoncé son soutien au président de la transition, Brice Clotaire Oligui Nguéma, en appelant à sa candidature lors de l''élection présidentielle de 2025 en soulignant ses projets économiques et sociaux.',
        'https://gabonactu.com/blog/2025/03/02/presidentielle-2025-acte-soutiendra-oligui-nguema/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances, Agriculture, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.242Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3845e5e1-1ca1-4549-aef7-0f9232fe3c16',
        'Le Mouvement Ensemble pour le 2è arrondissement de la commune de Libreville appelle à la candidature du Président de la transiti...',
        'Le Mouvement Ensemble pour le 2ᵉ arrondissement de Libreville appelle officiellement Brice Clotaire Oligui Nguema à se présenter à la présidentielle du 12 avril 2025, soulignant son leadership et sa vision pour le progrès national.',
        'https://www.gabonews.com/fr/actus/politique/article/le-mouvement-ensemble-pour-le-2e-arrondissement',
        'Gabonews',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.242Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0af810f2-b94b-4ccc-b3a8-bf86c378b50c',
        'Au bord de la Bouenguidi : Blaise Louembe officiellement investi à la tête du PDG',
        'Blaise Louembé a été officiellement investi à la présidence du Parti démocratique gabonais lors d''une cérémonie solennelle à Koula-Moutou, marquant le début de son mandat pour renforcer l''unité et la mission du parti.',
        'https://kongossanews.info/au-bord-de-la-bouenguidi-blaise-louembe-officiellement-investi-a-la-tete-du-pdg/',
        'Kongossa News',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.242Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '94453103-e6af-4c84-b29c-602f05efffd4',
        'OCT lance une plateforme innovante pour générer les factures en lignes',
        'Owendo Container Terminal (OCT) a lancé une plateforme innovante, IPAKI Extranet Solution, permettant de générer des factures en ligne et de simplifier les opérations pour ses clients.',
        'https://gabonactu.com/blog/2025/03/02/oct-lance-une-plateforme-innovante-pour-generer-les-factures-en-lignes/',
        'Gabon Actu',
        'Numérique / Digital, Services',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.242Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd7ebd01c-c42d-4e12-b2d5-08f803c197ef',
        'Dénutrition et cancer infantile au Gabon : une réalité alarmante à l’Institut de Cancérologie d’Akanda',
        'Une étude récente révèle que plus de 70 % des enfants atteints de cancer à l’Institut de Cancérologie d’Akanda au Gabon sont déjà dénutris au moment du diagnostic, compromettant leur pronostic vital.',
        'https://www.gabonreview.com/denutrition-et-cancer-infantile-au-gabon-une-realite-alarmante-a-linstitut-de-cancerologie-dakanda/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.243Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f1110c1-6b35-4439-ac8b-39f12fcdf78d',
        'La Türkiye et le Gabon signent un accord stratégique pour l’innovation scientifique',
        'La Türkiye et le Gabon ont signé un accord stratégique visant à renforcer leur coopération scientifique et technologique à travers des projets de recherche et développement conjoints et des programmes d’échange de scientifiques.',
        'https://gabonactu.com/blog/2025/03/02/la-turkiye-et-le-gabon-signent-un-accord-strategique-pour-linnovation-scientifique/',
        'Gabon Actu',
        'Numérique / Digital, Éducation, Services, Agriculture',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.243Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

