-- Batch 4 - Section 11/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'e7609469-8c99-4d9c-9b2f-3110f1cac259',
        'Bikele-Nzong : un nouveau quartier sur 75 hectares',
        'Un nouveau quartier de 1 070 logements est en construction à Bikele-Nzong pour reloger les familles affectées par le projet d''assainissement de Gué-Gué à Libreville.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/bikele-nzong-un-nouveau-quartier-sur-75-hectares',
        'Gabonews',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.454Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cc0e9a55-fe8f-4071-9bc5-b6d9a1b932d8',
        'Gabon/Déguerpis : le député Lionnel Ella Engonga sollicite une enquête parlementaire sur les expropriations à Plaine-Orety',
        'Un député de la transition demande une enquête parlementaire sur les expropriations qui ont eu lieu à Plaine-Orety depuis janvier 2024, visant à faire la lumière sur ces opérations.',
        'https://agpgabon.ga/gabon-deguerpis-le-depute-lionnel-ella-engonga-sollicite-une-enquete-parlementaire-sur-les-expropriations-a-plaine-orety/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.454Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a093d97d-8971-47e6-92c3-32752acca064',
        'Football/Panthères du Gabon : Thierry Mouyouma annonce des surprises pour les matchs de septembre',
        'Le sélectionneur des Panthères du Gabon, Thierry Mouyouma, annonce qu''il prépare plusieurs surprises dans sa sélection pour les matchs de qualification à la Coupe du monde 2026 en septembre, après avoir effectué plusieurs essais lors d''une victoire amicale contre la Guinée-Bissau.',
        'https://agpgabon.ga/football-pantheres-du-gabon-thierry-mouyouma-annonce-des-surprises-pour-les-matchs-de-septembre/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.454Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16dc2f4a-761a-4a97-bde0-6a739b587e02',
        'Gabon /Digitalisation de l’administration: Mise à jour du cadre juridique',
        'Après l’amendement du modèle économique du projet eGabon-Système d’Information de Santé (SIS), un atelier à Ntoum a permis de faire le point sur les aspects juridiques nécessaires à la mise en place et à la gestion de ce système de santé numérique au Gabon.',
        'https://vxp241.com/2025/06/11/gabon-digitalisation-de-ladministration-mise-a-jour-du-cadre-juridique/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.454Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e701a2f8-7ebf-471f-bc16-7d3a4e5bb2b8',
        'Gouvernance dans la « 5ème République » : Bilie-By-Nzé s’en indigne',
        'Alain-Claude Bilie-By-Nzé critique la gouvernance de la 5ème République gabonaise, exprimant son mécontentement lors d''une conférence de presse.',
        'https://gabonactu.com/blog/2025/06/11/gouvernance-dans-la-5eme-republique-bilie-by-nze-sen-indigne/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.454Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96b1f900-57c4-476d-81ba-c40c8c4ab974',
        'Mayfair confidentiel : exil doré, manœuvres froides, les Bongo bougent encore',
        'Après leur évacuation du Gabon suite au coup d’État de 2023, l''ancien président Ali Bongo et sa famille vivent discrètement à Londres, où ils tentent de réconcilier des membres dissidents de leur clan.',
        'https://www.gabonreview.com/mayfair-confidentiel-exil-dore-manoeuvres-froides-les-bongo-bougent-encore/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '33c34e92-cd2f-4730-b2da-a08568d59668',
        'Gabon/Diplomatie économique : le Chef de l’État échange avec une délégation de l’entreprise chinoise NORINCO',
        'Le président gabonais a rencontré une délégation de la société chinoise NORINCO pour discuter de futures collaborations, notamment dans le domaine militaire, en poursuivant des échanges entamés en 2024.',
        'https://agpgabon.ga/gabon-diplomatie-economique-le-chef-de-letat-echange-avec-une-delegation-de-lentreprise-chinoise-norinco/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '55d92901-5119-44ba-8de8-ef9005fa2e57',
        'Gabon/Sécurité Sanitaire des aliments : l’AGASA dévoile ses ambitions et ses défis',
        'L’AGASA veut renforcer la prévention des risques alimentaires et améliorer les standards de consommation, mais fait face à des défis financiers qui limitent ses contrôles sanitaires.',
        'https://agpgabon.ga/gabon-securite-sanitaire-des-aliments-lagasa-devoile-ses-ambitions-et-ses-defis/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '737718bf-ebc7-499e-988b-4f9d1b4c15a7',
        'Chine/Afrique : des journalistes africains francophones découvrent les mutations de la Chine à travers le prisme de la gouvernance centrée sur le peuple',
        'Une conférence à Pékin a présenté les évolutions de la Chine axées sur la gouvernance centrée sur le peuple, lors d’un séminaire réunissant des journalistes africains francophones pour découvrir les grandes étapes du développement chinois contemporain.',
        'https://agpgabon.ga/chine-afrique-des-journalistes-africains-francophones-decouvrent-les-mutations-de-la-chine-a-travers-le-prisme-de-la-gouvernance-centree-sur-le-peuple/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '66f128fc-8140-4ee8-a1ec-d62db5e46535',
        'Législatives & locales : Emmanuel Ombana en tournée consultative pour co-construire l''avenir du 2ᵉ Arrondissement de Franceville',
        'Emmanuel Ombana organise un marathon de rencontres dans les quartiers de Franceville pour écouter les attentes des habitants, notamment des jeunes, en vue des élections législatives et locales de 2025.',
        'https://www.gabonews.com/fr/actus/politique/article/legislatives-locales-emmanuel-ombana-en-tournee',
        'Gabonews',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c45ab063-6104-4514-b754-2734ba87f1d8',
        'Gabon/SGEPP : une rentabilité en forte hausse avec 848 millions de FCFA de bénéfices en 2024',
        'En 2024, la SGEPP a enregistré un bénéfice net de 848 millions de FCFA, en hausse de 105 % par rapport à l’année précédente, grâce à une hausse du chiffre d’affaires et à des stratégies d’optimisation.',
        'https://agpgabon.ga/gabon-sgepp-une-rentabilite-en-forte-hausse-avec-848-millions-de-fcfa-de-benefices-en-2024/',
        'AGP',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f4c3e7d-5a07-4f24-b5fd-9b23bc4a9905',
        'Diversification des partenariats stratégiques: OLIGUI NGUEMA devise avec le chinois NORINCO',
        'Le président Clotaire Olgui Nguema a rencontré une délégation de l’entreprise chinoise NORINCO pour discuter des perspectives de partenariat stratégique entre le Gabon et la Chine.',
        'https://vxp241.com/2025/06/11/diversification-des-partenariats-strategiques-oligui-nguema-devise-avec-le-chinois-norinco/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-11T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'edce686d-2d44-4ae8-9f34-cb0794a9072e',
        'Développement agricole : Des équipements de pointe pour les producteurs de Lambaréné',
        'Le ministre de l''Agriculture a remis aux producteurs de Lambaréné du matériel agricole moderne pour améliorer leur productivité.',
        'https://gabonactu.com/blog/2025/06/12/developpement-agricole-des-equipements-de-pointe-pour-les-producteurs-de-lambarene/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '209d077d-c45c-40cb-ba13-d473174587f4',
        'Route Mikouyi – Pont Alembe: Bientôt l’ouverture du chantier.',
        'Le chantier pour la construction de la route entre Mikouyi et le pont Alembe va bientôt commencer, améliorant ainsi l''accès aux infrastructures et la fiabilité des déplacements dans la région.',
        'https://gabonactu.com/blog/2025/06/11/route-mikouyi-pont-alembe-bientot-louverture-du-chantier/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3293e1e8-b88f-407d-859e-711c3f80b2be',
        'Opération reprise administrative des terrains du domaine public: OLIGUI NGUEMA instruit le démarrage immédiat des travaux',
        'Le président a donné des instructions pour démarrer immédiatement la réhabilitation des terrains publics dans le cadre d''une opération administrative, en collaboration avec plusieurs ministères et agences, afin de gérer efficacement les espaces urbains.',
        'https://vxp241.com/2025/06/12/operation-reprise-administrative-des-terrains-du-domaine-public-oligui-nguema-instruit-le-demarrage-immediat-des-travaux/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8699dbdf-6fce-4e20-af9a-27a64a42491d',
        'Cité administrative : Oligui Nguema exige le démarrage immédiat des chantiers',
        'Les responsables de la cité administrative d’Olinga demandent que les travaux de construction avancent rapidement pour terminer le projet.',
        'https://gabonmediatime.com/cite-administrative-oligui-nguema-exige-le-demarrage-immediat-des-chantiers/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '41ede348-8d97-455d-8439-7d2187c3f508',
        'Port d’Owendo : nouvelle procédure de sortie des véhicules importés, le coup de force réglementaire du ministère des Transports',
        'Le ministère des Transports introduit une nouvelle procédure pour la sortie des véhicules importés au port de Dowendo, renforçant ainsi le cadre réglementaire et la réglementation en vigueur.',
        'https://gabonmediatime.com/port-dowendo-nouvelle-procedure-de-sortie-des-vehicules-importes-le-coup-de-force-reglementaire-du-ministere-des-transports/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '90470336-a19e-4026-bb5a-ffc9e02a7c52',
        'Gabon : promis pour avril 2025, le Port de Ndjolé toujours en attente de livraison',
        'Le port de Ndjolé, prévu pour livraison en avril 2025, rencontre encore des difficultés et reste en attente d''achèvement, ce qui retarde son développement.',
        'https://gabonmediatime.com/gabon-promis-pour-avril-2025-le-port-de-ndjole-toujours-en-attente-de-livraison/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '13e1e848-0d88-4123-8d87-f0ab88073a67',
        'Cité administrative : Oligui Nguema exige le démarrage immédiat des chantiers',
        'Le maire d''Ogui, Nguema, exige la réalisation immédiate des travaux dans la cité administrative pour permettre son bon fonctionnement.',
        'https://gabonmediatime.com/cite-administrative-oligui-nguema-exige-le-demarrage-immediat-des-chantiers/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '76a94fde-fad0-44dd-be03-b66176fb215f',
        'Port d’Owendo : nouvelle procédure de sortie des véhicules importés, le coup de force réglementaire du ministère des Transports',
        'Le ministère des Transports gabonais a mis en place une nouvelle procédure pour la sortie des véhicules importés au port de Dowendo, renforçant ainsi le contrôle réglementaire.',
        'https://gabonmediatime.com/port-dowendo-nouvelle-procedure-de-sortie-des-vehicules-importes-le-coup-de-force-reglementaire-du-ministere-des-transports/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58e009c4-732b-43a7-86e6-f16faebeee98',
        'Gabon : promis pour avril 2025, le Port de Ndjolé toujours en attente de livraison',
        'Le port de Ndjolé, prévu pour livraison en avril 2025, demeure en attente malgré les promesses faites, ce qui suscite des préoccupations quant à son avancement.',
        'https://gabonmediatime.com/gabon-promis-pour-avril-2025-le-port-de-ndjole-toujours-en-attente-de-livraison/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b80282b6-0ad1-44d9-8a4b-0a9693a9d6d0',
        'Pascaline Bongo inculpée en France dans une affaire de blanchiment et de corruption',
        'La sœur de l’ancien président gabonais Ali Bongo est mise en cause pour avoir été bénéficiaire d’une structure financière à Hong Kong, dans une affaire de blanchiment et de corruption en France.',
        'https://www.jeuneafrique.com/1696149/politique/pascaline-bongo-inculpee-en-france-dans-une-affaire-de-blanchiment-et-de-corruption/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8f78b4a2-5420-4659-b941-76d435d2e4d3',
        'Distribution de produits pétroliers : Gab’Oil, une entreprise «maudite» vouée à disparaître ?',
        'Gab’Oil, entreprise clé pour la distribution des produits pétroliers au Gabon, connaît une crise financière profonde qui menace sa survie et suscite des inquiétudes chez ses partenaires et consommateurs.',
        'https://www.gabonreview.com/distribution-de-produits-petroliers-gaboil-une-entreprise-maudite-vouee-a-disparaitre%e2%80%89/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'baa9ac98-defb-4e1e-bb07-9f6a9752d857',
        'Publié le 12 / 06 / 2025',
        'Le président assure que tous les titulaires de titres fonciers seront dédommagés lors des opérations de déguerpissement.',
        'https://union.sonapresse.com/fr/operation-de-deguerpissement-le-chef-de-letat-assure-que-tous-les-detenteurs-dun-titre-foncier',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1a920b6c-dbda-40f9-9554-65f164031be2',
        'Publié le 11 / 06 / 2025',
        'L''article compare la gestion de l''expulsion des habitants à la Plaine Oury par le gouvernement à la méthode d''Ali Bongo, en soulignant un contraste dans les approches et les conséquences.',
        'https://union.sonapresse.com/fr/deguerpissements-plaine-orety-le-contraste-avec-la-methode-ali-bongo-pointe-par-bilie-nze',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9bec9731-2cff-41ae-8817-6577865a8c78',
        'Publié le 11 / 06 / 2025',
        'L''article dénonce le manque de soutien diplomatique dans l''affaire Mbanie Bilie Nze et souligne l''abandon de certains principes face à l''omnipotence du pouvoir.',
        'https://union.sonapresse.com/fr/affaire-mbanie-bilie-nze-denonce-un-abandon-diplomatique-et-lopacite-du-pouvoir',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0077d4d2-acda-4017-b60b-fa0338c41ddc',
        'Sécurité alimentaire : entre quête de résultats et mesures exceptionnelles, le pari osé d’Oligui Nguema',
        'Le gouvernement d’Oligui Nguema mise sur des mesures exceptionnelles pour améliorer la sécurité alimentaire, tout en cherchant des résultats rapides dans un contexte difficile.',
        'https://mediapostegabon.com/securite-alimentaire-entre-quete-de-resultats-et-mesures-exceptionnelles-le-pari-ose-doligui-nguema/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62e21382-6fa6-4c0f-bc72-4f6044c2e1d3',
        'Reprise administrative des terrains du domaine public : Oligui Nguema veut voir clair',
        'Le président gabonais a demandé aux autorités d’accélérer la récupération des terrains publics et de punir ceux qui spéculent ou détournent ces espaces.',
        'https://www.gabonreview.com/reprise-administrative-des-terrains-du-domaine-public-oligui-nguema-veut-voir-clair/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dd90129-3211-47f8-aa51-eb20d18c160c',
        'Publié le 12 / 06 / 2025',
        'Le président assure que tous les titulaires d’un titre foncier pourront participer à la procédure de déguerpissement et régulariser leur situation.',
        'https://union.sonapresse.com/fr/operation-de-deguerpissement-le-chef-de-letat-assure-que-tous-les-detenteurs-dun-titre-foncier',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a718483f-179b-4b95-988a-6a6ad1805fa8',
        'Publié le 11 / 06 / 2025',
        'L''article compare la méthode d''éviction des personnes à Bongoville avec celle de l''ancien président Ali Bongo, en soulignant les différences dans leurs approches et méthodes de gestion des délogements.',
        'https://union.sonapresse.com/fr/deguerpissements-plaine-orety-le-contraste-avec-la-methode-ali-bongo-pointe-par-bilie-nze',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dbab5ee5-fd13-4033-807c-5b9812d126bc',
        'Publié le 11 / 06 / 2025',
        'L''article dénonce l''abandon diplomatique et le déclin du pouvoir politique du président Mbanie Bilie Nze face aux enjeux de sa gouvernance.',
        'https://union.sonapresse.com/fr/affaire-mbanie-bilie-nze-denonce-un-abandon-diplomatique-et-lopacite-du-pouvoir',
        'L''union',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c0bbe217-8477-4d86-be2b-5e6bc3180426',
        'Sécurité alimentaire : entre quête de résultats et mesures exceptionnelles, le pari osé d’Oligui Nguema',
        'Oligui Nguema mise sur des mesures exceptionnelles et des résultats ambitieux pour assurer la sécurité alimentaire en Guinée équatoriale, confrontée à des défis importants dans ce secteur.',
        'https://mediapostegabon.com/securite-alimentaire-entre-quete-de-resultats-et-mesures-exceptionnelles-le-pari-ose-doligui-nguema/',
        'Media Poste Gabon',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e36b924f-2f37-425c-9a6b-fb424ccdf258',
        'Inde : un avion d’Air India avec 242 passagers à bord s’est écrasé à Ahmedabad',
        'Un avion de la compagnie Air India, transportant environ 242 passagers, s''est écrasé ce jeudi à Ahmedabad, en Inde, alors qu''il devait se rendre à Londres.',
        'https://agpgabon.ga/inde-un-avion-dair-india-avec-242-passagers-a-bord-sest-ecrase-a-ahmedabad/',
        'AGP',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e2bdcad-cf1c-465d-b83e-f817fe19dee8',
        'Centrafrique : 2 000 corps exhumés à Bangui pour l’élargissement d’une route',
        'En Centrafrique, environ 2 000 corps ont été exhumés pour élargir une route menant à l’aéroport, dans le cadre de projets d’amélioration des infrastructures routières à Bangui.',
        'https://agpgabon.ga/centrafrique-2-000-corps-exhumes-a-bangui-pour-lelargissement-dune-route/',
        'AGP',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ce492931-bf21-4054-83db-7ade998181f0',
        'Gabon/Port-Gentil : un mineur condamné à cinq ans de prison pour vol avec arme',
        'Un mineur de 17 ans a été condamné à cinq ans de prison pour avoir volé une chaîne à un élève avec une arme dans un lycée de Port-Gentil.',
        'https://agpgabon.ga/gabon-port-gentil-un-mineur-condamne-a-cinq-ans-de-prison-pour-vol-avec-arme/',
        'AGP',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b238cd5d-4bbe-43f2-aa82-822e35da6954',
        'Port-Gentil : 18 mois de prison pour un détenu mineur triple récidiviste pour vol avec usage d’arme apparente en bande organisée',
        'Un mineur récidiviste a été condamné à 18 mois de prison pour avoir volé avec une arme apparente dans une bande organisée à Port-Gentil.',
        'https://gabonactu.com/blog/2025/06/12/port-gentil-18-mois-de-prison-pour-un-detenu-mineur-triple-recidiviste-pour-vol-avec-usage-darme-apparente-en-bande-organisee/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '25213012-f8a4-497d-ae8a-b8e2b22a9042',
        'Réforme des partis politiques : «une entreprise de domestication du pluralisme», selon Bilie-By-Nze',
        'L''ancien Premier ministre Alain-Claude Bilie-By-Nze critique la réforme des partis politiques, qu''il qualifie d''entreprise visant àLimiter la diversité du pluralisme politique dans le pays.',
        'https://www.gabonreview.com/reforme-des-partis-politiques-une-entreprise-de-domestication-du-pluralisme-selon-bilie-by-nze/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31ca4602-518e-4e24-abfb-0f887b4012f6',
        'Protection des consommateurs : l’Agasa chiffre ses besoins à 3,3 milliards de FCFA',
        'L’Agasa a estimé ses besoins financiers à 3,3 milliards de FCFA pour se moderniser et devenir une référence en sécurité alimentaire d’ici 2027, en mettant en place un plan triennal de restructuration.',
        'https://www.gabonreview.com/protection-des-consommateurs-lagasa-chiffre-ses-besoins-a-33-milliards-de-fcfa/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5dd7a210-7d59-43c2-90d8-37c141577735',
        'Le président Oligui Nguema renforce le partenariat stratégique avec la Chine à travers Norinco',
        'Le président gabonais a rencontré les responsables de l''entreprise chinoise Norinco pour renforcer un partenariat stratégique multifacette entre le Gabon et la Chine, notamment dans les domaines de la défense et des ressources naturelles.',
        'https://www.gabonreview.com/le-president-oligui-nguema-renforce-le-partenariat-strategique-avec-la-chine-a-travers-norinco/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3d5a38a1-297d-4176-942d-f5c844c0d730',
        'Libreville/ Sécurité alimentaire : l''AGASA frappe fort contre l''insalubrité dans la restauration de rue',
        'L’Agence gabonaise de sécurité alimentaire a fermé plusieurs points de vente de nourriture de rue en raison de graves manquements à l’hygiène, mettant en danger la santé des consommateurs.',
        'https://www.gabonews.com/fr/actus/societe/article/libreville-securite-alimentaire-l-agasa-frappe',
        'Gabonews',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9dbbfd10-e927-4d24-987b-5cdb1770363f',
        'Afrique du Sud : le président Ramaphosa annonce un dialogue national',
        'Le président sud-africain a annoncé le lancement d’un grand dialogue national pour permettre aux citoyens de s’exprimer sur leurs préoccupations, avec une première rencontre prévue en août 2025 et un bilan en début 2026.',
        'https://agpgabon.ga/afrique-du-sud-le-president-ramaphosa-annonce-un-dialogue-national/',
        'AGP',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a2fbdc4c-18a0-4136-b00c-7f919ca8f63d',
        'Naissance du SIEN : Un Syndicat pour les Inspecteurs de l’Éducation Nationale',
        'Les inspecteurs de l’Éducation nationale au Gabon ont créé un syndicat, le SIEN, pour défendre leurs droits et améliorer leurs conditions de travail.',
        'https://gabonactu.com/blog/2025/06/12/naissance-du-sien-un-syndicat-pour-les-inspecteurs-de-leducation-nationale/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8a434dc-f6fb-4e52-a017-428e52067bb7',
        'Expropriations au quartier Plaine Orety de Libreville : les populations impactées seront relogées, rassure la Présidence',
        'La présidence de Libreville assure que les personnes dont les maisons seront expropriées dans le quartier Plaine Orety seront relogées dans le cadre du projet de développement urbain.',
        'https://gabonactu.com/blog/2025/06/12/expropriations-au-quartier-plaine-orety-de-libreville-les-populations-impactees-seront-relogees-rassure-la-presidence/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af6af35b-e418-43a5-82e4-528f759df99b',
        'Interdiction d’exportation du manganèse brut : Eramet et Comilog adhèrent',
        'Eramet et Comilog ont accepté d’interdire l’exportation de manganèse brut afin de valoriser davantage cette ressource en la transformant localement.',
        'https://gabonactu.com/blog/2025/06/12/interdiction-dexportation-du-manganese-brut-eramet-et-comilog-adhere/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9ff36c1-39f5-4950-9ac9-a42a6ecb3c02',
        'Déguerpissement à Libreville : «Les services compétents sont à l’œuvre pour que les droits légitimes des compatriotes soient pris en compte», porte-parole de la Présidence',
        'Les services compétents travaillent pour s’assurer que les droits légitimes des citoyens soient respectés lors du processus de déguerpissement à Libreville.',
        'https://www.gabonreview.com/deguerpissement-a-libreville-les-services-competents-sont-a-loeuvre-pour-que-les-droits-legitimes-des-compatriotes-soient-pris-en-compte-porte-parole-de-la-presidence/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '061e8e70-b1c9-4c0d-9def-bf89fe99b222',
        'Outrage au président gabonais : l’ambassadrice du Cameroun condamne fermement les propos d’un compatriote',
        'Une ambassadrice du Cameroun au Gabon a fermement condamné des propos insultants tenus par un compatriote à l’encontre du président gabonais, suscitant une réaction officielle et des mesures légales.',
        'https://gabonactu.com/blog/2025/06/12/outrage-au-president-gabonais-lambassadrice-du-cameroun-condamne-fermement-les-propos-dun-compatriote/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '925da269-1d84-43b8-8133-4841b2e7d48b',
        'Le monde du football gabonais continue de rendre hommage à Boupendza',
        'Le football gabonais continue de rendre hommage à Aaron Boupendza, un joueur apprécié, en évoquant ses performances passées et son impact sur la communauté sportive locale.',
        'https://gabonactu.com/blog/2025/06/12/le-monde-du-football-gabonais-continue-de-rendre-hommage-a-boupendza/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '114a58e8-8de8-4331-bc0a-f9979ca53c60',
        'Reprise des travaux sur les terrains du domaines publics de l’État, sur ordre du président Oligui Nguéma',
        'Le gouvernement gabonais a commencé la reprise des terrains publics de l''État à Libreville, conformément à un ordre du président Oligui Nguéma, afin de régulariser leur situation et d''améliorer la gestion foncière.',
        'https://gabonactu.com/blog/2025/06/12/libreville-debut-des-travaux-de-reprise-des-terrains-de-letat-sur-ordre-du-president-oligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f2b68f00-31a6-47be-ba41-d7f4e80088b3',
        'Pascaline Bongo, sœur de l''ex-président gabonais, visée par une nouvelle procédure en France',
        'Pascaline Bongo, sœur et fille héritière d''Omar Bongo, a été mise en examen en France en janvier pour blanchiment de corruption d''un agent public étranger dans le contexte de procédures judiciaires.',
        'https://www.rfi.fr/fr/afrique/20250612-pascaline-bongo-s%C5%93ur-de-l-ex-pr%C3%A9sident-gabonais-vis%C3%A9e-par-une-nouvelle-proc%C3%A9dure-en-france',
        'RFI',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a3e4af3a-120b-448f-97fc-d6ebcf34dd30',
        'Le Chef de l''État rend hommage à feu le Général d''Armée Idriss Firmin Ngari',
        'Le Président de la République, Brice Clotaire Oligui Nguema, a rendu un dernier hommage au général Idriss Firmin Ngari, décédé à l''âge de 79 ans au Maroc, lors d’une cérémonie à Baraka.',
        'https://www.gabonews.com/fr/actus/necrologie/article/libreville-le-12-juin-2025-le-president-de-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-12T00:00:00.000Z',
        '2025-09-15T23:06:12.455Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

