-- Batch 2 - Section 15/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '3850f3a4-b81a-4968-9c37-6707fa430864',
        'Minerai de fer : Genmin et Sinohydro s’unissent pour accélérer le développement de Baniaka',
        'La société minière Genmin et le géant chinois Sinohydro ont signé un accord pour accélérer le développement du projet de fer de Baniaka au Gabon, visant à renforcer les infrastructures et la production minière dans la région. Ce partenariat stratégique devrait stimuler l''économie locale et créer des emplois.',
        'https://www.gabonreview.com/minerai-de-fer-genmin-et-sinohydro-sunissent-pour-accelerer-le-developpement-de-baniaka/',
        'Gabon Review',
        'Services, Commerce, Agriculture',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17995bdf-aaed-4ba3-b846-fa674ceb6194',
        'Investiture présidentielle : mobilisation citoyenne et opérations savon-balayette à Akanda',
        'Des citoyens se sont mobilisés à Akanda pour nettoyer les rues avant l’investiture présidentielle, montrant un engagement communautaire envers l’environnement et la célébration nationale. Cette initiative symbolise à la fois la préparation pour l’événement et une volonté de changement.',
        'https://www.gabonreview.com/investiture-presidentielle-mobilisation-citoyenne-et-operations-savon-balayette-a-akanda/',
        'Gabon Review',
        'Services, Agriculture, Numérique / Digital',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bf494aed-9427-4af2-8f58-ee540897b371',
        'Préservation des forêts du Bassin du Congo : le Gabon mise sur la communication stratégique',
        'Le Gabon renforce ses efforts pour protéger les forêts du bassin du Congo en adoptant une stratégie de communication visant à sensibiliser et mobiliser les acteurs locaux et internationaux sur cet enjeu environnemental crucial.',
        'https://www.gabonreview.com/preservation-des-forets-du-bassin-du-congo-le-gabon-mise-sur-la-communication-strategique/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '70e5ec30-43d9-4528-8626-f86ca1bde4b5',
        'Religion : la dépouille du Pape est arrivée à Saint-Pierre pour l’hommage des fidèles',
        'La dépouille du pape est arrivée à Saint-Pierre où les fidèles peuvent lui rendre hommage.',
        'https://agpgabon.ga/2025/04/23/religion-la-depouille-du-pape-est-arrivee-a-saint-pierre-pour-lhommage-des-fideles/',
        'AGP',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2d77a09-5e20-4c28-a973-34876a0e1134',
        'Obsèques du Pape François : 3 jours de recueillement, drapeaux en berne et Oligui Nguéma attendu au Vatican',
        'Le Gabon observe trois jours de recueillement et met les drapeaux en berne suite au décès du pape François, en hommage à sa mémoire.',
        'https://gabonactu.com/blog/2025/04/23/gabon-deces-du-pape-francois-3-jours-de-recueillement-et-drapeaux-en-berne/',
        'Gabon Actu',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7aa0440-193f-4241-927a-3070dde031bb',
        'Tensions à l’ENAM : les 7 étudiants interpelés ne sont pas encore libérés malgré les assurances du ministre de la culture',
        'Sept étudiants interpellés lors de tensions à l’ENAM au Gabon n’ont toujours pas été libérés, malgré les promesses du ministre de la Culture. La situation suscite des inquiétudes quant au respect des droits des étudiants et à l’apaisement des conflits sur le campus.',
        'https://gabonactu.com/blog/2025/04/23/tensions-a-lenam-les-7-etudiants-interpeles-ne-sont-pas-encore-liberes-malgre-les-assurances-du-ministre-de-la-culture/',
        'Gabon Actu',
        'Éducation, Services',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36c73706-a709-4dbf-a122-957bab104423',
        'Décès du pape François : le Gabon met ses drapeaux en berne en signe de deuil national',
        'Le Gabon a décidé de mettre ses drapeaux en berne en signe de deuil national suite au décès du pape François, marquant ainsi le respect et la tristesse du pays.',
        'https://www.gabonreview.com/deces-du-pape-francois-le-gabon-met-ses-drapeaux-en-berne-en-signe-de-deuil-national/',
        'Gabon Review',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c44d39be-8c71-47e7-ab8d-7f8acdcda5fc',
        'Gabon/Décès d’Aaron Boupendza : l’État et la famille s’activent pour les obsèques',
        'L’État gabonais et la famille d’Aaron Boupendza s’organisent pour les obsèques du défunt, suite à son décès récent. Les préparatifs sont en cours pour lui rendre un dernier hommage digne.',
        'https://agpgabon.ga/2025/04/23/gabon-deces-daaron-boupendza-letat-et-la-famille-sactivent-pour-les-obseques/',
        'AGP',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a55dcbfe-84b6-45db-a73b-0aa3c7016c96',
        'Des obsèques dignes pour Aaron Boupendza',
        'Le joueur gabonais Aaron Boupendza a reçu des funérailles solennelles en présence de proches, de supporters et de personnalités, marquant un hommage émouvant à sa carrière et à son impact. La cérémonie a reflété l’affection et le respect portés à l’athlète disparu.',
        'https://gabonactu.com/blog/2025/04/23/des-obseques-dignes-pour-aaron-boupendza/',
        'Gabon Actu',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7db0bd07-2084-4120-9464-8e854de3ba90',
        'Coopération Gabon – Suisse : Au tour de Chasper Sarott de faire ses adieux à Ndong Sima',
        'Le conseiller économique suisse Chasper Sarott a quitté le Gabon après quatre ans de coopération marqués par des projets dans l''éducation et la formation professionnelle, saluant les progrès accomplis. Son départ coïncide avec la fin de son mandat et la poursuite des engagements entre les deux pays.',
        'https://www.gabonreview.com/cooperation-gabon-suisse-au-tour-de-chasper-sarott-de-faire-ses-adieux-a-ndong-sima/',
        'Gabon Review',
        'Éducation, Services, Numérique / Digital',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '08b7cbe2-90c3-49eb-a80c-7c62b32c7a40',
        'Bilie-By-Nze : « je ne féliciterai pas quelqu’un qui a verrouillé la Constitution »',
        'L’article critique la décision de verrouiller la constitution, considérant qu’il ne s’agit pas d’un acte méritant des félicitations, car cela limite les libertés démocratiques.',
        'https://gabonmediatime.com/bilie-by-nze-je-ne-feliciterai-pas-quelquun-qui-a-verrouille-la-constitution/',
        'Gabon Media Time',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c37f447d-bea9-49b6-b598-571bd04cf765',
        'Gabon : RSF pour un soutien financier transparent et impartial aux entreprises de presse',
        'RSF appelle à une allocation transparente et équitable des fonds publics aux médias gabonais, afin de garantir leur indépendance et éviter toute instrumentalisation politique.',
        'https://gabonmediatime.com/gabon-rsf-pour-un-soutien-financier-transparent-et-impartial-aux-entreprises-de-presse/',
        'Gabon Media Time',
        'Numérique / Digital, Finances, Services',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96dc1e52-1c46-46e7-985f-5b66eb17c214',
        'Gabon : la CDC opposée à un contrôle de ses activités par la COBAC',
        'La Caisse des Dépôts et Consignations (CDC) du Gabon refuse le contrôle de ses activités par la COBAC, l''organe de régulation bancaire en Afrique centrale, affirmant que cette supervision n''est pas prévue par ses statuts. Cette opposition soulève des questions sur la transparence et la conformité de l''institution financière.',
        'https://gabonmediatime.com/gabon-la-cdc-opposee-a-un-controle-de-ses-activites-par-la-cobac/',
        'Gabon Media Time',
        'Finances, Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5415f7b4-8a1c-43d6-bb18-bb2fef07fb5a',
        'Gabon/Patricia Gislaine Étome prend la tête de l’Observatoire national de l’Emploi et de la Formation : cap sur l’efficacité et ...',
        'Patricia Gislaine Etome a été nommée à la tête de l''Observatoire national de l''emploi et de la formation au Gabon, avec pour mission d''améliorer l''efficacité et d''encourager l''innovation dans ces domaines. Son rôle consistera à optimiser les politiques publiques pour répondre aux besoins du marché du travail et de la formation professionnelle.',
        'https://kongossanews.info/gabon-patricia-gislaine-etome-prend-la-tete-de-lobservatoire-national-de-lemploi-et-de-la-formation-cap-sur-lefficacite-et-linnovation/',
        'Kongossa News',
        'Éducation, Services, Numérique / Digital',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7b05b3d-06e7-42a5-bcd2-77603bcf8450',
        'Biendi Maganga Moussavou bientôt traduit en justice pour violences et actes de torture sur une employée domestique ?',
        'Biendi Maganga Moussavou, ministre gabonais, pourrait être poursuivi en justice pour des accusations de violences et d’actes de torture sur une employée domestique. L’affaire a suscité des réactions et des demandes de clarification de la part des autorités.',
        'https://kongossanews.info/biendi-maganga-moussavou-bientot-traduit-en-justice-pour-violences-et-actes-de-torture-sur-une-employee-domestique/',
        'Kongossa News',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '30e9257a-9477-4f07-aaa5-6f1333748793',
        'Publié le 23 / 04 / 2025',
        'Ella Nguema plaide pour la création d''une commission vérité et réconciliation au Gabon afin de favoriser la justice transitionnelle et la paix sociale après les crises politiques récentes. Elle souligne l''importance du dialogue et de la transparence pour reconstruire la confiance entre les citoyens et les institutions.',
        'https://union.sonapresse.com/fr/ella-nguema-appelle-la-mise-en-place-dune-commission-verite-et-reconciliation',
        'L''union',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '289eb3f3-f5fb-46b7-b0d1-cbfa5613fa4c',
        'Publié le 23 / 04 / 2025',
        'L''article présente les partenaires officiels de la campagne présidentielle, mettant en avant leur rôle et leur soutien dans le processus électoral. Ces collaborations illustrent l''engagement de divers acteurs en faveur de la démocratie et de la transparence.',
        'https://union.sonapresse.com/fr/presidentielle-et-voici-les-partenaires',
        'L''union',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2463b374-fb79-4cd1-bd48-6909fe68d05a',
        'Publié le 23 / 04 / 2025',
        'La Cour constitutionnelle n''a toujours pas proclamé les résultats de l''élection présidentielle, prolongeant l''attente et les incertitudes autour du scrutin.',
        'https://union.sonapresse.com/fr/cour-constitutionnelle-la-proclamation-des-resultats-de-la-presidentielle-toujours-attendue',
        'L''union',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7a308b8-5b94-4aea-bf8b-45ade86c1e5c',
        'Côte d’Ivoire : l’opposant Tidjane Thiam radié de la liste électorale',
        'Tidjane Thiam, opposant politique en Côte d’Ivoire, a été radié de la liste électorale, ce qui pourrait affecter sa participation aux prochains scrutins. Cette décision soulève des questions sur les critères et les motivations derrière cette exclusion.',
        'https://agpgabon.ga/2025/04/23/cote-divoire-lopposant-tidjane-thiam-radie-de-la-liste-electorale/',
        'AGP',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7bdf84af-8f43-4efc-9fa6-f5233e4eaa58',
        'Victoire d’Oligui Nguema au Gabon : cartographie d’un plébiscite',
        'Victoire Oligui Nguéma a remporté une large victoire aux élections au Gabon, confirmant un soutien massif à travers le pays. Les résultats montrent une domination dans la plupart des régions, reflétant une adhésion générale à son leadership.',
        'https://www.jeuneafrique.com/1682035/politique/victoire-doligui-nguema-au-gabon-cartographie-dun-plebiscite/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75e34468-f116-4468-ace8-f46d804428e5',
        'Bilie-By-Nze : « je ne féliciterai pas quelqu’un qui a verrouillé la Constitution »',
        'L’auteur critique une personne qui a modifié la constitution pour conserver le pouvoir, affirmant qu’il ne la félicitera pas pour un acte qu’il considère antidémocratique. Il souligne que verrouiller la constitution nuit à la transparence et à l’alternance politique.',
        'https://gabonmediatime.com/bilie-by-nze-je-ne-feliciterai-pas-quelquun-qui-a-verrouille-la-constitution/',
        'Gabon Media Time',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dea4548f-df40-4953-8868-e87c540efc3a',
        'Gabon : RSF pour un soutien financier transparent et impartial aux entreprises de presse',
        'RSF appelle à une allocation transparente et équitable des fonds publics pour soutenir les médias gabonais, afin d''éviter les favoritismes et garantir leur indépendance.',
        'https://gabonmediatime.com/gabon-rsf-pour-un-soutien-financier-transparent-et-impartial-aux-entreprises-de-presse/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8a436fce-19f8-450e-a5a9-17f98e36f564',
        'Gabon : la CDC opposée à un contrôle de ses activités par la COBAC',
        'La Caisse des Dépôts et Consignations (CDC) du Gabon refuse de soumettre ses activités au contrôle de la COBAC, l’organe de régulation bancaire en Afrique centrale, invoquant son statut spécial d’institution publique. Cette opposition soulève des questions sur la transparence et la conformité financière de l’établissement.',
        'https://gabonmediatime.com/gabon-la-cdc-opposee-a-un-controle-de-ses-activites-par-la-cobac/',
        'Gabon Media Time',
        'Finances, Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b46a76c-e960-4df4-91e7-1e9e7318627a',
        'Gabon/Patricia Gislaine Étome prend la tête de l’Observatoire national de l’Emploi et de la Formation : cap sur l’efficacité et ...',
        'Patricia Gislaine Etome a été nommée à la tête de l''Observatoire national de l''emploi et de la formation au Gabon, avec pour mission d''améliorer l''efficacité et d''encourager l''innovation dans ces domaines.',
        'https://kongossanews.info/gabon-patricia-gislaine-etome-prend-la-tete-de-lobservatoire-national-de-lemploi-et-de-la-formation-cap-sur-lefficacite-et-linnovation/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae22ae3d-c86d-4d19-81e0-0a094efe4eb4',
        'Biendi Maganga Moussavou bientôt traduit en justice pour violences et actes de torture sur une employée domestique ?',
        'Biendi Maganga Moussavou, ministre gabonais, risque des poursuites judiciaires pour violences et actes de torture présumés sur une employée domestique, selon des révélations récentes.',
        'https://kongossanews.info/biendi-maganga-moussavou-bientot-traduit-en-justice-pour-violences-et-actes-de-torture-sur-une-employee-domestique/',
        'Kongossa News',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d0c1d48-4ded-4081-89fa-eb436351cf14',
        'Publié le 23 / 04 / 2025',
        'Ella Nguema plaide pour la création d''une commission vérité et réconciliation au Gabon afin de favoriser le dialogue national et la paix sociale après les tensions politiques récentes. Elle souligne l''importance de cette initiative pour guérir les divisions et construire un avenir commun.',
        'https://union.sonapresse.com/fr/ella-nguema-appelle-la-mise-en-place-dune-commission-verite-et-reconciliation',
        'L''union',
        'Services, Éducation',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '023d66b1-ea02-4be1-8d9d-e4a382009e2f',
        'Publié le 23 / 04 / 2025',
        'L''article présente les partenariats établis pour soutenir une campagne présidentielle, mettant en avant les collaborations avec diverses organisations et entités. Ces alliances visent à renforcer la portée et l''impact de la campagne électorale.',
        'https://union.sonapresse.com/fr/presidentielle-et-voici-les-partenaires',
        'L''union',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6a48f21-1d72-4dbb-a9a4-b822c4611be2',
        'Publié le 23 / 04 / 2025',
        'La Cour constitutionnelle n''a pas encore proclamé les résultats définitifs de l''élection présidentielle, prolongeant l''attente des citoyens et des institutions. La situation reste en suspens, sans précision sur les délais ou les éventuelles contestations.',
        'https://union.sonapresse.com/fr/cour-constitutionnelle-la-proclamation-des-resultats-de-la-presidentielle-toujours-attendue',
        'L''union',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a0af0e1-1075-455f-b02b-f19b14112051',
        'Gabon : l’ambassadeur de Suisse fait ses adieux au Premier ministre',
        'L’ambassadeur de Suisse au Gabon a rencontré le Premier ministre pour une visite d’adieu, marquant la fin de sa mission diplomatique dans le pays. Les échanges ont porté sur les relations bilatérales et les perspectives de coopération future.',
        'https://agpgabon.ga/2025/04/23/gabon-lambassadeur-de-suisse-fait-ses-adieux-au-premier-ministre/',
        'AGP',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb1e2d7a-b4aa-4f46-957a-6ed91466d3af',
        'Victoire d’Oligui Nguema au Gabon : cartographie d’un plébiscite',
        'Victoire Oligui Nguéma remporte une large victoire aux élections au Gabon, confirmant un soutien massif à travers le pays. Les résultats montrent une domination écrasante dans la plupart des régions, reflétant une adhésion populaire significative.',
        'https://www.jeuneafrique.com/1682035/politique/victoire-doligui-nguema-au-gabon-cartographie-dun-plebiscite/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b173c1c0-47fa-4dc5-abac-21af9667d2c3',
        'Gabon/ANPI : 4018 entreprises créées au 1er trimestre 2025',
        'Au premier trimestre 2025, l''ANPI du Gabon a enregistré la création de 4 018 entreprises, reflétant une dynamique économique positive dans le pays. Cette hausse illustre l''engagement des entrepreneurs locaux et l''efficacité des mesures gouvernementales pour faciliter les démarches commerciales.',
        'https://agpgabon.ga/2025/04/23/gabon-anpi-4018-entreprises-creees-au-1er-trimestre-2025/',
        'AGP',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-04-23T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1d0a0892-8259-4030-9fe1-83f944f44b9e',
        'Pêche : le Gabon et le Japon renforcent leur partenariat',
        'Le Gabon et le Japon renforcent leur collaboration dans le secteur de la pêche, notamment pour améliorer les techniques de pêche durable et soutenir les communautés locales. Cet accord vise à promouvoir le développement économique tout en préservant les ressources marines.',
        'https://agpgabon.ga/2025/04/23/peche-le-gabon-et-le-japon-renforcent-leur-partenariat/',
        'AGP',
        'Agriculture, Services, Tourisme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de551a48-25f4-48e9-85d2-c6832c291556',
        'Charles M''ba et Mark-Alexandre Doumba à Washington dans le cadre des Réunions de Printemps du Fond monétaire international',
        'Deux entrepreneurs gabonais, Charles M. Ba et Mark Alexandre Doumba, discutent des défis et opportunités du secteur économique au Gabon, mettant l''accent sur l''innovation et la jeunesse comme leviers de développement.',
        'https://www.gabonews.com/fr/actus/economie/article/charles-m-ba-et-mark-alexandre-doumba-a',
        'Gabonews',
        'Numérique / Digital, Services, Finances, Éducation, Business Femme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d83c574-3824-4f98-a770-40c38446c500',
        'Dernière visite de l''ambassadeur de Suisse au Gabon chez le Chef du Gouvernement de la Transition',
        'L’ambassadeur de Suisse au Gabon a effectué une dernière visite officielle pour renforcer les liens de coopération entre les deux pays, notamment dans les domaines de l’éducation et du développement. Cette rencontre a permis d’évoquer les projets en cours et les perspectives futures de collaboration.',
        'https://www.gabonews.com/fr/actus/cooperation/article/derniere-visite-de-l-ambassadeur-de-suisse-au',
        'Gabonews',
        'Éducation, Services, Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f9e931bb-7394-4313-9640-3da9416108f5',
        'Cote d''Ivoire : Tidjane Thiam hors course à la présidentielle',
        'Tidjane Thiam, ancien directeur général de Credit Suisse, ne sera pas candidat à la prochaine élection présidentielle en Côte d''Ivoire, mettant fin aux spéculations sur son implication dans la course.',
        'https://www.gabonews.com/fr/actus/international/article/cote-d-ivoire-tidjane-thiam-hors-course-a-la',
        'Gabonews',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f7502e3-3cc5-4093-87f5-dd458765282a',
        'Port-Gentil : Junior Matoumba alias  »Scanner » jeté  en prison pour vol aggravé',
        'Un jeune surnommé "Scanner" a été condamné à une peine de prison pour vol aggravé à Port-Gentil, après avoir dérobé des objets de valeur lors d''un cambriolage. L''affaire rappelle l''importance de la lutte contre la délinquance juvénile dans la région.',
        'https://gabonactu.com/blog/2025/04/24/port-gentil-junior-matoumba-alias-scanner-jete-en-prison-pour-vol-aggrave/',
        'Gabon Actu',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c211b0af-60ac-4a92-a9ca-e314c4910a2b',
        'L’élection d’Oligui Nguema est le reflet d’une « société en quête de réconciliation », selon le  Mouvement Générations du Progrès',
        'L''élection d''Oligui Nguéma est perçue par le mouvement Générations du Progrès comme un symbole de réconciliation nationale, reflétant les aspirations d''une société gabonaise en quête d''unité et de stabilité.',
        'https://gabonactu.com/blog/2025/04/24/lelection-doligui-nguema-est-le-reflet-dune-societe-en-quete-de-reconciliation-selon-le-mouvement-generations-du-progres/',
        'Gabon Actu',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.424Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dca77ecd-04bb-4e50-b307-77c1df462cd2',
        'Gabon : Un Plan stratégique d’investissement pour relancer le secteur de l’énergie',
        'Le Gabon prévoit un plan stratégique d''investissement pour moderniser et relancer son secteur énergétique, visant à améliorer l''accès à l''électricité et à promouvoir les énergies renouvelables. Ce plan inclut des partenariats publics-privés et des réformes pour renforcer la production et la distribution d''énergie.',
        'https://www.gabonreview.com/gabon-un-plan-strategique-dinvestissement-pour-relancer-le-secteur-de-lenergie/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f8c37e22-1cb6-4c23-87f2-92b1e4dcd43b',
        'Gninga Chaning Zenaba : Une voix féminine pour le renouveau politique au Gabon',
        'Gninga Chaning Zenaba est une femme engagée qui utilise sa voix pour promouvoir l''éducation et l''autonomisation des jeunes filles en Afrique, notamment à travers des initiatives technologiques et sociales. Son action vise à briser les barrières et à inspirer les futures générations.',
        'https://www.gabonews.com/fr/actus/nianto/modeles/article/gninga-chaning-zenaba-une-voix-feminine-pour-le',
        'Gabonews',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '132e1156-45e4-4044-8037-02c6a0123323',
        'Il faut 1000 milliards FCFA d’investissement pour mettre fin aux coupures d’Electricité et d’Eau dans le Grand Libreville',
        'Le Grand Libreville a besoin de 1 000 milliards de FCFA d''investissement pour résoudre les problèmes récurrents de coupures d''électricité et d''eau, selon une analyse des besoins du secteur. Ces fonds permettraient de moderniser les infrastructures et d''assurer un approvisionnement stable.',
        'https://gabonactu.com/blog/2025/04/24/il-faut-1000-milliards-fcfa-dinvestissement-pour-mettre-fin-aux-coupures-delectricite-et-deau-dans-le-grand-libreville/',
        'Gabon Actu',
        'Numérique / Digital, Finances, Services',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e27ce029-8e80-4927-bbf0-fe9c05743404',
        'Ministère du Commerce : Vers une gouvernance commerciale plus efficace en territoires',
        'Le ministère gabonais du Commerce renforce sa gouvernance en déployant des équipes dans les territoires pour mieux réguler les prix, lutter contre la vie chère et améliorer le contrôle des activités commerciales. Cette initiative vise à rapprocher l’administration des citoyens et à garantir un marché plus transparent et équitable.',
        'https://www.gabonreview.com/ministere-du-commerce-vers-une-gouvernance-commerciale-plus-efficace-en-territoires/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2391762e-f6c3-4220-ae6a-8ceb85b84202',
        'Gabon/Pétrole : 56 millions de barils découverts au large de Mayumba',
        'Une nouvelle découverte pétrolière de 56 millions de barils a été annoncée au large de Mayumba, au Gabon, renforçant le potentiel énergétique du pays. Cette trouvaille pourrait stimuler l’économie locale et attirer des investissements dans le secteur.',
        'https://agpgabon.ga/2025/04/24/gabon-petrole-56-millions-de-barils-decouverts-au-large-de-mayumba/',
        'AGP',
        'Numérique / Digital, Finances, Commerce',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4c2c714d-46b1-4ab1-98be-782b90133dc0',
        'RSE : Le groupe Eramet a investi plus de 6 milliards de FCFA au Gabon en 2024',
        'Le groupe Eramet a investi plus de 6 milliards de FCFA en 2024 au Gabon dans des projets de responsabilité sociétale, notamment dans l’éducation, la santé et le développement local. Ces initiatives visent à soutenir les communautés locales et à renforcer l’impact positif de l’entreprise dans le pays.',
        'https://directinfosgabon.com/rse-le-groupe-eramet-a-investi-plus-de-6-milliards-de-fcfa-au-gabon-en-2024/',
        'Direct Infos Gabon',
        'Éducation, Services, Agriculture, Tourisme',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e266d06b-4c3c-4188-a60e-bbc593f3bb4b',
        'Comilog et Setrag : Une contribution économique de 494 milliards de francs en 2024',
        'En 2024, Comilog et Setrag, deux entreprises gabonaises, contribueront à hauteur de 494 milliards de francs CFA à l’économie nationale grâce à leurs activités dans le secteur minier et ferroviaire. Ces investissements soutiennent la croissance locale et créent des emplois.',
        'https://directinfosgabon.com/comilog-et-setrag-une-contribution-economique-de-494-milliards-de-francs-en-2024/',
        'Direct Infos Gabon',
        'Services, Finances, Commerce',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c825e71-91bc-495e-805c-cd889147c863',
        'Sécurité alimentaire : L’Agasa va revevoir l’appui du Maroc',
        'Le Maroc va renouveler son soutien à la GASA (Gabon Agriculture and Food Security Agency) pour renforcer la sécurité alimentaire au Gabon, notamment à travers des projets agricoles et des formations techniques. Cette collaboration vise à améliorer la production locale et réduire la dépendance aux importations.',
        'https://directinfosgabon.com/securite-alimentaire-lagasa-va-revevoir-lappui-du-maroc/',
        'Direct Infos Gabon',
        'Agriculture, Éducation, Services',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98c64c79-f1fa-4b30-8682-99bf12e6737b',
        '30ème SIEL : L’UDEG et son Président en Guest Star',
        'Lors de la 30e édition du SIEL, Ludeg et son président ont été mis à l’honneur en tant qu’invités spéciaux, soulignant leur engagement dans l’éducation et la culture au Gabon. Cet événement a permis de valoriser leur contribution au développement des jeunes à travers des initiatives innovantes.',
        'https://gabonactu.com/blog/2025/04/24/30eme-siel-ludeg-et-son-president-en-guest-star/',
        'Gabon Actu',
        'Numérique / Digital, Éducation',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af28c622-b06d-46f5-a177-18573ca12629',
        'Des nouvelles vignettes estampillées Moov Africa Gabon Telecom sur les taxis de Libreville',
        'Des vignettes estampillées Moov Africa Gabon Télécom sont désormais apposées sur les taxis de Libreville pour renforcer la visibilité de la marque et promouvoir ses services auprès des usagers. Cette initiative s’inscrit dans une stratégie de communication et de proximité avec les clients.',
        'https://gabonactu.com/blog/2025/04/24/des-nouvelles-vignettes-estampillees-moov-africa-gabon-telecom-sur-les-taxis-libreville/',
        'Gabon Actu',
        'Numérique / Digital, Services, Commerce',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '469d3301-ba41-4d5e-a2f7-6a1e3100624f',
        'Gabon, Pétrole, BEAC et bras de fer : l’heure de vérité pour la souveraineté monétaire',
        'Le Gabon et la Banque des États de l’Afrique centrale (BEAC) s’opposent sur le contrôle des recettes pétrolières, un conflit qui met en lumière les enjeux de souveraineté monétaire et économique du pays. Cette tension révèle les défis des États africains à maîtriser leurs ressources stratégiques face aux institutions régionales.',
        'https://www.gabonreview.com/gabon-petrole-beac-et-bras-de-fer-lheure-de-verite-pour-la-souverainete-monetaire/',
        'Gabon Review',
        'Finances, Numérique / Digital, Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fc6ab6d1-bb8d-4e89-a9f2-e8359b2f6626',
        'Gabon : après deux années en poste, l’ambassadeur de Suisse fait ses adieux à Ndong Sima',
        'L’ambassadeur de Suisse au Gabon a pris congé après deux ans de mission, marquée par des échanges diplomatiques et économiques entre les deux pays. Il a rencontré le Premier ministre gabonais pour une discussion d’adieu, soulignant les relations bilatérales renforcées durant son mandat.',
        'https://gabonmediatime.com/gabon-apres-deux-annees-en-poste-lambassadeur-de-suisse-fait-ses-adieux-a-ndong-sima/',
        'Gabon Media Time',
        'Autres',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d7a9c66-4de1-4a8a-b36a-17f6e3d381b9',
        'Mabanda : les chefs de quartiers dotés en congélateurs par le président Brice Clotaire Oligui Nguema',
        'Les chefs de quartier de Mabanda ont reçu des congélateurs offerts par le président Brice Clotaire Oligui Nguema pour renforcer leurs capacités locales. Cette initiative vise à améliorer les conditions de vie dans la communauté.',
        'https://kongossanews.info/mabanda-les-chefs-de-quartiers-dotes-en-congelateurs-par-le-president-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Services, Agriculture',
        '2025-04-24T00:00:00.000Z',
        '2025-09-15T23:06:12.425Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

