-- Batch 5 - Section 10/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '547c5ed1-4ccf-455f-ac3a-f4a5f536fead',
        'Donald Trump invite Oligui Nguema à Washington à un sommet restreint',
        'Donald Trump a invité Oligui Nguema à participer à un sommet restreint à Washington avec d''autres dirigeants africains et américains.',
        'https://gabonactu.com/blog/2025/07/03/donald-trump-invite-oligui-nguema-a-washington-a-un-sommet-restreint/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bc6cd473-9c3d-457a-a1bb-b1707787bf76',
        'Les Représentants de la BAD en séance de travail chez Louise Pierrette Mvono, ministre de la Planification et de la Prospective',
        'Une réunion stratégique a été organisée entre la ministre de la Planification du Gabon et des représentants de la BAD pour discuter du développement du pays et préparer le prochain Plan National du Développement 2026-2030.',
        'https://www.gabonews.com/fr/actus/cooperation/article/les-representants-de-la-bad-en-seance-de-travail',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fb637d5b-151e-4aa1-b8db-79ec8edd0f07',
        'Sensibilisation Citoyenne « vote et paix »',
        'Une initiative soutenue par l''ONU, en partenariat avec l''ONG Malachie, vise à sensibiliser les citoyens gabonais à l''importance du vote et de la paix en période électorale, afin de promouvoir un climat électoral apaisé dans la région de l''Ogooué-Maritime.',
        'https://www.gabonews.com/fr/actus/societe/article/sensibilisation-citoyenne-vote-et-paix',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45c48f09-981e-4b83-87a8-fa6011252578',
        'Gabon / Mines : la Chine confirme son intérêt pour le sous-sol gabonais',
        'La Chine montre un vif intérêt pour exploiter les richesses minières du Gabon, notamment le manganèse, le fer, le niobium et les terres rares, à la suite de rencontres bilatérales visant à renforcer la coopération dans le secteur minier.',
        'https://agpgabon.ga/gabon-mines-la-chine-confirme-son-interet-pour-le-sous-sol-gabonais/',
        'AGP',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dbe54866-66a8-48c5-8014-af82db004bed',
        'Football : le président de la Fegafoot reçu par le ministre des Sports',
        'Le président de la Fédération gabonaise de football et le ministre des Sports ont discuté de leur collaboration et des prochaines échéances de l''équipe nationale lors d''une rencontre de prise de contact.',
        'https://agpgabon.ga/football-le-president-de-la-fegafoot-recu-par-le-ministre-des-sports/',
        'AGP',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9c6ea161-c15e-40a8-a3ae-e281afdb2695',
        'Gabon / Digitalisation du système de santé : dix structures hospitalières déjà en immersion',
        'Dix établissements hospitaliers au Gabon sont déjà en phase d''implémentation du projet de digitalisation du système de santé, lancé en février 2024 dans le cadre du programme e-Gabon-SIS.',
        'https://agpgabon.ga/gabon-digitalisation-du-systeme-de-sante-dix-structures-hospitalieres-deja-en-immersion/',
        'AGP',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b3f94329-63ee-4a9a-aa43-9a82c4ffb03a',
        'Le Projet eGabon Lance le « Café des Ambassadeurs » pour Mobiliser les Professionnels de Santé autour du Système d’Information de Santé',
        'Du 2 au 5 juillet 2025, un séminaire et des ateliers sont organisés au Gabon pour mobiliser les professionnels de santé autour du projet eGabon, visant à déployer un Système d’Information de Santé efficace dans le pays.',
        'https://vxp241.com/2025/07/03/le-projet-egabon-lance-le-cafe-des-ambassadeurs-pour-mobiliser-les-professionnels-de-sante-autour-du-systeme-dinformation-de-sante/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2c9f26de-11ee-4a9e-a431-68277003831a',
        'Financement du développement : Le Gabon s’active sur plusieurs fronts',
        'Le Gabon met en œuvre plusieurs stratégies pour financer son développement, sous la direction du président, afin de soutenir ses projets économiques et sociaux.',
        'https://gabonactu.com/blog/2025/07/03/financement-du-developpement-le-gabon-sactive-sur-plusieurs-fronts/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1262a3b-f957-4c53-ad8b-3055371ef0c4',
        'Transformation locale des minerais : Lubin Ntoutoume s’assure des dispositions de Comilog',
        'Le ministre de l’Industrie a effectué une visite sur le terrain pour vérifier que la société Comilog respecte bien les dispositions liées à la transformation locale des minerais.',
        'https://gabonactu.com/blog/2025/07/03/transformation-locale-des-minerais-lubin-ntoutoume-sassure-des-dispositions-de-comilog/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1030281d-12b1-4609-a5a4-e0bdf7810936',
        'Baie de la Mondah : 2 580 milliards pour bâtir la ville verte du futur',
        'Un projet ambitieux de ville verte à la Baie de la Mondah, d’un coût de plus de 2 580 milliards de FCFA, est en phase de démarrage pour créer une cité écologique et durable au Gabon, sur une période de 7 ans.',
        'https://www.gabonreview.com/baie-de-la-mondah-2-580-milliards-pour-batir-la-ville-verte-du-futur/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '40ecfc17-2288-4bd5-9772-a004f027719d',
        'Prison centrale de Port-Gentil : Attribution de galons en reconnaissance de l’abnégation, du respect et de la discipline',
        'Vingt-cinq agents de la sécurité pénitentiaire de la prison de Port-Gentil ont été promus à différents grades en reconnaissance de leur dévouement, du respect et de la discipline.',
        'https://gabonactu.com/blog/2025/07/03/prison-centrale-de-port-gentil-attribution-de-galons-en-reconnaissance-de-labnegation-du-respect-et-de-la-discipline/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2c1f598-81f1-4f76-807f-67cc8dbd8a86',
        'Projet eGabon-SIS : l’atelier “Café des Ambassadeurs” pour consolider les acquis du Système d’information de santé',
        'Un séminaire de haut niveau sur la santé numérique s''est tenu à Nkok, visant à renforcer et promouvoir le système d''information en santé au Gabon.',
        'https://gabonactu.com/blog/2025/07/03/projet-egabon-sis-le-seminaire-cafe-des-ambassadeurs-pour-consolider-les-acquis-du-systeme-dinformation-de-sante/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bdff5bb3-7cc3-48ff-9980-7da76d947f0b',
        'Liverpool FC : Décès tragique de Diogo Jota',
        'Le joueur portugais de Liverpool, Diogo Jota, est mort tragiquement dans un accident de la route à l''âge de 28 ans.',
        'https://gabonactu.com/blog/2025/07/03/liverpool-fc-deces-tragique-de-diogo-jota/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7af9710b-a47a-4fd2-afae-a50737a3d218',
        'Gabon : «Nous ne nous tairons pas !» préviennent Sylvia et Noureddin Bongo',
        'Sylvia et Noureddin Bongo, proches de l’ancien président Ali Bongo, affirment avoir été forcés de signer des documents durant leur détention de 20 mois, mais ils déclarent aussi qu''ils ne se tairont pas face aux injustices qu’ils dénoncent.',
        'https://www.gabonreview.com/gabon-nous-ne-nous-tairons-pas-previennent-sylvia-et-noureddin-bongo/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f53a9330-9e87-452d-8272-d86547747795',
        'Inauguration officielle du Bantu Hôtel en présence du Ministre du Tourisme Durable et de l''Artisanat',
        'Le 1er juillet 2025, un nouveau hôtel nommé Bantu Hôtel a été inauguré à Libreville par le ministre du Tourisme, dans le cadre du développement de l’offre d’hébergement privée au Gabon.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/inauguration-officielle-du-bantu-hotel-en',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '336085d9-2f21-4a55-91ce-76af67b6635c',
        'Hommage rendu à Anicet Oyane Akaga, l''étoile de Minvoul par Me Alexis Nang Ntseme',
        'Maître Alexis Nang Ntseme rend hommage à Anicet Oyane Akaga, ancien député de Minvoul, décédé à Dubaï le 1er juillet 2025, en saluant son leadership et son engagement qui ont marqué sa localité.',
        'https://www.gabonews.com/fr/actus/necrologie/article/hommage-a-anicet-oyane-akaga-l-etoile-de-minvoul',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7b153030-c910-4196-9d63-235857214f80',
        'Publié le 03 / 07 / 2025',
        'L’article explique que la loi sur les partis politiques prévoit des dispositions transitoires pour mettre en place un nouveau cadre réglementaire, afin d’assurer une transition ordonnée et conforme aux nouvelles règles.',
        'https://union.sonapresse.com/fr/pierre-claver-maganga-moussavou-les-dispositions-transitoires-contenues-dans-la-loi-sur-les-partis',
        'L''union',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e7b24b0-ade7-4a23-afdf-3827cdcb0893',
        'Publié le 03 / 07 / 2025',
        'Les partis politiques se préparent discrètement aux élections de 2024, en évitant les grandes annonces et en recrutant de nouveaux membres pour renforcer leurs équipes.',
        'https://union.sonapresse.com/fr/elections-couplees-les-partis-sy-preparent-sans-tambour-ni-trompette',
        'L''union',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '12d80e85-f182-4429-95aa-55bcd2995703',
        'Le bloc opératoire de l''hôpital de Mbigou réhabilité grâce à la caravane chirurgicale de l''association Kundu Mulebe',
        'L''association Kundu Mulebe a entièrement réhabilité le bloc opératoire de l''hôpital de Mbigou lors de sa caravane chirurgicale, transformant un espace délabré en un lieu de soins sécurisé et fonctionnel.',
        'https://www.gabonews.com/fr/actus/social/article/le-bloc-operatoire-de-l-hopital-de-mbigou',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc3843c2-d34a-4858-925c-92690d3a4a20',
        '« Non aux déclarations paternalistes et colonialistes » Nicaise Moulombi répond à Christel Bories, PDG du groupe Eramet',
        'La décision du Gabon de cesser l''exportation de manganèse brut à partir de 2029 est une démarche stratégique visant à favoriser la transformation locale, malgré les critiques condescendantes de certaines entreprises étrangères.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/non-aux-declarations-paternalistes-et',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c4e86a0b-d0f2-4824-9ffd-f2ebc87e0339',
        'Le Chef de l''État s''entretient avec l''ambassadeur des États-Unis accrédité au Gabon.',
        'Le président gabonais a rencontré l''ambassadeur des États-Unis, qui lui a transmis une invitation de Donald Trump pour participer à une rencontre internationale multilatérale.',
        'https://www.gabonews.com/fr/actus/diplomatie/article/le-chef-de-l-etat-s-entretient-avec-l-ambassadeur-21029',
        'Gabonews',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '22b6c47c-38eb-40bc-a445-9008091d0b7e',
        'Publié le 03 / 07 / 2025',
        'L''article explique les dispositions transitoires prévues dans la loi sur les partis politiques, qui visent à encadrer la création, la transformation et la dissolution des partis en période de transition.',
        'https://union.sonapresse.com/fr/pierre-claver-maganga-moussavou-les-dispositions-transitoires-contenues-dans-la-loi-sur-les-partis',
        'L''union',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '772a7acd-fde9-4921-a742-2049836f70e8',
        'Publié le 03 / 07 / 2025',
        'Les partis politiques se préparent discrètement pour les prochaines élections couplées, sans faire beaucoup de bruit ni mobilisation évidente.',
        'https://union.sonapresse.com/fr/elections-couplees-les-partis-sy-preparent-sans-tambour-ni-trompette',
        'L''union',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd516854e-67c8-4ee1-96b4-807e7f2f73b3',
        'Gabon/PDG : Liste des membres du Bureau politique du parti dans le Woleu-Ntem',
        'Le Parti Démocratique Gabonais (PDG) a renouvelé ses membres du Bureau politique dans la province du Woleu-Ntem.',
        'https://agpgabon.ga/gabon-pdg-liste-des-membres-du-bureau-politique-du-parti-dans-le-woleu-ntem/',
        'AGP',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b8e192e-5c0c-4719-af0b-94cb6a89a523',
        '«Nous ne nous tairons pas»: les Bongo ciblent l’État gabonais dans un communiqué',
        'La famille Bongo accuse le gouvernement gabonais de tortures et de violences, en présentant des vidéos et des preuves dans le cadre d''une plainte déposée en France.',
        'https://www.rfi.fr/fr/afrique/20250703-nous-ne-nous-tairons-pas-les-bongo-ciblent-l-%C3%A9tat-gabonais-dans-un-communiqu%C3%A9',
        'RFI',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01a80e63-6b3f-47c1-92c8-2486cfa54549',
        'OLIGUI NGUEMA invité à Washington par Donald TRUMP',
        'Le président gabonais a rencontré l’ambassadeur américain pour discuter d’une invitation de Donald Trump à une rencontre diplomatique.',
        'https://vxp241.com/2025/07/03/oligui-nguema-invite-a-washington-par-donald-trump/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a4e8db8-6a86-4e7f-848a-c5771cb105d6',
        'Axe Derrière la Pédiatrie-Carrefour SNI: une métamorphose & des témoignages',
        'Les travaux de rénovation lancés en 2024 ont transformé de façon spectaculaire la voie secondaire menant au Centre universitaire des Sciences de la Santé à Owendo, facilitant ainsi l’accès pour les habitants de la zone.',
        'https://vxp241.com/2025/07/03/axe-derriere-la-pediatrie-carrefour-sni-une-metamorphose-des-temoignages/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-03T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e59f6a29-0e6d-4c88-b8f7-053901bb7e59',
        'Lambaréné : L’école de l’inclusion en chantier',
        'Une nouvelle école inclusive pour les enfants vulnérables et en situation de handicap va bientôt être construite à Lambaréné, afin de favoriser leur accès à l’éducation.',
        'https://gabonactu.com/blog/2025/07/03/lambarene-les-bases-de-lecole-de-linclusion-des-enfants-en-situation-de-handicap/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6206e109-c2f0-4b2f-b285-d1a865acf70a',
        'Football/Nécrologie : décès de Peter Rufai',
        'Peter Rufai, ancien gardien de but des Super Eagles, est décédé à 61 ans à Lagos après une longue maladie, laissant un grand vide dans le football africain.',
        'https://agpgabon.ga/football-necrologie-deces-de-peter-rufai/',
        'AGP',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1dc474ab-5720-40e4-ab71-e85b00ac7d5e',
        'À la veille de l’AG constitutive des Bâtisseurs : L’enjeu du débat',
        'L''article discute des débats juridiques et politiques liés à la possibilité pour le président de lancer une formation politique après avoir été élu en tant qu''indépendant, dans le contexte du régime en vigueur au Gabon.',
        'https://www.gabonreview.com/a-la-veille-de-lag-constitutive-des-batisseurs-lenjeu-du-debat/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8d8d0e17-d3e7-4779-9d42-70fe2d3c36ef',
        'À Rennes, la Coupe d’Afrique des nations dans l’attente de son podium final samedi',
        'Après un mois de compétition intense, la Coupe d’Afrique des nations (CAN) de Rennes se clôturera le 5 juillet 2025 avec la décision du podium final.',
        'https://www.ouest-france.fr/bretagne/rennes-35000/a-rennes-la-coupe-dafrique-des-nations-dans-lattente-de-son-podium-final-samedi-3e357f6a-5722-11f0-9771-bf42ae6be7a5?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b28b344f-c40d-46e4-86b1-b591e43e04a9',
        'Le Gabon s’allie à Global Fishing Watch contre la pêche illégale',
        'Le Gabon a signé un partenariat avec Global Fishing Watch pour mieux surveiller et lutter contre la pêche illégale dans ses eaux maritimes.',
        'https://directinfosgabon.com/le-gabon-sallie-a-global-fishing-watch-contre-la-peche-illegale/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a4a4fb6-9550-4483-96c0-054e4672bd2a',
        'Gilles Nembe : « Le Gabon a besoin de 15 000 milliards de FCFA pour exécuter l’ensemble de ses projets miniers »',
        'Le Gabon estime nécessiter 15 000 milliards de FCFA pour financer tous ses projets miniers, afin de développer son secteur et d''atteindre ses objectifs de croissance.',
        'https://directinfosgabon.com/gilles-nembe-le-gabon-a-besoin-de-15-000-milliards-de-fcfa-pour-executer-lensemble-de-ses-projets-miniers/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e6a5427c-b5bb-442b-a9b3-3b4651470993',
        'Virements frauduleux : Ali Bongo aurait perçu 266 milliards de francs en 10 ans',
        'Selon une enquête judiciaire relayée par RFI, Ali Bongo aurait reçu 266 milliards de francs CFA en virements irréguliers sur dix ans, avec des achats immobiliers financés par des rétrocommissions.',
        'https://directinfosgabon.com/virements-frauduleux-ali-bongo-aurait-percu-266-milliards-de-francs-en-10-ans/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '697a3f72-5d49-4be0-b37c-baa5d8c81b9a',
        'Affaire Bongo : entre contre-vérité politique et stratégie de diversion judiciaire',
        'L''article analyse comment l''affaire Bongo met en lumière les contradictions entre la vérité politique et les stratégies de diversion judiciaire en République du Congo.',
        'https://gabonmediatime.com/affaire-bongo-entre-contre-verite-politique-et-strategie-de-diversion-judiciaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2823e483-4565-43c7-8af1-c852040b3733',
        'Transformation locale du manganèse : le ministre de l’Industrie en visite sur les sites de Comilog à Moanda',
        'Le ministre de l''Industrie a visité les sites de Comilog à Moanda pour superviser la transformation locale du manganèse afin de renforcer la valeur ajoutée locale.',
        'https://gabonmediatime.com/transformation-locale-du-manganese-le-ministre-de-lindustrie-en-visite-sur-les-sites-de-comilog-a-moanda/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f7100f64-350c-4409-803d-9a2b2b7c777a',
        'Gabon : les délégués spéciaux sommés de déclarer leur candidature avant le 9 juillet 2025',
        'Les délégués spéciaux doivent déclarer leur candidature avant le 9 juillet 2025 pour participer aux prochaines élections en Guinée.',
        'https://gabonmediatime.com/gabon-les-delegues-speciaux-sommes-de-declarer-leur-candidature-avant-le-9-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6926b1da-314e-4e05-bfd7-0a3cd84468d4',
        'Gabon/souveraineté industrielle : l’État mise sur Moanda pour transformer son manganèse sur place',
        'Le gouvernement gabonais mise sur la souveraineté industrielle en investissant dans la transformation locale du manganèse à Moanda, afin de valoriser ses ressources minérales sur place.',
        'https://kongossanews.info/gabon-souverainete-industrielle-letat-mise-sur-moanda-pour-transformer-son-manganese-sur-place/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af88951c-6fd3-4452-bf10-5d62b8423831',
        '45 000 milliards de FCFA :  La valeur totale des services fournis par les forêts du Gabon en 20 ans',
        'La valeur totale des services fournis par les forêts du Gabon au cours des 20 dernières années est estimée à environ 45 000 milliards de FCFA, notamment grâce à leur rôle dans la absorption du CO₂ et leur contribution à l’économie.',
        'https://directinfosgabon.com/45-000-milliards-de-fcfa-la-valeur-totale-des-services-fournis-par-les-forets-du-gabon-en-20-ans/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a6b5205-7d16-474c-8308-8795738324a0',
        'Affaire Bongo : entre contre-vérité politique et stratégie de diversion judiciaire',
        'L''article explore les enjeux et les stratégies entourant l''affaire Bongo, mêlant contestation politique, tentatives de diversion judiciaire et débats sur la vérité.',
        'https://gabonmediatime.com/affaire-bongo-entre-contre-verite-politique-et-strategie-de-diversion-judiciaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '11cc160f-3257-4bdf-ac3f-e4f2333455ae',
        'Transformation locale du manganèse : le ministre de l’Industrie en visite sur les sites de Comilog à Moanda',
        'Le ministre de l’Industrie a visité les sites de Comilog à Moanda pour suivre l’avancement du projet de transformation locale du manganèse, visant à développer la filière minière et l’économie locale.',
        'https://gabonmediatime.com/transformation-locale-du-manganese-le-ministre-de-lindustrie-en-visite-sur-les-sites-de-comilog-a-moanda/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f3ec0a9c-646c-4998-9a6e-84af2c8bc542',
        'Gabon : les délégués spéciaux sommés de déclarer leur candidature avant le 9 juillet 2025',
        'Les délégués spéciaux doivent déclarer leur candidature avant le 9 juillet 2025 pour participer aux prochaines élections.',
        'https://gabonmediatime.com/gabon-les-delegues-speciaux-sommes-de-declarer-leur-candidature-avant-le-9-juillet-2025/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1182edbb-b899-4202-a5be-c9f2f9fe526f',
        'Gabon/souveraineté industrielle : l’État mise sur Moanda pour transformer son manganèse sur place',
        'Le gouvernement gabonais mise sur la transformation locale du manganèse à Moanda pour renforcer sa souveraineté industrielle.',
        'https://kongossanews.info/gabon-souverainete-industrielle-letat-mise-sur-moanda-pour-transformer-son-manganese-sur-place/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c143155-f459-4338-af8a-5e6976dd3e66',
        'Gabon: après la présidentielle, les candidats déposent leurs comptes de campagne',
        'Après la présidentielle au Gabon, tous les candidats avaient jusqu''au 25 juin pour déposer leur compte de campagne, mais certains ne l''ont pas encore fait malgré des sanctions prévues en cas de non-respect de la limite de dépenses de 10 milliards de francs CFA.',
        'https://www.rfi.fr/fr/afrique/20250704-gabon-apr%C3%A8s-la-pr%C3%A9sidentielle-les-candidats-d%C3%A9posent-leurs-comptes-de-campagne',
        'RFI',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7c38834c-2a0d-4b3a-9ede-7819f6b9104b',
        'Gabon: après la présidentielle, les candidats déposent leurs comptes de campagne',
        'Les candidats à la présidentielle gabonaise ont jusqu’au 25 juin pour déposer leurs comptes de campagne à la Cour des comptes, conformément aux délais impartis après la proclamation des résultats, tout en respectant la limite de dépenses fixée.',
        'https://www.rfi.fr/fr/afrique/20250704-gabon-apr%C3%A8s-la-pr%C3%A9sidentielle-les-candidats-d%C3%A9posent-leurs-comptes-de-campagne?utm_slink=rfi.my%2FBoVz&utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ffe26e3-399c-4d6d-b178-eb0ba914de5b',
        '« Gabon : Le pétrole et les mines doivent être des tremplins, pas des béquilles »',
        'L''article souligne que le secteur pétrolier et minier doit servir de tremplin pour le développement économique du Gabon, plutôt que de dépendre uniquement de ces ressources comme « béquilles » pour masquer la faiblesse d''autres industries et la gestion du pays.',
        'https://directinfosgabon.com/gabon-le-petrole-et-les-mines-doivent-etre-des-tremplins-pas-des-bequilles/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '979c5e52-95a9-4efb-a0e0-64e3d1044a4c',
        '« Dignité en détention » : Pour humaniser l’univers pénitentiaire et carcéral',
        'Un projet nommé « Dignité en prévention », lancé par des ONG gabonaises et françaises, vise à humaniser l''univers carcéral au Gabon en proposant des actions pour améliorer les conditions des détenus.',
        'https://gabonactu.com/blog/2025/07/04/dignite-en-detention-pour-humaniser-lunivers-penitentiaire-et-carceral/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6535b20-1488-4e1e-96d2-cdfd86cdee53',
        'Meeting international de Malaga : Guy Maganga-Gorra couvert d’argent en Espagne',
        'Le sprinter gabonais Guy Maganga-Gorra a remporté la médaille d’argent au 200 mètres lors du meeting international de Malaga en Espagne, avec un temps de 20’’71.',
        'https://gabonactu.com/blog/2025/07/04/meeting-international-de-malaga-guy-maganga-gorra-couvert-dargent-en-espagne/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a6bd0be-e400-4bae-9ed4-ca4363524a5d',
        'Les Bongo entendus cette semaine par un tribunal à Paris, maintiennent les allégations de « torture et d''enlèvement » contre les autorités gabonaises',
        'Sylvia et Nouredine Bongo, proches de l''ex-président gabonais Ali Bongo, affirment avoir été détenus illégalement et torturés par les nouvelles autorités du Gabon, qu''ils dénoncent dans une déclaration commune.',
        'https://www.bbc.com/afrique/articles/c4g8vk8lvpvo?xtor=AL-73-%5Bpartner%5D-%5Bflipboard%5D-%5Bheadline%5D-%5Bafrique%5D-%5Bbizdev%5D-%5Bisapi%5D',
        'Flipboard',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ab6d8f07-8190-42ad-bba2-43cbe414ce48',
        'Gabon: le président Brice Clotaire Oligui Nguema lance son parti les Bâtisseurs et suscite des questions',
        'La création du nouveau parti des Bâtisseurs par le président gabonais Brice Clotaire Oligui Nguema a été lancée lors d’une assemblée à Libreville, mais cet événement a étéReporté plusieurs fois et a suscité des critiques.',
        'https://www.rfi.fr/fr/afrique/20250704-gabon-le-pr%C3%A9sident-brice-clotaire-oligui-nguema-lance-son-parti-les-b%C3%A2tisseurs-et-suscite-des-questions',
        'RFI',
        'Business Intelligence',
        '2025-07-04T00:00:00.000Z',
        '2025-09-15T23:06:12.466Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

