-- Batch 2 - Section 2/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '10a1d4bc-5e52-4327-b657-9eb20bfeb024',
        'CNSS : Paiement des allocations familiales du 1er trimestre 2025',
        'La Caisse nationale de sécurité sociale (CNSS) du Gabon a annoncé le paiement des allocations familiales pour le premier trimestre 2025, conformément à son calendrier prévu. Les bénéficiaires peuvent retirer leurs fonds dans les agences habilitées ou via les canaux électroniques disponibles.',
        'https://directinfosgabon.com/cnss-paiement-des-allocations-familiales-du-1er-trimestre-2025/',
        'Direct Infos Gabon',
        'Numérique / Digital, Finances, Services',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ed6a1ae-c704-4625-9d4a-1c196d53cd06',
        'L’État gabonais lance un emprunt obligataire de 85 milliards de FCFA',
        'Le gouvernement gabonais lance un emprunt obligataire de 85 milliards de FCFA pour financer des projets de développement, notamment dans les secteurs des infrastructures et de l''éducation. Cet emprunt s''adresse aux investisseurs locaux et internationaux, avec une durée de remboursement prévue sur plusieurs années.',
        'https://directinfosgabon.com/letat-gabonais-lance-un-emprunt-obligataire-de-85-milliards-de-fcfa/',
        'Direct Infos Gabon',
        'Finances, Éducation, Commerce',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'aecd8b05-9842-450b-8dbf-f0da85d5b5d6',
        'Rassemblement des bâtisseurs : Les partis politiques affiliés sensibilisent et interpellent les indécis',
        'Des partis politiques affiliés au mouvement "Rassemblement des Bâtisseurs" mènent une campagne de sensibilisation pour convaincre les indécis de s''engager en faveur de leurs idées et projets. Ils interpellent directement les citoyens afin de les mobiliser autour de leurs actions et valeurs.',
        'https://gabonactu.com/blog/2025/04/07/rassemblement-des-batisseurs-les-partis-politiques-affilies-sensibilisent-et-interpellent-les-indecis/',
        'Gabon Actu',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2278d9d8-b7ad-4b14-8e8b-7199445375a7',
        '«Correct the Map» : Pour une «vraie» carte de l’Afrique',
        'L’article dénonce les distorsions fréquentes des cartes du continent africain, souvent réduit ou mal représenté, et plaide pour une cartographie plus précise et respectueuse de sa réalité géographique. Cette initiative vise à corriger les perceptions erronées et à valoriser l’Afrique dans sa juste dimension.',
        'https://www.gabonreview.com/correct-the-map-pour-une-carte-dafrique-vraie/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de98526b-2dad-4f7f-92a2-f23c3983f8bb',
        'Présidentielle 2025 : Les églises à l’unisson pour la paix et la cohésion',
        'Les églises du Gabon s''unissent pour promouvoir la paix et la cohésion sociale à l''approche de l''élection présidentielle de 2025, appelant à un scrutin apaisé et au dialogue entre les acteurs politiques.',
        'https://gabonactu.com/blog/2025/04/07/presidentielle-2025-les-eglises-a-lunisson-pour-la-paix-et-la-cohesion/',
        'Gabon Actu',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '752be742-7d2a-44d6-81d9-638a62d46a85',
        '« Le Gabon n’achète pas de carburant au Togo qui plus est ne dispose pas de raffinerie » (SOGARA)',
        'Le Gabon ne s''approvisionne pas en carburant auprès du Togo, qui ne possède d’ailleurs pas de raffinerie comme la SOGARA au Gabon. Cette clarification répond à des rumeurs infondées sur une éventuelle dépendance énergétique entre les deux pays.',
        'https://gabonactu.com/blog/2025/04/07/le-gabon-nachete-pas-de-carburant-au-togo-qui-plus-est-ne-dispose-pas-de-raffinerie-sogara/',
        'Gabon Actu',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0a504fbb-df80-4fbb-9db7-f00481103fc2',
        'Mobilisation pour Oligui Nguema : la coordination de l’Ogooué-Maritime s’active',
        'La coordination de l’Ogooué-Maritime se mobilise pour soutenir le général Oligui Nguéma, organisant des activités et des rencontres pour renforcer son leadership et son influence dans la région.',
        'https://www.gabonreview.com/mobilisation-pour-oligui-nguema-la-coordination-de-logooue-maritime-sactive/',
        'Gabon Review',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd686dd9a-8903-4772-824a-1b8b5166c11e',
        'Mobilisation pour Oligui Nguema : De Ndzomoé à Lalala-Dakar, la coordination de l’Estuaire intensifie sa campagne',
        'La coordination de l’Estuaire au Gabon intensifie sa campagne de mobilisation en faveur du général Oligui Nguema, avec des actions allant de Ndzomoe à Lalala, jusqu’à Dakar. Les partisans organisent des rassemblements et des rencontres pour soutenir sa vision politique.',
        'https://www.gabonreview.com/mobilisation-pour-oligui-nguema-de-ndzomoe-a-lalala-dakar-la-coordination-de-lestuaire-intensifie-sa-campagne/',
        'Gabon Review',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44e5600f-8a58-4326-8de8-dded4a7645fa',
        'Le Myanmar honore l’équipe de recherche et de sauvetage des Émirats arabes unis en reconnaissance de ses efforts humanitaires après le tremblement de terre',
        'Le Myanmar a rendu hommage à l’équipe de recherche et de sauvetage des Émirats arabes unis pour son aide humanitaire après un tremblement de terre, reconnaissant ainsi ses efforts déployés sur le terrain.',
        'https://agpgabon.ga/2025/04/07/le-myanmar-honore-lequipe-de-recherche-et-de-sauvetage-des-emirats-arabes-unis-en-reconnaissance-de-ses-efforts-humanitaires-apres-le-tremblement-de-terre/',
        'AGP',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '972368d2-4368-424e-85d6-af715f3df644',
        'Gabon/ Paiement des rappels soldes : le processus lancé à Akanda et Nzeng-Ayong',
        'Le processus de paiement des rappels de soldes pour les fonctionnaires a été lancé dans les districts d’Akanda et de Nzeng-Ayong au Gabon, marquant le début d’une opération attendue. Les bénéficiaires doivent suivre les étapes indiquées pour recevoir leurs dus.',
        'https://agpgabon.ga/2025/04/07/gabon-paiement-des-rappels-soldes-le-processus-lance-a-akanda-et-nzeng-ayong/',
        'AGP',
        'Services, Finances',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '57eb1baa-86a6-467a-828e-564570c456b5',
        'Gabon/ Présidentielle 2025 : le candidat Stéphane Germain Iloko Boussengui dévoile son projet de société à Cocobeach',
        'Stéphane Germain Iloko-Boussengui, candidat à la présidentielle gabonaise de 2025, a présenté son projet de société à Cocobeach, axé sur le développement économique, l’éducation et l’inclusion sociale. Ses propositions visent à moderniser le Gabon tout en renforçant les opportunités pour les jeunes et les populations rurales.',
        'https://agpgabon.ga/2025/04/07/gabon-presidentielle-2025-le-candidat-stephane-germain-iloko-boussengui-devoile-son-projet-de-societe-a-cocobeach/',
        'AGP',
        'Numérique / Digital, Éducation, Agriculture, Services, Business Femme',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '80e30beb-d851-416e-aae9-c44c86108abc',
        'Gabon/Présidentielle 2025 : le candidat Bilie-By-Nze promet des solutions spécifiques contre le chômage et le dérèglement climatique',
        'Le candidat Bilie By Nze propose des solutions ciblées pour lutter contre le chômage et les dérèglements climatiques lors de la présidentielle gabonaise de 2025.',
        'https://agpgabon.ga/2025/04/07/gabon-presidentielle-2025-le-candidat-bilie-by-nze-promet-des-solutions-specifiques-contre-le-chomage-et-le-dereglement-climatique/',
        'AGP',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd1c5f2e0-93f3-4163-be3b-3c2e83a5b356',
        'Présidentielle 2025 : Nouvelle Aurore appelle à voter en faveur de Bilie-By-Nze',
        'Le parti politique Nouvelle Aurore encourage les citoyens à voter pour Bilie By Nze lors de la présidentielle de 2025, le présentant comme un candidat porteur d''espoir pour le Gabon.',
        'https://gabonmediatime.com/presidentielle-2025-nouvelle-aurore-appelle-a-voter-en-faveur-de-bilie-by-nze/',
        'Gabon Media Time',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9b2a7ad-ec2e-405a-ba6d-f8844b6e7bcb',
        'Climate Risk Index 2025 : Le Gabon 45e pays le plus exposé aux phénomènes météorologiques extrêmes',
        'Le Gabon est classé 45e pays le plus exposé aux phénomènes météorologiques extrêmes selon le Climate Risk Index 2025, en raison de sa vulnérabilité aux changements climatiques. Cette situation souligne l''urgence de renforcer les mesures d''adaptation pour protéger les populations et les infrastructures.',
        'https://gabonmediatime.com/climate-risk-index-2025-le-gabon-45e-pays-le-plus-expose-aux-phenomenes-meteorologiques-extremes/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Agriculture, Tourisme',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '19b62bc4-3a65-4fea-bdd0-da2b1fac6249',
        'Gabon : Mission AKomplie pour les 20 ans du Show du Pays de Movaizhaleine !',
        'Le groupe gabonais Movaizhaleine a célébré ses 20 ans avec un spectacle réussi, marquant deux décennies de succès musical et d’engagement culturel. L’événement a rassemblé des fans et mis en lumière leur contribution à la musique africaine.',
        'https://gabonmediatime.com/gabon-mission-akomplie-pour-les-20-ans-du-show-du-pays-de-movaizhaleine/',
        'Gabon Media Time',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ee7e528-808f-45cf-8b65-a25a8c2c763a',
        'Promotion de l’entrepreneuriat : à Ovan, des kits AGRs pour les jeunes et les femmes Transport urbain : un bus Trans’Urb pour Ma...',
        'Des kits agricoles ont été distribués à des jeunes et femmes d’Ovan pour promouvoir l’entrepreneuriat et l’autonomisation, dans le cadre d’un projet soutenu par des partenaires locaux et internationaux.',
        'https://mediapostegabon.com/promotion-de-lentrepreneuriat-a-ovan-des-kits-agrs-pour-les-jeunes-et-les-femmes/',
        'Media Poste Gabon',
        'Numérique / Digital, Agriculture, Business Femme',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68d88834-e2e6-48a0-93b0-9c8f056e6e07',
        'Gabon: le CTRI se prêtera-t-il au jeu de la transparence sur la gestion des 220 milliards en 2024 ? Présidentielle: entouré et p...',
        'Le Gabon a lancé un projet pilote pour intégrer l''intelligence artificielle dans son système éducatif, visant à améliorer l''apprentissage et la formation des enseignants grâce à des outils technologiques innovants. Cette initiative s''inscrit dans une stratégie plus large de modernisation du secteur éducatif et de préparation aux métiers du futur.',
        'https://depeches241.com/?p=23263',
        'Dépêche 241',
        'Numérique / Digital, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '29d6c1b4-fb1d-4906-b8c8-481907eaadbf',
        'Présidentielle 2025: entre énergie et électrification, les ambitions d’Oligui confrontées à des réalités complexes Gabon: avec 3...',
        'Le Gabon a lancé un projet pilote pour intégrer l''intelligence artificielle dans son système éducatif, visant à moderniser l''apprentissage et à préparer les élèves aux compétences numériques futures. Cette initiative s''inscrit dans une stratégie plus large de transformation digitale du pays.',
        'https://depeches241.com/?p=23248',
        'Dépêche 241',
        'Numérique / Digital, Éducation',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2cf3d5cf-aa97-40d0-9ee8-1ed049c03c0e',
        'Election présidentielle : Pana promet 100% à Brice Clotaire Oligui Nguema',
        'Brice Clotaire Oligui Nguema, candidat à la présidentielle gabonaise, promet de créer 100 000 emplois pour les jeunes s’il est élu, dans le cadre de son programme économique et social.',
        'https://www.gabonews.com/fr/actus/politique/article/election-presidentielle-pana-promet-100-a-brice',
        'Gabonews',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f29dbc6d-0945-4f20-9cb9-e5efae1ae642',
        'Présidentielle 2025 : Nouvelle Aurore appelle à voter en faveur de Bilie-By-Nze',
        'Le mouvement Nouvelle Aurore encourage les citoyens à voter pour Bilie By Nze lors de la présidentielle de 2025, le présentant comme un choix porteur d''espoir pour le Gabon.',
        'https://gabonmediatime.com/presidentielle-2025-nouvelle-aurore-appelle-a-voter-en-faveur-de-bilie-by-nze/',
        'Gabon Media Time',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f8114db0-8c88-4f42-8dc9-04f5c37b668b',
        'Climate Risk Index 2025 : Le Gabon 45e pays le plus exposé aux phénomènes météorologiques extrêmes',
        'Le Gabon est classé 45e pays le plus exposé aux phénomènes météorologiques extrêmes selon le Climate Risk Index 2025, ce qui souligne sa vulnérabilité croissante face aux risques climatiques.',
        'https://gabonmediatime.com/climate-risk-index-2025-le-gabon-45e-pays-le-plus-expose-aux-phenomenes-meteorologiques-extremes/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c71cb93a-483a-488c-ba89-d2f05455e357',
        'Gabon : Mission AKomplie pour les 20 ans du Show du Pays de Movaizhaleine !',
        'Le groupe gabonais Movaizhaleine a célébré ses 20 ans avec un spectacle réussi, marquant deux décennies de succès musical et d’engagement culturel. L’événement a rassemblé des fans et mis en lumière l’impact durable du groupe sur la scène artistique gabonaise.',
        'https://gabonmediatime.com/gabon-mission-akomplie-pour-les-20-ans-du-show-du-pays-de-movaizhaleine/',
        'Gabon Media Time',
        'Autres',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef99af92-91b7-48d8-bb12-d92820c6cdad',
        'Promotion de l’entrepreneuriat : à Ovan, des kits AGRs pour les jeunes et les femmes Transport urbain : un bus Trans’Urb pour Ma...',
        'Des kits agricoles ont été remis à des jeunes et femmes d’Ovan pour promouvoir l’entrepreneuriat local, dans le cadre d’un projet visant à renforcer l’autonomie économique et la production agroalimentaire.',
        'https://mediapostegabon.com/promotion-de-lentrepreneuriat-a-ovan-des-kits-agrs-pour-les-jeunes-et-les-femmes/',
        'Media Poste Gabon',
        'Agriculture, Business Femme, Services',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4e557353-3c47-476a-bcec-15ef79432b19',
        'Gabon/Rappels de solde : un signal fort envoyé par l’État gabonais',
        'L’État gabonais a procédé au paiement des rappels de solde pour les fonctionnaires, démontrant ainsi son engagement à améliorer les conditions des agents publics et à renforcer la confiance dans l’administration. Cette mesure vise à apaiser les tensions sociales et à soutenir le pouvoir d’achat des employés de l’État.',
        'https://agpgabon.ga/2025/04/07/gabon-rappels-de-solde-un-signal-fort-envoye-par-letat-gabonais/',
        'AGP',
        'Services, Finances',
        '2025-04-07T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a711c57f-2aba-414b-88fa-f6cfcdc1361e',
        'Publié le 07 / 04 / 2025',
        'Nyanga Mabanda, candidate à la présidentielle, suscite l''espoir parmi les populations locales en proposant des solutions concrètes pour améliorer leurs conditions de vie et relancer l''économie. Son engagement en faveur de l''éducation et des infrastructures est perçu comme une opportunité de changement positif.',
        'https://union.sonapresse.com/fr/presidentielle-nyanga-mabanda-sur-fond-despoir-des-populations',
        'L''union',
        'Éducation, Services, Infrastructure',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a0933e8e-2214-4733-b13e-65e10b17327b',
        'Publié le 07 / 04 / 2025',
        'Les listes et le matériel électoral pour la présidentielle du 30 août en Ngounié (Gabon) sont enfin disponibles, après des retards liés à des problèmes logistiques et sécuritaires.',
        'https://union.sonapresse.com/fr/presidentielle-ngounie-listes-et-materiel-electoraux-enfin-disponibles',
        'L''union',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6fdcd639-c00b-440d-832b-5059a2824d46',
        'Publié le 07 / 04 / 2025',
        'Le Rassemblement pour le développement du Gabon (RDB) a lancé sa campagne présidentielle à Mouila, en Ngounié, marquant le début des hostilités électorales dans la région. Les membres du parti ont présenté leur programme et mobilisé leurs partisans en vue des élections à venir.',
        'https://union.sonapresse.com/fr/presidentielle-ngounie-le-rdb-lance-les-hostilites-mouila',
        'L''union',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0fd94988-73d6-47dc-9d9a-4bcc929deacf',
        'Publié le 07 / 04 / 2025',
        'Nyanga Mabanda, candidate à la présidentielle, suscite l''espoir parmi les populations locales grâce à ses propositions axées sur le développement socio-économique et l''amélioration des conditions de vie. Son engagement en faveur de l''éducation et des infrastructures est perçu comme une opportunité de changement positif.',
        'https://union.sonapresse.com/fr/presidentielle-nyanga-mabanda-sur-fond-despoir-des-populations',
        'L''union',
        'Numérique / Digital, Éducation, Services',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a54851b-da6a-4b1b-89b7-21532a6941c2',
        'Publié le 07 / 04 / 2025',
        'Les listes et le matériel électoral pour la présidentielle dans la province de la Ngounié au Gabon sont désormais disponibles, marquant une étape importante dans la préparation du scrutin.',
        'https://union.sonapresse.com/fr/presidentielle-ngounie-listes-et-materiel-electoraux-enfin-disponibles',
        'L''union',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6836eaff-5e6b-4df5-84ae-0c709565dc40',
        'Publié le 07 / 04 / 2025',
        'Le Rassemblement pour le Développement du Gabon (RDB) a organisé une marche à Mouila pour protester contre la gestion de la présidentielle en Ngounié, dénonçant des irrégularités et appelant à la transparence. Les manifestants ont exprimé leur mécontentement face au processus électoral, exigeant des réformes pour garantir des élections libres et équitables.',
        'https://union.sonapresse.com/fr/presidentielle-ngounie-le-rdb-lance-les-hostilites-mouila',
        'L''union',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9482f3b7-2058-4031-8779-8f8b229c89af',
        'Présidentielle au Gabon: la campagne est entrée dans la dernière ligne droite',
        'La campagne présidentielle au Gabon entre dans sa dernière phase, avec des candidats multipliant les meetings pour convaincre les électeurs avant le scrutin. Les enjeux principaux concernent la relance économique et la stabilité du pays.',
        'https://www.rfi.fr/fr/afrique/20250408-pr%C3%A9sidentielle-au-gabon-la-campagne-est-entr%C3%A9e-dans-la-derni%C3%A8re-ligne-droite',
        'RFI',
        'Numérique / Digital, Services, Finances, Éducation, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dc2fb9f7-7d26-46e3-9760-64b5e8e6d146',
        'Présidentielle au Gabon: la campagne est entrée dans la dernière ligne droite',
        'La campagne présidentielle au Gabon entre dans sa dernière phase, avec des candidats multipliant les meetings et des enjeux socio-économiques au cœur des débats, tandis que les autorités assurent du bon déroulement du scrutin.',
        'https://www.rfi.fr/fr/afrique/20250408-pr%C3%A9sidentielle-au-gabon-la-campagne-est-entr%C3%A9e-dans-la-derni%C3%A8re-ligne-droite?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Politique, Services, Éducation',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '54662600-fce8-46f3-9397-15ed4b986c5b',
        'Présidentielle 2025: Haut-Ogooué & Ogooué Lolo, OLIGUI NGUEMA fédère autour de lui',
        'Le président Oligui Nguema rassemble les régions du Haut-Ogooué et de l’Ogooué-Lolo en vue de l’élection présidentielle de 2025, renforçant ainsi son soutien local. Son leadership fédérateur vise à consolider sa position politique dans ces zones stratégiques.',
        'https://vxp241.com/2025/04/08/presidentielle-2025-haut-ogooue-ogooue-lolo-oligui-nguema-federe-autour-de-lui/',
        'Vox Populi',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97285ef3-5c8b-4f4b-805e-aa454ee4e9f4',
        'L''agriculture locale contre la vie chère au Gabon',
        'Au Gabon, des initiatives locales encouragent l''agriculture pour réduire la dépendance aux importations et lutter contre la vie chère, en promouvant des produits frais et accessibles.',
        'https://information.tv5monde.com/afrique/video/lagriculture-locale-contre-la-vie-chere-au-gabon-2769258?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Agriculture, Services, Commerce',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '713927a6-c184-4cda-8555-27159c55deb5',
        '"Non, tout pouvoir ne vient pas de Dieu" dixit Jean François Ntoutoume-Emane',
        'Certains dirigeants abusent de leur pouvoir en invoquant une légitimité divine, mais il est important de rappeler que tout pouvoir ne vient pas forcément de Dieu et doit être exercé avec sagesse et responsabilité.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/non-tout-pouvoir-ne-vient-pas-de-dieu-dixit-jean',
        'Gabonews',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4deb2273-7be9-4d43-adc0-48e9348ddbc3',
        'Au Gabon, les secrets du rebond de la famille Ping - Jeune Afrique.com',
        'La famille Ping, opposante historique au régime gabonais, renforce son influence politique et économique malgré les défis, en diversifiant ses activités et en s’appuyant sur des alliances stratégiques.',
        'https://www.jeuneafrique.com/1673346/politique/au-gabon-les-secrets-du-rebond-de-la-famille-ping/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Business Femme',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45f0731c-dd56-406f-bb5b-724e1cd53c44',
        'AGL Gabon et le Lycée Jean Fidèle Otando unissent leurs forces pour former les techniciens de demain',
        'AGL Gabon et le lycée Jean-Fidèle Otando collaborent pour former des techniciens qualifiés dans les domaines de l’électricité, de la mécanique et de la maintenance industrielle, afin de répondre aux besoins du marché local.',
        'https://www.gabonreview.com/agl-gabon-et-le-lycee-jean-fidele-otando-unissent-leurs-forces-pour-former-les-techniciens-de-demain/',
        'Gabon Review',
        'Éducation, Services',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '943895e4-0503-44b6-bf3a-8ece9fafe243',
        'Salon de l''entreprénariat de l''Afrique et de la dispora : Nantes bientôt parée aux couleurs ghanéennes',
        'Un salon dédié à l’entrepreneuriat en Afrique vise à promouvoir l’innovation et les échanges entre acteurs économiques pour stimuler le développement du continent. L’événement met l’accent sur les opportunités et les défis des entrepreneurs africains, notamment dans les secteurs technologiques et éducatifs.',
        'https://www.gabonews.com/fr/actus/economie/article/salon-de-l-entreprenariat-de-l-afrique-et-de-la',
        'Gabonews',
        'Numérique / Digital, Éducation, Services',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '44b17ee1-c649-408d-a866-56af3154c9d4',
        'Présidentielle 2025 : Quand la «Robe Noire» flirte avec la bannière politique !',
        'L''article évoque la tendance croissante des femmes gabonaises à porter des robes noires comme symbole de soutien politique en vue de l''élection présidentielle de 2025, mélangeant ainsi mode et engagement. Cette pratique reflète une stratégie de mobilisation silencieuse mais visible dans le paysage politique.',
        'https://www.gabonreview.com/presidentielle-2025-quand-la-robe-noire-flirte-avec-la-banniere-politique/',
        'Gabon Review',
        'Numérique / Digital, Business Femme, Éducation',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ce80c6e-ee1d-46f1-a568-a3a707c41af2',
        'Présidentielle 2025 : Gninga Chaning Zenaba salue l''accueil chaleureux des habitants de Franceville',
        'Gninga Chaning Zenaba Salou salue l’engagement des jeunes dans la préparation de la présidentielle 2025, soulignant leur rôle clé pour l’avenir du Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/presidentielle-2025-gninga-chaning-zenaba-salue-l',
        'Gabonews',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb069b39-a6c0-48ad-8006-47cf246e9188',
        'À 100 ans, il marche chaque jour dans les parcs palois',
        'Un centenaire palois reste actif en marchant quotidiennement dans les parcs de Pau, illustrant l’importance de l’exercice physique pour la santé à tout âge.',
        'https://www.larepubliquedespyrenees.fr/pyrenees-atlantiques/pau/a-100-ans-il-marche-chaque-jour-dans-les-parcs-palois-23957788.php?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c6e269d5-f590-4f47-8a7d-59b4d4644bf1',
        'Bilie Bye Nze veut mettre fin aux  inondations, au chômage et à l’insécurité',
        'Bilie Bye Nze propose des solutions pour résoudre les problèmes d’inondations, de chômage et d’insécurité au Gabon, en mettant l’accent sur des actions concrètes et des réformes structurelles. Son approche vise à améliorer les conditions de vie des citoyens grâce à des initiatives locales et durables.',
        'https://gabonactu.com/blog/2025/04/08/bilie-bye-nze-veut-mettre-fin-aux-inondations-au-chomage-et-a-linsecurite/',
        'Gabon Actu',
        'Numérique / Digital, Services, Agriculture, Business Femme',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9651774d-e6fd-4644-9aa4-d52a1ed512e1',
        'Port-Gentil : des scooters pour des personnes à mobilité réduite',
        'À Port-Gentil, des scooters électriques adaptés aux personnes à mobilité réduite ont été mis en service pour faciliter leurs déplacements en ville, dans le cadre d''une initiative inclusive. Ce projet vise à améliorer l''autonomie et l''accessibilité des personnes handicapées.',
        'https://gabonactu.com/blog/2025/04/08/port-gentil-des-scooters-pour-des-personnes-a-mobilite-reduite/',
        'Gabon Actu',
        'Services, Numérique / Digital, Business Femme',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.415Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a96aa87-eac1-4b5e-a6fd-8350d2856195',
        'Présidentielle 2025 : les scrutateurs de Port-Gentil en formation',
        'Des scrutateurs de Port-Gentil suivent une formation pour assurer le bon déroulement de l''élection présidentielle de 2025, en apprenant les procédures de contrôle et de transparence du vote.',
        'https://gabonactu.com/blog/2025/04/08/presidentielle-2025-les-scrutateurs-de-port-gentil-en-formation/',
        'Gabon Actu',
        'Éducation, Numérique / Digital',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fef5082c-076e-4747-8cc6-2ff86dcb27da',
        'Mobilisation pour Oligui Nguema : Un «score fleuve» comme objectif à Cocobeach',
        'À Cocobeach, une mobilisation populaire soutient le général Oligui Nguema, avec pour objectif un score électoral écrasant lors des prochaines élections. Les habitants expriment leur enthousiasme et leur confiance en sa leadership.',
        'https://www.gabonreview.com/mobilisation-pour-oligui-nguema-un-score-fleuve-comme-objectif-a-cocobeach/',
        'Gabon Review',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e153271f-dbc2-4ced-9f59-39debe61ae28',
        'Nicaise Moulombi : défenseur de l''environnement et soutien d''Oligui Nguema',
        'Nicaise Moulembou, un militant gabonais, lutte pour la protection de l’environnement en dénonçant les exploitations forestières illégales et en sensibilisant les communautés locales aux enjeux écologiques. Son engagement vise à préserver les forêts et à promouvoir un développement durable au Gabon.',
        'https://www.gabonews.com/fr/actus/politique/article/nicaise-moulombi-defenseur-de-l-environnement-et',
        'Gabonews',
        'Numérique / Digital, Services, Agriculture',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6a9984e4-b2fe-4e05-87ad-40f88f88b739',
        'Gabon : Lancement d’un emprunt obligataire régional de 85 milliards F CFA',
        'Le Gabon émet un emprunt obligataire régional de 85 milliards de F CFA pour financer des projets de développement économique et social. Cette initiative vise à mobiliser des fonds auprès des investisseurs locaux et internationaux.',
        'https://agpgabon.ga/2025/04/08/gabon-lancement-dun-emprunt-obligataire-regional-de-85-milliards-f-cfa/',
        'AGP',
        'Finances, Services',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '51dc9d0d-d002-4f1d-ba6e-4222888ef0e6',
        'Gabon : la justice française clôt l’enquête sur les « biens mal acquis » de la famille Bongo',
        'La justice française a clos l''enquête sur les biens mal acquis de la famille Bongo au Gabon, mettant fin à des années de procédures concernant des soupçons de détournement de fonds publics. Aucune poursuite n''a été engagée faute de preuves suffisantes.',
        'https://www.lemonde.fr/afrique/article/2025/04/08/gabon-la-justice-francaise-clot-l-enquete-sur-les-biens-mal-acquis-de-la-famille-bongo_6592788_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9033080f-acb0-45ad-ad48-190427e7c6ff',
        'Allocation de 150.000 FCFA à 160.000 chômeurs : un projet chimérique, selon Foumboula Libeka, porte-parole du candidat Oligui Nguema',
        'Le porte-parole du candidat Oligui Nguema qualifie de chimérique le projet d’allocation de 150 000 FCFA à 160 000 chômeurs, estimant qu’il manque de réalisme et de financement viable.',
        'https://gabonactu.com/blog/2025/04/08/allocation-de-150-000-fcfa-a-160-000-chomeurs-un-projet-chimerique-selon-foumboula-libeka-porte-parole-du-candidat-oligui-nguema/',
        'Gabon Actu',
        'Services, Finances, Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6508fa20-24f1-43a8-99eb-ee7560295791',
        'La mobilisation exceptionnelle des populations du département du Komo Océan des coordinations de campagne de la commune et du dé...',
        'Les populations du département du Komo-Océan se sont massivement mobilisées pour voter lors d''une campagne électorale marquée par un fort soutien à Oligui Nguema, avec une participation active des coordinations locales et communales. Cette mobilisation exceptionnelle témoigne de l''engagement citoyen et de l''importance accordée à ce scrutin.',
        'https://kongossanews.info/la-mobilisation-exceptionnelle-des-populations-du-departement-du-komo-ocean-des-coordinations-de-campagne-de-la-commune-et-du-departement-pour-voter-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-04-08T00:00:00.000Z',
        '2025-09-15T23:06:12.416Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

