-- Batch 4 - Section 3/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '59978d86-2b66-46ea-b39b-504c45a68e7a',
        'Semaine nationale de l’Environnement 2025 : demandez le programme !',
        'La Semaine nationale de l’environnement 2025, qui a débuté le 31 mai, mobilise la société gabonaise pour lutter contre la pollution plastique à travers des actions de terrain, des débats et des initiatives politiques.',
        'https://www.gabonreview.com/semaine-nationale-de-lenvironnement-2025-demandez-le-programme/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ecd5d03a-9bc3-409f-8faf-ad9aecb91db2',
        'Dossier Mbanie : préparons nous à affronter la seconde phase juridique',
        'Le différend frontalier entre le Gabon et la Guinée équatoriale, porté devant la Cour internationale de Justice, a été marqué par une première décision en mai 2025, témoignant d’une crise juridique en cours.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/dossier-mbanie-preparons-nous-a-affronter-la',
        'Gabonews',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3e996a8f-f182-428a-b5e8-c3a2d25f9011',
        'Gabon / Délestages à Libreville : la SEEG évoque une panne haute tension de 90 kV et annonce une alimentation alternée en électricité',
        'Une panne sur une ligne haute tension de 90 kV a provoqué des coupures d’électricité à Libreville, obligeant la SEEG à instaurer un programme d’alimentation alternée pour assurer l’approvisionnement dans la région.',
        'https://agpgabon.ga/2025/06/01/gabon-delestages-a-libreville-la-seeg-evoque-une-panne-haute-tension-de-90-kv-et-annonce-une-alimentation-alternee-en-electricite/',
        'AGP',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3325e00e-cf50-4836-96ce-5026e7e5aa2b',
        'États-Unis : Elon Musk quitte officiellement son poste',
        'Elon Musk a officiellement quitté son poste au sein de l’administration fédérale américaine après une brève participation, en exprimant sa gratitude envers Donald Trump tout en marquant une désapprobation publique.',
        'https://agpgabon.ga/2025/06/01/etats-unis-elon-musk-quitte-officiellement-son-poste/',
        'AGP',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '826c2c01-11fd-48ff-9c31-8b873e95a4fd',
        'La 40e édition de l’Open de golf de Libreville se tiendra du 5 au 9 juin 2025',
        'La Fédération de golf du Gabon a annoncé que la 40e édition de l’Open de golf de Libreville se déroulera du 5 au 9 juin 2025.',
        'https://gabonactu.com/blog/2025/06/01/la-40e-edition-de-lopen-de-golf-de-libreville-se-tiendra-du-5-au-9-juin-2025/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '03380d04-0fb1-4e36-9ace-ac69558ce45a',
        'Journée mondiale sans tabac 2025 : SOS tabagisme appelle le gouvernement à faire appliquer la loi antitabac dans son intégralité',
        'SOS Tabagisme appelle le gouvernement gabonais à faire respecter pleinement la loi anti-tabac à l''occasion de la Journée mondiale sans tabac 2025, afin de lutter contre le tabagisme et protéger la santé publique.',
        'https://gabonactu.com/blog/2025/06/01/journee-mondiale-sans-tabac-2025-sos-tabagisme-appelle-le-gouvernement-a-faire-appliquer-la-loi-antitabac-dans-son-integralite/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c5e2b49-3aff-4c58-a495-87f91ce4edcc',
        'Interdiction d’exportation du manganèse brut : Les miniers saluent « une décision historique »',
        'Les miniers saluent la décision historique d''interdire l''exportation du manganèse brut, estimant qu''elle pourra favoriser la transformation locale et le développement du secteur.',
        'https://gabonactu.com/blog/2025/06/01/interdiction-dexportation-du-manganese-brut-les-miniers-saluent-une-decision-historique/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1f50b043-3a8b-4b76-8528-b49f17326123',
        'Aide à l’enfance et à la femme : vers un partenariat entre la Fondation Ma Bannière et l’Afrique du Sud',
        'La Première Dame du Gabon et l’ambassadeur d’Afrique du Sud ont discuté d’un partenariat pour soutenir l’enfance et les femmes à travers la Fondation Ma Bannière.',
        'https://gabonactu.com/blog/2025/06/01/aide-a-lenfance-et-a-la-femme-vers-un-partenariat-entre-la-fondation-ma-banniere-et-lafrique-du-sud/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '390d6440-a689-43da-8e33-45ad2a9b5ded',
        'Vie syndicale : La FLUSEN accueille de nouveaux adhérents et rappelle ses préoccupations',
        'La FLUSEN a accueilli de nouveaux membres lors d''une réunion à Libreville, tout en réaffirmant ses préoccupations concernant le dialogue social et les réformes éducatives sous la Ve République.',
        'https://gabonactu.com/blog/2025/06/01/vie-syndicale-la-flusen-accueille-de-nouveaux-adherents-et-rappelle-ses-preoccupations/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '70a3c018-a74d-4e77-a334-34da9f816009',
        'Gabon : le gouvernement soupçonne des actes de sabotage sur le réseau électrique',
        'Le gouvernement gabonais soupçonne des actes de sabotage d’avoir endommagé le réseau électrique, causant des coupures fréquentes et mettant en question la sécurité de l’approvisionnement énergétique.',
        'https://gabonmediatime.com/gabon-le-gouvernement-soupconne-des-actes-de-sabotage-sur-le-reseau-electrique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe0cbc13-7e51-42c8-ae39-617d23c40c0a',
        'Hong Kong : le Gabon signe la convention portant création de l’IOMed',
        'Le Gabon et Hong Kong ont signé une convention pour créer l''Institut de médecine (Iomed), destiné à renforcer la coopération en santé et recherche entre les deux pays.',
        'https://gabonmediatime.com/hong-kong-le-gabon-signe-la-convention-portant-creation-de-liomed/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd55bfd48-8829-48fb-921c-4a21d42ef83f',
        'Gabon : vers l’organisation d’un forum économique sur la souveraineté budgétaire',
        'Le Gabon prévoit d’organiser un forum économique afin de renforcer la souveraineté budgétaire du pays et d’encourager le dialogue entre acteurs économiques et institutions financières.',
        'https://gabonmediatime.com/gabon-vers-lorganisation-dun-forum-economique-sur-la-souverainete-budgetaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f5e4ab3-986e-416a-98c0-1ffa18b421d7',
        'Visite d''une délégation nigériane à la ZIS de Nkok',
        'Une délégation nigériane du Collège National de Défense a visité la ZIS de Nkok pour s’inspirer de l’expérience gabonaise en gestion durable des forêts et exploitation des ressources naturelles.',
        'https://www.gabonews.com/fr/actus/cooperation/article/visite-d-une-delegation-nigeriane-a-la-zis-de',
        'Gabonews',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1fa82624-b725-403d-808d-fce05a284dd7',
        'Journée mondiale sans tabac : L''ONG Agir pour le Gabon du Dr Louma fête ses 30 ans, et plaide pour plus d''inclusion',
        'Lors d''une célébration à Libreville, la clinique Alia et Zeida a commémoré les 30 ans de l''ONG "Agir pour le Gabon" en même temps que la Journée mondiale sans tabac et les 5 ans de son centre, avec la participation de personnalités et de professionnels de santé.',
        'https://www.gabonews.com/fr/actus/societe/article/journee-mondiale-sans-tabac-l-ong-agir-pour-le',
        'Gabonews',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b89f9171-e3a2-4ebc-80d7-5e256ba37dca',
        'Sahara marocain : Le Royaume-Uni rejoint les grandes puissances en soutien au plan d''autonomie sous souveraineté marocaine',
        'Le Royaume-Uni a exprimé son soutien clair au plan d''autonomie du Maroc pour régler le conflit autour du Sahara, lors d''une signature de communiqué avec Rabat.',
        'https://www.gabonews.com/fr/actus/cooperation/article/sahara-marocain-le-royaume-uni-rejoint-les',
        'Gabonews',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '79f4b919-0407-43ed-9f88-b796aa34a6b9',
        'Gabon : le gouvernement soupçonne des actes de sabotage sur le réseau électrique',
        'Le gouvernement gabonais soupçonne des actes de sabotage d’avoir causé des coupures répétées dans le réseau électrique, compromettant l’approvisionnement en énergie du pays.',
        'https://gabonmediatime.com/gabon-le-gouvernement-soupconne-des-actes-de-sabotage-sur-le-reseau-electrique/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'df9fbdb1-b34e-4d93-bd59-1d8e5c5528cd',
        'Hong Kong : le Gabon signe la convention portant création de l’IOMed',
        'Le Gabon et Hong Kong ont signé une convention pour créer une zone économique spéciale, visant à renforcer leur coopération commerciale et attirer les investissements.',
        'https://gabonmediatime.com/hong-kong-le-gabon-signe-la-convention-portant-creation-de-liomed/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a407526f-3ed9-4ad8-b3c5-6ee0cda96cb4',
        'Gabon : vers l’organisation d’un forum économique sur la souveraineté budgétaire',
        'Le Gabon envisage d’organiser un forum économique axé sur la souveraineté budgétaire afin de renforcer la gestion financière nationale et attirer des investissements.',
        'https://gabonmediatime.com/gabon-vers-lorganisation-dun-forum-economique-sur-la-souverainete-budgetaire/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63c6863d-d7ad-4efb-9854-085c9c4ab5fc',
        'Sahara : soutien ferme du Royaume-Uni au plan marocain d’autonomie',
        'Le Royaume-Uni a réaffirmé son soutien à l’initiative marocaine d’autonomie pour le Sahara, la considérant comme la solution la plus crédible pour régler le conflit.',
        'https://agpgabon.ga/2025/06/01/sahara-soutien-ferme-du-royaume-uni-au-plan-marocain-dautonomie/',
        'AGP',
        'Business Intelligence',
        '2025-06-01T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1484efe2-5b7e-4cf9-9b3a-b865b30a5881',
        'Le français Eramet « continuera de travailler » avec le Gabon malgré l’interdiction d’exporter du manganèse',
        'Le Gabon va interdire l’exportation de manganèse à partir de 2029 afin de développer une industrie locale de transformation, mais la société française Eramet pourra continuer à travailler dans le pays malgré cette interdiction.',
        'https://www.lemonde.fr/afrique/article/2025/06/02/le-francais-eramet-continuera-de-travailler-avec-le-gabon-malgre-l-interdiction-d-exporter-du-manganese_6610207_3212.html?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ae28ab09-f121-4030-b2e1-4d9297c4fd36',
        'Tribune / Administration : A quoi sert réellement le DGA ?',
        'L''article explique que dans les institutions publiques gabonaises, la fonction de Directeur Général Adjoint (DGA), bien que prévue par la loi, est souvent inefficace et peu exploitée, ce qui limite son rôle stratégique.',
        'https://directinfosgabon.com/tribune-administration-a-quoi-sert-reellement-le-dga/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2d648c51-2e2a-45eb-b271-3050d04d6345',
        'VAALCO GABON offre un accompagnement complet à 2 jeunes boursiers gabonais',
        'Vaalco Gabon soutient deux jeunes boursiers gabonais en leur offrant un accompagnement complet, notamment du matériel informatique, dans le cadre de ses actions en faveur de l''éducation et de l''égalité des opportunités.',
        'https://directinfosgabon.com/vaalco-gabon-offre-un-accompagnement-complet-a-2-jeunes-boursiers-gabonais/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4b7f098-a1af-4ad8-b4bf-4f28ba53b5a3',
        'Interdiction d’exporter le manganèse brut : réaction d’Eramet',
        'Eramet critique la décision d’interdire l’exportation de minerai de manganèse brut, estimant que cela pourrait nuire à l’économie locale et à ses activités industrielles.',
        'https://gabonactu.com/blog/2025/06/02/interdiction-dexporter-le-manganese-brut-reaction-deramet/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '72e5ee6a-ae02-4c83-8dbd-54af41468603',
        'Consécration de Mangasport : Le pari réussi de la  Comilog',
        'L’AS Mangasport a remporté son 10e titre de champion national grâce à un travail solide, une équipe stable, un staff engagé et le soutien de la société minière COMILOG.',
        'https://directinfosgabon.com/consecration-de-mangasport-le-pari-reussi-de-la-comilog/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16231e6c-2042-4b97-bdd3-f9ba9a78cca6',
        'Manganèse brut : Comilog se prépare au tournant de 2029',
        'Comilog se prépare à arrêter l’exportation de manganèse brut à partir de 2029, conformément à la décision du gouvernement gabonais, ce qui pousse le groupe minier Eramet à anticiper cette transition.',
        'https://directinfosgabon.com/manganese-brut-comilog-se-prepare-au-tournant-de-2029/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4087c99-9fa7-453e-bd55-a2850826f198',
        'Clinique Alia & Zéida : 5 ans de lutte contre les addictions, mais toujours en quête d’identité',
        'La clinique Alia & Zéida célèbre ses 5 ans de lutte contre les addictions, tout en restant discrète sur son identité et ses activités dans ce domaine.',
        'https://gabonactu.com/blog/2025/06/02/clinique-alia-zeida-5-ans-de-lutte-contre-les-addictions-mais-toujours-dans-lanonymat/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a4b2f835-14e9-4b2a-ab25-6870ab80a964',
        'Mangasport : La touche inspirante de Comilog',
        'L’engagement de Comilog dans la gestion sportive de l’AS Mangasport illustre un modèle durable de partenariat entre l’industrie minière, le sport et la communauté locale, permettant à l’équipe de remporter son dixième titre depuis plusieurs années.',
        'https://gabonactu.com/blog/2025/06/02/mangasport-comilog-imprime-son-management-sportif-et-montre-la-voie-a-suivre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98f98025-56d6-47f5-88fc-365b5fbfffc1',
        'Semaine nationale de l’environnement : le Gabon mobilisé contre la pollution plastique',
        'Le Gabon a lancé une semaine de sensibilisation pour lutter contre la pollution plastique, en premier lieu lors d’une cérémonie à l’arboretum de Sibang, dans le cadre de la Journée mondiale de l’environnement.',
        'https://www.gabonreview.com/semaine-nationale-de-lenvironnement-le-gabon-mobilise-contre-la-pollution-plastique/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5268d96d-b3ce-43aa-b560-42bd90da02f9',
        'Emprunt « EOG MULTI TRANCHES 2024-2030 II » : le Gabon séduit les investisseurs à la BVMAC',
        'Le Gabon a réussi à lever 80 milliards de FCFA en émettant ses premières obligations « EOG MULTI TRANCHES 2024-2030 II » sur la Bourse des valeurs de l’Afrique centrale, attirant de nombreux investisseurs.',
        'https://www.gabonreview.com/emprunt-eog-multi-tranches-2024-2030-ii-le-gabon-seduit-les-investisseurs-a-la-bvmac/',
        'Gabon Review',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5f15ad14-89e1-4c78-984d-04c94b340347',
        'Le Chef de l''État en visite de chantiers à Cocobeach',
        'Le président de la République s''est rendu à Cocobeach pour suivre l''avancement de plusieurs projets en cours, montrant ainsi son engagement à favoriser un développement équilibré.',
        'https://www.gabonews.com/fr/actus/infrastructures/article/le-chef-de-l-etat-en-visite-de-chantiers-a',
        'Gabonews',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c39c1f1a-1ae5-43dc-95e8-69d4b26a20b0',
        'La position du Royaume-Uni, "un développement diplomatique majeur" qui renforce l''élan international en faveur du plan marocain d''autonomie (Député santoméen)',
        'Le Royaume-Uni a soutenu le plan marocain d''autonomie pour le Sahara, le considérant comme une solution crédible et pragmatique, ce qui renforce la position internationale en faveur de cette initiative.',
        'https://www.gabonews.com/fr/actus/cooperation/article/la-position-du-royaume-uni-un-developpement',
        'Gabonews',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '74704d4a-e4a6-4293-8dcb-4fb20eef1ca8',
        'France : Anges Kevin Nzigou parle entrepreneuriat avec le Réseau des femmes de la diaspora issues du RdB',
        'Kevin Nzigou, un entrepreneur gabonais en France, partage son expérience et son engagement pour encourager les femmes africaines issues de la diaspora à s’impliquer dans le développement de leur pays par l’entrepreneuriat.',
        'https://gabonmediatime.com/france-anges-kevin-nzigou-parle-entrepreneuriat-avec-le-reseau-des-femmes-de-la-diaspora-issues-du-rdb/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5b5d1720-c40b-4297-a35f-5ced0ca3b7a1',
        'Gabon : VAALCO réaffirme son engagement en faveur de l’éducation en accompagnant deux jeunes boursiers',
        'Gabon Vaalco réaffirme son engagement envers l''éducation en accompagnant deux jeunes boursiers dans leur parcours scolaire.',
        'https://gabonmediatime.com/gabon-vaalco-reaffirme-son-engagement-en-faveur-de-leducation-en-accompagnant-deux-jeunes-boursiers/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63286880-9f81-4591-aaa1-f9bbb39647c7',
        'Cocobeach : Oligui Nguema en visite d’inspection des projets d’infrastructure',
        'Oligui Nguema a effectué une visite d’inspection à Cocobeach pour suivre l’avancement de plusieurs projets d’infrastructure destinés à améliorer le développement de la région.',
        'https://gabonmediatime.com/cocobeach-oligui-nguema-en-visite-dinspection-des-projets-dinfrastructure/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b9d9a53e-b540-4c53-bd0f-58344f4b4dc7',
        'Ulrich Mamfoumbi Mamfoumbi, trompé et manipulé par ses collaborateurs ?',
        'Ulrich Mamfoumbi est accusé d''avoir été trompé et manipulé par ses collaborateurs, ce qui remet en question sa crédibilité et ses actions dans le contexte professionnel.',
        'https://kongossanews.info/ulrich-mamfoumbi-mamfoumbi-trompe-et-manipule-par-ses-collaborateurs/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0745197-6e53-4c8a-bb70-6e9ec5ecf249',
        'Crise à l’AGASA : le SYNATA alerte sur les dérives managériales et interpelle les plus hautes autorités',
        'La crise à l’AGERASA révèle des dérives managériales et pousse le syndicat à alerter les plus hautes autorités sur la dégradation de la situation.',
        'https://kongossanews.info/crise-a-lagasa-le-synata-alerte-sur-les-derives-manageriales-et-interpelle-les-plus-hautes-autorites/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8886e0a4-85fe-4109-a50b-eba76ce7e70d',
        'L’AS Mangasport, un modèle d’excellence et d’engagement territorial soutenu par Comilog',
        'Las Mangasport est un exemple d''excellence et d''engagement territorial soutenu par Comilog, illustrant comment le sport peut contribuer au développement local et à la valorisation des talents.',
        'https://kongossanews.info/las-mangasport-un-modele-dexcellence-et-dengagement-territorial-soutenu-par-comilog/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'db483401-0cc7-43fc-a1e3-1456156e2280',
        'Publié le 02 / 06 / 2025',
        'L''article explique le différend diplomatique entre le Gabon et la Guinée équatoriale concernant l''accueil d''un groupe de jeunes gabonais, illustrant les tensions liées à la gestion des relations entre ces deux pays africains.',
        'https://union.sonapresse.com/fr/editorial-differend-gabon-guinee-equatoriale-auberge-espagnole',
        'L''union',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '979b8b65-df04-4bad-aa02-4351dbe6c6b0',
        'Publié le 02 / 06 / 2025',
        'La Cour internationale de Justice a décidé que son arrêt dans le différend entre le Gabon, la Guinée équatoriale et la RDC s''applique à toutes les parties concernées.',
        'https://union.sonapresse.com/fr/differend-gabon-guinee-equatoriale-larret-de-la-cij-sapplique-toutes-les-parties',
        'L''union',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38f52e6c-5f59-4c4b-8964-497f7ab68e57',
        'Publié le 01 / 06 / 2025',
        'Le gouvernement prévoit de réduire le nombre de cabinets ministériels pour limiter l''inflation des effectifs et optimiser la gestion des ressources publiques.',
        'https://union.sonapresse.com/fr/rationalisation-des-cabinets-ministeriels-letat-veut-mettre-fin-linflation-des-effectifs',
        'L''union',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f4d7751b-6b26-4f5c-9033-b5562b0f3a90',
        'Cocobeach: OLIGUI NGUEMA visite les chantiers',
        'Le Président Brice Clotaire Oligui Nguema s’est rendu à Cocobeach pour suivre l’avancement de plusieurs projets en cours dans la région, en présence de membres du Gouvernement.',
        'https://vxp241.com/2025/06/02/cocobeach-oligui-nguema-visite-les-chantiers/',
        'Vox Populi',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bdd2f705-6a56-459c-b877-5025681f739e',
        'Naissance du Réseau des 9 diamants du Gabon pour financer et accompagner l’entrepreneuriat féminin',
        'Le Réseau des 9 diamants du Gabon (R9DG) a été officiellement lancé pour soutenir et financer l’entrepreneuriat féminin dans le pays.',
        'https://gabonactu.com/blog/2025/06/02/naissance-du-reseau-des-9-diamants-du-gabon-pour-financer-et-accompagner-lentrepreneuriat-feminin/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6b92ea1f-7998-4b43-97ae-e47ef3d54720',
        'L''inefficacité des partenaires en matière de dépendance alimentaire : le SG de l''Ong Idrc Africa sollicite une révision urgente du modèle de coopération gabonaise',
        'Hervais Omva invite à reconsidérer les partenariats avec certains bailleurs internationaux, tels que le PNUD et la FAO, en critiquant l’efficacité réelle des aides extérieures sur le quotidien des citoyens gabonais.',
        'https://www.gabonews.com/fr/actus/societe/article/l-inefficacite-des-partenaires-en-matiere-de',
        'Gabonews',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c29f34b-4aaf-4b5f-a4ac-90d51b0601d4',
        'Minvoul 2025 prépare sa stratégie électorale pour les locales et législatives d''octobre prochain',
        'Les membres de la plateforme Minvoul 2025 se sont réunis pour élaborer une stratégie afin de renforcer leur impact dans le département du Haut-Ntem lors des élections locales et législatives d’octobre.',
        'https://www.gabonews.com/fr/actus/politique/article/minvoul-2025-prepare-sa-strategie-electorale-pour',
        'Gabonews',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d0526a7-f3ec-41c7-81ea-10b0c2c436dc',
        'France : Anges Kevin Nzigou parle entrepreneuriat avec le Réseau des femmes de la diaspora issues du RdB',
        'Kevin Nzigou, entrepreneur franco-gabonais, partage son expérience et ses conseils pour encourager l''entrepreneuriat parmi les femmes de la diaspora africaine.',
        'https://gabonmediatime.com/france-anges-kevin-nzigou-parle-entrepreneuriat-avec-le-reseau-des-femmes-de-la-diaspora-issues-du-rdb/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'efe721ac-44e9-4941-b9d0-459e26e92410',
        'Gabon : VAALCO réaffirme son engagement en faveur de l’éducation en accompagnant deux jeunes boursiers',
        'Vaalco réaffirme son engagement envers l''éducation en soutenant deux jeunes boursiers gabonais pour favoriser leur développement académique.',
        'https://gabonmediatime.com/gabon-vaalco-reaffirme-son-engagement-en-faveur-de-leducation-en-accompagnant-deux-jeunes-boursiers/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9959ce53-aad3-41f8-97c1-00c8a051e897',
        'Cocobeach : Oligui Nguema en visite d’inspection des projets d’infrastructure',
        'Oligui Nguema a effectué une visite d’inspection à Cocobeach pour suivre l’avancement de plusieurs projets d’infrastructure visant à améliorer les services et le développement dans la région.',
        'https://gabonmediatime.com/cocobeach-oligui-nguema-en-visite-dinspection-des-projets-dinfrastructure/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '62f5cd24-367b-4813-8b35-800f9c42771f',
        'Ulrich Mamfoumbi Mamfoumbi, trompé et manipulé par ses collaborateurs ?',
        'Ulrich Mamfoumbi est victime de manipulation et de tromperies de la part de certains de ses collaborateurs, ce qui remet en question sa crédibilité et sa gestion.',
        'https://kongossanews.info/ulrich-mamfoumbi-mamfoumbi-trompe-et-manipule-par-ses-collaborateurs/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '103ea3b9-c689-42e9-bb49-5c942134d041',
        'Crise à l’AGASA : le SYNATA alerte sur les dérives managériales et interpelle les plus hautes autorités',
        'Le syndicat SYNAFADE alerte sur la crise à l’Agence de l’eau et dénonce des déviations managériales qui impactent la gestion et la pérennité de la structure, appelant les hautes autorités à intervenir.',
        'https://kongossanews.info/crise-a-lagasa-le-synata-alerte-sur-les-derives-manageriales-et-interpelle-les-plus-hautes-autorites/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e354dbab-97b5-460c-9697-5d36aa1aaac6',
        'L’AS Mangasport, un modèle d’excellence et d’engagement territorial soutenu par Comilog',
        'Le projet Mangasport, soutenu par Comilog, est un modèle d''excellence et d''engagement territorial dans le domaine sportif, favorisant le développement local et la valorisation des talents sportifs.',
        'https://kongossanews.info/las-mangasport-un-modele-dexcellence-et-dengagement-territorial-soutenu-par-comilog/',
        'Kongossa News',
        'Business Intelligence',
        '2025-06-02T00:00:00.000Z',
        '2025-09-15T23:06:12.449Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

