-- Batch 2 - Section 12/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'ad24828c-88d1-48bc-af60-e47a4222c5d7',
        'Le Togo, leader africain des exportations vers le Gabon',
        'Le Togo est le principal fournisseur africain du Gabon, exportant notamment des produits alimentaires et des matériaux de construction, grâce à des relations commerciales dynamiques et une proximité géographique.',
        'https://directinfosgabon.com/le-togo-leader-africain-des-exportations-vers-le-gabon/',
        'Direct Infos Gabon',
        'Commerce, Agriculture',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c70aeb0-2280-45a2-b148-62b2b0637aac',
        'Présidentielle 2025 : Résultats provisoires revus et corrigés',
        'Les résultats provisoires de la présidentielle 2025 au Gabon ont été révisés et corrigés, montrant des ajustements dans les scores des candidats sans changer l’issue globale du scrutin. Ces modifications suivent des vérifications et des recours, confirmant la transparence du processus électoral.',
        'https://gabonactu.com/blog/2025/04/18/presidentielle-2025-resultats-provisoires-revus-et-corriges/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c993236b-6ff7-4ac1-ae89-c0059c2da09a',
        'Gabon : Ella Nguema veut initier une loi pour sauver les femmes du célibat',
        'Une députée gabonaise propose une loi pour lutter contre le célibat féminin en encourageant le mariage et en soutenant les femmes célibataires à travers des mesures sociales et économiques. Son initiative vise à réduire les pressions sociales et les difficultés auxquelles ces femmes sont confrontées.',
        'https://gabonmediatime.com/gabon-ella-nguema-veut-initier-une-loi-pour-sauver-les-femmes-du-celibat/',
        'Gabon Media Time',
        'Services, Business Femme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b6f4ab95-4a44-4f6f-8548-b18c23366557',
        'Décès Boupendza : les supporters du Zhejiang FC choqués après le maintien d’un match de championnat',
        'Les supporters du Zhejiang FC sont choqués que le match de championnat ait été maintenu malgré le décès de l’attaquant gabonais Aaron Boupendza, estimant que cela manque de respect envers le joueur et sa famille.',
        'https://gabonmediatime.com/deces-boupendza-les-supporters-du-zhejiang-fc-choques-apres-le-maintien-dun-match-de-championnat/',
        'Gabon Media Time',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'dfaffd16-8eef-4a65-9c65-dbc710c8beaa',
        'Affaire Opiangah : vers une condamnation du Gabon par la Commission africaine des droits de l’Homme ?',
        'La Commission africaine des droits de l''homme pourrait condamner le Gabon pour violation des droits humains dans l''affaire Opiangah, concernant des arrestations arbitraires et des conditions de détention inhumaines.',
        'https://gabonmediatime.com/affaire-opiangah-vers-une-condamnation-du-gabon-par-la-commission-africaine-des-droits-de-lhomme/',
        'Gabon Media Time',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5ea5b09d-d88e-4817-a89f-d157dc3e4cc3',
        'Publié le 18 / 04 / 2025',
        'L''article analyse la situation politique au Gabon à travers le prisme des élections présidentielles, en soulignant les enjeux démocratiques et les défis spécifiques au contexte africain. Il met en lumière les tensions et les questionnements autour de la transparence et de la légitimité du processus électoral.',
        'https://union.sonapresse.com/fr/presidentielle-le-gabon-un-cas-decole',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0d16a632-b33d-46f6-85bf-83ea136dfdc4',
        'Publié le 18 / 04 / 2025',
        'Le président gabonais Oligui Nguema rend hommage à l’attaquant Aaron Boupendza, décédé, en saluant son talent et sa contribution au football.',
        'https://union.sonapresse.com/fr/deces-daaron-boupendza-le-president-oligui-nguema-salue-la-memoire-dun-avant-centre-de-talent',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'af7b4c88-ded7-4293-b041-4872d44846dc',
        'Publié le 17 / 04 / 2025',
        'La plateforme RDB a annulé son assemblée générale prévue initialement le samedi 19 avril, sans préciser les raisons de cette décision ni une nouvelle date.',
        'https://union.sonapresse.com/fr/rdb-la-plateforme-annule-son-ag-prevue-ce-samedi-19-avril',
        'L''union',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a23d6612-e852-4cc2-a99b-da20541f3feb',
        'Au Gabon, la France poursuit son désengagement militaire',
        'La France continue de réduire sa présence militaire au Gabon, conformément à sa stratégie de désengagement en Afrique, malgré les tensions politiques récentes dans le pays. Cette décision s''inscrit dans un contexte plus large de réorganisation des bases françaises sur le continent.',
        'https://www.ouest-france.fr/monde/gabon/au-gabon-la-france-poursuit-son-desengagement-militaire-bb596c32-1c48-11f0-acea-8da06560feaa?utm_source=Flipboard-news&utm_medium=fluxrss&utm_campaign=banquedecontenu',
        'Flipboard',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9b22068f-0391-485c-aeea-d754c8606dec',
        'Election d’Oligui Nguema aux commandes du Gabon :  l’espoir qui va surmonter tous les obstacles selon le FDR',
        'Oligui Nguéma, à la tête du Gabon, incarne un espoir de changement selon le FDR, qui estime qu''il pourra surmonter les défis malgré les obstacles politiques et économiques.',
        'https://gabonactu.com/blog/2025/04/18/election-doligui-nguema-aux-commandes-du-gabon-lespoir-qui-va-surmonter-tous-les-obstacles-selon-le-fdr/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3147a7cf-8848-4ba8-aeff-483efae54ebd',
        'Présidentielle 2025 : Oligui Nguema a finalement obtenu 94,85%',
        'Le général Oligui Nguema a remporté l''élection présidentielle de 2025 au Gabon avec 94,85 % des voix, consolidant ainsi son pouvoir après la période de transition.',
        'https://gabonactu.com/blog/2025/04/18/presidentielle-2025-oligui-nguema-a-finalement-obtenu-9485/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2587bd86-036a-498a-9578-b1041510600d',
        'Présidentielle 2025 : Le pourcentage d’Oligui Nguema corrigé et revu à la hausse (94,85%)',
        'Les sondages pour la présidentielle gabonaise de 2025 montrent une hausse des intentions de vote en faveur d’Ali Bongo Ondimba, tandis que celles d’Oligui Nguema sont revues à la baisse. La situation politique reste incertaine avec des ajustements fréquents dans les estimations.',
        'https://www.gabonreview.com/presidentielle-2025-le-pourcentage-doligui-nguema-corrige-et-revu-a-la-hausse-9485/',
        'Gabon Review',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e9ad3686-72b1-44d4-bc7a-6001838108a8',
        'Oligui Nguema reçoit une délégation de China First Highway à Oyem',
        'Le président de la transition gabonaise, le général Brice Clotaire Oligui Nguéma, a reçu une délégation de China First Highway pour discuter d’un projet routier visant à relier Oyem à la frontière camerounaise, afin d’améliorer les infrastructures et les échanges économiques.',
        'https://www.gabonreview.com/oligui-nguema-recoit-une-delegation-de-china-first-highway-a-oyem/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce, Tourisme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cabceccf-95e0-45e9-af56-515377c3b3fc',
        '«Terrorisme», «Djihad», comment RFI utilise ces termes?',
        'RFI explique comment elle utilise les termes "terrorisme" et "djihad" dans ses reportages, en privilégiant la précision et le contexte pour éviter les amalgames ou les généralisations. Le média souligne l''importance de décrire les faits sans attribuer de labels simplistes aux groupes ou aux actions.',
        'https://www.rfi.fr/fr/podcasts/pourquoi-rfi-dit-%C3%A7a/20250418-terrorisme-djihad-comment-rfi-utilise-ces-termes',
        'RFI',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '10335f7e-00fc-4f0b-b47e-b4d024850507',
        'Gabon : tristesse à Libreville après la mort du footballeur Aaron Boupendza',
        'La ville de Libreville est en deuil après le décès du footballeur gabonais Aaron Boupendza, survenu dans des circonstances tragiques, provoquant une vive émotion parmi les supporters et la population locale.',
        'https://www.france24.com/fr/vid%C3%A9o/20250418-gabon-tristesse-%C3%A0-libreville-apr%C3%A8s-la-mort-du-footballeur-aaron-boupendza?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6088d4bb-1f60-43b6-ad46-d6bf0385af9b',
        'Gabon : Oligui Nguema investi le 3 mai ?',
        'Le général Brice Clotaire Oligui Nguema a été investi président de la transition du Gabon le 3 mai 2024, marquant une nouvelle étape politique après la période de transition initiée en 2023.',
        'https://www.gabonreview.com/gabon-oligui-nguema-investi-le-3-mai/',
        'Gabon Review',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9f6e2111-fa18-4fca-a0de-7b1b93a36822',
        'Les propositions de l’ONG Croissance Saine Environnement pour aider le Président Oligui Nguema à relever les défis économiques et environnementaux',
        'Le blog propose des solutions pour une croissance économique durable et la protection de l''environnement au Gabon, visant à soutenir le président Oligui Nguema dans la gestion des défis du pays. Les idées incluent des réformes structurelles et des initiatives écologiques pour équilibrer développement et préservation des ressources naturelles.',
        'https://gabonactu.com/blog/2025/04/18/les-propositions-de-long-croissance-saine-environnement-pour-aider-le-president-oligui-nguema-a-relever-les-defis-economiques-et-environnementaux/',
        'Gabon Actu',
        'Numérique / Digital, Services, Agriculture, Tourisme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '009493ae-066c-42bd-8f64-5e01be44ef14',
        'Présidentielle 25 : les résultats provisoires transmis vendredi à la Cour constitutionnelle',
        'Les résultats provisoires de la présidentielle 2025 au Gabon ont été transmis à la Cour constitutionnelle vendredi, dans l’attente de leur validation officielle. Cette étape marque un moment clé du processus électoral avant la proclamation des résultats définitifs.',
        'https://gabonactu.com/blog/2025/04/18/presidentielle-25-les-resultats-provisoires-transmis-vendredi-a-la-cour-constitutionnelle/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c80bf059-b3f1-4eee-a5ac-209cb636137e',
        '« Refusez les réseaux incestueux, entourez-vous de fidèles à la République » (lettre ouverte du Dr Benicien Bouschedy au Président Oligui Nguema)',
        'Le Dr. Benicien Bouschedy appelle le président Oligui Nguema à éviter les réseaux d’influence familiaux et à s’entourer de personnes loyales à la République pour garantir une gouvernance transparente et équitable. Il souligne l’importance de privilégier l’intérêt général plutôt que les intérêts personnels ou claniques.',
        'https://gabonactu.com/blog/2025/04/18/refusez-les-reseaux-incestueux-entourez-vous-de-fideles-a-la-republique-lettre-ouverte-du-dr-benicien-bouschedy-au-president-oligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b951d001-9b94-44d0-945f-fd0fd71da4ba',
        'Gabon/Présidentielle 2025 : Brice Clotaire Nguema l’emporte avec 94,85%',
        'Brice Clotaire Nguema remporte l’élection présidentielle gabonaise de 2025 avec 94,85 % des voix, selon les résultats officiels.',
        'https://agpgabon.ga/2025/04/18/gabon-presidentielle-2025-brice-clotaire-nguema-lemporte-avec-9485/',
        'AGP',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '50b23391-e493-4da5-b9d0-fc95ad2a3730',
        'Journée nationale de la femme : OCT organise un échange d’expériences entre étudiants et professionnels',
        'L’OCT a organisé une rencontre entre étudiants et professionnels pour partager des expériences et promouvoir l’insertion des femmes dans les métiers du numérique lors de la Journée nationale de la femme. L’événement visait à inspirer les jeunes filles et à renforcer leur engagement dans les STEM.',
        'https://gabonactu.com/blog/2025/04/18/journee-nationale-de-la-femme-oct-organise-un-echange-dexperiences-entre-etudiants-et-professionnels/',
        'Gabon Actu',
        'Numérique / Digital, Éducation, Business Femme',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '132b8541-0085-4111-8ccf-910f0b105629',
        'Lundi de pâques : les agences commerciales de la SEEG seront exceptionnellement fermées',
        'Les agences commerciales de la SEEG seront exceptionnellement fermées le lundi de Pâques, conformément à la journée fériée. Les clients sont invités à prévoir leurs démarches en conséquence.',
        'https://gabonactu.com/blog/2025/04/18/lundi-de-paques-les-agences-commerciales-de-la-seeg-seront-exceptionnellement-fermees/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '19ae2b3b-51ae-4293-918c-b9f0cbf355bc',
        'Victoire d’Oligui Nguema à la présidentielle 2025 : Jean Fidèle Otandault ne cache pas sa joie',
        'Jean-Fidèle Otandault exprime ouvertement sa satisfaction après l’annonce de la candidature de Victoire Doligui Nguema à la présidentielle gabonaise de 2025.',
        'https://gabonactu.com/blog/2025/04/18/victoire-doligui-nguema-a-la-presidentielle-2025-jean-fidele-otandault-ne-cache-pas-sa-joie/',
        'Gabon Actu',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95a1c6e8-4e96-485c-9711-3c7531eae746',
        'Diplomatie : les États-Unis saluent le processus pacifique et félicitent Oligui Nguema',
        'Les États-Unis saluent le processus pacifique de transition au Gabon et félicitent le général Oligui Nguema pour ses efforts en faveur de la stabilité et de la démocratie.',
        'https://agpgabon.ga/2025/04/18/diplomatie-les-etats-unis-saluent-le-processus-pacifique-et-felicitent-oligui-nguema/',
        'AGP',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d82615e-14bc-477c-80db-aadf6959b72d',
        'Gabon/Décès d’Aaron Boupendza : le ministre des Sports rassure la famille du soutien de l’Etat',
        'Le ministre gabonais des Sports a exprimé son soutien à la famille d''Aaron Boupendza après son décès, assurant que l''État les accompagnera dans cette épreuve.',
        'https://agpgabon.ga/2025/04/18/gabon-deces-daaron-boupendza-le-ministre-des-sports-rassure-la-famille-du-soutien-de-letat/',
        'AGP',
        'Autres',
        '2025-04-18T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eb36b504-1124-4049-ae81-e96ebfe82d14',
        'Gabon/PDG : de nouveaux responsables à la tête de l’UFPDG et de l’UJPDG',
        'De nouveaux responsables ont été nommés à la tête de l''UFP-DG et de l''UJPDG, marquant un renouvellement dans la direction de ces organisations politiques gabonaises.',
        'https://agpgabon.ga/2025/04/18/gabon-pdg-de-nouveaux-responsables-a-la-tete-de-lufpdg-et-de-lujpdg/',
        'AGP',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6fe4794b-2982-42e0-bdde-1be4a57f80e4',
        'Football/Saudi Pro League : Aubameyang offre la victoire à Al-Qadsiah',
        'Pierre-Emerick Aubameyang a marqué le but victorieux pour Al-Qadsiah contre Al-Khaleej, permettant à son équipe de remporter le match 1-0 dans le championnat saoudien.',
        'https://agpgabon.ga/2025/04/18/football-saudi-pro-league-aubameyang-offre-la-victoire-a-al-qadsiah/',
        'AGP',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '38041c7c-f3f2-477e-8433-3c2b73b23b60',
        'Oligui Nguema élu au Gabon, cyberattaque contre le Maroc, crise Algérie-Mali, Tidjane Thiam candidat, Trump et les dettes africaines : les 5 infos qu’il ne fallait pas rater',
        'Oligui Nguema a été élu président du Gabon, tandis qu''une cyberattaque a visé le Maroc et que des tensions persistent entre l''Algérie et le Mali, avec en toile de fond les dettes africaines et la candidature de Tidjane Thiam soutenue par Trump.',
        'https://www.jeuneafrique.com/1680835/politique/oligui-nguema-elu-au-gabon-cyberattaque-contre-le-maroc-crise-algerie-mali-tidjane-thiam-candidat-trump-et-les-dettes-africaines-les-5-infos-quil-ne-fallait-pas-rater/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2105b149-70f0-4a7e-b30e-d748b3ee1d49',
        'Conférence de presse du ministre de l’Intérieur : Brice Clotaire Oligui Nguema confirmé avec 94,85% des voix',
        'Brice Clotaire Oligui Nguema, ministre de l’Intérieur, a confirmé les résultats de l’élection présidentielle avec 94,85 % des voix lors d’une conférence de presse.',
        'https://kongossanews.info/conference-de-presse-du-ministre-de-linterieur-brice-clotaire-oligui-nguema-confirme-avec-9485-des-voix/',
        'Kongossa News',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27e90e74-8dcf-4ddd-8091-5f4c81fdb13d',
        'Nora Kassa salue la victoire du président Oligui Nguema et fait l’apologie de l’unité nationale',
        'Nora Kassa félicite le président Oligui Nguema pour sa victoire et met en avant l’importance de l’unité nationale pour le Gabon. Elle encourage la population à soutenir cette vision pour un avenir commun.',
        'https://kongossanews.info/nora-kassa-salue-la-victoire-du-president-oligui-nguema-et-fait-lapologie-de-lunite-nationale/',
        'Kongossa News',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ff09d3f4-b105-44c2-81f1-79f5f2680c2a',
        'Roland N’ZOMA met en avant le projet numérique du Président Oligui Nguema dans le Haut-Ogooué',
        'Roland Nzoma présente le projet numérique du président Oligui Nguema dans le Haut-Ogooué, visant à moderniser les infrastructures technologiques pour améliorer l''éducation et les services publics. Cette initiative s''inscrit dans une stratégie plus large de développement économique et social par le numérique.',
        'https://kongossanews.info/roland-nzoma-met-en-avant-le-projet-numerique-du-president-oligui-nguema-dans-le-haut-ogooue/',
        'Kongossa News',
        'Numérique / Digital, Éducation, Services',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2e822521-ca53-43b6-98f0-c7682b5052a1',
        'Afrique centrale : bras de fer entre la BEAC et les companies pétrolières',
        'La Banque des États de l''Afrique centrale (BEAC) impose aux compagnies pétrolières de vendre leurs dollars sur le marché local pour stabiliser la monnaie, mais ces dernières résistent, craignant des pertes financières. Ce conflit pourrait affecter l''économie de la région.',
        'https://information.tv5monde.com/afrique/video/afrique-centrale-bras-de-fer-entre-la-beac-et-les-companies-petrolieres-2770530?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Finances, Numérique / Digital, Services',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7180248-1b1c-4509-abf0-c27c0f8229b9',
        'Oligui Nguema élu au Gabon, cyberattaque contre le Maroc, crise Algérie-Mali, Tidjane Thiam candidat, Trump et les dettes africaines : les 5 infos qu’il ne fallait pas rater',
        'Oligui Nguema est élu président du Gabon après un coup d''État, tandis qu''une cyberattaque vise le Maroc, et Tidjane Thiam se présente comme candidat en Côte d''Ivoire, dans un contexte de dettes africaines et de tensions régionales. La crise entre l''Algérie et le Mali s''aggrave, et Donald Trump suscite des réactions en Afrique.',
        'https://www.jeuneafrique.com/1680835/politique/oligui-nguema-elu-au-gabon-cyberattaque-contre-le-maroc-crise-algerie-mali-tidjane-thiam-candidat-trump-et-les-dettes-africaines-les-5-infos-quil-ne-fallait-pas-rater/?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '066e46d4-4cec-4dbd-af39-62594c211e0f',
        'Leadership : Mark Alexandre Doumba distingué Young Global Leaders 2025',
        'Mark Alexander Doumba, un leader gabonais, a été sélectionné parmi les Young Global Leaders 2025 pour son engagement en faveur du développement technologique et éducatif en Afrique. Cette distinction reconnaît son influence et ses initiatives prometteuses pour l''avenir du continent.',
        'https://gabonactu.com/blog/2025/04/19/leadership-mark-alexander-doumba-distingue-young-global-leaders-2025/',
        'Gabon Actu',
        'Numérique / Digital, Éducation',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '826f8949-2c35-42d6-ad70-d762e7209861',
        'Economie : silence à Paris sur l’avenir du FCFA dans la CEMAC',
        'Le silence des autorités françaises et de la CEMAC concernant l''avenir du FCFA suscite des interrogations, alors que des débats sur une possible réforme ou abandon de cette monnaie persistent dans la région. Certains pays africains explorent des alternatives, mais aucune décision claire n''a encore été annoncée.',
        'https://gabonactu.com/blog/2025/04/19/economie-silence-a-paris-sur-lavenir-du-fcfa-dans-la-cemac/',
        'Gabon Actu',
        'Finances, Numérique / Digital',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '630765e2-2db5-4804-b7a6-3a59a314f539',
        'Regarder en arrière pour mieux bâtir l''avenir : une rétrospective historique pour éclairer la gouvernance de la Cinquième République gabonaise',
        'L''article souligne l''importance d''apprendre du passé pour mieux construire l''avenir, en mettant l''accent sur les leçons historiques et culturelles comme fondations d''un développement durable. Il encourage une réflexion critique sur les erreurs passées pour éviter de les répéter et progresser collectivement.',
        'https://www.gabonews.com/fr/actus/libre-propos/article/regarder-en-arriere-pour-mieux-batir-l-avenir-une',
        'Gabonews',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '48a8b81f-ab7a-4646-b8ec-7d10841e71b9',
        'Le soutien à la marocanité du Sahara et à l''Initiative d''autonomie traduit le consensus international pour clore définitivement ce différend régional',
        'Plusieurs pays africains réaffirment leur soutien à la marocanité du Sahara et à l''autonomie proposée par le Maroc, considérant cette solution comme réaliste pour résoudre le conflit.',
        'https://www.gabonews.com/fr/actus/international/article/le-soutien-a-la-marocanite-du-sahara-et-a-l',
        'Gabonews',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cf03e5ee-1c96-4e2d-9ace-8a2ca79105e5',
        'JNF 2025 : partage d’expériences entre les agents OCT et les étudiantes d’ESM',
        'Des agents de l''Office du Conseil du Travail (OCT) ont échangé avec des étudiantes de l’École Normale Supérieure de Libreville sur les opportunités professionnelles et les défis du marché de l’emploi, dans le cadre des Journées Nationales de la Femme 2025.',
        'https://gabonmediatime.com/jnf-2025-partage-dexperiences-entre-les-agents-oct-et-les-etudiantes-desm/',
        'Gabon Media Time',
        'Éducation, Services, Business Femme',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c2376e8f-b749-4b90-a3ae-a4b43879623e',
        'Présidentielle 2025 : Oligui Nguema reçoit les félicitations du président chinois Xi Jinping après sa brillante victoire',
        'Le président chinois Xi Jinping a félicité le général Oligui Nguema pour sa victoire à l’élection présidentielle gabonaise de 2025, saluant sa performance et renforçant les liens entre les deux pays.',
        'https://gabonmediatime.com/presidentielle-2025-oligui-nguema-recoit-les-felicitations-du-president-chinois-xi-jinping-apres-sa-brillante-victoire/',
        'Gabon Media Time',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '01eec284-9171-4a15-8e62-e398b59c3a38',
        'JNF 2025 : K.IN.G célèbre l’autonomisation féminine et la transmission culinaire',
        'La Journée Nationale de la Femme 2025 au Gabon a mis en avant l''autonomisation des femmes et la transmission des savoirs culinaires à travers des ateliers et des échanges intergénérationnels.',
        'https://gabonmediatime.com/jnf-2025-k-in-g-celebre-lautonomisation-feminine-et-la-transmission-culinaire/',
        'Gabon Media Time',
        'Business Femme, Éducation, Tourisme',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe4137f2-5581-4352-84e3-01187fde5d7e',
        'Publié le 19 / 04 / 2025',
        'L''article discute de l''idée qu''une élection présidentielle n''est pas toujours indispensable pour assurer la stabilité politique, en suggérant que d''autres mécanismes démocratiques peuvent être envisagés. Il souligne que la priorité devrait être la bonne gouvernance plutôt que le simple respect des formalités électorales.',
        'https://union.sonapresse.com/fr/presidentielle-pas-forcement-necessaire',
        'L''union',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96c8701a-ba17-4209-a744-b3c38797a1d3',
        'Publié le 19 / 04 / 2025',
        'Le général Brice Clotaire Oligui Nguema a remporté l''élection présidentielle au Gabon avec 94,85 % des voix, selon les résultats provisoires annoncés par la commission électorale. Ce scrutin, organisé après la transition post-coup d''État d''août 2023, marque son passage de chef de la junte à président élu.',
        'https://union.sonapresse.com/fr/presidentielle-oligui-nguema-lemporte-desormais-avec-9485',
        'L''union',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a11f4f76-1939-40d2-9e85-224703f3f593',
        'Publié le 18 / 04 / 2025',
        'Des messages de félicitations ont été adressés au président Brice Clotaire Oligui Nguema par divers acteurs, saluant son leadership et ses actions pour le pays. Les soutiens exprimés mettent en avant son engagement en faveur du développement et de la stabilité.',
        'https://union.sonapresse.com/fr/messages-de-felicitations-au-president-brice-clotaire-oligui-nguema',
        'L''union',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '07152e67-fd25-402b-96d3-91171b5a579e',
        'Présidentielle 2025:  révision des scores & investiture d’OLIGUI NGUEMA',
        'La présidentielle 2025 au Gabon voit une révision des scores électoraux, avec l’investiture d’Oligui Nguéma confirmant son maintien au pouvoir malgré les contestations. Les résultats ajustés renforcent sa légitimité tout en alimentant les débats sur la transparence du processus.',
        'https://vxp241.com/2025/04/19/presidentielle-2025-revision-des-scores-investiture-doligui-nguema/',
        'Vox Populi',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '75aac1c2-66b7-490a-906e-cdabb587f7b6',
        'Gabon : Les chiffres de la production de manganèse en 2024',
        'En 2024, le Gabon a produit environ 7,5 millions de tonnes de manganèse, confirmant sa position parmi les principaux producteurs mondiaux, malgré une légère baisse par rapport à l''année précédente.',
        'https://directinfosgabon.com/gabon-les-chiffres-de-la-production-de-manganese-en-2024/',
        'Direct Infos Gabon',
        'Commerce, Finances, Services',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a5a548e2-076c-4f6a-9155-c31d9a3637fd',
        'Gabon : Les chiffres de la production pétrolière en 2024',
        'En 2024, le Gabon a produit environ 10,2 millions de barils de pétrole, marquant une légère baisse par rapport à l''année précédente, mais confirmant sa place parmi les principaux producteurs africains. Les défis logistiques et les fluctuations des prix mondiaux continuent d’impacter le secteur.',
        'https://directinfosgabon.com/gabon-les-chiffres-de-la-production-petroliere-en-2024/',
        'Direct Infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5bc29c61-f662-4795-bc67-afcaa9453680',
        'AGL Gabon renforce son engagement environnemental',
        'L''AGL Gabon intensifie ses actions environnementales en plantant des arbres et en sensibilisant les populations locales à la protection des forêts, dans le cadre de ses engagements pour un développement durable. Ces initiatives visent à réduire l''impact écologique tout en impliquant les communautés.',
        'https://directinfosgabon.com/agl-gabon-renforce-son-engagement-environnemental/',
        'Direct Infos Gabon',
        'Agriculture, Business Femme, Éducation',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9fc3aed3-fddb-43f5-b940-58011b4596d3',
        'Jean Rémy Yama mise sur les élections législatives et locales',
        'Jean-Rémy Yama annonce sa candidature aux élections législatives et locales, mettant en avant son engagement pour le développement local et la jeunesse gabonaise.',
        'https://gabonactu.com/blog/2025/04/19/jean-remy-yama-mise-sur-les-elections-legislatives-et-locales/',
        'Gabon Actu',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f950b46e-fb81-4279-9f9a-88560a51c3ee',
        'JNF 2025 : partage d’expériences entre les agents OCT et les étudiantes d’ESM',
        'Des agents de l’Office des Changes et des Transactions (OCT) ont échangé avec des étudiantes de l’École Supérieure de Management (DESM) pour partager leurs expériences professionnelles et les orienter sur les opportunités dans le secteur financier. Ces discussions visaient à renforcer les compétences des futures diplômées et à promouvoir leur insertion professionnelle.',
        'https://gabonmediatime.com/jnf-2025-partage-dexperiences-entre-les-agents-oct-et-les-etudiantes-desm/',
        'Gabon Media Time',
        'Éducation, Finances, Business Femme',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b5816d09-c489-4905-b2f7-2c8588d031f4',
        'Présidentielle 2025 : Oligui Nguema reçoit les félicitations du président chinois Xi Jinping après sa brillante victoire',
        'Le président chinois Xi Jinping a félicité le général Oligui Nguema pour sa victoire à l’élection présidentielle gabonaise de 2025, saluant sa performance et renforçant les relations entre les deux pays.',
        'https://gabonmediatime.com/presidentielle-2025-oligui-nguema-recoit-les-felicitations-du-president-chinois-xi-jinping-apres-sa-brillante-victoire/',
        'Gabon Media Time',
        'Autres',
        '2025-04-19T00:00:00.000Z',
        '2025-09-15T23:06:12.422Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

