-- Batch 6 - Section 14/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '86cb21f5-b1ae-4389-9773-6ed747b216fa',
        'Gabon/Santé : la 3è édition de la Caravane ophtalmologique lancée à l’hôpital régional de Melen',
        'Une campagne gratuite de soins ophtalmologiques, organisée par la Ligue islamique en collaboration avec le ministère de la Santé, se tient du 30 juillet au 11 août à Melen pour aider les personnes ayant des problèmes de vision.',
        'https://agpgabon.ga/gabon-sante-la-3e-edition-de-la-caravane-ophtalmologique-lancee-a-lhopital-regional-de-melen/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a431227b-28a1-4a69-96b6-e9fb5ac5992e',
        'Gabon/Transport : Ulrich Manfoumbi Manfoumbi en immersion dans ses entités sous tutelle',
        'Le ministre des Transports en Guinée a visité plusieurs structures sous sa tutelle pour évaluer leur fonctionnement et ajuster les politiques en fonction des réalités du terrain.',
        'https://agpgabon.ga/gabon-transport-ulrich-manfoumbi-manfoumbi-en-immersion-dans-ses-entites-sous-tutelle/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8607330f-cab4-45b6-8779-81aba6d2fc01',
        'Gabon/Grand Prix de l’Entrepreneuriat : 100 entrepreneurs bientôt en lice pour l’étape 3',
        'Environ 100 entrepreneurs ont terminé une étape de sélection lors de laquelle ils ont participé à des ateliers de réseautage pour favoriser les échanges et la création de synergies, et ils seront bientôt en lice pour la troisième étape du Grand Prix de l’Entrepreneuriat 2025.',
        'https://agpgabon.ga/gabon-grand-prix-de-lentrepreneuriat-100-entrepreneurs-bientot-en-lice-pour-letape-3/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '63982dcf-71df-4363-8a9d-c8d69d4a137d',
        'BAD : Le Gabonais Cédric Achille Mbeng Mezui nommé Représentant-pays au Mali',
        'Cédric Achille Mbeng Mezui, un ingénieur financier gabonais, a été nommé représentant de la Banque africaine de développement (BAD) au Mali, en reconnaissance de son parcours professionnel au sein de l''institution panafricaine depuis 2008.',
        'https://directinfosgabon.com/bad-le-gabonais-cedric-achille-mbeng-mezui-nomme-representant-pays-au-mali/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a167480d-314f-4cde-850f-6e6d7f694bf5',
        '« La ZIS de Nkok n’est pas un espace où l’État ne gagne rien » (Serge Samy Biveghe)',
        'La Zone d’Investissements Spéciaux de Nkok, malgré ses avantages fiscaux, génère des revenus pour l’État gabonais, contrairement à l’idée qu’elle serait une enclave où l’État ne profite de rien.',
        'https://directinfosgabon.com/la-zis-de-nkok-nest-pas-un-espace-ou-letat-ne-gagne-rien-serge-samy-biveghe/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c83e368-4808-4a9f-9a6e-e17bd25027a5',
        'LF2026 : « Chaque dépense devra être justifiée, évaluée et priorisée » (HCO)',
        'Pour la loi de finances 2026, chaque dépense publique devra être justifiée, évaluée et priorisée afin d''assurer une gestion plus efficace des ressources.',
        'https://directinfosgabon.com/lf2026-chaque-depense-devra-etre-justifiee-evaluee-et-priorisee-hco/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f017319c-1b8c-46c8-add8-a3c7ac33fe2b',
        'Rencontre d’Ankara : Hommage, écoute et engagement présidentiel envers la diaspora gabonaise en Turquie',
        'Le président gabonais, Brice Clotaire Oligui Nguema, a rencontré la diaspora gabonaise en Turquie pour échanger, écouter leurs préoccupations et leur assurer un soutien accru.',
        'https://www.gabonreview.com/rencontre-dankara-hommage-ecoute-et-engagement-presidentiel-envers-la-diaspora-gabonaise-en-turquie/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fa762ad4-a856-477d-ac60-b7cbbbc090ca',
        'INFOGRAPHIE : Les 10 premiers producteurs de pétrole au Gabon (Février 2025)',
        'L''article présente le classement des dix principaux producteurs de pétrole au Gabon en février 2025, en mettant en évidence leurs volumes de production respectifs.',
        'https://directinfosgabon.com/infographie-les-10-premiers-producteurs-de-petrole-au-gabon-fevrier-2025/',
        'Direct Infos Gabon',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8ff9a051-941e-4611-9bee-f5d8bdb6e510',
        'Législatives et locales à Port-Gentil : la Team Man Mamboundou ne rejoindra pas l’UDB d’Oligui Nguema',
        'La Team Man Mamboundou a décidé de ne pas rejoindre l’Union pour la démocratie et le progrès social (UDB) d’Oligui Nguema pour les élections législatives et locales à Port-Gentil.',
        'https://gabonactu.com/blog/2025/07/31/legislatives-et-locales-a-port-gentil-la-team-man-mamboundou-ne-rejoindra-pas-ludb-doligui-nguema/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3f9e171c-a2e2-449e-8f4a-290b20f68ad4',
        '16 ans de prison infligés à Clément Nkonombouet  pour avoir violé sa petite sœur mineure',
        'Clément Nkonombouet a été condamné à 16 ans de prison pour avoir violé sa petite sœur mineure.',
        'https://gabonactu.com/blog/2025/07/31/16-ans-de-prison-infliges-a-clement-nkonombouet-pour-avoir-viole-sa-petite-soeur/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd0b64439-a47c-4ce2-b00d-806e96b331c8',
        'Cession des actifs de Tullow Oil au Gabon : une nouvelle ère pour le secteur énergétique africain',
        'La vente des actifs non opérés de Tullow Oil au Gabon à la société publique GOC marque une étape importante dans le secteur énergétique du pays, symbolisant une nouvelle ère pour le développement énergétique africain.',
        'https://www.gabonreview.com/cession-des-actifs-de-tullow-oil-au-gabon-une-nouvelle-ere-pour-le-secteur-energetique-africain/',
        'Gabon Review',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '423c3c53-a6cd-4301-910f-8206bf337391',
        'Ogooué-Maritime/Transport urbain : grève illimitée des transporteurs contre les mesures municipales',
        'Les transporteurs urbains de Port-Gentil ont lancé une grève illimitée pour protester contre une décision municipale imposant le port de blouses aux conducteurs, dénonçant des contrôles abusifs et un manque de dialogue.',
        'https://agpgabon.ga/ogooue-maritime-transport-urbain-greve-illimitee-des-transporteurs-contre-les-mesures-municipales/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0e870232-550e-475e-98ea-1859326a431a',
        'Ogooué-Ivindo/Faits-divers: un gardé à vue sucombe à des brûlures suite à un incendie dans sa cellule',
        'Un homme gardé à vue dans un commissariat au Gabon a trouvé la mort après avoir été brûlé lors d’un incendie dans sa cellule, et est décédé malgré son transfert à l’hôpital.',
        'https://agpgabon.ga/ogooue-ivindo-faits-divers-un-garde-a-vue-sucombe-a-des-brulures-suite-a-un-incendie-dans-sa-cellule/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f49625ab-a497-4d15-bdf3-1da1ef934026',
        'Port-Gentil : menace de grève des taximen suite aux rackets récurrents de la Mairie',
        'Les taximen de Port-Gentil menacent de faire greve à cause de rackets répétés de la mairie, qu''ils dénoncent lors d''une assemblée organisée par leur syndicat.',
        'https://gabonactu.com/blog/2025/07/31/port-gentil-menace-de-greve-des-taximen-suite-aux-rackets-recurrents-de-la-mairie/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a6e14cdb-fb08-4604-ac4e-4ce295474408',
        'Préservation des mangroves à Port-Gentil : les associations engagées dans le planting',
        'Des associations et anciens résidents plantent des arbres pour préserver l''écosystème des mangroves à Port-Gentil.',
        'https://gabonactu.com/blog/2025/07/31/preservation-des-mangroves-a-port-gentil-les-associations-engagees-dans-le-planting/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b8c1fa8e-5279-4571-9ed5-a3c1c21eb890',
        'Youzou Elite Basketball : Moanda Basketball (H) et Relais Omnisport (D) sacrés champions de l’édition 2025',
        'En 2025, Moanda Basketball a remporté la compétition masculine après une victoire serrée en prolongation, tandis que Relais Omnisport a dominé facilement l’équipe féminine lors du tournoi Youzou Elite Basketball à Libreville.',
        'https://agpgabon.ga/youzou-elite-basketball-moanda-basketball-h-et-relais-omnisport-d-sacres-champions-de-ledition-2025/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b4c698b-65a0-44f6-a28c-01e018bb4a00',
        'Championnats du monde de natation : Noélie Lacour vise un nouveau record national',
        'Noélie Lacour, nageuse gabonaise, souhaite battre un nouveau record national lors des championnats du monde de natation dans les disciplines du 50 mètres nage libre et 50 mètres papillon, en améliorant ses performances et en progressant dans le classement international.',
        'https://agpgabon.ga/championnats-du-monde-de-natation-noelie-lacour-vise-un-nouveau-record-national/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e208b7a4-ba90-4b1e-8867-5cef997573a0',
        'Oyem : Les 3 meurtriers de « Madame Mauro » condamnés à perpétuité',
        'Trois hommes ont été condamnés à perpétuité par la justice pour avoir tué Noëlle ZANG Ondo, surnommée « Madame Mauro », une femme d''une soixantaine d''années.',
        'https://vxp241.com/2025/07/31/oyem-les-3-meurtriers-de-madame-mauro-condamnes-a-perpetuite/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2131a7fa-7b85-4b57-b550-9ee675fbf085',
        'Gabon: vers la fin des sacs plastiques à usage unique dans les grandes surfaces',
        'Le Gabon interdira l’usage des sacs plastiques à usage unique dans les grandes surfaces à partir du 23 septembre, afin de lutter contre la pollution créée par ces déchets présents dans la nature et dans les eaux.',
        'https://www.rfi.fr/fr/afrique/20250731-gabon-vers-la-fin-des-sacs-plastiques-%C3%A0-usage-unique-dans-les-grandes-surfaces',
        'RFI',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a81ab617-82ca-4c2a-9288-a8a5a798b2fa',
        'Gabon: vers la fin des sacs plastiques à usage unique dans les grandes surfaces',
        'À compter du 23 septembre, les sacs plastiques à usage unique seront interdits dans les grandes surfaces au Gabon afin de lutter contre la pollution environnementale.',
        'https://www.rfi.fr/fr/afrique/20250731-gabon-vers-la-fin-des-sacs-plastiques-%C3%A0-usage-unique-dans-les-grandes-surfaces?utm_source=flipboard&utm_content=topic%2Ffr-gabon',
        'Flipboard',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8e0139b0-1a1a-401e-83e3-57f137f1a531',
        'BGFIBank Gabon : Préparer l’avenir de vos enfants avec des offres spécialement conçues pour eux !',
        'BGFIBank Gabon propose des offres financières adaptées pour aider les parents à préparer l''avenir éducatif de leurs enfants.',
        'https://gabonmediatime.com/bgfibank-gabon-preparer-lavenir-de-vos-enfants-avec-des-offres-specialement-concues-pour-eux/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eb15f313-9bbe-4c28-80c5-810f06fd4a33',
        'Gabon : GOC boucle le rachat des actifs de Tullow Oil pour 180 milliards de FCFA',
        'Le gouvernement gabonais a finalisé le rachat des actifs de Tullow Oil pour 180 milliards de FCFA, permettant au pays de prendre le contrôle de ses ressources pétrolières.',
        'https://gabonmediatime.com/gabon-goc-boucle-le-rachat-des-actifs-de-tullow-oil-pour-180-milliards-de-fcfa/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17e690e3-ed80-4673-93fd-abaeea232a68',
        'Gabon : PNCD 2026-2030, l’occasion ou jamais de changer de cap',
        'Le nouveau Plan National de Développement 2026-2030 vise à transformer durablement le Gabon en favorisant une croissance économique inclusive et en améliorant la qualité de vie des populations.',
        'https://gabonmediatime.com/gabon-pncd-2026-2030-loccasion-ou-jamais-de-changer-de-cap/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4811107a-36f7-4ae5-82b4-2102ec3bdba6',
        'AGASA : Le Synata suspend son préavis de grève après un accord avec la tutelle',
        'Le syndicat Agasa et le SYNATA ont suspendu leur préavis de grève après avoir trouvé un accord avec les autorités, permettant ainsi de calmer la situation dans le secteur concerné.',
        'https://kongossanews.info/agasa-le-synata-suspend-son-preavis-de-greve-apres-un-accord-avec-la-tutelle/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b4562a0-c8f4-440c-9cfd-276327803d6c',
        'Mission parlementaire de Madame Paulette MISSAMBO dans l’Ogooué-Lolo : une tournée d’écoute, de pédagogie et de mobilisation cit...',
        'Mme Paulette Missambo a mené une tournée éducative et citoyenne dans le village de Logooue-Lolo, visant à sensibiliser la population sur les enjeux politiques et encourager la participation citoyenne.',
        'https://kongossanews.info/mission-parlementaire-de-madame-paulette-missambo-dans-logooue-lolo-une-tournee-decoute-de-pedagogie-et-de-mobilisation-citoyenne/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '177fa880-6fbb-44d3-89f8-75e92d4411c2',
        'Régulation des médicaments : le Conseil d’administration de l’ANMAPS fixe ses priorités',
        'Le Conseil d’administration de l’ANMAPS a défini ses priorités pour mieux réguler la vente et la distribution des médicaments, afin d’assurer leur qualité et leur sécurité.',
        'https://kongossanews.info/regulation-des-medicaments-le-conseil-dadministration-de-lanmaps-fixe-ses-priorites/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '95591e86-f23d-4f80-ba58-764c47a132b7',
        'OLIGUI NGUEMA à l’écoute des préoccupations de la diaspora gabonaise en Turquie',
        'Le président gabonais Brice Clotaire OLIGUI NGUEMA a rencontré les membres de la diaspora gabonaise en Turquie afin d’écouter leurs préoccupations et de renforcer leur lien avec le pays lors de sa visite officielle à Ankara.',
        'https://vxp241.com/2025/07/31/oligui-nguema-a-lecoute-des-preoccupations-de-la-diaspora-gabonaise-en-turquie/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85865c73-ecbc-4b4c-af8c-a0ac5062796e',
        'Déjà des investisseurs turcs intéressés par des secteurs porteurs au Gabon',
        'Le président gabonais a rencontré des investisseurs turcs lors de son séjour en Turquie, les encourageant à investir dans des secteurs clés pour renforcer la coopération économique entre les deux pays.',
        'https://vxp241.com/2025/07/31/deja-des-investisseurs-turcs-interesses-par-des-secteurs-porteurs-au-gabon/',
        'Vox Populi',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a98d2fc7-e32e-4a46-9422-63817bc953c3',
        'FEGAHAND : Nicole Assélé  »met à nu » le complot derrière l’invalidation de sa candidature',
        'Nicole Assélé accuse un complot visant à injustement invalider sa candidature à une élection, dénonçant une décision qu''elle qualifie de cynique et inique lors d''une conférence de presse.',
        'https://gabonactu.com/blog/2025/07/31/fegahand-nicole-assele-devoile-le-complot-derriere-linvalidation-de-sa-candidature/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9d020116-e78b-420c-b172-5c08abb0b741',
        'BGFIBank Gabon : Préparer l’avenir de vos enfants avec des offres spécialement conçues pour eux !',
        'Bgfibank Gabon propose des offres financières adaptées pour aider les parents à préparer l''avenir éducatif de leurs enfants.',
        'https://gabonmediatime.com/bgfibank-gabon-preparer-lavenir-de-vos-enfants-avec-des-offres-specialement-concues-pour-eux/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.485Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e4fd8309-56b9-4522-b07c-74397faf3db1',
        'Gabon : GOC boucle le rachat des actifs de Tullow Oil pour 180 milliards de FCFA',
        'Le gouvernement gabonais a finalisé l’achat des actifs de Tullow Oil pour 180 milliards de FCFA, renforçant ainsi sa participation dans le secteur pétrolier national.',
        'https://gabonmediatime.com/gabon-goc-boucle-le-rachat-des-actifs-de-tullow-oil-pour-180-milliards-de-fcfa/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0ece9a0d-6778-4dcd-a45c-ca7d3af18404',
        'Gabon : PNCD 2026-2030, l’occasion ou jamais de changer de cap',
        'Le programme national de développement économique et social du Gabon vise à transformer durablement le pays d''ici 2030 en diversifiant son économie et en renforçant ses secteurs clés.',
        'https://gabonmediatime.com/gabon-pncd-2026-2030-loccasion-ou-jamais-de-changer-de-cap/',
        'Gabon Media Time',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '82f53915-c567-471a-ad30-9e29f316297a',
        'AGASA : Le Synata suspend son préavis de grève après un accord avec la tutelle',
        'L''Union des syndicats de l''agas (Agasa) et du Synata ont suspendu leur préavis de grève après avoir trouvé un accord avec l''autorité compétente, mettant fin à la crise sociale.',
        'https://kongossanews.info/agasa-le-synata-suspend-son-preavis-de-greve-apres-un-accord-avec-la-tutelle/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f18cf022-f0ca-429d-8c7a-24367e6ad1e4',
        'Mission parlementaire de Madame Paulette MISSAMBO dans l’Ogooué-Lolo : une tournée d’écoute, de pédagogie et de mobilisation cit...',
        'Madame Paulette Missambo a effectué une tournée pédagogique et citoyenne dans le village de Logooue-Lolo pour sensibiliser la population sur des enjeux importants, en visant à encourager la participation citoyenne et à renforcer la conscience collective.',
        'https://kongossanews.info/mission-parlementaire-de-madame-paulette-missambo-dans-logooue-lolo-une-tournee-decoute-de-pedagogie-et-de-mobilisation-citoyenne/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '83472ad2-1921-4ff1-bb99-e5740f232b74',
        'Régulation des médicaments : le Conseil d’administration de l’ANMAPS fixe ses priorités',
        'Le Conseil d''administration de l''ANMAPS a défini ses priorités pour améliorer la réglementation des médicaments, notamment en renforçant la surveillance, la qualité et la disponibilité des médicaments au Niger.',
        'https://kongossanews.info/regulation-des-medicaments-le-conseil-dadministration-de-lanmaps-fixe-ses-priorites/',
        'Kongossa News',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '97fdba16-a6e1-40e5-8439-184135c003b0',
        'Élection Fégahand/Invalidation de sa candidature : Nicole Assélé juge la décision “inique et cynique”',
        'Nicole Assélé a annoncé qu’elle allait faire appel de l’invalidation de sa candidature, jugeant la décision injuste et en promettant de se battre, tout en dénonçant une décision qu’elle qualifie de cynique.',
        'https://agpgabon.ga/election-fegahand-invalidation-de-sa-candidature-nicole-assele-juge-la-decision-inique-et-cynique/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '135f9b65-f006-4bbb-955a-d8677053d3ae',
        'Gabon/Justice : le Procès du naufrage d’Esther Miracle annoncé pour le 7 août prochain',
        'Le procès du naufrage du navire Esther Miracle, ayant causé une trentaine de morts en 2023, se tiendra le 7 août à Libreville, avec des enjeux sur la légalité de la détention des prévenus et la possibilité pour l''État gabonais de se constituer partie civile.',
        'https://agpgabon.ga/gabon-justice-le-proces-du-naufrage-desther-miracle-annonce-pour-le-7-aout-prochain/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c44096e-1ebc-4484-9c3d-53973de71fe1',
        'Fégahand-Présidence : la candidature de Nicole Assélé rejetée',
        'La candidature de l’ancienne ministre Nicole Assélé à la présidence de la Fédération gabonaise de handball a été rejetée en raison de l''absence d''autorisation du ministère de la Défense nationale.',
        'https://agpgabon.ga/fegahand-presidence-la-candidature-de-nicole-assele-rejetee/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '449100b5-0fd0-46af-a10a-9f4439ac8a13',
        'Gabon/École d’été Transbio à Ipassa : les savoirs animaux inspirent les pharmacopées locales',
        'Une école d’été au Gabon a rassemblé chercheurs et étudiants pour étudier comment les savoirs locaux sur les animaux peuvent inspirer la création de remèdes traditionnels, en mêlant écologie et sciences sociales.',
        'https://agpgabon.ga/gabon-ecole-dete-transbio-a-ipassa-les-savoirs-animaux-inspirent-les-pharmacopees-locales/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9eaf5407-80e2-4d81-a465-c2217c25a275',
        'Élection Fégahand/Invalidation de sa candidature : Nicole Assélé juge la décision “inique et cynique”',
        'Une ancienne ministre des Sports, Nicole Assélé, refuse l''invalidation de sa candidature à l’élection Fégahand et annonce qu’elle va faire appel, estimant la décision injuste et cynique.',
        'https://agpgabon.ga/election-fegahand-invalidation-de-sa-candidature-nicole-assele-juge-la-decision-inique-et-cynique/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c7815870-d214-4312-93c5-9006dd08beee',
        'Le Président à l''écoute de la diaspora gabonaise en Turquie',
        'Le président gabonais a rencontré la diaspora en Turquie pour écouter leurs préoccupations concernant l''emploi, l''administration et le paiement des bourses.',
        'https://www.gabonews.com/fr/actus/politique/article/le-president-a-l-ecoute-de-la-diaspora-gabonaise',
        'Gabonews',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c8409119-5092-418d-b8df-11e9874acb11',
        'Gabon/Togo : signature de l''accord de partenariat entre les deux pays',
        'Le Gabon et le Togo ont signé un accord de partenariat pour renforcer la formation et la compétence des agents des régies financières, afin d''améliorer la gestion fiscale dans les deux pays.',
        'https://www.gabonews.com/fr/actus/cooperation/article/gabon-togo-signature-de-l-accord-de-partenariat',
        'Gabonews',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a05dfb17-366f-4721-810e-9c8b7a857c90',
        'Le Président renforce la coopération économique avec les investisseurs turcs',
        'Le président gabonais a rencontré des investisseurs turcs lors d''une visite à Ankara pour renforcer la coopération économique et accélérer les projets de développement entre les deux pays.',
        'https://www.gabonews.com/fr/actus/cooperation/article/le-president-renforce-la-cooperation-economique',
        'Gabonews',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '278fe952-1044-4379-b4a1-11e528438f20',
        'Gabon/Législatives et Locales 2025 :  prestation de serment ce vendredi pour les membres des commissions retardataires',
        'Une seconde session de prestation de serment est prévue vendredi pour les membres des commissions électorales locales et de l’Autorité de Contrôle des Élections et du Référendum, afin de combler leur absence lors de la première étape.',
        'https://agpgabon.ga/gabon-legislatives-et-locales-2025-prestation-de-serment-ce-vendredi-pour-les-membres-des-commissions-retardataires/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b326b2d1-78e6-40e5-abac-c5da7cc56a8b',
        'Gabon/Élections législatives : quatre anciens candidats à la présidentielle proposent le réaménagement du calendrier électoral',
        'Quatre anciens candidats à la présidentielle de 2025 proposent de retarder et de réorganiser le calendrier des élections législatives et locales pour assurer un processus plus calme et crédible.',
        'https://agpgabon.ga/gabon-elections-legislatives-quatre-anciens-candidats-a-la-presidentielle-proposent-le-reamenagement-du-calendrier-electoral/',
        'AGP',
        'Business Intelligence',
        '2025-07-31T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b2e6a425-86e5-4da3-82dd-2d0d9deef198',
        'Elections 2025 : le PDG d’Ali Bongo lance le processus d’investiture de ses candidats',
        'Le Parti Démocratique Gabonais (PDG) a lancé le processus d’investiture de ses candidats pour les élections de 2025, après la nomination de Ali Akbar Onanga Y’Obegue en tant que secrétaire général.',
        'https://gabonactu.com/blog/2025/08/01/elections-2025-le-pdg-dali-bongo-lance-le-processus-dinvestiture-de-ses-candidats/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ef6f05fd-283a-4d71-bfdd-529bed8c5b59',
        'Expropriations et démolitions : Le tour du PK 11',
        'La mairie de Libreville continue ses opérations de démolition et d''expropriation pour libérer des espaces occupés illégalement dans la ville.',
        'https://gabonactu.com/blog/2025/07/31/expropriations-et-demolitions-le-tour-du-pk-11/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '58952592-e9ed-4c85-bcb3-802f4cbce0d7',
        'PDG / Législatives et locales 2025 : Ali Akbar Onanga Y’Obégué à la manœuvre',
        'Ali Akbar Onanga Y’Obégué, secrétaire général du PDG, orchestre la préparation des investitures pour les élections législatives et locales de 2025.',
        'https://gabonactu.com/blog/2025/07/31/pdg-legislatives-et-locales-2025-ali-akbar-onanga-yobegue-a-la-manoeuvre/',
        'Gabon Actu',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2ff8a383-dbc2-4a02-9cb0-9e0073ac89e0',
        'La Première Dame, marraine de la caravane nationale de collecte de sang à Libreville',
        'La Première Dame, Zita Oligui Nguema, a lancé officiellement une caravane nationale de collecte de sang en partenariat avec la Croix-Rouge gabonaise, pour encourager le don de sang et renforcer la santé dans le pays.',
        'https://www.gabonews.com/fr/actus/social/article/la-premiere-dame-marraine-de-la-caravane',
        'Gabonews',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '505cee37-dffe-4685-b359-bf84be9796d2',
        'Gabon/Économie : la BEAC lance l’application “BEAC NG2020” pour authentifier les billets',
        'La BEAC a lancé une application mobile gratuite pour permettre au public et aux professionnels d’authentifier facilement les billets de la gamme «Type 2020» et lutter contre la contrefaçon.',
        'https://agpgabon.ga/gabon-economie-la-beac-lance-lapplication-beac-ng2020-pour-authentifier-les-billets/',
        'AGP',
        'Business Intelligence',
        '2025-08-01T00:00:00.000Z',
        '2025-09-15T23:06:12.486Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

