-- Batch 1 - Section 4/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        'fdaf9e51-4e66-45f0-a4eb-33377dbb287b',
        'Présidentielle 2025 : Telema et Boundzanga, l’alliance qui défie ‘le système CTRI-PDG’',
        'Le Mouvement Telema, lancé en mars 2025 à Libreville et dirigé par le professeur Noël Bertrand Boundzanga, vise à renverser six décennies de gouvernance au Gabon en soutenant sa candidature présidentielle avec un programme axé sur la souveraineté nationale et la lutte contre le chômage des jeunes.',
        'https://www.gabonreview.com/presidentielle-2025-telema-et-boundzanga-lalliance-qui-defie-le-systeme-ctri-pdg/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.243Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6e3e3601-92c4-4688-99e4-bf2dee5d3f0a',
        'Retour au bercail : le Dr Alfred Nguia Banda brise le silence après neuf ans d’exil',
        'Après neuf ans d’exil en France, le Dr Alfred Nguia Banda revient au Gabon, dénonce les dérives autocratiques du régime Bongo et exprime son soutien à la transition actuelle dirigée par Brice Clotaire Oligui Nguema.',
        'https://kongossanews.info/retour-au-bercail-le-dr-alfred-nguia-banda-brise-le-silence-apres-neuf-ans-dexil/',
        'Kongossa News',
        'Politique, Éducation, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.243Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '661a507a-91f2-4d3e-b261-bfea6f0c741b',
        'Port-Gentil : Face aux divisions ethniques, le mouvement PBI rassemble à ‘l’ombre des palmiers’',
        'Le mouvement Patrick Barbera Isac organise à Port-Gentil une rencontre citoyenne visant à promouvoir l’unité sociale et à lutter contre les divisions ethniques.',
        'https://www.gabonreview.com/port-gentil-face-aux-divisions-ethniques-le-mouvement-pbi-rassemble-a-lombre-des-palmiers/',
        'Gabon Review',
        'Éducation, Services',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.244Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '343a0c9e-7194-4ebc-bcb3-438507caacdf',
        'Oyem : Le RPM prêt à poursuivre l’œuvre de construction nationale avec le Président Oligui Nguema',
        'Le RPM, dirigé par Alexandre Barro Chambrier, a lancé une campagne à Oyem pour mobiliser ses militants en soutien au président de la Transition Brice Clotaire Oligui Nguema en vue de l’élection présidentielle d’avril 2025.',
        'https://www.gabonews.com/fr/actus/politique/article/oyem-le-rpm-pret-a-poursuivre-l-oeuvre-de',
        'Gabonews',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.244Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '746da99c-5b4b-448b-b968-b5b9f660e7ea',
        'Les enjeux culturels des prochaines joutes électorales',
        'À l’approche des élections présidentielles, la réorganisation ministérielle et les initiatives régionales renforcent le rôle du secteur culturel gabonais, offrant aux acteurs culturels une opportunité d’influencer les débats électoraux.',
        'https://www.gabonreview.com/les-enjeux-culturels-des-prochaines-joutes-electorales/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Culture, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.244Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca84c3bd-c54b-4e94-b452-090277dbf935',
        'Gabon/Département du Ntem/Canton Ékorété en mouvement : appel à la réconciliation générationnelle et à la mobilisation électoral...',
        'Les habitants du canton Ékorété se sont réunis à Libreville pour promouvoir la réconciliation intergénérationnelle et encourager la mobilisation électorale en vue des élections présidentielles du 12 avril 2025.',
        'https://kongossanews.info/departement-du-ntem-canton-ekore-ete-en-mouvement-appel-a-la-reconciliation-generationnelle-et-a-la-mobilisation-electorale/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation, Finances, Business Femme',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.244Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ee3830cb-6566-4283-a967-6e64015304bb',
        'Woleu-Ntem : Barro Chambrier et le RPM décidés à poursuivre avec Oligui Nguema',
        'Le leader du RPM, Alexandre Barro Chambrier, réaffirme son engagement à soutenir le président de la transition Oligui Nguema et prépare l’avenir politique du Gabon lors de sa tournée dans la province du Woleu-Ntem.',
        'https://www.gabonreview.com/woleu-ntem-barro-chambrier-et-le-rpm-decides-a-poursuivre-avec-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-02T00:00:00.000Z',
        '2025-09-15T23:06:12.245Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ee49be22-fbec-4496-b8f6-e962d58011e5',
        'Consulat du Bénin à Libreville, 7 ans de lutte et 32 millions FCFA impayés : quand les Affaires étrangères abandonnent un compatriote en détresse',
        'Après sept années de lutte, Michel Ikamba, retraité gabonais, réclame toujours 32,4 millions de francs CFA au Consulat du Bénin à Libreville, se sentant abandonné par le ministère des Affaires étrangères du Gabon.',
        'https://www.gabonreview.com/consulat-du-benin-a-libreville-7-ans-de-lutte-et-32-millions-fcfa-impayes-quand-les-affaires-etrangeres-abandonnent-un-compatriote-en-detresse/',
        'Gabon Review',
        'Finances, Services, Numérique / Digital',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.245Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '69344413-c3c7-45bb-a748-976f1e14eb56',
        'Après 9 ans d’exil, Nguia Banda raconte sa ‘mésaventure’ et appelle à voter Oligui Nguema',
        'Après neuf ans d''exil, l''homme politique gabonais Alfred Nguia Banda retourne au pays pour partager son expérience et soutenir le président Oligui Nguema en vue des élections présidentielles de 2025.',
        'https://www.gabonreview.com/apres-9-ans-dexil-nguia-banda-raconte-sa-mesaventure-et-appelle-a-voter-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.245Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ddcad8a5-f8d7-4c62-9784-660b4bbbf59f',
        'Michel Ikamba : un Gabonais lésé par le Consulat du Bénin à Libreville et abandonné par les Affaires étrangères',
        'Michel Ikamba, un Gabonais, lutte depuis sept ans pour récupérer sa villa et 32,4 millions de francs CFA de loyer impayé par le Consulat du Bénin à Libreville, tout en faisant face à l''absence de réponse des autorités compétentes.',
        'https://www.gabonews.com/fr/actus/societe/article/michel-ikamba-un-gabonais-lese-par-le-consulat-du',
        'Gabonews',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.245Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3bda4b29-52ef-4539-9030-fad28692e322',
        '« 75% des entreprises au Gabon considèrent l’électricité comme le premier frein à leur activité »',
        'Un article analyse comment l''interconnexion électrique entre le Gabon et la Guinée Équatoriale pourrait réduire les obstacles énergétiques perçus par 75 % des entreprises gabonaises et dynamiser le commerce transfrontalier au sein de la CEMAC.',
        'https://directinfosgabon.com/75-des-entreprises-au-gabon-considerent-lelectricite-comme-le-premier-frein-a-leur-activite/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Commerce, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.245Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '94765b3f-b8ae-49a1-9234-75e6a7067164',
        '[Interview] Bertrand Noël Boundzanga : «La Transition a échoué dès lors que les militaires veulent garder le pouvoir»',
        'Le candidat présidentiel gabonais Bertrand Noël Boundzanga critique l’échec de la transition actuelle dominée par les militaires et présente son programme visant une gouvernance transparente et une économie inclusive.',
        'https://www.gabonreview.com/interview-bertrand-noel-boundzanga-la-transition-a-echoue-des-lors-que-les-militaires-veulent-garder-le-pouvoir/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation, Agriculture, Business Femme',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.246Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '45d1671a-d9cd-4362-9056-80951af721e9',
        'Dr Armande Longo épouse Moulengui présentée aux populations de Koulamoutou',
        'Le 1er mars 2025, la Ministre de la Culture et des Arts, Dr Armande Longo épouse Moulengui, a été officiellement présentée aux habitants de Koulamoutou lors d''une cérémonie traditionnelle marquée par un large soutien communautaire.',
        'https://www.gabonews.com/fr/actus/politique/article/dr-armande-longo-epouse-moulengui-presentee-aux',
        'Gabonews',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.246Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b7b153e5-2cff-43e1-b684-4a58b238b2a7',
        '‘Fichier électoral illégal’ : Quatre figures politiques saisissent la Cour constitutionnelle',
        'Quatre responsables politiques gabonais contestent l’élection présidentielle de 2025 en dénonçant l’illégalité du fichier électoral et demandent son report devant la Cour constitutionnelle.',
        'https://www.gabonreview.com/fichier-electoral-illegal-quatre-figures-politiques-saisissent-la-cour-constitutionnelle/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.246Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2db967d0-88ca-40cb-86a0-4eeca3ce27ab',
        'Démission d’Oligui Nguema des Forces de Défense et de Sécurité : la Présidence dément la fakenews ventilée par l’AGP',
        'La Présidence de la République a fermement démenti les rumeurs diffusées par l’Agence Gabonaise de Presse concernant la démission de Brice Clotaire Oligui Nguema des Forces de Défense et de Sécurité.',
        'https://kongossanews.info/demission-doligui-nguema-des-forces-de-defense-et-de-securite-la-presidence-dement-la-fakenews-ventilee-par-lagp/',
        'Kongossa News',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.247Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0c2d094d-ba6e-49a7-9322-66bab3dc7f98',
        'JCI GABON 2025 : Une rentrée solennelle groupée sous le signe de l’élévation',
        'La Jeune Chambre Internationale Gabon a tenu sa 30ème rentrée solennelle, inaugurant Deoly Houndy comme nouvelle présidente locale 2025 et lançant un mandat axé sur le leadership des jeunes, le numérique et le recrutement pour redynamiser le mouvement.',
        'https://www.gabonews.com/fr/actus/societe/article/jci-gabon-2025-une-rentree-solennelle-groupee',
        'Gabonews',
        'Numérique / Digital, Services, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.247Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '629ba87f-fd35-40e0-a4a1-73c92be7fe72',
        '«Ensemble, réunis, c’est plus de 11 % de l’électorat du Gabon» : Oligui Nguema prépare-t-il son assaut électoral ?',
        'Le général Brice Clotaire Oligui Nguema rassemble les Forces de Défense et de Sécurité au stade de l’Amitié pour préparer et annoncer sa candidature à l’élection présidentielle gabonaise du 12 avril 2025.',
        'https://www.gabonreview.com/ensemble-reunis-cest-plus-de-11-de-lelectorat-du-gabon-oligui-nguema-prepare-t-il-son-assaut-electoral/',
        'Gabon Review',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.247Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3dd6c9a4-402f-4b58-97e5-a9ad516b3432',
        'Rencontre citoyenne à Nzeng-Ayong : Bilan et perspectives pour le 6ᵉ arrondissement de Libreville',
        'Une rencontre citoyenne dans le 6ᵉ arrondissement de Libreville a évalué les réalisations du Comité pour la Transition et la Restauration des Institutions et a défini des perspectives futures tout en appelant à l’unité et à la mobilisation collective.',
        'https://kongossanews.info/rencontre-citoyenne-a-nzeng-ayong-bilan-et-perspectives-pour-le-6%e1%b5%89-arrondissement-de-libreville/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.248Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8075910b-baf4-4d41-b83b-30ca13737f91',
        'OCT renforce la digitalisation de ses services avec IPAKI Extranet Solution',
        'Owendo Container Terminal (OCT) a renforcé la digitalisation de ses services en lançant la plateforme IPAKI Extranet Solution afin d’améliorer l’expérience client et d’optimiser la gestion des opérations portuaires.',
        'https://www.gabonreview.com/oct-renforce-la-digitalisation-de-ses-services-avec-ipaki-extranet-solution/',
        'Gabon Review',
        'Numérique / Digital, Services',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.248Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9ed9ab77-b476-4c10-b106-c6347cefee0f',
        'Gabon: Oligui Nguema inaugure l’interconnexion électrique entre le Gabon et la Guinée-Équatoriale Transition: la plateforme Ga...',
        'Le Président de la Transition gabonaise, Brice Clotaire Oligui Nguema, a inauguré une interconnexion électrique avec la Guinée équatoriale afin de renforcer l''intégration énergétique régionale et de réduire les délestages dans la province du Woleu-Ntem.',
        'https://depeches241.com/?p=22737',
        'Dépêche 241',
        'Numérique / Digital, Services, Finances',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.248Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '071bd0a1-858f-4089-92de-c5742373829e',
        'Présidentielle 25 : la fin du vrai faux suspens d’Oligui Nguema !',
        'Le président de la Transition, Brice Clotire Oligui Nguema, devrait officiellement annoncer sa candidature à l''élection présidentielle prévue le 12 avril prochain.',
        'https://gabonactu.com/blog/2025/03/03/presidentielle-25-la-fin-du-vrai-faux-suspens-doligui-nguema/',
        'Gabon Actu',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.248Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'b0203f1b-171a-4b43-b56c-603557742b2e',
        'Nyanga : Mobilisation massive pour appeler à la candidature de Brice Clotaire Oligui Nguema',
        'Le 1er mars 2025, une grande mobilisation dans la province de Nyanga a exprimé un soutien massif au Président de la Transition, Brice Clotaire Oligui Nguema, appelant à la poursuite de ses réformes et efforts pour le développement provincial.',
        'https://www.gabonews.com/fr/actus/politique/article/nyanga-mobilisation-massive-pour-appeler-a-la',
        'Gabonews',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.249Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '53fd4e64-408f-4127-8628-d5750673fcfb',
        'Haut-Ogooué : Deux départements collectent 30 millions FCFA pour la candidature d’Oligui Nguema',
        'Les départements des Plateaux et de Djouori-Agnili du Haut-Ogooué ont réuni 30 millions FCFA pour soutenir la candidature du général Brice Clotaire Oligui Nguema à l''élection présidentielle de 2025 au Gabon.',
        'https://www.gabonreview.com/haut-ogooue-deux-departements-collectent-30-millions-fcfa-pour-la-candidature-doligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.249Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '42326931-83b9-42e3-96ad-6464ea5fef29',
        '‘’L’Union Sacrée des Amis de Brice Clotaire Oligui Nguéma’’  sensibilise et mobilise à Port-Gentil',
        'Une coalition dirigée par Féfé Onanga a lancé une campagne de mobilisation à Port-Gentil pour soutenir Brice Clotaire Oligui Nguéma et encourager l''inscription des jeunes électeurs en vue des prochaines élections.',
        'https://gabonactu.com/blog/2025/03/03/lunion-sacree-des-amis-de-brice-clotaire-oligui-nguema-sensibilise-et-mobilise-a-port-gentil/',
        'Gabon Actu',
        'Numérique / Digital, Éducation, Services',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.249Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9e2e5b94-f649-4069-9622-23365a72c0a1',
        'Fin de la Transition, Espoir de Renouveau et Candidature de Brice Clotaire Oligui Nguema – par Charles Assembe Ovono, fils du ca...',
        'Le Gabon atteint la fin de sa transition politique sous la direction du Général Brice Clotaire Oligui Nguema, nourrissant l''espoir d''un renouveau démocratique et posant sa candidature à l''élection présidentielle tout en questionnant la possibilité d''un véritable renouvellement des acteurs politiques.',
        'https://kongossanews.info/fin-de-la-transition-espoir-de-renouveau-et-candidature-de-brice-clotaire-oligui-nguema-par-charles-assembe-ovono-fils-du-canton-nye/',
        'Kongossa News',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.249Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '17cc2464-c4f2-483e-ad57-7f60bf31dfe6',
        'PID/PIH : Le gouvernement exige plus de rigueur dans l’exécution des projets',
        'Le gouvernement demande à Maurel & Prom d’améliorer la rigueur et la coordination dans l’exécution des projets PID/PIH après que l’entreprise n’ait atteint que 60 % de ses objectifs en 2024.',
        'https://www.gabonreview.com/pid-pih-le-gouvernement-exige-plus-de-rigueur-dans-lexecution-des-projets/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.250Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5afea709-64c6-4074-80ef-8b5d85abcf10',
        'Le PLC et PASTEF renforcent leur coopération politique panafricaine',
        'Le PLC et le PASTEF ont renforcé leur coopération politique panafricaine en consolidant leurs liens historiques et en prévoyant une convention de jumelage pour promouvoir une Afrique souveraine et unie.',
        'https://gabonactu.com/blog/2025/03/03/le-plc-et-pastef-renforcent-leur-cooperation-politique-panafricaine/',
        'Gabon Actu',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.250Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '68605564-18bc-4532-bac8-9048bfd28980',
        'Port-Gentil : Élection présidentielle, prorogation de l’enrôlement, repli identitaire – Féfé Onanga en campagne de sensibilisation',
        'Féfé Onanga, en alliance avec la coalition pro-Oligui Nguéma, a lancé à Port-Gentil une campagne de sensibilisation et de mobilisation des jeunes électeurs en vue des élections présidentielles, tout en appelant à éviter les tensions identitaires.',
        'https://www.gabonreview.com/port-gentil-election-presidentielle-prorogation-de-lenrolement-repli-identitaire-fefe-onanga-en-campagne-de-sensibilisation/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.250Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a9867651-be86-4e00-840b-9fbc9448b543',
        'Gabon/Clôture de la Foire Agricole de Libreville : des distinctions et un engagement fort pour l’avenir du secteur',
        'La clôture de la Foire Agricole de Libreville a mis en avant des distinctions pour les meilleurs exposants et réaffirmé l''engagement fort du gouvernement gabonais envers le développement futur du secteur agricole.',
        'https://kongossanews.info/gabon-cloture-de-la-foire-agricole-de-libreville-des-distinctions-et-un-engagement-fort-pour-lavenir-du-secteur/',
        'Kongossa News',
        'Agriculture, Services, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.250Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '100f79f2-7ba9-4142-8a40-c115e2440e9c',
        'Coupures et délestages : Dédommagements et remboursements',
        'Le nouvel administrateur provisoire de la SEEG explique aux clients gabonais les démarches pour obtenir des dédommagements et remboursements suite aux coupures et délestages d''électricité récurrents.',
        'https://gabonactu.com/blog/2025/03/03/coupures-et-delestages-dedommagements-et-remboursements-eventuels/',
        'Gabon Actu',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.251Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fca77b34-8bcb-4030-af96-389abd09c162',
        'Messe d’action de grâces en l’honneur du  50è anniversaire du Président Oligui Nguema',
        'Le président gabonais Brice Oligui Clotaire Nguema et sa Première Dame ont assisté à une messe d’action de grâces célébrant son 50ᵉ anniversaire en présence de nombreuses personnalités.',
        'https://www.gabonews.com/fr/actus/societe/article/messe-d-action-de-graces-en-l-honneur-du-50e',
        'Gabonews',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.251Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6ab4fdb4-b7a1-4125-8d96-353f0d5b7920',
        'Investissements publics : 300 milliards de FCFA supplémentaires par an ?',
        'Le Gabon réforme la gestion des investissements publics en intégrant la Direction des Investissements Publics au Commissariat Général au Plan afin d''optimiser les ressources et de mobiliser 300 milliards de FCFA supplémentaires par an pour améliorer les projets de développement et attirer les investisseurs privés.',
        'https://directinfosgabon.com/investissements-publics-300-milliards-de-fcfa-supplementaires-par-an/',
        'Direct infos Gabon',
        'Numérique / Digital, Finances, Services, Éducation, Agriculture',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.251Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '4ff8ed20-476b-436c-9667-15e0fc18368b',
        'Grève des magistrats : le gouvernement appelle à une suspension du mouvement',
        'Le gouvernement de la Transition du Gabon appelle le Syndicat national des magistrats à suspendre sa grève en raison des progrès significatifs obtenus lors des négociations pour répondre à leurs revendications.',
        'https://www.gabonreview.com/greve-des-magistrats-le-gouvernement-appelle-a-une-suspension-du-mouvement/',
        'Gabon Review',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.251Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '96b3c9c2-b5b0-4e4f-ab17-968f2f19d5d8',
        'Repli identitaire : Le péché originel viendrait-il du sommet ?',
        'En pré-campagne présidentielle de 2025, le président de transition gabonais Brice Clotaire Oligui Nguéma exacerbe les tensions ethniques en soutenant des associations régionales, compromettant ainsi l''unité nationale.',
        'https://gabonactu.com/blog/2025/03/03/repli-identitaire-le-peche-originel-viendrait-il-du-sommet/',
        'Gabon Actu',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.252Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '532bce4b-76ff-4a17-b684-b5974e89fc59',
        'Passé sous pavillon saoudien, la branche agricole d’Olam maintient ses activités au Gabon',
        'Olam Group Limited, désormais sous pavillon saoudien, confirme la poursuite de ses importantes opérations agricoles au Gabon, incluant les plantations de palmiers à huile et de caoutchouc, tout en s’engageant dans des partenariats public-privé pour une agriculture durable.',
        'https://directinfosgabon.com/passe-sous-pavillon-saoudien-la-branche-agricole-dolam-maintient-ses-activites-au-gabon/',
        'Direct infos Gabon',
        'Agriculture, Services, Numérique / Digital',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.252Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd9f0b5b2-9442-458d-aca2-443046abc1b2',
        'Foire agricole de Libreville : un tremplin pour la souveraineté alimentaire et l’entrepreneuriat rural',
        'Lors de sa septième édition, la Foire agricole de Libreville a mis en avant la souveraineté alimentaire et l''entrepreneuriat rural, soulignant l''importance de l''agriculture dans la diversification économique du Gabon.',
        'https://www.gabonreview.com/foire-agricole-de-libreville-un-tremplin-pour-la-souverainete-alimentaire-et-lentrepreneuriat-rural/',
        'Gabon Review',
        'Agriculture, Services, Numérique / Digital, Finances',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.252Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3a9a90f1-06e0-4a1e-8e7b-cc5af56ed0af',
        'PGP : Jean Ping jette l’éponge',
        'Jean Ping démissionne du Parti gabonais du progrès (PGP) en raison de différends internes avec son président, Benoit Joseph Mouity Nzamba.',
        'https://gabonactu.com/blog/2025/03/03/pgp-jean-ping-jette-leponge/',
        'Gabon Actu',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.252Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd4cc8017-94d8-436e-9908-488a01f40c51',
        'Classement des pays africains les plus influents en 2025 : Le Gabon à la 43e place',
        'En 2025, le Gabon se classe au 43ᵉ rang parmi les 54 pays africains les plus influents en matière de soft power, selon le cabinet Brand Finance.',
        'https://directinfosgabon.com/classement-des-pays-africains-les-plus-influents-en-2025-le-gabon-a-la-43e-place/',
        'Direct infos Gabon',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.253Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c3c9bd73-46d2-40c7-9a28-47da9e3d05bd',
        'Koreg, première société pétrolière gabonaise à explorer le sous-sol national',
        'Le gouvernement gabonais a signé un contrat d’exploitation et de partage de production avec Koreg, devenant ainsi la première société pétrolière autochtone à explorer le sous-sol national, marquant une avancée significative pour l''industrie pétrolière du Gabon.',
        'https://www.gabonreview.com/koreg-premiere-societe-petroliere-gabonaise-a-explorer-le-sous-sol-national/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.253Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2612ebef-6677-4e35-ae82-c352a047e4bb',
        'Présidentielle 2025 : fin du suspens Oligui Nguema est candidat',
        'Brice Clotaire Oligui Nguema, président de la transition au Gabon, a officiellement annoncé sa candidature à l’élection présidentielle du 12 avril 2025 devant des milliers d’habitants à Libreville.',
        'https://gabonactu.com/blog/2025/03/03/presidentielle-2025-fin-du-suspens-oligui-nguema-est-candidat/',
        'Gabon Actu',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.253Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cd1beab5-2482-472b-a249-f2d950f30b10',
        'Entre promesse de toges et paiement partiel de la dette, Oligui sollicite les suffrages des enseignants-chercheurs',
        'Le président de la transition gabonaise, Brice Clotaire Oligui Nguema, a annoncé des mesures visant à améliorer les conditions des enseignants-chercheurs, telles que la fourniture de toges, la réduction de la dette pédagogique et la création de nouveaux postes, afin de renforcer l’enseignement supérieur et solliciter leur soutien électoral.',
        'https://www.gabonreview.com/gabon-entre-promesse-de-500-toges-et-paiement-partiel-de-la-dette-oligui-nguema-sollicite-les-suffrages-des-enseignants-chercheurs/',
        'Gabon Review',
        'Éducation, Services, Numérique / Digital',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.253Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '98c9d6fe-6e98-48e6-b3cd-e04d68369278',
        'Transition: la dangereuse ingérence du Président Obiang Nguema dans les affaires internes du Gabon Gabon: Oligui Nguema inaugure...',
        'Lors d''une cérémonie d''interconnexion électrique, le président Obiang Nguema s''est immiscé dans les affaires internes du Gabon en soutenant publiquement Brice Clotaire Oligui Nguema, provoquant une vive controverse nationale.',
        'https://depeches241.com/?p=22763',
        'Dépêche 241',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9609be7f-4860-4960-8308-145f4a0c0293',
        'Forêt du Gabon : Un capital naturel colossal, un défi économique majeur',
        'L''article souligne le rôle crucial des forêts du Gabon en tant que capital naturel exceptionnel et explore les défis économiques liés à leur valorisation durable pour favoriser une croissance verte.',
        'https://www.gabonreview.com/foret-du-gabon-un-capital-naturel-colossal-un-defi-economique-majeur/',
        'Gabon Review',
        'Numérique / Digital, Finances, Agriculture, Éducation',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a430e084-5435-422c-ae7b-e03ac0481819',
        'Ovan: Le nouveau Secrétaire Général de Préfecture installé Exploitation pétrolière: soupçons de monopole et de favoritisme dans ...',
        'César Nguema Atsame a été officiellement installé comme nouveau Secrétaire Général de Préfecture d’Ovan le 19 février 2025, s’engageant à améliorer l’administration publique et à collaborer étroitement avec les agents de l’État.',
        'https://depeches241.com/?p=22713',
        'Dépêche 241',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5c6160f4-b076-4072-86bf-5d5acf8d06f8',
        'SEEG : vingt ans de négligence, 475 milliards de rattrapage',
        'L''Administrateur provisoire de la SEEG a révélé qu''un investissement de 475 milliards de FCFA est nécessaire pour moderniser les infrastructures énergétiques vieillissantes du Gabon, soulignant ainsi les conséquences de deux décennies de négligence dans le secteur électrique.',
        'https://www.gabonreview.com/seeg-vingt-ans-de-negligence-475-milliards-de-rattrapage/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '181d9ac2-a3a8-4b9f-b9d7-f1cfb5be3734',
        'Présidentielle 2025 : Au Gabon, gouverneurs et délégués spéciaux rappelés à leur obligation de neutralité',
        'À l''approche des élections présidentielles de 2025 au Gabon, les gouverneurs et délégués spéciaux sont rappelés par le ministère de l’Intérieur à observer une stricte neutralité politique durant le processus électoral.',
        'https://www.gabonreview.com/presidentielle-2025-au-gabon-gouverneurs-et-delegues-speciaux-rappeles-a-leur-obligation-de-neutralite/',
        'Gabon Review',
        'Autres',
        '2025-03-03T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e6a47671-9baf-4ec5-bfbf-0ad08b9073da',
        'Rites et traditions du Gabon: après le rite Agueyi Ndjogo, la danse ngwata présentée au grand public Cinéma: « Oncle Didine » ti...',
        'L''article décrit la présentation réussie de la danse traditionnelle ngwata au grand public par le Conseil National des Rites et Traditions du Gabon, visant à valoriser les traditions locales et à préparer un futur congrès national.',
        'https://depeches241.com/?p=22696',
        'Dépêche 241',
        'Éducation, Tourisme, Culture et Arts',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'eac7a766-80e0-490c-9f1e-8e7f79993e2e',
        'Gabon : Oligui Nguema officiellement candidat à la présidentielle',
        'Brice Clotaire Oligui Nguema, actuel président de la transition gabonaise, s’est officiellement déclaré candidat à l’élection présidentielle prévue le 12 avril 2025.',
        'https://www.gabonreview.com/gabon-oligui-nguema-officiellement-candidat-a-la-presidentielle/',
        'Gabon Review',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.254Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f0951661-e4c5-4674-a08c-26b06f36571e',
        'La Setrag ouvre ses portes aux élèves de l’école St Joseph de Calasanz pour une immersion pédagogique',
        'La société Setrag a accueilli des élèves de l’école St Joseph de Calasanz pour une visite éducative à la gare ferroviaire d’Owendo, visant à les sensibiliser aux métiers du rail.',
        'https://www.gabonews.com/fr/actus/education/article/la-setrag-ouvre-ses-portes-aux-eleves-de-l-ecole',
        'Gabonews',
        'Éducation, Services, Numérique / Digital',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.255Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3066b0dd-e7ea-4da5-8d76-ec565efa42f8',
        'Transfert du dossier HPO à la chambre d’accusation: Eddy Minang va-t-il honorer la justice gabonaise ou la souiller comme Bruno ...',
        'L’article analyse le transfert du dossier HPO à la chambre d’accusation et s’interroge sur l’engagement d’Eddy Minang à assurer une justice intègre au Gabon.',
        'https://depeches241.com/?p=22758',
        'Dépêche 241',
        'Autres',
        '2025-03-04T00:00:00.000Z',
        '2025-09-15T23:06:12.255Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

