-- Batch 1 - Section 14/20 (50 articles)

INSERT INTO articles (
  id, title, summary, url, author, category, 
  published_at, created_at, keywords, sentiment_confidence, 
  image_url, ai_summary
) VALUES ,
(
        '307b1152-7f04-4a79-973e-223d47bbc810',
        'JNE : Une célébration sous le signe de l’innovation technologique et de la reconnaissance des éducateurs',
        'La 33e édition de la Journée nationale de l’Enseignant au Gabon a été célébrée à Libreville sous le thème de la valorisation des enseignants à l’ère de l’intelligence artificielle, mettant en avant les innovations technologiques et les reconnaissances envers les éducateurs.',
        'https://www.gabonreview.com/journee-nationale-de-lenseignant-une-celebration-sous-le-signe-de-linnovation-technologique-et-de-la-reconnaissance-des-educateurs/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.350Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '03abd26a-2585-46a1-964e-dc8c365e34de',
        'Pétrole : après Assala Oligui annonce le rachat de Tullow oil',
        'Le président de la transition gabonaise, Brice Clotaire Oligui Nguema, annonce l''acquisition de Tullow Oil Gabon afin d''augmenter la production pétrolière nationale à 82 000 barils par jour.',
        'https://gabonactu.com/blog/2025/03/25/petrole-apres-assala-oligui-annonce-le-rachat-de-tullow-oil/',
        'Gabon Actu',
        'Commerce, Finances, Numérique / Digital',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.350Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6c27bfd8-bdec-4c51-a87c-a11460361044',
        'Canton Anéngué : Renforcer la vision du PDG et inclure les jeunes et les femmes dans le cercle décisionnel, la mission de Charles Otando',
        'Lors de la cérémonie d’installation des nouveaux responsables fédéraux du PDG dans le canton Anéngué, Charles Otando a affirmé la mission de renforcer la vision du parti en intégrant davantage les jeunes et les femmes dans le cercle décisionnel.',
        'https://www.gabonreview.com/canton-anengue-renforcer-la-vision-du-pdg-et-inclure-les-jeunes-et-les-femmes-dans-le-cercle-decisionnel-la-mission-de-charles-otando/',
        'Gabon Review',
        'Éducation, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.350Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1e4254b9-91bd-4637-b750-a7fd22471f8e',
        'Journées de l’Industriel : La Comilog remporte le prix d’Honneur RSE',
        'Lors de la cérémonie des Journées de l’Industriel, la Compagnie minière de l’Ogooué (Comilog) a été distinguée par le prix d’Honneur RSE pour ses efforts exemplaires en responsabilité sociétale et environnementale.',
        'https://gabonactu.com/blog/2025/03/24/journees-de-lindustriel-la-comilog-remporte-le-prix-dhonneur-rse/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation, Agriculture, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1884fdf7-3db9-4ce6-9d84-33daa62fb64d',
        'Aux Journées de l’industriel, la Comilog faite Prix d’honneur RSE',
        'Lors de la troisième édition des Journées de l’Industriel au Gabon, la Compagnie minière de l’Ogooué (Comilog) a été distinguée par le prix d’Honneur RSE pour ses efforts exemplaires en responsabilité sociétale et son rôle dans le développement local et national.',
        'https://www.gabonreview.com/aux-journees-de-lindustriel-la-comilog-faite-prix-dhonneur-rse/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Agriculture, Business Femme, Industrie',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3506f6a9-bed5-4a0b-8a81-eed0801f85c3',
        'Les Sociaux-Démocrates Gabonais (SDG) du Haut-Ogooué apportent leur soutien indéfectible à Brice Clotaire Oligui Nguema',
        'Les Sociaux-Démocrates Gabonais du Haut-Ogooué ont officiellement réaffirmé leur soutien indéfectible à Brice Clotaire Oligui Nguema pour l’élection présidentielle du 12 avril 2025.',
        'https://kongossanews.info/les-sociaux-democrates-gabonais-sdg-du-haut-ogooue-apportent-leur-soutien-indefectible-a-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bce31773-38f0-4299-ad7a-3480288d4077',
        'Gabon : 1 million FCFA d’amende en cas de campagne électorale hors durée légale',
        'À l''approche des élections présidentielles de mars 2025 au Gabon, le Code électoral impose une amende pouvant atteindre 1 million FCFA pour toute campagne menée en dehors de la période légale, et les autorités exhortent les candidats à respecter strictement ces délais pour garantir l’équité électorale.',
        'https://gabonmediatime.com/gabon-1-million-fcfa-damende-en-cas-de-campagne-electorale-hors-duree-legale/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e23054bf-3b03-4b91-9612-122a142ba908',
        'Agriculture : E-tumba propose des solutions et logiciels d’aide à la décision pour les agriculteurs',
        'La startup gabonaise E-Tumba développe des logiciels d’aide à la décision pour les agriculteurs afin d’augmenter la productivité et réduire la dépendance alimentaire du pays.',
        'https://www.gabonreview.com/agriculture-e-tumba-propose-des-solutions-et-logiciels-daide-a-la-decision-pour-les-agriculteurs/',
        'Gabon Review',
        'Numérique / Digital, Agriculture, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd8e7e71a-c33d-48ad-a3bf-a5f38076f36e',
        'Gabon : plus de 90 œuvres d’art restituées par un collectionneur italien',
        'Plus de 90 œuvres d’art gabonaises, longtemps exposées en Europe, ont été restituées par le collectionneur italien Paul Bory et seront prochainement rapatriées au Gabon, illustrant les efforts du gouvernement gabonais pour préserver son patrimoine culturel.',
        'https://gabonmediatime.com/gabon-plus-de-90-oeuvres-dart-restituees-par-un-collectionneur-italien/',
        'Gabon Media Time',
        'Culture, Tourisme, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de9967a2-84b0-4448-a397-6089e1d3119a',
        'Propriété intellectuelle : BOTF-Gabon milite pour un traité international sur les savoirs ancestraux',
        'L’ONG Blessings Of The Forest – Gabon (BOTF-Gabon) a participé à la 50e session de l’OMPI à Genève pour plaider en faveur d’un traité international protégeant les savoirs traditionnels contre la biopiraterie et l’exploitation commerciale non régulée.',
        'https://www.gabonreview.com/propriete-intellectuelle-botf-gabon-milite-pour-un-traite-international-sur-les-savoirs-ancestraux/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services, Finances',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.351Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '268d4dec-4ff5-47c7-a5a0-a8865df7f0dd',
        'Libreville : L’association Colibri appelle à l’engagement citoyen',
        'L’association Colibri, dirigée par Victorine Tchicot, a organisé à Libreville des activités pour promouvoir l’engagement citoyen et recueillir les préoccupations des habitants afin de les intégrer dans le projet présidentiel.',
        'https://gabonmediatime.com/libreville-lassociation-colibri-appelle-a-lengagement-citoyen/',
        'Gabon Media Time',
        'Éducation, Services, Numérique / Digital',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '3b5b91ea-673c-4513-bdb6-f84896539c6e',
        'Assises des jeunes du 2ᵉ arrondissement de Libreville : une jeunesse engagée pour son avenir',
        'La jeunesse du 2ᵉ arrondissement de Libreville s''est engagée lors des Assises des Jeunes 2025 pour identifier et proposer des solutions aux défis locaux en matière d''emploi, d''éducation, d''engagement citoyen et de sécurité.',
        'https://www.gabonreview.com/assises-des-jeunes-du-2%e1%b5%89-arrondissement-de-libreville-une-jeunesse-engagee-pour-son-avenir/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services, Finances, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '77160a3c-eedd-4b87-8afd-c3ae01e2e526',
        'Publié le 25 / 03 / 2025',
        'Le président de la Haute autorité de la Communication a instauré une Commission de 17 membres destinée à garantir un accès équitable des candidats et partis aux médias publics durant la période électorale précédant l’élection présidentielle du 12 avril 2025.',
        'https://union.sonapresse.com/fr/presidentielleacces-des-candidats-aux-medias-publics-la-commission-entre-en-scene',
        'L''Union',
        'Numérique / Digital, Services, Éducation',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7f96d830-d97b-4d7c-9b4f-1b69e47461ff',
        'Les femmes de la Djoué autour de Romina Ngoulakia pour soutenir la candidature d’Oligui Nguema',
        'Les femmes du département de la Djoué, sous la coordination de Romina Ngoulakia, se mobilisent pour soutenir la candidature de Brice Clotaire Oligui Nguema à l''élection présidentielle du 12 avril prochain.',
        'https://www.gabonews.com/fr/actus/politique/article/les-femmes-de-la-djoue-autour-de-romina-ngoulakia',
        'Gabonews',
        'Business Femme, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '9fd726b0-3b08-4d6e-8ee1-2b3c10522941',
        'Kinguélé Aval : AGL Gabon en première ligne avec l’acheminement de 2 transformateurs',
        'Le barrage hydroélectrique de Kinguélé Aval voit AGL Gabon jouer un rôle clé en assurant l’acheminement sécurisé de deux transformateurs essentiels à la production de 35 MW, contribuant ainsi à combler 13 % des besoins énergétiques du Grand Libreville.',
        'https://gabonmediatime.com/kinguele-aval-agl-gabon-en-premiere-ligne-avec-lacheminement-de-2-transformateurs/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '47897f7a-23dd-40c5-8f30-82f99ef114e7',
        'Libreville : la précollecte des déchets enfin encadrée !',
        'La Mairie de Libreville a officialisé la précollecte des déchets en émettant 21 arrêtés, structurant ainsi un secteur informel pour améliorer la gestion des déchets urbains, créer des emplois et favoriser l''insertion professionnelle des précollecteurs.',
        'https://www.gabonreview.com/libreville-la-precollecte-des-dechets-enfin-encadree/',
        'Gabon Review',
        'Numérique / Digital, Services, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.352Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd2176691-fed9-4af3-93b0-002a5d251ebb',
        'Publié le 25 / 03 / 2025',
        'La mairie de Libreville, dirigée par Jude Ibrahim Rapontchombo, lutte principalement contre les difficultés de recouvrement financier causées par la parafiscalité et la corruption en mettant en œuvre des réformes administratives et technologiques.',
        'https://union.sonapresse.com/fr/mairie-de-libreville-le-recouvrement-financier-comme-principal-ecueil',
        'L''Union',
        'Numérique / Digital, Services, Finances',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '09acffe9-0530-4528-9170-005e7dc4a632',
        'Présidentielle 2025 : le RdB lance sa campagne d’adhésion en Nzeng-Ayong',
        'Le Rassemblement des Bâtisseurs a lancé sa campagne d’adhésion populaire à Nzeng-Ayong pour mobiliser et élargir sa base militante en vue des élections présidentielles de 2025.',
        'https://gabonmediatime.com/presidentielle-2025-le-rdb-lance-sa-campagne-dadhesion-en-nzeng-ayong/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '5869d99d-2780-49e8-8cab-2deaf8b45da9',
        'SETRAG : Avis d’Appel d’Offres (AAOI) 13-03-25-AFD/SET',
        'L''État gabonais, soutenu par l''Agence Française de Développement, lance un appel d’offres pour le confortement des talus sur six sites du chemin de fer Transgabonais, supervisé par la Société d’Exploitation du Transgabonais (SETRAG).',
        'https://www.gabonreview.com/setrag-avis-dappel-doffres-aaoi-13-03-25-afd-set/',
        'Gabon Review',
        'Services, Commerce, Éducation, Agriculture',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '0b3ae434-cf0a-476c-a279-6291615ce5af',
        'Publié le 24 / 03 / 2025',
        'Les sages du Haut-Ogooué réaffirment leur soutien à Brice Clotaire Oligui Nguema, louant son bilan positif durant la transition et appelant les populations à soutenir sa candidature aux prochaines élections.',
        'https://union.sonapresse.com/fr/les-sages-altogoveens-appellent-voter-le-batisseur-en-chef',
        'L''Union',
        'Autres',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '85b26034-a375-4597-aa63-8b96555451fe',
        'Lambaréné : le lycée Charle Méfane remporte tous les prix de la 3ème édition du Mag’edo et du challenge Zohra Ndong Mba',
        'Le lycée Charles Méfane de Lambaréné a remporté tous les prix de la troisième édition du Mag’Edo et du Challenge Zohra Ndong Mba, mettant en valeur l''importance du sport pour la cohésion et le développement des jeunes de la province du Moyen Ogooué.',
        'https://www.gabonews.com/fr/actus/societe/article/lambarene-le-lycee-charle-mefane-remporte-tous',
        'Gabonews',
        'Éducation, Services, Tourisme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '16517093-7e50-44e8-8f13-02602b92c43d',
        'Un collectionneur privé italien restitue 90 objets d’art au Gabon',
        'Un collectionneur privé italien a offert au gouvernement gabonais 90 objets d’art culturel, incluant des masques et des reliques, acquis au cours de plusieurs décennies passées au Gabon.',
        'https://www.gabonreview.com/un-collectionneur-prive-italien-restitue-90-objets-dart-au-gabon/',
        'Gabon Review',
        'Culture, Tourisme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a583d84c-14e8-40a8-8d14-1e6e1c1b62c9',
        'L’Implication de l’Intelligence Artificielle dans la Finance Publique',
        'À l’ère numérique, l’intelligence artificielle offre au Gabon une opportunité stratégique pour moderniser la gestion des finances publiques en optimisant les ressources, améliorant la transparence et renforçant l’efficacité administrative, tout en devant surmonter des défis techniques, éthiques et d’intégration.',
        'https://www.gabonreview.com/limplication-de-lintelligence-artificielle-dans-la-finance-publique/',
        'Gabon Review',
        'Numérique / Digital, Finances, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.353Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6f388a81-8620-48a6-98e0-1cf721211380',
        'L’Université Internationale de Libreville – Berthe & Jean célèbre une décennie d’innovation et de rayonnement académique',
        'L’Université Internationale de Libreville – Berthe & Jean a célébré son dixième anniversaire, marquant une décennie d’innovation et de rayonnement académique au Gabon.',
        'https://www.gabonews.com/fr/actus/enseignement-superieur/article/l-universite-internationale-de-libreville-berthe',
        'Gabonews',
        'Éducation, Numérique / Digital',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.354Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'fe96cd55-ea58-4f2d-9a2a-a7878c6a63ec',
        'Gayver Mouengui : Un modèle d’entrepreneuriat et de promotion de l’employabilité au Gabon',
        'Gayver Mouengui, jeune entrepreneur gabonais de 30 ans, est reconnu comme un modèle d’entrepreneuriat et de promotion de l’employabilité au Gabon grâce à sa société Relium Network qui prépare efficacement les candidats à intégrer le marché du travail.',
        'https://kongossanews.info/gayver-mouengui-un-modele-dentrepreneuriat-et-de-promotion-de-lemployabilite-au-gabon/',
        'Kongossa News',
        'Éducation, Services, Numérique / Digital, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.354Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'bb7102f7-5f8a-4a9b-9f37-0c6642222630',
        'SETRAG : Avis d’Appel d’Offres National (AAON) 17-03-25-AFD/SET',
        'L’État gabonais, via la SETRAG et avec le soutien de l’AFD, lance un appel d’offres national pour raccorder 28 passages à niveau du chemin de fer Transgabonais à la fibre optique du Backbone Gabonais dans le cadre de sa réhabilitation.',
        'https://www.gabonreview.com/setrag-avis-dappel-doffres-national-aaon-17-03-25-afd-set/',
        'Gabon Review',
        'Numérique / Digital, Services, Commerce',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.354Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e480f69b-1b21-4b12-ab21-6cbba6fd46aa',
        'Gabon-PNUD : Aissata Dé réaffirme l’engagement du PNUD à accompagner le Gabon',
        'Aissata Dé, directrice adjointe du PNUD Afrique, a réaffirmé lors d''une rencontre avec le vice-premier ministre gabonais l''engagement du PNUD à accompagner le Gabon dans ses efforts de développement et de transition politique.',
        'https://www.gabonreview.com/gabon-pnud-aissata-de-reaffirme-lengagement-du-pnud-a-accompagner-le-gabon/',
        'Gabon Review',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.354Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'f59840a5-79ea-4450-b298-5f2474fdc259',
        'Rassemblement des bâtisseurs: Le Woleu-Ntem s’unit derrière Brice-Clotaire Oligui Nguema',
        'Le Woleu-Ntem s''est massivement mobilisé au Palais Omar Bongo Ondimba pour soutenir Brice-Clotaire Oligui Nguema et le Rassemblement des Bâtisseurs en vue des prochaines élections présidentielles.',
        'https://kongossanews.info/rassemblement-des-batisseurs-le-woleu-ntem-sunit-derriere-brice-clotaire-oligui-nguema/',
        'Kongossa News',
        'Autres',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.354Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2493b2a6-942b-442c-a3a8-a591e807a127',
        'Au seuil de la présidentielle : La même dérive',
        'À l''approche des élections présidentielles de 2025, l''article dénonce la campagne de Brice Clotaire Oligui Nguema pour sa confusion persistante entre intérêts personnels et publics, similaire aux dérives observées sous les précédents dirigeants gabonais.',
        'https://www.gabonreview.com/au-seuil-de-la-presidentielle-la-meme-derive/',
        'Gabon Review',
        'Autres',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.355Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '60f0887c-73a6-4eb9-9b27-54c7c8243a08',
        'Kinguélé Aval : Le ministre de l’Énergie inspecte les transformateurs du barrage',
        'Le ministre de l’Énergie, Séraphin Akure-Davain, a inspecté les transformateurs du barrage hydroélectrique de Kinguélé Aval, un projet clé visant à fournir 35 MW et couvrir 13 % des besoins énergétiques du Grand Libreville, essentiel pour la transition énergétique du Gabon.',
        'https://www.gabonreview.com/kinguele-aval-le-ministre-de-lenergie-inspecte-les-transformateurs-du-barrage/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Commerce, Éducation, Agriculture',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.355Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '909fcb14-2c43-4bcb-b89f-ab6de5dd039a',
        'Journée nationale de l’enseignant : des annonces fortes pour valoriser le corps enseignant au Gabon',
        'Lors de la 33ᵉ Journée nationale de l’enseignant au Gabon, le président Brice Clotaire Oligui Nguema a annoncé des mesures inédites pour valoriser le corps enseignant, incluant la création de postes budgétaires, des primes d’éloignement, la réhabilitation des infrastructures scolaires et la possibilité de convertir les rappels de solde en terrains lotis.',
        'https://kongossanews.info/journee-nationale-de-lenseignant-des-annonces-fortes-pour-valoriser-le-corps-enseignant-au-gabon/',
        'Kongossa News',
        'Éducation, Numérique / Digital, Services, Finances',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.355Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'de838965-3399-4e87-84fd-c957496d5c52',
        'Rachat de Tullow Oil : La GOC remporte la bataille face à Perenco pour 182 milliards de FCFA',
        'La Gabon Oil Company (GOC) a acquis les actifs gabonais de Tullow Oil pour 182 milliards de FCFA, remportant ainsi la bataille face à Perenco.',
        'https://directinfosgabon.com/rachat-de-tullow-oil-la-goc-remporte-la-bataille-face-a-perenco-pour-182-milliards-de-fcfa/',
        'Direct infos Gabon',
        'Industrie Pétrolière, Finances, Services',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.355Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '6090238a-b7ba-4067-954d-5ecf967d1679',
        'Présidentielle du 12 avril : Oligui Nguema en duel contre des adversaires… invisibles ?',
        'Le candidat présidentiel Brice Clotaire Oligui Nguema affirme ne pas avoir d’adversaires politiques, se concentrant plutôt sur la lutte contre le chômage des jeunes, la vie chère et les infrastructures défaillantes lors de la présidentielle du 12 avril 2025.',
        'https://www.gabonreview.com/presidentielle-du-12-avril-oligui-nguema-en-duel-contre-des-adversaires-invisibles/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-25T00:00:00.000Z',
        '2025-09-15T23:06:12.355Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1eeb813f-2b22-4f60-8029-f095b26aa01c',
        '« Gabon Immortel », une plateforme pour faire triompher le candidat Oligui Nguema au prochain scrutin présidentiel',
        'L’article présente « Gabon Immortel », une plateforme associative visant à soutenir activement Brice Clotaire Oligui Nguema dans sa candidature pour l’élection présidentielle gabonaise d’avril 2025.',
        'https://gabonactu.com/blog/2025/03/25/gabon-immortel-une-plateforme-pour-faire-triompher-le-candidat-oligui-nguema-au-prochain-scrutin-presidentiel/',
        'Gabon Actu',
        'Numérique / Digital, Services, Éducation, Business Femme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.356Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd02151aa-fc8e-4d3a-95b5-073bd372922d',
        'Gabon : Les 10 mesures d’Oligui pour dynamiser le climat des affaires',
        'Le président de la Transition gabonaise, Brice Clotaire Oligui Nguema, a dévoilé dix mesures stratégiques visant à améliorer le climat des affaires au Gabon, incluant la maîtrise des dépenses publiques, la simplification administrative, une fiscalité plus attractive, la digitalisation de l’administration, le renforcement de la protection judiciaire des entreprises, un meilleur accès au financement, l’amélioration de l’éducation et de la formation, la gestion optimisée de la dette publique, une politique de stabilité macroéconomique, et l’instauration d’un cadre permanent de concertation avec le secteur privé.',
        'https://directinfosgabon.com/gabon-les-10-mesures-doligui-pour-dynamiser-le-climat-des-affaires/',
        'Direct infos Gabon',
        'Numérique / Digital, Services, Finances, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.356Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'c81e0ee8-c653-411d-bb78-12f6a3c5c2f2',
        'Soudan : Une frappe aérienne de l’armée sur un marché du Darfour-Nord fait des centaines de victimes civiles',
        'Une frappe aérienne de l’armée soudanaise sur un marché de Tora, dans le Darfour-Nord, aurait tué des centaines de civils, selon un collectif d’avocats pro-démocratie.',
        'https://www.gabonreview.com/soudan-une-frappe-aerienne-de-larmee-sur-un-marche-du-darfour-nord-fait-des-centaines-de-victimes-civiles/',
        'Gabon Review',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.356Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '8abd5628-1ef6-4cae-b3fb-e9656e1e187a',
        'Pétrole : le Gabon a racheté Tullow oil à 181 milliards de FCFA (officiel)',
        'L''État gabonais a racheté les actifs pétroliers de Tullow Oil pour 181 milliards de FCFA, augmentant ainsi la production nationale à 82 000 barils par jour.',
        'https://gabonactu.com/blog/2025/03/25/petrole-le-gabon-a-rachete-tullow-oil-a-181-milliards-de-fcfa-officiel/',
        'Gabon Actu',
        'Commerce, Finances, Numérique / Digital',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.356Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '36592a78-c4dc-49e2-8b7c-8089f5b61e47',
        'Rassemblement des Bâtisseurs : L’appel du Dr Yvon Brice Etoughe Mebiame pour une adhésion massive des Port-Gentillais',
        'Le Dr Yvon Brice Etoughe Mebiame appelle massivement les Port-Gentillais à adhérer au Rassemblement des Bâtisseurs pour soutenir le développement du Gabon sous la gouvernance actuelle.',
        'https://www.gabonreview.com/rassemblement-des-batisseurs-lappel-du-dr-yvon-brice-etoughe-mebiame-pour-une-adhesion-massive-des-port-gentillais/',
        'Gabon Review',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.356Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '31bc99a1-b743-48cc-87d7-353a17ab0c12',
        'Crédit bancaire : Le Cameroun et le Gabon leaders en zone CEMAC',
        'Un rapport de la BEAC révèle que le Cameroun et le Gabon dominent le marché du crédit bancaire en zone CEMAC en captant plus de 80 % des nouveaux crédits octroyés jusqu’à septembre 2024, soulignant ainsi leur prédominance économique dans la sous-région.',
        'https://directinfosgabon.com/credit-bancaire-le-cameroun-et-le-gabon-leaders-en-zone-cemac/',
        'Direct infos Gabon',
        'Finances, Numérique / Digital',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.357Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'e12d6a93-8a74-4f7b-94b2-8d2ed254bf91',
        'Mine : vers l’exploitation de la mine de Baniaka',
        'Le Président de la Transition gabonaise a signé un accord avec REMINAC pour exploiter la mine de Baniaka, promising de dynamiser l’économie locale, créer des emplois et développer des infrastructures durables.',
        'https://mediapostegabon.com/mine-vers-lexploitation-de-la-mine-de-baniaka/',
        'Media Poste Gabon',
        'Numérique / Digital, Services, Agriculture, Finances',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.357Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7d9d13db-c66f-4180-9e02-e131e255e24b',
        'Port-Gentil : Féfé Onanga mobilise la jeunesse contre l’abstention',
        'Féfé Onanga mobilise activement la jeunesse de Port-Gentil pour qu''elle participe aux élections présidentielles de 2025 en soutenant Brice Clotaire Oligui Nguema et en luttant contre l’abstention.',
        'https://www.gabonreview.com/port-gentil-fefe-onanga-mobilise-la-jeunesse-contre-labstention/',
        'Gabon Review',
        'Numérique / Digital, Éducation, Services, Business Femme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.357Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'd405b80f-5ca0-44a9-a3bd-749f61256bb7',
        'Présidentielle 2025 : à Ndendé, Mbil ba Ghétu appelle à soutenir Oligui Nguema Au Gabon, la Diaspora gabonaise s’implique à la v...',
        'L''association "Mbil ba Ghétu" à Ndendé a officiellement annoncé son soutien inconditionnel à Brice Clotaire Oligui Nguema pour l''élection présidentielle de 2025.',
        'https://mediapostegabon.com/presidentielle-2025-a-ndende-mbil-ba-ghetu-appelle-a-soutenir-oligui-nguema/',
        'Media Poste Gabon',
        'Numérique / Digital, Services, Business Femme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.358Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'ca5e3d53-4b4c-48a6-b5a8-c4904a973294',
        'Projet de coexistence pacifique : une nouvelle stratégie pour mieux cohabiter avec les éléphants',
        'Un projet de coexistence pacifique entre les humains et les éléphants a été inauguré à Cocobeach, visant à réduire les conflits grâce à l''installation de barrières électriques, l''amélioration agricole, la sensibilisation des populations et la mise en place d''un mécanisme d''assurance.',
        'https://www.gabonreview.com/projet-de-coexistence-pacifique-une-nouvelle-strategie-pour-mieux-cohabiter-avec-les-elephants/',
        'Gabon Review',
        'Numérique / Digital, Services, Agriculture, Finances',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.358Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '2595b1d2-69ab-4e56-bb17-ae013c33dd5d',
        'Transports terrestres : Jonathan Ignoumba accusé de freiner la modernisation initiée par son prédécesseur',
        'Jonathan Ignoumba, nouveau ministre des Transports au Gabon, est accusé de ralentir les réformes de modernisation initiées par son prédécesseur, compromettant ainsi le développement du secteur des transports terrestres.',
        'https://kongossanews.info/transports-terrestres-jonathan-ignoumba-accuse-de-freiner-la-modernisation-initiee-par-son-predecesseur/',
        'Kongossa News',
        'Numérique / Digital, Services, Finances, Éducation, Commerce, Tourisme',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.358Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'a38d846c-738f-4438-9cbf-e1d078be11bf',
        'CIMAF Gabon renforce sa production de ciment au Gabon',
        'CIMAF Gabon renforce sa production de ciment en signant un accord d’investissement avec le gouvernement pour ajouter une troisième ligne de production d’un million de tonnes par an et prévoit la construction d’une unité de clinker afin d’atteindre l’autosuffisance industrielle.',
        'https://www.gabonreview.com/cimaf-gabon-renforce-sa-production-de-ciment-au-gabon/',
        'Gabon Review',
        'Services, Agriculture, Commerce',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.358Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cfbd8e86-b2db-4d9f-8554-4db7d608271f',
        'Présidentielle 2025 : le PDG au cœur de la coordination de campagne d’Oligui Nguema',
        'Le PDG joue un rôle central dans la coordination de la campagne présidentielle de Brice Clotaire Oligui Nguema pour les élections de 2025.',
        'https://gabonmediatime.com/presidentielle-2025-le-pdg-au-coeur-de-la-coordination-de-campagne-doligui-nguema/',
        'Gabon Media Time',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.358Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        'cd766fbd-56ca-4d80-91ad-dfc376efbad4',
        'François Didier Douneni élu président de l’association Liyibou Fraternité',
        'François Didier Douneni a été élu président de l’association apolitique et à but non lucratif Liyibou Fraternité lors de son assemblée générale extraordinaire à Libreville, avec pour mission de promouvoir l’unité et le développement de la région de Liyibou.',
        'https://kongossanews.info/francois-didier-douneni-elu-president-de-lassociation-liyibou-fraternite/',
        'Kongossa News',
        'Services, Éducation, Agriculture',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '7a2e0f8c-9fd4-43db-8d7b-2a51e07d494f',
        'Port-Gentil : Engagement des Volontaires du Oui en faveur de Brice Clotaire Oligui Nguema',
        'La coordination des Volontaires du Oui de Port-Gentil s’engage à soutenir la candidature de Brice Clotaire Oligui Nguema pour l’élection présidentielle de 2025 au Gabon.',
        'https://www.gabonreview.com/port-gentil-engagement-des-volontaires-du-oui-en-faveur-de-brice-clotaire-oligui-nguema/',
        'Gabon Review',
        'Autres',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '1225ba21-6ff1-47b2-85f7-ccc2dace5e18',
        'Gabon : Ndong Sima sonne l’heure de l’évaluation au sein de l’administration publique',
        'Le Premier ministre gabonais Raymond Ndong Sima a lancé une évaluation de l’administration publique en exigeant la présentation de rapports sur les systèmes d’évaluation et de notation des agents publics.',
        'https://gabonmediatime.com/gabon-ndong-sima-sonne-lheure-de-levaluation-au-sein-de-ladministration-publique/',
        'Gabon Media Time',
        'Numérique / Digital, Services, Éducation',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      ),
,
(
        '27ad8d09-2da6-4f26-b0d5-dc123074d755',
        'Tullow Oil cède ses actifs gabonais à Gabon Oil Company pour 300 millions de dollars',
        'L''État gabonais, par le biais de Gabon Oil Company, a acquis les actifs pétroliers de Tullow Oil au Gabon pour 300 millions de dollars, renforçant ainsi la renationalisation des ressources naturelles du pays.',
        'https://www.gabonreview.com/tullow-oil-cede-ses-actifs-gabonais-a-gabon-oil-company-pour-300-millions-de-dollars/',
        'Gabon Review',
        'Numérique / Digital, Services, Finances, Agriculture',
        '2025-03-26T00:00:00.000Z',
        '2025-09-15T23:06:12.359Z',
        '{}',
        0.5,
        null,
        null
      )
ON CONFLICT (id) DO NOTHING;

